var searchData=
[
  ['paramnames_2epy',['paramnames.py',['../paramnames_8py.html',1,'']]],
  ['parampriors_2epy',['parampriors.py',['../parampriors_8py.html',1,'']]],
  ['paramset_2ef90',['ParamSet.f90',['../ParamSet_8f90.html',1,'']]],
  ['planck_5fdatasets_5f1d_2epy',['planck_datasets_1d.py',['../planck__datasets__1d_8py.html',1,'']]],
  ['planckstyle_2epy',['planckStyle.py',['../planckStyle_8py.html',1,'']]],
  ['plik_5fpostprocess_2epy',['plik_postprocess.py',['../plik__postprocess_8py.html',1,'']]],
  ['plikparams_2epy',['plikParams.py',['../plikParams_8py.html',1,'']]],
  ['plot_5fdirective_2epy',['plot_directive.py',['../plot__directive_8py.html',1,'']]],
  ['plotcls_2em',['plotcls.m',['../plotcls_8m.html',1,'']]],
  ['plotdiffs_2em',['plotdiffs.m',['../plotdiffs_8m.html',1,'']]],
  ['plotpk_2em',['plotpk.m',['../plotpk_8m.html',1,'']]],
  ['plots_2epy',['plots.py',['../plots_8py.html',1,'']]],
  ['plottt_2em',['plotTT.m',['../plotTT_8m.html',1,'']]],
  ['pol_5fcompare_2epy',['pol_compare.py',['../pol__compare_8py.html',1,'']]],
  ['pol_5ftriangle_2epy',['pol_triangle.py',['../pol__triangle_8py.html',1,'']]],
  ['powellconstrainedminimize_2ef90',['PowellConstrainedMinimize.f90',['../PowellConstrainedMinimize_8f90.html',1,'']]],
  ['power_5ftilt_2ef90',['power_tilt.f90',['../power__tilt_8f90.html',1,'']]],
  ['propose_2ef90',['propose.f90',['../propose_8f90.html',1,'']]]
];
