cosmomc_bde_v3p1: getdist.types.NumberFormatter Class Reference
getdist.types.NumberFormatter Class Reference
Public Member Functions
def __init__ (self, sig_figs=4, separate_limit_tol=0.1)
def namesigFigs (self, value, limplus, limminus, wantSign=True)
def formatNumber (self, value, sig_figs=None, wantSign=False)
def decimal_places (self, s)
def plusMinusLimit (self, limit, upper, lower)
Public Attributes
sig_figs
separate_limit_tol
Constructor & Destructor Documentation
__init__()
def getdist.types.NumberFormatter.__init__ (self, sig_figs = 4, separate_limit_tol = 0.1)
Member Function Documentation
decimal_places()
def getdist.types.NumberFormatter.decimal_places (self, s)
Referenced by getdist.types.NumberFormatter.namesigFigs().
formatNumber()
def getdist.types.NumberFormatter.formatNumber (self, value, sig_figs = None, wantSign = False)
References CAMB_test_files.float, getdist.types.numberFigs(), and getdist.types.NumberFormatter.sig_figs.
Referenced by getdist.types.NumberFormatter.namesigFigs().
namesigFigs()
def getdist.types.NumberFormatter.namesigFigs (self, value, limplus, limminus, wantSign = True)
References getdist.types.NumberFormatter.decimal_places(), CAMB_test_files.float, getdist.types.NumberFormatter.formatNumber(), and getdist.types.NumberFormatter.sig_figs.
plusMinusLimit()
def getdist.types.NumberFormatter.plusMinusLimit (self, limit, upper, lower)
References getdist.types.NumberFormatter.separate_limit_tol.
Member Data Documentation
separate_limit_tol
getdist.types.NumberFormatter.separate_limit_tol
Referenced by getdist.types.NumberFormatter.plusMinusLimit().
sig_figs
getdist.types.NumberFormatter.sig_figs
Referenced by getdist.types.NumberFormatter.formatNumber(), and getdist.types.NumberFormatter.namesigFigs().
The documentation for this class was generated from the following file:
/home/ealmaraz/software/cosmomc/bde/v3.1/python/getdist/types.py