cosmomc_bde_v3p1: camb.camb.CAMBdata Class Reference
camb.camb.CAMBdata Class Reference
Public Member Functions
def __init__ (self)
def __enter__ (self)
def __exit__ (self, exc_type, exc_value, traceback)
def __del__ (self)
def free (self)
def set_params (self, params)
def get_params (self)
def get_derived_params (self)
def get_background_outputs (self)
def get_BAO (self, redshifts, params)
def calc_background_no_thermo (self, params)
def calc_background (self, params)
def calc_transfers (self, params, only_transfers=True)
def calc_power_spectra (self, params=None)
def power_spectra_from_transfer (self, initial_power_params)
def get_cmb_power_spectra (self, params=None, lmax=None, spectra=['total', unlensed_scalar, unlensed_total, lensed_scalar, tensor, lens_potential)
def get_cmb_transfer_data (self, tp='scalar')
def get_time_evolution (self, q, eta, vars=model.evolve_names, lAccuracyBoost=4)
def get_redshift_evolution (self, q, z, vars=model.evolve_names, lAccuracyBoost=4)
def get_background_time_evolution (self, eta, vars=model.background_names, format='dict')
def get_background_redshift_evolution (self, z, vars=model.background_names, format='dict')
def get_matter_transfer_data (self)
def get_linear_matter_power_spectrum (self, var1=None, var2=None, hubble_units=True, have_power_spectra=False, params=None, nonlinear=False)
def get_nonlinear_matter_power_spectrum (self, kwargs)
def get_sigma8 (self)
def get_matter_power_spectrum (self, minkh=1e-4, maxkh=1.0, npoints=100, var1=None, var2=None, have_power_spectra=False, params=None)
def get_total_cls (self, lmax)
def get_tensor_cls (self, lmax)
def get_unlensed_scalar_cls (self, lmax)
def get_unlensed_total_cls (self, lmax)
def get_lensed_scalar_cls (self, lmax)
def get_lens_potential_cls (self, lmax)
def get_unlensed_scalar_array_cls (self, lmax)
def angular_diameter_distance (self, z)
def angular_diameter_distance2 (self, z1, z2)
def comoving_radial_distance (self, z)
def redshift_at_comoving_radial_distance (self, chi, nz_step=150, zmax=10000)
def luminosity_distance (self, z)
def h_of_z (self, z)
def hubble_parameter (self, z)
def physical_time_a1_a2 (self, a1, a2)
def physical_time (self, z)
def conformal_time_a1_a2 (self, a1, a2)
def conformal_time (self, z)
def cosmomc_theta (self)
Public Attributes
Params
Private Member Functions
def _transfer_var (self, var1, var2)
Private Attributes
_key
_one
Detailed Description
An object for storing transfer function data and parameters for CAMB.
Not that it *only* stores transfer functions. If you want to get power spectra or background functions,
you must have called one of the calculation functions for the parameters of interest more recently than
any other call to these functions. You can can make multiple instances of CAMBdata and then later call
`power_spectra_from_transfer` to calculate other quantities.
To quickly make a fully calculated CAMBdata instance for a set of parameters you can call :func:`get_results`.
:ivar Params: the :class:`.model.CAMBparams` parameters being used
Constructor & Destructor Documentation
__init__()
def camb.camb.CAMBdata.__init__ (self)
__del__()
def camb.camb.CAMBdata.__del__ (self)
References camb.camb.CAMBdata.free().
Member Function Documentation
__enter__()
def camb.camb.CAMBdata.__enter__ (self)
__exit__()
def camb.camb.CAMBdata.__exit__ (self, exc_type, exc_value, traceback)
References camb.camb.CAMBdata.free().
_transfer_var()
def camb.camb.CAMBdata._transfer_var (self, var1, var2) private
References camb.camb.CAMBdata.get_linear_matter_power_spectrum().
Referenced by camb.camb.CAMBdata.get_linear_matter_power_spectrum(), and camb.camb.CAMBdata.get_matter_power_spectrum().
angular_diameter_distance()
def camb.camb.CAMBdata.angular_diameter_distance (self, z)
Get (non-comoving) angular diameter distance to redshift z.
Must have called calc_background, calc_background_no_thermo or calculated transfer functions or power spectra.
:param z: redshift or array of redshifts
:return: angular diameter distances, matching rank of z
References camb.camb.AngularDiameterDistance, camb.camb.AngularDiameterDistanceArr, and camb.camb.c_double.
Referenced by camb.camb.CAMBdata.luminosity_distance().
angular_diameter_distance2()
def camb.camb.CAMBdata.angular_diameter_distance2 (self, z1, z2)
Get angular diameter distance between two redshifts
[r/(1+z2)]*sin_K([chi(z_1) - chi(z_1)]/r) where r is curvature radius and chi is the comoving radial distance
Must have called calc_background, calc_background_no_thermo or calculated transfer functions or power spectra.
:param z1: redshift 1
:param z2: redshift 2
:return: result
References camb.camb.AngularDiameterDistance2, and camb.camb.c_double.
calc_background()
def camb.camb.CAMBdata.calc_background (self, params)
Calculate the background evolution and thermal history.
e.g. call this if you want to get derived parameters and call background functions
:param params:  :class:`.model.CAMBparams` instance to use
References camb.camb.CAMBdata._key, and camb.camb.CAMB_CalcBackgroundTheory.
Referenced by camb.camb.CAMBdata.get_BAO().
calc_background_no_thermo()
def camb.camb.CAMBdata.calc_background_no_thermo (self, params)
Calculate the background evolution without calculating thermal history.
e.g. call this if you want to just use `angular_diameter_distance` and similar background functions
:param params:  :class:`.model.CAMBparams` instance to use
References camb.camb.CAMBdata._key, and camb.camb.CAMB_SetParamsForBackground.
calc_power_spectra()
def camb.camb.CAMBdata.calc_power_spectra (self, params = None)
Calculates transfer functions and power spectra.
:param params: optional :class:`.model.CAMBparams` instance with parameters to use
References camb.camb.CAMBdata._key, camb.camb.CAMBdata.calc_transfers(), and camb.camb.CAMBdata_transferstopowers.
Referenced by camb.camb.CAMBdata.get_cmb_power_spectra(), camb.camb.CAMBdata.get_linear_matter_power_spectrum(), and camb.camb.CAMBdata.get_matter_power_spectrum().
calc_transfers()
def camb.camb.CAMBdata.calc_transfers (self, params, only_transfers = True)
Calculate the transfer functions (for CMB and matter power, as determined by params.WantCls, params.WantTransfer)
:param params: :class:`.model.CAMBparams` instance with parameters to use
:param only_transfers: only calculate transfer functions, no power spectra
:return: non-zero if error, zero if OK
References camb.camb.CAMBdata._key, and camb.camb.CAMBdata_gettransfers.
Referenced by camb.camb.CAMBdata.calc_power_spectra().
comoving_radial_distance()
def camb.camb.CAMBdata.comoving_radial_distance (self, z)
Get comoving radial distance from us to redshift z in Mpc
Must have called calc_background, calc_background_no_thermo or calculated transfer functions or power spectra.
:param z: redshift
:return: comoving radial distance (Mpc)
References camb.camb.c_double, camb.camb.ComovingRadialDistance, and camb.camb.CAMBdata.conformal_time().
conformal_time()
def camb.camb.CAMBdata.conformal_time (self, z)
Conformal time from hot big bang to redshift z in Megaparsec.
:param z: redshift or array of redshifts
:return: eta(z)/Mpc
References camb.camb.TimeOfzArr.
Referenced by camb.camb.CAMBdata.comoving_radial_distance(), camb.camb.CAMBdata.get_background_redshift_evolution(), camb.camb.CAMBdata.get_redshift_evolution(), and camb.camb.CAMBdata.redshift_at_comoving_radial_distance().
conformal_time_a1_a2()
def camb.camb.CAMBdata.conformal_time_a1_a2 (self, a1, a2)
Get conformal time between two scale factors (=comoving radial distance travelled by light on light cone)
:param a1: scale factor 1
:param a2: scale factor 2
:return: eta(a2)-eta(a1) = chi(a1)-chi(a2) in Megaparsec
References camb.camb.c_double, and camb.camb.DeltaTime.
cosmomc_theta()
def camb.camb.CAMBdata.cosmomc_theta (self)
Get theta_MC, an approximation of the radio of the sound horizon to the angular diameter distance at recombination.
:return: theta_MC
References camb.camb.CosmomcTheta.
free()
def camb.camb.CAMBdata.free (self)
References camb.camb.CAMBdata._key, and camb.camb.CAMBdata_free.
Referenced by camb.camb.CAMBdata.__del__(), and camb.camb.CAMBdata.__exit__().
get_background_outputs()
def camb.camb.CAMBdata.get_background_outputs (self)
Get BAO values for redshifts (set redshifts using 'set_z_outputs')
:return: rs/DV, H, DA, F_AP for each requested redshift (as 2D array)
References camb.camb.CAMB_GetBackgroundOutputs, and camb.camb.CAMB_GetNumBackgroundOutputs.
Referenced by camb.camb.CAMBdata.get_BAO().
get_background_redshift_evolution()
def camb.camb.CAMBdata.get_background_redshift_evolution (self, z, vars = model.background_names, format = 'dict')
Get the evolution of background variables a function of redshift.
For the moment a and H are rather perversely only available via :meth:`get_time_evolution`
:param eta: array of requested conformal times to output
:param vars: list of variable names to output
:param format: 'dict' or 'array', for either dict of 1D arrays indexed by name, or 2D array
:return: n_eta x len(vars) 2D numpy array of outputs or dict of 1D arrays
References camb.camb.CAMBdata.conformal_time(), and camb.camb.CAMBdata.get_background_time_evolution().
get_background_time_evolution()
def camb.camb.CAMBdata.get_background_time_evolution (self, eta, vars = model.background_names, format = 'dict')
Get the evolution of background variables a function of conformal time.
For the moment a and H are rather perversely only available via :meth:`get_time_evolution`
:param eta: array of requested conformal times to output
:param vars: list of variable names to output
:param format: 'dict' or 'array', for either dict of 1D arrays indexed by name, or 2D array
:return: n_eta x len(vars) 2D numpy array of outputs or dict of 1D arrays
References camb.camb.CAMB_BackgroundEvolution, set(), and copyGridFiles.zip.
Referenced by camb.camb.CAMBdata.get_background_redshift_evolution().
get_BAO()
def camb.camb.CAMBdata.get_BAO (self, redshifts, params)
Get BAO parameters at given redshifts, using parameters in params
:param redshifts: list of redshifts
:param params: optional :class:`.model.CAMBparams` instance to use
:return: array of rs/DV, H, DA, F_AP for each redshift as 2D array
References camb.camb.CAMBdata.calc_background(), camb.camb.CAMBdata.get_background_outputs(), and camb.camb.set_z_outputs().
get_cmb_power_spectra()
def camb.camb.CAMBdata.get_cmb_power_spectra (self, params = None, lmax = None, spectra = ['total', unlensed_scalar, unlensed_total, lensed_scalar, tensor, lens_potential)
Get CMB power spectra, as requested by the 'spectra' argument. All power spectra are l(l+1)C_l/2pi self-owned
numpy arrays (0..lmax, 0..3), where 0..3 index are TT, EE, BB TT.
:param params: optional :class:`.model.CAMBparams` instance with parameters to use. If None, must have
  previously set parameters and called `calc_power_spectra` (e.g. if you got this instance using `camb.get_results`),
:param lmax: maximum l
:param spectra: list of names of spectra to get
:return: dictionary of power spectrum arrays, indexed by names of requested spectra
References camb.camb.CAMBdata.calc_power_spectra(), and camb.camb.CAMBdata.Params.
Referenced by camb.camb.CAMBdata.power_spectra_from_transfer().
get_cmb_transfer_data()
def camb.camb.CAMBdata.get_cmb_transfer_data (self, tp = 'scalar')
Get C_l transfer functions
:return: class:`.ClTransferData` instance holding output arrays (copies, not pointers)
References camb.camb.CAMBdata._key, camb.camb.CAMBdata_cltransferdata, camb.camb.fortran_array(), and chainPeek.index.
get_derived_params()
def camb.camb.CAMBdata.get_derived_params (self)
:return: dictionary of derived parameter values, indexed by name ('kd', 'age', etc..)
References copyGridFiles.zip.
get_lens_potential_cls()
def camb.camb.CAMBdata.get_lens_potential_cls (self, lmax)
Get lensing deflection angle potential power spectrum, and cross-correlation with T and E. Must have already calculated power spectra.
Power spectra are [l(l+1)]^2C_l^{phi phi}/2/pi and corresponding deflection cross-correlations.
:param lmax: lmax to output to
:return: numpy array CL[0:lmax+1,0:3], where 0..2 indexes PP, PT, PE.
References camb.camb.CAMBdata._one, and camb.camb.CAMB_SetLensPotentialCls.
get_lensed_scalar_cls()
def camb.camb.CAMBdata.get_lensed_scalar_cls (self, lmax)
Get lensed scalar CMB power spectra. Must have already calculated power spectra.
:param lmax: lmax to output to
:return: numpy array CL[0:lmax+1,0:4], where 0..3 indexes TT, EE, BB, TE.
References camb.camb.CAMBdata._one, and camb.camb.CAMB_SetLensedScalCls.
get_linear_matter_power_spectrum()
def camb.camb.CAMBdata.get_linear_matter_power_spectrum (self, var1 = None, var2 = None, hubble_units = True, have_power_spectra = False, params = None, nonlinear = False)
Calculates P_{xy}(k/h), where x, y are one of model.Transfer_cdm, model.Transfer_xx etc.
The output k values are not regularly spaced, and not interpolated.
:param var1: variable i (index, or name of variable; default delta_tot)
:param var2: variable j (index, or name of variable; default delta_tot)
:param hubble_units: if true, output power spectrum in (Mpc/h)^{-3} units, otherwise Mpc^{-3}
:param have_power_spectra: set to True if already computed power spectra
:param params: if have_power_spectra=False, optional :class:`.model.CAMBparams` instance to specify new parameters
:param nonlinear: include non-linear correction from halo model
:return: kh, z, PK, where kz an z are arrays of k/h and z respectively, and PK[i,j] is value at z[i], k/h[j]
References camb.camb.CAMBdata._key, camb.camb.CAMBdata._transfer_var(), camb.camb.CAMBdata.calc_power_spectra(), camb.camb.CAMBdata_GetLinearMatterPower, camb.camb.CAMBdata_GetNonLinearMatterPower, camb.camb.CAMBdata.get_matter_transfer_data(), and camb.camb.CAMBdata.Params.
Referenced by camb.camb.CAMBdata._transfer_var(), and camb.camb.CAMBdata.get_nonlinear_matter_power_spectrum().
get_matter_power_spectrum()
def camb.camb.CAMBdata.get_matter_power_spectrum (self, minkh = 1e-4, maxkh = 1.0, npoints = 100, var1 = None, var2 = None, have_power_spectra = False, params = None)
Calculates P_{xy}(k/h), where x, y are one of Transfer_cdm, Transfer_xx etc defined in ModelParams.
The output k values are regularly log spaced and interpolated. If NonLinear is set, the result is non-linear.
:param minkh: minimum value of k/h for output grid (very low values < 1e-4 may not be calculated)
:param maxkh: maximum value of k/h (check consistent with input params.Transfer.kmax)
:param npoints: number of points equally spaced in log k
:param var1: variable i (index, or name of variable; default delta_tot)
:param var2: variable j (index, or name of variable; default delta_tot)
:param have_power_spectra: set to True if already computed power spectra
:param params: if have_power_spectra=False and want to specify new parameters, a :class:`.model.CAMBparams` instance
:return: kh, z, PK, where kz an z are arrays of k/h and z respectively, and PK[i,j] is value at z[i], k/h[j]
References camb.camb.CAMBdata._key, camb.camb.CAMBdata._transfer_var(), camb.camb.c_double, camb.camb.CAMBdata.calc_power_spectra(), camb.camb.CAMBdata_GetMatterPower, and camb.camb.CAMBdata.Params.
Referenced by camb.camb.CAMBdata.get_sigma8().
get_matter_transfer_data()
def camb.camb.CAMBdata.get_matter_transfer_data (self)
Get matter transfer function data and sigma8 for calculated results.
:return: :class:`.MatterTransferData` instance holding output arrays (copies, not pointers)
References camb.camb.CAMBdata._key, camb.camb.CAMBdata_mattertransferdata, camb.camb.fortran_array(), and camb.camb.CAMBdata.Params.
Referenced by camb.camb.CAMBdata.get_linear_matter_power_spectrum(), and camb.camb.CAMBdata.get_sigma8().
get_nonlinear_matter_power_spectrum()
def camb.camb.CAMBdata.get_nonlinear_matter_power_spectrum (self, kwargs)
Calculates P_{xy}(k/h), where x, y are one of model.Transfer_cdm, model.Transfer_xx etc.
The output k values are not regularly spaced, and not interpolated.
:param var1: variable i (index, or name of variable; default delta_tot)
:param var2: variable j (index, or name of variable; default delta_tot)
:param hubble_units: if true, output power spectrum in (Mpc/h)^{-3} units, otherwise Mpc^{-3}
:param have_power_spectra: set to True if already computed power spectra
:param params: if have_power_spectra=False, optional :class:`.model.CAMBparams` instance to specify new parameters
:return: kh, z, PK, where kz an z are arrays of k/h and z respectively, and PK[i,j] is value at z[i], k/h[j]
References camb.camb.CAMBdata.get_linear_matter_power_spectrum().
get_params()
def camb.camb.CAMBdata.get_params (self)
Get the parameters currently set. Returned object references stored data, so elements can be modified without
calling set_params again.
:return: :class:`.model.CAMBparams` instance pointing to the underlying parameters used by CAMB.
References camb.camb.CAMBdata._key, and camb.camb.CAMBdata_getparams.
Referenced by camb.camb.CAMBdata.power_spectra_from_transfer().
get_redshift_evolution()
def camb.camb.CAMBdata.get_redshift_evolution (self, q, z, vars = model.evolve_names, lAccuracyBoost = 4)
Get the mode evolution as a function of redshift for some k values.
:param q: wavenumber values to calculate (or array of k values)
:param z: array of redshifts to output
:param vars: list of variable names to output
:return: nd array, A_{qti}, size(q) x size(times) x len(vars), or 2d array if q is scalar
References camb.camb.CAMBdata.conformal_time(), and camb.camb.CAMBdata.get_time_evolution().
get_sigma8()
def camb.camb.CAMBdata.get_sigma8 (self)
Get sigma_8 values (must previously have calculated power spectra)
:return: array of sigma_8 values, in order of increasing time (decreasing redshift)
References camb.camb.CAMBdata.get_matter_power_spectrum(), and camb.camb.CAMBdata.get_matter_transfer_data().
get_tensor_cls()
def camb.camb.CAMBdata.get_tensor_cls (self, lmax)
Get tensor CMB power spectra. Must have already calculated power spectra.
:param lmax: lmax to output to
:return: numpy array CL[0:lmax+1,0:4], where 0..3 indexes TT, EE, BB, TE
References camb.camb.CAMBdata._one, and camb.camb.CAMB_SetTensorCls.
Referenced by camb.camb.CAMBdata.get_unlensed_total_cls().
get_time_evolution()
def camb.camb.CAMBdata.get_time_evolution (self, q, eta, vars = model.evolve_names, lAccuracyBoost = 4)
Get the mode evolution as a function of conformal time for some k values.
:param q: wavenumber values to calculate (or array of k values)
:param eta: array of requested conformal times to output
:param vars: list of variable names to output
:return: nd array, A_{qti}, size(q) x size(times) x len(vars), or 2d array if q is scalar
References camb.camb.CAMB_TimeEvolution, and set().
Referenced by camb.camb.CAMBdata.get_redshift_evolution().
get_total_cls()
def camb.camb.CAMBdata.get_total_cls (self, lmax)
Get lensed-scalar + tensor CMB power spectra. Must have already calculated power spectra.
:param lmax: lmax to output to
:return: numpy array CL[0:lmax+1,0:4], where 0..3 indexes TT, EE, BB, TE
References camb.camb.CAMBdata._one, and camb.camb.CAMB_SetTotCls.
get_unlensed_scalar_array_cls()
def camb.camb.CAMBdata.get_unlensed_scalar_array_cls (self, lmax)
Get array of all cross power spectra. Must have already calculated power spectra.
:param lmax: lmax to output to
:return: numpy array CL[0:lmax+1,0:, 0:], where 0.. index T, E, deflection angle, source window functions
References camb.camb.CAMBdata._one, and camb.camb.CAMB_SetUnlensedScalarArray.
get_unlensed_scalar_cls()
def camb.camb.CAMBdata.get_unlensed_scalar_cls (self, lmax)
Get unlensed scalar CMB power spectra. Must have already calculated power spectra.
:param lmax: lmax to output to
:return: numpy array CL[0:lmax+1,0:4], where 0..3 indexes TT, EE, BB, TE. CL[:,2] will be zero.
References camb.camb.CAMBdata._one, and camb.camb.CAMB_SetUnlensedScalCls.
Referenced by camb.camb.CAMBdata.get_unlensed_total_cls().
get_unlensed_total_cls()
def camb.camb.CAMBdata.get_unlensed_total_cls (self, lmax)
Get unlensed CMB power spectra, including tensors if relevant. Must have already calculated power spectra.
:param lmax: lmax to output to
:return: numpy array CL[0:lmax+1,0:4], where 0..3 indexes TT, EE, BB, TE.
References camb.camb.CAMBdata.get_tensor_cls(), and camb.camb.CAMBdata.get_unlensed_scalar_cls().
h_of_z()
def camb.camb.CAMBdata.h_of_z (self, z)
Get Hubble rate at redshift z, in Mpc^{-1} units.
Must have called calc_background, calc_background_no_thermo or calculated transfer functions or power spectra.
:param z: redshift
:return: H(z)
References camb.camb.c_double, and camb.camb.Hofz.
Referenced by camb.camb.CAMBdata.hubble_parameter().
hubble_parameter()
def camb.camb.CAMBdata.hubble_parameter (self, z)
Get Huuble rate at redshift z, in km/s/Mpc units.
Must have called calc_background, calc_background_no_thermo or calculated transfer functions or power spectra.
:param z: redshift
:return: H(z)/[km/s/Mpc]
References camb.camb.CAMBdata.h_of_z().
luminosity_distance()
def camb.camb.CAMBdata.luminosity_distance (self, z)
Get luminosity distance from to redshift z.
Must have called calc_background, calc_background_no_thermo or calculated transfer functions or power spectra.
:param z: redshift or array of redshifts
:return: luminosity distance (matches rank of z)
References camb.camb.CAMBdata.angular_diameter_distance().
physical_time()
def camb.camb.CAMBdata.physical_time (self, z)
Get physical time from hot big bang to redshift z in Gigayears.
:param z:  redshift
:return: t(z)/Gigayear
References camb.camb.CAMBdata.physical_time_a1_a2().
physical_time_a1_a2()
def camb.camb.CAMBdata.physical_time_a1_a2 (self, a1, a2)
Get physical time between two scalar factors in Gigayears
Must have called calc_background, calc_background_no_thermo or calculated transfer functions or power spectra.
:param a1: scale factor 1
:param a2: scale factor 2
:return: (age(a2)-age(a1))/Gigayear
References camb.camb.c_double, and camb.camb.DeltaPhysicalTimeGyr.
Referenced by camb.camb.CAMBdata.physical_time().
power_spectra_from_transfer()
def camb.camb.CAMBdata.power_spectra_from_transfer (self, initial_power_params)
Assuming `calc_transfers` or `calc_power_spectra` have already been used, re-calculate the power spectra
using a new set of initial power spectrum parameters with otherwise the same cosmology.
This is typically much faster that re-calculating everything, as the transfer functions can be re-used.
:param initial_power_params: :class:`.initialpower.InitialPowerParams` instance with new primordial power spectrum parameters
References camb.camb.CAMBdata._key, camb.camb.CAMBdata_transferstopowers, camb.camb.CAMBdata.get_cmb_power_spectra(), camb.camb.CAMBdata.get_params(), and camb.camb.CAMBdata.Params.
redshift_at_comoving_radial_distance()
def camb.camb.CAMBdata.redshift_at_comoving_radial_distance (self, chi, nz_step = 150, zmax = 10000)
Convert comoving radial distance array to redshift array.
This is not calculated directly, but fit from a spline to a forward calculation of chi from z
This is a utility routine, not optimized to be fast (though it can work on a large vector efficiently)
:param chi: comoving radial distance (in Mpc), scalar or array
:param nz_step: number of redshifts calculated internally for solving grid
:param zmax: maximum redshift in internal solving grid
:return: redshift at chi, scalar or array
References camb.camb.CAMBdata.conformal_time(), and camb.bbn.f.
set_params()
def camb.camb.CAMBdata.set_params (self, params)
Set parameters from params
:param params: a :class:`.model.CAMBparams` instance
References camb.camb.CAMBdata._key, and camb.camb.CAMBdata_setparams.
Member Data Documentation
_key
camb.camb.CAMBdata._key private
Referenced by camb.camb.CAMBdata.calc_background(), camb.camb.CAMBdata.calc_background_no_thermo(), camb.camb.CAMBdata.calc_power_spectra(), camb.camb.CAMBdata.calc_transfers(), camb.camb.CAMBdata.free(), camb.camb.CAMBdata.get_cmb_transfer_data(), camb.camb.CAMBdata.get_linear_matter_power_spectrum(), camb.camb.CAMBdata.get_matter_power_spectrum(), camb.camb.CAMBdata.get_matter_transfer_data(), camb.camb.CAMBdata.get_params(), camb.camb.CAMBdata.power_spectra_from_transfer(), and camb.camb.CAMBdata.set_params().
_one
camb.camb.CAMBdata._one private
Referenced by camb.camb.CAMBdata.get_lens_potential_cls(), camb.camb.CAMBdata.get_lensed_scalar_cls(), camb.camb.CAMBdata.get_tensor_cls(), camb.camb.CAMBdata.get_total_cls(), camb.camb.CAMBdata.get_unlensed_scalar_array_cls(), and camb.camb.CAMBdata.get_unlensed_scalar_cls().
Params
camb.camb.CAMBdata.Params
Referenced by camb.camb.CAMBdata.get_cmb_power_spectra(), camb.camb.CAMBdata.get_linear_matter_power_spectrum(), camb.camb.CAMBdata.get_matter_power_spectrum(), camb.camb.CAMBdata.get_matter_transfer_data(), and camb.camb.CAMBdata.power_spectra_from_transfer().
The documentation for this class was generated from the following file:
/home/ealmaraz/software/cosmomc/bde/v3.1/camb/pycamb/camb/camb.py