cosmomc_bde_v3p1: getdist.densities.Density1D Class Reference
getdist.densities.Density1D Class Reference
Public Member Functions
def __init__ (self, x, P=None, view_ranges=None)
def bounds (self)
def Prob (self, x, derivative=0)
def integrate (self, P)
def norm_integral (self)
def initLimitGrids (self, factor=None)
def getLimits (self, p, interpGrid=None, accuracy_factor=None)
Public Member Functions inherited from getdist.densities.GridDensity
def normalize (self, by='integral', in_place=False)
def setP (self, P=None)
def bounds (self)
def getContourLevels (self, contours=defaultContours)
Public Attributes
n
axes
x
view_ranges
spacing
spl
Public Attributes inherited from getdist.densities.GridDensity
spl
P
Private Member Functions
def _initSpline (self)
Detailed Description
Class for 1D marginalized densities, inheriting from :class:`GridDensity`.
Constructor & Destructor Documentation
__init__()
def getdist.densities.Density1D.__init__ (self, x, P = None, view_ranges = None)
:param x: array of x values
:param P: array of densities at x values
:param view_ranges: optional range for viewing density
Member Function Documentation
_initSpline()
def getdist.densities.Density1D._initSpline (self) private
Referenced by getdist.densities.Density1D.Prob(), getdist.densities.Density2D.Prob(), and getdist.densities.DensityND.Prob().
bounds()
def getdist.densities.Density1D.bounds (self)
Get min, max bounds (from view_ranges if set)
References getdist.densities.Density1D.view_ranges, and getdist.densities.Density1D.x.
getLimits()
def getdist.densities.Density1D.getLimits (self, p, interpGrid = None, accuracy_factor = None)
Get parameter equal-density confidence limits (a credible interval).
If the density is bounded, may only have a one-tail limit.
:param p: list of limits to calculate, e.g. [0.68, 0.95]
:param interpGrid: optional pre-computed cache
:param accuracy_factor: parameter to boost default accuracy for fine sampling
:return: list of (min, max, has_min, has_top) values
where has_min and has_top are True or False depending on whether lower and upper limit exists
References getdist.densities.Density1D.initLimitGrids(), getdist.densities.Density1D.spacing, getdist.densities.Density1D.x, and copyGridFiles.zip.
initLimitGrids()
def getdist.densities.Density1D.initLimitGrids (self, factor = None)
Referenced by getdist.densities.Density1D.getLimits().
integrate()
def getdist.densities.Density1D.integrate (self, P)
References getdist.densities.Density1D.spacing.
Referenced by getdist.densities.Density1D.norm_integral(), getdist.densities.Density2D.norm_integral(), and getdist.densities.DensityND.norm_integral().
norm_integral()
def getdist.densities.Density1D.norm_integral (self)
References getdist.densities.Density1D.integrate(), and getdist.densities.GridDensity.P.
Referenced by getdist.densities.GridDensity.normalize().
Prob()
def getdist.densities.Density1D.Prob (self, x, derivative = 0)
Calculate density at position x by interpolation in the density grid
:param x: x value
:param derivative: optional order of derivative to calculate (default: no derivative)
:return: P(x) density value
References getdist.densities.Density1D._initSpline(), and getdist.densities.GridDensity.spl.
Member Data Documentation
axes
getdist.densities.Density1D.axes
Referenced by getdist.densities.GridDensity.bounds(), and getdist.densities.GridDensity.setP().
n
getdist.densities.Density1D.n
spacing
getdist.densities.Density1D.spacing
Referenced by getdist.densities.Density1D.getLimits(), getdist.densities.Density1D.integrate(), and getdist.densities.Density2D.integrate().
spl
getdist.densities.Density1D.spl
view_ranges
getdist.densities.Density1D.view_ranges
Referenced by getdist.densities.GridDensity.bounds(), and getdist.densities.Density1D.bounds().
x
getdist.densities.Density1D.x
Referenced by getdist.densities.Density2D._initSpline(), getdist.densities.Density1D.bounds(), and getdist.densities.Density1D.getLimits().
The documentation for this class was generated from the following file:
/home/ealmaraz/software/cosmomc/bde/v3.1/python/getdist/densities.py