cosmomc_bde_v3p1: getdist.plots.GetDistPlotter Class Reference
getdist.plots.GetDistPlotter Class Reference
Public Member Functions
def __init__ (self, plot_data=None, chain_dir=None, settings=None, analysis_settings=None, mcsamples=True)
def newPlot (self)
def show_all_settings (self)
def paramNamesForRoot (self, root)
def paramBoundsForRoot (self, root)
def add_1d (self, root, param, plotno=0, normalized=False, ax=None, kwargs)
def add_2d_density_contours (self, density, kwargs)
def add_2d_contours (self, root, param1=None, param2=None, plotno=0, of=None, cols=None, contour_levels=None, add_legend_proxy=True, param_pair=None, density=None, alpha=None, ax=None, kwargs)
def add_2d_shading (self, root, param1, param2, colormap=None, density=None, ax=None, kwargs)
def plot_2d (self, roots, param1=None, param2=None, param_pair=None, shaded=False, add_legend_proxy=True, line_offset=0, proxy_root_exclude=[], kwargs)
def add_x_marker (self, marker, color=None, ls=None, lw=None, ax=None, kwargs)
def add_y_marker (self, marker, color=None, ls=None, lw=None, ax=None, kwargs)
def add_x_bands (self, x, sigma, color='gray', ax=None, alpha1=0.15, alpha2=0.1, kwargs)
def add_y_bands (self, y, sigma, color='gray', ax=None, alpha1=0.15, alpha2=0.1, kwargs)
def setAxes (self, params=[], lims=None, do_xlabel=True, do_ylabel=True, no_label_no_numbers=False, pos=None, prune=None, color_label_in_axes=False, ax=None, other_args)
def set_xlabel (self, param, ax=None)
def set_ylabel (self, param, ax=None)
def plot_1d (self, roots, param, marker=None, marker_color=None, label_right=False, no_ylabel=False, no_ytick=False, no_zero=False, normalized=False, param_renames={}, kwargs)
def make_figure (self, nplot=1, nx=None, ny=None, xstretch=1.0, ystretch=1.0)
def get_param_array (self, root, params=None, renames={})
def param_latex_label (self, root, name, labelParams=None)
def add_legend (self, legend_labels, legend_loc=None, line_offset=0, legend_ncol=None, colored_text=False, figure=False, ax=None, label_order=None, align_right=False, fontsize=None)
def finish_plot (self, legend_labels=None, legend_loc=None, line_offset=0, legend_ncol=None, label_order=None, no_gap=False, no_extra_legend_space=False, no_tight=False)
def plots_1d (self, roots, params=None, legend_labels=None, legend_ncol=None, label_order=None, nx=None, paramList=None, roots_per_param=False, share_y=None, markers=None, xlims=None, param_renames={}, kwargs)
def plots_2d (self, roots, param1=None, params2=None, param_pairs=None, nx=None, legend_labels=None, legend_ncol=None, label_order=None, filled=False, shaded=False, kwargs)
def plots_2d_triplets (self, root_params_triplets, nx=None, filled=False, x_lim=None)
def triangle_plot (self, roots, params=None, legend_labels=None, plot_3d_with_param=None, filled=False, shaded=False, contour_args=None, contour_colors=None, contour_ls=None, contour_lws=None, line_args=None, label_order=None, legend_ncol=None, legend_loc=None, upper_roots=None, upper_kwargs={}, kwargs)
def rectangle_plot (self, xparams, yparams, yroots=None, roots=None, plot_roots=None, plot_texts=None, xmarkers=None, ymarkers=None, marker_args={}, param_limits={}, legend_labels=None, legend_ncol=None, label_order=None, kwargs)
def rotate_yticklabels (self, ax=None, rotation=90)
def add_colorbar (self, param, orientation='vertical', mappable=None, ax=None, ax_args)
def add_line (self, xdata, ydata, zorder=0, color=None, ls=None, ax=None, kwargs)
def add_colorbar_label (self, cb, param, label_rotation=None)
def add_2d_scatter (self, root, x, y, color='k', alpha=1, extra_thin=1, scatter_size=None, ax=None)
def add_3d_scatter (self, root, params, color_bar=True, alpha=1, extra_thin=1, scatter_size=None, ax=None, kwargs)
def plot_2d_scatter (self, roots, param1, param2, color='k', line_offset=0, add_legend_proxy=True, kwargs)
def plot_3d (self, roots, params=None, params_for_plots=None, color_bar=True, line_offset=0, add_legend_proxy=True, kwargs)
def plots_3d (self, roots, param_sets, nx=None, legend_labels=None, kwargs)
def plots_3d_z (self, roots, param_x, param_y, param_z=None, max_z=None, kwargs)
def add_text (self, text_label, x=0.95, y=0.06, ax=None, kwargs)
def add_text_left (self, text_label, x=0.05, y=0.06, ax=None, kwargs)
def export (self, fname=None, adir=None, watermark=None, tag=None)
Public Attributes
chain_dir
settings
plot_data
sampleAnalyser
extra_artists
contours_added
lines_added
param_name_sets
param_bounds_sets
fig
subplots
plot_col
plot_row
legend
last_scatter
last_colorbar
Private Member Functions
def _get_plot_args (self, plotno, kwargs)
def _get_dashes_for_ls (self, ls)
def _get_default_ls (self, plotno=0)
def _get_line_styles (self, plotno, kwargs)
def _get_color (self, plotno, kwargs)
def _get_linestyle (self, plotno, kwargs)
def _get_alpha2D (self, plotno, kwargs)
def _check_param_ranges (self, root, name, xmin, xmax)
def _updateLimit (self, bounds, curbounds)
def _updateLimits (self, res, xlims, ylims, doResize=True)
def _make_line_args (self, nroots, kwargs)
def _make_contour_args (self, nroots, kwargs)
def _set_locator (self, axis, x=False, prune=None)
def _setAxisProperties (self, axis, x, prune=None)
def _check_param (self, root, param, renames={})
def _escapeLatex (self, text)
def _rootDisplayName (self, root, i)
def _default_legend_labels (self, legend_labels, roots)
def _subplot (self, x, y, kwargs)
def _subplot_number (self, i)
def _spaceTicks (self, axis, expand=True)
def _makeParamObject (self, names, samples)
def _paramNameListFromFile (self, fname)
Detailed Description
Main class for making plots from one or more sets of samples.
:ivar settings: a :class:`GetDistPlotSettings` instance with settings
:ivar subplots: a 2D array of :class:`~matplotlib:matplotlib.axes.Axes` for subplots
:ivar sampleAnalyser: a :class:`MCSampleAnalysis` instance for getting :class:`~.mcsamples.MCSamples`
     and derived data from a given root name tag (e.g. sampleAnalyser.samplesForRoot('rootname'))
Constructor & Destructor Documentation
__init__()
def getdist.plots.GetDistPlotter.__init__ (self, plot_data = None, chain_dir = None, settings = None, analysis_settings = None, mcsamples = True)
:param plot_data: (deprecated) directory name if you have pre-computed plot_data/ directory from GetDist; None by default
:param chain_dir: Set this to a directory or grid root to search for chains (can also be a list of such, searched in order)
:param analysis_settings: The settings to be used by :class:`MCSampleAnalysis` when analysing samples
:param mcsamples: if True defaults to current method of using :class:`MCSampleAnalysis` instance to analyse chains on demand
Member Function Documentation
_check_param()
def getdist.plots.GetDistPlotter._check_param (self, root, param, renames = {}) private
Get :class:`~.paramnames.ParamInfo` for given name for samples with specified root
:param root: The root name of the samples
:param param: The parameter name (or :class:`~.paramnames.ParamInfo`)
:param renames: optional dictionary mapping input names and equivalent names used by the samples
:return: a :class:`~.paramnames.ParamInfo` instance, or None if name not found
References getdist.plots.GetDistPlotter.paramNamesForRoot().
Referenced by getdist.plots.GetDistPlotter.add_1d(), getdist.plots.GetDistPlotter.param_latex_label(), getdist.plots.GetDistPlotter.plot_1d(), getdist.plots.GetDistPlotter.plots_1d(), getdist.plots.GetDistPlotter.plots_2d(), getdist.plots.GetDistPlotter.plots_3d(), and getdist.plots.GetDistPlotter.triangle_plot().
_check_param_ranges()
def getdist.plots.GetDistPlotter._check_param_ranges (self, root, name, xmin, xmax) private
Checks The upper and lower bounds are not outside hard priors
:param root: The root file to use.
:param name: The param name to check.
:param xmin: The lower bound
:param xmax: The upper bound
:return: The bounds (highest lower limit, and lowest upper limit)
References getdist.plots.GetDistPlotter.paramBoundsForRoot().
Referenced by getdist.plots.GetDistPlotter.plot_1d(), getdist.plots.GetDistPlotter.plot_2d(), and getdist.plots.GetDistPlotter.plot_3d().
_default_legend_labels()
def getdist.plots.GetDistPlotter._default_legend_labels (self, legend_labels, roots) private
Returns default legend labels, based on name tags of samples
:param legend_labels: The current legend labels.
:param roots: The root names of the samples
:return: A list of labels
References getdist.plots.GetDistPlotter._rootDisplayName(), and getdist.plots.GetDistPlotter.plots_1d().
Referenced by getdist.plots.GetDistPlotter.plots_1d(), getdist.plots.GetDistPlotter.plots_2d(), getdist.plots.GetDistPlotter.plots_3d(), getdist.plots.GetDistPlotter.rectangle_plot(), and getdist.plots.GetDistPlotter.triangle_plot().
_escapeLatex()
def getdist.plots.GetDistPlotter._escapeLatex (self, text) private
Referenced by getdist.plots.GetDistPlotter._rootDisplayName(), and getdist.plots.GetDistPlotter.export().
_get_alpha2D()
def getdist.plots.GetDistPlotter._get_alpha2D (self, plotno, kwargs) private
Get the alpha for the given 2D contour added to plot
:param plotno:  The index of contours added to the plot
:param kwargs: arguments for :func:`~GetDistPlotter._get_line_styles`,
    These may also include: filled
:return: The alpha for the given plot contours
References getdist.plots.GetDistPlotter._get_plot_args(), and getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter.add_2d_contours().
_get_color()
def getdist.plots.GetDistPlotter._get_color (self, plotno, kwargs) private
Get the color for the given line number
:param plotno: line number added to plot
:param kwargs: arguments for :func:`~GetDistPlotter._get_line_styles`
:return: The color.
References getdist.plots.GetDistPlotter._get_line_styles().
_get_dashes_for_ls()
def getdist.plots.GetDistPlotter._get_dashes_for_ls (self, ls) private
Gets the dash style for the given line style.
:param ls: The line style
:return: The dash style.
References getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter._get_line_styles().
_get_default_ls()
def getdist.plots.GetDistPlotter._get_default_ls (self, plotno = 0) private
Get default line style.
:param plotno: The number of the line added to the plot to get the style of.
:return: The default line style.
References getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter._get_line_styles().
_get_line_styles()
def getdist.plots.GetDistPlotter._get_line_styles (self, plotno, kwargs) private
Gets the styles of the line for the given line added to a plot
:param plotno: The number of the line added to the plot.
:param kwargs: Params for :func:`~GetDistPlotter._get_plot_args`.
:return: dict with ls, dashes, lw and color set appropriately
References getdist.plots.GetDistPlotter._get_dashes_for_ls(), getdist.plots.GetDistPlotter._get_default_ls(), getdist.plots.GetDistPlotter._get_plot_args(), and getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter._get_color(), getdist.plots.GetDistPlotter._get_linestyle(), getdist.plots.GetDistPlotter.add_1d(), getdist.plots.GetDistPlotter.add_2d_contours(), and getdist.plots.GetDistPlotter.add_legend().
_get_linestyle()
def getdist.plots.GetDistPlotter._get_linestyle (self, plotno, kwargs) private
Get line style for given plot line number.
:param plotno: line number added to plot
:param kwargs: arguments for :func:`~GetDistPlotter._get_line_styles`
:return: The line style for the given plot line.
References getdist.plots.GetDistPlotter._get_line_styles().
_get_plot_args()
def getdist.plots.GetDistPlotter._get_plot_args (self, plotno, kwargs) private
Get plot arguments for the given plot line number
:param plotno: The index of the line added to a plot
:param kwargs: optional settings to override in the current ones
:return: The updated dict of arguments.
References getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter._get_alpha2D(), getdist.plots.GetDistPlotter._get_line_styles(), and getdist.plots.GetDistPlotter.add_2d_contours().
_make_contour_args()
def getdist.plots.GetDistPlotter._make_contour_args (self, nroots, kwargs) private
References getdist.plots.GetDistPlotter._make_line_args(), getdist.plots.GetDistPlotter.plot_2d(), and copyGridFiles.zip.
Referenced by getdist.plots.GetDistPlotter.plot_2d(), getdist.plots.GetDistPlotter.plot_3d(), and getdist.plots.GetDistPlotter.triangle_plot().
_make_line_args()
def getdist.plots.GetDistPlotter._make_line_args (self, nroots, kwargs) private
Referenced by getdist.plots.GetDistPlotter._make_contour_args(), getdist.plots.GetDistPlotter.plot_1d(), and getdist.plots.GetDistPlotter.triangle_plot().
_makeParamObject()
def getdist.plots.GetDistPlotter._makeParamObject (self, names, samples) private
Referenced by getdist.plots.GetDistPlotter.add_3d_scatter().
_paramNameListFromFile()
def getdist.plots.GetDistPlotter._paramNameListFromFile (self, fname) private
Reads param names for a file.
:param fname: The file to read
:return: A list of param names
Referenced by getdist.plots.GetDistPlotter.plots_1d().
_rootDisplayName()
def getdist.plots.GetDistPlotter._rootDisplayName (self, root, i) private
References getdist.plots.GetDistPlotter._escapeLatex().
Referenced by getdist.plots.GetDistPlotter._default_legend_labels().
_set_locator()
def getdist.plots.GetDistPlotter._set_locator (self, axis, x = False, prune = None) private
Set the locator for ticks
:param axis: The axis instance
:param x: True if x axis, False for y axis
:param prune: Parameter for MaxNLocator constructor,  ['lower' | 'upper' | 'both' | None]
References getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter._setAxisProperties().
_setAxisProperties()
def getdist.plots.GetDistPlotter._setAxisProperties (self, axis, x, prune = None) private
Sets axis properties.
:param axis: The axis to set properties to.
:param x: True if x axis, False for y axis
:param prune: Parameter for MaxNLocator constructor, ,  ['lower' | 'upper' | 'both' | None]
References getdist.plots.GetDistPlotter._set_locator(), getdist.plots.GetDistPlotter.setAxes(), and getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter.setAxes(), and getdist.plots.GetDistPlotter.triangle_plot().
_spaceTicks()
def getdist.plots.GetDistPlotter._spaceTicks (self, axis, expand = True) private
Space the axis ticks so there are none near the edges (which are likely to overlap on packed subplots)
:param axis: axis instance
:param expand: if True, increase axis range so existing ticks are safely not near edgel
        otherwise remove end ticks
:return: list of tick values
References getdist.plots.GetDistPlotter.settings, and getdist.plots.GetDistPlotter.triangle_plot().
Referenced by getdist.plots.GetDistPlotter.plots_1d(), getdist.plots.GetDistPlotter.rectangle_plot(), and getdist.plots.GetDistPlotter.triangle_plot().
_subplot()
def getdist.plots.GetDistPlotter._subplot (self, x, y, kwargs) private
Create a subplot with given parameters.
:param x: x location in the subplot grid
:param y: y location in the subplot grid
:param kwargs: arguments for :func:`~matplotlib:matplotlib.pyplot.subplot`
:return: an :class:`~matplotlib:matplotlib.axes.Axes` instance for the subplot axes
References getdist.plots.GetDistPlotter.plot_col, getdist.plots.GetDistPlotter.plot_row, and getdist.plots.GetDistPlotter.subplots.
Referenced by getdist.plots.GetDistPlotter.rectangle_plot(), and getdist.plots.GetDistPlotter.triangle_plot().
_subplot_number()
def getdist.plots.GetDistPlotter._subplot_number (self, i) private
Create a subplot with given index.
:param i: index of the subplot
:return: an :class:`~matplotlib:matplotlib.axes.Axes` instance for the subplot axes
References getdist.plots.GetDistPlotter.plot_col, getdist.plots.GetDistPlotter.plot_row, and getdist.plots.GetDistPlotter.subplots.
Referenced by getdist.plots.GetDistPlotter.plots_1d(), getdist.plots.GetDistPlotter.plots_2d(), getdist.plots.GetDistPlotter.plots_2d_triplets(), and getdist.plots.GetDistPlotter.plots_3d().
_updateLimit()
def getdist.plots.GetDistPlotter._updateLimit (self, bounds, curbounds) private
Calculates the merge of two upper and lower limits, so result encloses both ranges
:param bounds:  bounds to update
:param curbounds:  bounds to add
:return: The new limits
Referenced by getdist.plots.GetDistPlotter._updateLimits(), and getdist.plots.GetDistPlotter.plot_1d().
_updateLimits()
def getdist.plots.GetDistPlotter._updateLimits (self, res, xlims, ylims, doResize = True) private
update 2D limits with new x and y limits (expanded unless doResize is False)
:param res: The current limits
:param xlims: The new lims for x
:param ylims: The new lims for y.
:param doResize: True if should resize, False otherwise.
:return: The newly calculated limits.
References getdist.plots.GetDistPlotter._updateLimit().
Referenced by getdist.plots.GetDistPlotter.plot_2d(), getdist.plots.GetDistPlotter.plot_3d(), and getdist.plots.GetDistPlotter.rectangle_plot().
add_1d()
def getdist.plots.GetDistPlotter.add_1d (self, root, param, plotno = 0, normalized = False, ax = None, kwargs)
Low-level function to add a 1D marginalized density line to a plot
:param root: The root name of the samples
:param param: The parameter name
:param plotno: The index of the line being added to the plot
:param normalized: True if areas under lines should match, False if normalized to unit maximum
:param ax: optional :class:`~matplotlib:matplotlib.axes.Axes` instance to add to (defaults to current plot)
:param kwargs: arguments for :func:`~matplotlib:matplotlib.pyplot.plot`
:return: min, max for the plotted density
References getdist.plots.GetDistPlotter._check_param(), getdist.plots.GetDistPlotter._get_line_styles(), getdist.plots.GetDistPlotter.lines_added, getdist.plots.GetDistPlotter.sampleAnalyser, and getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter.plot_1d().
add_2d_contours()
def getdist.plots.GetDistPlotter.add_2d_contours (self, root, param1 = None, param2 = None, plotno = 0, of = None, cols = None, contour_levels = None, add_legend_proxy = True, param_pair = None, density = None, alpha = None, ax = None, kwargs)
Low-level function to add 2D contours to plot for samples with given root name and parameters
:param root: The root name of samples to use
:param param1: x parameter
:param param2: y parameter
:param plotno: The index of the contour lines being added
:param of: the total number of contours being added (this is line plotno of of)
:param cols: optional list of colors to use for contours, by default uses default for this plotno
:param contour_levels: levels at which to plot the contours, by default given by contours array in the analysis settings
:param add_legend_proxy: True if should add a proxy to the legend of this plot.
:param param_pair: an [x,y] parameter name pair if you prefer to provide this rather than param1 and param2
:param density: optional :class:`~.densities.Density2D` to plot rather than that computed automatically from the samples
:param alpha: alpha for the contours added
:param ax: optional :class:`~matplotlib:matplotlib.axes.Axes` instance to add to (defaults to current plot)
:param kwargs: optional keyword arguments:
       - **filled**: True to make filled contours
       - **color**: top color to automatically make paling contour colours for a filled plot
       - kwargs for :func:`~matplotlib:matplotlib.pyplot.contour` and :func:`~matplotlib:matplotlib.pyplot.contourf`
:return: bounds (from :meth:`~.densities.GridDensity.bounds`) for the 2D density plotted
References getdist.plots.GetDistPlotter._get_alpha2D(), getdist.plots.GetDistPlotter._get_line_styles(), getdist.plots.GetDistPlotter._get_plot_args(), getdist.plots.GetDistPlotter.contours_added, getdist.plots.GetDistPlotter.get_param_array(), chainPeek.index, getdist.plots.GetDistPlotter.sampleAnalyser, and getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter.add_2d_density_contours(), getdist.plots.GetDistPlotter.plot_2d(), and getdist.plots.GetDistPlotter.plot_3d().
add_2d_density_contours()
def getdist.plots.GetDistPlotter.add_2d_density_contours (self, density, kwargs)
Low-level function to add 2D contours to a plot using provided density
:param density: a :class:`.densities.Density2D` instance
:param kwargs: arguments for :func:`~GetDistPlotter.add_2d_contours`
:return: bounds (from :func:`.~densities.GridDensity.bounds`) of density
References getdist.plots.GetDistPlotter.add_2d_contours().
add_2d_scatter()
def getdist.plots.GetDistPlotter.add_2d_scatter (self, root, x, y, color = 'k', alpha = 1, extra_thin = 1, scatter_size = None, ax = None)
Low-level function to adds a 2D sample scatter plot to the current axes (or ax if specified).
:param root: The root name of the samples to use
:param param1: name of x parameter
:param param2: name of y parameter
:param color: color to plot the samples
:param alpha: The alpha to use.
:param extra_thin: thin the weight one samples by this additional factor before plotting
:param scatter_size: point size (default: settings.scatter_size)
:param ax: optional :class:`~matplotlib:matplotlib.axes.Axes` instance to add to (defaults to current plot)
:return: (xmin, xmax), (ymin, ymax) bounds for the axes.
References getdist.plots.GetDistPlotter.add_3d_scatter().
add_2d_shading()
def getdist.plots.GetDistPlotter.add_2d_shading (self, root, param1, param2, colormap = None, density = None, ax = None, kwargs)
Low-level function to add 2D density shading to the given plot.
:param root: The root name of samples to use
:param param1: x parameter
:param param2: y parameter
:param colormap: color map, default to settings.colormap (see :class:`GetDistPlotSettings`)
:param density: optional user-provided :class:`~.densities.Density2D` to plot rather than
        the auto-generated density from the samples
:param ax: optional :class:`~matplotlib:matplotlib.axes.Axes` instance to add to (defaults to current plot)
:param kwargs: keyword arguments for :func:`~matplotlib:matplotlib.pyplot.contourf`
References CAMB_test_files.float, getdist.plots.GetDistPlotter.get_param_array(), getdist.plots.GetDistPlotter.sampleAnalyser, and getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter.plot_2d().
add_3d_scatter()
def getdist.plots.GetDistPlotter.add_3d_scatter (self, root, params, color_bar = True, alpha = 1, extra_thin = 1, scatter_size = None, ax = None, kwargs)
Low-level function to add a 3D scatter plot to the current axes (or ax if specified).
:param root: The root name of the samples to use
:param params:  list of parameters to plot
:param color_bar: True to add a colorbar for the plotted scatter color
:param alpha: The alpha to use.
:param extra_thin: thin the weight one samples by this additional factor before plotting
:param scatter_size: point size (default: settings.scatter_size)
:param ax: optional :class:`~matplotlib:matplotlib.axes.Axes` instance to add to (defaults to current plot)
:param kwargs: arguments for :func:`~GetDistPlotter.add_colorbar`
:return: (xmin, xmax), (ymin, ymax) bounds for the axes.
References getdist.plots.GetDistPlotter._makeParamObject(), getdist.plots.GetDistPlotter.get_param_array(), getdist.plots.GetDistPlotter.paramNamesForRoot(), and getdist.plots.GetDistPlotter.sampleAnalyser.
Referenced by getdist.plots.GetDistPlotter.add_2d_scatter(), and getdist.plots.GetDistPlotter.plot_3d().
add_colorbar()
def getdist.plots.GetDistPlotter.add_colorbar (self, param, orientation = 'vertical', mappable = None, ax = None, ax_args)
Adds a color bar to the given plot.
:param param: a :class:`~.paramnames.ParamInfo` with label for the parameter the color bar is describing
:param orientation: The orientation of the color bar (default: 'vertical')
:param mappable: the thing to color, defaults to current scatter
:param ax: optional :class:`~matplotlib:matplotlib.axes.Axes` instance to add to (defaults to current plot)
:param ax_args: extra arguments -
       **color_label_in_axes** - if True, label is not added (insert as text label in plot instead)
:return: The new :class:`~matplotlib:matplotlib.colorbar.Colorbar` instance
References getdist.plots.GetDistPlotter.add_colorbar_label(), getdist.plots.GetDistPlotter.rotate_yticklabels(), and getdist.plots.GetDistPlotter.settings.
add_colorbar_label()
def getdist.plots.GetDistPlotter.add_colorbar_label (self, cb, param, label_rotation = None)
Adds a color bar label.
:param cb: a :class:`~matplotlib:matplotlib.colorbar.Colorbar` instance
:param param: a :class:`~.paramnames.ParamInfo` with label for the plotted parameter
:param label_rotation: If set rotates the label (degrees)
References getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter.add_colorbar(), and getdist.plots.GetDistPlotter.triangle_plot().
add_legend()
def getdist.plots.GetDistPlotter.add_legend (self, legend_labels, legend_loc = None, line_offset = 0, legend_ncol = None, colored_text = False, figure = False, ax = None, label_order = None, align_right = False, fontsize = None)
Add a legend to the axes or figure.
:param legend_labels: The labels
:param legend_loc: The legend location, default from settings
:param line_offset: The offset of plotted lines to label (e.g. 1 to not label first line)
:param legend_ncol: The number of columns in the legend, defaults to 1
:param colored_text:
             - True: legend labels are colored to match the lines/contours
             - False: colored lines/boxes are drawn before black labels
:param figure: True if legend is for the figure rather than the selected axes
:param ax: if figure == False, the :class:`~matplotlib:matplotlib.axes.Axes` instance to use; defaults to current axes.
:param label_order: minus one to show legends in reverse order that lines were added, or a list giving specific order of line indices
:param align_right: True to align legend text at the right
:param fontsize: The size of the font, default from settings
:return: a :class:`matplotlib:matplotlib.legend.Legend` instance
References getdist.plots.GetDistPlotter._get_line_styles(), getdist.plots.GetDistPlotter.contours_added, getdist.plots.GetDistPlotter.lines_added, nonlinear.reverse(), and getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter.finish_plot(), and getdist.plots.GetDistPlotter.param_latex_label().
add_line()
def getdist.plots.GetDistPlotter.add_line (self, xdata, ydata, zorder = 0, color = None, ls = None, ax = None, kwargs)
Adds a line to the given axes, using :class:`~matplotlib:matplotlib.lines.Line2D`
:param xdata: pair of x coordinates
:param ydata: pair of y coordinates
:param zorder: Z-order for Line2D
:param color: The color of the line, uses settings.axis_marker_color by default
:param ls: The line style to be used, uses settings.axis_marker_ls by default
:param ax: the :class:`~matplotlib:matplotlib.axes.Axes` instance to use, defaults to current axes
:param kwargs:  Additional arguments for :class:`~matplotlib:matplotlib.lines.Line2D`
References getdist.plots.GetDistPlotter.settings.
add_text()
def getdist.plots.GetDistPlotter.add_text (self, text_label, x = 0.95, y = 0.06, ax = None, kwargs)
Add text to given axis.
:param text_label: The label to add.
:param x: The x coordinate of where to add the label
:param y: The y coordinate of where to add the label.
:param ax: the :class:`~matplotlib:matplotlib.axes.Axes` instance to use,
   index or [x,y] coordinate of subplot to use, or default to current axes.
:param kwargs: keyword arguments for :func:`~matplotlib:matplotlib.pyplot.text`
References getdist.plots.GetDistPlotter.fig, and getdist.plots.GetDistPlotter.subplots.
Referenced by getdist.plots.GetDistPlotter.add_text_left(), and getdist.plots.GetDistPlotter.setAxes().
add_text_left()
def getdist.plots.GetDistPlotter.add_text_left (self, text_label, x = 0.05, y = 0.06, ax = None, kwargs)
Add text to the left, Wraps add_text.
:param text_label: The label to add.
:param x: The x coordinate of where to add the label
:param y: The y coordinate of where to add the label.
:param ax: the :class:`~matplotlib:matplotlib.axes.Axes` instance to use, defaults to current axes.
:param kwargs: keyword arguments for :func:`~matplotlib:matplotlib.pyplot.text`
References getdist.plots.GetDistPlotter.add_text().
Referenced by getdist.plots.GetDistPlotter.rectangle_plot().
add_x_bands()
def getdist.plots.GetDistPlotter.add_x_bands (self, x, sigma, color = 'gray', ax = None, alpha1 = 0.15, alpha2 = 0.1, kwargs)
Adds vertical shaded bands showing one and two sigma ranges.
:param x: central x value for bands
:param sigma: 1 sigma error on x
:param color: The base color to use
:param ax: optional :class:`~matplotlib:matplotlib.axes.Axes` instance to add the bands to (defaults to current plot)
:param alpha1: alpha for the 1 sigma band; note this is drawn on top of the 2 sigma band. Set to zero if you only want 2 sigma band
:param alpha2: alpha for the 2 sigma band. Set to zero if you only want 1 sigma band
:param kwargs: optional keyword arguments for :func:`~matplotlib:matplotlib.pyplot.axvspan`
.. plot::
   :include-source:
    from getdist import plots, gaussian_mixtures
    samples1, samples2 = gaussian_mixtures.randomTestMCSamples(ndim=2, nMCSamples=2)
    g = plots.getSinglePlotter(width_inch=4)
    g.plot_2d([samples1, samples2], ['x0','x1'], filled=False);
    g.add_x_bands(0, 1)
add_x_marker()
def getdist.plots.GetDistPlotter.add_x_marker (self, marker, color = None, ls = None, lw = None, ax = None, kwargs)
Adds a vertical line marking some x value. Optional arguments can override default settings.
:param marker: The x coordinate of the location the marker line
:param color: optional color of the marker
:param ls: optional line style of the marker
:param lw: optional line width
:param ax: optional :class:`~matplotlib:matplotlib.axes.Axes` instance to add to (defaults to current plot)
:param kwargs: additional arguments to pass to :func:`~matplotlib:matplotlib.pyplot.axvline`
References getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter.plot_1d(), and getdist.plots.GetDistPlotter.rectangle_plot().
add_y_bands()
def getdist.plots.GetDistPlotter.add_y_bands (self, y, sigma, color = 'gray', ax = None, alpha1 = 0.15, alpha2 = 0.1, kwargs)
Adds horizontal shaded bands showing one and two sigma ranges.
:param y: central y value for bands
:param sigma: 1 sigma error on y
:param color: The base color to use
:param ax: optional :class:`~matplotlib:matplotlib.axes.Axes` instance to add the bands to (defaults to current plot)
:param alpha1: alpha for the 1 sigma band; note this is drawn on top of the 2 sigma band. Set to zero if you only want 2 sigma band
:param alpha2: alpha for the 2 sigma band. Set to zero if you only want 1 sigma band
:param kwargs: optional keyword arguments for :func:`~matplotlib:matplotlib.pyplot.axhspan`
.. plot::
   :include-source:
    from getdist import plots, gaussian_mixtures
    samples= gaussian_mixtures.randomTestMCSamples(ndim=2, nMCSamples=1)
    g = plots.getSinglePlotter(width_inch=4)
    g.plot_2d(samples, ['x0','x1'], filled=True);
    g.add_y_bands(0, 1)
add_y_marker()
def getdist.plots.GetDistPlotter.add_y_marker (self, marker, color = None, ls = None, lw = None, ax = None, kwargs)
Adds a horizontal line marking some y value. Optional arguments can override default settings.
:param marker: The y coordinate of the location the marker line
:param color: optional color of the marker
:param ls: optional line style of the marker
:param lw: optional line width.
:param ax: optional :class:`~matplotlib:matplotlib.axes.Axes` instance to add to (defaults to current plot)
:param kwargs: additional arguments to pass to :func:`~matplotlib:matplotlib.pyplot.axhline`
References getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter.rectangle_plot().
export()
def getdist.plots.GetDistPlotter.export (self, fname = None, adir = None, watermark = None, tag = None)
Exports given figure to a file. If the filename is not specified, saves to a file with the same
name as the calling script (useful for plot scripts where the script name matches the output figure).
:param fname: The filename to export to. The extension (.pdf, .png, etc) determines the file type
:param adir: The directory to save to
:param watermark: a watermark text, e.g. to make the plot with some pre-final version number
:param tag: A suffix to add to the filename.
References getdist.plots.GetDistPlotter._escapeLatex(), getdist.plots.GetDistPlotter.extra_artists, and getdist.plots.GetDistPlotter.fig.
finish_plot()
def getdist.plots.GetDistPlotter.finish_plot (self, legend_labels = None, legend_loc = None, line_offset = 0, legend_ncol = None, label_order = None, no_gap = False, no_extra_legend_space = False, no_tight = False)
Finish the current plot, adjusting subplot spacing and adding legend
:param legend_labels: The labels
:param legend_loc: The legend location, default from settings
:param line_offset: The offset of plotted lines to label (e.g. 1 to not label first line)
:param legend_ncol: The number of columns in the legend, defaults to 1
:param label_order: minus one to show legends in reverse order that lines were added, or a list giving specific order of line indices
:param no_gap: True if should leave no subplot padding in tight_layout
:param no_extra_legend_space: True to prevent making additional space above subplots for the legend
:param no_tight: don't use :func:`~matplotlib:matplotlib.pyplot.tight_layout` to adjust subplot positions
References getdist.plots.GetDistPlotter.add_legend(), getdist.plots.GetDistPlotter.extra_artists, getdist.plots.GetDistPlotter.plot_row, and getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter.plots_1d(), getdist.plots.GetDistPlotter.plots_2d(), getdist.plots.GetDistPlotter.plots_2d_triplets(), getdist.plots.GetDistPlotter.plots_3d(), getdist.plots.GetDistPlotter.rectangle_plot(), and getdist.plots.GetDistPlotter.triangle_plot().
get_param_array()
def getdist.plots.GetDistPlotter.get_param_array (self, root, params = None, renames = {})
Gets an array of :class:`~.paramnames.ParamInfo` for named params
:param root: The root name of the samples to use
:param params: the parameter names (if not specified, get all)
:param renames: optional dictionary mapping input names and equivalent names used by the samples
:return: list of :class:`~.paramnames.ParamInfo` instances for the parameters
References getdist.plots.GetDistPlotter.paramNamesForRoot().
Referenced by getdist.plots.GetDistPlotter.add_2d_contours(), getdist.plots.GetDistPlotter.add_2d_shading(), getdist.plots.GetDistPlotter.add_3d_scatter(), getdist.plots.GetDistPlotter.plot_2d(), getdist.plots.GetDistPlotter.plot_3d(), getdist.plots.GetDistPlotter.plots_1d(), getdist.plots.GetDistPlotter.plots_2d(), getdist.plots.GetDistPlotter.plots_3d_z(), and getdist.plots.GetDistPlotter.triangle_plot().
make_figure()
def getdist.plots.GetDistPlotter.make_figure (self, nplot = 1, nx = None, ny = None, xstretch = 1.0, ystretch = 1.0)
Makes a new figure.
:param nplot: number of subplots
:param nx: number of subplots in each row
:param ny: number of subplots in each column
:param xstretch: The parameter of how much to stretch the width, 1 is default
:param ystretch: The parameter of how much to stretch the height, 1 is default
:return: The plot_col, plot_row numbers of subplots for the figure
References CAMB_test_files.int, getdist.plots.SampleAnalysisGetDist.newPlot(), getdist.plots.MCSampleAnalysis.newPlot(), getdist.plots.GetDistPlotter.newPlot(), and getdist.plots.GetDistPlotter.plot_col.
Referenced by getdist.plots.GetDistPlotter.plot_1d(), getdist.plots.GetDistPlotter.plot_2d(), getdist.plots.GetDistPlotter.plot_3d(), getdist.plots.GetDistPlotter.plots_1d(), getdist.plots.GetDistPlotter.plots_2d(), getdist.plots.GetDistPlotter.plots_2d_triplets(), getdist.plots.GetDistPlotter.plots_3d(), getdist.plots.GetDistPlotter.rectangle_plot(), and getdist.plots.GetDistPlotter.triangle_plot().
newPlot()
def getdist.plots.GetDistPlotter.newPlot (self)
Resets the given plotter to make a new empty plot.
Referenced by getdist.plots.GetDistPlotter.make_figure().
param_latex_label()
def getdist.plots.GetDistPlotter.param_latex_label (self, root, name, labelParams = None)
Returns the latex label for given parameter.
:param root: root name of the samples having the parameter (or :class:`~.mcsamples.MCSamples` instance)
:param name:  The param name
:param labelParams: optional name of .paramnames file to override parameter name labels
:return: The latex label
References getdist.plots.GetDistPlotter._check_param(), getdist.plots.GetDistPlotter.add_legend(), and getdist.plots.GetDistPlotter.sampleAnalyser.
paramBoundsForRoot()
def getdist.plots.GetDistPlotter.paramBoundsForRoot (self, root)
Get any hard prior bounds for the parameters with root file name
:param root: The root name to be used
:return: object with getUpper() and getLower() bounds functions
References getdist.plots.GetDistPlotter.param_bounds_sets, and getdist.plots.GetDistPlotter.sampleAnalyser.
Referenced by getdist.plots.GetDistPlotter._check_param_ranges().
paramNamesForRoot()
def getdist.plots.GetDistPlotter.paramNamesForRoot (self, root)
Get the parameter names and labels :class:`~.paramnames.ParamNames` instance for the given root name
:param root: The root name of the samples.
:return: :class:`~.paramnames.ParamNames` instance
References getdist.plots.GetDistPlotter.param_name_sets, getdist.plots.GetDistPlotter.sampleAnalyser, and getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter._check_param(), getdist.plots.GetDistPlotter.add_3d_scatter(), and getdist.plots.GetDistPlotter.get_param_array().
plot_1d()
def getdist.plots.GetDistPlotter.plot_1d (self, roots, param, marker = None, marker_color = None, label_right = False, no_ylabel = False, no_ytick = False, no_zero = False, normalized = False, param_renames = {}, kwargs)
Make a single 1D plot with marginalized density lines.
:param roots: root name or :class:`~.mcsamples.MCSamples` instance (or list of any of either of these) for the samples to plot
:param param: the parameter name to plot
:param marker: If set, places a marker at given coordinate.
:param marker_color: If set, sets the marker color.
:param label_right: If True, label the y axis on the right rather than the left
:param no_ylabel: If True excludes the label on the y axis
:param no_ytick: If True show no y ticks
:param no_zero: If true does not show tick label at zero on y axis
:param normalized: plot normalized densities (if False, densities normalized to peak at 1)
:param param_renames: optional dictionary mapping input parameter names to equivalent names used by the samples
:param kwargs: additional optional keyword arguments:
* **lims**: optional limits for x range of the plot [xmin, xmax]
* **ls** : list of line styles for the different lines plotted
* **colors**: list of colors for the different lines plotted
* **lws**: list of line widths for the different lines plotted
* **alphas**: list of alphas for the different lines plotted
* **line_args**: a list of dictionaries with settings for each set of lines
* arguments for :func:`~GetDistPlotter.setAxes`
.. plot::
   :include-source:
    from getdist import plots, gaussian_mixtures
    samples1, samples2 = gaussian_mixtures.randomTestMCSamples(ndim=2, nMCSamples=2)
    g = plots.getSinglePlotter(width_inch=4)
    g.plot_1d([samples1, samples2], 'x0', marker=0)
.. plot::
   :include-source:
    from getdist import plots, gaussian_mixtures
    samples1, samples2 = gaussian_mixtures.randomTestMCSamples(ndim=2, nMCSamples=2)
    g = plots.getSinglePlotter(width_inch=3)
    g.plot_1d([samples1, samples2], 'x0', normalized=True, colors=['green','black'])
References getdist.plots.GetDistPlotter._check_param(), getdist.plots.GetDistPlotter._check_param_ranges(), getdist.plots.GetDistPlotter._make_line_args(), getdist.plots.GetDistPlotter._updateLimit(), getdist.plots.GetDistPlotter.add_1d(), getdist.plots.GetDistPlotter.add_x_marker(), getdist.plots.GetDistPlotter.fig, getdist.plots.GetDistPlotter.make_figure(), getdist.plots.makeList(), getdist.plots.GetDistPlotter.setAxes(), and getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter.plots_1d(), getdist.plots.GetDistPlotter.set_ylabel(), and getdist.plots.GetDistPlotter.triangle_plot().
plot_2d()
def getdist.plots.GetDistPlotter.plot_2d (self, roots, param1 = None, param2 = None, param_pair = None, shaded = False, add_legend_proxy = True, line_offset = 0, proxy_root_exclude = [], kwargs)
Create a single 2D line, contour or filled plot.
:param roots: root name or :class:`~.mcsamples.MCSamples` instance (or list of any of either of these) for the samples to plot
:param param1: x parameter name
:param param2:  y parameter name
:param param_pair: An [x,y] pair of params; can be set instead of param1 and param2
:param shaded: True if plot should be a shaded density plot (for the first samples plotted)
:param add_legend_proxy: True if should add to the legend proxy
:param line_offset: line_offset if not adding first contours to plot
:param proxy_root_exclude: any root names not to include when adding to the legend proxy
:param kwargs: additional optional arguments:
* **filled**: True for filled contours
* **lims**: list of limits for the plot [xmin, xmax, ymin, ymax]
* **ls** : list of line styles for the different sample contours plotted
* **colors**: list of colors for the different sample contours plotted
* **lws**: list of line widths for the different sample contours plotted
* **alphas**: list of alphas for the different sample contours plotted
* **line_args**: a list of dictionaries with settings for each set of contours
* arguments for :func:`~GetDistPlotter.setAxes`
:return: The xbounds, ybounds of the plot.
.. plot::
   :include-source:
    from getdist import plots, gaussian_mixtures
    samples1, samples2 = gaussian_mixtures.randomTestMCSamples(ndim=4, nMCSamples=2)
    g = plots.getSinglePlotter(width_inch = 4)
    g.plot_2d([samples1,samples2], 'x1', 'x2', filled=True);
References getdist.plots.GetDistPlotter._check_param_ranges(), getdist.plots.GetDistPlotter._make_contour_args(), getdist.gaussian_mixtures.Mixture2D._updateLimits(), getdist.plots.GetDistPlotter._updateLimits(), getdist.plots.GetDistPlotter.add_2d_contours(), getdist.plots.GetDistPlotter.add_2d_shading(), getdist.plots.GetDistPlotter.fig, getdist.plots.GetDistPlotter.get_param_array(), getdist.plots.GetDistPlotter.make_figure(), getdist.plots.makeList(), getdist.plots.GetDistPlotter.setAxes(), and getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter._make_contour_args(), getdist.plots.GetDistPlotter.plots_2d(), getdist.plots.GetDistPlotter.plots_2d_triplets(), getdist.plots.GetDistPlotter.rectangle_plot(), and getdist.plots.GetDistPlotter.triangle_plot().
plot_2d_scatter()
def getdist.plots.GetDistPlotter.plot_2d_scatter (self, roots, param1, param2, color = 'k', line_offset = 0, add_legend_proxy = True, kwargs)
Make a 2D sample scatter plot.
If roots is a list of more than one, additional densities are plotted as contour lines.
:param roots: root name or :class:`~.mcsamples.MCSamples` instance (or list of any of either of these) for the samples to plot
:param param1: name of x parameter
:param param2: name of y parameter
:param color: color to plot the samples
:param line_offset: The line index offset for added contours
:param add_legend_proxy: True if should add a legend proxy
:param kwargs: additional optional arguments:
* **filled**: True for filled contours for second and later items in roots
* **lims**: limits for the plot [xmin, xmax, ymin, ymax]
* **ls** : list of line styles for the different sample contours plotted
* **colors**: list of colors for the different sample contours plotted
* **lws**: list of linewidths for the different sample contours plotted
* **alphas**: list of alphas for the different sample contours plotted
* **line_args**: a list of dict with settings for contours from each root
References getdist.plots.GetDistPlotter.plot_3d().
plot_3d()
def getdist.plots.GetDistPlotter.plot_3d (self, roots, params = None, params_for_plots = None, color_bar = True, line_offset = 0, add_legend_proxy = True, kwargs)
Make a 2D scatter plot colored by the value of a third parameter (a 3D plot).
If roots is a list of more than one, additional densities are plotted as contour lines.
:param roots: root name or :class:`~.mcsamples.MCSamples` instance (or list of any of either of these) for the samples to plot
:param params: list with the three parameter names to plot (x, y, color)
:param params_for_plots: list of parameter triplets to plot for each root plotted; more general alternative to params
:param color_bar: True if should include a color bar
:param line_offset: The line index offset for added contours
:param add_legend_proxy: True if should add a legend proxy
:param kwargs: additional optional arguments:
* **filled**: True for filled contours for second and later items in roots
* **lims**: limits for the plot [xmin, xmax, ymin, ymax]
* **ls** : list of line styles for the different sample contours plotted
* **colors**: list of colors for the different sample contours plotted
* **lws**: list of linewidths for the different sample contours plotted
* **alphas**: list of alphas for the different sample contours plotted
* **line_args**: a list of dict with settings for contours from each root
* arguments for :func:`~GetDistPlotter.add_colorbar`
.. plot::
   :include-source:
    from getdist import plots, gaussian_mixtures
    samples1, samples2 = gaussian_mixtures.randomTestMCSamples(ndim=3, nMCSamples=2)
    g = plots.getSinglePlotter(width_inch=4)
    g.plot_3d([samples1, samples2], ['x0','x1','x2']);
References getdist.plots.GetDistPlotter._check_param_ranges(), getdist.plots.GetDistPlotter._make_contour_args(), getdist.gaussian_mixtures.Mixture2D._updateLimits(), getdist.plots.GetDistPlotter._updateLimits(), getdist.plots.GetDistPlotter.add_2d_contours(), getdist.plots.GetDistPlotter.add_3d_scatter(), getdist.plots.GetDistPlotter.fig, getdist.plots.GetDistPlotter.get_param_array(), getdist.plots.GetDistPlotter.make_figure(), getdist.plots.makeList(), getdist.plots.GetDistPlotter.setAxes(), and copyGridFiles.zip.
Referenced by getdist.plots.GetDistPlotter.plot_2d_scatter(), getdist.plots.GetDistPlotter.plots_3d(), and getdist.plots.GetDistPlotter.triangle_plot().
plots_1d()
def getdist.plots.GetDistPlotter.plots_1d (self, roots, params = None, legend_labels = None, legend_ncol = None, label_order = None, nx = None, paramList = None, roots_per_param = False, share_y = None, markers = None, xlims = None, param_renames = {}, kwargs)
Make an array of 1D marginalized density subplots
:param roots: root name or :class:`~.mcsamples.MCSamples` instance (or list of any of either of these) for the samples to plot
:param params: list of names of parameters to plot
:param legend_labels: list of legend labels
:param legend_ncol: Number of columns for the legend.
:param label_order: minus one to show legends in reverse order that lines were added, or a list giving specific order of line indices
:param nx: number of subplots per row
:param paramList: name of .paramnames file listing specific subset of parameters to plot
:param roots_per_param: True to use a different set of samples for each parameter:
      plots param[i] using roots[i] (where roots[i] is the list of sample root names to use for plotting parameter i).
      This is useful for example for  plotting one-parameter extensions of a baseline model, each with various data combinations.
:param share_y: True for subplots to share a common y axis with no horizontal space between subplots
:param markers: optional dict giving vertical markers index by parameter, or a list of marker values for each parameter plotted
:param xlims: list of [min,max] limits for the range of each parameter plot
:param param_renames: optional dictionary holding mapping between input names and equivalent names used in the samples.
:param kwargs: optional keyword arguments for :func:`~GetDistPlotter.plot_1d`
:return: The plot_col, plot_row subplot dimensions of the new figure
.. plot::
   :include-source:
    from getdist import plots, gaussian_mixtures
    samples1, samples2 = gaussian_mixtures.randomTestMCSamples(ndim=4, nMCSamples=2)
    g = plots.getSubplotPlotter()
    g.plots_1d([samples1, samples2], ['x0', 'x1', 'x2'], nx=3, share_y=True, legend_ncol =2,
         markers={'x1':0}, colors=['red', 'green'], ls=['--', '-.'])
References getdist.plots.GetDistPlotter._check_param(), getdist.plots.GetDistPlotter._default_legend_labels(), getdist.plots.GetDistPlotter._paramNameListFromFile(), getdist.plots.GetDistPlotter._spaceTicks(), getdist.plots.GetDistPlotter._subplot_number(), getdist.plots.GetDistPlotter.finish_plot(), getdist.plots.GetDistPlotter.get_param_array(), getdist.plots.GetDistPlotter.make_figure(), getdist.plots.makeList(), getdist.plots.GetDistPlotter.plot_1d(), getdist.plots.GetDistPlotter.plot_col, getdist.plots.GetDistPlotter.plots_2d(), getdist.plots.GetDistPlotter.settings, and copyGridFiles.zip.
Referenced by getdist.plots.GetDistPlotter._default_legend_labels().
plots_2d()
def getdist.plots.GetDistPlotter.plots_2d (self, roots, param1 = None, params2 = None, param_pairs = None, nx = None, legend_labels = None, legend_ncol = None, label_order = None, filled = False, shaded = False, kwargs)
Make an array of 2D line, filled or contour plots.
:param roots: root name or :class:`~.mcsamples.MCSamples` instance (or list of either of these) for the samples to plot
:param param1: x parameter to plot
:param params2: list of y parameters to plot against x
:param param_pairs: list of [x,y] parameter pairs to plot; either specify param1, param2, or param_pairs
:param nx: number of subplots per row
:param legend_labels: The labels used for the legend.
:param legend_ncol: The amount of columns in the legend.
:param label_order: minus one to show legends in reverse order that lines were added, or a list giving specific order of line indices
:param filled: True to plot filled contours
:param shaded: True to shade by the density for the first root plotted
:param kwargs: optional keyword arguments for :func:`~GetDistPlotter.plot_2d`
:return: The plot_col, plot_row subplot dimensions of the new figure
.. plot::
   :include-source:
    from getdist import plots, gaussian_mixtures
    samples1, samples2 = gaussian_mixtures.randomTestMCSamples(ndim=4, nMCSamples=2)
    g = plots.getSubplotPlotter(subplot_size=4)
    g.settings.legend_frac_subplot_margin = 0.05
    g.plots_2d([samples1, samples2], param_pairs=[['x0', 'x1'], ['x1', 'x2']],
                    nx=2, legend_ncol=2, colors=['blue', 'red'])
References getdist.plots.GetDistPlotter._check_param(), getdist.plots.GetDistPlotter._default_legend_labels(), getdist.plots.GetDistPlotter._subplot_number(), getdist.plots.GetDistPlotter.finish_plot(), getdist.plots.GetDistPlotter.get_param_array(), getdist.plots.GetDistPlotter.make_figure(), getdist.plots.makeList(), and getdist.plots.GetDistPlotter.plot_2d().
Referenced by getdist.plots.GetDistPlotter.plots_1d().
plots_2d_triplets()
def getdist.plots.GetDistPlotter.plots_2d_triplets (self, root_params_triplets, nx = None, filled = False, x_lim = None)
Creates an array of 2D plots, where each plot uses different samples, x and y parameters
:param root_params_triplets: a list of (root, x, y) giving sample root names, and x and y parameter names to plot in each subplot
:param nx: number of subplots per row
:param filled:  True for filled contours
:param x_lim: limits for all the x axes.
:return: The plot_col, plot_row subplot dimensions of the new figure
References getdist.plots.GetDistPlotter._subplot_number(), getdist.plots.GetDistPlotter.finish_plot(), getdist.plots.GetDistPlotter.make_figure(), and getdist.plots.GetDistPlotter.plot_2d().
plots_3d()
def getdist.plots.GetDistPlotter.plots_3d (self, roots, param_sets, nx = None, legend_labels = None, kwargs)
Create multiple 3D subplots
:param roots: root name or :class:`~.mcsamples.MCSamples` instance (or list of any of either of these) for the samples to plot
:param param_sets: A list of triplets of parameter names to plot [(x,y, color), (x2,y2,color2)..]
:param nx: number of subplots per row
:param legend_labels: list of legend labels
:param kwargs: keyword arguments for  :func:`~GetDistPlotter.plot_3d`
:return: The plot_col, plot_row subplot dimensions of the new figure
.. plot::
   :include-source:
    from getdist import plots, gaussian_mixtures
    samples1, samples2 = gaussian_mixtures.randomTestMCSamples(ndim=5, nMCSamples=2)
    g = plots.getSubplotPlotter(subplot_size=4)
    g.plots_3d([samples1, samples2], [['x0', 'x1', 'x2'], ['x3', 'x4', 'x2']], nx=2);
References getdist.plots.GetDistPlotter._check_param(), getdist.plots.GetDistPlotter._default_legend_labels(), getdist.plots.GetDistPlotter._subplot_number(), getdist.plots.GetDistPlotter.finish_plot(), getdist.plots.GetDistPlotter.make_figure(), getdist.plots.makeList(), and getdist.plots.GetDistPlotter.plot_3d().
Referenced by getdist.plots.GetDistPlotter.plots_3d_z().
plots_3d_z()
def getdist.plots.GetDistPlotter.plots_3d_z (self, roots, param_x, param_y, param_z = None, max_z = None, kwargs)
Make set of sample scatter subplots of param_x against param_y, each coloured by values of parameters in param_z (all if None).
Any second or more samples in root are shown as contours
:param roots: root name or :class:`~.mcsamples.MCSamples` instance (or list of any of either of these) for the samples to plot
:param param_x: x parameter name
:param param_y: y parameter name
:param param_z: list of parameter to names to color samples in each subplot (default: all)
:param max_z: The maximum number of z parameters we should use.
:param kwargs: keyword arguments for :func:`~GetDistPlotter.plot_3d`
:return: The plot_col, plot_row subplot dimensions of the new figure
References getdist.plots.GetDistPlotter.get_param_array(), getdist.plots.makeList(), and getdist.plots.GetDistPlotter.plots_3d().
rectangle_plot()
def getdist.plots.GetDistPlotter.rectangle_plot (self, xparams, yparams, yroots = None, roots = None, plot_roots = None, plot_texts = None, xmarkers = None, ymarkers = None, marker_args = {}, param_limits = {}, legend_labels = None, legend_ncol = None, label_order = None, kwargs)
Make a grid of 2D plots.
A rectangle plot shows all x parameters plotted againts all y parameters in a grid of subplots with no spacing.
Set roots to use the same set of roots for every plot in the rectangle, or set
yroots (list of list of roots) to use different set of roots for each row of the plot; alternatively
plot_roots allows you to specify explicitly (via list of list of list of roots) the set of roots for each individual subplot
:param xparams: list of parameters for the x axes
:param yparams: list of parameters for the y axes
:param yroots: (list of list of roots) allows use of different set of root names for each row of the plot;
       set either roots or yroots
:param roots: list of root names or :class:`~.mcsamples.MCSamples` instances.
Uses the same set of roots for every plot in the rectangle; set either roots or yroots.
:param plot_roots: Allows you to specify (via list of list of list of roots) the set of roots for each individual subplot
:param plot_texts: a 2D array (or list of lists) of a text label to put in each subplot (use a None entry to skip one)
:param xmarkers: list of markers for the x axis
:param ymarkers: list of markers for the y axis
:param marker_args: arguments for :func:`~GetDistPlotter.add_x_marker` and :func:`~GetDistPlotter.add_y_marker`
:param param_limits: a dictionary holding a mapping from parameter names to axis limits for that parameter
:param legend_labels: list of labels for the legend
:param legend_ncol: The number of columns for the legend
:param label_order: minus one to show legends in reverse order that lines were added, or a list giving specific order of line indices
:param kwargs: arguments for :func:`~GetDistPlotter.plot_2d`.
:return: the 2D list of :class:`~matplotlib:matplotlib.axes.Axes` created
.. plot::
   :include-source:
    from getdist import plots, gaussian_mixtures
    samples1, samples2 = gaussian_mixtures.randomTestMCSamples(ndim=4, nMCSamples=2)
    g = plots.getSubplotPlotter()
    g.rectangle_plot(['x0','x1'], ['x2','x3'], roots = [samples1, samples2], filled=True)
References getdist.plots.GetDistPlotter._default_legend_labels(), getdist.plots.GetDistPlotter._spaceTicks(), getdist.plots.GetDistPlotter._subplot(), getdist.gaussian_mixtures.Mixture2D._updateLimits(), getdist.plots.GetDistPlotter._updateLimits(), getdist.plots.GetDistPlotter.add_text_left(), getdist.plots.GetDistPlotter.add_x_marker(), getdist.plots.GetDistPlotter.add_y_marker(), getdist.plots.GetDistPlotter.finish_plot(), getdist.plots.GetDistPlotter.make_figure(), getdist.plots.makeList(), getdist.plots.GetDistPlotter.plot_2d(), and copyGridFiles.zip.
Referenced by getdist.plots.GetDistPlotter.triangle_plot().
rotate_yticklabels()
def getdist.plots.GetDistPlotter.rotate_yticklabels (self, ax = None, rotation = 90)
Rotates the y-tick labels by given rotation (degrees)
:param ax: the :class:`~matplotlib:matplotlib.axes.Axes` instance to use, defaults to current axes.
:param rotation: How much to rotate in degrees.
Referenced by getdist.plots.GetDistPlotter.add_colorbar().
set_xlabel()
def getdist.plots.GetDistPlotter.set_xlabel (self, param, ax = None)
Sets the label for the x axis.
:param param: the :class:`~.paramnames.ParamInfo` for the x axis parameter
:param ax: the :class:`~matplotlib:matplotlib.axes.Axes` instance to use, defaults to current axes.
References getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter.setAxes().
set_ylabel()
def getdist.plots.GetDistPlotter.set_ylabel (self, param, ax = None)
Sets the label for the y axis.
:param param: the :class:`~.paramnames.ParamInfo` for the y axis parameter
:param ax: the :class:`~matplotlib:matplotlib.axes.Axes` instance to use, defaults to current axes.
References getdist.plots.GetDistPlotter.plot_1d(), and getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter.setAxes(), and getdist.plots.GetDistPlotter.triangle_plot().
setAxes()
def getdist.plots.GetDistPlotter.setAxes (self, params = [], lims = None, do_xlabel = True, do_ylabel = True, no_label_no_numbers = False, pos = None, prune = None, color_label_in_axes = False, ax = None, other_args)
Set the axis labels and ticks, and various styles. Do not usually need to call this directly.
:param params: [x,y] list of the :class:`~.paramnames.ParamInfo` for the x and y parameters to use for labels
:param lims: optional [xmin, xmax, ymin, ymax] to fix specific limits for the axes
:param do_xlabel: True if should include label for x axis.
:param do_ylabel: True if should include label for y axis.
:param no_label_no_numbers: True to hide tick labels
:param pos: optional position of the axes ['left' | 'bottom' | 'width' | 'height']
:param prune: Parameter for MaxNLocator constructor,  ['lower' | 'upper' | 'both' | None]
:param color_label_in_axes: If True, and params has at last three entries, puts text in the axis to label the third parameter
:param ax: the :class:`~matplotlib:matplotlib.axes.Axes` instance to use, defaults to current axes.
:param other_args: Not used, just quietly ignore so that setAxes can be passed general kwargs
:return: an :class:`~matplotlib:matplotlib.axes.Axes` instance
References getdist.plots.GetDistPlotter._setAxisProperties(), getdist.plots.GetDistPlotter.add_text(), getdist.plots.GetDistPlotter.set_xlabel(), getdist.plots.GetDistPlotter.set_ylabel(), and getdist.plots.GetDistPlotter.settings.
Referenced by getdist.plots.GetDistPlotter._setAxisProperties(), getdist.plots.GetDistPlotter.plot_1d(), getdist.plots.GetDistPlotter.plot_2d(), and getdist.plots.GetDistPlotter.plot_3d().
show_all_settings()
def getdist.plots.GetDistPlotter.show_all_settings (self)
Prints settings and library versions
References getdist.plots.GetDistPlotter.settings.
triangle_plot()
def getdist.plots.GetDistPlotter.triangle_plot (self, roots, params = None, legend_labels = None, plot_3d_with_param = None, filled = False, shaded = False, contour_args = None, contour_colors = None, contour_ls = None, contour_lws = None, line_args = None, label_order = None, legend_ncol = None, legend_loc = None, upper_roots = None, upper_kwargs = {}, kwargs)
Make a trianglular array of 1D and 2D plots.
A triangle plot is an array of subplots with 1D plots along the diagonal, and 2D plots in the lower corner.
The upper triangle can also be used by setting upper_roots.
:param roots: root name or :class:`~.mcsamples.MCSamples` instance (or list of any of either of these) for the samples to plot
:param params: list of parameters to plot (default: all, can also use glob patterns to match groups of parameters)
:param legend_labels: list of legend labels
:param plot_3d_with_param: for the 2D plots, make sample scatter plot, with samples colored by this parameter name (to make a '3D' plot)
:param filled: True for filled contours
:param shaded: plot shaded density for first root (cannot be used with filled)
:param contour_args: optional dict (or list of dict) with arguments for each 2D plot (e.g. specifying color, alpha,etc)
:param contour_colors: list of colors for plotting contours (for each root)
:param contour_ls: list of Line styles for contours (for each root)
:param contour_lws: list of Line widths for contours (for each root)
:param line_args: dict (or list of dict) with arguments for each 2D plot (e.g. specifying ls, lw, color, etc)
:param label_order: minus one to show legends in reverse order that lines were added, or a list giving specific order of line indices
:param legend_ncol: The number of columns for the legend
:param legend_loc: The location for the legend
:param upper_roots: set to fill the upper triangle with subplots using this list of sample root names
             (TODO: this needs some work to easily work without a lot of tweaking)
:param upper_kwargs: list of dict for arguments when making upper-triangle 2D plots
:param kwargs: optional keyword arguments for :func:`~GetDistPlotter.plot_2d` or :func:`~GetDistPlotter.plot_3d` (lower triangle only)
.. plot::
   :include-source:
    from getdist import plots, gaussian_mixtures
    samples1, samples2 = gaussian_mixtures.randomTestMCSamples(ndim=4, nMCSamples=2)
    g = plots.getSubplotPlotter()
    g.triangle_plot([samples1, samples2], filled=True, legend_labels = ['Contour 1', 'Contour 2'])
.. plot::
   :include-source:
    from getdist import plots, gaussian_mixtures
    samples1, samples2 = gaussian_mixtures.randomTestMCSamples(ndim=4, nMCSamples=2)
    g = plots.getSubplotPlotter()
    g.triangle_plot([samples1, samples2], ['x0','x1','x2'], plot_3d_with_param='x3')
References getdist.plots.GetDistPlotter._check_param(), getdist.plots.GetDistPlotter._default_legend_labels(), getdist.plots.GetDistPlotter._make_contour_args(), getdist.plots.GetDistPlotter._make_line_args(), getdist.plots.GetDistPlotter._setAxisProperties(), getdist.plots.GetDistPlotter._spaceTicks(), getdist.plots.GetDistPlotter._subplot(), getdist.plots.GetDistPlotter.add_colorbar_label(), getdist.plots.GetDistPlotter.fig, getdist.plots.GetDistPlotter.finish_plot(), getdist.plots.GetDistPlotter.get_param_array(), getdist.plots.GetDistPlotter.last_scatter, getdist.plots.GetDistPlotter.make_figure(), getdist.plots.makeList(), getdist.plots.GetDistPlotter.plot_1d(), getdist.plots.GetDistPlotter.plot_2d(), getdist.plots.GetDistPlotter.plot_3d(), getdist.plots.GetDistPlotter.rectangle_plot(), getdist.plots.GetDistPlotter.set_ylabel(), getdist.plots.GetDistPlotter.settings, getdist.plots.GetDistPlotter.subplots, and copyGridFiles.zip.
Referenced by getdist.plots.GetDistPlotter._spaceTicks().
Member Data Documentation
chain_dir
getdist.plots.GetDistPlotter.chain_dir
contours_added
getdist.plots.GetDistPlotter.contours_added
Referenced by getdist.plots.GetDistPlotter.add_2d_contours(), and getdist.plots.GetDistPlotter.add_legend().
extra_artists
getdist.plots.GetDistPlotter.extra_artists
Referenced by getdist.plots.GetDistPlotter.export(), and getdist.plots.GetDistPlotter.finish_plot().
fig
getdist.plots.GetDistPlotter.fig
Referenced by getdist.plots.GetDistPlotter.add_text(), getdist.plots.GetDistPlotter.export(), getdist.plots.GetDistPlotter.plot_1d(), getdist.plots.GetDistPlotter.plot_2d(), getdist.plots.GetDistPlotter.plot_3d(), and getdist.plots.GetDistPlotter.triangle_plot().
last_colorbar
getdist.plots.GetDistPlotter.last_colorbar
last_scatter
getdist.plots.GetDistPlotter.last_scatter
Referenced by getdist.plots.GetDistPlotter.triangle_plot().
legend
getdist.plots.GetDistPlotter.legend
lines_added
getdist.plots.GetDistPlotter.lines_added
Referenced by getdist.plots.GetDistPlotter.add_1d(), and getdist.plots.GetDistPlotter.add_legend().
param_bounds_sets
getdist.plots.GetDistPlotter.param_bounds_sets
Referenced by getdist.plots.GetDistPlotter.paramBoundsForRoot().
param_name_sets
getdist.plots.GetDistPlotter.param_name_sets
Referenced by getdist.plots.GetDistPlotter.paramNamesForRoot().
plot_col
getdist.plots.GetDistPlotter.plot_col
Referenced by getdist.plots.GetDistPlotter._subplot(), getdist.plots.GetDistPlotter._subplot_number(), getdist.plots.GetDistPlotter.make_figure(), and getdist.plots.GetDistPlotter.plots_1d().
plot_data
getdist.plots.GetDistPlotter.plot_data
plot_row
getdist.plots.GetDistPlotter.plot_row
Referenced by getdist.plots.GetDistPlotter._subplot(), getdist.plots.GetDistPlotter._subplot_number(), and getdist.plots.GetDistPlotter.finish_plot().
sampleAnalyser
getdist.plots.GetDistPlotter.sampleAnalyser
Referenced by getdist.plots.GetDistPlotter.add_1d(), getdist.plots.GetDistPlotter.add_2d_contours(), getdist.plots.GetDistPlotter.add_2d_shading(), getdist.plots.GetDistPlotter.add_3d_scatter(), getdist.plots.GetDistPlotter.param_latex_label(), getdist.plots.GetDistPlotter.paramBoundsForRoot(), and getdist.plots.GetDistPlotter.paramNamesForRoot().
settings
getdist.plots.GetDistPlotter.settings
Referenced by getdist.plots.GetDistPlotter._get_alpha2D(), getdist.plots.GetDistPlotter._get_dashes_for_ls(), getdist.plots.GetDistPlotter._get_default_ls(), getdist.plots.GetDistPlotter._get_line_styles(), getdist.plots.GetDistPlotter._get_plot_args(), getdist.plots.GetDistPlotter._set_locator(), getdist.plots.GetDistPlotter._setAxisProperties(), getdist.plots.GetDistPlotter._spaceTicks(), getdist.plots.GetDistPlotter.add_1d(), getdist.plots.GetDistPlotter.add_2d_contours(), getdist.plots.GetDistPlotter.add_2d_shading(), getdist.plots.GetDistPlotter.add_colorbar(), getdist.plots.GetDistPlotter.add_colorbar_label(), getdist.plots.GetDistPlotter.add_legend(), getdist.plots.GetDistPlotter.add_line(), getdist.plots.GetDistPlotter.add_x_marker(), getdist.plots.GetDistPlotter.add_y_marker(), getdist.plots.GetDistPlotter.finish_plot(), planckStyle.planckPlotter.getJobItem(), getdist.plots.GetDistPlotter.paramNamesForRoot(), getdist.plots.GetDistPlotter.plot_1d(), getdist.plots.GetDistPlotter.plot_2d(), getdist.plots.GetDistPlotter.plots_1d(), getdist.plots.GetDistPlotter.set_xlabel(), getdist.plots.GetDistPlotter.set_ylabel(), getdist.plots.GetDistPlotter.setAxes(), getdist.plots.GetDistPlotter.show_all_settings(), and getdist.plots.GetDistPlotter.triangle_plot().
subplots
getdist.plots.GetDistPlotter.subplots
Referenced by getdist.plots.GetDistPlotter._subplot(), getdist.plots.GetDistPlotter._subplot_number(), getdist.plots.GetDistPlotter.add_text(), and getdist.plots.GetDistPlotter.triangle_plot().
The documentation for this class was generated from the following file:
/home/ealmaraz/software/cosmomc/bde/v3.1/python/getdist/plots.py