cosmomc_bde_v3p1: planckStyle.planckPlotter Class Reference
planckStyle.planckPlotter Class Reference
Public Member Functions
def getBatch (self)
def doExport (self, fname=None, adir=None, watermark=None, tag=None)
def export (self, fname=None, tag=None)
def exportExtra (self, fname=None)
def getRoot (self, paramtag, datatag, returnJobItem=False)
def getJobItem (self, paramtag, datatag)
Public Attributes
batch
Member Function Documentation
doExport()
def planckStyle.planckPlotter.doExport (self, fname = None, adir = None, watermark = None, tag = None)
References planckStyle.planckPlotter.export().
Referenced by planckStyle.planckPlotter.export(), and planckStyle.planckPlotter.exportExtra().
export()
def planckStyle.planckPlotter.export (self, fname = None, tag = None)
References planckStyle.planckPlotter.doExport().
Referenced by planckStyle.planckPlotter.doExport().
exportExtra()
def planckStyle.planckPlotter.exportExtra (self, fname = None)
References planckStyle.planckPlotter.doExport().
getBatch()
def planckStyle.planckPlotter.getBatch (self)
Referenced by planckStyle.planckPlotter.getRoot().
getJobItem()
def planckStyle.planckPlotter.getJobItem (self, paramtag, datatag)
References planckStyle.planckPlotter.getRoot(), and getdist.plots.GetDistPlotter.settings.
getRoot()
def planckStyle.planckPlotter.getRoot (self, paramtag, datatag, returnJobItem = False)
References planckStyle.planckPlotter.getBatch().
Referenced by planckStyle.planckPlotter.getJobItem().
Member Data Documentation
batch
planckStyle.planckPlotter.batch
The documentation for this class was generated from the following file:
/home/ealmaraz/software/cosmomc/bde/v3.1/python/planckStyle.py