cosmomc_bde_v3p1: /home/ealmaraz/software/cosmomc/bde/v3.1/camb/equations_bde_v3_original.f90 File Reference
equations_bde_v3_original.f90 File Reference
Data Types
type gaugeinterface::evolutionvars
Modules
module lambdageneral
module quint
module gaugeinterface
Functions/Subroutines
subroutine lambdageneral::darkenergy_readparams (Ini)
subroutine quint::bde_nxyl
subroutine quint::bde_xylata (a, x, y, l)
subroutine quint::bde_wde0 (P, wBDE0)
subroutine quint::bde_h0 (P, H0)
real(dl) function quint::bde_omegade0 (x, y, l)
real(dl) function quint::vofphi (phi, deriv)
subroutine quint::bde_background
subroutine quint::quint_valsata (a, aphi, aphidot)
real(dl) function getomegak ()
subroutine init_background
real(dl) function dtauda (a)
subroutine gaugeinterface::gaugeinterface_scalev (EV, y, tau, tauend, tol1, ind, c, w)
integer function gaugeinterface::next_nu_nq (nq)
recursive subroutine gaugeinterface::gaugeinterface_evolvescal (EV, tau, y, tauend, tol1, ind, c, w)
subroutine gaugeinterface::gaugeinterface_evolvetens (EV, tau, y, tauend, tol1, ind, c, w)
real(dl) function gaugeinterface::deltatimemaxed (a1, a2, tol)
subroutine gaugeinterface::gaugeinterface_init
subroutine gaugeinterface::setupscalararrayindices (EV, max_num_eqns)
subroutine gaugeinterface::copyscalarvariablearray (y, yout, EV, EVout)
subroutine gaugeinterface::setuptensorarrayindices (EV, maxeq)
subroutine gaugeinterface::copytensorvariablearray (y, yout, EV, EVout)
subroutine gaugeinterface::getnumeqns (EV)
subroutine gaugeinterface::switchtomassivenuapprox (EV, y, nu_i)
subroutine gaugeinterface::massivenuvarsout (EV, y, yprime, a, grho, gpres, dgrho, dgq, dgpi, gdpi_diff, pidot_sum, clxnu_all)
subroutine gaugeinterface::nu_integrate_l012 (EV, y, a, nu_i, drhonu, fnu, dpnu, pinu)
subroutine gaugeinterface::nu_pinudot (EV, y, ydot, a, adotoa, nu_i, pinudot)
real(dl) function gaugeinterface::nu_pi (EV, y, a, nu_i)
subroutine gaugeinterface::nu_intvsq (EV, y, a, nu_i, G11, G30)
subroutine gaugeinterface::massivenuvars (EV, y, a, grho, gpres, dgrho, dgq, wnu_arr)
subroutine gaugeinterface::output (EV, y, j, tau, sources)
subroutine gaugeinterface::outputt (EV, yt, n, j, tau, dt, dte, dtb)
subroutine gaugeinterface::outputv (EV, yv, n, j, tau, dt, dte, dtb)
subroutine gaugeinterface::initial (EV, y, tau)
subroutine gaugeinterface::initialt (EV, yt, tau)
subroutine gaugeinterface::initialv (EV, yv, tau)
subroutine gaugeinterface::outtransf (EV, y, tau, Arr)
subroutine gaugeinterface::derivs (EV, n, tau, ay, ayprime)
subroutine gaugeinterface::derivsv (EV, n, tau, yv, yvprime)
subroutine gaugeinterface::derivst (EV, n, tau, ayt, aytprime)
Function/Subroutine Documentation
dtauda()
real(dl) function dtauda (real(dl), intent(in) a)
References modelparams::ac, modelparams::accuracyboost, modelparams::adotrad, modelparams::alphabde, gaugeinterface::basic_num_eqns, gaugeinterface::copyscalarvariablearray(), gaugeinterface::copytensorvariablearray(), modelparams::cosfunc(), modelparams::cp, thermodata::cs2, lambdageneral::cs2_lam, modeldata::ctransscal, thermodata::ddvis, modelparams::deltatime(), gaugeinterface::deltatimemaxed(), gaugeinterface::denl, gaugeinterface::derivs(), gaugeinterface::derivst(), gaugeinterface::derivsv(), gaugeinterface::dolateradtruncation, thermodata::dopac, gaugeinterface::dotensorneutrinos, dtauda(), dverk(), thermodata::dvis, gaugeinterface::ep0, gaugeinterface::epsw, errors::error_evolution, constants::ev, thermodata::expmmu, modelparams::f_k(), modelparams::fixq, gaugeinterface::gaugeinterface_evolvescal(), gaugeinterface::gaugeinterface_scalev(), errors::global_error_flag, errors::globalerror(), modelparams::grhob, modelparams::grhoc, modelparams::grhodgc, modelparams::grhog, modelparams::grhok, modelparams::grhormass, modelparams::grhornomass, modelparams::grhov, modelparams::highaccuracydefault, gaugeinterface::initial_adiabatic, gaugeinterface::initial_iso_baryon, gaugeinterface::initial_iso_neutrino, gaugeinterface::initial_iso_neutrino_vel, gaugeinterface::initial_nummodes, gaugeinterface::initial_vector, modelparams::l0max, modelparams::laccuracyboost, modelparams::lambdac, gaugeinterface::lmaxnu_high_ktau, gaugeinterface::magnetic, gaugeinterface::massivenuvars(), gaugeinterface::massivenuvarsout(), thermodata::matter_verydom_tau, gaugeinterface::max_l_evolve, gaugeinterface::next_nu_nq(), massivenu::nqmax, massivenu::nu_background(), modelparams::nu_best, massivenu::nu_drho(), massivenu::nu_int_kernel, gaugeinterface::nu_integrate_l012(), gaugeinterface::nu_intvsq(), modelparams::nu_masses, gaugeinterface::nu_pi(), gaugeinterface::nu_pinudot(), massivenu::nu_q, massivenu::nu_rho(), gaugeinterface::nu_tau_massive, gaugeinterface::nu_tau_nonrelativistic, gaugeinterface::nu_tau_notmassless, modelparams::nu_trunc, thermodata::opac, gaugeinterface::polfac, quint::quint_valsata(), lambdageneral::quintessence, modelparams::rofchi(), gaugeinterface::second_order_tightcoupling, gaugeinterface::setupscalararrayindices(), gaugeinterface::setuptensorarrayindices(), gaugeinterface::switchtomassivenuapprox(), modelparams::tanfunc(), modelparams::tau_maxvis, modelparams::taurend, thermodata::thermo(), thermodata::thermo_opacitytotime(), thermodata::tight_tau, modelparams::tol, transfer::transfer_b, transfer::transfer_cdm, transfer::transfer_g, transfer::transfer_kh, transfer::transfer_max, transfer::transfer_newt_vel_baryon, transfer::transfer_newt_vel_cdm, transfer::transfer_nonu, transfer::transfer_nu, transfer::transfer_r, transfer::transfer_tot, transfer::transfer_tot_de, transfer::transfer_vel_baryon_cdm, transfer::transfer_weyl, gaugeinterface::vec_sig0, gaugeinterface::vecfac, gaugeinterface::vecfacpol, thermodata::vis, quint::vofphi(), lambdageneral::w_lam, and lambdageneral::w_perturb.
getomegak()
real(dl) function getomegak ()
References modelparams::cp, and getomegak().
init_background()
subroutine init_background ()
References quint::bde_background().