cosmomc_bde_v3p1: /home/ealmaraz/software/cosmomc/bde/v3.1/camb/equations_ppf.f90 File Reference
equations_ppf.f90 File Reference
Data Types
type gaugeinterface::evolutionvars
Modules
module lambdageneral
module gaugeinterface
Functions/Subroutines
subroutine lambdageneral::darkenergy_readparams (Ini)
subroutine lambdageneral::setddwa
real(dl) function lambdageneral::w_de (a)
real(dl) function lambdageneral::drdlna_de (al)
subroutine lambdageneral::interpolrde
real(dl) function lambdageneral::grho_de (a)
subroutine lambdageneral::cubicsplint (xa, ya, y2a, n, x, y)
subroutine lambdageneral::setcgammappf
real(dl) function getomegak ()
subroutine init_background
real(dl) function dtauda (a)
subroutine gaugeinterface::gaugeinterface_scalev (EV, y, tau, tauend, tol1, ind, c, w)
integer function gaugeinterface::next_nu_nq (nq)
recursive subroutine gaugeinterface::gaugeinterface_evolvescal (EV, tau, y, tauend, tol1, ind, c, w)
subroutine gaugeinterface::gaugeinterface_evolvetens (EV, tau, y, tauend, tol1, ind, c, w)
real(dl) function gaugeinterface::deltatimemaxed (a1, a2, tol)
subroutine gaugeinterface::gaugeinterface_init
subroutine gaugeinterface::setupscalararrayindices (EV, max_num_eqns)
subroutine gaugeinterface::copyscalarvariablearray (y, yout, EV, EVout)
subroutine gaugeinterface::setuptensorarrayindices (EV, maxeq)
subroutine gaugeinterface::copytensorvariablearray (y, yout, EV, EVout)
subroutine gaugeinterface::getnumeqns (EV)
subroutine gaugeinterface::switchtomassivenuapprox (EV, y, nu_i)
subroutine gaugeinterface::massivenuvarsout (EV, y, yprime, a, grho, gpres, dgrho, dgq, dgpi, gdpi_diff, pidot_sum, clxnu_all)
subroutine gaugeinterface::nu_integrate_l012 (EV, y, a, nu_i, drhonu, fnu, dpnu, pinu)
subroutine gaugeinterface::nu_pinudot (EV, y, ydot, a, adotoa, nu_i, pinudot)
real(dl) function gaugeinterface::nu_pi (EV, y, a, nu_i)
subroutine gaugeinterface::nu_intvsq (EV, y, a, nu_i, G11, G30)
subroutine gaugeinterface::massivenuvars (EV, y, a, grho, gpres, dgrho, dgq, wnu_arr)
subroutine gaugeinterface::output (EV, y, j, tau, sources)
subroutine gaugeinterface::outputt (EV, yt, n, j, tau, dt, dte, dtb)
subroutine gaugeinterface::outputv (EV, yv, n, j, tau, dt, dte, dtb)
subroutine gaugeinterface::initial (EV, y, tau)
subroutine gaugeinterface::initialt (EV, yt, tau)
subroutine gaugeinterface::initialv (EV, yv, tau)
subroutine gaugeinterface::outtransf (EV, y, tau, Arr)
subroutine gaugeinterface::derivs (EV, n, tau, ay, ayprime)
subroutine gaugeinterface::derivsv (EV, n, tau, yv, yvprime)
subroutine gaugeinterface::derivst (EV, n, tau, ayt, aytprime)
Variables
logical lambdageneral::use_tabulated_w = .false.
real(dl) lambdageneral::c_gamma_ppf = 0.4_dl
integer, parameter lambdageneral::nwmax = 5000
integer, parameter, private lambdageneral::nde = 2000
integer lambdageneral::nw_ppf
real(dl), dimension(nwmax) lambdageneral::w_ppf
real(dl), dimension(nwmax) lambdageneral::a_ppf
real(dl), dimension(nwmax), private lambdageneral::ddw_ppf
real(dl), dimension(nde), private lambdageneral::rde
real(dl), dimension(nde), private lambdageneral::ade
real(dl), dimension(nde), private lambdageneral::ddrde
real(dl), parameter, private lambdageneral::amin = 1.d-9
logical lambdageneral::is_cosmological_constant
Function/Subroutine Documentation
dtauda()
real(dl) function dtauda (real(dl), intent(in) a)
References modelparams::cp, dtauda(), lambdageneral::grho_de(), modelparams::grhob, modelparams::grhoc, modelparams::grhog, modelparams::grhok, modelparams::grhormass, modelparams::grhornomass, modelparams::grhov, gaugeinterface::initial_iso_baryon, gaugeinterface::initial_iso_neutrino, gaugeinterface::initial_iso_neutrino_vel, gaugeinterface::initial_vector, lambdageneral::is_cosmological_constant, modelparams::nu_masses, and massivenu::nu_rho().
getomegak()
real(dl) function getomegak ()
References modelparams::cp, and getomegak().
init_background()
subroutine init_background ()
References lambdageneral::is_cosmological_constant, lambdageneral::use_tabulated_w, lambdageneral::w_lam, and lambdageneral::wa_ppf.