cosmomc_bde_v3p1: /home/ealmaraz/software/cosmomc/bde/v3.1/camb/equations.f90 File Reference
equations.f90 File Reference
Data Types
type gaugeinterface::evolutionvars
Modules
module lambdageneral
module gaugeinterface
Functions/Subroutines
subroutine lambdageneral::darkenergy_readparams (Ini)
real(dl) function getomegak ()
subroutine init_background
real(dl) function dtauda (a)
subroutine gaugeinterface::gaugeinterface_scalev (EV, y, tau, tauend, tol1, ind, c, w)
integer function gaugeinterface::next_nu_nq (nq)
recursive subroutine gaugeinterface::gaugeinterface_evolvescal (EV, tau, y, tauend, tol1, ind, c, w)
subroutine gaugeinterface::gaugeinterface_evolvetens (EV, tau, y, tauend, tol1, ind, c, w)
real(dl) function gaugeinterface::deltatimemaxed (a1, a2, tol)
subroutine gaugeinterface::gaugeinterface_init
subroutine gaugeinterface::setupscalararrayindices (EV, max_num_eqns)
subroutine gaugeinterface::copyscalarvariablearray (y, yout, EV, EVout)
subroutine gaugeinterface::setuptensorarrayindices (EV, maxeq)
subroutine gaugeinterface::copytensorvariablearray (y, yout, EV, EVout)
subroutine gaugeinterface::getnumeqns (EV)
subroutine gaugeinterface::switchtomassivenuapprox (EV, y, nu_i)
subroutine gaugeinterface::massivenuvarsout (EV, y, yprime, a, grho, gpres, dgrho, dgq, dgpi, gdpi_diff, pidot_sum, clxnu_all)
subroutine gaugeinterface::nu_integrate_l012 (EV, y, a, nu_i, drhonu, fnu, dpnu, pinu)
subroutine gaugeinterface::nu_pinudot (EV, y, ydot, a, adotoa, nu_i, pinudot)
real(dl) function gaugeinterface::nu_pi (EV, y, a, nu_i)
subroutine gaugeinterface::nu_intvsq (EV, y, a, nu_i, G11, G30)
subroutine gaugeinterface::massivenuvars (EV, y, a, grho, gpres, dgrho, dgq, wnu_arr)
subroutine gaugeinterface::output (EV, y, j, tau, sources)
subroutine gaugeinterface::outputt (EV, yt, n, j, tau, dt, dte, dtb)
subroutine gaugeinterface::outputv (EV, yv, n, j, tau, dt, dte, dtb)
subroutine gaugeinterface::initial (EV, y, tau)
subroutine gaugeinterface::initialt (EV, yt, tau)
subroutine gaugeinterface::initialv (EV, yv, tau)
subroutine gaugeinterface::outtransf (EV, y, tau, Arr)
subroutine gaugeinterface::derivs (EV, n, tau, ay, ayprime)
subroutine gaugeinterface::derivsv (EV, n, tau, yv, yvprime)
subroutine gaugeinterface::derivst (EV, n, tau, ayt, aytprime)
Variables
real(dl) lambdageneral::w_lam = -1_dl
real(dl) lambdageneral::cs2_lam = 1_dl
real(dl), parameter lambdageneral::wa_ppf = 0._dl
logical lambdageneral::w_perturb = .true.
character(len= *), parameter gaugeinterface::eqns_name = 'gauge_inv'
integer, parameter gaugeinterface::basic_num_eqns = 5
logical gaugeinterface::dotensorneutrinos = .true.
logical gaugeinterface::dolateradtruncation = .true.
logical, parameter gaugeinterface::second_order_tightcoupling = .true.
real(dl) gaugeinterface::magnetic = 0._dl
real(dl) gaugeinterface::vec_sig0 = 1._dl
integer, parameter gaugeinterface::max_l_evolve = 256
integer, parameter gaugeinterface::initial_adiabatic =1
integer, parameter gaugeinterface::initial_iso_cdm =2
integer, parameter gaugeinterface::initial_iso_baryon =3
integer, parameter gaugeinterface::initial_iso_neutrino =4
integer, parameter gaugeinterface::initial_iso_neutrino_vel =5
integer, parameter gaugeinterface::initial_vector = 0
integer, parameter gaugeinterface::initial_nummodes = initial_iso_neutrino_vel
real(dl), dimension(max_l_evolve) gaugeinterface::polfac
real(dl), dimension(max_l_evolve) gaugeinterface::denl
real(dl), dimension(max_l_evolve) gaugeinterface::vecfac
real(dl), dimension(max_l_evolve) gaugeinterface::vecfacpol
real(dl), parameter gaugeinterface::ep0 =1.0d-2
integer, parameter gaugeinterface::lmaxnu_high_ktau =4
real(dl) gaugeinterface::epsw
real(dl), dimension(nqmax0+1, max_nu) gaugeinterface::nu_tau_notmassless
real(dl), dimension(max_nu) gaugeinterface::nu_tau_nonrelativistic
real(dl), dimension(max_nu) gaugeinterface::nu_tau_massive
Function/Subroutine Documentation
dtauda()
real(dl) function dtauda (real(dl), intent(in) a)
References modelparams::cp, modelparams::grhob, modelparams::grhoc, modelparams::grhog, modelparams::grhok, modelparams::grhormass, modelparams::grhornomass, modelparams::grhov, modelparams::nu_masses, massivenu::nu_rho(), and lambdageneral::w_lam.
Referenced by thermodata::ddamping_da(), recombination::ddeltaxe_dtau(), thermodata::ddragoptdepth_dz(), thermodata::doptdepth_dz(), dtauda(), thermodata::inithermo(), and recombination::recombination_init().
getomegak()
real(dl) function getomegak ()
References modelparams::cp.
Referenced by getomegak().
init_background()
subroutine init_background ()
Referenced by modelparams::cambparams_set().