cosmomc_bde_v3p1: /home/ealmaraz/software/cosmomc/bde/v3.1/source/GetDist.f90 File Reference
GetDist.f90 File Reference
Modules
module mcsamples
Functions/Subroutines
subroutine mcsamples::adjustpriors
subroutine mcsamples::mapparameters (invars)
subroutine mcsamples::coolchain (cool)
subroutine mcsamples::deletezeros
subroutine mcsamples::sortcoldata (bycol)
subroutine mcsamples::makesinglesamples (single_thin)
subroutine mcsamples::writethindata (fname, cool)
subroutine mcsamples::thindata (fac, ix1, ix2)
subroutine mcsamples::getcovmatrix
integer function mcsamples::mostcorrelated2d (i1, i2, direc)
subroutine mcsamples::getfractionindices (fraction_indices, n)
real(mcp) function mcsamples::confidval (ix, limfrac, upper, ix1, ix2)
subroutine mcsamples::writes (S)
subroutine mcsamples::pca (pars, n, param_map, normparam_num)
subroutine mcsamples::getusedcols
subroutine mcsamples::doconvergetests (limfrac)
subroutine mcsamples::get1ddensity (j)
subroutine mcsamples::get2dplotdata (j, j2)
logical function mcsamples::plotcontmatlab (aunit, aroot, j, j2, DoShade)
character(len=:) function, allocatable mcsamples::matlablabel (i)
subroutine mcsamples::write2dplotmatlab (aunit, j, j2, DoLabelx, DoLabely, hide_ticklabels)
subroutine mcsamples::writeplotfileinit (unit, sm, subplot_size)
subroutine mcsamples::writeplotfileexport (unit, tag, plot_col, plot_row)
character(len=:) function, allocatable mcsamples::quoted_param_name (j)
character(len=:) function, allocatable mcsamples::quoted_param_name_used (j)
character(len=:) function, allocatable mcsamples::python_param_array (params, num)
subroutine mcsamples::write1dplotmatlab (aunit, j)
subroutine mcsamples::writematlablinelabels (F)
subroutine mcsamples::edgewarning (param)
character(len=:) function, allocatable mcsamples::dat_file_name (rootname, j)
character(len=:) function, allocatable mcsamples::dat_file_2d (rootname, j, j2)
subroutine mcsamples::checkmatlabaxes (afile)
real(mcp) function mcsamples::dinvnorm (p)
subroutine mcsamples::getchainlikesummary (unit)
program getdist
Variables
type(tparamnames), save mcsamples::namemapping
integer, parameter mcsamples::gp = KIND(1.d0)
character(len= *), parameter mcsamples::float_format = '(*(E16.7))'
real(gp), dimension(:,:), allocatable mcsamples::coldata
integer, dimension(:), allocatable mcsamples::thin_ix
integer mcsamples::thin_rows
integer, parameter mcsamples::max_rows = 500000
integer, parameter mcsamples::max_cols = 500
integer, parameter mcsamples::max_chains = 100
integer, parameter mcsamples::max_split_tests = 4
integer, parameter mcsamples::max_contours = 5
integer mcsamples::corr_length_thin = 0
integer mcsamples::corr_length_steps = 15
type(tdensity1d) mcsamples::density1d
integer, dimension(max_chains) mcsamples::chain_indices
integer mcsamples::num_chains_used
integer mcsamples::bestfit_ix
real(mcp) mcsamples::meanlike
real(mcp) mcsamples::maxlike
integer mcsamples::nrows
integer mcsamples::ncols
integer mcsamples::num_bins
integer mcsamples::num_bins_2d
real(mcp) mcsamples::numsamp
real(mcp) mcsamples::max_mult
real(mcp) mcsamples::mean_mult
integer mcsamples::nd_cont1
integer mcsamples::nd_cont2
real(mcp), dimension(:,:), allocatable mcsamples::nd_limit_top
real(mcp), dimension(:,:), allocatable mcsamples::nd_limit_bot
integer mcsamples::covmat_dimension
integer, dimension(max_cols) mcsamples::colix
integer mcsamples::num_vars
real(mcp), dimension(2, max_cols) mcsamples::prior_ranges
real(mcp), dimension(max_cols) mcsamples::mean
real(mcp), dimension(max_cols) mcsamples::sddev
real(mcp), dimension(:,:), allocatable mcsamples::corrmatrix
character(len=:), allocatable mcsamples::plot_data_dir
character(len=:), allocatable mcsamples::out_dir
character(len=:), allocatable mcsamples::rootdirname
character(len=:), allocatable mcsamples::in_root
character(len=128), dimension(max_cols) mcsamples::labels
character(len=128), dimension(max_cols) mcsamples::pname
logical, dimension(max_cols) mcsamples::has_limits
logical, dimension(max_cols) mcsamples::has_limits_top
logical, dimension(max_cols) mcsamples::has_limits_bot
logical, dimension(max_contours, max_cols) mcsamples::marge_limits_top
logical, dimension(max_contours, max_cols) mcsamples::marge_limits_bot
logical, dimension(max_cols) mcsamples::has_markers
real(mcp), dimension(max_cols) mcsamples::markers
integer mcsamples::num_contours
character(len=3) mcsamples::plot_ext = 'm'
real(mcp) mcsamples::matlab_version
character(len=3) mcsamples::plot_output = 'pdf'
real mcsamples::subplot_size_inch = 3.0
real mcsamples::subplot_size_inch2
real mcsamples::subplot_size_inch3
logical mcsamples::matlab_latex = .false.
real(mcp) mcsamples::font_scale = 1.
real(mcp), dimension(max_contours) mcsamples::contours
real(mcp), dimension(max_contours) mcsamples::max_frac_twotail
integer mcsamples::indep_thin = 0
integer, dimension(max_chains) mcsamples::chain_numbers
logical, dimension(max_cols) mcsamples::isused
logical mcsamples::force_twotail
logical mcsamples::plot_meanlikes
logical mcsamples::mean_loglikes = .false.
logical mcsamples::shade_meanlikes
logical mcsamples::make_single_samples
integer mcsamples::single_thin
integer, dimension(max_cols **2) mcsamples::cust2dplots
integer, dimension(max_cols) mcsamples::ix_min
integer, dimension(max_cols) mcsamples::ix_max
real(mcp), dimension(max_cols) mcsamples::limmin
real(mcp), dimension(max_cols) mcsamples::limmax
real(mcp), dimension(max_cols) mcsamples::center
real(mcp), dimension(max_cols) mcsamples::param_min
real(mcp), dimension(max_cols) mcsamples::param_max
real(mcp), dimension(max_cols) mcsamples::range_min
real(mcp), dimension(max_cols) mcsamples::range_max
logical mcsamples::bw
logical mcsamples::do_shading
type(tstringlist), save mcsamples::compareplots
logical mcsamples::prob_label = .false.
logical mcsamples::plots_only
logical mcsamples::no_plots
real(mcp) mcsamples::smooth_scale_1d =-1.d0
real(mcp) mcsamples::smooth_scale_2d = 1.d0
real(mcp) mcsamples::credible_interval_threshold = 0.05d0
integer mcsamples::boundary_correction_method = 1
Function/Subroutine Documentation
getdist()
program getdist ()
References mcsamples::adjustpriors(), mcsamples::bestfit_ix, mcsamples::boundary_correction_method, mcsamples::bw, mcsamples::chain_indices, mcsamples::chain_numbers, mcsamples::checkmatlabaxes(), mcsamples::coldata, mcsamples::colix, mcsamples::compareplots, mcsamples::confidval(), mcsamples::contours, mcsamples::coolchain(), mcsamples::corr_length_steps, mcsamples::corr_length_thin, mcsamples::corrmatrix, mcsamples::covmat_dimension, mcsamples::credible_interval_threshold, mcsamples::cust2dplots, mcsamples::deletezeros(), mcsamples::density1d, mcsamples::dinvnorm(), mcsamples::do_shading, mcsamples::doconvergetests(), mcsamples::font_scale, mcsamples::force_twotail, mcsamples::get1ddensity(), mcsamples::get2dplotdata(), mcsamples::getchainlikesummary(), mcsamples::getcovmatrix(), mcsamples::getusedcols(), mcsamples::has_limits_bot, mcsamples::has_limits_top, mcsamples::has_markers, mcsamples::in_root, mcsamples::indep_thin, io::io_outputmargestats(), io::io_readchainrows(), io::io_readparamnames(), io::io_writebounds(), mcsamples::isused, mcsamples::ix_max, mcsamples::ix_min, mcsamples::labels, mcsamples::limmax, mcsamples::limmin, mcsamples::make_single_samples, mcsamples::makesinglesamples(), mcsamples::mapparameters(), mcsamples::marge_limits_bot, mcsamples::marge_limits_top, mcsamples::markers, mcsamples::matlab_latex, mcsamples::matlab_version, mcsamples::matlablabel(), mcsamples::max_chains, mcsamples::max_frac_twotail, mcsamples::max_mult, mcsamples::max_rows, mcsamples::mean, mcsamples::mean_mult, mcsamples::namemapping, mcsamples::ncols, mcsamples::nd_cont1, mcsamples::nd_cont2, mcsamples::nd_limit_bot, mcsamples::nd_limit_top, mcsamples::no_plots, mcsamples::nrows, mcsamples::num_bins, mcsamples::num_bins_2d, mcsamples::num_chains_used, mcsamples::num_contours, mcsamples::num_vars, mcsamples::numsamp, mcsamples::out_dir, mcsamples::pca(), mcsamples::plot_data_dir, mcsamples::plot_ext, mcsamples::plot_meanlikes, mcsamples::plot_output, mcsamples::plots_only, mcsamples::pname, mcsamples::prior_ranges, mcsamples::prob_label, mcsamples::python_param_array(), mcsamples::quoted_param_name(), mcsamples::quoted_param_name_used(), mcsamples::range_max, mcsamples::range_min, mcsamples::rootdirname, settings::rootname, mcsamples::sddev, mcsamples::shade_meanlikes, mcsamples::single_thin, mcsamples::smooth_scale_1d, mcsamples::smooth_scale_2d, mcsamples::sortcoldata(), settings::stdout, mcsamples::subplot_size_inch, mcsamples::subplot_size_inch2, mcsamples::subplot_size_inch3, mcsamples::thindata(), mcsamples::write1dplotmatlab(), mcsamples::write2dplotmatlab(), mcsamples::writematlablinelabels(), mcsamples::writeplotfileexport(), mcsamples::writeplotfileinit(), and mcsamples::writethindata().