cosmomc_bde_v3p1: /home/ealmaraz/software/cosmomc/bde/v3.1/camb/halofit_ppf.f90 File Reference
halofit_ppf.f90 File Reference
Data Types
type nonlinear::hm_cosmology
type nonlinear::hm_tables
Modules
module nonlinear
Functions/Subroutines
subroutine, public nonlinear::nonlinear_readparams (Ini)
subroutine, public nonlinear::nonlinear_getnonlinratios (CAMB_Pk)
subroutine nonlinear::halofit (rk, rn, rncur, rknl, plin, pnl, pq, ph)
subroutine nonlinear::wint (CAMB_Pk, itf, r, sig, d1, d2)
real(dl) function nonlinear::omega_m (aa, om_m0, om_v0, wval, waval)
real(dl) function nonlinear::omega_v (aa, om_m0, om_v0, wval, waval)
subroutine nonlinear::hmcode (CAMB_Pk)
real function nonlinear::delta_v (z, lut, cosm)
real function nonlinear::delta_c (z, lut, cosm)
real function nonlinear::eta (z, lut, cosm)
real function nonlinear::kstar (z, lut, cosm)
real function nonlinear::as (z, lut, cosm)
real function nonlinear::fdamp (z, lut, cosm)
real function nonlinear::alpha (z, lut, cosm)
real function nonlinear::r_nl (lut)
subroutine nonlinear::halomod (k, z, p1h, p2h, pfull, plin, lut, cosm)
subroutine nonlinear::fill_table (min, max, arr, n)
subroutine nonlinear::fill_plintab (iz, cosm, CAMB_PK)
real function nonlinear::tcb_tcbnu_ratio (k, z, cosm)
subroutine nonlinear::assign_hm_cosmology (cosm)
subroutine nonlinear::initialise_hm_cosmology (iz, cosm, CAMB_PK)
subroutine nonlinear::allocate_lut (lut)
subroutine nonlinear::deallocate_lut (lut)
subroutine nonlinear::halomod_init (z, lut, cosm)
subroutine nonlinear::write_parameters (z, lut, cosm)
pure real function nonlinear::radius_m (m, cosm)
real function nonlinear::neff (lut, cosm)
subroutine nonlinear::conc_bull (z, lut, cosm)
real function nonlinear::grow_int (b, acc, cosm)
subroutine nonlinear::zcoll_bull (z, cosm, lut)
real function nonlinear::mass_r (r, cosm)
pure real function nonlinear::cosmic_density (cosm)
real function nonlinear::find_pk (k, itype, cosm)
real function nonlinear::p_lin (k, z, itype, cosm)
real function nonlinear::p_2h (k, z, plin, lut, cosm)
real function nonlinear::p_1h (k, z, lut, cosm)
subroutine nonlinear::fill_sigtab (cosm)
real function nonlinear::sigma_v (R, z, cosm)
real function nonlinear::sigma (r, z, itype, cosm)
real function nonlinear::sigmac (r, z, cosm)
real function nonlinear::wk_tophat (x)
real function nonlinear::inttab (x, y, n, iorder)
real function nonlinear::sigma_integrand (t, R, f, z, itype, cosm)
real function nonlinear::f_rapid (r)
real function nonlinear::sigint0 (r, z, itype, cosm)
real function nonlinear::sigint1 (r, z, itype, cosm)
real function nonlinear::sigint2 (r, z, itype, cosm)
real function nonlinear::win (k, rv, c)
real function nonlinear::winnfw (k, rv, c)
real function nonlinear::mass (c)
real function nonlinear::gnu (nu)
real function nonlinear::gst (nu)
real function nonlinear::hubble2 (z, cosm)
real function nonlinear::x_de (a, cosm)
real function nonlinear::w_de_hm (a, cosm)
real function nonlinear::omega_m_hm (z, cosm)
real function nonlinear::grow (z, cosm)
real function nonlinear::dispint (z, cosm)
real function nonlinear::si (x)
real function nonlinear::ci (x)
real function nonlinear::derivative_table (x, xin, yin, n, iorder, imeth)
real function nonlinear::find (x, xin, yin, n, iorder, imeth)
integer function nonlinear::table_integer (x, xtab, n, imeth)
integer function nonlinear::linear_table_integer (x, xtab, n)
integer function nonlinear::search_int (x, xtab, n)
integer function nonlinear::int_split (x, xtab, n)
subroutine nonlinear::fit_line (a1, a0, x1, y1, x2, y2)
subroutine nonlinear::fit_quadratic (a2, a1, a0, x1, y1, x2, y2, x3, y3)
subroutine nonlinear::fit_cubic (a, b, c, d, x1, y1, x2, y2, x3, y3, x4, y4)
subroutine nonlinear::reverse (arry, n)
subroutine nonlinear::fill_growtab (cosm)
subroutine nonlinear::ode_growth (x, v, t, kk, ti, tf, xi, vi, acc, imeth, cosm)
real function nonlinear::fv (d, v, k, a, cosm)
real function nonlinear::fd (d, v, k, a, cosm)
real function nonlinear::ah (z, cosm)
subroutine nonlinear_getratios (CAMB_Pk)
subroutine nonlinear_getratios_all (CAMB_Pk)
Variables
real, parameter, public nonlinear::min_kh_nonlinear = 0.005
real(dl) nonlinear::om_m
real(dl) nonlinear::om_v
real(dl) nonlinear::fnu
real(dl) nonlinear::omm0
real(dl) nonlinear::acur
integer, parameter, public nonlinear::halofit_original = 1
integer, parameter, public nonlinear::halofit_bird =2
integer, parameter, public nonlinear::halofit_peacock =3
integer, parameter, public nonlinear::halofit_takahashi =4
integer, parameter, public nonlinear::halofit_mead =5
integer, parameter, public nonlinear::halofit_halomodel =6
integer, parameter, public nonlinear::halofit_default = halofit_takahashi
integer, public nonlinear::halofit_version = halofit_default
integer nonlinear::imead
integer nonlinear::ihm
Function/Subroutine Documentation
nonlinear_getratios()
subroutine nonlinear_getratios (type(matterpowerdata) CAMB_Pk) private
References nonlinear::nonlinear_getnonlinratios().
Referenced by calculator_camb::cambcalc_getnlandratios(), transfer::matterpowerdata_makenonlinear(), lrggettheory::transfer_getmatterpowerandnw(), transfer::transfer_getmatterpowerd(), and transfer::transfer_getunsplinednonlinearpower().
nonlinear_getratios_all()
subroutine nonlinear_getratios_all (type(matterpowerdata) CAMB_Pk)