cosmomc_bde_v3p1: getdist.convolve Namespace Reference
getdist.convolve Namespace Reference
Functions
def nearestFFTnumber (x)
def convolve1D (x, y, mode, largest_size=0, cache=None)
def convolve2D (x, y, mode, largest_size=0, cache=None)
def convolveFFT (x, y, mode='same', yfft=None, xfft=None, largest_size=0, cache=None)
def convolveFFTn (in1, in2, mode="same", largest_size=0, cache=None, yfft=None, xfft=None)
def _centered (arr, newsize)
def autoCorrelation (x, n=None, normalized=True, start_index=0)
def autoConvolve (x, n=None, normalize=True)
def convolveGaussianDCT (x, sigma, pad_sigma=4, mode='same', cache={})
def convolveGaussian (x, sigma, sigma_range=4, cache=None)
def convolveGaussianTrunc (x, sigma, sigma_range=4, mode='same', cache=None)
def dct2d (a)
def idct2d (a)
Variables
fastFFT
Function Documentation
_centered()
def getdist.convolve._centered (arr, newsize) private
Referenced by getdist.convolve.convolveFFTn().
autoConvolve()
def getdist.convolve.autoConvolve (x, n = None, normalize = True)
Calculates auto-covariance of x, result[k] = sum_i x_i x_{i+k}
n is maximum size to return (k = 0..n-1)
if normalize=True then normalize convolution by the number of terms for each k
(can input x-mean(x) and divide result by variance to get auto correlation)
References getdist.convolve.nearestFFTnumber().
Referenced by getdist.convolve.autoCorrelation(), and getdist.chains.WeightedSamples.getAutocorrelation().
autoCorrelation()
def getdist.convolve.autoCorrelation (x, n = None, normalized = True, start_index = 0)
    Calculates auto-correlation of x, result[k] = sum_{i=0}^{n-k} x_i x_{i+k}/(n-k)
    if normalized=True, divides by the variance (for if start_index=0, first number is one)
References getdist.convolve.autoConvolve().
convolve1D()
def getdist.convolve.convolve1D (x, y, mode, largest_size = 0, cache = None)
References getdist.convolve.convolveFFT().
Referenced by getdist.mcsamples.MCSamples.get1DDensityGridData().
convolve2D()
def getdist.convolve.convolve2D (x, y, mode, largest_size = 0, cache = None)
References getdist.convolve.convolveFFTn().
Referenced by getdist.mcsamples.MCSamples.get2DDensityGridData().
convolveFFT()
def getdist.convolve.convolveFFT (x, y, mode = 'same', yfft = None, xfft = None, largest_size = 0, cache = None)
convolution of x with y; fft cans be cached
References getdist.convolve.nearestFFTnumber().
Referenced by getdist.convolve.convolve1D().
convolveFFTn()
def getdist.convolve.convolveFFTn (in1, in2, mode = "same", largest_size = 0, cache = None, yfft = None, xfft = None)
References getdist.convolve._centered(), CAMB_test_files.int, and getdist.convolve.nearestFFTnumber().
Referenced by getdist.convolve.convolve2D().
convolveGaussian()
def getdist.convolve.convolveGaussian (x, sigma, sigma_range = 4, cache = None)
1D convolution of x with Gaussian of width sigma pixels
x_max = int(sigma_range*sigma) the zero padding range at ends
This uses periodic boundary conditions, and mode = 'same'
This is the fastest fft version
References CAMB_test_files.float, CAMB_test_files.int, and getdist.convolve.nearestFFTnumber().
convolveGaussianDCT()
def getdist.convolve.convolveGaussianDCT (x, sigma, pad_sigma = 4, mode = 'same', cache = {})
1D convolution of x with Gaussian of width sigma pixels
If pad_sigma>0, pads ends with zeros by int(pad_sigma*sigma) pixels
Otherwise does unpadded fast cosine transform, hence reflection from the ends
References CAMB_test_files.float, CAMB_test_files.int, and getdist.convolve.nearestFFTnumber().
convolveGaussianTrunc()
def getdist.convolve.convolveGaussianTrunc (x, sigma, sigma_range = 4, mode = 'same', cache = None)
1D convolution of x with Gaussian of width sigma pixels
x_max = int(sigma_range*sigma) determines the finite support (in pixels) of the truncated gaussian
This uses normalized finite range approximation to Gaussian
References CAMB_test_files.int, and getdist.convolve.nearestFFTnumber().
dct2d()
def getdist.convolve.dct2d (a)
idct2d()
def getdist.convolve.idct2d (a)
nearestFFTnumber()
def getdist.convolve.nearestFFTnumber (x)
Referenced by getdist.convolve.autoConvolve(), getdist.convolve.convolveFFT(), getdist.convolve.convolveFFTn(), getdist.convolve.convolveGaussian(), getdist.convolve.convolveGaussianDCT(), and getdist.convolve.convolveGaussianTrunc().
Variable Documentation
fastFFT
getdist.convolve.fastFFT
Initial value:
 =  np.array(
     [2, 4, 6, 8, 10, 12, 16, 20, 24, 32, 40, 48, 64, 80, 96, 128, 144, 160, 192, 256, 288, 320, 384, 432, 480,
      512, 576, 640, 720, 768, 864, 960, 1024, 1152, 1280, 1440, 1536, 1728, 1920, 2048, 2304, 2560, 2880, 3072,
      3456, 3840, 4096, 4608, 5120, 5760, 6144, 6912, 7680, 8192, 9216, 10240, 11520, 12288, 13824, 15360, 16384,
      18432, 20480, 23040, 24576, 27648, 30720, 32768, 36864, 40960, 46080, 49152, 55296, 61440, 65536, 73728, 81920,
      92160, 98304, 110592, 122880, 131072, 147456, 163840, 184320, 196608, 221184, 245760, 262144, 294912, 327680,
      368640, 393216, 442368, 491520, 524288, 589824, 655360, 737280, 786432, 884736, 983040, 1048576, 1179648,
      1310720, 1474560, 1572864, 1769472, 1966080, 2097152, 2359296, 2621440, 2949120, 3145728, 3538944, 3932160,
      4194304, 4718592, 5242880, 5898240, 6291456, 7077888, 7864320, 8388608, 9437184, 10485760, 11796480, 12582912,
      14155776, 15728640, 16777216, 18874368, 20971520, 23592960, 25165824, 28311552, 31457280, 33554432, 37748736,
      41943040, 47185920, 50331648, 56623104, 62914560, 67108864, 75497472, 83886080, 94371840, 100663296, 113246208,
      125829120, 134217728, 150994944, 167772160, 188743680, 201326592, 226492416, 234881024, 251658240, 268435456,
      301989888, 335544320, 377487360, 402653184, 452984832, 503316480, 536870912, 603979776, 671088640, 754974720,
      805306368, 905969664, 1006632960, 1207959552, 1342177280, 1358954496, 1509949440, 1610612736, 1811939328,
      2013265920], dtype=np.int)