cosmomc_bde_v3p1: lambdageneral Module Reference
lambdageneral Module Reference
Functions/Subroutines
subroutine darkenergy_readparams (Ini)
subroutine setddwa
real(dl) function w_de (a)
real(dl) function drdlna_de (al)
subroutine interpolrde
real(dl) function grho_de (a)
subroutine cubicsplint (xa, ya, y2a, n, x, y)
subroutine setcgammappf
Variables
real(dl) w_lam = -1_dl
real(dl) cs2_lam = 1_dl
real(dl), parameter wa_ppf = 0._dl
logical w_perturb = .true.
logical quintessence = .true.
logical use_tabulated_w = .false.
real(dl) c_gamma_ppf = 0.4_dl
integer, parameter nwmax = 5000
integer, parameter, private nde = 2000
integer nw_ppf
real(dl), dimension(nwmax) w_ppf
real(dl), dimension(nwmax) a_ppf
real(dl), dimension(nwmax), private ddw_ppf
real(dl), dimension(nde), private rde
real(dl), dimension(nde), private ade
real(dl), dimension(nde), private ddrde
real(dl), parameter, private amin = 1.d-9
logical is_cosmological_constant
Function/Subroutine Documentation
cubicsplint()
subroutine lambdageneral::cubicsplint (xa, ya, y2a, integer n, x, y)
Referenced by grho_de(), and w_de().
darkenergy_readparams()
subroutine lambdageneral::darkenergy_readparams (type(tinifile) Ini)
References cs2_lam, inifile::ini_read_double_file(), and w_lam.
drdlna_de()
real(dl) function lambdageneral::drdlna_de (real(dl), intent(in) al)
References w_de().
Referenced by interpolrde().
grho_de()
real(dl) function lambdageneral::grho_de (real(dl), intent(in) a)
References ade, amin, cubicsplint(), ddrde, modelparams::grhov, nde, rde, use_tabulated_w, w_de(), and wa_ppf.
Referenced by dtauda().
interpolrde()
subroutine lambdageneral::interpolrde ()
References ade, amin, ddrde, drdlna_de(), nde, rde, and spline().
setcgammappf()
subroutine lambdageneral::setcgammappf ()
References c_gamma_ppf.
setddwa()
subroutine lambdageneral::setddwa ()
References a_ppf, ddw_ppf, nw_ppf, spline(), and w_ppf.
w_de()
real(dl) function lambdageneral::w_de (real(dl), intent(in) a)
References a_ppf, cubicsplint(), ddw_ppf, nw_ppf, use_tabulated_w, w_ppf, and wa_ppf.
Referenced by drdlna_de(), and grho_de().
Variable Documentation
a_ppf
real(dl), dimension(nwmax) lambdageneral::a_ppf
Referenced by setddwa(), and w_de().
ade
real(dl), dimension(nde), private lambdageneral::ade private
Referenced by grho_de(), and interpolrde().
amin
real(dl), parameter, private lambdageneral::amin = 1.d-9 private
Referenced by grho_de(), and interpolrde().
c_gamma_ppf
real(dl) lambdageneral::c_gamma_ppf = 0.4_dl
Referenced by setcgammappf().
cs2_lam
real(dl) lambdageneral::cs2_lam = 1_dl
Referenced by darkenergy_readparams(), gaugeinterface::derivs(), and dtauda().
ddrde
real(dl), dimension(nde), private lambdageneral::ddrde private
Referenced by grho_de(), and interpolrde().
ddw_ppf
real(dl), dimension(nwmax), private lambdageneral::ddw_ppf private
Referenced by setddwa(), and w_de().
is_cosmological_constant
logical lambdageneral::is_cosmological_constant
Referenced by dtauda(), and init_background().
nde
integer, parameter, private lambdageneral::nde = 2000 private
Referenced by grho_de(), and interpolrde().
nw_ppf
integer lambdageneral::nw_ppf
Referenced by setddwa(), and w_de().
nwmax
integer, parameter lambdageneral::nwmax = 5000
quintessence
logical lambdageneral::quintessence = .true.
Referenced by dtauda().
rde
real(dl), dimension(nde), private lambdageneral::rde private
Referenced by grho_de(), and interpolrde().
use_tabulated_w
logical lambdageneral::use_tabulated_w = .false.
Referenced by grho_de(), init_background(), and w_de().
w_lam
real(dl) lambdageneral::w_lam = -1_dl
Referenced by nonlinear::assign_hm_cosmology(), calculator_camb::cambcalc_cmbtocamb(), gaugeinterface::copyscalarvariablearray(), darkenergy_readparams(), gaugeinterface::derivs(), gaugeinterface::derivst(), gaugeinterface::derivsv(), dtauda(), nonlinear::halofit(), init_background(), gaugeinterface::initial(), nonlinear::nonlinear_getnonlinratios(), gaugeinterface::output(), and gaugeinterface::setupscalararrayindices().
w_perturb
logical lambdageneral::w_perturb = .true.
Referenced by gaugeinterface::copyscalarvariablearray(), gaugeinterface::derivs(), dtauda(), gaugeinterface::initial(), gaugeinterface::output(), and gaugeinterface::setupscalararrayindices().
w_ppf
real(dl), dimension(nwmax) lambdageneral::w_ppf
Referenced by setddwa(), and w_de().
wa_ppf
real(dl) lambdageneral::wa_ppf = 0._dl
Referenced by nonlinear::assign_hm_cosmology(), calculator_camb::cambcalc_cmbtocamb(), grho_de(), nonlinear::halofit(), init_background(), nonlinear::nonlinear_getnonlinratios(), and w_de().