cosmomc_bde_v3p1: initests Module Reference
initests Module Reference
Functions/Subroutines
integer function runinitests ()
subroutine test_read (fails)
Variables
character(len=0), target empty_string = ''
Function/Subroutine Documentation
runinitests()
integer function initests::runinitests ()
References test_read().
Referenced by tester().
test_read()
subroutine initests::test_read (integer fails)
References stringutils::getenvironmentvariable().
Referenced by runinitests().
Variable Documentation
empty_string
character(len=0), target initests::empty_string = ''