cosmomc_bde_v3p1: wigglezinfo Module Reference
wigglezinfo Module Reference
Functions/Subroutines
subroutine gigglezinfo_init ()
real(mcp) function giggleztoicsmooth (k, zbin)
subroutine wigglezpowerat (kh, zbin, PK)
Variables
real(mcp), parameter za = 0.22d0
real(mcp), parameter zb = 0.41d0
real(mcp), parameter zc = 0.6d0
real(mcp), parameter zd = 0.78d0
real(mcp), dimension(4) zeval
type(tcubicspline), dimension(:), allocatable gigglezpk
integer, parameter gigglez_numk = 500
integer, parameter gigglez_numz = 4
Function/Subroutine Documentation
gigglezinfo_init()
subroutine wigglezinfo::gigglezinfo_init ()
References settings::datadir, gigglez_numk, gigglez_numz, and gigglezpk.
Referenced by wigglez::twigglezcommon_readini().
giggleztoicsmooth()
real(mcp) function wigglezinfo::giggleztoicsmooth (real(mcp), intent(in) k, integer, intent(in) zbin)
Referenced by wigglezpowerat().
wigglezpowerat()
subroutine wigglezinfo::wigglezpowerat (real(mcp), intent(in) kh, integer, intent(in) zbin, real(mcp), intent(inout) PK)
References gigglezpk, and giggleztoicsmooth().
Referenced by wigglez::wigglez_lnlike().
Variable Documentation
gigglez_numk
integer, parameter wigglezinfo::gigglez_numk = 500
Referenced by gigglezinfo_init().
gigglez_numz
integer, parameter wigglezinfo::gigglez_numz = 4
Referenced by gigglezinfo_init().
gigglezpk
type(tcubicspline), dimension(:), allocatable wigglezinfo::gigglezpk
Referenced by gigglezinfo_init(), and wigglezpowerat().
za
real(mcp), parameter wigglezinfo::za = 0.22d0
Referenced by wigglez::twigglezcommon_readini().
zb
real(mcp), parameter wigglezinfo::zb = 0.41d0
Referenced by wigglez::twigglezcommon_readini().
zc
real(mcp), parameter wigglezinfo::zc = 0.6d0
Referenced by wigglez::twigglezcommon_readini().
zd
real(mcp), parameter wigglezinfo::zd = 0.78d0
Referenced by wigglez::twigglezcommon_readini().
zeval
real(mcp), dimension(4) wigglezinfo::zeval
Referenced by wigglez::twigglezcommon_readini(), and wigglez::wigglez_readini().