cosmomc_bde_v3p1: makeParamCompare Namespace Reference
makeParamCompare Namespace Reference
Functions
def makeMath (txt)
def textAsColumn (txt, latex=True)
def sortData (batch, datatags)
Variables
Opts = batchjob_args.batchArgs('Compare parameter constraints over set of models')
nargs
default
action
type
int
batch
args
formatter = types.TableFormatter()
names = paramnames.ParamNames(args.paramNameFile)
chain_name_params
compare
table = dict()
paramtag_for_param = dict()
paramNameFile
None
bestfit
nobestfits
noconverge
True
silent
list results = []
texValues = jobItem.result_marge.texValues(formatter, par, limit=args.limit)
dataTable = table[jobItem.paramtag]
list lines = []
list cols = [makeMath(names.parWithName(par, True).label)]
res = table[paramtag][datatag][par2]
outdir
outname
Function Documentation
makeMath()
def makeParamCompare.makeMath (txt)
Referenced by textAsColumn().
sortData()
def makeParamCompare.sortData (batch, datatags)
textAsColumn()
def makeParamCompare.textAsColumn (txt, latex = True)
References makeMath().
Referenced by getdist.types.ResultTable.paramLabelColumn(), and getdist.types.ResultTable.paramResultTex().
Variable Documentation
action
makeParamCompare.action
args
makeParamCompare.args
batch
makeParamCompare.batch
bestfit
makeParamCompare.bestfit
chain_name_params
makeParamCompare.chain_name_params
cols
list makeParamCompare.cols = [makeMath(names.parWithName(par, True).label)]
compare
makeParamCompare.compare
dataTable
makeParamCompare.dataTable = table[jobItem.paramtag]
default
makeParamCompare.default
formatter
makeParamCompare.formatter = types.TableFormatter()
int
makeParamCompare.int
lines
list makeParamCompare.lines = []
names
makeParamCompare.names = paramnames.ParamNames(args.paramNameFile)
nargs
makeParamCompare.nargs
nobestfits
makeParamCompare.nobestfits
noconverge
makeParamCompare.noconverge
None
makeParamCompare.None
Opts
makeParamCompare.Opts = batchjob_args.batchArgs('Compare parameter constraints over set of models')
outdir
makeParamCompare.outdir
outname
makeParamCompare.outname
paramNameFile
makeParamCompare.paramNameFile
paramtag_for_param
makeParamCompare.paramtag_for_param = dict()
res
makeParamCompare.res = table[paramtag][datatag][par2]
results
list makeParamCompare.results = []
silent
makeParamCompare.silent
table
makeParamCompare.table = dict()
texValues
makeParamCompare.texValues = jobItem.result_marge.texValues(formatter, par, limit=args.limit)
True
makeParamCompare.True
type
makeParamCompare.type