cosmomc_bde_v3p1: modeldata Module Reference
modeldata Module Reference
Data Types
type cltransferdata
type limberrec
Functions/Subroutines
subroutine init_cltransfer (CTrans)
subroutine init_limber (CTrans)
subroutine free_cltransfer (CTrans)
subroutine free_limber (CTrans)
subroutine checkloadedhighltemplate
subroutine init_cls
integer function open_file_header (filename, Col1, Columns, n)
character(len=5) function scalar_fieldname (i)
subroutine output_cl_files (ScalFile, ScalCovFile, TensFile, TotFile, LensFile, LensTotFile, factor)
subroutine output_lens_pot_files (LensPotFile, factor)
subroutine output_veccl_files (VecFile, factor)
subroutine normalizeclsatl (lnorm)
subroutine modeldata_free
Variables
type(cltransferdata), target, save ctransscal
type(cltransferdata), target, save ctranstens
type(cltransferdata), target, save ctransvec
integer, parameter c_temp = 1
integer, parameter c_e = 2
integer, parameter c_cross =3
integer, parameter c_phi = 4
integer, parameter c_phitemp = 5
integer, parameter c_phie =6
integer c_last = C_PhiE
integer, parameter ct_temp =1
integer, parameter ct_e = 2
integer, parameter ct_b = 3
integer, parameter ct_cross = 4
integer, parameter name_tag_len = 12
character(len=name_tag_len), dimension(c_phie), parameter c_name_tags = ['TT','EE','TE','PP','TP','EP']
character(len=name_tag_len), dimension(ct_cross), parameter ct_name_tags = ['TT','EE','BB','TE']
character(len=name_tag_len), dimension(7), parameter lens_pot_name_tags = ['TT','EE','BB','TE','PP','TP','EP']
logical has_cl_2d_array = .false.
real(dl), dimension(:,:,:), allocatable cl_scalar
real(dl), dimension(:,:,:), allocatable cl_tensor
real(dl), dimension(:,:,:), allocatable cl_vector
real(dl), dimension(:,:,:,:), allocatable cl_scalar_array
integer lmax_lensed
real(dl), dimension(:,:,:), allocatable cl_lensed
Function/Subroutine Documentation
checkloadedhighltemplate()
subroutine modeldata::checkloadedhighltemplate ()
References c_cross, c_e, c_phi, c_temp, modelparams::fileio_unit, modelparams::highl_cl_template, modelparams::highl_unlensed_cl_template, modelparams::lmax_extrap_highl, and modelparams::lmin.
Referenced by init_cls().
free_cltransfer()
subroutine modeldata::free_cltransfer (type(cltransferdata) CTrans)
References free_limber().
Referenced by camb::camb_freecambdata(), camb::camb_gettransfers(), and modeldata_free().
free_limber()
subroutine modeldata::free_limber (type(cltransferdata) CTrans)
Referenced by free_cltransfer().
init_cls()
subroutine modeldata::init_cls ()
References c_last, c_temp, checkloadedhighltemplate(), cl_scalar, cl_scalar_array, cl_tensor, cl_vector, modelparams::cp, ct_cross, ct_temp, has_cl_2d_array, modelparams::lmin, and modelparams::num_redshiftwindows.
Referenced by cambmain::cltransfertocl().
init_cltransfer()
subroutine modeldata::init_cltransfer (type(cltransferdata) CTrans)
Referenced by cambmain::setkvaluesforint().
init_limber()
subroutine modeldata::init_limber (type(cltransferdata) CTrans)
References modelparams::limber_phiphi, and modelparams::num_redshiftwindows.
Referenced by cambmain::getlimbertransfers().
modeldata_free()
subroutine modeldata::modeldata_free ()
References cl_lensed, cl_scalar, cl_scalar_array, cl_tensor, cl_vector, ctransscal, ctranstens, ctransvec, and free_cltransfer().
Referenced by camb::camb_cleanup().
normalizeclsatl()
subroutine modeldata::normalizeclsatl (integer, intent(in) lnorm)
References c_cross, c_temp, cl_scalar, cl_tensor, modelparams::cp, ct_cross, ct_temp, and modelparams::lmin.
Referenced by cambmain::cltransfertocl().
open_file_header()
integer function modeldata::open_file_header (character(len=*), intent(in) filename, character(len=*), intent(in) Col1, character(len=name_tag_len), dimension(:), intent(in) Columns, integer, intent(in), optional n)
References modelparams::output_file_headers.
Referenced by output_cl_files(), output_lens_pot_files(), output_veccl_files(), transfer::transfer_savematterpower(), and transfer::transfer_savetofiles().
output_cl_files()
subroutine modeldata::output_cl_files (character(len=*) ScalFile, character(len=*) ScalCovFile, character(len=*) TensFile, character(len=*) TotFile, character(len=*) LensFile, character(len=*) LensTotFile, real(dl), intent(in), optional factor)
References c_cross, c_e, c_last, c_name_tags, c_phitemp, c_temp, cl_lensed, cl_scalar, cl_scalar_array, cl_tensor, modelparams::cp, ct_b, ct_cross, ct_name_tags, ct_temp, ctransscal, has_cl_2d_array, lmax_lensed, modelparams::lmin, open_file_header(), and scalar_fieldname().
output_lens_pot_files()
subroutine modeldata::output_lens_pot_files (character(len=*) LensPotFile, real(dl), intent(in), optional factor)
References c_cross, c_e, c_phi, c_temp, cl_scalar, cl_tensor, modelparams::cp, ct_b, ct_cross, ct_e, ct_temp, lens_pot_name_tags, modelparams::lmin, and open_file_header().
output_veccl_files()
subroutine modeldata::output_veccl_files (character(len=*) VecFile, real(dl), intent(in), optional factor)
References cl_vector, modelparams::cp, ct_cross, ct_name_tags, ct_temp, modelparams::lmin, and open_file_header().
scalar_fieldname()
character(len=5) function modeldata::scalar_fieldname (integer, intent(in) i)
Referenced by output_cl_files().
Variable Documentation
c_cross
integer, parameter modeldata::c_cross =3
Referenced by lensing::badharmonic(), cambmain::calcscalcls(), cambmain::calcscalcls2(), camb::camb_getcls(), calculator_camb::cambcalc_setpowersfromcamb(), checkloadedhighltemplate(), lensing::corrfuncflatsky(), lensing::corrfuncfullskyimpl(), cambmain::getsourcemem(), normalizeclsatl(), output_cl_files(), and output_lens_pot_files().
c_e
integer, parameter modeldata::c_e = 2
Referenced by lensing::badharmonic(), cambmain::calcscalcls(), cambmain::calcscalcls2(), camb::camb_getcls(), calculator_camb::cambcalc_setpowersfromcamb(), checkloadedhighltemplate(), lensing::corrfuncflatsky(), lensing::corrfuncfullskyimpl(), output_cl_files(), output_lens_pot_files(), and calculator_pico::pico_getnewpowerdata().
c_last
integer modeldata::c_last = C_PhiE
Referenced by cambmain::calcscalcls2(), cambmain::cltransfertocl(), cambmain::getsourcemem(), init_cls(), cambmain::interpolatecls(), and output_cl_files().
c_name_tags
character(len=name_tag_len), dimension(c_phie), parameter modeldata::c_name_tags = ['TT','EE','TE','PP','TP','EP']
Referenced by output_cl_files().
c_phi
integer, parameter modeldata::c_phi = 4
Referenced by lensing::badharmonic(), cambmain::calclimberscalcls(), cambmain::calcscalcls(), checkloadedhighltemplate(), lensing::corrfuncflatsky(), lensing::corrfuncfullskyimpl(), and output_lens_pot_files().
c_phie
integer, parameter modeldata::c_phie =6
Referenced by cambmain::calcscalcls(), and cambmain::getsourcemem().
c_phitemp
integer, parameter modeldata::c_phitemp = 5
Referenced by cambmain::calcscalcls(), and output_cl_files().
c_temp
integer, parameter modeldata::c_temp = 1
Referenced by lensing::badharmonic(), cambmain::calcscalcls(), cambmain::calcscalcls2(), camb::camb_getcls(), calculator_camb::cambcalc_setpowersfromcamb(), checkloadedhighltemplate(), cambmain::cltransfertocl(), lensing::corrfuncflatsky(), lensing::corrfuncfullskyimpl(), init_cls(), cambmain::interpolatecls(), normalizeclsatl(), output_cl_files(), output_lens_pot_files(), and calculator_pico::pico_getnewpowerdata().
cl_lensed
real(dl), dimension (:,:,:), allocatable modeldata::cl_lensed
Referenced by lensing::badharmonic(), camb::camb_getcls(), calculator_camb::cambcalc_setpowersfromcamb(), lensing::corrfuncflatsky(), lensing::corrfuncfullskyimpl(), modeldata_free(), and output_cl_files().
cl_scalar
real(dl), dimension (:,:,:), allocatable modeldata::cl_scalar
Referenced by lensing::badharmonic(), camb::camb_getcls(), calculator_camb::cambcalc_setpowersfromcamb(), lensing::corrfuncflatsky(), lensing::corrfuncfullskyimpl(), init_cls(), cambmain::interpolatecls(), modeldata_free(), normalizeclsatl(), output_cl_files(), and output_lens_pot_files().
cl_scalar_array
real(dl), dimension (:,:,:,:), allocatable modeldata::cl_scalar_array
Referenced by init_cls(), cambmain::interpolatecls(), modeldata_free(), and output_cl_files().
cl_tensor
real(dl), dimension (:,:,:), allocatable modeldata::cl_tensor
Referenced by lensing::badharmonic(), camb::camb_getcls(), calculator_camb::cambcalc_setpowersfromcamb(), init_cls(), cambmain::interpolatecls(), modeldata_free(), normalizeclsatl(), output_cl_files(), and output_lens_pot_files().
cl_vector
real(dl), dimension (:,:,:), allocatable modeldata::cl_vector
Referenced by init_cls(), cambmain::interpolatecls(), modeldata_free(), and output_veccl_files().
ct_b
integer, parameter modeldata::ct_b = 3
Referenced by lensing::badharmonic(), cambmain::calctenscls(), cambmain::calctensorsources(), cambmain::calcveccls(), cambmain::calcvectorsources(), calculator_camb::cambcalc_setpowersfromcamb(), lensing::corrfuncflatsky(), lensing::corrfuncfullskyimpl(), output_cl_files(), output_lens_pot_files(), and calculator_pico::pico_getnewpowerdata().
ct_cross
integer, parameter modeldata::ct_cross = 4
Referenced by lensing::badharmonic(), cambmain::calctenscls(), cambmain::calcveccls(), camb::camb_getcls(), calculator_camb::cambcalc_setpowersfromcamb(), cambmain::cltransfertocl(), lensing::corrfuncflatsky(), lensing::corrfuncfullskyimpl(), init_cls(), cambmain::interpolatecls(), normalizeclsatl(), output_cl_files(), output_lens_pot_files(), output_veccl_files(), and calculator_pico::pico_getnewpowerdata().
ct_e
integer, parameter modeldata::ct_e = 2
Referenced by lensing::badharmonic(), cambmain::calctenscls(), cambmain::calctensorsources(), cambmain::calcveccls(), cambmain::calcvectorsources(), lensing::corrfuncflatsky(), lensing::corrfuncfullskyimpl(), and output_lens_pot_files().
ct_name_tags
character(len=name_tag_len), dimension(ct_cross), parameter modeldata::ct_name_tags = ['TT','EE','BB','TE']
Referenced by output_cl_files(), and output_veccl_files().
ct_temp
integer, parameter modeldata::ct_temp =1
Referenced by lensing::badharmonic(), cambmain::calctenscls(), cambmain::calctensorsources(), cambmain::calcveccls(), cambmain::calcvectorsources(), camb::camb_getcls(), cambmain::cltransfertocl(), lensing::corrfuncflatsky(), lensing::corrfuncfullskyimpl(), init_cls(), cambmain::interpolatecls(), normalizeclsatl(), output_cl_files(), output_lens_pot_files(), and output_veccl_files().
ctransscal
type(cltransferdata), target, save modeldata::ctransscal
Referenced by camb::camb_getresults(), camb::camb_gettransfers(), cambmain::cmbmain(), dtauda(), cambmain::interpolatecls(), modeldata_free(), and output_cl_files().
ctranstens
type(cltransferdata), target, save modeldata::ctranstens
Referenced by camb::camb_gettransfers(), cambmain::cmbmain(), and modeldata_free().
ctransvec
type(cltransferdata), target, save modeldata::ctransvec
Referenced by camb::camb_gettransfers(), cambmain::cmbmain(), and modeldata_free().
has_cl_2d_array
logical modeldata::has_cl_2d_array = .false.
Referenced by cambmain::calclimberscalcls(), cambmain::calcscalcls(), cambmain::cltransfertocl(), init_cls(), cambmain::interpolatecls(), and output_cl_files().
lens_pot_name_tags
character(len=name_tag_len), dimension(7), parameter modeldata::lens_pot_name_tags = ['TT','EE','BB','TE','PP','TP','EP']
Referenced by output_lens_pot_files().
lmax_lensed
integer modeldata::lmax_lensed
Referenced by lensing::badharmonic(), camb::camb_getcls(), lensing::corrfuncflatsky(), lensing::corrfuncfullskyimpl(), and output_cl_files().
name_tag_len
integer, parameter modeldata::name_tag_len = 12