cosmomc_bde_v3p1: calculator_cosmology Module Reference
calculator_cosmology Module Reference
Data Types
type tcosmologycalculator
type tcosmologyimportanceoptions
Functions/Subroutines
subroutine tcosmologycalculator_readimportanceparams (this, Ini)
subroutine getnewbackgrounddata (this, CMB, Theory, error)
subroutine setparamsforbackground (this, CMB)
subroutine setbackgroundtheorydata (this, CMB, Theory, error)
subroutine getnewtransferdata (this, CMB, Info, Theory, error)
subroutine getnewpowerdata (this, CMB, Info, Theory, error)
subroutine gettheoryforimportance (this, CMB, Theory, error)
subroutine getcosmotheoryforimportance (this, CMB, Theory, error)
real(mcp) function getopticaldepth (this, CMB)
real(mcp) function getzrefromtau (this, CMB, tau)
real(mcp) function cmbtotheta (this, CMB)
real(mcp) function bao_d_v (this, z)
real(mcp) function angulardiameterdistance (this, z)
real(mcp) function comovingradialdistance (this, z)
real(mcp) function angulardiameterdistance2 (this, z1, z2)
real(mcp) function luminositydistance (this, z)
real(mcp) function hofz (this, z)
real(mcp) function hofz_hunit (this, z)
Variables
real(mcp), parameter, public neutrino_mass_fac = 94.07_mcp
real(mcp), parameter, public standard_neutrino_neff = 3.046_mcp
Function/Subroutine Documentation
angulardiameterdistance()
real(mcp) function calculator_cosmology::angulardiameterdistance (class(tcosmologycalculator) this, real(mcp), intent(in) z) private
angulardiameterdistance2()
real(mcp) function calculator_cosmology::angulardiameterdistance2 (class(tcosmologycalculator) this, real(mcp), intent(in) z1, real(mcp), intent(in) z2) private
bao_d_v()
real(mcp) function calculator_cosmology::bao_d_v (class(tcosmologycalculator) this, real(mcp), intent(in) z) private
cmbtotheta()
real(mcp) function calculator_cosmology::cmbtotheta (class(tcosmologycalculator) this, class(cmbparams) CMB) private
comovingradialdistance()
real(mcp) function calculator_cosmology::comovingradialdistance (class(tcosmologycalculator) this, real(mcp), intent(in) z) private
getcosmotheoryforimportance()
subroutine calculator_cosmology::getcosmotheoryforimportance (class(tcosmologycalculator) this, class(cmbparams) CMB, class(tcosmotheorypredictions) Theory, integer error) private
getnewbackgrounddata()
subroutine calculator_cosmology::getnewbackgrounddata (class(tcosmologycalculator) this, class(cmbparams) CMB, class(tcosmotheorypredictions) Theory, integer error) private
getnewpowerdata()
subroutine calculator_cosmology::getnewpowerdata (class(tcosmologycalculator) this, class(cmbparams) CMB, class(ttheoryintermediatecache), pointer Info, class(tcosmotheorypredictions) Theory, integer error) private
getnewtransferdata()
subroutine calculator_cosmology::getnewtransferdata (class(tcosmologycalculator) this, class(cmbparams) CMB, class(ttheoryintermediatecache), pointer Info, class(tcosmotheorypredictions) Theory, integer error) private
getopticaldepth()
real(mcp) function calculator_cosmology::getopticaldepth (class(tcosmologycalculator) this, class(cmbparams) CMB) private
gettheoryforimportance()
subroutine calculator_cosmology::gettheoryforimportance (class(tcosmologycalculator) this, class(ttheoryparams) CMB, class(ttheorypredictions) Theory, integer error) private
getzrefromtau()
real(mcp) function calculator_cosmology::getzrefromtau (class(tcosmologycalculator) this, class(cmbparams) CMB, real(mcp), intent(in) tau) private
hofz()
real(mcp) function calculator_cosmology::hofz (class(tcosmologycalculator) this, real(mcp), intent(in) z) private
hofz_hunit()
real(mcp) function calculator_cosmology::hofz_hunit (class(tcosmologycalculator) this, real(mcp), intent(in) z) private
References settings::const_c.
luminositydistance()
real(mcp) function calculator_cosmology::luminositydistance (class(tcosmologycalculator) this, real(mcp), intent(in) z) private
setbackgroundtheorydata()
subroutine calculator_cosmology::setbackgroundtheorydata (class(tcosmologycalculator) this, class(cmbparams) CMB, class(tcosmotheorypredictions) Theory, integer error) private
setparamsforbackground()
subroutine calculator_cosmology::setparamsforbackground (class(tcosmologycalculator) this, class(cmbparams) CMB) private
tcosmologycalculator_readimportanceparams()
subroutine calculator_cosmology::tcosmologycalculator_readimportanceparams (class(tcosmologycalculator) this, class(tsettingini) Ini) private
Variable Documentation
neutrino_mass_fac
real(mcp), parameter, public calculator_cosmology::neutrino_mass_fac = 94.07_mcp
Referenced by cosmologyparameterizations::bk_paramarraytotheoryparams(), calculator_cosmology::tcosmologycalculator::readimportanceparams(), cosmologyparameterizations::setforh(), and cosmologyparameterizations::tp_nonbaseparameterpriors().
standard_neutrino_neff
real(mcp), parameter, public calculator_cosmology::standard_neutrino_neff = 3.046_mcp
Referenced by elementabundances::abundance_lnlike(), cosmologyparameterizations::bk_paramarraytotheoryparams(), calculator_cosmology::tcosmologycalculator::readimportanceparams(), cosmologyparameterizations::setforh(), and cosmologyparameterizations::tp_nonbaseparameterpriors().