cosmomc_bde_v3p1: calclike Module Reference
calclike Module Reference
Data Types
type tgenericlikecalculator
type tlikecalculator
type tlikelihooduser
type ttheorylikecalculator
type ttheorylikelihooduser
Functions/Subroutines
subroutine addlike (this, CurrentLike, LikeToAdd)
subroutine addliketemp (this, CurrentLike, LikeToAdd)
real(mcp) function getloglikebounds (this, Params)
real(mcp) function getlogpriors (this, P)
real(mcp) function getloglike (this, Params)
real(mcp) function getloglikemain (this, Params)
subroutine tlikecalculator_readparams (this, Ini)
real(mcp) function tlikecalculator_testlikelihoodfunction (this, Params)
subroutine tlikecalculator_writeperformancestats (this, unit)
subroutine tlikecalculator_writeparamshumantext (this, aunit, P, LogLike, weight)
subroutine tlikecalculator_writeparamshumantextfile (this, fname, P, LogLike, weight)
subroutine tlikecalculator_writeparampointtextdata (this, output_root, Params)
real(mcp) function generic_getloglikemain (this, Params)
subroutine theorylike_settheoryparams (this, Params)
subroutine theorylike_setnewtheoryresults (this, Params)
real(mcp) function theorylike_getloglikemain (this, Params)
real(mcp) function theorylike_checkpriorcuts (this, Params)
real(mcp) function theorylike_getloglikepost (this, Params, do_like)
real(mcp) function theorylike_loglikewiththeoryset (this, likelihood_mask)
logical function theorylike_calculaterequiredtheorychanges (this)
subroutine theorylike_gettheoryforlike (this, Like)
subroutine theorylike_gettheoryforimportance (this, Params, error)
subroutine theorylike_updatetheoryforlikelihoods (this, Params)
real(mcp) function theorylike_testlikelihoodfunction (this, Params)
subroutine ttheorylike_writeparamshumantext (this, aunit, P, LogLike, weight)
subroutine ttheorylike_writeparampointtextdata (this, output_root, Params)
Function/Subroutine Documentation
addlike()
subroutine calclike::addlike (class(tlikecalculator) this, real(mcp) CurrentLike, real(mcp), intent(in) LikeToAdd) private
addliketemp()
subroutine calclike::addliketemp (class(tlikecalculator) this, real(mcp) CurrentLike, real(mcp), intent(in) LikeToAdd) private
generic_getloglikemain()
real(mcp) function calclike::generic_getloglikemain (class(tgenericlikecalculator) this, class(tcalculationatparampoint) Params) private
getloglike()
real(mcp) function calclike::getloglike (class(tlikecalculator) this, class(tcalculationatparampoint) Params) private
Referenced by estcovmatmodule::gethess(), estcovmatmodule::getstepsfordchisq1(), and estcovmatmodule::placegrid().
getloglikebounds()
real(mcp) function calclike::getloglikebounds (class(tlikecalculator) this, class(tcalculationatparampoint) Params) private
References baseparameters::baseparams.
getloglikemain()
real(mcp) function calclike::getloglikemain (class(tlikecalculator) this, class(tcalculationatparampoint) Params) private
getlogpriors()
real(mcp) function calclike::getlogpriors (class(tlikecalculator) this, real(mcp), dimension(num_params), intent(in) P) private
References baseparameters::baseparams.
theorylike_calculaterequiredtheorychanges()
logical function calclike::theorylike_calculaterequiredtheorychanges (class(ttheorylikecalculator) this) private
theorylike_checkpriorcuts()
real(mcp) function calclike::theorylike_checkpriorcuts (class(ttheorylikecalculator) this, class(tcalculationatparampoint) Params) private
theorylike_getloglikemain()
real(mcp) function calclike::theorylike_getloglikemain (class(ttheorylikecalculator) this, class(tcalculationatparampoint) Params) private
theorylike_getloglikepost()
real(mcp) function calclike::theorylike_getloglikepost (class(ttheorylikecalculator) this, class(tcalculationatparampoint) Params, logical, dimension(datalikelihoods%count), intent(in), optional do_like) private
theorylike_gettheoryforimportance()
subroutine calclike::theorylike_gettheoryforimportance (class(ttheorylikecalculator) this, class(tcalculationatparampoint), target Params, integer error) private
theorylike_gettheoryforlike()
subroutine calclike::theorylike_gettheoryforlike (class(ttheorylikecalculator) this, class(tdatalikelihood), pointer Like) private
theorylike_loglikewiththeoryset()
real(mcp) function calclike::theorylike_loglikewiththeoryset (class(ttheorylikecalculator) this, logical, dimension(datalikelihoods%count), intent(in), optional likelihood_mask) private
theorylike_setnewtheoryresults()
subroutine calclike::theorylike_setnewtheoryresults (class(ttheorylikecalculator) this, class(tcalculationatparampoint) Params) private
theorylike_settheoryparams()
subroutine calclike::theorylike_settheoryparams (class(ttheorylikecalculator) this, class(tcalculationatparampoint), target Params) private
theorylike_testlikelihoodfunction()
real(mcp) function calclike::theorylike_testlikelihoodfunction (class(ttheorylikecalculator) this, class(tcalculationatparampoint) Params) private
theorylike_updatetheoryforlikelihoods()
subroutine calclike::theorylike_updatetheoryforlikelihoods (class(ttheorylikecalculator) this, class(tcalculationatparampoint) Params) private
tlikecalculator_readparams()
subroutine calclike::tlikecalculator_readparams (class(tlikecalculator) this, class(tsettingini) Ini) private
tlikecalculator_testlikelihoodfunction()
real(mcp) function calclike::tlikecalculator_testlikelihoodfunction (class(tlikecalculator) this, class(tcalculationatparampoint) Params) private
tlikecalculator_writeparampointtextdata()
subroutine calclike::tlikecalculator_writeparampointtextdata (class(tlikecalculator) this, character(len=*), intent(in) output_root, class(tcalculationatparampoint) Params) private
tlikecalculator_writeparamshumantext()
subroutine calclike::tlikecalculator_writeparamshumantext (class(tlikecalculator) this, integer, intent(in) aunit, class(tcalculationatparampoint) P, real(mcp), intent(in), optional LogLike, real(mcp), intent(in), optional weight) private
tlikecalculator_writeparamshumantextfile()
subroutine calclike::tlikecalculator_writeparamshumantextfile (class(tlikecalculator) this, character(len=*), intent(in) fname, class(tcalculationatparampoint) P, real(mcp), intent(in), optional LogLike, real(mcp), intent(in), optional weight) private
tlikecalculator_writeperformancestats()
subroutine calclike::tlikecalculator_writeperformancestats (class(tlikecalculator) this, integer, intent(in) unit) private
ttheorylike_writeparampointtextdata()
subroutine calclike::ttheorylike_writeparampointtextdata (class(ttheorylikecalculator) this, character(len=*), intent(in) output_root, class(tcalculationatparampoint) Params) private
ttheorylike_writeparamshumantext()
subroutine calclike::ttheorylike_writeparamshumantext (class(ttheorylikecalculator) this, integer, intent(in) aunit, class(tcalculationatparampoint) P, real(mcp), intent(in), optional LogLike, real(mcp), intent(in), optional weight) private