cosmomc_bde_v3p1: bbn Namespace Reference
bbn Namespace Reference
Classes
type tbbnpredictions
Functions
def yhe_to_ypBBN (Yp)
def ypBBN_to_yhe (YBBN)
def yhe_fit (omegab, dneff, taun)
def dh_fit (omegab, dneff, taun)
def runBBN (eta, DeltaN=0, tau=tau_n, prog='./alter_etannutau.x')
def ypBBN_Parthenope (omegab, neff)
def yhe_to_ypBBN (Yp, ombh2)
def runBBNplot ()
subroutine bbn_init (this)
subroutine bbnpredictions_error (this, S, v1, v2)
Variables
float hbar = 1.05457e-34
int c = 299792458.
float kB = 1.380650e-23
float MeV = 1.6021764e-13
float eV = MeV / 1e6
float G = 6.6738e-11
float TCMB = 2.7255
mP = np.sqrt(hbar * c / G)
float Mpc = 3.0856776e22
float m_proton = 1.672621637e-27
float m_H = 1.673575e-27
float not4 = 3.9715
float m_He = m_H * not4
float zeta3 = 1.202056903
float tau_n = 880.3
tuple n_photon = (kB * TCMB / hbar / c) ** 3 * zeta3 * 2 / np.pi ** 2
tuple omegafac = (1e5 / Mpc) ** 2 / (8 * np.pi * G) * 3
bool alterBBN = False
ombh2s
list DeltaNs = [-3,-2,-1,-0.5,0,0.5,1,2,3,4,5,6,7]
list lines = []
float Yp_fid = 0.2;
tuple rho_b = ombh2 * omegafac;
def YBBN = yhe_fit(ombh2, DeltaN, tau_n)
tuple n_baryon = (4 * Yp_fid / m_He + (1 - Yp_fid) / m_H) * rho_b
tuple eta = n_baryon / n_photon
def outtxt = runBBN(eta,DeltaN)
D = dh_fit(ombh2, DeltaN, tau_n)*1e-5
He3
Li7
Li6
Be7
sigYBBN = 0.0003
sigdD = 6e-7
sigHe3
sigLi7
sigLi6
sigBe7
tuple actual_ombh2 = eta * n_photon * (YBBN * m_He / 4 + (1 - YBBN) * m_H)/omegafac
tuple Yp = (eta * n_photon/ actual_ombh2/omegafac- 1/m_H)/(4/m_He-1/m_H)
tuple line = (('%12.5f ')*6 + ('%12.3e %12.2e')*3)%(actual_ombh2, eta*1e10, DeltaN, Yp, YBBN, sigYBBN, D, sigdD, He3, sigHe3,Li7,sigLi7)
f = open('BBN_full_alterBBN_'+str(tau_n)+'.dat', 'w')
type(tbbnpredictions), target, save bbn_yhe
type(tbbnpredictions), target, save bbn_ypbbn = TBBNPredictions(data_col=5)
type(tbbnpredictions), target, save bbn_ypbbn_err = TBBNPredictions(data_col=6)
type(tbbnpredictions), target, save bbn_dh = TBBNPredictions(data_col=7)
type(tbbnpredictions), target, save bbn_dh_err = TBBNPredictions(data_col=8)
character(len= *), parameter bbn_data_file = 'BBN_full_Parthenelope_880.3.dat'
Function Documentation
bbn_init()
subroutine bbn::bbn_init (class(tbbnpredictions) this)
References bbn_data_file, settings::datadir, and settings::feedback.
bbnpredictions_error()
subroutine bbn::bbnpredictions_error (class(tbbnpredictions) this, character(len=*), intent(in) S, class(*), intent(in), optional v1, class(*), intent(in), optional v2)
dh_fit()
def bbn.dh_fit (omegab, dneff, taun)
runBBN()
def bbn.runBBN (eta, DeltaN = 0, tau = tau_n, prog = './alter_etannutau.x')
Referenced by runBBNplot().
runBBNplot()
def bbn.runBBNplot ()
References CAMB_test_files.float, stringutils.join(), and runBBN().
yhe_fit()
def bbn.yhe_fit (omegab, dneff, taun)
Referenced by camb.model.CAMBparams.set_bbn_helium().
yhe_to_ypBBN() [1/2]
def bbn.yhe_to_ypBBN (Yp)
Referenced by yhe_to_ypBBN().
yhe_to_ypBBN() [2/2]
def bbn.yhe_to_ypBBN (Yp, ombh2)
References yhe_to_ypBBN().
ypBBN_Parthenope()
def bbn.ypBBN_Parthenope (omegab, neff)
ypBBN_to_yhe()
def bbn.ypBBN_to_yhe (YBBN)
Variable Documentation
actual_ombh2
tuple bbn.actual_ombh2 = eta * n_photon * (YBBN * m_He / 4 + (1 - YBBN) * m_H)/omegafac
alterBBN
bool bbn.alterBBN = False
bbn_data_file
character(len=*), parameter bbn.bbn_data_file = 'BBN_full_Parthenelope_880.3.dat'
Referenced by bbn_init().
bbn_dh
type(tbbnpredictions), target, save bbn.bbn_dh = TBBNPredictions(data_col=7)
Referenced by elementabundances::abundance_readini(), and cosmologyparameterizations::tp_calcderivedparams().
bbn_dh_err
type(tbbnpredictions), target, save bbn.bbn_dh_err = TBBNPredictions(data_col=8)
Referenced by elementabundances::abundance_readini().
bbn_yhe
type(tbbnpredictions), target, save bbn.bbn_yhe
bbn_ypbbn
type(tbbnpredictions), target, save bbn.bbn_ypbbn = TBBNPredictions(data_col=5)
Referenced by elementabundances::abundance_readini().
bbn_ypbbn_err
type(tbbnpredictions), target, save bbn.bbn_ypbbn_err = TBBNPredictions(data_col=6)
Referenced by elementabundances::abundance_readini().
Be7
bbn.Be7
c
int bbn.c = 299792458.
D
def bbn.D = dh_fit(ombh2, DeltaN, tau_n)*1e-5
DeltaNs
list bbn.DeltaNs = [-3,-2,-1,-0.5,0,0.5,1,2,3,4,5,6,7]
eta
tuple bbn.eta = n_baryon / n_photon
eV
float bbn.eV = MeV / 1e6
f
bbn.f = open('BBN_full_alterBBN_'+str(tau_n)+'.dat', 'w')
G
float bbn.G = 6.6738e-11
hbar
float bbn.hbar = 1.05457e-34
He3
bbn.He3
kB
float bbn.kB = 1.380650e-23
Li6
bbn.Li6
Li7
bbn.Li7
line
tuple bbn.line = (('%12.5f ')*6 + ('%12.3e %12.2e')*3)%(actual_ombh2, eta*1e10, DeltaN, Yp, YBBN, sigYBBN, D, sigdD, He3, sigHe3,Li7,sigLi7)
lines
list bbn.lines = []
m_H
float bbn.m_H = 1.673575e-27
m_He
float bbn.m_He = m_H * not4
m_proton
float bbn.m_proton = 1.672621637e-27
MeV
float bbn.MeV = 1.6021764e-13
mP
bbn.mP = np.sqrt(hbar * c / G)
Mpc
float bbn.Mpc = 3.0856776e22
n_baryon
tuple bbn.n_baryon = (4 * Yp_fid / m_He + (1 - Yp_fid) / m_H) * rho_b
n_photon
tuple bbn.n_photon = (kB * TCMB / hbar / c) ** 3 * zeta3 * 2 / np.pi ** 2
not4
float bbn.not4 = 3.9715
ombh2s
bbn.ombh2s
Initial value:
 =  np.hstack((np.linspace(0.005, 0.02, num=int((0.02 - 0.005) / 0.001), endpoint=False),
          np.linspace(0.020,0.024, num=16 , endpoint=False),
          np.linspace(0.024, 0.04, num=int((0.04 - 0.024) / 0.001) + 1, endpoint=True)))
omegafac
tuple bbn.omegafac = (1e5 / Mpc) ** 2 / (8 * np.pi * G) * 3
outtxt
def bbn.outtxt = runBBN(eta,DeltaN)
rho_b
tuple bbn.rho_b = ombh2 * omegafac;
sigBe7
bbn.sigBe7
sigdD
int bbn.sigdD = 6e-7
sigHe3
bbn.sigHe3
sigLi6
bbn.sigLi6
sigLi7
bbn.sigLi7
sigYBBN
float bbn.sigYBBN = 0.0003
tau_n
float bbn.tau_n = 880.3
TCMB
float bbn.TCMB = 2.7255
YBBN
bbn.YBBN = yhe_fit(ombh2, DeltaN, tau_n)
Yp
float bbn.Yp = (eta * n_photon/ actual_ombh2/omegafac- 1/m_H)/(4/m_He-1/m_H)
Yp_fid
tuple bbn.Yp_fid = 0.2;
zeta3
float bbn.zeta3 = 1.202056903