cosmomc_bde_v3p1: cosmologyparameterizations Module Reference
cosmologyparameterizations Module Reference
Data Types
type backgroundparameterization
type thetaparameterization
Functions/Subroutines
subroutine tp_init (this, Ini, Names, Config)
real(mcp) function tp_nonbaseparameterpriors (this, CMB)
subroutine tp_paramarraytotheoryparams (this, Params, CMB)
subroutine cosmomc_nxyl (y)
real(mcp) function getypbbn (Yhe)
subroutine tp_calcderivedparams (this, P, Theory, derived)
subroutine setfast (Params, CMB)
subroutine setforh (Params, CMB, H0, wx0, thetaq, firsttime, error)
subroutine bk_init (this, Ini, Names, Config)
subroutine bk_paramarraytotheoryparams (this, Params, CMB)
subroutine bk_calcderivedparams (this, P, Theory, derived)
Function/Subroutine Documentation
bk_calcderivedparams()
subroutine cosmologyparameterizations::bk_calcderivedparams (class(backgroundparameterization) this, real(mcp), dimension(:) P, class(ttheorypredictions), allocatable Theory, real(mcp), dimension(:), allocatable derived) private
bk_init()
subroutine cosmologyparameterizations::bk_init (class(backgroundparameterization) this, class(tsettingini) Ini, class(tparamnames) Names, class(tgeneralconfig), target Config)
bk_paramarraytotheoryparams()
subroutine cosmologyparameterizations::bk_paramarraytotheoryparams (class(backgroundparameterization) this, real(mcp), dimension(:) Params, class(ttheoryparams), target CMB) private
References calculator_cosmology::neutrino_mass_fac, and calculator_cosmology::standard_neutrino_neff.
cosmomc_nxyl()
subroutine cosmologyparameterizations::cosmomc_nxyl (real(mcp), dimension(6) y)
References quint::abde, quint::ddlbde, quint::ddxbde, quint::ddybde, quint::dn, quint::lbde, quint::nbde, quint::numpoints, quint::numpointsex, spline(), quint::xbde, and quint::ybde.
Referenced by tp_paramarraytotheoryparams().
getypbbn()
real(mcp) function cosmologyparameterizations::getypbbn (real(mcp), intent(in) Yhe)
Referenced by tp_calcderivedparams().
setfast()
subroutine cosmologyparameterizations::setfast (real(mcp), dimension(num_params) Params, type(cmbparams) CMB) private
References cosmologytypes::as_index, cosmologytypes::index_initpower, and cosmologytypes::num_initpower.
Referenced by setforh(), and tp_paramarraytotheoryparams().
setforh()
subroutine cosmologyparameterizations::setforh (real(mcp), dimension(num_params) Params, type(cmbparams) CMB, real(mcp) H0, real(mcp) wx0, real(mcp) thetaq, logical, intent(in) firsttime, integer, optional error) private
References constants::c, constants::c8pig_evm2, constants::cobe_cmbtemp, constants::const_pi, cosmologytypes::cosmosettings, constants::default_nnu, constants::ev, constants::ev2tompcm2, constants::gdgc, constants::gsmgut, constants::gsmm, constants::k_b, calculator_cosmology::neutrino_mass_fac, setfast(), and calculator_cosmology::standard_neutrino_neff.
Referenced by tp_paramarraytotheoryparams().
tp_calcderivedparams()
subroutine cosmologyparameterizations::tp_calcderivedparams (class(thetaparameterization) this, real(mcp), dimension(:) P, class(ttheorypredictions), allocatable Theory, real(mcp), dimension(:), allocatable derived) private
References cosmologytypes::as_index, bbn::bbn_dh, cosmologytypes::cl_norm, cosmologytypes::cosmosettings, getypbbn(), cosmologytypes::nrun_index, cosmologytypes::nrunrun_index, and cosmologytypes::ns_index.
tp_init()
subroutine cosmologyparameterizations::tp_init (class(thetaparameterization) this, class(tsettingini) Ini, class(tparamnames) Names, class(tgeneralconfig), target Config) private
References cosmologytypes::cosmosettings, and cosmologytypes::last_power_index.
tp_nonbaseparameterpriors()
real(mcp) function cosmologyparameterizations::tp_nonbaseparameterpriors (class(thetaparameterization) this, class(ttheoryparams) CMB) private
References calculator_cosmology::neutrino_mass_fac, and calculator_cosmology::standard_neutrino_neff.
tp_paramarraytotheoryparams()
subroutine cosmologyparameterizations::tp_paramarraytotheoryparams (class(thetaparameterization) this, real(mcp), dimension(:) Params, class(ttheoryparams), target CMB) private
References quint::bde_xylata(), constants::c, constants::c8pig_evm2, cosmomc_nxyl(), constants::ev2tompcm2, constants::mpl2, cosmologytypes::num_hard, setfast(), setforh(), quint::xbde, and quint::ybde.