cosmomc_bde_v3p1: constants Module Reference
constants Module Reference
Variables
real(dl), parameter const_pi = 3.1415926535897932384626433832795_dl
real(dl), parameter const_twopi =2._dl*const_pi
real(dl), parameter const_fourpi =4._dl*const_pi
real(dl), parameter const_sqrt6 =2.4494897427831780981972840747059_dl
real(dl), parameter c = 2.99792458e8_dl
real(dl), parameter h_p = 6.62606896e-34_dl
real(dl), parameter hbar = h_P/const_twopi
real(dl), parameter g =6.6738e-11_dl
real(dl), parameter sigma_thomson = 6.6524616e-29_dl
real(dl), parameter sigma_boltz = 5.6704e-8_dl
real(dl), parameter k_b = 1.3806504e-23_dl
real(dl), parameter ev = 1.60217646e-19_dl
real(dl), parameter m_p = 1.672621637e-27_dl
real(dl), parameter m_h = 1.673575e-27_dl
real(dl), parameter m_e = 9.10938215e-31_dl
real(dl), parameter mass_ratio_he_h = 3.9715_dl
real(dl), parameter gyr =3.1556926e16_dl
real(dl), parameter mpc = 3.085678e22_dl
real(dl), parameter mpc_in_sec = Mpc/c
real(dl), parameter barssc0 = k_B / m_p / c**2
real(dl), parameter kappa =8._dl*const_pi*G
real(dl), parameter a_rad = 8._dl*const_pi**5*k_B**4/15/c**3/h_p**3
real(dl), parameter compton_ct = MPC_in_sec*(8.d0/3.d0)*(sigma_thomson/(m_e*c))*a_rad
real(dl), parameter f_21cm = 1420.40575e6_dl
real(dl), parameter l_21cm = c/f_21cm
real(dl), parameter t_21cm = h_P*f_21cm/k_B
real(dl), parameter a10 = 2.869e-15
real(dl), parameter b10 = l_21cm**3/2/h_P/c*A10
real(dl), parameter line21_const = 3*l_21cm**2*C*h_P/32/const_pi/k_B*A10 * Mpc_in_sec * 1000
real(dl), parameter cobe_cmbtemp = 2.7255_dl
real(dl), parameter default_nnu = 3.046_dl
real(dl), parameter delta_mnu21 = 7.54e-5_dl
real(dl), parameter delta_mnu31 = 2.46e-3_dl
real(dl), parameter mnu_min_normal = 0.06_dl
real(dl), parameter ev2tompcm2 =(2._dl*const_pi*eV*Mpc/(c*h_P))**2
real(dl), parameter c8pig_evm2 =16._dl*const_pi**2*G*eV**2/(h_P*c**5)
real(dl), parameter mpl2 =h_P*c**5/(16._dl*const_pi**2*G*eV**2)
real(dl), parameter gdgc =97.5
real(dl), parameter gsmm =10.75
real(dl), parameter gsmgut =228.75
Variable Documentation
a10
real(dl), parameter constants::a10 = 2.869e-15
Referenced by recombination::ion(), and recombination::recombination_init().
a_rad
real(dl), parameter constants::a_rad = 8._dl*const_pi**5*k_B**4/15/c**3/h_p**3
Referenced by recombination::recombination_init().
b10
real(dl), parameter constants::b10 = l_21cm**3/2/h_P/c*A10
barssc0
real(dl), parameter constants::barssc0 = k_B / m_p / c**2
Referenced by thermodata::inithermo().
c
real(dl), parameter constants::c = 2.99792458e8_dl
Referenced by quint::bde_h0(), handles::camb_getbackgroundoutputs(), handles::camb_primordialpower(), modelparams::cambparams_set(), modelparams::deltaphysicaltimegyr(), recombination::ion(), recombination::recombination_init(), cosmologyparameterizations::setforh(), and cosmologyparameterizations::tp_paramarraytotheoryparams().
c8pig_evm2
real(dl), parameter constants::c8pig_evm2 =16._dl*const_pi**2*G*eV**2/(h_P*c**5)
Referenced by quint::bde_h0(), modelparams::cambparams_set(), cosmologyparameterizations::setforh(), and cosmologyparameterizations::tp_paramarraytotheoryparams().
cobe_cmbtemp
real(dl), parameter constants::cobe_cmbtemp = 2.7255_dl
Referenced by camb::camb_setdefparams(), and cosmologyparameterizations::setforh().
compton_ct
real(dl), parameter constants::compton_ct = MPC_in_sec*(8.d0/3.d0)*(sigma_thomson/(m_e*c))*a_rad
Referenced by thermodata::inithermo(), and recombination::recombination_init().
const_fourpi
real(dl), parameter constants::const_fourpi =4._dl*const_pi
const_pi
real(dl), parameter constants::const_pi = 3.1415926535897932384626433832795_dl
Referenced by cosmologyparameterizations::setforh().
const_sqrt6
real(dl), parameter constants::const_sqrt6 =2.4494897427831780981972840747059_dl
const_twopi
real(dl), parameter constants::const_twopi =2._dl*const_pi
default_nnu
real(dl), parameter constants::default_nnu = 3.046_dl
Referenced by camb::camb_setdefparams(), camb::camb_setneutrinohierarchy(), calculator_camb::cambcalc_cmbtocamb(), and cosmologyparameterizations::setforh().
delta_mnu21
real(dl), parameter constants::delta_mnu21 = 7.54e-5_dl
Referenced by camb::camb_setneutrinohierarchy(), calculator_camb::cambcalc_cmbtocamb(), and massivenu::sum_mnu_for_m1().
delta_mnu31
real(dl), parameter constants::delta_mnu31 = 2.46e-3_dl
Referenced by camb::camb_setneutrinohierarchy(), calculator_camb::cambcalc_cmbtocamb(), and massivenu::sum_mnu_for_m1().
ev
real(dl), parameter constants::ev = 1.60217646e-19_dl
Referenced by modelparams::cambparams_set(), dtauda(), getdist.densities.Density2D::Prob(), and cosmologyparameterizations::setforh().
ev2tompcm2
real(dl), parameter constants::ev2tompcm2 =(2._dl*const_pi*eV*Mpc/(c*h_P))**2
Referenced by quint::bde_h0(), modelparams::cambparams_set(), cosmologyparameterizations::setforh(), and cosmologyparameterizations::tp_paramarraytotheoryparams().
f_21cm
real(dl), parameter constants::f_21cm = 1420.40575e6_dl
g
real(dl), parameter constants::g =6.6738e-11_dl
Referenced by recombination::recombination_init().
gdgc
real(dl), parameter constants::gdgc =97.5
Referenced by cosmologyparameterizations::setforh().
gsmgut
real(dl), parameter constants::gsmgut =228.75
Referenced by cosmologyparameterizations::setforh().
gsmm
real(dl), parameter constants::gsmm =10.75
Referenced by cosmologyparameterizations::setforh().
gyr
real(dl), parameter constants::gyr =3.1556926e16_dl
Referenced by modelparams::deltaphysicaltimegyr().
h_p
real(dl), parameter constants::h_p = 6.62606896e-34_dl
Referenced by recombination::ion(), and recombination::recombination_init().
hbar
real(dl), parameter constants::hbar = h_P/const_twopi
k_b
real(dl), parameter constants::k_b = 1.3806504e-23_dl
Referenced by modelparams::cambparams_set(), recombination::ion(), recombination::recombination_init(), and cosmologyparameterizations::setforh().
kappa
real(dl), parameter constants::kappa =8._dl*const_pi*G
Referenced by modelparams::cambparams_set().
l_21cm
real(dl), parameter constants::l_21cm = c/f_21cm
line21_const
real(dl), parameter constants::line21_const = 3*l_21cm**2*C*h_P/32/const_pi/k_B*A10 * Mpc_in_sec * 1000
Referenced by recombination::recombination_init().
m_e
real(dl), parameter constants::m_e = 9.10938215e-31_dl
Referenced by recombination::recombination_init().
m_h
real(dl), parameter constants::m_h = 1.673575e-27_dl
Referenced by modelparams::cambparams_set(), recombination::ion(), and recombination::recombination_init().
m_p
real(dl), parameter constants::m_p = 1.672621637e-27_dl
mass_ratio_he_h
real(dl), parameter constants::mass_ratio_he_h = 3.9715_dl
Referenced by modelparams::cambparams_set(), and reionization::reionization_init().
mnu_min_normal
real(dl), parameter constants::mnu_min_normal = 0.06_dl
Referenced by camb::camb_setneutrinohierarchy(), and calculator_camb::cambcalc_cmbtocamb().
mpc
real(dl), parameter constants::mpc = 3.085678e22_dl
Referenced by modelparams::cambparams_set(), and modelparams::deltaphysicaltimegyr().
mpc_in_sec
real(dl), parameter constants::mpc_in_sec = Mpc/c
Referenced by recombination::ddeltaxe_dtau(), recombination::ion(), and recombination::recombination_init().
mpl2
real(dl), parameter constants::mpl2 =h_P*c**5/(16._dl*const_pi**2*G*eV**2)
Referenced by modelparams::cambparams_set(), and cosmologyparameterizations::tp_paramarraytotheoryparams().
sigma_boltz
real(dl), parameter constants::sigma_boltz = 5.6704e-8_dl
Referenced by modelparams::cambparams_set().
sigma_thomson
real(dl), parameter constants::sigma_thomson = 6.6524616e-29_dl
Referenced by modelparams::cambparams_set().
t_21cm
real(dl), parameter constants::t_21cm = h_P*f_21cm/k_B
Referenced by recombination::ion(), and recombination::recombination_init().