cosmomc_bde_v3p1: paramnames Module Reference
paramnames Module Reference
Data Types
type tbaseparamnames
type tparamnames
Functions/Subroutines
logical function paramnames_parseline (this, InLine, n)
subroutine paramnames_alloc (this, n)
subroutine paramnames_dealloc (this)
subroutine paramnames_init (this, filename)
subroutine paramnames_assignitem (this, Names2, n, i)
subroutine paramnames_addfile (this, filename, check_duplicates)
subroutine paramnames_add (this, Names, check_duplicates)
subroutine paramnames_setlabels (this, filename)
subroutine paramnames_setunnamed (this, nparams, prefix)
integer function paramnames_index (this, name)
character(len=:) function, allocatable paramnames_label (this, name)
character(len=:) function, allocatable paramnames_name (this, ix)
subroutine paramnames_readindices (this, InLine, params, num, unknown_value)
character(len=:) function, allocatable paramnames_asstring (this, i, want_comment)
subroutine paramnames_writefile (this, fname, indices, add_derived)
character(len=:) function, allocatable paramnames_nameornumber (this, ix, tag_derived)
integer function paramnames_maxnamelen (this)
character(len=:) function, allocatable paramnames_readiniforparam (this, Ini, Key, param)
logical function paramnames_hasreadiniforparam (this, Ini, Key, param)
subroutine paramnames_addderivedrange (this, Name, Mn, Mx)
Variables
integer, parameter, public paramnames_maxlen = 128
Function/Subroutine Documentation
paramnames_add()
subroutine paramnames::paramnames_add (class(tparamnames), target this, class(tparamnames), target Names, logical, intent(in), optional check_duplicates) private
References miscutils::defaultfalse(), and mpiutils::mpistop().
paramnames_addderivedrange()
subroutine paramnames::paramnames_addderivedrange (class(tparamnames) this, character(len=*), intent(in) Name, real(mcp), intent(in), optional Mn, real(mcp), intent(in), optional Mx)
paramnames_addfile()
subroutine paramnames::paramnames_addfile (class(tparamnames), target this, character(len=*), intent(in) filename, logical, intent(in), optional check_duplicates) private
paramnames_alloc()
subroutine paramnames::paramnames_alloc (class(tparamnames) this, integer, intent(in) n) private
paramnames_assignitem()
subroutine paramnames::paramnames_assignitem (class(tparamnames), target this, class(tbaseparamnames), target Names2, integer n, integer i) private
paramnames_asstring()
character(len=:) function, allocatable paramnames::paramnames_asstring (class(tparamnames) this, integer, intent(in) i, logical, intent(in), optional want_comment) private
References mpiutils::mpistop().
paramnames_dealloc()
subroutine paramnames::paramnames_dealloc (class(tparamnames) this) private
paramnames_hasreadiniforparam()
logical function paramnames::paramnames_hasreadiniforparam (class(tparamnames) this, class(tinifile) Ini, character(len=*), intent(in) Key, integer, intent(in) param)
References stringutils::inttostr().
paramnames_index()
integer function paramnames::paramnames_index (class(tparamnames) this, character(len=*), intent(in) name) private
paramnames_init()
subroutine paramnames::paramnames_init (class(tparamnames) this, character(len=*), intent(in) filename) private
References stringutils::concat(), fileutils::file, mpiutils::mpistop(), and stringutils::stringreplace().
paramnames_label()
character(len = :) function, allocatable paramnames::paramnames_label (class(tparamnames) this, character(len=*), intent(in) name) private
paramnames_maxnamelen()
integer function paramnames::paramnames_maxnamelen (class(tparamnames) this) private
paramnames_name()
character(len=:) function, allocatable paramnames::paramnames_name (class(tparamnames) this, integer, intent(in) ix) private
paramnames_nameornumber()
character(len=:) function, allocatable paramnames::paramnames_nameornumber (class(tparamnames) this, integer, intent(in) ix, logical, intent(in), optional tag_derived) private
References miscutils::defaultfalse(), and stringutils::inttostr().
paramnames_parseline()
logical function paramnames::paramnames_parseline (class(tparamnames) this, character(len=*) InLine, integer n) private
References stringutils::iswhitespace().
paramnames_readindices()
subroutine paramnames::paramnames_readindices (class(tparamnames) this, character(len=*), intent(in) InLine, integer, dimension(*), intent(out) params, integer num, integer, intent(in), optional unknown_value) private
References stringutils::iswhitespace(), and mpiutils::mpistop().
paramnames_readiniforparam()
character(len=:) function, allocatable paramnames::paramnames_readiniforparam (class(tparamnames) this, class(tinifile) Ini, character(len=*), intent(in) Key, integer, intent(in) param) private
References stringutils::inttostr().
paramnames_setlabels()
subroutine paramnames::paramnames_setlabels (class(tparamnames) this, character(len=*), intent(in) filename) private
paramnames_setunnamed()
subroutine paramnames::paramnames_setunnamed (class(tparamnames) this, integer, intent(in) nparams, character(len=*), intent(in), optional prefix) private
References stringutils::inttostr().
paramnames_writefile()
subroutine paramnames::paramnames_writefile (class(tparamnames) this, character(len=*), intent(in) fname, integer, dimension(:), intent(in), optional indices, logical, intent(in), optional add_derived) private
Variable Documentation
paramnames_maxlen
integer, parameter, public paramnames::paramnames_maxlen = 128
Referenced by paramnames::tparamnames::add().