cosmomc_bde_v3p1: cosmology Module Reference
cosmology Module Reference
Data Types
type cospar
Functions/Subroutines
real(dl) function eh (z)
real(dl) function omegam (z)
real(dl) function omegade (z)
real(dl) function omegak (z)
real(dl) function r (z)
real(dl) function rint (z)
real(dl) function da (z)
real(dl) function dvdzdo (z)
Variables
type(cospar), save cosmopar
Function/Subroutine Documentation
da()
real(dl) function cosmology::da (real(dl), intent(in) z)
References r().
Referenced by massobservable::theta500(), and massobservable::y500().
dvdzdo()
real(dl) function cosmology::dvdzdo (real(dl), intent(in) z)
References eh(), and r().
eh()
real(dl) function cosmology::eh (real(dl), intent(in) z)
References cosmopar.
Referenced by dvdzdo(), omegade(), omegam(), rint(), massobservable::theta500(), and massobservable::y500().
omegade()
real(dl) function cosmology::omegade (real(dl), intent(in) z)
References cosmopar, and eh().
Referenced by power_sz::ddelta(), and omegak().
omegak()
real(dl) function cosmology::omegak (real(dl), intent(in) z)
References omegade(), and omegam().
Referenced by power_sz::ddelta().
omegam()
real(dl) function cosmology::omegam (real(dl), intent(in) z)
References cosmopar, and eh().
Referenced by power_sz::ddelta(), power_sz::growint(), and omegak().
r()
real(dl) function cosmology::r (real(dl), intent(in) z)
References cosmopar, rint(), and rombint().
Referenced by da(), and dvdzdo().
rint()
real(dl) function cosmology::rint (real(dl), intent(in) z)
References eh().
Referenced by r().
Variable Documentation
cosmopar
type (cospar), save cosmology::cosmopar
Referenced by power_sz::ddelta(), power_sz::delta(), eh(), power_sz::growint(), omegade(), omegam(), r(), szcounts::szcc_cash(), massobservable::theta500(), and massobservable::y500().