cosmomc_bde_v3p1: recombination Module Reference
recombination Module Reference
Data Types
type recombinationparams
Functions/Subroutines
subroutine, public recombination_readparams (R, Ini)
subroutine, public recombination_setdefparams (R)
subroutine, public recombination_validate (R, OK)
real(dl) function, public recombination_tm (a)
real(dl) function, public recombination_ts (a)
real(dl) function, public recombination_xe (a)
subroutine, public recombination_init (Recomb, OmegaC, OmegaB, Omegan, Omegav, h0inp, tcmb, yp, nnu)
subroutine get_init (z, x_H0, x_He0, x0)
subroutine ion (Recomb, Ndim, z, Y, f)
real(dl) function, public ddeltaxe_dtau (a, Delta_xe, Delta_nH, Delta_Tm, hdot, kvb)
real(dl) function polevl (x, coef, N)
real(dl) function derivpolevl (x, coef, N)
real(dl) function, public kappa_hh_21cm (T, deriv)
real(dl) function, public kappa_eh_21cm (T, deriv)
real(dl) function, public kappa_ph_21cm (T, deriv)
Variables
real(dl), parameter zinitial = 1e4_dl
real(dl), parameter zfinal =0._dl
integer, parameter nz =10000
real(dl), parameter delta_z = (zinitial-zfinal)/Nz
integer, parameter recfast_heswitch_default = 6
real(dl), parameter recfast_fudge_he_default = 0.86_dl
logical, parameter recfast_hswitch_default = .true.
real(dl), parameter recfast_fudge_default = 1.14_dl
real(dl), parameter recfast_fudge_default2 = 1.105d0 + 0.02d0
real(dl) agauss1 = -0.14D0
real(dl) agauss2 = 0.079D0
real(dl) zgauss1 = 7.28D0
real(dl) zgauss2 = 6.73D0
real(dl) wgauss1 = 0.18D0
real(dl) wgauss2 = 0.33D0
character(len= *), parameter, public recombination_name = 'Recfast_1.5.2'
real(dl), dimension(nz) zrec
real(dl), dimension(nz) xrec
real(dl), dimension(nz) dxrec
real(dl), dimension(nz) tsrec
real(dl), dimension(nz) dtsrec
real(dl), dimension(nz) tmrec
real(dl), dimension(nz) dtmrec
real(dl), parameter, public do21cm_mina = 1/(1+900.)
logical, parameter evolve_ts = .false.
real(dl), parameter do21cm_minev = 1/(1+400.)
real(dl), parameter b01 = 3*B10
real(dl) nnow
real(dl) fhe
logical, public do21cm = .false.
logical, public dotmattspin = .false.
real(dl), public recombination_saha_z
real(dl), public recombination_saha_tau
Function/Subroutine Documentation
ddeltaxe_dtau()
real(dl) function, public recombination::ddeltaxe_dtau (real(dl), intent(in) a, real(dl), intent(in) Delta_xe, real(dl), intent(in) Delta_nH, real(dl), intent(in) Delta_Tm, real(dl), intent(in) hdot, real(dl), intent(in) kvb)
References recdata::cb1, recdata::cdb, recdata::ck, recdata::cl, recdata::cr, dtauda(), fhe, recdata::fu, recdata::lambda, constants::mpc_in_sec, nnow, recombination_tm(), recombination_xe(), and recdata::tnow.
derivpolevl()
real(dl) function recombination::derivpolevl (real(dl) x, real(dl), dimension(n+1) coef, integer N) private
Referenced by kappa_eh_21cm().
get_init()
subroutine recombination::get_init (real(dl) z, real(dl) x_H0, real(dl) x_He0, real(dl) x0)
References recdata::cb1, recdata::cb1_he1, recdata::cb1_he2, recdata::cr, fhe, nnow, and recdata::tnow.
Referenced by recombination_init().
ion()
subroutine recombination::ion (type (recombinationparams) Recomb, integer Ndim, real(dl) z, real(dl), dimension(ndim) Y, real(dl), dimension(ndim) f)
References constants::a10, recdata::a2p_s, recdata::a2p_t, agauss1, agauss2, recdata::bfact, constants::c, recdata::cdb, recdata::cdb_he, recdata::ck, recdata::ck_he, recdata::cl, recdata::cl_he, recdata::cr, recdata::ct, do21cm, do21cm_minev, evolve_ts, fhe, recdata::fu, recdata::h_frac, constants::h_p, recdata::ho, constants::k_b, kappa_eh_21cm(), kappa_hh_21cm(), recdata::l_he2st_ion, recdata::l_he_2p, recdata::l_he_2pt, recdata::l_he_2st, recdata::lambda, recdata::lambda_he, constants::m_h, constants::mpc_in_sec, nnow, recdata::not4, recdata::omegak, recdata::omegat, recombination_saha_z, recdata::sigma_he_2ps, recdata::sigma_he_2pt, constants::t_21cm, recdata::tnow, wgauss1, wgauss2, recdata::z_eq, zgauss1, and zgauss2.
Referenced by recombination_init().
kappa_eh_21cm()
real(dl) function, public recombination::kappa_eh_21cm (real(dl), intent(in) T, logical, intent(in) deriv)
References derivpolevl(), and polevl().
Referenced by ion(), and recombination_init().
kappa_hh_21cm()
real(dl) function, public recombination::kappa_hh_21cm (real(dl), intent(in) T, logical, intent(in) deriv)
References spline().
Referenced by ion(), and recombination_init().
kappa_ph_21cm()
real(dl) function, public recombination::kappa_ph_21cm (real(dl), intent(in) T, logical, intent(in) deriv)
References spline().
polevl()
real(dl) function recombination::polevl (real(dl) x, real(dl), dimension(n+1) coef, integer N)
Referenced by kappa_eh_21cm().
recombination_init()
subroutine, public recombination::recombination_init (type (recombinationparams) Recomb, real(dl), intent(in) OmegaC, real(dl), intent(in) OmegaB, real(dl), intent(in) Omegan, real(dl), intent(in) Omegav, real(dl), intent(in) h0inp, real(dl) tcmb, real(dl), intent(in) yp, real(dl), intent(in), optional nnu)
References constants::a10, constants::a_rad, recdata::bfact, recdata::bigh, constants::c, recdata::cb1, recdata::cb1_he1, recdata::cb1_he2, recdata::cdb, recdata::cdb_he, recdata::ck, recdata::ck_he, recdata::cl, recdata::cl_he, constants::compton_ct, recdata::cr, recdata::ct, recdata::deltab, recdata::deltab_he, do21cm, do21cm_minev, dotmattspin, dtauda(), dtmrec, dtsrec, dverk(), dxrec, evolve_ts, fhe, recdata::fu, constants::g, get_init(), recdata::h_frac, constants::h_p, recdata::ho, ion(), constants::k_b, kappa_eh_21cm(), kappa_hh_21cm(), recdata::l_h_alpha, recdata::l_h_ion, recdata::l_he1_ion, recdata::l_he2_ion, recdata::l_he_2p, recdata::l_he_2s, recdata::lalpha, recdata::lalpha_he, constants::line21_const, constants::m_e, constants::m_h, constants::mpc_in_sec, recdata::mu_h, recdata::mu_t, recdata::n_eq, nnow, recdata::not4, nz, recdata::omegak, recdata::omegat, recombination_saha_z, spline(), constants::t_21cm, tmrec, recdata::tnow, tsrec, xrec, recdata::z_eq, zinitial, and zrec.
recombination_readparams()
subroutine, public recombination::recombination_readparams (type(recombinationparams) R, type(tinifile) Ini)
References agauss1, agauss2, inifile::ini_read_double_file(), inifile::ini_read_int_file(), inifile::ini_read_logical_file(), recfast_fudge_default, recfast_fudge_default2, recfast_fudge_he_default, recfast_heswitch_default, recfast_hswitch_default, wgauss1, wgauss2, zgauss1, and zgauss2.
recombination_setdefparams()
subroutine, public recombination::recombination_setdefparams (type (recombinationparams) R)
References recfast_fudge_default, recfast_fudge_default2, recfast_fudge_he_default, recfast_heswitch_default, and recfast_hswitch_default.
Referenced by camb::camb_setdefparams().
recombination_tm()
real(dl) function, public recombination::recombination_tm (real(dl) a)
References delta_z, dotmattspin, dtmrec, nz, tmrec, recdata::tnow, zinitial, and zrec.
Referenced by ddeltaxe_dtau().
recombination_ts()
real(dl) function, public recombination::recombination_ts (real(dl), intent(in) a)
References delta_z, dtsrec, nz, tsrec, zinitial, and zrec.
recombination_validate()
subroutine, public recombination::recombination_validate (type(recombinationparams), intent(in) R, logical, intent(inout) OK)
Referenced by camb::camb_validateparams().
recombination_xe()
real(dl) function, public recombination::recombination_xe (real(dl), intent(in) a)
References delta_z, dxrec, nz, xrec, zinitial, and zrec.
Referenced by ddeltaxe_dtau().
Variable Documentation
agauss1
real(dl) recombination::agauss1 = -0.14D0 private
Referenced by ion(), and recombination_readparams().
agauss2
real(dl) recombination::agauss2 = 0.079D0 private
Referenced by ion(), and recombination_readparams().
b01
real(dl), parameter recombination::b01 = 3*B10 private
delta_z
real(dl), parameter recombination::delta_z = (zinitial-zfinal)/Nz private
Referenced by recombination_tm(), recombination_ts(), and recombination_xe().
do21cm
logical, public recombination::do21cm = .false.
Referenced by ion(), and recombination_init().
do21cm_mina
real(dl), parameter, public recombination::do21cm_mina = 1/(1+900.)
do21cm_minev
real(dl), parameter recombination::do21cm_minev = 1/(1+400.) private
Referenced by ion(), and recombination_init().
dotmattspin
logical, public recombination::dotmattspin = .false.
Referenced by recombination_init(), and recombination_tm().
dtmrec
real(dl), dimension(nz) recombination::dtmrec private
Referenced by recombination_init(), and recombination_tm().
dtsrec
real(dl), dimension(nz) recombination::dtsrec private
Referenced by recombination_init(), and recombination_ts().
dxrec
real(dl), dimension(nz) recombination::dxrec private
Referenced by recombination_init(), and recombination_xe().
evolve_ts
logical, parameter recombination::evolve_ts = .false. private
Referenced by ion(), and recombination_init().
fhe
real(dl) recombination::fhe private
Referenced by ddeltaxe_dtau(), get_init(), ion(), and recombination_init().
nnow
real(dl) recombination::nnow private
Referenced by ddeltaxe_dtau(), get_init(), ion(), and recombination_init().
nz
integer, parameter recombination::nz =10000 private
Referenced by recombination_init(), recombination_tm(), recombination_ts(), and recombination_xe().
recfast_fudge_default
real(dl), parameter recombination::recfast_fudge_default = 1.14_dl private
Referenced by recombination_readparams(), and recombination_setdefparams().
recfast_fudge_default2
real(dl), parameter recombination::recfast_fudge_default2 = 1.105d0 + 0.02d0 private
Referenced by recombination_readparams(), and recombination_setdefparams().
recfast_fudge_he_default
real(dl), parameter recombination::recfast_fudge_he_default = 0.86_dl private
Referenced by recombination_readparams(), and recombination_setdefparams().
recfast_heswitch_default
integer, parameter recombination::recfast_heswitch_default = 6 private
Referenced by recombination_readparams(), and recombination_setdefparams().
recfast_hswitch_default
logical, parameter recombination::recfast_hswitch_default = .true. private
Referenced by recombination_readparams(), and recombination_setdefparams().
recombination_name
character(len=*), parameter, public recombination::recombination_name = 'Recfast_1.5.2'
recombination_saha_tau
real(dl), public recombination::recombination_saha_tau
recombination_saha_z
real(dl), public recombination::recombination_saha_z
Referenced by ion(), and recombination_init().
tmrec
real(dl), dimension(nz) recombination::tmrec private
Referenced by recombination_init(), and recombination_tm().
tsrec
real(dl), dimension(nz) recombination::tsrec private
Referenced by recombination_init(), and recombination_ts().
wgauss1
real(dl) recombination::wgauss1 = 0.18D0 private
Referenced by ion(), and recombination_readparams().
wgauss2
real(dl) recombination::wgauss2 = 0.33D0 private
Referenced by ion(), and recombination_readparams().
xrec
real(dl), dimension(nz) recombination::xrec private
Referenced by recombination_init(), and recombination_xe().
zfinal
real(dl), parameter recombination::zfinal =0._dl private
zgauss1
real(dl) recombination::zgauss1 = 7.28D0 private
Referenced by ion(), and recombination_readparams().
zgauss2
real(dl) recombination::zgauss2 = 6.73D0 private
Referenced by ion(), and recombination_readparams().
zinitial
real(dl), parameter recombination::zinitial = 1e4_dl private
Referenced by recombination_init(), recombination_tm(), recombination_ts(), and recombination_xe().
zrec
real(dl), dimension(nz) recombination::zrec private
Referenced by recombination_init(), recombination_tm(), recombination_ts(), and recombination_xe().