cosmomc_bde_v3p1: paramgrid.gridconfig Namespace Reference
paramgrid.gridconfig Namespace Reference
Functions
def getArgs (vals=None)
def setMinimize (jobItem, ini)
def updateIniParams (ini, params, path)
def pathIsGrid (batchPath)
def makeGrid (batchPath, settingName=None, settings=None, readOnly=False, interactive=False)
Variables
default_params = dict()
dictionary default_param_extra_opts
Function Documentation
getArgs()
def paramgrid.gridconfig.getArgs (vals = None)
makeGrid()
def paramgrid.gridconfig.makeGrid (batchPath, settingName = None, settings = None, readOnly = False, interactive = False)
References paramgrid.gridconfig.pathIsGrid(), paramgrid.gridconfig.setMinimize(), and paramgrid.gridconfig.updateIniParams().
pathIsGrid()
def paramgrid.gridconfig.pathIsGrid (batchPath)
Referenced by paramgrid.gridconfig.makeGrid().
setMinimize()
def paramgrid.gridconfig.setMinimize (jobItem, ini)
Referenced by paramgrid.gridconfig.makeGrid().
updateIniParams()
def paramgrid.gridconfig.updateIniParams (ini, params, path)
Referenced by paramgrid.gridconfig.makeGrid().
Variable Documentation
default_param_extra_opts
dictionary paramgrid.gridconfig.default_param_extra_opts
Initial value:
 =  {
     'mnu': {'num_massive_neutrinos': 3},
     'meffsterile': {'param[mnu]': '0.06', 'param[nnu]': '3.1 3.046 10 0.05 0.05', 'num_massive_neutrinos': 1,
                     'accuracy_level': 1.2},
     'yhe': {'bbn_consistency': False},
     'r': {'compute_tensors': True},
     'nt': {'inflation_consistency': False, 'lmax_tensor': 1000}
 }
default_params
paramgrid.gridconfig.default_params = dict()