cosmomc_bde_v3p1: handles Module Reference
handles Module Reference
Data Types
type c_cltransferdata
type c_mattertransferdata
Functions/Subroutines
subroutine cambdata_new (handle)
subroutine cambdata_free (cptr)
subroutine cambdata_setparams (data, Params)
subroutine cambdata_getparams (data, handle)
integer function cambdata_gettransfers (data, Params, onlytransfer)
subroutine cambdata_setparamsforbackground (data, P)
integer function cambdata_calcbackgroundtheory (data, P)
subroutine cambdata_mattertransferdata (data, cData)
subroutine cambdata_cltransferdata (data, cData, i)
subroutine convert_cltransferdata (data, cData)
subroutine cambdata_getlinearmatterpower (data, PK, var1, var2, hubble_units)
subroutine cambdata_getnonlinearmatterpower (data, PK, var1, var2, hubble_units)
subroutine cambdata_getmatterpower (data, outpower, minkh, dlnkh, npoints, var1, var2)
subroutine camb_setinitialpower (Params, P)
subroutine camb_settotcls (lmax, tot_scalar_Cls, in)
subroutine camb_setunlensedcls (lmax, unlensed_cls, in)
subroutine camb_setlenspotentialcls (lmax, cls, in)
subroutine camb_setunlensedscalcls (lmax, scalar_Cls, in)
subroutine camb_setlensedscalcls (lmax, lensed_Cls, in)
subroutine camb_settensorcls (lmax, tensor_Cls, in)
subroutine camb_setunlensedscalararray (lmax, ScalarArray, in, n)
subroutine camb_setbackgroundoutputs_z (redshifts, n)
integer function camb_getnumbackgroundoutputs ()
subroutine camb_getbackgroundoutputs (outputs, n)
subroutine set_cls_template (cls_template)
integer function camb_primordialpower (Params, k, powers, n, i)
subroutine getoutputevolutionfork (EV, times, outputs)
integer function camb_timeevolution (nq, q, ntimes, times, noutputs, outputs)
Function/Subroutine Documentation
camb_getbackgroundoutputs()
subroutine handles::camb_getbackgroundoutputs (real(dl), dimension(4,n), intent(out) outputs, integer, intent(in) n)
References modelparams::backgroundoutputs, and constants::c.
camb_getnumbackgroundoutputs()
integer function handles::camb_getnumbackgroundoutputs ()
References modelparams::backgroundoutputs.
camb_primordialpower()
integer function handles::camb_primordialpower (type(cambparams) Params, real(dl), dimension(n), intent(in) k, real(dl), dimension(n), intent(out) powers, integer, intent(in) n, integer, intent(in) i)
References constants::c.
camb_setbackgroundoutputs_z()
subroutine handles::camb_setbackgroundoutputs_z (real(dl), dimension(n), intent(in) redshifts, integer, intent(in) n)
References modelparams::backgroundoutputs.
camb_setinitialpower()
subroutine handles::camb_setinitialpower (type(cambparams) Params, type(initialpowerparams) P)
camb_setlensedscalcls()
subroutine handles::camb_setlensedscalcls (integer, intent(in) lmax, real(dl), dimension(4, 0:lmax), intent(out) lensed_Cls, integer, intent(in) in)
References modelparams::cp, and modelparams::lmin.
camb_setlenspotentialcls()
subroutine handles::camb_setlenspotentialcls (integer, intent(in) lmax, real(dl), dimension(3, 0:lmax), intent(out) cls, integer, intent(in) in)
References modelparams::cp, and modelparams::lmin.
camb_settensorcls()
subroutine handles::camb_settensorcls (integer, intent(in) lmax, real(dl), dimension(4, 0:lmax), intent(out) tensor_Cls, integer, intent(in) in)
References modelparams::cp, and modelparams::lmin.
camb_settotcls()
subroutine handles::camb_settotcls (integer, intent(in) lmax, real(dl), dimension(4, 0:lmax), intent(out) tot_scalar_Cls, integer, intent(in) in)
References modelparams::cp, and modelparams::lmin.
camb_setunlensedcls()
subroutine handles::camb_setunlensedcls (integer, intent(in) lmax, real(dl), dimension(4,0:lmax), intent(out) unlensed_cls, integer, intent(in) in)
References modelparams::cp, and modelparams::lmin.
camb_setunlensedscalararray()
subroutine handles::camb_setunlensedscalararray (integer, intent(in) lmax, real(dl), dimension(n, n, 0:lmax), intent(out) ScalarArray, integer, intent(in) in, integer, intent(in) n)
References modelparams::cp, and modelparams::lmin.
camb_setunlensedscalcls()
subroutine handles::camb_setunlensedscalcls (integer, intent(in) lmax, real(dl), dimension(4, 0:lmax), intent(out) scalar_Cls, integer, intent(in) in)
References modelparams::cp, and modelparams::lmin.
camb_timeevolution()
integer function handles::camb_timeevolution (integer, intent(in) nq, real(dl), dimension(nq), intent(in) q, integer, intent(in) ntimes, real(dl), dimension(ntimes), intent(in) times, integer, intent(in) noutputs, real(dl), dimension(transfer_max+8, ntimes, nq), intent(out) outputs)
References getoutputevolutionfork().
cambdata_calcbackgroundtheory()
integer function handles::cambdata_calcbackgroundtheory (type (cambdata) data, type(cambparams) P)
References modelparams::cambparams_set(), and cambmain::initvars().
cambdata_cltransferdata()
subroutine handles::cambdata_cltransferdata (type(cambdata), target data, type(c_cltransferdata) cData, integer, intent(in) i)
References convert_cltransferdata().
cambdata_free()
subroutine handles::cambdata_free (type(c_ptr) cptr)
References camb::camb_freecambdata().
cambdata_getlinearmatterpower()
subroutine handles::cambdata_getlinearmatterpower (type(cambdata) data, real(dl), dimension(data%mtrans%num_q_trans,data%params%transfer%pk_num_redshifts) PK, integer, intent(in) var1, integer, intent(in) var2, logical hubble_units)
References transfer::transfer_getunsplinedpower().
cambdata_getmatterpower()
subroutine handles::cambdata_getmatterpower (type(cambdata) data, real(dl), dimension(npoints,data%params%transfer%pk_num_redshifts), intent(out) outpower, real(dl), intent(in) minkh, real(dl), intent(in) dlnkh, integer, intent(in) npoints, integer, intent(in) var1, integer, intent(in) var2)
References transfer::transfer_getmatterpowerd().
cambdata_getnonlinearmatterpower()
subroutine handles::cambdata_getnonlinearmatterpower (type(cambdata) data, real(dl), dimension(data%mtrans%num_q_trans,data%params%transfer%pk_num_redshifts) PK, integer, intent(in) var1, integer, intent(in) var2, logical hubble_units)
References transfer::transfer_getunsplinednonlinearpower().
cambdata_getparams()
subroutine handles::cambdata_getparams (type (cambdata), target data, type(c_ptr), intent(out) handle)
cambdata_gettransfers()
integer function handles::cambdata_gettransfers (type (cambdata) data, type(cambparams) Params, logical(kind=c_bool) onlytransfer)
References camb::camb_gettransfers(), modelparams::nonlinear_both, modelparams::nonlinear_lens, transfer::transfer_setfornonlinearlensing(), and transfer::transfer_sortandindexredshifts().
cambdata_mattertransferdata()
subroutine handles::cambdata_mattertransferdata (type(cambdata), target data, type(c_mattertransferdata) cData)
cambdata_new()
subroutine handles::cambdata_new (type(c_ptr), intent(out) handle)
References camb::camb_initcambdata(), and camb::camb_setdefparams().
cambdata_setparams()
subroutine handles::cambdata_setparams (type (cambdata), target data, type(cambparams) Params)
cambdata_setparamsforbackground()
subroutine handles::cambdata_setparamsforbackground (type (cambdata) data, type(cambparams) P)
References modelparams::cambparams_set().
convert_cltransferdata()
subroutine handles::convert_cltransferdata (type(cltransferdata), target data, type(c_cltransferdata) cData)
Referenced by cambdata_cltransferdata().
getoutputevolutionfork()
subroutine handles::getoutputevolutionfork (type(evolutionvars) EV, real(dl), dimension(:), intent(in) times, real(dl), dimension(:,:,:), intent(out) outputs)
References modelparams::accuracyboost, cambmain::gettaustart(), modelparams::grhob, modelparams::grhoc, and modelparams::tol.
Referenced by camb_timeevolution().
set_cls_template()
subroutine handles::set_cls_template (character(len=*), intent(in) cls_template)
References modelparams::highl_unlensed_cl_template.