cosmomc_bde_v3p1: getdist.plots Namespace Reference
getdist.plots Namespace Reference
Classes
class GetDistPlotError
class GetDistPlotSettings
class GetDistPlotter
class MCSampleAnalysis
class RootInfo
class SampleAnalysisGetDist
Functions
def makeList (roots)
def getPlotter (kwargs)
def getSinglePlotter (ratio=3/4., width_inch=6, kwargs)
def getSubplotPlotter (subplot_size=2, width_inch=None, kwargs)
Variables
warn
defaultSettings = GetDistPlotSettings()
Function Documentation
getPlotter()
def getdist.plots.getPlotter (kwargs)
Creates a new plotter and returns it
:param kwargs: arguments for :class:`~getdist.plots.GetDistPlotter`
:return: The :class:`GetDistPlotter` instance
Referenced by getdist.plots.getSinglePlotter(), and getdist.plots.getSubplotPlotter().
getSinglePlotter()
def getdist.plots.getSinglePlotter (ratio = 3 / 4., width_inch = 6, kwargs)
Get a :class:`~.plots.GetDistPlotter` for making a single plot of fixed width.
For a half-column plot for a paper use width_inch=3.464.
Use this or :func:`~getSubplotPlotter` to make a :class:`~.plots.GetDistPlotter` instance for making plots.
If you want customized sizes or styles for all plots, you can make a new module
defining these functions, and then use it exactly as a replacement for getdist.plots.
:param ratio: The ratio between height and width.
:param width_inch:  The width of the plot in inches
:param kwargs: arguments for :class:`GetDistPlotter`
:return: The :class:`~.plots.GetDistPlotter` instance
References getdist.plots.getPlotter().
getSubplotPlotter()
def getdist.plots.getSubplotPlotter (subplot_size = 2, width_inch = None, kwargs)
Get a :class:`~.plots.GetDistPlotter` for making an array of subplots.
If width_inch is None, just makes plot as big as needed for given subplot_size, otherwise fixes total width
and sets default font sizes etc. from matplotlib's default rcParams.
Use this or :func:`~getSinglePlotter` to make a :class:`~.plots.GetDistPlotter` instance for making plots.
If you want customized sizes or styles for all plots, you can make a new module
defining these functions, and then use it exactly as a replacement for getdist.plots.
:param subplot_size: The size of each subplot in inches
:param width_inch: Optional total width in inches
:param kwargs: arguments for :class:`GetDistPlotter`
:return: The :class:`GetDistPlotter` instance
References getdist.plots.getPlotter().
makeList()
def getdist.plots.makeList (roots)
Checks if the given parameter is a list, If not, Creates a list with the parameter as an item in it.
:param roots: The parameter to check
:return: A list containing the parameter.
Referenced by getdist.plots.GetDistPlotter.plot_1d(), getdist.plots.GetDistPlotter.plot_2d(), getdist.plots.GetDistPlotter.plot_3d(), getdist.plots.GetDistPlotter.plots_1d(), getdist.plots.GetDistPlotter.plots_2d(), getdist.plots.GetDistPlotter.plots_3d(), getdist.plots.GetDistPlotter.plots_3d_z(), getdist.plots.GetDistPlotter.rectangle_plot(), and getdist.plots.GetDistPlotter.triangle_plot().
Variable Documentation
defaultSettings
getdist.plots.defaultSettings = GetDistPlotSettings()
warn
getdist.plots.warn