cosmomc_bde_v3p1: szcounts Module Reference
szcounts Module Reference
Data Types
type szlikelihood
Functions/Subroutines
subroutine, public szlikelihood_add (LikeList, Ini)
subroutine sz_init
real(mcp) function, public szcc_cash (this, CMB, Theory, DataParams)
Variables
logical do_sz_init = .true.
logical use_sz = .false.
integer sz_num
integer ny
integer nz
integer sz_switch
integer nmiss_switch
integer errorz_switch
integer print_counts
integer nmiss
integer nred2
integer ncat
integer nerf
integer nrows_qa
integer nrows_erf
integer ylim_switch
integer for
integer constant
integer ylim
integer variable
real(dl), dimension(:,:), allocatable dncat
real(dl), dimension(:), allocatable dnzcat
real(dl), dimension(:), allocatable dnycat
real(dl), dimension(:,:), allocatable dn
real(dl), dimension(:), allocatable dnz
real(dl), dimension(:), allocatable dny
real(dl), dimension(:), allocatable z
real(dl), dimension(:), allocatable logy
real(dl), dimension(:,:), allocatable ylims
real(dl), dimension(:), allocatable thetas
real(dl), dimension(:), allocatable skyfracs
real(dl), dimension(:,:), allocatable erf_list
real(dl), dimension(:,:), allocatable qa_ytot
real(dl), dimension(:,:), allocatable szcat
real(dl) clash
real(dl) wtg
real(dl) lens
real(dl) cccp
real(dl) pns
real(dl) oh2
real(dl) palpha
real(dl) pystar
real(dl) psigma
real(dl) pbeta
real sz_kmax = 4.0
character(len=256) sz_filename = ''
character(len= *), parameter sz_version = 'Nov_2014'
real(dl), save zmaxs
real(dl), save z0
real(dl), save dz
integer, save nred
integer, save nscat
Function/Subroutine Documentation
sz_init()
subroutine szcounts::sz_init () private
0=constant ylim, <0=variable ylim
References dn, dncat, dny, dnycat, dnz, dnzcat, do_sz_init, dz, errorz_switch, logy, massfunction::massfnpar, ncat, nmiss, nmiss_switch, nred2, nscat, ny, nz, massobservable::q, skyfracs, sz_switch, szcat, thetas, ylim_switch, ylims, z, z0, and zmaxs.
Referenced by szlikelihood_add().
szcc_cash()
real(mcp) function, public szcounts::szcc_cash (class(szlikelihood) this, class (cmbparams) CMB, class(tcosmotheorypredictions), target Theory, real(mcp), dimension(:) DataParams)
References cccp, cosmology::cosmopar, numbercounts::deltan_yz(), dn, dncat, dny, dnz, dnzcat, erf_list, lens, logy, settings::logzero, ncat, nred2, cosmologytypes::ns_index, ny, nz, oh2, palpha, pbeta, pns, print_counts, psigma, pystar, qa_ytot, skyfracs, sz_switch, thetas, wtg, ylims, and z.
Referenced by szcounts::szlikelihood::loglike().
szlikelihood_add()
subroutine, public szcounts::szlikelihood_add (class(tlikelihoodlist) LikeList, class(tsettingini) Ini)
References cccp, clash, settings::datadir, lens, massfunction::massfnpar, oh2, palpha, pbeta, pns, print_counts, psigma, pystar, sz_init(), sz_kmax, sz_switch, sz_version, and wtg.
Referenced by szcounts::szlikelihood::loglike(), and datalikelihoodlist::setdatalikelihoods().
Variable Documentation
cccp
real(dl) szcounts::cccp private
Referenced by szcc_cash(), and szlikelihood_add().
clash
real(dl) szcounts::clash private
Referenced by szlikelihood_add().
constant
integer szcounts::constant private
dn
real(dl), dimension(:,:), allocatable szcounts::dn private
Referenced by sz_init(), and szcc_cash().
dncat
real(dl), dimension(:,:), allocatable szcounts::dncat private
Referenced by sz_init(), and szcc_cash().
dny
real(dl), dimension(:), allocatable szcounts::dny private
Referenced by sz_init(), and szcc_cash().
dnycat
real(dl), dimension(:), allocatable szcounts::dnycat private
Referenced by sz_init().
dnz
real(dl), dimension(:), allocatable szcounts::dnz private
Referenced by sz_init(), and szcc_cash().
dnzcat
real(dl), dimension(:), allocatable szcounts::dnzcat private
Referenced by sz_init(), and szcc_cash().
do_sz_init
logical szcounts::do_sz_init = .true. private
Referenced by sz_init().
dz
real(dl), save szcounts::dz private
Referenced by sz_init().
erf_list
real(dl), dimension(:,:), allocatable szcounts::erf_list private
Referenced by szcc_cash().
errorz_switch
integer szcounts::errorz_switch private
Referenced by sz_init().
for
integer szcounts::for private
lens
real(dl) szcounts::lens private
Referenced by szcc_cash(), and szlikelihood_add().
logy
real(dl), dimension(:), allocatable szcounts::logy private
Referenced by sz_init(), and szcc_cash().
ncat
integer szcounts::ncat private
Referenced by sz_init(), and szcc_cash().
nerf
integer szcounts::nerf private
nmiss
integer szcounts::nmiss private
Referenced by sz_init().
nmiss_switch
integer szcounts::nmiss_switch private
Referenced by sz_init().
nred
integer, save szcounts::nred private
nred2
integer szcounts::nred2 private
Referenced by sz_init(), and szcc_cash().
nrows_erf
integer szcounts::nrows_erf private
nrows_qa
integer szcounts::nrows_qa private
nscat
integer, save szcounts::nscat private
Referenced by sz_init().
ny
integer szcounts::ny private
Referenced by sz_init(), and szcc_cash().
nz
integer szcounts::nz private
Referenced by sz_init(), and szcc_cash().
oh2
real(dl) szcounts::oh2 private
Referenced by szcc_cash(), and szlikelihood_add().
palpha
real(dl) szcounts::palpha private
Referenced by szcc_cash(), and szlikelihood_add().
pbeta
real(dl) szcounts::pbeta private
Referenced by szcc_cash(), and szlikelihood_add().
pns
real(dl) szcounts::pns private
Referenced by szcc_cash(), and szlikelihood_add().
print_counts
integer szcounts::print_counts private
Referenced by szcc_cash(), and szlikelihood_add().
psigma
real(dl) szcounts::psigma private
Referenced by szcc_cash(), and szlikelihood_add().
pystar
real(dl) szcounts::pystar private
Referenced by szcc_cash(), and szlikelihood_add().
qa_ytot
real(dl), dimension(:,:), allocatable szcounts::qa_ytot private
Referenced by szcc_cash().
skyfracs
real(dl), dimension(:), allocatable szcounts::skyfracs private
Referenced by sz_init(), and szcc_cash().
sz_filename
character(len=256) szcounts::sz_filename = '' private
sz_kmax
real szcounts::sz_kmax = 4.0 private
Referenced by szlikelihood_add().
sz_num
integer szcounts::sz_num private
sz_switch
integer szcounts::sz_switch private
Referenced by sz_init(), szcc_cash(), and szlikelihood_add().
sz_version
character(len=*), parameter szcounts::sz_version = 'Nov_2014' private
Referenced by szlikelihood_add().
szcat
real(dl), dimension(:,:), allocatable szcounts::szcat private
Referenced by sz_init().
thetas
real(dl), dimension(:), allocatable szcounts::thetas private
Referenced by sz_init(), and szcc_cash().
use_sz
logical szcounts::use_sz = .false. private
variable
integer szcounts::variable private
wtg
real(dl) szcounts::wtg private
Referenced by szcc_cash(), and szlikelihood_add().
ylim
integer szcounts::ylim private
ylim_switch
integer szcounts::ylim_switch private
Referenced by sz_init().
ylims
real(dl), dimension(:,:), allocatable szcounts::ylims private
Referenced by sz_init(), and szcc_cash().
z
real(dl), dimension(:), allocatable szcounts::z private
Referenced by sz_init(), and szcc_cash().
z0
real(dl), save szcounts::z0 private
Referenced by sz_init().
zmaxs
real(dl), save szcounts::zmaxs private
Referenced by sz_init().