cosmomc_bde_v3p1: bbn_yhe Namespace Reference
bbn_yhe Namespace Reference
Functions
def yhe_to_ypBBN (Yp)
def addYpFit (samples)
def addYpFitRoots (roots)
def ypBBN (omegab, dneff, taun=880.3)
def dh_fit (omegab, dneff, taun=880.3)
Variables
float sigma_yp_theo = 0.0003
int num_ob = 50
float ob_min = 0.018
float ob_max = 0.026
float yp_min = 0.15
float yp_max = 0.35
float aver_mean = 0.2465
float aver_sigma = 0.0097
float sere_minus = 0.294
float sere_plus = yp_max
sere_b = np.zeros(2, dtype='float')
sere_y1 = np.zeros(2, dtype='float')
sere_y2 = np.zeros(2, dtype='float')
list labels = [s.defplanck, s.defplanck + "+BAO", s.planckall]
list datatag = [s.defdata, s.defdata + '_BAO', s.defdata_all]
g = s.getSinglePlotter()
ombh2 -Yhe #############
colors = g.settings.solid_colors[3:0:-1]
bbn_b = np.arange(ob_min, ob_max + 0.1, (ob_max - ob_min) / num_ob)
def bbn_y = ypBBN(bbn_b, 0)
def bbn_y1 = bbn_y - sigma_yp_theo
def bbn_y2 = bbn_y + sigma_yp_theo
xlim
alpha
color
linestyle
fontsize
list roots = [g.getRoot('yhe', d) for d in datatag]
legend_fontsize
filled
True
lims
legend_loc
colored_text
xy
xycoords
xytext
textcoords
arrowprops
float N_min = 0.01
int N_max = 5
Neff = np.arange(N_min, N_max + 0.1, 0.1)
list Nrange = [N_min, N_max]
False
tag
Function Documentation
addYpFit()
def bbn_yhe.addYpFit (samples)
References yhe_to_ypBBN().
Referenced by addYpFitRoots().
addYpFitRoots()
def bbn_yhe.addYpFitRoots (roots)
References addYpFit().
dh_fit()
def bbn_yhe.dh_fit (omegab, dneff, taun = 880.3)
yhe_to_ypBBN()
def bbn_yhe.yhe_to_ypBBN (Yp)
Referenced by addYpFit().
ypBBN()
def bbn_yhe.ypBBN (omegab, dneff, taun = 880.3)
Variable Documentation
alpha
bbn_yhe.alpha
arrowprops
bbn_yhe.arrowprops
aver_mean
bbn_yhe.aver_mean = 0.2465
aver_sigma
bbn_yhe.aver_sigma = 0.0097
bbn_b
bbn_yhe.bbn_b = np.arange(ob_min, ob_max + 0.1, (ob_max - ob_min) / num_ob)
bbn_y
def bbn_yhe.bbn_y = ypBBN(bbn_b, 0)
bbn_y1
def bbn_yhe.bbn_y1 = bbn_y - sigma_yp_theo
bbn_y2
def bbn_yhe.bbn_y2 = bbn_y + sigma_yp_theo
color
bbn_yhe.color
colored_text
bbn_yhe.colored_text
colors
bbn_yhe.colors = g.settings.solid_colors[3:0:-1]
datatag
list bbn_yhe.datatag = [s.defdata, s.defdata + '_BAO', s.defdata_all]
False
bbn_yhe.False
filled
bbn_yhe.filled
fontsize
bbn_yhe.fontsize
g
bbn_yhe.g = s.getSinglePlotter()
ombh2 -Yhe #############
Neff -Yhe #############.
labels
bbn_yhe.labels = [s.defplanck, s.defplanck + "+BAO", s.planckall]
legend_fontsize
bbn_yhe.legend_fontsize
legend_loc
bbn_yhe.legend_loc
lims
bbn_yhe.lims
linestyle
bbn_yhe.linestyle
N_max
int bbn_yhe.N_max = 5
N_min
float bbn_yhe.N_min = 0.01
Neff
bbn_yhe.Neff = np.arange(N_min, N_max + 0.1, 0.1)
Nrange
bbn_yhe.Nrange = [N_min, N_max]
num_ob
int bbn_yhe.num_ob = 50
ob_max
float bbn_yhe.ob_max = 0.026
ob_min
float bbn_yhe.ob_min = 0.018
roots
list bbn_yhe.roots = [g.getRoot('yhe', d) for d in datatag]
sere_b
bbn_yhe.sere_b = np.zeros(2, dtype='float')
sere_minus
float bbn_yhe.sere_minus = 0.294
sere_plus
float bbn_yhe.sere_plus = yp_max
sere_y1
bbn_yhe.sere_y1 = np.zeros(2, dtype='float')
sere_y2
bbn_yhe.sere_y2 = np.zeros(2, dtype='float')
sigma_yp_theo
float bbn_yhe.sigma_yp_theo = 0.0003
tag
bbn_yhe.tag
textcoords
bbn_yhe.textcoords
True
bbn_yhe.True
xlim
bbn_yhe.xlim
xy
bbn_yhe.xy
xycoords
bbn_yhe.xycoords
xytext
bbn_yhe.xytext
yp_max
bbn_yhe.yp_max = 0.35
yp_min
float bbn_yhe.yp_min = 0.15