cosmomc_bde_v3p1: estcovmatmodule Module Reference
estcovmatmodule Module Reference
Functions/Subroutines
real(mcp) function, dimension(num_params_used, num_params_used) estcovmat (Params, bestdll_in, sucess)
real(mcp) function placegrid (CenterParams, parsteps, bestdll)
subroutine getstepsfordchisq1 (CenterParams, LCenter, maxstepsizetries, parsteps, bestdll)
subroutine gethess (CenterParams, CenterLike, parsteps, Hess)
Variables
integer, dimension(:,:), allocatable step_positions
logical, dimension(:), allocatable is_weakly_constrained
Function/Subroutine Documentation
estcovmat()
real(mcp) function, dimension(num_params_used,num_params_used) estcovmatmodule::estcovmat (type(paramset) Params, real(mcp), intent(in) bestdll_in, integer, intent(out) sucess)
References baseparameters::baseparams, settings::feedback, gethess(), is_weakly_constrained, matrixutils::matrix_diagonalize(), matrixutils::matrix_inverse(), settings::num_params_used, settings::params_used, placegrid(), and step_positions.
gethess()
subroutine estcovmatmodule::gethess (type(paramset) CenterParams, real(mcp) CenterLike, real(mcp), dimension(num_params_used) parsteps, real(mcp), dimension(num_params_used,num_params_used) Hess)
References baseparameters::baseparams, settings::doabort(), settings::feedback, calclike::getloglike(), is_weakly_constrained, settings::logzero, settings::params_used, and step_positions.
Referenced by estcovmat().
getstepsfordchisq1()
subroutine estcovmatmodule::getstepsfordchisq1 (type(paramset) CenterParams, real(mcp) LCenter, integer, intent(in) maxstepsizetries, real(mcp), dimension(num_params_used) parsteps, real(mcp) bestdll)
References baseparameters::baseparams, settings::feedback, calclike::getloglike(), is_weakly_constrained, settings::params_used, and step_positions.
Referenced by placegrid().
placegrid()
real(mcp) function estcovmatmodule::placegrid (type(paramset) CenterParams, real(mcp), dimension(num_params_used) parsteps, real(mcp) bestdll)
References settings::doabort(), settings::feedback, calclike::getloglike(), getstepsfordchisq1(), and settings::logzero.
Referenced by estcovmat().
Variable Documentation
is_weakly_constrained
logical, dimension(:), allocatable estcovmatmodule::is_weakly_constrained
Referenced by estcovmat(), gethess(), and getstepsfordchisq1().
step_positions
integer, dimension(:,:), allocatable estcovmatmodule::step_positions
Referenced by estcovmat(), gethess(), and getstepsfordchisq1().