cosmomc_bde_v3p1: baseparameters Module Reference
baseparameters Module Reference
Data Types
type paramgaussprior
type tbaseparameters
type tlinearcombination
Functions/Subroutines
subroutine tbaseparameters_initializeusedparams (this, Ini)
subroutine tbaseparameters_paramerror (this, str, param)
subroutine tbaseparameters_setstartpositions (this, Params)
subroutine tbaseparameters_readparams (this, Ini)
subroutine tbaseparameters_readpriors (this, Ini)
subroutine tbaseparameters_setcovmat (this, prop_mat)
subroutine tbaseparameters_readsetcovmatrix (this, prop_mat, matrix, NewParams)
subroutine tbaseparameters_outputparamnames (this, fname, indices, add_derived)
subroutine tbaseparameters_outputparamranges (this, fname)
subroutine orderindices (arr, n)
subroutine tbaseparameters_setfastslowparams (this, Ini, use_fast_slow)
character(len=:) function, allocatable tbaseparameters_usedparamnameornumber (this, i)
Variables
integer, parameter tp_unused = 0
integer, parameter tp_slow =1
integer, parameter tp_semislow =2
integer, parameter tp_semifast =3
integer, parameter tp_fast =4
integer, parameter, public slow_tp_max = tp_semislow
type(tbaseparameters), save, public baseparams
Function/Subroutine Documentation
orderindices()
subroutine baseparameters::orderindices (integer, dimension(:) arr, integer, intent(in) n) private
References arrayutils::indexof().
Referenced by tbaseparameters_setfastslowparams().
tbaseparameters_initializeusedparams()
subroutine baseparameters::tbaseparameters_initializeusedparams (class(tbaseparameters) this, class(tsettingini) Ini) private
References settings::num_data_params, settings::num_params, settings::num_theory_params, and settings::output_lines.
tbaseparameters_outputparamnames()
subroutine baseparameters::tbaseparameters_outputparamnames (class(tbaseparameters) this, character(len=*), intent(in) fname, integer, dimension(:), intent(in), optional indices, logical, intent(in), optional add_derived) private
tbaseparameters_outputparamranges()
subroutine baseparameters::tbaseparameters_outputparamranges (class(tbaseparameters) this, character(len=*), intent(in) fname) private
tbaseparameters_paramerror()
subroutine baseparameters::tbaseparameters_paramerror (class(tbaseparameters) this, character(len=*), intent(in) str, integer, intent(in) param) private
References settings::doabort().
tbaseparameters_readparams()
subroutine baseparameters::tbaseparameters_readparams (class(tbaseparameters) this, class(tsettingini) Ini) private
References settings::num_params, settings::num_params_used, and settings::params_used.
tbaseparameters_readpriors()
subroutine baseparameters::tbaseparameters_readpriors (class(tbaseparameters) this, class(tsettingini) Ini) private
tbaseparameters_readsetcovmatrix()
subroutine baseparameters::tbaseparameters_readsetcovmatrix (class(tbaseparameters) this, character(len=*), intent(in) prop_mat, real(mcp), dimension(num_params_used, num_params_used) matrix, logical, optional NewParams) private
tbaseparameters_setcovmat()
subroutine baseparameters::tbaseparameters_setcovmat (class(tbaseparameters) this, character(len=*), intent(in) prop_mat) private
tbaseparameters_setfastslowparams()
subroutine baseparameters::tbaseparameters_setfastslowparams (class(tbaseparameters) this, class(tsettingini) Ini, logical, intent(in) use_fast_slow)
References baseparams, orderindices(), slow_tp_max, tp_fast, tp_semifast, tp_semislow, tp_slow, and tp_unused.
tbaseparameters_setstartpositions()
subroutine baseparameters::tbaseparameters_setstartpositions (class(tbaseparameters) this, class(tcalculationatparampoint) Params) private
References randutils::gaussian1(), settings::num_params_used, and settings::params_used.
tbaseparameters_usedparamnameornumber()
character(len=:) function, allocatable baseparameters::tbaseparameters_usedparamnameornumber (class(tbaseparameters) this, integer, intent(in) i) private
Variable Documentation
baseparams
type(tbaseparameters), save, public baseparameters::baseparams
Referenced by samplecollector::checklimitsconverge(), estcovmatmodule::estcovmat(), estcovmatmodule::gethess(), calclike::getloglikebounds(), calclike::getlogpriors(), estcovmatmodule::getstepsfordchisq1(), parampointset::paramset_readmodel(), parampointset::paramset_writemodel(), tbaseparameters_setfastslowparams(), samplecollector::tmpichaincollector_addnewpoint(), samplecollector::tmpichaincollector_readstate(), samplecollector::tmpichaincollector_updatecovandcheckconverge(), generalsetup::tsetup_doneinitialize(), and generalsetup::tsetup_dosampling().
slow_tp_max
integer, parameter, public baseparameters::slow_tp_max = tp_semislow
Referenced by tbaseparameters_setfastslowparams().
tp_fast
integer, parameter baseparameters::tp_fast =4 private
Referenced by tbaseparameters_setfastslowparams().
tp_semifast
integer, parameter baseparameters::tp_semifast =3 private
Referenced by tbaseparameters_setfastslowparams().
tp_semislow
integer, parameter baseparameters::tp_semislow =2 private
Referenced by tbaseparameters_setfastslowparams().
tp_slow
integer, parameter baseparameters::tp_slow =1 private
Referenced by tbaseparameters_setfastslowparams().
tp_unused
integer, parameter baseparameters::tp_unused = 0 private
Referenced by tbaseparameters_setfastslowparams().