cosmomc_bde_v3p1: inifile Module Reference
inifile Module Reference
Data Types
type tinifile
type tnamevalue
type tnamevalue_pointer
type tnamevaluelist
Functions/Subroutines
subroutine tnamevaluelist_init (L, ignoreDuplicates)
subroutine tnamevaluelist_clear (L)
subroutine tnamevaluelist_valueof (L, AName, AValue)
integer function tnamevaluelist_indexof (L, AName)
logical function tnamevaluelist_haskey (L, AName)
subroutine tnamevaluelist_add (L, AName, AValue, only_if_undefined)
subroutine tnamevaluelist_setcapacity (L, C)
subroutine tnamevaluelist_delete (L, i)
subroutine ini_namevalue_add (Ini, AInLine, only_if_undefined)
subroutine ini_open (filename, unit_id, error, slash_comments)
character(len=ini_max_string_len) function ini_extractfilepath (aname)
recursive subroutine ini_open_file (Ini, filename, unit_id, error, slash_comments, append, only_if_undefined)
subroutine ini_open_fromlines (Ini, Lines, NumLines, slash_comments)
subroutine ini_close
subroutine ini_close_file (Ini)
character(len=ini_max_string_len) function ini_read_string (Key, NotFoundFail)
character(len=ini_max_string_len) function ini_read_string_default (Key, Default, AllowBlank)
character(len=ini_max_string_len) function ini_read_string_file (Ini, Key, NotFoundFail)
character(len=ini_max_string_len) function ini_read_string_default_file (Ini, Key, Default, AllowBlank)
logical function ini_haskey (Key)
logical function ini_haskey_file (Ini, Key)
character(len=ini_max_string_len) function ini_key_to_arraykey (Key, index)
character(len=ini_max_string_len) function ini_read_string_array (Key, index, NotFoundFail)
character(len=ini_max_string_len) function ini_read_string_array_file (Ini, Key, index, NotFoundFail)
integer function ini_read_int_array (Key, index, Default)
integer function ini_read_int_array_file (Ini, Key, index, Default)
integer function ini_read_int (Key, Default)
integer function ini_read_int_file (Ini, Key, Default)
double precision function ini_read_double (Key, Default)
double precision function ini_read_double_file (Ini, Key, Default)
double precision function ini_read_double_array (Key, index, Default)
double precision function ini_read_double_array_file (Ini, Key, index, Default)
real function ini_read_real (Key, Default)
real function ini_read_real_file (Ini, Key, Default)
real function ini_read_real_array (Key, index, Default)
real function ini_read_real_array_file (Ini, Key, index, Default)
logical function ini_read_logical (Key, Default)
logical function ini_read_logical_file (Ini, Key, Default)
subroutine ini_savereadvalues (afile, unit_id)
subroutine ini_savereadvalues_file (Ini, afile, unit_id)
Variables
integer, parameter ini_max_name_len = 128
integer, parameter ini_max_string_len = 1024
logical ini_fail_on_not_found = .false.
logical ini_echo_read = .false.
logical ini_allowduplicatekeys = .false.
type(tinifile) defini
Function/Subroutine Documentation
ini_close()
subroutine inifile::ini_close ()
References defini, and ini_close_file().
ini_close_file()
subroutine inifile::ini_close_file (type(tinifile) Ini)
References tnamevaluelist_clear().
Referenced by ini_close().
ini_extractfilepath()
character(len=ini_max_string_len) function inifile::ini_extractfilepath (character(len=*), intent(in) aname)
Referenced by ini_open_file().
ini_haskey()
logical function inifile::ini_haskey (character (len=*), intent(in) Key)
References defini, and ini_haskey_file().
ini_haskey_file()
logical function inifile::ini_haskey_file (type(tinifile), intent(in) Ini, character (len=*), intent(in) Key)
References tnamevaluelist_haskey().
Referenced by ini_haskey(), and ini_read_string_default_file().
ini_key_to_arraykey()
character(len=ini_max_string_len) function inifile::ini_key_to_arraykey (character (len=*), intent(in) Key, integer, intent(in) index)
Referenced by ini_read_double_array_file(), ini_read_int_array_file(), ini_read_real_array_file(), and ini_read_string_array_file().
ini_namevalue_add()
subroutine inifile::ini_namevalue_add (type(tinifile) Ini, character (len=*), intent(in) AInLine, logical, intent(in), optional only_if_undefined)
References tnamevaluelist_add().
Referenced by ini_open_file(), and ini_open_fromlines().
ini_open()
subroutine inifile::ini_open (character (len=*), intent(in) filename, integer, intent(in) unit_id, logical, intent(out), optional error, logical, intent(in), optional slash_comments)
References defini, ini_open_file(), and tnamevaluelist_init().
ini_open_file()
recursive subroutine inifile::ini_open_file (type(tinifile) Ini, character (len=*), intent(in) filename, integer, intent(in) unit_id, logical, intent(out) error, logical, intent(in), optional slash_comments, logical, intent(in), optional append, logical, intent(in), optional only_if_undefined)
References ini_extractfilepath(), ini_namevalue_add(), tnamevaluelist_add(), tnamevaluelist_clear(), and tnamevaluelist_init().
Referenced by ini_open().
ini_open_fromlines()
subroutine inifile::ini_open_fromlines (type(tinifile) Ini, character (len=*), dimension(numlines), intent(in) Lines, integer, intent(in) NumLines, logical, intent(in) slash_comments)
References ini_namevalue_add(), and tnamevaluelist_init().
ini_read_double()
double precision function inifile::ini_read_double (character (len=*), intent(in) Key, double precision, intent(in), optional Default)
References defini, and ini_read_double_file().
ini_read_double_array()
double precision function inifile::ini_read_double_array (character (len=*), intent(in) Key, integer, intent(in) index, double precision, intent(in), optional Default)
References defini, and ini_read_double_array_file().
ini_read_double_array_file()
double precision function inifile::ini_read_double_array_file (type(tinifile) Ini, character (len=*), intent(in) Key, integer, intent(in) index, double precision, intent(in), optional Default)
References ini_key_to_arraykey(), and ini_read_double_file().
Referenced by ini_read_double_array(), and initialpower::initialpower_readparams().
ini_read_double_file()
double precision function inifile::ini_read_double_file (type(tinifile) Ini, character (len=*), intent(in) Key, double precision, intent(in), optional Default)
References ini_read_string_file(), and tnamevaluelist_add().
Referenced by lambdageneral::darkenergy_readparams(), ini_read_double(), ini_read_double_array_file(), initialpower::initialpower_readparams(), recombination::recombination_readparams(), and reionization::reionization_readparams().
ini_read_int()
integer function inifile::ini_read_int (character (len=*), intent(in) Key, integer, intent(in), optional Default)
References defini, and ini_read_int_file().
ini_read_int_array()
integer function inifile::ini_read_int_array (character (len=*), intent(in) Key, integer, intent(in) index, integer, intent(in), optional Default)
References defini, and ini_read_int_array_file().
ini_read_int_array_file()
integer function inifile::ini_read_int_array_file (type(tinifile) Ini, character (len=*), intent(in) Key, integer, intent(in) index, integer, intent(in), optional Default)
References ini_key_to_arraykey(), and ini_read_int_file().
Referenced by ini_read_int_array().
ini_read_int_file()
integer function inifile::ini_read_int_file (type(tinifile) Ini, character (len=*), intent(in) Key, integer, intent(in), optional Default)
References ini_read_string_file(), and tnamevaluelist_add().
Referenced by ini_read_int(), ini_read_int_array_file(), initialpower::initialpower_readparams(), nonlinear::nonlinear_readparams(), and recombination::recombination_readparams().
ini_read_logical()
logical function inifile::ini_read_logical (character (len=*), intent(in) Key, logical, intent(in), optional Default)
References defini, and ini_read_logical_file().
ini_read_logical_file()
logical function inifile::ini_read_logical_file (type(tinifile) Ini, character (len=*), intent(in) Key, logical, intent(in), optional Default)
References ini_read_string_file(), and tnamevaluelist_add().
Referenced by ini_read_logical(), recombination::recombination_readparams(), and reionization::reionization_readparams().
ini_read_real()
real function inifile::ini_read_real (character (len=*), intent(in) Key, real, intent(in), optional Default)
References defini, and ini_read_real_file().
ini_read_real_array()
real function inifile::ini_read_real_array (character (len=*), intent(in) Key, integer, intent(in) index, real, intent(in), optional Default)
References defini, and ini_read_real_array_file().
ini_read_real_array_file()
real function inifile::ini_read_real_array_file (type(tinifile) Ini, character (len=*), intent(in) Key, integer, intent(in) index, real, intent(in), optional Default)
References ini_key_to_arraykey(), and ini_read_real_file().
Referenced by ini_read_real_array().
ini_read_real_file()
real function inifile::ini_read_real_file (type(tinifile) Ini, character (len=*), intent(in) Key, real, intent(in), optional Default)
References ini_read_string_file(), and tnamevaluelist_add().
Referenced by ini_read_real(), and ini_read_real_array_file().
ini_read_string()
character(len=ini_max_string_len) function inifile::ini_read_string (character (len=*), intent(in) Key, logical, intent(in), optional NotFoundFail)
References defini, and ini_read_string_file().
ini_read_string_array()
character(len=ini_max_string_len) function inifile::ini_read_string_array (character (len=*), intent(in) Key, integer, intent(in) index, logical, intent(in), optional NotFoundFail)
References defini, and ini_read_string_array_file().
ini_read_string_array_file()
character(len=ini_max_string_len) function inifile::ini_read_string_array_file (type(tinifile) Ini, character (len=*), intent(in) Key, integer, intent(in) index, logical, intent(in), optional NotFoundFail)
References ini_key_to_arraykey(), and ini_read_string_file().
Referenced by ini_read_string_array().
ini_read_string_default()
character(len=ini_max_string_len) function inifile::ini_read_string_default (character (len=*), intent(in) Key, character (len=*), intent(in) Default, logical, intent(in), optional AllowBlank)
References defini, and ini_read_string_default_file().
ini_read_string_default_file()
character(len=ini_max_string_len) function inifile::ini_read_string_default_file (type(tinifile) Ini, character (len=*), intent(in) Key, character (len=*), intent(in) Default, logical, intent(in), optional AllowBlank)
References ini_haskey_file(), and ini_read_string_file().
Referenced by ini_read_string_default().
ini_read_string_file()
character(len=ini_max_string_len) function inifile::ini_read_string_file (type(tinifile) Ini, character (len=*), intent(in) Key, logical, intent(in), optional NotFoundFail)
References ini_echo_read, ini_fail_on_not_found, tnamevaluelist_add(), and tnamevaluelist_valueof().
Referenced by ini_read_double_file(), ini_read_int_file(), ini_read_logical_file(), ini_read_real_file(), ini_read_string(), ini_read_string_array_file(), and ini_read_string_default_file().
ini_savereadvalues()
subroutine inifile::ini_savereadvalues (character(len=*) afile, integer, intent(in) unit_id)
References defini, and ini_savereadvalues_file().
ini_savereadvalues_file()
subroutine inifile::ini_savereadvalues_file (type(tinifile) Ini, character(len=*), intent(in) afile, integer, intent(in) unit_id)
Referenced by ini_savereadvalues().
tnamevaluelist_add()
subroutine inifile::tnamevaluelist_add (type (tnamevaluelist) L, character(len=*), intent(in) AName, character(len=*), intent(in) AValue, logical, intent(in), optional only_if_undefined)
References ini_allowduplicatekeys, tnamevaluelist_haskey(), and tnamevaluelist_setcapacity().
Referenced by ini_namevalue_add(), ini_open_file(), ini_read_double_file(), ini_read_int_file(), ini_read_logical_file(), ini_read_real_file(), and ini_read_string_file().
tnamevaluelist_clear()
subroutine inifile::tnamevaluelist_clear (type (tnamevaluelist) L)
References tnamevaluelist_init().
Referenced by ini_close_file(), and ini_open_file().
tnamevaluelist_delete()
subroutine inifile::tnamevaluelist_delete (type (tnamevaluelist) L, integer, intent(in) i)
tnamevaluelist_haskey()
logical function inifile::tnamevaluelist_haskey (type (tnamevaluelist), intent(in) L, character(len=*), intent(in) AName)
References tnamevaluelist_indexof().
Referenced by ini_haskey_file(), and tnamevaluelist_add().
tnamevaluelist_indexof()
integer function inifile::tnamevaluelist_indexof (type (tnamevaluelist), intent(in) L, character(len=*), intent(in) AName)
Referenced by tnamevaluelist_haskey().
tnamevaluelist_init()
subroutine inifile::tnamevaluelist_init (type (tnamevaluelist) L, logical, intent(in), optional ignoreDuplicates)
Referenced by ini_open(), ini_open_file(), ini_open_fromlines(), and tnamevaluelist_clear().
tnamevaluelist_setcapacity()
subroutine inifile::tnamevaluelist_setcapacity (type (tnamevaluelist) L, integer C)
Referenced by tnamevaluelist_add().
tnamevaluelist_valueof()
subroutine inifile::tnamevaluelist_valueof (type (tnamevaluelist), intent(in) L, character(len=*), intent(in) AName, character(len=*), intent(out) AValue)
Referenced by ini_read_string_file().
Variable Documentation
defini
type(tinifile) inifile::defini
Referenced by ini_close(), ini_haskey(), ini_open(), ini_read_double(), ini_read_double_array(), ini_read_int(), ini_read_int_array(), ini_read_logical(), ini_read_real(), ini_read_real_array(), ini_read_string(), ini_read_string_array(), ini_read_string_default(), and ini_savereadvalues().
ini_allowduplicatekeys
logical inifile::ini_allowduplicatekeys = .false.
Referenced by tnamevaluelist_add().
ini_echo_read
logical inifile::ini_echo_read = .false.
Referenced by ini_read_string_file().
ini_fail_on_not_found
logical inifile::ini_fail_on_not_found = .false.
Referenced by ini_read_string_file().
ini_max_name_len
integer, parameter inifile::ini_max_name_len = 128
ini_max_string_len
integer, parameter inifile::ini_max_string_len = 1024