cosmomc_bde_v3p1: getdist_tests.test_distributions Namespace Reference
getdist_tests.test_distributions Namespace Reference
Classes
class Test1DDistributions
class Test2DDistributions
Functions
def simFiles (prob, file_root, sample_lengths=[1000, text=True)
def compareSimPlot2D (g, samples, density, pars=['x', y)
def compareSimPlot (g, samples, density, par='x')
def plot1DSim (g, prob, nsamp=default_nsamp, settings={})
def plot2DSim (g, prob, nsamp=default_nsamp, settings={})
def compare1D (g, probs, nsamp=default_nsamp, settings={})
def compare2D (g, probs, nsamp=default_nsamp, settings={})
def get2DMises (prob, nsamp=default_nsamp, nsim=20, scales=np.arange(0.6, 1.5, 0.1), settings={})
def get1DMises (prob, nsamp=default_nsamp, nsim=50, scales=[0.6, settings={})
def plot_compare_method (ax, prob, colors=['k'], sims=100, nsamp=default_nsamp, scalings=[0.3, test_settings=[None], linestyles=['-'])
def plot_compare_probs_methods (ax, probs, colors=['b', r, k, m, c, kwargs)
def compare_method_nsims (g, probs, sizes=[1000, kwargs)
def compare_method (probs, nx=2, fname='', kwargs)
def join_subplots (ax_array)
def testProgram ()
Variables
int default_nsamp = 10000
Function Documentation
compare1D()
def getdist_tests.test_distributions.compare1D (g, probs, nsamp = default_nsamp, settings = {})
References getdist_tests.test_distributions.compareSimPlot(), and copyGridFiles.zip.
Referenced by getdist_tests.test_distributions.testProgram().
compare2D()
def getdist_tests.test_distributions.compare2D (g, probs, nsamp = default_nsamp, settings = {})
References getdist_tests.test_distributions.compareSimPlot2D(), and copyGridFiles.zip.
Referenced by getdist_tests.test_distributions.testProgram().
compare_method()
def getdist_tests.test_distributions.compare_method (probs, nx = 2, fname = '', kwargs)
References getdist_tests.test_distributions.plot_compare_method().
Referenced by getdist_tests.test_distributions.testProgram().
compare_method_nsims()
def getdist_tests.test_distributions.compare_method_nsims (g, probs, sizes = [1000, kwargs)
References getdist_tests.test_distributions.plot_compare_probs_methods().
compareSimPlot()
def getdist_tests.test_distributions.compareSimPlot (g, samples, density, par = 'x')
Referenced by getdist_tests.test_distributions.compare1D(), and getdist_tests.test_distributions.plot1DSim().
compareSimPlot2D()
def getdist_tests.test_distributions.compareSimPlot2D (g, samples, density, pars = ['x', y)
Referenced by getdist_tests.test_distributions.compare2D(), and getdist_tests.test_distributions.plot2DSim().
get1DMises()
def getdist_tests.test_distributions.get1DMises (prob, nsamp = default_nsamp, nsim = 50, scales = [0.6, settings = {})
Referenced by getdist_tests.test_distributions.plot_compare_method(), and getdist_tests.test_distributions.testProgram().
get2DMises()
def getdist_tests.test_distributions.get2DMises (prob, nsamp = default_nsamp, nsim = 20, scales = np.arange(0.6, 1.5, 0.1), settings = {})
Referenced by getdist_tests.test_distributions.plot_compare_method(), and getdist_tests.test_distributions.testProgram().
join_subplots()
def getdist_tests.test_distributions.join_subplots (ax_array)
Referenced by getdist_tests.test_distributions.testProgram().
plot1DSim()
def getdist_tests.test_distributions.plot1DSim (g, prob, nsamp = default_nsamp, settings = {})
References getdist_tests.test_distributions.compareSimPlot().
plot2DSim()
def getdist_tests.test_distributions.plot2DSim (g, prob, nsamp = default_nsamp, settings = {})
References getdist_tests.test_distributions.compareSimPlot2D().
plot_compare_method()
def getdist_tests.test_distributions.plot_compare_method (ax, prob, colors = ['k'], sims = 100, nsamp = default_nsamp, scalings = [0.3, test_settings = [None], linestyles = ['-'])
References getdist_tests.test_distributions.get1DMises(), getdist_tests.test_distributions.get2DMises(), and copyGridFiles.zip.
Referenced by getdist_tests.test_distributions.compare_method(), getdist_tests.test_distributions.Test2DDistributions.distributions(), and getdist_tests.test_distributions.plot_compare_probs_methods().
plot_compare_probs_methods()
def getdist_tests.test_distributions.plot_compare_probs_methods (ax, probs, colors = ['b', r, k, m, c, kwargs)
References getdist_tests.test_distributions.plot_compare_method(), and copyGridFiles.zip.
Referenced by getdist_tests.test_distributions.compare_method_nsims().
simFiles()
def getdist_tests.test_distributions.simFiles (prob, file_root, sample_lengths = [1000, text = True)
testProgram()
def getdist_tests.test_distributions.testProgram ()
References getdist_tests.test_distributions.compare1D(), getdist_tests.test_distributions.compare2D(), getdist_tests.test_distributions.compare_method(), getdist_tests.test_distributions.get1DMises(), getdist_tests.test_distributions.get2DMises(), getdist_tests.test_distributions.join_subplots(), and copyGridFiles.zip.
Variable Documentation
default_nsamp
int getdist_tests.test_distributions.default_nsamp = 10000