cosmomc_bde_v3p1: modelparams Module Reference
modelparams Module Reference
Data Types
type cambparams
type tbackgroundoutputs
type transferparams
Functions/Subroutines
subroutine cambparams_set (P, error, DoReion)
real(sp) function gettesttime ()
real(dl) function rofchi (Chi)
real(dl) function cosfunc (Chi)
real(dl) function tanfunc (Chi)
real(dl) function invsinfunc (x)
real(dl) function f_k (x)
real(dl) function deltatime (a1, a2, in_tol)
real(dl) function timeofz (z)
subroutine timeofzarr (nz, redshifts, outputs)
real(dl) function deltaphysicaltimegyr (a1, a2, in_tol)
real(dl) function angulardiameterdistance (z)
subroutine angulardiameterdistancearr (arr, z, n)
real(dl) function angulardiameterdistance2 (z1, z2)
real(dl) function luminositydistance (z)
real(dl) function comovingradialdistance (z)
real(dl) function hofz (z)
real(dl) function bao_d_v_from_da_h (z, DA, Hz)
real(dl) function bao_d_v (z)
real(dl) function dsound_da_exact (a)
real(dl) function dsound_da (a)
real(dl) function dtda (a)
subroutine nxyl (y)
real(dl) function cosmomctheta ()
Variables
character(len= *), parameter version = 'Nov16'
integer feedbacklevel = 0
logical output_file_headers = .true.
logical, parameter debugmsgs =.false.
logical, parameter debugevolution = .false.
real(dl) debugparam = 0._dl
logical do_bispectrum = .false.
logical, parameter hard_bispectrum = .false.
logical, parameter full_bessel_integration = .false.
integer, parameter nu_int = 0
integer, parameter nu_trunc =1
integer, parameter nu_approx = 2
integer, parameter nu_best = 3
integer, parameter max_nu = 5
integer, parameter max_transfer_redshifts = 150
integer, parameter fileio_unit = 13
integer, parameter outnone =1
integer max_bessels_l_index = 1000000
real(dl) max_bessels_etak = 1000000*2
real(dl), parameter outputdenominator =twopi
type(regions) timesteps
integer, parameter nonlinear_none =0
integer, parameter nonlinear_pk =1
integer, parameter nonlinear_lens =2
integer, parameter nonlinear_both =3
type(cambparams), save cp
real(dl) scale
logical call_again = .false.
real(dl) grhom
real(dl) grhog
real(dl) grhor
real(dl) grhob
real(dl) grhoc
real(dl) grhov
real(dl) grhornomass
real(dl) grhok
real(dl) taurst
real(dl) dtaurec
real(dl) taurend
real(dl) tau_maxvis
real(dl) adotrad
real(dl) grhodgc
real(dl) lambdac
real(dl) alphabde
real(dl) wdgc
real(dl) omegadgc
real(dl) ac
real(dl) k_phi
real(dl) norm_pot
real(dl) fixq = 0._dl
real(dl), dimension(max_nu) grhormass
real(dl), dimension(max_nu) nu_masses
real(dl) akthom
real(dl) fhe
real(dl) nnow
integer threadnum = 0
logical highaccuracydefault = .true.
real(dl) lsampleboost =1._dl
real(dl) accuracyboost =1._dl
real(sp) laccuracyboost =1.
integer limber_phiphi = 0
integer num_redshiftwindows = 0
integer num_extra_redshiftwindows = 0
integer, parameter lmin = 2
real(dl), parameter omegakflat = 5e-7_dl
real(dl), parameter tol =1.0d-4
real(dl), parameter spl_large =1.e40_dl
integer, parameter l0max =4000
integer, parameter lmax_arr = l0max
character(len=1024) highl_unlensed_cl_template = 'HighLExtrapTemplate_lenspotentialCls.dat'
logical use_spline_template = .true.
integer, parameter lmax_extrap_highl = 8000
real(dl), dimension(:,:), allocatable highl_cl_template
integer, parameter derived_age =1
integer, parameter derived_zstar =2
integer, parameter derived_rstar =3
integer, parameter derived_thetastar =4
integer, parameter derived_dastar = 5
integer, parameter derived_zdrag =6
integer, parameter derived_rdrag =7
integer, parameter derived_kd =8
integer, parameter derived_thetad =9
integer, parameter derived_zeq =10
integer, parameter derived_keq =11
integer, parameter derived_thetaeq =12
integer, parameter derived_theta_rs_eq = 13
integer, parameter nthermo_derived = 13
real(dl), dimension(nthermo_derived) thermoderivedparams
type(tbackgroundoutputs), save backgroundoutputs
Function/Subroutine Documentation
angulardiameterdistance()
real(dl) function modelparams::angulardiameterdistance (real(dl), intent(in) z)
References comovingradialdistance(), cp, and rofchi().
Referenced by angulardiameterdistancearr(), bao_d_v(), cosmomctheta(), thermodata::inithermo(), and luminositydistance().
angulardiameterdistance2()
real(dl) function modelparams::angulardiameterdistance2 (real(dl), intent(in) z1, real(dl), intent(in) z2)
References comovingradialdistance(), cp, and rofchi().
angulardiameterdistancearr()
subroutine modelparams::angulardiameterdistancearr (real(dl), dimension(n), intent(out) arr, real(dl), dimension(n), intent(in) z, integer, intent(in) n)
References angulardiameterdistance().
bao_d_v()
real(dl) function modelparams::bao_d_v (real(dl), intent(in) z)
References angulardiameterdistance(), bao_d_v_from_da_h(), and hofz().
bao_d_v_from_da_h()
real(dl) function modelparams::bao_d_v_from_da_h (real(dl), intent(in) z, real(dl), intent(in) DA, real(dl), intent(in) Hz)
Referenced by bao_d_v(), and thermodata::inithermo().
cambparams_set()
subroutine modelparams::cambparams_set (type(cambparams), intent(in) P, integer, optional error, logical, optional DoReion)
References ac, adotrad, akthom, alphabde, constants::c, constants::c8pig_evm2, call_again, cosmomctheta(), cp, errors::error_unsupported_params, constants::ev, constants::ev2tompcm2, feedbacklevel, fhe, errors::global_error_flag, errors::globalerror(), grhob, grhoc, grhodgc, grhog, grhok, grhom, grhor, grhormass, grhornomass, grhov, init_background(), init_massive_nu(), constants::k_b, k_phi, constants::kappa, lambdac, constants::m_h, constants::mass_ratio_he_h, constants::mpc, constants::mpl2, nnow, nonlinear_both, nonlinear_lens, norm_pot, nu_approx, nu_masses, nu_trunc, omegadgc, omegakflat, reionization::reionization_init(), rofchi(), scale, constants::sigma_boltz, constants::sigma_thomson, timeofz(), and wdgc.
Referenced by camb::camb_getage(), camb::camb_getresults(), camb::camb_getzrefromtau(), handles::cambdata_calcbackgroundtheory(), handles::cambdata_setparamsforbackground(), and calculator_pico::pico_getnewpowerdata().
comovingradialdistance()
real(dl) function modelparams::comovingradialdistance (real(dl), intent(in) z)
References deltatime().
Referenced by angulardiameterdistance(), and angulardiameterdistance2().
cosfunc()
real(dl) function modelparams::cosfunc (real(dl) Chi)
References cp.
Referenced by dtauda(), and gaugeinterface::outputt().
cosmomctheta()
real(dl) function modelparams::cosmomctheta ()
References angulardiameterdistance(), cp, dsound_da(), and reionization::rombint.
Referenced by calculator_camb::cambcalc_cmbtotheta(), cambparams_set(), and calculator_pico::pico_getnewpowerdata().
deltaphysicaltimegyr()
real(dl) function modelparams::deltaphysicaltimegyr (real(dl), intent(in) a1, real(dl), intent(in) a2, real(dl), intent(in), optional in_tol)
References accuracyboost, constants::c, dtda(), constants::gyr, constants::mpc, and reionization::rombint.
Referenced by camb::camb_getage(), and thermodata::inithermo().
deltatime()
real(dl) function modelparams::deltatime (real(dl), intent(in) a1, real(dl), intent(in) a2, real(dl), intent(in), optional in_tol)
References accuracyboost, reionization::dtauda, reionization::rombint, and tol.
Referenced by comovingradialdistance(), gaugeinterface::deltatimemaxed(), dtauda(), gaugeinterface::gaugeinterface_init(), gaugeinterface::initial(), and timeofz().
dsound_da()
real(dl) function modelparams::dsound_da (real(dl) a)
References cp, and reionization::dtauda.
Referenced by cosmomctheta().
dsound_da_exact()
real(dl) function modelparams::dsound_da_exact (real(dl) a)
References reionization::dtauda, grhob, and grhog.
Referenced by thermodata::inithermo().
dtda()
real(dl) function modelparams::dtda (real(dl) a)
References reionization::dtauda.
Referenced by deltaphysicaltimegyr().
f_k()
real(dl) function modelparams::f_k (real(dl), intent(in) x)
References cp, and rofchi().
Referenced by dtauda(), and gaugeinterface::output().
gettesttime()
real(sp) function modelparams::gettesttime ()
Referenced by lensing::badharmonic(), cambmain::cmbmain(), lensing::corrfuncflatsky(), and lensing::corrfuncfullskyimpl().
hofz()
real(dl) function modelparams::hofz (real(dl), intent(in) z)
References reionization::dtauda.
Referenced by bao_d_v(), and thermodata::inithermo().
invsinfunc()
real(dl) function modelparams::invsinfunc (real(dl) x)
References cp.
Referenced by cambmain::integratesourcesbessels().
luminositydistance()
real(dl) function modelparams::luminositydistance (real(dl), intent(in) z)
References angulardiameterdistance().
nxyl()
subroutine modelparams::nxyl (real(dl), dimension(6) y)
rofchi()
real(dl) function modelparams::rofchi (real(dl) Chi)
References cp.
Referenced by angulardiameterdistance(), angulardiameterdistance2(), cambparams_set(), cambmain::dorangeint(), cambmain::dorangeinttensor(), cambmain::dosourceintegration(), dtauda(), f_k(), gaugeinterface::output(), and gaugeinterface::outputt().
tanfunc()
real(dl) function modelparams::tanfunc (real(dl) Chi)
References cp.
Referenced by gaugeinterface::derivs(), gaugeinterface::derivst(), and dtauda().
timeofz()
real(dl) function modelparams::timeofz (real(dl), intent(in) z)
References deltatime().
Referenced by cambmain::calcscalarsources(), cambparams_set(), thermodata::inithermo(), cambmain::initvars(), and timeofzarr().
timeofzarr()
subroutine modelparams::timeofzarr (integer, intent(in) nz, real(dl), dimension(nz), intent(in) redshifts, real(dl), dimension(nz), intent(out) outputs)
References timeofz().
Variable Documentation
ac
real(dl) modelparams::ac
Referenced by quint::bde_xylata(), cambmain::calcscalarsources(), cambparams_set(), dtauda(), and quint::quint_valsata().
accuracyboost
real(dl) modelparams::accuracyboost =1._dl
Referenced by lensing::badharmonic(), cambmain::calcscalarsources(), cambmain::calctensorsources(), cambmain::calcvectorsources(), calculator_camb::cambcalc_initcambparams(), lensing::corrfuncflatsky(), lensing::corrfuncfullskyimpl(), deltaphysicaltimegyr(), deltatime(), cambmain::doflatintegration(), cambmain::dorangeint(), cambmain::dorangeinttensor(), dtauda(), gaugeinterface::gaugeinterface_evolvescal(), gaugeinterface::gaugeinterface_init(), spherbessels::generatebessels(), cambmain::getlimbertransfers(), handles::getoutputevolutionfork(), cambmain::gettransfer(), thermodata::inithermo(), gaugeinterface::initial(), cambmain::inittransfer(), cambmain::initvars(), cambmain::integratesourcesbessels(), massivenu::nu_init(), cambmain::setkvaluesforint(), cambmain::setkvaluesforsources(), gaugeinterface::setuptensorarrayindices(), cambmain::uselimber(), and spherbessels::uspherbesselwithderiv().
adotrad
real(dl) modelparams::adotrad
Referenced by cambparams_set(), dtauda(), gaugeinterface::getnumeqns(), cambmain::gettaustart(), thermodata::inithermo(), gaugeinterface::initial(), gaugeinterface::initialt(), and gaugeinterface::initialv().
akthom
real(dl) modelparams::akthom
Referenced by cambparams_set(), and thermodata::inithermo().
alphabde
real(dl) modelparams::alphabde
Referenced by quint::bde_background(), cambmain::calcscalarsources(), cambparams_set(), dtauda(), and quint::vofphi().
backgroundoutputs
type(tbackgroundoutputs), save modelparams::backgroundoutputs
Referenced by handles::camb_getbackgroundoutputs(), handles::camb_getnumbackgroundoutputs(), handles::camb_setbackgroundoutputs_z(), calculator_camb::cambcalc_initcambparams(), and thermodata::inithermo().
call_again
logical modelparams::call_again = .false.
Referenced by camb::camb_getresults(), and cambparams_set().
cp
type(cambparams), save modelparams::cp
Referenced by angulardiameterdistance(), angulardiameterdistance2(), nonlinear::assign_hm_cosmology(), cambmain::calclimberscalcls(), cambmain::calcscalarsources(), cambmain::calcscalcls(), cambmain::calcscalcls2(), cambmain::calctenscls(), cambmain::calcveccls(), camb::camb_getcls(), camb::camb_getresults(), camb::camb_getzrefromtau(), handles::camb_setlensedscalcls(), handles::camb_setlenspotentialcls(), handles::camb_settensorcls(), handles::camb_settotcls(), handles::camb_setunlensedcls(), handles::camb_setunlensedscalararray(), handles::camb_setunlensedscalcls(), camb::camb_transferstopowers(), cambparams_set(), cambmain::cltransfertocl(), cambmain::cmbmain(), gaugeinterface::copyscalarvariablearray(), gaugeinterface::copytensorvariablearray(), lensing::corrfuncfullsky(), lensing::corrfuncfullskyimpl(), cosfunc(), cosmomctheta(), gaugeinterface::derivs(), gaugeinterface::derivst(), cambmain::doflatintegration(), cambmain::dorangeint(), cambmain::dorangeinttensor(), cambmain::dosourceintegration(), cambmain::dosourcek(), dsound_da(), dtauda(), f_k(), gaugeinterface::gaugeinterface_evolvescal(), gaugeinterface::gaugeinterface_init(), spherbessels::generatebessels(), cambmain::getlimbertransfers(), gaugeinterface::getnumeqns(), getomegak(), cambmain::getsourcemem(), cambmain::gettaustart(), cambmain::gettransfer(), modeldata::init_cls(), thermodata::inithermo(), gaugeinterface::initial(), gaugeinterface::initialt(), gaugeinterface::initialv(), lvalues::initlval(), spherbessels::initspherbessels(), cambmain::inittransfer(), cambmain::initvars(), cambmain::integratesourcesbessels(), cambmain::interpolatecls(), cambmain::interpolatesources(), invsinfunc(), lensing::lens_cls(), gaugeinterface::massivenuvars(), gaugeinterface::massivenuvarsout(), nonlinear::nonlinear_getnonlinratios(), modeldata::normalizeclsatl(), massivenu::nu_init(), gaugeinterface::output(), modeldata::output_cl_files(), modeldata::output_lens_pot_files(), modeldata::output_veccl_files(), gaugeinterface::outputt(), gaugeinterface::outputv(), rofchi(), cambmain::setclosedkvaluesfromarr(), cambmain::setkvaluesforint(), cambmain::setkvaluesforsources(), gaugeinterface::setupscalararrayindices(), gaugeinterface::setuptensorarrayindices(), cambmain::sourcetotransfers(), and tanfunc().
debugevolution
logical, parameter modelparams::debugevolution = .false.
Referenced by cambmain::calcscalarsources(), and cambmain::interpolatesources().
debugmsgs
logical, parameter modelparams::debugmsgs =.false.
Referenced by lensing::badharmonic(), cambmain::cltransfertocl(), cambmain::cmbmain(), lensing::corrfuncflatsky(), lensing::corrfuncfullskyimpl(), spherbessels::generatebessels(), thermodata::inithermo(), spherbessels::initspherbessels(), cambmain::initvars(), and cambmain::transferout().
debugparam
real(dl) modelparams::debugparam = 0._dl
derived_age
integer, parameter modelparams::derived_age =1
Referenced by thermodata::inithermo().
derived_dastar
integer, parameter modelparams::derived_dastar = 5
Referenced by thermodata::inithermo().
derived_kd
integer, parameter modelparams::derived_kd =8
Referenced by thermodata::inithermo().
derived_keq
integer, parameter modelparams::derived_keq =11
Referenced by thermodata::inithermo().
derived_rdrag
integer, parameter modelparams::derived_rdrag =7
Referenced by thermodata::inithermo().
derived_rstar
integer, parameter modelparams::derived_rstar =3
Referenced by thermodata::inithermo().
derived_theta_rs_eq
integer, parameter modelparams::derived_theta_rs_eq = 13
Referenced by thermodata::inithermo().
derived_thetad
integer, parameter modelparams::derived_thetad =9
Referenced by thermodata::inithermo().
derived_thetaeq
integer, parameter modelparams::derived_thetaeq =12
Referenced by thermodata::inithermo().
derived_thetastar
integer, parameter modelparams::derived_thetastar =4
Referenced by thermodata::inithermo().
derived_zdrag
integer, parameter modelparams::derived_zdrag =6
Referenced by thermodata::inithermo().
derived_zeq
integer, parameter modelparams::derived_zeq =10
Referenced by thermodata::inithermo().
derived_zstar
integer, parameter modelparams::derived_zstar =2
Referenced by thermodata::inithermo().
do_bispectrum
logical modelparams::do_bispectrum = .false.
Referenced by camb::camb_getresults(), cambmain::doflatintegration(), spherbessels::generatebessels(), thermodata::inithermo(), and cambmain::setkvaluesforint().
dtaurec
real(dl) modelparams::dtaurec
Referenced by thermodata::inithermo(), and cambmain::initvars().
feedbacklevel
integer modelparams::feedbacklevel = 0
Referenced by lensing::badharmonic(), cambparams_set(), cambmain::cltransfertocl(), cambmain::cmbmain(), spherbessels::generatebessels(), cambmain::getlimbertransfers(), thermodata::inithermo(), spherbessels::initspherbessels(), cambmain::initvars(), and cambmain::transferout().
fhe
real(dl) modelparams::fhe
Referenced by cambparams_set().
fileio_unit
integer, parameter modelparams::fileio_unit = 13
Referenced by modeldata::checkloadedhighltemplate().
fixq
real(dl) modelparams::fixq = 0._dl
Referenced by cambmain::calcscalarsources(), cambmain::dosourcek(), dtauda(), and cambmain::gettaustart().
full_bessel_integration
logical, parameter modelparams::full_bessel_integration = .false.
Referenced by cambmain::doflatintegration().
grhob
real(dl) modelparams::grhob
Referenced by cambmain::calcscalarsources(), cambparams_set(), gaugeinterface::derivs(), gaugeinterface::derivst(), gaugeinterface::derivsv(), dsound_da_exact(), dtauda(), cambmain::evolved(), handles::getoutputevolutionfork(), thermodata::inithermo(), gaugeinterface::initial(), gaugeinterface::initialt(), gaugeinterface::initialv(), and gaugeinterface::output().
grhoc
real(dl) modelparams::grhoc
Referenced by cambmain::calcscalarsources(), cambparams_set(), gaugeinterface::derivs(), gaugeinterface::derivst(), gaugeinterface::derivsv(), dtauda(), cambmain::evolved(), handles::getoutputevolutionfork(), thermodata::inithermo(), gaugeinterface::initial(), gaugeinterface::initialt(), gaugeinterface::initialv(), and gaugeinterface::output().
grhodgc
real(dl) modelparams::grhodgc
Referenced by cambmain::calcscalarsources(), cambparams_set(), and dtauda().
grhog
real(dl) modelparams::grhog
Referenced by cambmain::calcscalarsources(), cambparams_set(), gaugeinterface::derivs(), gaugeinterface::derivst(), gaugeinterface::derivsv(), dsound_da_exact(), dtauda(), thermodata::inithermo(), gaugeinterface::initial(), gaugeinterface::initialt(), gaugeinterface::initialv(), and gaugeinterface::output().
grhok
real(dl) modelparams::grhok
Referenced by cambparams_set(), gaugeinterface::derivs(), gaugeinterface::derivst(), dtauda(), and gaugeinterface::output().
grhom
real(dl) modelparams::grhom
Referenced by cambparams_set(), thermodata::inithermo(), and massivenu::nu_init().
grhor
real(dl) modelparams::grhor
Referenced by cambparams_set(), and massivenu::nu_init().
grhormass
real(dl), dimension(max_nu) modelparams::grhormass
Referenced by cambparams_set(), gaugeinterface::derivst(), dtauda(), thermodata::inithermo(), gaugeinterface::initial(), gaugeinterface::initialt(), gaugeinterface::massivenuvars(), and gaugeinterface::massivenuvarsout().
grhornomass
real(dl) modelparams::grhornomass
Referenced by cambmain::calcscalarsources(), cambparams_set(), gaugeinterface::derivs(), gaugeinterface::derivst(), gaugeinterface::derivsv(), dtauda(), thermodata::inithermo(), gaugeinterface::initial(), gaugeinterface::initialt(), gaugeinterface::initialv(), and gaugeinterface::output().
grhov
real(dl) modelparams::grhov
Referenced by cambparams_set(), gaugeinterface::derivs(), gaugeinterface::derivst(), gaugeinterface::derivsv(), dtauda(), lambdageneral::grho_de(), and gaugeinterface::output().
hard_bispectrum
logical, parameter modelparams::hard_bispectrum = .false.
Referenced by thermodata::inithermo(), and cambmain::setkvaluesforint().
highaccuracydefault
logical modelparams::highaccuracydefault = .true.
Referenced by camb::camb_getresults(), calculator_camb::cambcalc_initcambparams(), lensing::corrfuncfullsky(), cambmain::doflatintegration(), cambmain::dorangeint(), dtauda(), gaugeinterface::getnumeqns(), gaugeinterface::initial(), lvalues::initlval(), cambmain::inittransfer(), cambmain::integratesourcesbessels(), cambmain::setkvaluesforint(), and cambmain::setkvaluesforsources().
highl_cl_template
real(dl), dimension(:,:), allocatable modelparams::highl_cl_template
Referenced by modeldata::checkloadedhighltemplate(), lensing::corrfuncfullskyimpl(), and lvalues::interpolateclarrtemplated().
highl_unlensed_cl_template
character(len=1024) modelparams::highl_unlensed_cl_template = 'HighLExtrapTemplate_lenspotentialCls.dat'
Referenced by modeldata::checkloadedhighltemplate(), and handles::set_cls_template().
k_phi
real(dl) modelparams::k_phi
Referenced by cambparams_set().
l0max
integer, parameter modelparams::l0max =4000
Referenced by dtauda(), and gaugeinterface::getnumeqns().
laccuracyboost
real(sp) modelparams::laccuracyboost =1.
Referenced by calculator_camb::cambcalc_initcambparams(), dtauda(), gaugeinterface::gaugeinterface_init(), gaugeinterface::getnumeqns(), gaugeinterface::initial(), and gaugeinterface::setupscalararrayindices().
lambdac
real(dl) modelparams::lambdac
Referenced by cambmain::calcscalarsources(), cambparams_set(), and dtauda().
limber_phiphi
integer modelparams::limber_phiphi = 0
Referenced by cambmain::calclimberscalcls(), cambmain::calcscalcls(), cambmain::getlimbertransfers(), and modeldata::init_limber().
lmax_arr
integer, parameter modelparams::lmax_arr = l0max
lmax_extrap_highl
integer, parameter modelparams::lmax_extrap_highl = 8000
Referenced by modeldata::checkloadedhighltemplate(), lensing::corrfuncfullsky(), and lvalues::interpolateclarrtemplated().
lmin
integer, parameter modelparams::lmin = 2
Referenced by handles::camb_setlensedscalcls(), handles::camb_setlenspotentialcls(), handles::camb_settensorcls(), handles::camb_settotcls(), handles::camb_setunlensedcls(), handles::camb_setunlensedscalararray(), handles::camb_setunlensedscalcls(), modeldata::checkloadedhighltemplate(), modeldata::init_cls(), lvalues::initlval(), cambmain::interpolatecls(), modeldata::normalizeclsatl(), modeldata::output_cl_files(), modeldata::output_lens_pot_files(), and modeldata::output_veccl_files().
lsampleboost
real(dl) modelparams::lsampleboost =1._dl
Referenced by calculator_camb::cambcalc_initcambparams(), and lvalues::initlval().
max_bessels_etak
real(dl) modelparams::max_bessels_etak = 1000000*2
Referenced by cambmain::cmbmain(), spherbessels::generatebessels(), cambmain::getlimbertransfers(), spherbessels::initspherbessels(), and cambmain::setkvaluesforint().
max_bessels_l_index
integer modelparams::max_bessels_l_index = 1000000
Referenced by cambmain::cmbmain(), cambmain::doflatintegration(), spherbessels::generatebessels(), and cambmain::getlimbertransfers().
max_nu
integer, parameter modelparams::max_nu = 5
max_transfer_redshifts
integer, parameter modelparams::max_transfer_redshifts = 150
Referenced by camb::camb_validateparams(), and calculator_camb::cambcalc_initcambparams().
nnow
real(dl) modelparams::nnow
Referenced by cambparams_set().
nonlinear_both
integer, parameter modelparams::nonlinear_both =3
Referenced by calculator_camb::cambcalc_initcambparams(), handles::cambdata_gettransfers(), cambparams_set(), and cambmain::cmbmain().
nonlinear_lens
integer, parameter modelparams::nonlinear_lens =2
Referenced by calculator_camb::cambcalc_initcambparams(), handles::cambdata_gettransfers(), cambparams_set(), and cambmain::cmbmain().
nonlinear_none
integer, parameter modelparams::nonlinear_none =0
Referenced by camb::camb_setdefparams().
nonlinear_pk
integer, parameter modelparams::nonlinear_pk =1
Referenced by calculator_camb::cambcalc_initcambparams().
norm_pot
real(dl) modelparams::norm_pot
Referenced by cambparams_set(), and quint::vofphi().
nthermo_derived
integer, parameter modelparams::nthermo_derived = 13
nu_approx
integer, parameter modelparams::nu_approx = 2
Referenced by cambparams_set().
nu_best
integer, parameter modelparams::nu_best = 3
Referenced by camb::camb_setdefparams(), dtauda(), and gaugeinterface::getnumeqns().
nu_int
integer, parameter modelparams::nu_int = 0
nu_masses
real(dl), dimension(max_nu) modelparams::nu_masses
Referenced by cambparams_set(), gaugeinterface::copyscalarvariablearray(), gaugeinterface::derivs(), gaugeinterface::derivst(), dtauda(), gaugeinterface::gaugeinterface_init(), gaugeinterface::getnumeqns(), cambmain::gettaustart(), init_massive_nu(), gaugeinterface::initial(), gaugeinterface::massivenuvars(), gaugeinterface::massivenuvarsout(), massivenu::nu_init(), gaugeinterface::nu_integrate_l012(), gaugeinterface::nu_intvsq(), gaugeinterface::nu_pi(), gaugeinterface::nu_pinudot(), gaugeinterface::setupscalararrayindices(), and gaugeinterface::switchtomassivenuapprox().
nu_trunc
integer, parameter modelparams::nu_trunc =1
Referenced by cambparams_set(), dtauda(), gaugeinterface::gaugeinterface_evolvescal(), and gaugeinterface::getnumeqns().
num_extra_redshiftwindows
integer modelparams::num_extra_redshiftwindows = 0
Referenced by cambmain::getsourcemem().
num_redshiftwindows
integer modelparams::num_redshiftwindows = 0
Referenced by cambmain::calclimberscalcls(), cambmain::calcscalcls(), cambmain::cmbmain(), cambmain::getlimbertransfers(), cambmain::getsourcemem(), modeldata::init_cls(), modeldata::init_limber(), and cambmain::interpolatecls().
omegadgc
real(dl) modelparams::omegadgc
Referenced by cambparams_set().
omegakflat
real(dl), parameter modelparams::omegakflat = 5e-7_dl
Referenced by cambparams_set().
outnone
integer, parameter modelparams::outnone =1
Referenced by camb::camb_setdefparams(), and calculator_camb::cambcalc_initcambparams().
output_file_headers
logical modelparams::output_file_headers = .true.
Referenced by modeldata::open_file_header().
outputdenominator
real(dl), parameter modelparams::outputdenominator =twopi
Referenced by lensing::badharmonic(), cambmain::calclimberscalcls(), cambmain::calcscalcls(), cambmain::calcscalcls2(), cambmain::calctenscls(), cambmain::calcveccls(), lensing::corrfuncflatsky(), and lensing::corrfuncfullskyimpl().
scale
real(dl) modelparams::scale
Referenced by lensing::badharmonic(), cambparams_set(), cambmain::cmbmain(), cambmain::dorangeint(), cambmain::dorangeinttensor(), and lvalues::initlval().
spl_large
real(dl), parameter modelparams::spl_large =1.e40_dl
Referenced by spherbessels::generatebessels(), lensing::getbessels(), cambmain::initsourceinterpolation(), cambmain::interpolatesources(), and cambmain::makenonlinearsources().
tau_maxvis
real(dl) modelparams::tau_maxvis
Referenced by dtauda(), cambmain::getlimbertransfers(), thermodata::inithermo(), cambmain::initvars(), gaugeinterface::output(), and gaugeinterface::setuptensorarrayindices().
taurend
real(dl) modelparams::taurend
Referenced by cambmain::calcscalarsources(), dtauda(), gaugeinterface::gaugeinterface_evolvescal(), and thermodata::inithermo().
taurst
real(dl) modelparams::taurst
Referenced by thermodata::inithermo(), cambmain::inittransfer(), and cambmain::setkvaluesforsources().
thermoderivedparams
real(dl), dimension(nthermo_derived) modelparams::thermoderivedparams
Referenced by thermodata::inithermo().
threadnum
integer modelparams::threadnum = 0
Referenced by calculator_camb::cambcalc_gettheoryforimportance(), and calculator_camb::cambcalc_initcambparams().
timesteps
type(regions) modelparams::timesteps
Referenced by cambmain::calcscalarsources(), cambmain::calctensorsources(), cambmain::calcvectorsources(), cambmain::doflatintegration(), cambmain::dorangeint(), cambmain::dorangeinttensor(), cambmain::getlimbertransfers(), cambmain::getsourcemem(), thermodata::inithermo(), cambmain::initsourceinterpolation(), cambmain::integratesourcesbessels(), cambmain::integrationvars_init(), cambmain::interpolatesources(), cambmain::makenonlinearsources(), and cambmain::sourcetotransfers().
tol
real(dl), parameter modelparams::tol =1.0d-4
Referenced by cambmain::calcscalarsources(), cambmain::calctensorsources(), cambmain::calcvectorsources(), deltatime(), gaugeinterface::deltatimemaxed(), dtauda(), handles::getoutputevolutionfork(), and cambmain::gettransfer().
use_spline_template
logical modelparams::use_spline_template = .true.
Referenced by lvalues::initlval(), and lvalues::interpolateclarrtemplated().
version
character(len=*), parameter modelparams::version = 'Nov16'
wdgc
real(dl) modelparams::wdgc
Referenced by cambmain::calcscalarsources(), cambparams_set(), and dtauda().