cosmomc_bde_v3p1: plot_directive Namespace Reference
plot_directive Namespace Reference
Classes
class ImageFile
class PlotError
Functions
def format_template (template, kw)
def plot_directive (name, arguments, options, content, lineno, content_offset, block_text, state, state_machine)
def _option_boolean (arg)
def _option_context (arg)
def _option_format (arg)
def _option_align (arg)
def mark_plot_labels (app, document)
def setup (app)
def contains_doctest (text)
def unescape_doctest (text)
def split_code_at_show (text)
def remove_coding (text)
def out_of_date (original, derived)
def run_code (code, code_path, ns=None, function_name=None)
def clear_state (plot_rcparams, close=True)
def render_figures (code, code_path, output_dir, output_base, context, function_name, config, context_reset=False)
def run (arguments, content, options, state_machine, state, lineno)
Variables
align = Image.align
sphinx_version = sphinx.__version__.split(".")
int __version__ = 2
string TEMPLATE
string exception_template
plot_context = dict()
Detailed Description
A directive for including a matplotlib plot in a Sphinx document.
By default, in HTML output, `plot` will include a .png file with a
link to a high-res .png and .pdf.  In LaTeX output, it will include a
.pdf.
The source code for the plot may be included in one of three ways:
  1. **A path to a source file** as the argument to the directive::
       .. plot:: path/to/plot.py
     When a path to a source file is given, the content of the
     directive may optionally contain a caption for the plot::
       .. plot:: path/to/plot.py
  This is the caption for the plot
     Additionally, one my specify the name of a function to call (with
     no arguments) immediately after importing the module::
       .. plot:: path/to/plot.py plot_function1
  2. Included as **inline content** to the directive::
       .. plot::
  import matplotlib.pyplot as plt
  import matplotlib.image as mpimg
  import numpy as np
  img = mpimg.imread('_static/stinkbug.png')
  imgplot = plt.imshow(img)
  3. Using **doctest** syntax::
       .. plot::
  A plotting example:
  >>> import matplotlib.pyplot as plt
  >>> plt.plot([1,2,3], [4,5,6])
Options
-------
The ``plot`` directive supports the following options:
    format : {'python', 'doctest'}
Specify the format of the input
    include-source : bool
Whether to display the source code. The default can be changed
using the `plot_include_source` variable in conf.py
    encoding : str
If this source file is in a non-UTF8 or non-ASCII encoding,
the encoding must be specified using the `:encoding:` option.
The encoding will not be inferred using the ``-*- coding -*-``
metacomment.
    context : bool or str
If provided, the code will be run in the context of all
previous plot directives for which the `:context:` option was
specified.  This only applies to inline code plot directives,
not those run from files. If the ``:context: reset`` is specified,
the context is reset for this and future plots.
    nofigs : bool
If specified, the code block will be run, but no figures will
be inserted.  This is usually useful with the ``:context:``
option.
Additionally, this directive supports all of the options of the
`image` directive, except for `target` (since plot will add its own
target).  These include `alt`, `height`, `width`, `scale`, `align` and
`class`.
Configuration options
---------------------
The plot directive has the following configuration options:
    plot_include_source
Default value for the include-source option
    plot_html_show_source_link
Whether to show a link to the source in HTML.
    plot_pre_code
Code that should be executed before each plot.
    plot_basedir
Base directory, to which ``plot::`` file names are relative
to.  (If None or empty, file names are relative to the
directory where the file containing the directive is.)
    plot_formats
File formats to generate. List of tuples or strings::
    [(suffix, dpi), suffix, ...]
that determine the file format and the DPI. For entries whose
DPI was omitted, sensible defaults are chosen.
    plot_html_show_formats
Whether to show links to the files in HTML.
    plot_rcparams
A dictionary containing any non-standard rcParams that should
be applied before each plot.
    plot_apply_rcparams
By default, rcParams are applied when `context` option is not used in
a plot directive.  This configuration option overrides this behavior
and applies rcParams before each plot.
    plot_working_directory
By default, the working directory will be changed to the directory of
the example, so the code can get at its data files, if any.  Also its
path will be added to `sys.path` so it can import any helper modules
sitting beside it.  This configuration option can be used to specify
a central directory (also added to `sys.path`) where data files and
helper modules for all code are located.
    plot_template
Provide a customized template for preparing restructured text.
Function Documentation
_option_align()
def plot_directive._option_align (arg) private
_option_boolean()
def plot_directive._option_boolean (arg) private
_option_context()
def plot_directive._option_context (arg) private
_option_format()
def plot_directive._option_format (arg) private
clear_state()
def plot_directive.clear_state (plot_rcparams, close = True)
References render_figures().
Referenced by render_figures().
contains_doctest()
def plot_directive.contains_doctest (text)
Referenced by run(), split_code_at_show(), and unescape_doctest().
format_template()
def plot_directive.format_template (template, kw)
Referenced by run().
mark_plot_labels()
def plot_directive.mark_plot_labels (app, document)
To make plots referenceable, we need to move the reference from
the "htmlonly" (or "latexonly") node to the actual figure node
itself.
out_of_date()
def plot_directive.out_of_date (original, derived)
Returns True if derivative is out-of-date wrt original,
both of which are full file paths.
Referenced by render_figures().
plot_directive()
def plot_directive.plot_directive (name, arguments, options, content, lineno, content_offset, block_text, state, state_machine)
References run().
remove_coding()
def plot_directive.remove_coding (text)
Remove the coding comment, which six.exec_ doesn't like.
render_figures()
def plot_directive.render_figures (code, code_path, output_dir, output_base, context, function_name, config, context_reset = False)
Run a pyplot script and save the low and high res PNGs and a PDF
in *output_dir*.
Save the images under *output_dir* with file names derived from
*output_base*
References clear_state(), CAMB_test_files.int, out_of_date(), run_code(), split_code_at_show(), and CAMB_test_files.type.
Referenced by clear_state(), and run().
run()
def plot_directive.run (arguments, content, options, state_machine, state, lineno)
References contains_doctest(), format_template(), stringutils.join(), render_figures(), and unescape_doctest().
Referenced by plot_directive().
run_code()
def plot_directive.run_code (code, code_path, ns = None, function_name = None)
Import a Python module from a path, and run the function given by
name, if function_name is not None.
Referenced by render_figures().
setup()
def plot_directive.setup (app)
split_code_at_show()
def plot_directive.split_code_at_show (text)
Split code at plt.show()
References contains_doctest(), and stringutils.join().
Referenced by render_figures().
unescape_doctest()
def plot_directive.unescape_doctest (text)
Extract code from a piece of text, which contains either Python code
or doctests.
References contains_doctest().
Referenced by run().
Variable Documentation
__version__
int plot_directive.__version__ = 2 private
align
plot_directive.align = Image.align
exception_template
string plot_directive.exception_template
Initial value:
 =  """
 .. htmlonly::
    [`source code <%(linkdir)s/%(basename)s.py>`__]
 Exception occurred rendering plot.
 """
plot_context
plot_directive.plot_context = dict()
sphinx_version
plot_directive.sphinx_version = sphinx.__version__.split(".")
TEMPLATE
string plot_directive.TEMPLATE