cosmomc_bde_v3p1: getdist.chains Namespace Reference
getdist.chains Namespace Reference
Classes
class Chains
class ParamConfidenceData
class ParSamples
class WeightedSampleError
class WeightedSamples
Functions
def lastModified (files)
def chainFiles (root, chain_indices=None, ext='.txt', first_chain=0, last_chain=-1, chain_exclude=None)
def loadNumpyTxt (fname, skiprows=None)
def getSignalToNoise (C, noise=None, R=None, eigs_only=False)
def covToCorr (cov, copy=True)
Variables
bool print_load_details = True
use_pandas = LooseVersion(pandas.version.version) > LooseVersion("0.14.0")
Function Documentation
chainFiles()
def getdist.chains.chainFiles (root, chain_indices = None, ext = '.txt', first_chain = 0, last_chain = -1, chain_exclude = None)
Creates a list of file names for samples given a root name and optional filters
:param root: Root name for files (no extension)
:param chain_indices: If True, only indexes inside the list included, If False, includes all indexes.
:param ext: extension for files
:param first_chain: The first index to include.
:param last_chain: The last index to include.
:param chain_exclude: A list of indexes to exclude, None to include all
:return: The list of file names
covToCorr()
def getdist.chains.covToCorr (cov, copy = True)
Convert covariance matrix to correlation matrix
:param cov: The covariance matrix to work on
:param copy: True if we shouldn't modify the input matrix, False otherwise.
:return: correlation matrix
Referenced by getdist.chains.WeightedSamples.corr(), and getdist.chains.WeightedSamples.getCorrelationMatrix().
getSignalToNoise()
def getdist.chains.getSignalToNoise (C, noise = None, R = None, eigs_only = False)
Returns w, M, where w is the eigenvalues of the signal to noise (small means better constrained)
:param C: covariance matrix
:param noise: noise matrix
:param R: rotation matrix, defaults to inverse of Cholesky root of the noise matrix
:param eigs_only: only return eigenvalues
:return: eigenvalues and matrix
lastModified()
def getdist.chains.lastModified (files)
Returns the the latest "last modified" time for the given list of files. Ignores files that do not exist.
:param files: An iterable of file names.
:return: The latest "last modified" time
loadNumpyTxt()
def getdist.chains.loadNumpyTxt (fname, skiprows = None)
Utility routine to loads numpy array from file.
Uses faster pandas read routine if pandas is installed, or falls back to numpy's loadtxt otherwise
:param fname: The file to load
:param skiprows: The number of rows to skip at the begging of the file
:return: numpy array of the data values
Referenced by getdist.chains.WeightedSamples.__init__().
Variable Documentation
print_load_details
bool getdist.chains.print_load_details = True
use_pandas
bool getdist.chains.use_pandas = LooseVersion(pandas.version.version) > LooseVersion("0.14.0")