cosmomc_bde_v3p1: numbercounts Module Reference
numbercounts Module Reference
Functions/Subroutines
real(dl) function next_z (zi, binz)
subroutine deltan_yz (Z, Nz, LOGY, Ny, DN, DN2D, skyfracs, thetas, ylims, switch, qa_ytot, erf_list)
subroutine integrate_m_z (grid, skyfracs, compl, steps_z, steps_m, nsteps_z, nsteps_m, z1, z2, binz, dlnm, sum)
subroutine integrate_m_zq (grid, skyfracs, compl, steps_z, steps_m, nsteps_z, nsteps_m, z1, z2, binz, biny, dlnm, sum)
subroutine grid_c_2d (npatches, steps_z, steps_m, thetas, ylims, skyfracs, completeness, logy, qa_ytot, erf_list, iy)
subroutine grid_c (npatches, steps_z, steps_m, thetas, ylims, skyfracs, completeness, qa_ytot, erf_list)
subroutine get_grid (nz, nm, z, lnm, grid)
Function/Subroutine Documentation
deltan_yz()
subroutine numbercounts::deltan_yz (real(dl), dimension(:), intent(in) Z, integer, intent(in) Nz, real(dl), dimension(:), intent(in) LOGY, integer, intent(in) Ny, real(dl), dimension(:) DN, real(dl), dimension(:,:) DN2D, real(dl), dimension(:), intent(in) skyfracs, real(dl), dimension(:), intent(in) thetas, real(dl), dimension(:,:), intent(in) ylims, integer, intent(in) switch, real(dl), dimension(:,:), intent(in) qa_ytot, real(dl), dimension(:,:), intent(in) erf_list)
References get_grid(), grid_c(), grid_c_2d(), integrate_m_z(), integrate_m_zq(), and next_z().
Referenced by szcounts::szcc_cash().
get_grid()
subroutine numbercounts::get_grid (integer nz, integer nm, real(dl), dimension(:) z, real(dl), dimension(:) lnm, real(dl), dimension(:,:) grid)
References power_sz::delta(), and massfunction::dndlnm().
Referenced by deltan_yz().
grid_c()
subroutine numbercounts::grid_c (integer npatches, real(dl), dimension(:), intent(in) steps_z, real(dl), dimension(:), intent(in) steps_m, real(dl), dimension(:), intent(in) thetas, real(dl), dimension(:,:), intent(in) ylims, real(dl), dimension(:), intent(in) skyfracs, real(sp), dimension(:,:) completeness, real(dl), dimension(:,:), intent(in) qa_ytot, real(dl), dimension(:,:), intent(in) erf_list)
References massobservable::erf_compl(), constants_sz::pi, massobservable::q, massobservable::theta500(), and massobservable::y500().
Referenced by deltan_yz().
grid_c_2d()
subroutine numbercounts::grid_c_2d (integer npatches, real(dl), dimension(:), intent(in) steps_z, real(dl), dimension(:), intent(in) steps_m, real(dl), dimension(:), intent(in) thetas, real(dl), dimension(:,:), intent(in) ylims, real(dl), dimension(:), intent(in) skyfracs, real(sp), dimension(:,:,:) completeness, real(dl), dimension(:), intent(in) logy, real(dl), dimension(:,:), intent(in) qa_ytot, real(dl), dimension(:,:), intent(in) erf_list, integer iy)
References massobservable::erf_compl(), constants_sz::pi, massobservable::q, massobservable::theta500(), and massobservable::y500().
Referenced by deltan_yz().
integrate_m_z()
subroutine numbercounts::integrate_m_z (real(dl), dimension(:,:), intent(in) grid, real(dl), dimension(:), intent(in) skyfracs, real (sp), dimension(:,:), intent(in) compl, real(dl), dimension(:), intent(in) steps_z, real(dl), dimension(:), intent(in) steps_m, integer nsteps_z, integer nsteps_m, real(dl), intent(in) z1, real(dl), intent(in) z2, real(dl), intent(in) binz, real(dl), intent(in) dlnm, real(dl) sum)
Referenced by deltan_yz().
integrate_m_zq()
subroutine numbercounts::integrate_m_zq (real(dl), dimension(:,:), intent(in) grid, real(dl), dimension(:), intent(in) skyfracs, real (sp), dimension(:,:,:), intent(in) compl, real(dl), dimension(:), intent(in) steps_z, real(dl), dimension(:), intent(in) steps_m, integer nsteps_z, integer nsteps_m, real(dl), intent(in) z1, real(dl), intent(in) z2, real(dl), intent(in) binz, integer biny, real(dl), intent(in) dlnm, real(dl) sum)
Referenced by deltan_yz().
next_z()
real(dl) function numbercounts::next_z (real(dl) zi, real(dl) binz)
Referenced by deltan_yz().