cosmomc_bde_v3p1: samplecollector Module Reference
samplecollector Module Reference
Data Types
type tmpichaincollector
type tmpidata
Functions/Subroutines
subroutine tmpichaincollector_addnewweightedpoint (this, CurParams, CurLike, mult, thin_fac)
subroutine tmpichaincollector_readparams (this, Ini)
subroutine tmpichaincollector_savestate (this, F)
subroutine tmpichaincollector_readstate (this, F)
subroutine tmpichaincollector_writecheckpoint (this)
subroutine tmpichaincollector_readcheckpoint (this)
subroutine tmpichaincollector_clear (this)
subroutine tmpichaincollector_updatecovandcheckconverge (this)
subroutine tmpichaincollector_addnewpoint (this, P, like)
subroutine convergestatus (isDone, R, Msg)
logical function checklimitsconverge (this, L, MpiCovmat)
Variables
integer, parameter chk_id = 3252359
Function/Subroutine Documentation
checklimitsconverge()
logical function samplecollector::checklimitsconverge (class(tmpichaincollector) this, class(tsamplelist), intent(in) L, real(mcp), dimension(:,:), intent(in) MpiCovmat) private
References baseparameters::baseparams.
convergestatus()
subroutine samplecollector::convergestatus (logical, intent(in) isDone, real(mcp), intent(in) R, character(len=*), intent(in), optional Msg) private
Referenced by tmpichaincollector_updatecovandcheckconverge().
tmpichaincollector_addnewpoint()
subroutine samplecollector::tmpichaincollector_addnewpoint (class(tmpichaincollector) this, real(mcp), dimension(:) P, real(mcp), intent(in) like) private
References baseparameters::baseparams.
tmpichaincollector_addnewweightedpoint()
subroutine samplecollector::tmpichaincollector_addnewweightedpoint (class(tmpichaincollector) this, class(tcalculationatparampoint), intent(in) CurParams, real(mcp) CurLike, real(mcp), intent(in) mult, integer, intent(in), optional thin_fac) private
tmpichaincollector_clear()
subroutine samplecollector::tmpichaincollector_clear (type(tmpichaincollector) this) private
Referenced by samplecollector::tmpichaincollector::tmpichaincollector_clear().
tmpichaincollector_readcheckpoint()
subroutine samplecollector::tmpichaincollector_readcheckpoint (class(tmpichaincollector) this) private
References chk_id.
tmpichaincollector_readparams()
subroutine samplecollector::tmpichaincollector_readparams (class(tmpichaincollector) this, class(tsettingini) Ini) private
tmpichaincollector_readstate()
subroutine samplecollector::tmpichaincollector_readstate (class(tmpichaincollector) this, class(tfilestream) F) private
References baseparameters::baseparams.
tmpichaincollector_savestate()
subroutine samplecollector::tmpichaincollector_savestate (class(tmpichaincollector) this, class(tfilestream) F) private
tmpichaincollector_updatecovandcheckconverge()
subroutine samplecollector::tmpichaincollector_updatecovandcheckconverge (class(tmpichaincollector) this) private
References baseparameters::baseparams, convergestatus(), and samples::gelmanrubinevalues().
tmpichaincollector_writecheckpoint()
subroutine samplecollector::tmpichaincollector_writecheckpoint (class(tmpichaincollector) this) private
References chk_id.
Variable Documentation
chk_id
integer, parameter samplecollector::chk_id = 3252359 private
Referenced by tmpichaincollector_readcheckpoint(), and tmpichaincollector_writecheckpoint().