cosmomc_bde_v3p1: transfer Module Reference
transfer Module Reference
Data Types
type matterpowerdata
type mattertransferdata
interface transfer_getmatterpower
Functions/Subroutines
subroutine transfer_getunsplinedpower (M, PK, var1, var2, hubble_units)
subroutine transfer_getunsplinednonlinearpower (M, PK, var1, var2, hubble_units)
subroutine transfer_getmatterpowerdata (MTrans, PK_data, power_ix, itf_only, var1, var2)
subroutine matterpowerdata_load (PK_data, fname)
subroutine matterpowerdata_getsplines (PK_data)
subroutine matterpowerdata_makenonlinear (PK_data)
subroutine matterpowerdata_free (PK_data)
subroutine matterpowerdata_nullify (PK_data)
real(dl) function matterpowerdata_k (PK, kh, itf)
subroutine transfer_getmatterpowers (MTrans, outpower, itf, in, minkh, dlnkh, npoints, var1, var2)
subroutine transfer_getmatterpowerd (MTrans, outpower, itf_PK, in, minkh, dlnkh, npoints, var1, var2)
subroutine transfer_get_sigmar (MTrans, R, outvals, var1, var2, power_ix, root)
subroutine transfer_getsigmararray (MTrans, R, sigmaR, redshift_ix, var1, var2, power_ix)
subroutine transfer_get_sigma8 (MTrans, R, var1, var2)
subroutine transfer_get_sigmas (MTrans, R, var_delta, var_v)
subroutine transfer_output_sig8 (MTrans)
subroutine transfer_allocate (MTrans)
subroutine transfer_nullify (Mtrans)
subroutine transfer_free (MTrans)
subroutine transfer_setfornonlinearlensing (P)
subroutine transfer_savetofiles (MTrans, FileNames)
subroutine transfer_savematterpower (MTrans, FileNames)
subroutine transfer_sortandindexredshifts (P)
Variables
integer, parameter transfer_kh =1
integer, parameter transfer_cdm =2
integer, parameter transfer_b =3
integer, parameter transfer_g =4
integer, parameter transfer_r =5
integer, parameter transfer_nu = 6
integer, parameter transfer_tot =7
integer, parameter transfer_nonu =8
integer, parameter transfer_tot_de =9
integer, parameter transfer_weyl = 10
integer, parameter transfer_newt_vel_cdm =11
integer, parameter transfer_newt_vel_baryon =12
integer, parameter transfer_vel_baryon_cdm = 13
integer, parameter transfer_max = Transfer_vel_baryon_cdm
character(len=name_tag_len), dimension(transfer_max-1) transfer_name_tags = ['CDM ', 'baryon ', 'photon ', 'nu ', 'mass_nu ', 'total ', 'no_nu ', 'total_de', 'Weyl ', 'v_CDM ', 'v_b ', 'v_b-v_c ']
logical transfer_interp_matterpower = .true.
integer transfer_power_var = Transfer_tot
logical get_growth_sigma8 = .true.
type(mattertransferdata), save mt
Function/Subroutine Documentation
matterpowerdata_free()
subroutine transfer::matterpowerdata_free (type(matterpowerdata) PK_data)
References matterpowerdata_nullify().
Referenced by calculator_camb::cambcalc_getnlandratios(), cambmain::makenonlinearsources(), lrggettheory::transfer_getmatterpowerandnw(), transfer_getmatterpowerd(), transfer_getmatterpowerdata(), transfer_getsigmararray(), transfer_getunsplinednonlinearpower(), and transfer_savematterpower().
matterpowerdata_getsplines()
subroutine transfer::matterpowerdata_getsplines (type(matterpowerdata) PK_data)
References spline().
Referenced by calculator_camb::cambcalc_getnlandratios(), matterpowerdata_load(), matterpowerdata_makenonlinear(), and transfer_getmatterpowerdata().
matterpowerdata_k()
real(dl) function transfer::matterpowerdata_k (type(matterpowerdata) PK, real (dl), intent(in) kh, integer, intent(in) itf)
Referenced by nonlinear::fill_plintab(), nonlinear::nonlinear_getnonlinratios(), transfer_getsigmararray(), and nonlinear::wint().
matterpowerdata_load()
subroutine transfer::matterpowerdata_load (type(matterpowerdata) PK_data, character(len=*) fname)
References matterpowerdata_getsplines().
matterpowerdata_makenonlinear()
subroutine transfer::matterpowerdata_makenonlinear (type(matterpowerdata) PK_data)
References matterpowerdata_getsplines(), and nonlinear_getratios().
Referenced by transfer_savematterpower().
matterpowerdata_nullify()
subroutine transfer::matterpowerdata_nullify (type(matterpowerdata) PK_data)
Referenced by matterpowerdata_free().
transfer_allocate()
subroutine transfer::transfer_allocate (type(mattertransferdata) MTrans)
References get_growth_sigma8, and transfer_max.
Referenced by cambmain::inittransfer().
transfer_free()
subroutine transfer::transfer_free (type(mattertransferdata) MTrans)
References get_growth_sigma8, and transfer_nullify().
Referenced by camb::camb_cleanup(), camb::camb_freecambdata(), and camb::camb_gettransfers().
transfer_get_sigma8()
subroutine transfer::transfer_get_sigma8 (type(mattertransferdata) MTrans, real(dl), intent(in), optional R, integer, intent(in), optional var1, integer, intent(in), optional var2)
References errors::global_error_flag, and transfer_get_sigmar().
transfer_get_sigmar()
subroutine transfer::transfer_get_sigmar (type(mattertransferdata) MTrans, real(dl), intent(in) R, real(dl), dimension(:), intent(out) outvals, integer, intent(in), optional var1, integer, intent(in), optional var2, integer, intent(in), optional power_ix, logical, intent(in), optional root)
References transfer_kh, and transfer_power_var.
Referenced by transfer_get_sigma8(), and transfer_get_sigmas().
transfer_get_sigmas()
subroutine transfer::transfer_get_sigmas (type(mattertransferdata) MTrans, real(dl), intent(in), optional R, integer, intent(in), optional var_delta, integer, intent(in), optional var_v)
References get_growth_sigma8, errors::global_error_flag, transfer_get_sigmar(), transfer_newt_vel_cdm, and transfer_power_var.
Referenced by camb::camb_transferstopowers(), and cambmain::cmbmain().
transfer_getmatterpowerd()
subroutine transfer::transfer_getmatterpowerd (type(mattertransferdata), intent(in) MTrans, real(dl), dimension(npoints), intent(out) outpower, integer, intent(in) itf_PK, integer, intent(in) in, real(dl), intent(in) minkh, real(dl), intent(in) dlnkh, integer, intent(in) npoints, integer, intent(in), optional var1, integer, intent(in), optional var2)
References errors::global_error_flag, matterpowerdata_free(), nonlinear_getratios(), spline(), transfer_getmatterpowerdata(), transfer_kh, and transfer_power_var.
Referenced by handles::cambdata_getmatterpower(), and transfer_getmatterpowers().
transfer_getmatterpowerdata()
subroutine transfer::transfer_getmatterpowerdata (type(mattertransferdata), intent(in) MTrans, type(matterpowerdata) PK_data, integer, intent(in), optional power_ix, integer, intent(in), optional itf_only, integer, intent(in), optional var1, integer, intent(in), optional var2)
References errors::global_error_flag, matterpowerdata_free(), matterpowerdata_getsplines(), transfer_kh, and transfer_power_var.
Referenced by cambmain::makenonlinearsources(), lrggettheory::transfer_getmatterpowerandnw(), transfer_getmatterpowerd(), transfer_getsigmararray(), transfer_getunsplinednonlinearpower(), and transfer_savematterpower().
transfer_getmatterpowers()
subroutine transfer::transfer_getmatterpowers (type(mattertransferdata), intent(in) MTrans, real, dimension(*), intent(out) outpower, integer, intent(in) itf, integer, intent(in) in, real, intent(in) minkh, real, intent(in) dlnkh, integer, intent(in) npoints, integer, intent(in), optional var1, integer, intent(in), optional var2)
References transfer_getmatterpowerd().
Referenced by transfer_savematterpower().
transfer_getsigmararray()
subroutine transfer::transfer_getsigmararray (type(mattertransferdata) MTrans, real(dl), dimension(:), intent(in) R, real(dl), dimension(:), intent(out) sigmaR, integer, intent(in), optional redshift_ix, integer, intent(in), optional var1, integer, intent(in), optional var2, integer, intent(in), optional power_ix)
References matterpowerdata_free(), matterpowerdata_k(), transfer_getmatterpowerdata(), and transfer_kh.
Referenced by calculator_camb::cambcalc_setpkfromcamb().
transfer_getunsplinednonlinearpower()
subroutine transfer::transfer_getunsplinednonlinearpower (type(mattertransferdata), intent(in) M, real(dl), dimension(:,:), intent(inout) PK, integer, intent(in), optional var1, integer, intent(in), optional var2, logical, intent(in), optional hubble_units)
References matterpowerdata_free(), nonlinear_getratios(), transfer_getmatterpowerdata(), and transfer_getunsplinedpower().
Referenced by handles::cambdata_getnonlinearmatterpower().
transfer_getunsplinedpower()
subroutine transfer::transfer_getunsplinedpower (type(mattertransferdata) M, real(dl), dimension(:,:), intent(inout) PK, integer, intent(in), optional var1, integer, intent(in), optional var2, logical, intent(in), optional hubble_units)
References transfer_kh, and transfer_power_var.
Referenced by calculator_camb::cambcalc_setpkfromcamb(), handles::cambdata_getlinearmatterpower(), and transfer_getunsplinednonlinearpower().
transfer_nullify()
subroutine transfer::transfer_nullify (type(mattertransferdata) Mtrans)
Referenced by transfer_free().
transfer_output_sig8()
subroutine transfer::transfer_output_sig8 (type(mattertransferdata), intent(in) MTrans)
References get_growth_sigma8.
transfer_savematterpower()
subroutine transfer::transfer_savematterpower (type(mattertransferdata), intent(in) MTrans, character(len=ini_max_string_len), dimension(*), intent(in) FileNames)
References matterpowerdata_free(), matterpowerdata_makenonlinear(), modeldata::open_file_header(), transfer_getmatterpowerdata(), transfer_getmatterpowers(), transfer_interp_matterpower, and transfer_kh.
transfer_savetofiles()
subroutine transfer::transfer_savetofiles (type(mattertransferdata), intent(in) MTrans, character(len=ini_max_string_len), dimension(*), intent(in) FileNames)
References modeldata::open_file_header(), transfer_kh, transfer_max, and transfer_name_tags.
transfer_setfornonlinearlensing()
subroutine transfer::transfer_setfornonlinearlensing (type(transferparams) P)
Referenced by handles::cambdata_gettransfers().
transfer_sortandindexredshifts()
subroutine transfer::transfer_sortandindexredshifts (type(transferparams) P)
Referenced by handles::cambdata_gettransfers().
Variable Documentation
get_growth_sigma8
logical transfer::get_growth_sigma8 = .true.
Referenced by transfer_allocate(), transfer_free(), transfer_get_sigmas(), and transfer_output_sig8().
mt
type (mattertransferdata), save transfer::mt
Referenced by cambmain::calcscalarsources(), camb::camb_cleanup(), camb::camb_gettransfers(), cambmain::cmbmain(), cambmain::gettransfer(), cambmain::inittransfer(), cambmain::makenonlinearsources(), and cambmain::transferout().
transfer_b
integer, parameter transfer::transfer_b =3
Referenced by gaugeinterface::derivs(), and dtauda().
transfer_cdm
integer, parameter transfer::transfer_cdm =2
Referenced by gaugeinterface::derivs(), and dtauda().
transfer_g
integer, parameter transfer::transfer_g =4
Referenced by gaugeinterface::derivs(), and dtauda().
transfer_interp_matterpower
logical transfer::transfer_interp_matterpower = .true.
Referenced by transfer_savematterpower().
transfer_kh
integer, parameter transfer::transfer_kh =1
Referenced by calculator_camb::cambcalc_setpkfromcamb(), gaugeinterface::derivs(), dtauda(), gaugeinterface::outtransf(), transfer_get_sigmar(), lrggettheory::transfer_getmatterpowerandnw(), transfer_getmatterpowerd(), transfer_getmatterpowerdata(), transfer_getsigmararray(), transfer_getunsplinedpower(), transfer_savematterpower(), and transfer_savetofiles().
transfer_max
integer, parameter transfer::transfer_max = Transfer_vel_baryon_cdm
Referenced by dtauda(), gaugeinterface::outtransf(), transfer_allocate(), lrggettheory::transfer_getmatterpowerandnw(), and transfer_savetofiles().
transfer_name_tags
character(len=name_tag_len), dimension(transfer_max-1) transfer::transfer_name_tags = ['CDM ', 'baryon ', 'photon ', 'nu ', 'mass_nu ', 'total ', 'no_nu ', 'total_de', 'Weyl ', 'v_CDM ', 'v_b ', 'v_b-v_c ']
Referenced by transfer_savetofiles().
transfer_newt_vel_baryon
integer, parameter transfer::transfer_newt_vel_baryon =12
Referenced by gaugeinterface::derivs(), and dtauda().
transfer_newt_vel_cdm
integer, parameter transfer::transfer_newt_vel_cdm =11
Referenced by gaugeinterface::derivs(), dtauda(), and transfer_get_sigmas().
transfer_nonu
integer, parameter transfer::transfer_nonu =8
Referenced by calculator_camb::cambcalc_setpkfromcamb(), gaugeinterface::derivs(), and dtauda().
transfer_nu
integer, parameter transfer::transfer_nu = 6
Referenced by gaugeinterface::derivs(), and dtauda().
transfer_power_var
integer transfer::transfer_power_var = Transfer_tot
Referenced by calculator_camb::cambcalc_setpkfromcamb(), transfer_get_sigmar(), transfer_get_sigmas(), lrggettheory::transfer_getmatterpowerandnw(), transfer_getmatterpowerd(), transfer_getmatterpowerdata(), and transfer_getunsplinedpower().
transfer_r
integer, parameter transfer::transfer_r =5
Referenced by gaugeinterface::derivs(), and dtauda().
transfer_tot
integer, parameter transfer::transfer_tot =7
Referenced by gaugeinterface::derivs(), dtauda(), and lrggettheory::transfer_getmatterpowerandnw().
transfer_tot_de
integer, parameter transfer::transfer_tot_de =9
Referenced by gaugeinterface::derivs(), and dtauda().
transfer_vel_baryon_cdm
integer, parameter transfer::transfer_vel_baryon_cdm = 13
Referenced by gaugeinterface::derivs(), and dtauda().
transfer_weyl
integer, parameter transfer::transfer_weyl = 10
Referenced by calculator_camb::cambcalc_setpkfromcamb(), gaugeinterface::derivs(), and dtauda().