cosmomc_bde_v3p1: powell_constrainedoptimize Module Reference
powell_constrainedoptimize Module Reference
Data Types
type tbobyqa
Functions/Subroutines
real(powell_co_prec) function funkk (this, n, X)
logical function bobyqa (this, N, NPT, X, XL, XU, RHOBEG, RHOEND, IPRINT, MAXFUN)
logical function bobyqb (this, N, NPT, X, XL, XU, RHOBEG, RHOEND, IPRINT, MAXFUN, XBASE, XPT, FVAL, XOPT, GOPT, HQ, PQ, BMAT, ZMAT, NDIM, SL, SU, XNEW, XALT, D, VLAG, W)
subroutine altmov (N, NPT, XPT, XOPT, BMAT, ZMAT, NDIM, SL, SU, KOPT, KNEW, ADELT, XNEW, XALT, ALPHA, CAUCHY, GLAG, HCOL, W)
subroutine prelim (this, N, NPT, X, XL, XU, RHOBEG, IPRINT, MAXFUN, XBASE, XPT, FVAL, GOPT, HQ, PQ, BMAT, ZMAT, NDIM, SL, SU, NF, KOPT)
subroutine rescue (this, N, NPT, XL, XU, IPRINT, MAXFUN, XBASE, XPT, FVAL, XOPT, GOPT, HQ, PQ, BMAT, ZMAT, NDIM, SL, SU, NF, DELTA, KOPT, VLAG, PTSAUX, PTSID, W)
subroutine trsbox (N, NPT, XPT, XOPT, GOPT, HQ, PQ, SL, SU, DELTA, XNEW, D, GNEW, XBDI, S, HS, HRED, DSQ, CRVMIN)
subroutine update (N, NPT, BMAT, ZMAT, NDIM, VLAG, BETA, DENOM, KNEW, W)
Variables
integer, parameter dp = KIND(1.d0)
integer, parameter func_dp = dp
integer, parameter, public powell_co_prec = dp
Function/Subroutine Documentation
altmov()
subroutine powell_constrainedoptimize::altmov (N, NPT, dimension(npt,*) XPT, dimension(*) XOPT, dimension(ndim,*) BMAT, dimension(npt,*) ZMAT, NDIM, dimension(*) SL, dimension(*) SU, KOPT, KNEW, ADELT, dimension(*) XNEW, dimension(*) XALT, ALPHA, CAUCHY, dimension(*) GLAG, dimension(*) HCOL, dimension(*) W) private
Referenced by bobyqb().
bobyqa()
logical function powell_constrainedoptimize::bobyqa (class(tbobyqa) this, integer, intent(in) N, integer, intent(in) NPT, real(dp), dimension(*) X, real(dp), dimension(*) XL, real(dp), dimension(*) XU, RHOBEG, RHOEND, integer, intent(in) IPRINT, integer, intent(in) MAXFUN) private
References bobyqb().
bobyqb()
logical function powell_constrainedoptimize::bobyqb (class(tbobyqa) this, N, NPT, dimension(*) X, dimension(*) XL, dimension(*) XU, RHOBEG, RHOEND, IPRINT, MAXFUN, dimension(*) XBASE, dimension(npt,*) XPT, dimension(*) FVAL, dimension(*) XOPT, dimension(*) GOPT, dimension(*) HQ, dimension(*) PQ, dimension(ndim,*) BMAT, dimension(npt,*) ZMAT, NDIM, dimension(*) SL, dimension(*) SU, dimension(*) XNEW, dimension(*) XALT, dimension(*) D, dimension(*) VLAG, dimension(*) W) private
References altmov(), prelim(), rescue(), trsbox(), and update().
Referenced by bobyqa().
funkk()
real(powell_co_prec) function powell_constrainedoptimize::funkk (class(tbobyqa) this, integer, intent(in) n, real(powell_co_prec), dimension(n) X) private
prelim()
subroutine powell_constrainedoptimize::prelim (class(tbobyqa) this, N, NPT, dimension(*) X, dimension(*) XL, dimension(*) XU, RHOBEG, IPRINT, MAXFUN, dimension(*) XBASE, dimension(npt,*) XPT, dimension(*) FVAL, dimension(*) GOPT, dimension(*) HQ, dimension(*) PQ, dimension(ndim,*) BMAT, dimension(npt,*) ZMAT, NDIM, dimension(*) SL, dimension(*) SU, NF, KOPT) private
Referenced by bobyqb().
rescue()
subroutine powell_constrainedoptimize::rescue (class(tbobyqa) this, N, NPT, dimension(*) XL, dimension(*) XU, IPRINT, MAXFUN, dimension(*) XBASE, dimension(npt,*) XPT, dimension(*) FVAL, dimension(*) XOPT, dimension(*) GOPT, dimension(*) HQ, dimension(*) PQ, dimension(ndim,*) BMAT, dimension(npt,*) ZMAT, NDIM, dimension(*) SL, dimension(*) SU, NF, DELTA, KOPT, dimension(*) VLAG, dimension(2,*) PTSAUX, dimension(*) PTSID, dimension(*) W) private
References update().
Referenced by bobyqb().
trsbox()
subroutine powell_constrainedoptimize::trsbox (N, NPT, dimension(npt,*) XPT, dimension(*) XOPT, dimension(*) GOPT, dimension(*) HQ, dimension(*) PQ, dimension(*) SL, dimension(*) SU, DELTA, dimension(*) XNEW, dimension(*) D, dimension(*) GNEW, dimension(*) XBDI, dimension(*) S, dimension(*) HS, dimension(*) HRED, DSQ, CRVMIN) private
Referenced by bobyqb().
update()
subroutine powell_constrainedoptimize::update (N, NPT, dimension(ndim,*) BMAT, dimension(npt,*) ZMAT, NDIM, dimension(*) VLAG, BETA, DENOM, KNEW, dimension(*) W) private
Referenced by paramgrid.batchjob.dataSet::add(), bobyqb(), and rescue().
Variable Documentation
dp
integer, parameter powell_constrainedoptimize::dp = KIND(1.d0) private
func_dp
integer, parameter powell_constrainedoptimize::func_dp = dp private
powell_co_prec
integer, parameter, public powell_constrainedoptimize::powell_co_prec = dp
Referenced by powell_constrainedoptimize::tbobyqa::bobyqa().