cosmomc_bde_v3p1: bk_planck Module Reference
bk_planck Module Reference
Data Types
type tbandpass
type tbk_planck
Functions/Subroutines
subroutine tbk_planck_readini (this, Ini)
subroutine tbk_planck_read_bandpass (this, fname, Bandpass)
subroutine dustscaling (beta, Tdust, bandpass, nu0, fdust)
subroutine syncscaling (beta, bandpass, nu0, fsync)
subroutine tbk_planck_addforegrounds (this, Cls, DataParams)
Variables
real(mcp), parameter t_cmb = 2.7255_mcp
real(mcp), parameter h = 6.62606957e-34_mcp
real(mcp), parameter kb = 1.3806488e-23_mcp
real(mcp), parameter ghz_kelvin = h/kB*1e9_mcp
Function/Subroutine Documentation
dustscaling()
subroutine bk_planck::dustscaling (real(mcp), intent(in) beta, real(mcp), intent(in) Tdust, type(tbandpass), intent(in) bandpass, real(mcp), intent(in) nu0, real(mcp), intent(out) fdust) private
References ghz_kelvin.
Referenced by tbk_planck_addforegrounds().
syncscaling()
subroutine bk_planck::syncscaling (real(mcp), intent(in) beta, type(tbandpass), intent(in) bandpass, real(mcp), intent(in) nu0, real(mcp), intent(out) fsync) private
Referenced by tbk_planck_addforegrounds().
tbk_planck_addforegrounds()
subroutine bk_planck::tbk_planck_addforegrounds (class(tbk_planck) this, class(tmapcrosspowerspectrum), dimension(:,:), intent(inout), target Cls, real(mcp), dimension(:), intent(in) DataParams) private
References dustscaling(), and syncscaling().
tbk_planck_read_bandpass()
subroutine bk_planck::tbk_planck_read_bandpass (class(tbk_planck) this, character(len=*), intent(in) fname, type(tbandpass), target Bandpass) private
References fileutils::file, ghz_kelvin, and t_cmb.
tbk_planck_readini()
subroutine bk_planck::tbk_planck_readini (class(tbk_planck) this, class(tsettingini) Ini) private
Variable Documentation
ghz_kelvin
real(mcp), parameter bk_planck::ghz_kelvin = h/kB*1e9_mcp private
Referenced by dustscaling(), and tbk_planck_read_bandpass().
h
real(mcp), parameter bk_planck::h = 6.62606957e-34_mcp private
kb
real(mcp), parameter bk_planck::kb = 1.3806488e-23_mcp private
t_cmb
real(mcp), parameter bk_planck::t_cmb = 2.7255_mcp private
Referenced by tbk_planck_read_bandpass().