cosmomc_bde_v3p1: gaugeinterface Module Reference
gaugeinterface Module Reference
Data Types
type evolutionvars
Functions/Subroutines
subroutine gaugeinterface_scalev (EV, y, tau, tauend, tol1, ind, c, w)
integer function next_nu_nq (nq)
recursive subroutine gaugeinterface_evolvescal (EV, tau, y, tauend, tol1, ind, c, w)
subroutine gaugeinterface_evolvetens (EV, tau, y, tauend, tol1, ind, c, w)
real(dl) function deltatimemaxed (a1, a2, tol)
subroutine gaugeinterface_init
subroutine setupscalararrayindices (EV, max_num_eqns)
subroutine copyscalarvariablearray (y, yout, EV, EVout)
subroutine setuptensorarrayindices (EV, maxeq)
subroutine copytensorvariablearray (y, yout, EV, EVout)
subroutine getnumeqns (EV)
subroutine switchtomassivenuapprox (EV, y, nu_i)
subroutine massivenuvarsout (EV, y, yprime, a, grho, gpres, dgrho, dgq, dgpi, gdpi_diff, pidot_sum, clxnu_all)
subroutine nu_integrate_l012 (EV, y, a, nu_i, drhonu, fnu, dpnu, pinu)
subroutine nu_pinudot (EV, y, ydot, a, adotoa, nu_i, pinudot)
real(dl) function nu_pi (EV, y, a, nu_i)
subroutine nu_intvsq (EV, y, a, nu_i, G11, G30)
subroutine massivenuvars (EV, y, a, grho, gpres, dgrho, dgq, wnu_arr)
subroutine output (EV, y, j, tau, sources)
subroutine outputt (EV, yt, n, j, tau, dt, dte, dtb)
subroutine outputv (EV, yv, n, j, tau, dt, dte, dtb)
subroutine initial (EV, y, tau)
subroutine initialt (EV, yt, tau)
subroutine initialv (EV, yv, tau)
subroutine outtransf (EV, y, tau, Arr)
subroutine derivs (EV, n, tau, ay, ayprime)
subroutine derivsv (EV, n, tau, yv, yvprime)
subroutine derivst (EV, n, tau, ayt, aytprime)
Variables
character(len= *), parameter eqns_name = 'gauge_inv'
integer, parameter basic_num_eqns = 5
logical dotensorneutrinos = .true.
logical dolateradtruncation = .true.
logical, parameter second_order_tightcoupling = .true.
real(dl) magnetic = 0._dl
real(dl) vec_sig0 = 1._dl
integer, parameter max_l_evolve = 256
integer, parameter initial_adiabatic =1
integer, parameter initial_iso_cdm =2
integer, parameter initial_iso_baryon =3
integer, parameter initial_iso_neutrino =4
integer, parameter initial_iso_neutrino_vel =5
integer, parameter initial_vector = 0
integer, parameter initial_nummodes = initial_iso_neutrino_vel
real(dl), dimension(max_l_evolve) polfac
real(dl), dimension(max_l_evolve) denl
real(dl), dimension(max_l_evolve) vecfac
real(dl), dimension(max_l_evolve) vecfacpol
real(dl), parameter ep0 =1.0d-2
integer, parameter lmaxnu_high_ktau =4
real(dl) epsw
real(dl), dimension(nqmax0+1, max_nu) nu_tau_notmassless
real(dl), dimension(max_nu) nu_tau_nonrelativistic
real(dl), dimension(max_nu) nu_tau_massive
Function/Subroutine Documentation
copyscalarvariablearray()
subroutine gaugeinterface::copyscalarvariablearray (real(dl), dimension(ev%nvar), intent(in) y, real(dl), dimension(evout%nvar), intent(out) yout, type(evolutionvars) EV, type(evolutionvars) EVout)
References basic_num_eqns, modelparams::cp, modelparams::nu_masses, massivenu::nu_q, lambdageneral::w_lam, and lambdageneral::w_perturb.
Referenced by dtauda(), gaugeinterface_evolvescal(), and switchtomassivenuapprox().
copytensorvariablearray()
subroutine gaugeinterface::copytensorvariablearray (real(dl), dimension(ev%nvart), intent(in) y, real(dl), dimension(evout%nvart), intent(out) yout, type(evolutionvars) EV, type(evolutionvars) EVout)
References modelparams::cp, dotensorneutrinos, and massivenu::nqmax.
Referenced by dtauda(), and gaugeinterface_evolvetens().
deltatimemaxed()
real(dl) function gaugeinterface::deltatimemaxed (real(dl) a1, real(dl) a2, real(dl), optional tol)
References modelparams::deltatime(), and modelparams::tol.
Referenced by dtauda(), and gaugeinterface_init().
derivs()
subroutine gaugeinterface::derivs (type(evolutionvars) EV, integer n, real(dl) tau, real(dl), dimension(n) ay, real(dl), dimension(n) ayprime)
References modelparams::cp, lambdageneral::cs2_lam, modelparams::grhob, modelparams::grhoc, modelparams::grhog, modelparams::grhok, modelparams::grhornomass, modelparams::grhov, massivenuvars(), massivenuvarsout(), modelparams::nu_masses, massivenu::nu_q, second_order_tightcoupling, modelparams::tanfunc(), thermodata::thermo(), transfer::transfer_b, transfer::transfer_cdm, transfer::transfer_g, transfer::transfer_kh, transfer::transfer_newt_vel_baryon, transfer::transfer_newt_vel_cdm, transfer::transfer_nonu, transfer::transfer_nu, transfer::transfer_r, transfer::transfer_tot, transfer::transfer_tot_de, transfer::transfer_vel_baryon_cdm, transfer::transfer_weyl, lambdageneral::w_lam, and lambdageneral::w_perturb.
Referenced by cambmain::calcscalarsources(), dtauda(), gaugeinterface_scalev(), output(), and outtransf().
derivst()
subroutine gaugeinterface::derivst (type(evolutionvars) EV, integer n, real(dl) tau, real(dl), dimension(n), target ayt, real(dl), dimension(n), target aytprime)
References modelparams::cp, dotensorneutrinos, modelparams::grhob, modelparams::grhoc, modelparams::grhog, modelparams::grhok, modelparams::grhormass, modelparams::grhornomass, modelparams::grhov, massivenu::nqmax, modelparams::nu_masses, nu_pi(), massivenu::nu_q, massivenu::nu_rho(), modelparams::tanfunc(), thermodata::thermo(), and lambdageneral::w_lam.
Referenced by dtauda(), gaugeinterface_evolvetens(), and outputt().
derivsv()
subroutine gaugeinterface::derivsv (type(evolutionvars) EV, integer n, real(dl) tau, real(dl), dimension(n), target yv, real(dl), dimension(n), target yvprime)
References denl, ep0, epsw, modelparams::grhob, modelparams::grhoc, modelparams::grhog, modelparams::grhornomass, modelparams::grhov, magnetic, thermodata::thermo(), vecfac, vecfacpol, and lambdageneral::w_lam.
Referenced by cambmain::calcvectorsources(), dtauda(), and outputv().
gaugeinterface_evolvescal()
recursive subroutine gaugeinterface::gaugeinterface_evolvescal (type(evolutionvars) EV, real(dl) tau, real(dl), dimension(ev%nvar) y, real(dl) tauend, real(dl) tol1, integer ind, real(dl), dimension(24) c, real(dl), dimension(ev%nvar,9) w)
References modelparams::accuracyboost, copyscalarvariablearray(), modelparams::cp, thermodata::cs2, dolateradtruncation, gaugeinterface_scalev(), errors::global_error_flag, thermodata::matter_verydom_tau, next_nu_nq(), massivenu::nqmax, nu_tau_nonrelativistic, nu_tau_notmassless, modelparams::nu_trunc, second_order_tightcoupling, setupscalararrayindices(), switchtomassivenuapprox(), modelparams::taurend, and thermodata::thermo().
Referenced by cambmain::calcscalarsources(), dtauda(), and cambmain::gettransfer().
gaugeinterface_evolvetens()
subroutine gaugeinterface::gaugeinterface_evolvetens (type(evolutionvars) EV, real(dl) tau, real(dl), dimension(ev%nvart) y, real(dl) tauend, real(dl) tol1, integer ind, real(dl), dimension(24) c, real(dl), dimension(ev%nvart,9) w)
References copytensorvariablearray(), derivst(), dverk(), setuptensorarrayindices(), and thermodata::thermo().
Referenced by cambmain::calctensorsources().
gaugeinterface_init()
subroutine gaugeinterface::gaugeinterface_init ()
References modelparams::accuracyboost, modelparams::cp, modelparams::deltatime(), deltatimemaxed(), denl, epsw, modelparams::laccuracyboost, max_l_evolve, massivenu::nqmax, modelparams::nu_masses, massivenu::nu_q, nu_tau_massive, nu_tau_nonrelativistic, nu_tau_notmassless, polfac, vecfac, and vecfacpol.
Referenced by cambmain::initvars().
gaugeinterface_scalev()
subroutine gaugeinterface::gaugeinterface_scalev (type(evolutionvars) EV, real(dl), dimension(ev%nvar) y, real(dl) tau, real(dl) tauend, real(dl) tol1, integer ind, real(dl), dimension(24) c, real(dl), dimension(ev%nvar,9) w)
References derivs(), dverk(), errors::error_evolution, and errors::globalerror().
Referenced by dtauda(), and gaugeinterface_evolvescal().
getnumeqns()
subroutine gaugeinterface::getnumeqns (type(evolutionvars) EV)
References modelparams::adotrad, modelparams::cp, dotensorneutrinos, modelparams::highaccuracydefault, modelparams::l0max, modelparams::laccuracyboost, max_l_evolve, massivenu::nqmax, modelparams::nu_best, modelparams::nu_masses, massivenu::nu_q, modelparams::nu_trunc, setupscalararrayindices(), and setuptensorarrayindices().
Referenced by cambmain::dosourcek(), and cambmain::transferout().
initial()
subroutine gaugeinterface::initial (type(evolutionvars) EV, real(dl), dimension(ev%nvar) y, real(dl) tau)
References modelparams::accuracyboost, modelparams::adotrad, modelparams::cp, modelparams::deltatime(), denl, ep0, epsw, modelparams::grhob, modelparams::grhoc, modelparams::grhog, modelparams::grhormass, modelparams::grhornomass, modelparams::highaccuracydefault, initial_adiabatic, initial_nummodes, initial_vector, modelparams::laccuracyboost, modelparams::nu_masses, nu_tau_massive, polfac, second_order_tightcoupling, thermodata::thermo_opacitytotime(), thermodata::tight_tau, lambdageneral::w_lam, and lambdageneral::w_perturb.
Referenced by cambmain::calcscalarsources(), and cambmain::gettransfer().
initialt()
subroutine gaugeinterface::initialt (type(evolutionvars) EV, real(dl), dimension(ev%nvart) yt, real(dl) tau)
References modelparams::adotrad, modelparams::cp, denl, dotensorneutrinos, ep0, epsw, modelparams::grhob, modelparams::grhoc, modelparams::grhog, modelparams::grhormass, modelparams::grhornomass, thermodata::thermo_opacitytotime(), and thermodata::tight_tau.
Referenced by cambmain::calctensorsources().
initialv()
subroutine gaugeinterface::initialv (type(evolutionvars) EV, real(dl), dimension(ev%nvarv) yv, real(dl) tau)
References modelparams::adotrad, modelparams::cp, modelparams::grhob, modelparams::grhoc, modelparams::grhog, modelparams::grhornomass, magnetic, and vec_sig0.
Referenced by cambmain::calcvectorsources().
massivenuvars()
subroutine gaugeinterface::massivenuvars (type(evolutionvars) EV, real(dl), dimension(ev%nvar) y, real(dl) a, real(dl) grho, real(dl) gpres, real(dl) dgrho, real(dl) dgq, real(dl), dimension(max_nu), intent(out), optional wnu_arr)
References modelparams::cp, modelparams::grhormass, massivenu::nu_background(), nu_integrate_l012(), and modelparams::nu_masses.
Referenced by derivs(), and dtauda().
massivenuvarsout()
subroutine gaugeinterface::massivenuvarsout (type(evolutionvars) EV, real(dl), dimension(ev%nvar) y, real(dl), dimension(ev%nvar) yprime, real(dl) a, real(dl), optional grho, real(dl), optional gpres, real(dl), optional dgrho, real(dl), optional dgq, real(dl), optional dgpi, real(dl), optional gdpi_diff, real(dl), optional pidot_sum, real(dl), optional clxnu_all)
References modelparams::cp, modelparams::grhormass, massivenu::nu_background(), massivenu::nu_drho(), nu_integrate_l012(), modelparams::nu_masses, and nu_pinudot().
Referenced by derivs(), dtauda(), and output().
next_nu_nq()
integer function gaugeinterface::next_nu_nq (integer, intent(in) nq)
References massivenu::nqmax, and massivenu::nu_q.
Referenced by dtauda(), and gaugeinterface_evolvescal().
nu_integrate_l012()
subroutine gaugeinterface::nu_integrate_l012 (type(evolutionvars) EV, real(dl), dimension(ev%nvar), intent(in) y, real(dl), intent(in) a, integer, intent(in) nu_i, real(dl), intent(out) drhonu, real(dl), intent(out) fnu, real(dl), intent(out), optional dpnu, real(dl), intent(out), optional pinu)
References massivenu::nqmax, massivenu::nu_int_kernel, modelparams::nu_masses, and massivenu::nu_q.
Referenced by dtauda(), massivenuvars(), massivenuvarsout(), and switchtomassivenuapprox().
nu_intvsq()
subroutine gaugeinterface::nu_intvsq (type(evolutionvars) EV, real(dl), dimension(ev%nvar), intent(in) y, real(dl), intent(in) a, integer, intent(in) nu_i, real(dl), intent(out) G11, real(dl), intent(out) G30)
References massivenu::nqmax, massivenu::nu_int_kernel, modelparams::nu_masses, and massivenu::nu_q.
Referenced by dtauda(), and switchtomassivenuapprox().
nu_pi()
real(dl) function gaugeinterface::nu_pi (type(evolutionvars) EV, real(dl), dimension(ev%nvart), intent(in) y, real(dl), intent(in) a, integer, intent(in) nu_i)
References massivenu::nqmax, massivenu::nu_int_kernel, modelparams::nu_masses, and massivenu::nu_q.
Referenced by derivst(), and dtauda().
nu_pinudot()
subroutine gaugeinterface::nu_pinudot (type(evolutionvars) EV, real(dl), dimension(ev%nvar), intent(in) y, real(dl), dimension(ev%nvar), intent(in) ydot, real(dl), intent(in) a, real(dl), intent(in) adotoa, integer, intent(in) nu_i, real(dl) pinudot)
References massivenu::nqmax, massivenu::nu_int_kernel, modelparams::nu_masses, and massivenu::nu_q.
Referenced by dtauda(), and massivenuvarsout().
output()
subroutine gaugeinterface::output (type(evolutionvars) EV, real(dl), dimension(ev%nvar), target y, integer j, real(dl) tau, real(dl), dimension(ctransscal%numsources) sources)
References modelparams::cp, thermodata::ddvis, derivs(), thermodata::dopac, thermodata::dvis, thermodata::expmmu, modelparams::f_k(), modelparams::grhob, modelparams::grhoc, modelparams::grhog, modelparams::grhok, modelparams::grhornomass, modelparams::grhov, massivenuvarsout(), thermodata::opac, modelparams::rofchi(), second_order_tightcoupling, modelparams::tau_maxvis, thermodata::vis, lambdageneral::w_lam, and lambdageneral::w_perturb.
Referenced by cambmain::calcscalarsources().
outputt()
subroutine gaugeinterface::outputt (type(evolutionvars) EV, real(dl), dimension(n), target yt, integer n, integer j, real(dl) tau, real(dl) dt, real(dl) dte, real(dl) dtb)
References modelparams::cosfunc(), modelparams::cp, thermodata::ddvis, derivst(), thermodata::dopac, thermodata::dvis, thermodata::expmmu, thermodata::opac, modelparams::rofchi(), and thermodata::vis.
Referenced by cambmain::calctensorsources().
outputv()
subroutine gaugeinterface::outputv (type(evolutionvars) EV, real(dl), dimension(n), target yv, integer n, integer j, real(dl) tau, real(dl) dt, real(dl) dte, real(dl) dtb)
References modelparams::cp, derivsv(), thermodata::dvis, thermodata::expmmu, and thermodata::vis.
Referenced by cambmain::calcvectorsources().
outtransf()
subroutine gaugeinterface::outtransf (type(evolutionvars) EV, real(dl), dimension(ev%nvar) y, real(dl), intent(in) tau, real, dimension(:), target Arr)
References derivs(), transfer::transfer_kh, and transfer::transfer_max.
Referenced by cambmain::calcscalarsources(), and cambmain::gettransfer().
setupscalararrayindices()
subroutine gaugeinterface::setupscalararrayindices (type(evolutionvars) EV, integer, intent(out), optional max_num_eqns)
References basic_num_eqns, modelparams::cp, modelparams::laccuracyboost, lmaxnu_high_ktau, massivenu::nqmax, modelparams::nu_masses, nu_tau_nonrelativistic, lambdageneral::w_lam, and lambdageneral::w_perturb.
Referenced by dtauda(), gaugeinterface_evolvescal(), getnumeqns(), and switchtomassivenuapprox().
setuptensorarrayindices()
subroutine gaugeinterface::setuptensorarrayindices (type(evolutionvars) EV, integer, intent(out), optional maxeq)
References modelparams::accuracyboost, modelparams::cp, dotensorneutrinos, massivenu::nqmax, nu_tau_nonrelativistic, and modelparams::tau_maxvis.
Referenced by dtauda(), gaugeinterface_evolvetens(), and getnumeqns().
switchtomassivenuapprox()
subroutine gaugeinterface::switchtomassivenuapprox (type(evolutionvars) EV, real(dl), dimension(ev%nvar) y, integer, intent(in) nu_i)
References copyscalarvariablearray(), massivenu::nu_background(), nu_integrate_l012(), nu_intvsq(), modelparams::nu_masses, and setupscalararrayindices().
Referenced by dtauda(), and gaugeinterface_evolvescal().
Variable Documentation
basic_num_eqns
integer parameter gaugeinterface::basic_num_eqns = 5
Referenced by copyscalarvariablearray(), dtauda(), and setupscalararrayindices().
denl
real(dl), dimension(max_l_evolve) gaugeinterface::denl
Referenced by derivsv(), dtauda(), gaugeinterface_init(), initial(), and initialt().
dolateradtruncation
logical gaugeinterface::dolateradtruncation = .true.
Referenced by dtauda(), and gaugeinterface_evolvescal().
dotensorneutrinos
logical gaugeinterface::dotensorneutrinos = .true.
Referenced by copytensorvariablearray(), derivst(), dtauda(), getnumeqns(), initialt(), and setuptensorarrayindices().
ep0
real(dl), parameter gaugeinterface::ep0 =1.0d-2
Referenced by derivsv(), dtauda(), initial(), and initialt().
epsw
real(dl) gaugeinterface::epsw
Referenced by derivsv(), dtauda(), gaugeinterface_init(), initial(), and initialt().
eqns_name
character(len=*), parameter gaugeinterface::eqns_name = 'gauge_inv'
Referenced by calculator_camb::cambcalc_versiontraceoutput(), and calculator_pico::pico_versiontraceoutput().
initial_adiabatic
integer parameter gaugeinterface::initial_adiabatic =1
Referenced by camb::camb_setdefparams(), dtauda(), and initial().
initial_iso_baryon
integer parameter gaugeinterface::initial_iso_baryon =3
Referenced by dtauda().
initial_iso_cdm
integer parameter gaugeinterface::initial_iso_cdm =2
initial_iso_neutrino
integer parameter gaugeinterface::initial_iso_neutrino =4
Referenced by dtauda().
initial_iso_neutrino_vel
integer parameter gaugeinterface::initial_iso_neutrino_vel =5
Referenced by dtauda().
initial_nummodes
integer parameter gaugeinterface::initial_nummodes = initial_iso_neutrino_vel
Referenced by dtauda(), and initial().
initial_vector
integer parameter gaugeinterface::initial_vector = 0
Referenced by dtauda(), and initial().
lmaxnu_high_ktau
integer parameter gaugeinterface::lmaxnu_high_ktau =4
Referenced by dtauda(), and setupscalararrayindices().
magnetic
real(dl) gaugeinterface::magnetic = 0._dl
Referenced by derivsv(), dtauda(), and initialv().
max_l_evolve
integer parameter gaugeinterface::max_l_evolve = 256
Referenced by dtauda(), gaugeinterface_init(), and getnumeqns().
nu_tau_massive
real(dl), dimension(max_nu) gaugeinterface::nu_tau_massive
Referenced by dtauda(), gaugeinterface_init(), and initial().
nu_tau_nonrelativistic
real(dl), dimension(max_nu) gaugeinterface::nu_tau_nonrelativistic
Referenced by dtauda(), gaugeinterface_evolvescal(), gaugeinterface_init(), setupscalararrayindices(), and setuptensorarrayindices().
nu_tau_notmassless
real(dl), dimension(nqmax0+1,max_nu) gaugeinterface::nu_tau_notmassless
Referenced by dtauda(), gaugeinterface_evolvescal(), and gaugeinterface_init().
polfac
real(dl), dimension(max_l_evolve) gaugeinterface::polfac
Referenced by dtauda(), gaugeinterface_init(), and initial().
second_order_tightcoupling
logical parameter gaugeinterface::second_order_tightcoupling = .true.
Referenced by derivs(), dtauda(), gaugeinterface_evolvescal(), initial(), and output().
vec_sig0
real(dl) gaugeinterface::vec_sig0 = 1._dl
Referenced by dtauda(), and initialv().
vecfac
real(dl), dimension(max_l_evolve) gaugeinterface::vecfac
Referenced by derivsv(), dtauda(), and gaugeinterface_init().
vecfacpol
real(dl), dimension(max_l_evolve) gaugeinterface::vecfacpol
Referenced by derivsv(), dtauda(), and gaugeinterface_init().