cosmomc_bde_v3p1: likelihood_cosmology Module Reference
likelihood_cosmology Module Reference
Data Types
type tcmblikelihood
type tcosmocalclikelihood
type tcosmologylikelihood
Functions/Subroutines
real(mcp) function getloglike (this, Params, Theory, DataParams)
real(mcp) function logliketheory (this, CMB)
real(mcp) function loglikedataparams (this, CMB, DataParams)
real(mcp) function loglike (this, CMB, Theory, DataParams)
subroutine tcosmocalclikelihood_initconfig (this, Config)
subroutine tcmblikelihood_readparams (this, Ini)
Function/Subroutine Documentation
getloglike()
real(mcp) function likelihood_cosmology::getloglike (class(tcosmologylikelihood) this, class(ttheoryparams) Params, class(ttheorypredictions) Theory, real(mcp), dimension(:) DataParams) private
References loglike().
loglike()
real(mcp) function likelihood_cosmology::loglike (class(tcosmologylikelihood) this, class(cmbparams) CMB, class(tcosmotheorypredictions), target Theory, real(mcp), dimension(:) DataParams) private
Referenced by cmblikes::cmblikes_loglike(), getloglike(), loglikedataparams(), logliketheory(), and cmblikelihoods::twmaplikelihood_loglike().
loglikedataparams()
real(mcp) function likelihood_cosmology::loglikedataparams (class(tcosmologylikelihood) this, class(cmbparams) CMB, real(mcp), dimension(:) DataParams) private
References loglike().
logliketheory()
real(mcp) function likelihood_cosmology::logliketheory (class(tcosmologylikelihood) this, class(cmbparams) CMB) private
References loglike().
tcmblikelihood_readparams()
subroutine likelihood_cosmology::tcmblikelihood_readparams (class(tcmblikelihood) this, class(tsettingini) Ini) private
tcosmocalclikelihood_initconfig()
subroutine likelihood_cosmology::tcosmocalclikelihood_initconfig (class(tcosmocalclikelihood) this, class(tgeneralconfig), target Config) private