cosmomc_bde_v3p1: reionization Module Reference
reionization Module Reference
Data Types
type reionizationhistory
type reionizationparams
Functions/Subroutines
real(dl) function reionization_xe (a, tau, xe_recomb)
integer function reionization_timesteps (ReionHist)
subroutine reionization_readparams (Reion, Ini)
subroutine reionization_setparamsforzre (Reion, ReionHist)
subroutine reionization_init (Reion, ReionHist, Yhe, akthom, tau0, FeedbackLevel)
subroutine reionization_setdefparams (Reion)
subroutine reionization_validate (Reion, OK)
real(dl) function reionization_doptdepth_dz (z)
real(dl) function reionization_getoptdepth (Reion, ReionHist)
subroutine reionization_zrefromoptdepth (Reion, ReionHist)
subroutine reionization_setfromoptdepth (Reion, ReionHist)
Variables
character(len= *), parameter reionization_name = 'CAMB_reionization'
real(dl), parameter reionization_deffraction = -1._dl
real(dl) reionization_accuracyboost = 1._dl
real(dl) rionization_zexp = 1.5_dl
logical include_helium_fullreion = .true.
real(dl), parameter reionization_maxz = 50._dl
real(dl), parameter, private reionization_tol = 1d-5
real(dl), external, private dtauda
real(dl), external, private rombint
real(dl), external, private rombint2
type(reionizationparams), pointer, private thisreion
type(reionizationhistory), pointer, private thisreionhist
Function/Subroutine Documentation
reionization_doptdepth_dz()
real(dl) function reionization::reionization_doptdepth_dz (real(dl), intent(in) z)
References dtauda, reionization_xe(), and thisreionhist.
Referenced by reionization_getoptdepth().
reionization_getoptdepth()
real(dl) function reionization::reionization_getoptdepth (type(reionizationparams), target Reion, type(reionizationhistory), target ReionHist)
References reionization_doptdepth_dz(), reionization_maxz, reionization_tol, rombint2, thisreion, and thisreionhist.
Referenced by reionization_init(), and reionization_zrefromoptdepth().
reionization_init()
subroutine reionization::reionization_init (type(reionizationparams), target Reion, type(reionizationhistory), target ReionHist, real(dl), intent(in) Yhe, real(dl), intent(in) akthom, real(dl), intent(in) tau0, integer, intent(in) FeedbackLevel)
References dtauda, constants::mass_ratio_he_h, reionization_deffraction, reionization_getoptdepth(), reionization_setfromoptdepth(), reionization_setparamsforzre(), rombint, thisreion, and thisreionhist.
Referenced by modelparams::cambparams_set().
reionization_readparams()
subroutine reionization::reionization_readparams (type(reionizationparams) Reion, type(tinifile) Ini)
References inifile::ini_read_double_file(), inifile::ini_read_logical_file(), and reionization_deffraction.
reionization_setdefparams()
subroutine reionization::reionization_setdefparams (type(reionizationparams) Reion)
References reionization_deffraction.
Referenced by camb::camb_setdefparams().
reionization_setfromoptdepth()
subroutine reionization::reionization_setfromoptdepth (type(reionizationparams) Reion, type(reionizationhistory) ReionHist)
References dtauda, include_helium_fullreion, reionization_accuracyboost, reionization_zrefromoptdepth(), and thisreionhist.
Referenced by reionization_init().
reionization_setparamsforzre()
subroutine reionization::reionization_setparamsforzre (type(reionizationparams), target Reion, type(reionizationhistory), target ReionHist)
References rionization_zexp.
Referenced by reionization_init(), and reionization_zrefromoptdepth().
reionization_timesteps()
integer function reionization::reionization_timesteps (type(reionizationhistory) ReionHist)
reionization_validate()
subroutine reionization::reionization_validate (type(reionizationparams), intent(in) Reion, logical, intent(inout) OK)
References include_helium_fullreion, reionization_deffraction, and reionization_maxz.
Referenced by camb::camb_validateparams().
reionization_xe()
real(dl) function reionization::reionization_xe (real(dl), intent(in) a, real(dl), intent(in), optional tau, real(dl), intent(in), optional xe_recomb)
References include_helium_fullreion, rionization_zexp, thisreion, and thisreionhist.
Referenced by reionization_doptdepth_dz().
reionization_zrefromoptdepth()
subroutine reionization::reionization_zrefromoptdepth (type(reionizationparams) Reion, type(reionizationhistory) ReionHist)
References reionization_accuracyboost, reionization_getoptdepth(), reionization_maxz, and reionization_setparamsforzre().
Referenced by reionization_setfromoptdepth().
Variable Documentation
dtauda
real(dl), external, private reionization::dtauda private
Referenced by modelparams::deltatime(), modelparams::dsound_da(), modelparams::dsound_da_exact(), modelparams::dtda(), modelparams::hofz(), reionization_doptdepth_dz(), reionization_init(), and reionization_setfromoptdepth().
include_helium_fullreion
logical reionization::include_helium_fullreion = .true.
Referenced by reionization_setfromoptdepth(), reionization_validate(), and reionization_xe().
reionization_accuracyboost
real(dl) reionization::reionization_accuracyboost = 1._dl
Referenced by reionization_setfromoptdepth(), and reionization_zrefromoptdepth().
reionization_deffraction
real(dl), parameter reionization::reionization_deffraction = -1._dl
Referenced by reionization_init(), reionization_readparams(), reionization_setdefparams(), and reionization_validate().
reionization_maxz
real(dl), parameter reionization::reionization_maxz = 50._dl
Referenced by reionization_getoptdepth(), reionization_validate(), and reionization_zrefromoptdepth().
reionization_name
character(len=*), parameter reionization::reionization_name = 'CAMB_reionization'
reionization_tol
real(dl), parameter, private reionization::reionization_tol = 1d-5 private
Referenced by reionization_getoptdepth().
rionization_zexp
real(dl) reionization::rionization_zexp = 1.5_dl
Referenced by reionization_setparamsforzre(), and reionization_xe().
rombint
real(dl), external, private reionization::rombint private
Referenced by modelparams::cosmomctheta(), modelparams::deltaphysicaltimegyr(), modelparams::deltatime(), and reionization_init().
rombint2
real(dl), external, private reionization::rombint2 private
Referenced by reionization_getoptdepth().
thisreion
type(reionizationparams), pointer, private reionization::thisreion private
Referenced by reionization_getoptdepth(), reionization_init(), and reionization_xe().
thisreionhist
type(reionizationhistory), pointer, private reionization::thisreionhist private
Referenced by reionization_doptdepth_dz(), reionization_getoptdepth(), reionization_init(), reionization_setfromoptdepth(), and reionization_xe().