cosmomc_bde_v3p1: calculator_pico Module Reference
calculator_pico Module Reference
Data Types
type pico_calculator
Functions/Subroutines
subroutine pico_cmbtocamb (this, CMB, P)
subroutine pico_getnewtransferdata (this, CMB, Info, Theory, error)
subroutine pico_getoutputarray (Theory, i, j, name)
subroutine pico_getnewpowerdata (this, CMB, Info, Theory, error)
subroutine pico_gettheoryforimportance (this, CMB, Theory, error)
subroutine pico_versiontraceoutput (this, ReadValues)
subroutine pico_readparams (this, Ini)
Function/Subroutine Documentation
pico_cmbtocamb()
subroutine calculator_pico::pico_cmbtocamb (class(pico_calculator) this, class(cmbparams) CMB, type(cambparams) P) private
References cosmologytypes::cosmosettings.
pico_getnewpowerdata()
subroutine calculator_pico::pico_getnewpowerdata (class(pico_calculator) this, class(cmbparams) CMB, class(ttheoryintermediatecache), pointer Info, class(tcosmotheorypredictions) Theory, integer error) private
References modeldata::c_e, modeldata::c_temp, modelparams::cambparams_set(), modelparams::cosmomctheta(), cosmologytypes::cosmosettings, modeldata::ct_b, modeldata::ct_cross, settings::feedback, and pico_getoutputarray().
pico_getnewtransferdata()
subroutine calculator_pico::pico_getnewtransferdata (class(pico_calculator) this, class(cmbparams) CMB, class(ttheoryintermediatecache), pointer Info, class(tcosmotheorypredictions) Theory, integer error) private
pico_getoutputarray()
subroutine calculator_pico::pico_getoutputarray (class(tcosmotheorypredictions) Theory, integer i, integer j, character(len=*) name) private
References cosmologytypes::cosmosettings.
Referenced by pico_getnewpowerdata().
pico_gettheoryforimportance()
subroutine calculator_pico::pico_gettheoryforimportance (class(pico_calculator) this, class(cmbparams) CMB, class(tcosmotheorypredictions) Theory, integer error)
pico_readparams()
subroutine calculator_pico::pico_readparams (class(pico_calculator) this, class(tsettingini) Ini)
pico_versiontraceoutput()
subroutine calculator_pico::pico_versiontraceoutput (class(pico_calculator) this, class(tnamevaluelist) ReadValues) private
References gaugeinterface::eqns_name.