cosmomc_bde_v3p1: makeTables Namespace Reference
makeTables Namespace Reference
Functions
def texEscapeText (string)
def getTableLines (content, referenceDataJobItem=None)
def paramResultTable (jobItem, deltaChisqJobItem=None, referenceDataJobItem=None)
def compareTable (jobItems, titles=None)
def dataIndex (jobItem)
Variables
Opts
help
type
int
default
action
nargs
batch
args
blockEndParams
paramList
formatter = planckStyle.planckStyleTableFormatter()
items = Opts.sortedParamtagDict(chainExist=not args.bestfitonly)
list limits = [1, 2, 3]
delta_chisq_paramtag
baseJobItems = dict()
int isBase = 0
referenceJobItem = copy.deepcopy(jobItem)
paramNameFile
loc = os.path.split(args.latex_filename)[0]
limit
outfile = args.latex_filename
list lines = []
string paramText = 'Baseline model'
string section = '\\newpage\\section{ ' + paramText + '}'
compares = Opts.filterForDataCompare(parambatch, args.compare)
list theseItems
referenceDataJobItem = None
bestfit
list refItems = []
normed_without
list origCompare = [item for item in theseItems if args.changes_replacing[0] in item.data_set.names]
def tableLines = paramResultTable(jobItem, referenceJobItem, referenceDataJobItem)
outdir
outname
root = os.path.splitext(outfile)[0]
list delext = ['aux', 'log', 'out', 'toc']
Function Documentation
compareTable()
def makeTables.compareTable (jobItems, titles = None)
dataIndex()
def makeTables.dataIndex (jobItem)
getTableLines()
def makeTables.getTableLines (content, referenceDataJobItem = None)
Referenced by paramResultTable().
paramResultTable()
def makeTables.paramResultTable (jobItem, deltaChisqJobItem = None, referenceDataJobItem = None)
References getTableLines(), stringutils.join(), and texEscapeText().
texEscapeText()
def makeTables.texEscapeText (string)
Referenced by paramResultTable().
Variable Documentation
action
makeTables.action
args
makeTables.args
baseJobItems
makeTables.baseJobItems = dict()
batch
makeTables.batch
bestfit
makeTables.bestfit
blockEndParams
makeTables.blockEndParams
compares
makeTables.compares = Opts.filterForDataCompare(parambatch, args.compare)
default
makeTables.default
delext
list makeTables.delext = ['aux', 'log', 'out', 'toc']
delta_chisq_paramtag
makeTables.delta_chisq_paramtag
formatter
makeTables.formatter = planckStyle.planckStyleTableFormatter()
help
makeTables.help
int
makeTables.int
isBase
int makeTables.isBase = 0
items
makeTables.items = Opts.sortedParamtagDict(chainExist=not args.bestfitonly)
limit
makeTables.limit
limits
list makeTables.limits = [1, 2, 3]
lines
list makeTables.lines = []
loc
makeTables.loc = os.path.split(args.latex_filename)[0]
nargs
makeTables.nargs
normed_without
makeTables.normed_without
Opts
makeTables.Opts
Initial value:
 =  batchjob_args.batchArgs('Make pdf tables from latex generated from getdist outputs', importance=True,
                               converge=True)
origCompare
list makeTables.origCompare = [item for item in theseItems if args.changes_replacing[0] in item.data_set.names]
outdir
makeTables.outdir
outfile
makeTables.outfile = args.latex_filename
outname
makeTables.outname
paramList
makeTables.paramList
paramNameFile
makeTables.paramNameFile
paramText
def makeTables.paramText = 'Baseline model'
referenceDataJobItem
makeTables.referenceDataJobItem = None
referenceJobItem
makeTables.referenceJobItem = copy.deepcopy(jobItem)
refItems
list makeTables.refItems = []
root
makeTables.root = os.path.splitext(outfile)[0]
section
string makeTables.section = '\\newpage\\section{ ' + paramText + '}'
tableLines
def makeTables.tableLines = paramResultTable(jobItem, referenceJobItem, referenceDataJobItem)
theseItems
list makeTables.theseItems
Initial value:
 =  [jobItem for jobItem in parambatch
                           if (os.path.exists(jobItem.distPath) or args.bestfitonly) and (
                     args.converge == 0 or jobItem.hasConvergeBetterThan(args.converge))]
type
makeTables.type