cosmomc_bde_v3p1: calculator_camb Module Reference
calculator_camb Module Reference
Data Types
type camb_calculator
type cambtransfercache
Functions/Subroutines
subroutine cambcalc_cmbtocamb (this, CMB, P)
subroutine cambcalc_setderived (this, Theory)
subroutine cambcalc_setparamsforbackground (this, CMB)
subroutine cambcalc_setbackgroundtheorydata (this, CMB, Theory, error)
subroutine cambcalc_getnewtransferdata (this, CMB, Info, Theory, error)
subroutine cambcalc_getnewpowerdata (this, CMB, Info, Theory, error)
subroutine cambcalc_gettheoryforimportance (this, CMB, Theory, error)
subroutine cambcalc_setpowersfromcamb (this, CMB, Theory)
subroutine cambcalc_setpkfromcamb (this, M, Theory, error)
subroutine cambcalc_getnlandratios (this, M, Theory, Ratios, error)
subroutine cambcalc_initcamb (this, CMB, error, DoReion)
real(mcp) function cambcalc_getopticaldepth (this, CMB)
real(mcp) function cambcalc_getzrefromtau (this, CMB, tau)
real(mcp) function cambcalc_cmbtotheta (this, CMB)
real(mcp) function cambcalc_bao_d_v (this, z)
real(mcp) function cambcalc_angulardiameterdistance (this, z)
real(mcp) function cambcalc_comovingradialdistance (this, z)
real(mcp) function cambcalc_angulardiameterdistance2 (this, z1, z2)
real(mcp) function cambcalc_luminositydistance (this, z)
real(mcp) function cambcalc_hofz (this, z)
subroutine cambcalc_initcambparams (this, P)
subroutine cambcalc_setcambinitpower (this, P, CMB, ix)
subroutine cambcalc_readparams (this, Ini)
subroutine cambcalc_initforlikelihoods (this)
subroutine cambcalc_versiontraceoutput (this, ReadValues)
subroutine loadfiducialhighltemplate (this)
subroutine cambtransfercache_clear (Info)
Function/Subroutine Documentation
cambcalc_angulardiameterdistance()
real(mcp) function calculator_camb::cambcalc_angulardiameterdistance (class(camb_calculator) this, real(mcp), intent(in) z)
cambcalc_angulardiameterdistance2()
real(mcp) function calculator_camb::cambcalc_angulardiameterdistance2 (class(camb_calculator) this, real(mcp), intent(in) z1, real(mcp), intent(in) z2)
cambcalc_bao_d_v()
real(mcp) function calculator_camb::cambcalc_bao_d_v (class(camb_calculator) this, real(mcp), intent(in) z)
cambcalc_cmbtocamb()
subroutine calculator_camb::cambcalc_cmbtocamb (class(camb_calculator) this, class(cmbparams) CMB, type(cambparams) P) private
References cambmain::alens, lensing::alens_fiducial, camb::camb_setneutrinohierarchy(), cosmologytypes::cosmosettings, constants::default_nnu, constants::delta_mnu21, constants::delta_mnu31, constants::mnu_min_normal, massivenu::sum_mnu_for_m1(), lambdageneral::w_lam, and lambdageneral::wa_ppf.
cambcalc_cmbtotheta()
real(mcp) function calculator_camb::cambcalc_cmbtotheta (class(camb_calculator) this, class(cmbparams) CMB) private
References modelparams::cosmomctheta().
cambcalc_comovingradialdistance()
real(mcp) function calculator_camb::cambcalc_comovingradialdistance (class(camb_calculator) this, real(mcp), intent(in) z)
cambcalc_getnewpowerdata()
subroutine calculator_camb::cambcalc_getnewpowerdata (class(camb_calculator) this, class(cmbparams) CMB, class(ttheoryintermediatecache), pointer Info, class(tcosmotheorypredictions) Theory, integer error)
References camb::camb_transferstopowers(), cosmologytypes::cosmosettings, and errors::global_error_flag.
cambcalc_getnewtransferdata()
subroutine calculator_camb::cambcalc_getnewtransferdata (class(camb_calculator) this, class(cmbparams) CMB, class(ttheoryintermediatecache), pointer Info, class(tcosmotheorypredictions) Theory, integer error)
References camb::camb_gettransfers(), camb::camb_initcambdata(), settings::feedback, errors::global_error_message, settings::logfile, settings::num_threads, settings::stop_on_error, and settings::timer().
cambcalc_getnlandratios()
subroutine calculator_camb::cambcalc_getnlandratios (class(camb_calculator) this, type(mattertransferdata) M, class(tcosmotheorypredictions) Theory, real(mcp), dimension(:,:), intent(out), allocatable Ratios, integer error)
References transfer::matterpowerdata_free(), transfer::matterpowerdata_getsplines(), and nonlinear_getratios().
cambcalc_getopticaldepth()
real(mcp) function calculator_camb::cambcalc_getopticaldepth (class(camb_calculator) this, class(cmbparams) CMB) private
cambcalc_gettheoryforimportance()
subroutine calculator_camb::cambcalc_gettheoryforimportance (class(camb_calculator) this, class(cmbparams) CMB, class(tcosmotheorypredictions) Theory, integer error) private
References camb::camb_gettransfers(), camb::camb_initcambdata(), camb::camb_transferstopowers(), cosmologytypes::cosmosettings, settings::feedback, errors::global_error_flag, settings::num_threads, modelparams::threadnum, and settings::timer().
cambcalc_getzrefromtau()
real(mcp) function calculator_camb::cambcalc_getzrefromtau (class(camb_calculator) this, class(cmbparams) CMB, real(mcp), intent(in) tau) private
cambcalc_hofz()
real(mcp) function calculator_camb::cambcalc_hofz (class(camb_calculator) this, real(mcp), intent(in) z)
cambcalc_initcamb()
subroutine calculator_camb::cambcalc_initcamb (class(camb_calculator) this, class(cmbparams), intent(in) CMB, integer error, logical, intent(in), optional DoReion)
cambcalc_initcambparams()
subroutine calculator_camb::cambcalc_initcambparams (class(camb_calculator) this, type(cambparams) P)
References modelparams::accuracyboost, modelparams::backgroundoutputs, modelparams::highaccuracydefault, modelparams::laccuracyboost, lensing::lensing_includes_tensors, modelparams::lsampleboost, modelparams::max_transfer_redshifts, modelparams::nonlinear_both, modelparams::nonlinear_lens, modelparams::nonlinear_pk, modelparams::outnone, and modelparams::threadnum.
cambcalc_initforlikelihoods()
subroutine calculator_camb::cambcalc_initforlikelihoods (class(camb_calculator) this)
cambcalc_luminositydistance()
real(mcp) function calculator_camb::cambcalc_luminositydistance (class(camb_calculator) this, real(mcp), intent(in) z)
cambcalc_readparams()
subroutine calculator_camb::cambcalc_readparams (class(camb_calculator) this, class(tsettingini) Ini) private
References nonlinear::halofit_default, and nonlinear::halofit_version.
cambcalc_setbackgroundtheorydata()
subroutine calculator_camb::cambcalc_setbackgroundtheorydata (class(camb_calculator) this, class(cmbparams) CMB, class(tcosmotheorypredictions) Theory, integer error)
References errors::global_error_flag, and cambmain::initvars().
cambcalc_setcambinitpower()
subroutine calculator_camb::cambcalc_setcambinitpower (class(camb_calculator) this, type(cambparams) P, class(cmbparams) CMB, integer, intent(in) ix)
cambcalc_setderived()
subroutine calculator_camb::cambcalc_setderived (class(camb_calculator) this, class(tcosmotheorypredictions) Theory)
References settings::const_c, and cosmologytypes::max_derived_parameters.
cambcalc_setparamsforbackground()
subroutine calculator_camb::cambcalc_setparamsforbackground (class(camb_calculator) this, class(cmbparams) CMB) private
cambcalc_setpkfromcamb()
subroutine calculator_camb::cambcalc_setpkfromcamb (class(camb_calculator) this, type(mattertransferdata) M, class(tcosmotheorypredictions) Theory, integer error)
References transfer::transfer_getsigmararray(), transfer::transfer_getunsplinedpower(), transfer::transfer_kh, transfer::transfer_nonu, transfer::transfer_power_var, and transfer::transfer_weyl.
cambcalc_setpowersfromcamb()
subroutine calculator_camb::cambcalc_setpowersfromcamb (class(camb_calculator) this, class(cmbparams) CMB, class(tcosmotheorypredictions), target Theory)
References cosmologytypes::aphiphi_index, modeldata::c_cross, modeldata::c_e, modeldata::c_temp, modeldata::cl_lensed, cosmologytypes::cl_phi, modeldata::cl_scalar, modeldata::cl_tensor, cosmologytypes::cosmosettings, modeldata::ct_b, and modeldata::ct_cross.
cambcalc_versiontraceoutput()
subroutine calculator_camb::cambcalc_versiontraceoutput (class(camb_calculator) this, class(tnamevaluelist) ReadValues) private
References gaugeinterface::eqns_name.
cambtransfercache_clear()
subroutine calculator_camb::cambtransfercache_clear (class(cambtransfercache) Info) private
loadfiducialhighltemplate()
subroutine calculator_camb::loadfiducialhighltemplate (class(camb_calculator) this)