cosmomc_bde_v3p1: objectlists Module Reference
objectlists Module Reference
Data Types
type object_array_pointer
type object_pointer
type tintegerarraylist
type tobjectlist
type townedintrinsiclist
type trealarraylist
type trealcomparelist
type treallist
type tsaveloadstateobject
type tstringlist
Functions/Subroutines
subroutine loadstate (this, F)
subroutine savestate (this, F)
subroutine clear (this, itemsOnly)
subroutine finalize (this)
subroutine error (this, msg)
subroutine additem (this, C, Object)
subroutine additempointer (this, C, Object)
subroutine addcopy (this, C, Object)
subroutine assignpointers (this, L2, ixmin, ixmax)
integer function deltasize (this)
subroutine setcapacity (this, C)
subroutine freeitem (this, i)
subroutine deleteitem (this, i)
subroutine deleterange (this, i1, i2)
subroutine addarray (this, P)
subroutine checkindex (this, i)
class(*) function, dimension(:), pointer arrayitem (this, i)
class(*) function, pointer arrayitemindex (this, i, j)
class(*) function, pointer tobjectlist_object (this, i)
subroutine savebinary (this, fid)
subroutine readbinary (this, fid)
subroutine thin (this, i)
subroutine swap (this, i, j)
recursive subroutine quicksortarr (this, Lin, R, index)
subroutine sortarr (this, index)
recursive subroutine quicksort (this, Lin, R)
subroutine sort (this)
integer function compare (this, R1, R2)
subroutine removeduplicates (this)
subroutine tobjectlist_savestate (this, F)
subroutine tobjectlist_loadstate (this, F)
subroutine townedintrinsiclist_loadstate (this, F)
subroutine townedintrinsiclist_savestate (this, F)
subroutine townedintrinsiclist_additem (this, C, Object)
integer function comparereal (this, R1, R2)
real(list_prec) function treallist_item (this, i)
subroutine treallist_addarrayitems (this, A)
real(kind=list_prec) function, dimension(this%count) treallist_asarray (this)
real(list_prec) function, dimension(:), pointer trealarraylist_item (this, i)
real(list_prec) function trealarraylist_value (this, i, j)
integer function, dimension(:), pointer tintegerarraylist_item (this, i)
integer function tintegerarraylist_value (this, i, j)
character(len=:) function, pointer tstringlist_item (this, i)
character(len=:) function, pointer tstringlist_valueof (this, key)
subroutine tstringlist_setfromstring (this, S, valid_chars_in)
subroutine tstringlist_readcolumnsgetarray (this, filename, array)
integer function tstringlist_indexof (this, S)
character function tstringlist_charat (this, i, j)
integer function tstringlist_compare (this, R1, R2)
subroutine writeitems (this, unit)
subroutine additems (this, List, nodups)
subroutine tstringlist_addfromfile (this, fname, nodups)
Variables
integer, parameter, public list_prec = Kind(1.0)
Function/Subroutine Documentation
addarray()
subroutine objectlists::addarray (class (tobjectlist) this, class(*), dimension(:), intent(in), target P) private
Referenced by objectlists::tobjectlist::add().
addcopy()
subroutine objectlists::addcopy (class(tobjectlist) this, class(*), intent(in) C, class(*), intent(in), optional Object) private
additem()
subroutine objectlists::additem (class(tobjectlist) this, class(*), intent(in), target C, class(*), intent(in), optional, target Object) private
Referenced by objectlists::tobjectlist::add().
additempointer()
subroutine objectlists::additempointer (class(tobjectlist) this, class(*), intent(in), pointer C, class(*), intent(in), optional, pointer Object) private
additems()
subroutine objectlists::additems (class(tstringlist) this, class(tstringlist) List, logical, intent(in) nodups) private
arrayitem()
class(*) function, dimension(:), pointer objectlists::arrayitem (class(tobjectlist) this, integer, intent(in) i) private
arrayitemindex()
class(*) function, pointer objectlists::arrayitemindex (class(tobjectlist) this, integer, intent(in) i, integer, intent(in) j) private
assignpointers()
subroutine objectlists::assignpointers (class(tobjectlist) this, class(tobjectlist) L2, integer, intent(in), optional ixmin, integer, intent(in), optional ixmax) private
checkindex()
subroutine objectlists::checkindex (class(tobjectlist) this, integer, intent(in) i) private
clear()
subroutine objectlists::clear (class(tobjectlist) this, logical, intent(in), optional itemsOnly) private
Referenced by getdist.gui.mainwindow.MainWindow::_readGridChains(), getdist.gui.mainwindow.MainWindow::_updateComboBoxColor(), getdist.gui.mainwindow.MainWindow::_updateComboBoxRootname(), getdist.gui.mainwindow.MainWindow::clearScript(), and getdist.gui.mainwindow.MainWindow::setParamTag().
compare()
integer function objectlists::compare (class(tobjectlist) this, class(*) R1, class(*) R2) private
comparereal()
integer function objectlists::comparereal (class(trealcomparelist) this, class(*) R1, class(*) R2) private
deleteitem()
subroutine objectlists::deleteitem (class(tobjectlist) this, integer, intent(in) i) private
deleterange()
subroutine objectlists::deleterange (class(tobjectlist) this, integer, intent(in) i1, integer, intent(in) i2) private
deltasize()
integer function objectlists::deltasize (class(tobjectlist) this) private
error()
subroutine objectlists::error (class(tobjectlist) this, character(len=*), intent(in) msg) private
Referenced by samples::gelmanrubinevalues().
finalize()
subroutine objectlists::finalize (type(tobjectlist) this) private
Referenced by objectlists::tobjectlist::finalize().
freeitem()
subroutine objectlists::freeitem (class(tobjectlist) this, integer, intent(in) i) private
loadstate()
subroutine objectlists::loadstate (class(tsaveloadstateobject) this, class(tfilestream) F) private
quicksort()
recursive subroutine objectlists::quicksort (class(tobjectlist) this, integer, intent(in) Lin, integer, intent(in) R) private
quicksortarr()
recursive subroutine objectlists::quicksortarr (class(tobjectlist) this, integer, intent(in) Lin, integer, intent(in) R, integer, intent(in) index) private
readbinary()
subroutine objectlists::readbinary (class(tobjectlist) this, integer, intent(in) fid) private
removeduplicates()
subroutine objectlists::removeduplicates (class(tobjectlist) this) private
savebinary()
subroutine objectlists::savebinary (class(tobjectlist) this, integer, intent(in) fid) private
savestate()
subroutine objectlists::savestate (class(tsaveloadstateobject) this, class(tfilestream) F) private
setcapacity()
subroutine objectlists::setcapacity (class(tobjectlist) this, integer C) private
sort()
subroutine objectlists::sort (class(tobjectlist) this) private
sortarr()
subroutine objectlists::sortarr (class(tobjectlist) this, integer, intent(in) index) private
swap()
subroutine objectlists::swap (class(tobjectlist) this, integer, intent(in) i, integer, intent(in) j) private
thin()
subroutine objectlists::thin (class(tobjectlist) this, integer, intent(in) i) private
tintegerarraylist_item()
integer function, dimension(:), pointer objectlists::tintegerarraylist_item (class(tintegerarraylist) this, integer, intent(in) i) private
tintegerarraylist_value()
integer function objectlists::tintegerarraylist_value (class(tintegerarraylist) this, integer, intent(in) i, integer, intent(in) j) private
tobjectlist_loadstate()
subroutine objectlists::tobjectlist_loadstate (class(tobjectlist) this, class(tfilestream) F) private
tobjectlist_object()
class(*) function, pointer objectlists::tobjectlist_object (class(tobjectlist) this, integer, intent(in) i) private
tobjectlist_savestate()
subroutine objectlists::tobjectlist_savestate (class(tobjectlist) this, class(tfilestream) F) private
townedintrinsiclist_additem()
subroutine objectlists::townedintrinsiclist_additem (class(townedintrinsiclist) this, class(*), intent(in), target C, class(*), intent(in), optional, target Object) private
townedintrinsiclist_loadstate()
subroutine objectlists::townedintrinsiclist_loadstate (class(townedintrinsiclist) this, class(tfilestream) F) private
townedintrinsiclist_savestate()
subroutine objectlists::townedintrinsiclist_savestate (class(townedintrinsiclist) this, class(tfilestream) F) private
trealarraylist_item()
real(list_prec) function, dimension(:), pointer objectlists::trealarraylist_item (class(trealarraylist) this, integer, intent(in) i) private
trealarraylist_value()
real(list_prec) function objectlists::trealarraylist_value (class(trealarraylist) this, integer, intent(in) i, integer, intent(in) j) private
treallist_addarrayitems()
subroutine objectlists::treallist_addarrayitems (class(treallist) this, real(kind=list_prec), dimension(:), intent(in) A) private
treallist_asarray()
real(kind=list_prec) function, dimension(this%count) objectlists::treallist_asarray (class(treallist) this) private
treallist_item()
real(list_prec) function objectlists::treallist_item (class(treallist) this, integer, intent(in) i) private
Referenced by objectlists::treallist::item().
tstringlist_addfromfile()
subroutine objectlists::tstringlist_addfromfile (class(tstringlist) this, character(len=*), intent(in) fname, logical, intent(in) nodups) private
tstringlist_charat()
character function objectlists::tstringlist_charat (class(tstringlist) this, integer, intent(in) i, integer, intent(in) j) private
tstringlist_compare()
integer function objectlists::tstringlist_compare (class(tstringlist) this, class(*) R1, class(*) R2) private
tstringlist_indexof()
integer function objectlists::tstringlist_indexof (class(tstringlist) this, character(len=*), intent(in) S) private
tstringlist_item()
character(len=:) function, pointer objectlists::tstringlist_item (class(tstringlist) this, integer, intent(in) i) private
tstringlist_readcolumnsgetarray()
subroutine objectlists::tstringlist_readcolumnsgetarray (class(tstringlist) this, character(len=*), intent(in) filename, real(list_prec), dimension(:,:), intent(out), allocatable array) private
References fileutils::file.
tstringlist_setfromstring()
subroutine objectlists::tstringlist_setfromstring (class(tstringlist) this, character(len=*), intent(in) S, character(len=*), intent(in), optional valid_chars_in) private
tstringlist_valueof()
character(len=:) function, pointer objectlists::tstringlist_valueof (class(tstringlist) this, character(len=*), intent(in) key) private
writeitems()
subroutine objectlists::writeitems (class(tstringlist) this, integer, intent(in), optional unit) private
Variable Documentation
list_prec
integer parameter public objectlists::list_prec = Kind(1.0)
Referenced by objectlists::tstringlist::item().