cosmomc_bde_v3p1: settings Module Reference
settings Module Reference
Data Types
type tnamekeyinifile
type tsettingini
Functions/Subroutines
subroutine initializeglobalsettingdefaults
subroutine dostop (S, abort)
subroutine tsettingini_failstop (this)
character(len=:) function, allocatable tsettingini_replacedirs (this, inname, ADir)
character(len=:) function, allocatable tsettingini_readrelativefilename (this, key, ADir, NotFoundFail)
character(len=:) function, allocatable tsettingini_readfilename (this, key, ADir, NotFoundFail, relative)
subroutine tsettingini_tagvaluesforname (this, name, OutList, filename)
subroutine tsettingini_settingvaluesfortagname (this, name, tag, OutList, filename)
character(len=:) function, allocatable tnamekeyinifile_namedkey (this, Key, Name)
subroutine checkparamchangef (F)
subroutine checkparamchange
subroutine timer (Msg, start)
subroutine doabort (S)
Variables
integer, parameter mcp = KIND(1.0)
integer, parameter mpi_real_mcp = MPI_REAL
integer, parameter time_dp = KIND(1.d0)
double precision, parameter pi =3.14159265358979323846264338328d0
double precision, parameter twopi =2*pi
double precision, parameter fourpi =4*pi
double precision, parameter root2 = 1.41421356237309504880168872421d0
double precision, parameter sqrt2 = root2
double precision, parameter log2 = 0.693147180559945309417232121458d0
real, parameter pi_r = 3.141592653
real, parameter twopi_r = 2*pi_r
real, parameter fourpi_r = twopi_r*2
real(mcp), parameter const_c = 2.99792458e8_mcp
logical use_fast_slow = .false.
character(len= *), parameter cosmomc_version = 'Nov2016'
character(len=:), allocatable chisq_label
real(mcp) accuracylevel = 1
logical flush_write = .true.
logical new_chains = .true.
integer, parameter max_likelihood_functions = 50
integer, parameter max_data_params = 200
integer, parameter max_theory_params = 50
integer, parameter max_num_params = max_theory_params + max_data_params
integer, parameter sampling_metropolis = 1
integer, parameter sampling_slice = 2
integer, parameter sampling_fastslice =3
integer, parameter sampling_slowgrid = 4
integer, parameter sampling_multicanonical = 5
integer, parameter sampling_wang_landau = 6
integer, parameter sampling_fast_dragging = 7
integer sampling_method = sampling_metropolis
real(mcp) dragging_steps = 3._mcp
logical generic_mcmc = .false.
character(len=:), allocatable datadir
character(len=:), allocatable localdir
type(tsettingini), save customparams
logical stop_on_error = .true.
integer num_theory_params
integer index_data
integer index_semislow =-1
integer, dimension(:), allocatable params_used
integer num_params
integer num_params_used
integer num_data_params
integer num_threads = 0
integer instance = 0
integer mpichains = 1
integer mpirank = 0
real(time_dp) mpirun_start_time
logical checkpoint = .false.
integer output_lines = 0
type(ttextfile), save chainoutfile = TTextFile(RealFormat='(*(E16.7))')
type(ttextfile), save logfile
integer feedback = 0
real(mcp), parameter logzero = 1e30_mcp
character(len=1024) filechangeini = ''
character(len=1024) filechangeiniall = ''
character(len=:), allocatable baseroot
character(len=:), allocatable rootname
integer, parameter stdout = output_unit
Function/Subroutine Documentation
checkparamchange()
subroutine settings::checkparamchange ()
References checkparamchangef(), filechangeini, and filechangeiniall.
checkparamchangef()
subroutine settings::checkparamchangef (character(len=*), intent(in) F)
References feedback, fileutils::file, filechangeini, mpiutils::mpistop(), and num_threads.
Referenced by checkparamchange().
doabort()
subroutine settings::doabort (character(len=*), intent(in), optional S)
Referenced by estcovmatmodule::gethess(), estcovmatmodule::placegrid(), and baseparameters::tbaseparameters_paramerror().
dostop()
subroutine settings::dostop (character(len=*), intent(in), optional S, logical, intent(in), optional abort)
References chainoutfile, feedback, mpirank, and mpirun_start_time.
initializeglobalsettingdefaults()
subroutine settings::initializeglobalsettingdefaults ()
References chisq_label, datadir, and localdir.
timer()
subroutine settings::timer (character(len=*), intent(in), optional Msg, real(time_dp), optional start)
References mpiutils::timertime().
Referenced by calculator_camb::cambcalc_getnewtransferdata(), and calculator_camb::cambcalc_gettheoryforimportance().
tnamekeyinifile_namedkey()
character(len=:) function, allocatable settings::tnamekeyinifile_namedkey (class(tnamekeyinifile) this, character(len=*), intent(in) Key, character(len=*), intent(in) Name)
tsettingini_failstop()
subroutine settings::tsettingini_failstop (class(tsettingini) this)
References mpiutils::mpistop().
tsettingini_readfilename()
character(len=:) function, allocatable settings::tsettingini_readfilename (class(tsettingini) this, character(len=*), intent(in) key, character(len=*), intent(in), optional ADir, logical, optional NotFoundFail, logical, optional relative)
References customparams, miscutils::defaultfalse(), fileutils::file, and stringutils::stringreplace().
tsettingini_readrelativefilename()
character(len=:) function, allocatable settings::tsettingini_readrelativefilename (class(tsettingini) this, character(len=*), intent(in) key, character(len=*), intent(in), optional ADir, logical, optional NotFoundFail)
tsettingini_replacedirs()
character(len=:) function, allocatable settings::tsettingini_replacedirs (class(tsettingini) this, character(len=*) inname, character(len=*), intent(in), optional ADir)
References datadir, fileutils::file, localdir, and stringutils::stringreplace().
tsettingini_settingvaluesfortagname()
subroutine settings::tsettingini_settingvaluesfortagname (class(tsettingini) this, character(len=*), intent(in) name, character(len=*), intent(in) tag, class(tnamevaluelist) OutList, logical, intent(in), optional filename)
References miscutils::defaultfalse(), and stringutils::stringstarts().
tsettingini_tagvaluesforname()
subroutine settings::tsettingini_tagvaluesforname (class(tsettingini) this, character(len=*), intent(in) name, class(tnamevaluelist) OutList, logical, intent(in), optional filename)
References miscutils::defaultfalse(), and stringutils::stringstarts().
Variable Documentation
accuracylevel
real(mcp) settings::accuracylevel = 1
baseroot
character(len=:), allocatable settings::baseroot
Referenced by importancesampling::timportancesampler_readparams().
chainoutfile
type(ttextfile), save settings::chainoutfile = TTextFile(RealFormat='(*(E16.7))')
Referenced by dostop(), and importancesampling::timportancesampler_importancesample().
checkpoint
logical settings::checkpoint = .false.
chisq_label
character(len=:), allocatable settings::chisq_label
Referenced by initializeglobalsettingdefaults().
const_c
real(mcp), parameter settings::const_c = 2.99792458e8_mcp
Referenced by bao::acoustic(), calculator_camb::cambcalc_setderived(), wl::get_convergence(), and calculator_cosmology::hofz_hunit().
cosmomc_version
character(len=*), parameter settings::cosmomc_version = 'Nov2016'
customparams
type(tsettingini), save settings::customparams
Referenced by tsettingini_readfilename().
datadir
character(len=:), allocatable settings::datadir
Referenced by bbn::bbn_init(), wigglezinfo::gigglezinfo_init(), initializeglobalsettingdefaults(), jla::jlalikelihood_add(), jla::read_jla_dataset(), snls::read_snls_dataset(), snls::snlslikelihood_add(), szcounts::szlikelihood_add(), and tsettingini_replacedirs().
dragging_steps
real(mcp) settings::dragging_steps = 3._mcp
feedback
integer settings::feedback = 0
Referenced by bao::bao_lnlike(), bao::bao_readini(), bao::baolikelihood_add(), bbn::bbn_init(), calculator_camb::cambcalc_getnewtransferdata(), calculator_camb::cambcalc_gettheoryforimportance(), checkparamchangef(), cliklike::clik_likeinit(), cliklike::clik_lnlike(), cliklike::clik_readparams(), dostop(), estcovmatmodule::estcovmat(), estcovmatmodule::gethess(), estcovmatmodule::getstepsfordchisq1(), jla::jla_alpha_beta_like(), jla::jla_lnlike(), jla::jla_prep(), jla::jlalikelihood_add(), mcsamples::makesinglesamples(), mpk::mpk_lnlike(), mpk::mpk_readini(), mpk::mpklikelihood_add(), calculator_pico::pico_getnewpowerdata(), estcovmatmodule::placegrid(), jla::read_cov_matrix(), snls::read_cov_matrix(), jla::read_jla_dataset(), snls::read_snls_dataset(), wigglez::readwigglezmatrices(), snls::snls_alpha_beta_like(), snls::snls_lnlike(), snls::snls_prep(), cosmologytypes::tcosmotheorysettings_initforlikelihoods(), importancesampling::timportancesampler_importancesample(), wigglez::wigglez_lnlike(), wigglez::wigglez_readini(), wigglez::wigglezlikelihood_add(), wl::wl_readini(), and wl::wllikelihood_add().
filechangeini
character (len =1024) settings::filechangeini = ''
Referenced by checkparamchange(), and checkparamchangef().
filechangeiniall
character (len =1024) settings::filechangeiniall = ''
Referenced by checkparamchange().
flush_write
logical settings::flush_write = .true.
Referenced by io::io_outputchainrow(), parampointset::paramset_writemodel(), and importancesampling::timportancesampler_importancesample().
fourpi
double precision, parameter settings::fourpi =4*pi
fourpi_r
real, parameter settings::fourpi_r = twopi_r*2
generic_mcmc
logical settings::generic_mcmc = .false.
index_data
integer settings::index_data
index_semislow
integer settings::index_semislow =-1
Referenced by cosmologytypes::tcosmologyparameterization_setnumbers().
instance
integer settings::instance = 0
Referenced by importancesampling::timportancesampler_importancesample().
localdir
character(len=:), allocatable settings::localdir
Referenced by initializeglobalsettingdefaults(), and tsettingini_replacedirs().
log2
double precision, parameter settings::log2 = 0.693147180559945309417232121458d0
logfile
type(ttextfile), save settings::logfile
Referenced by calculator_camb::cambcalc_getnewtransferdata().
logzero
real(mcp), parameter settings::logzero = 1e30_mcp
Referenced by bao::bao_dr1x_loglike(), bao::bao_mgs_loglike(), mcsamples::get1ddensity(), estcovmatmodule::gethess(), jla::jla_alpha_beta_like(), jla::jla_lnlike(), mpk::mpk_lnlike(), estcovmatmodule::placegrid(), snls::snls_alpha_beta_like(), snls::snls_lnlike(), szcounts::szcc_cash(), importancesampling::timportancesampler_importancesample(), and wigglez::wigglez_lnlike().
max_data_params
integer, parameter settings::max_data_params = 200
max_likelihood_functions
integer, parameter settings::max_likelihood_functions = 50
max_num_params
integer, parameter settings::max_num_params = max_theory_params + max_data_params
max_theory_params
integer, parameter settings::max_theory_params = 50
mcp
integer parameter settings::mcp = KIND(1.0)
Referenced by parampointset::paramset_readmodel(), and parampointset::paramset_writemodel().
mpi_real_mcp
integer parameter settings::mpi_real_mcp = MPI_REAL
Referenced by cmblikes::readcovmat(), and importancesampling::timportancesampler_importancesample().
mpichains
integer settings::mpichains = 1
Referenced by importancesampling::timportancesampler_importancesample().
mpirank
integer settings::mpirank = 0
Referenced by bao::bao_readini(), cliklike::clik_likeinit(), cliklike::clik_readparams(), dostop(), cosmologytypes::tcosmotheorysettings_initforlikelihoods(), and importancesampling::timportancesampler_importancesample().
mpirun_start_time
real(time_dp) settings::mpirun_start_time
Referenced by dostop().
new_chains
logical settings::new_chains = .true.
Referenced by cosmotheory::tcosmotheorypredictions_writetheory().
num_data_params
integer settings::num_data_params
Referenced by baseparameters::tbaseparameters_initializeusedparams().
num_params
integer settings::num_params
Referenced by io::io_readproposematrix(), parampointset::paramset_readmodel(), baseparameters::tbaseparameters_initializeusedparams(), baseparameters::tbaseparameters_readparams(), and importancesampling::timportancesampler_importancesample().
num_params_used
integer settings::num_params_used
Referenced by estcovmatmodule::estcovmat(), parampointset::paramset_readmodel(), parampointset::paramset_writemodel(), baseparameters::tbaseparameters_readparams(), and baseparameters::tbaseparameters_setstartpositions().
num_theory_params
integer settings::num_theory_params
Referenced by io::io_readproposematrix(), baseparameters::tbaseparameters_initializeusedparams(), and cosmologytypes::tcosmologyparameterization_setnumbers().
num_threads
integer settings::num_threads = 0
Referenced by calculator_camb::cambcalc_getnewtransferdata(), calculator_camb::cambcalc_gettheoryforimportance(), and checkparamchangef().
output_lines
integer settings::output_lines = 0
Referenced by baseparameters::tbaseparameters_initializeusedparams().
params_used
integer, dimension(:), allocatable settings::params_used
Referenced by estcovmatmodule::estcovmat(), estcovmatmodule::gethess(), estcovmatmodule::getstepsfordchisq1(), propose::init(), io::io_readchainrow(), parampointset::paramset_readmodel(), parampointset::paramset_writemodel(), baseparameters::tbaseparameters_readparams(), baseparameters::tbaseparameters_setstartpositions(), and importancesampling::timportancesampler_importancesample().
pi
double precision, parameter settings::pi =3.14159265358979323846264338328d0
Referenced by wl::get_convergence().
pi_r
real, parameter settings::pi_r = 3.141592653
root2
double precision, parameter settings::root2 = 1.41421356237309504880168872421d0
rootname
character(len=:), allocatable settings::rootname
Referenced by mcsamples::get1ddensity(), getdist(), and mcsamples::makesinglesamples().
sampling_fast_dragging
integer, parameter settings::sampling_fast_dragging = 7
sampling_fastslice
integer, parameter settings::sampling_fastslice =3
sampling_method
integer settings::sampling_method = sampling_metropolis
sampling_metropolis
integer, parameter settings::sampling_metropolis = 1
sampling_multicanonical
integer, parameter settings::sampling_multicanonical = 5
sampling_slice
integer, parameter settings::sampling_slice = 2
sampling_slowgrid
integer, parameter settings::sampling_slowgrid = 4
sampling_wang_landau
integer, parameter settings::sampling_wang_landau = 6
sqrt2
double precision, parameter settings::sqrt2 = root2
stdout
integer, parameter settings::stdout = output_unit
Referenced by getdist().
stop_on_error
logical settings::stop_on_error = .true.
Referenced by calculator_camb::cambcalc_getnewtransferdata().
time_dp
integer, parameter settings::time_dp = KIND(1.d0)
twopi
double precision, parameter settings::twopi =2*pi
twopi_r
real, parameter settings::twopi_r = 2*pi_r
use_fast_slow
logical settings::use_fast_slow = .false.