cosmomc_bde_v3p1: lvalues Module Reference
lvalues Module Reference
Data Types
type lsamples
Functions/Subroutines
integer function lvalues_indexof (lSet, l)
subroutine initlval (lSet, max_l)
subroutine interpolateclarr (lSet, iCl, all_Cl, max_ind)
subroutine interpolateclarrtemplated (lSet, iCl, all_Cl, max_ind, template_index)
Variables
type(lsamples) lsamp
logical log_lvalues = .false.
Function/Subroutine Documentation
initlval()
subroutine lvalues::initlval (type(lsamples) lSet, integer, intent(in) max_l)
References modelparams::cp, modelparams::highaccuracydefault, modelparams::lmin, log_lvalues, modelparams::lsampleboost, modelparams::scale, and modelparams::use_spline_template.
Referenced by cambmain::cmbmain(), and lensing::lens_cls().
interpolateclarr()
subroutine lvalues::interpolateclarr (type (lsamples), intent(in) lSet, real(dl), dimension(*), intent(in) iCl, real(dl), dimension(lmin:*), intent(out) all_Cl, integer, intent(in) max_ind)
References spline().
Referenced by lensing::badharmonic(), interpolateclarrtemplated(), and cambmain::interpolatecls().
interpolateclarrtemplated()
subroutine lvalues::interpolateclarrtemplated (type (lsamples), intent(in) lSet, real(dl), dimension(*), intent(in) iCl, real(dl), dimension(lmin:*), intent(out) all_Cl, integer, intent(in) max_ind, integer, intent(in), optional template_index)
References modelparams::highl_cl_template, interpolateclarr(), modelparams::lmax_extrap_highl, and modelparams::use_spline_template.
Referenced by cambmain::interpolatecls().
lvalues_indexof()
integer function lvalues::lvalues_indexof (type(lsamples) lSet, integer, intent(in) l)
Referenced by cambmain::getlimbertransfers().
Variable Documentation
log_lvalues
logical lvalues::log_lvalues = .false.
Referenced by initlval().
lsamp
type(lsamples) lvalues::lsamp
Referenced by cambmain::cltransfertocl(), cambmain::cmbmain(), lensing::corrfuncflatsky(), lensing::corrfuncfullskyimpl(), cambmain::doflatintegration(), cambmain::dosourceintegration(), spherbessels::generatebessels(), spherbessels::initspherbessels(), cambmain::integratesourcesbessels(), and lensing::lens_cls().