cosmomc_bde_v3p1: nonlinear Module Reference
nonlinear Module Reference
Data Types
type hm_cosmology
type hm_tables
Functions/Subroutines
subroutine, public nonlinear_readparams (Ini)
subroutine, public nonlinear_getnonlinratios (CAMB_Pk)
subroutine halofit (rk, rn, rncur, rknl, plin, pnl, pq, ph)
subroutine wint (CAMB_Pk, itf, r, sig, d1, d2)
real(dl) function omega_m (aa, om_m0, om_v0, wval, waval)
real(dl) function omega_v (aa, om_m0, om_v0, wval, waval)
subroutine hmcode (CAMB_Pk)
real function delta_v (z, lut, cosm)
real function delta_c (z, lut, cosm)
real function eta (z, lut, cosm)
real function kstar (z, lut, cosm)
real function as (z, lut, cosm)
real function fdamp (z, lut, cosm)
real function alpha (z, lut, cosm)
real function r_nl (lut)
subroutine halomod (k, z, p1h, p2h, pfull, plin, lut, cosm)
subroutine fill_table (min, max, arr, n)
subroutine fill_plintab (iz, cosm, CAMB_PK)
real function tcb_tcbnu_ratio (k, z, cosm)
subroutine assign_hm_cosmology (cosm)
subroutine initialise_hm_cosmology (iz, cosm, CAMB_PK)
subroutine allocate_lut (lut)
subroutine deallocate_lut (lut)
subroutine halomod_init (z, lut, cosm)
subroutine write_parameters (z, lut, cosm)
pure real function radius_m (m, cosm)
real function neff (lut, cosm)
subroutine conc_bull (z, lut, cosm)
real function grow_int (b, acc, cosm)
subroutine zcoll_bull (z, cosm, lut)
real function mass_r (r, cosm)
pure real function cosmic_density (cosm)
real function find_pk (k, itype, cosm)
real function p_lin (k, z, itype, cosm)
real function p_2h (k, z, plin, lut, cosm)
real function p_1h (k, z, lut, cosm)
subroutine fill_sigtab (cosm)
real function sigma_v (R, z, cosm)
real function sigma (r, z, itype, cosm)
real function sigmac (r, z, cosm)
real function wk_tophat (x)
real function inttab (x, y, n, iorder)
real function sigma_integrand (t, R, f, z, itype, cosm)
real function f_rapid (r)
real function sigint0 (r, z, itype, cosm)
real function sigint1 (r, z, itype, cosm)
real function sigint2 (r, z, itype, cosm)
real function win (k, rv, c)
real function winnfw (k, rv, c)
real function mass (c)
real function gnu (nu)
real function gst (nu)
real function hubble2 (z, cosm)
real function x_de (a, cosm)
real function w_de_hm (a, cosm)
real function omega_m_hm (z, cosm)
real function grow (z, cosm)
real function dispint (z, cosm)
real function si (x)
real function ci (x)
real function derivative_table (x, xin, yin, n, iorder, imeth)
real function find (x, xin, yin, n, iorder, imeth)
integer function table_integer (x, xtab, n, imeth)
integer function linear_table_integer (x, xtab, n)
integer function search_int (x, xtab, n)
integer function int_split (x, xtab, n)
subroutine fit_line (a1, a0, x1, y1, x2, y2)
subroutine fit_quadratic (a2, a1, a0, x1, y1, x2, y2, x3, y3)
subroutine fit_cubic (a, b, c, d, x1, y1, x2, y2, x3, y3, x4, y4)
subroutine reverse (arry, n)
subroutine fill_growtab (cosm)
subroutine ode_growth (x, v, t, kk, ti, tf, xi, vi, acc, imeth, cosm)
real function fv (d, v, k, a, cosm)
real function fd (d, v, k, a, cosm)
real function ah (z, cosm)
Variables
real, parameter, public min_kh_nonlinear = 0.005
real(dl) om_m
real(dl) om_v
real(dl) fnu
real(dl) omm0
real(dl) acur
integer, parameter, public halofit_original = 1
integer, parameter, public halofit_bird =2
integer, parameter, public halofit_peacock =3
integer, parameter, public halofit_takahashi =4
integer, parameter, public halofit_mead =5
integer, parameter, public halofit_halomodel =6
integer, parameter, public halofit_default = halofit_takahashi
integer, public halofit_version = halofit_default
integer imead
integer ihm
Function/Subroutine Documentation
ah()
real function nonlinear::ah (real, intent(in) z, type(hm_cosmology), intent(in) cosm) private
References w_de_hm(), and x_de().
Referenced by fv().
allocate_lut()
subroutine nonlinear::allocate_lut (type(hm_tables) lut) private
Referenced by halomod_init().
alpha()
real function nonlinear::alpha (real, intent(in) z, type(hm_tables), intent(in) lut, type(hm_cosmology), intent(in) cosm) private
References imead.
Referenced by f_rapid(), halomod(), sigma_v(), and write_parameters().
as()
real function nonlinear::as (real, intent(in) z, type(hm_tables), intent(in) lut, type(hm_cosmology), intent(in) cosm) private
References imead.
Referenced by conc_bull(), and write_parameters().
assign_hm_cosmology()
subroutine nonlinear::assign_hm_cosmology (type(hm_cosmology) cosm) private
References modelparams::cp, ihm, lambdageneral::w_lam, and lambdageneral::wa_ppf.
Referenced by hmcode().
ci()
real function nonlinear::ci (real, intent(in) x) private
Referenced by winnfw().
conc_bull()
subroutine nonlinear::conc_bull (real, intent(in) z, type(hm_tables) lut, type(hm_cosmology) cosm) private
References as(), grow(), grow_int(), and zcoll_bull().
Referenced by halomod_init().
cosmic_density()
pure real function nonlinear::cosmic_density (type(hm_cosmology), intent(in) cosm) private
Referenced by mass_r(), and radius_m().
deallocate_lut()
subroutine nonlinear::deallocate_lut (type(hm_tables) lut) private
Referenced by halomod_init().
delta_c()
real function nonlinear::delta_c (real, intent(in) z, type(hm_tables), intent(in) lut, type(hm_cosmology), intent(in) cosm) private
References imead, and omega_m_hm().
Referenced by halomod_init(), write_parameters(), and zcoll_bull().
delta_v()
real function nonlinear::delta_v (real, intent(in) z, type(hm_tables), intent(in) lut, type(hm_cosmology), intent(in) cosm) private
References imead, and omega_m_hm().
Referenced by halomod_init(), p_1h(), and write_parameters().
derivative_table()
real function nonlinear::derivative_table (real, intent(in) x, real, dimension(n), intent(in) xin, real, dimension(n), intent(in) yin, integer, intent(in) n, integer, intent(in) iorder, integer, intent(in) imeth) private
References fit_cubic(), fit_line(), fit_quadratic(), reverse(), and table_integer().
Referenced by neff().
dispint()
real function nonlinear::dispint (real, intent(in) z, type(hm_cosmology), intent(in) cosm) private
References p_lin().
Referenced by halomod_init().
eta()
real function nonlinear::eta (real, intent(in) z, type(hm_tables), intent(in) lut, type(hm_cosmology), intent(in) cosm) private
References imead.
Referenced by p_1h(), and write_parameters().
f_rapid()
real function nonlinear::f_rapid (real, intent(in) r) private
References alpha().
Referenced by sigint0().
fd()
real function nonlinear::fd (real, intent(in) d, real, intent(in) v, real, intent(in) k, real, intent(in) a, type(hm_cosmology), intent(in) cosm) private
Referenced by ode_growth().
fdamp()
real function nonlinear::fdamp (real, intent(in) z, type(hm_tables), intent(in) lut, type(hm_cosmology), intent(in) cosm) private
References imead.
Referenced by p_2h(), and write_parameters().
fill_growtab()
subroutine nonlinear::fill_growtab (type(hm_cosmology) cosm) private
References find(), ihm, and ode_growth().
Referenced by hmcode().
fill_plintab()
subroutine nonlinear::fill_plintab (integer, intent(in) iz, type(hm_cosmology) cosm, type(matterpowerdata), intent(in) CAMB_PK) private
References fill_table(), grow(), ihm, transfer::matterpowerdata_k(), sigma(), and tcb_tcbnu_ratio().
Referenced by initialise_hm_cosmology().
fill_sigtab()
subroutine nonlinear::fill_sigtab (type(hm_cosmology) cosm) private
References ihm, and sigma().
Referenced by initialise_hm_cosmology().
fill_table()
subroutine nonlinear::fill_table (real, intent(in) min, real, intent(in) max, real, dimension(:), allocatable arr, integer, intent(in) n) private
Referenced by fill_plintab().
find()
real function nonlinear::find (real, intent(in) x, real, dimension(n), intent(in) xin, real, dimension(n), intent(in) yin, integer, intent(in) n, integer, intent(in) iorder, integer, intent(in) imeth) private
References fit_cubic(), fit_line(), fit_quadratic(), reverse(), and table_integer().
Referenced by fill_growtab(), find_pk(), grow(), r_nl(), sigmac(), and zcoll_bull().
find_pk()
real function nonlinear::find_pk (real, intent(in) k, integer, intent(in) itype, type(hm_cosmology), intent(in) cosm) private
References find().
Referenced by p_lin().
fit_cubic()
subroutine nonlinear::fit_cubic (real, intent(out) a, real, intent(out) b, real, intent(out) c, real, intent(out) d, real, intent(in) x1, real, intent(in) y1, real, intent(in) x2, real, intent(in) y2, real, intent(in) x3, real, intent(in) y3, real, intent(in) x4, real, intent(in) y4) private
Referenced by derivative_table(), find(), and inttab().
fit_line()
subroutine nonlinear::fit_line (real, intent(out) a1, real, intent(out) a0, real, intent(in) x1, real, intent(in) y1, real, intent(in) x2, real, intent(in) y2) private
Referenced by derivative_table(), and find().
fit_quadratic()
subroutine nonlinear::fit_quadratic (real, intent(out) a2, real, intent(out) a1, real, intent(out) a0, real, intent(in) x1, real, intent(in) y1, real, intent(in) x2, real, intent(in) y2, real, intent(in) x3, real, intent(in) y3) private
Referenced by derivative_table(), find(), and inttab().
fv()
real function nonlinear::fv (real, intent(in) d, real, intent(in) v, real, intent(in) k, real, intent(in) a, type(hm_cosmology), intent(in) cosm) private
References ah(), hubble2(), and omega_m_hm().
Referenced by ode_growth().
gnu()
real function nonlinear::gnu (real, intent(in) nu) private
References gst().
Referenced by p_1h().
grow()
real function nonlinear::grow (real, intent(in) z, type(hm_cosmology), intent(in) cosm) private
References find().
Referenced by conc_bull(), fill_plintab(), p_lin(), sigmac(), and zcoll_bull().
grow_int()
real function nonlinear::grow_int (real b, real acc, type(hm_cosmology) cosm) private
References omega_m_hm().
Referenced by conc_bull().
gst()
real function nonlinear::gst (real, intent(in) nu) private
Referenced by gnu().
halofit()
subroutine nonlinear::halofit (real(dl) rk, real(dl) rn, real(dl) rncur, real(dl) rknl, real(dl) plin, real(dl) pnl, real(dl) pq, real(dl) ph) private
References acur, fnu, halofit_bird, halofit_original, halofit_peacock, halofit_takahashi, halofit_version, om_m, om_v, lambdageneral::w_lam, and lambdageneral::wa_ppf.
Referenced by nonlinear_getnonlinratios().
halomod()
subroutine nonlinear::halomod (real, intent(in) k, real, intent(in) z, real, intent(out) p1h, real, intent(out) p2h, real, intent(out) pfull, real, intent(in) plin, type(hm_tables), intent(in) lut, type(hm_cosmology), intent(in) cosm) private
References alpha(), p_1h(), and p_2h().
Referenced by hmcode().
halomod_init()
subroutine nonlinear::halomod_init (real, intent(in) z, type(hm_tables) lut, type(hm_cosmology) cosm) private
References allocate_lut(), conc_bull(), deallocate_lut(), delta_c(), delta_v(), dispint(), ihm, neff(), r_nl(), radius_m(), sigma(), sigma_v(), sigmac(), and write_parameters().
Referenced by hmcode().
hmcode()
subroutine nonlinear::hmcode (type(matterpowerdata) CAMB_Pk) private
References assign_hm_cosmology(), fill_growtab(), halofit_halomodel, halofit_mead, halofit_version, halomod(), halomod_init(), ihm, imead, initialise_hm_cosmology(), and p_lin().
Referenced by nonlinear_getnonlinratios().
hubble2()
real function nonlinear::hubble2 (real, intent(in) z, type(hm_cosmology), intent(in) cosm) private
References om_m, om_v, and x_de().
Referenced by fv(), and omega_m_hm().
initialise_hm_cosmology()
subroutine nonlinear::initialise_hm_cosmology (integer, intent(in) iz, type(hm_cosmology) cosm, type(matterpowerdata), intent(in) CAMB_PK) private
References fill_plintab(), and fill_sigtab().
Referenced by hmcode().
int_split()
integer function nonlinear::int_split (real, intent(in) x, real, dimension(n), intent(in) xtab, integer, intent(in) n) private
Referenced by table_integer().
inttab()
real function nonlinear::inttab (real, dimension(n), intent(in) x, real, dimension(n), intent(in) y, integer, intent(in) n, integer, intent(in) iorder) private
References fit_cubic(), and fit_quadratic().
kstar()
real function nonlinear::kstar (real, intent(in) z, type(hm_tables), intent(in) lut, type(hm_cosmology), intent(in) cosm) private
References imead.
Referenced by p_1h(), and write_parameters().
linear_table_integer()
integer function nonlinear::linear_table_integer (real, intent(in) x, real, dimension(n), intent(in) xtab, integer, intent(in) n) private
Referenced by table_integer().
mass()
real function nonlinear::mass (real, intent(in) c) private
Referenced by winnfw().
mass_r()
real function nonlinear::mass_r (real r, type(hm_cosmology) cosm) private
References cosmic_density().
neff()
real function nonlinear::neff (type(hm_tables), intent(in) lut, type(hm_cosmology), intent(in) cosm) private
References derivative_table().
Referenced by halomod_init().
nonlinear_getnonlinratios()
subroutine, public nonlinear::nonlinear_getnonlinratios (type(matterpowerdata) CAMB_Pk)
References acur, modelparams::cp, fnu, halofit(), halofit_halomodel, halofit_mead, halofit_version, hmcode(), transfer::matterpowerdata_k(), min_kh_nonlinear, om_m, om_v, omega_m(), omega_v(), omm0, lambdageneral::w_lam, lambdageneral::wa_ppf, and wint().
Referenced by cambmain::makenonlinearsources(), and nonlinear_getratios().
nonlinear_readparams()
subroutine, public nonlinear::nonlinear_readparams (type(tinifile) Ini)
References halofit_default, halofit_version, and inifile::ini_read_int_file().
ode_growth()
subroutine nonlinear::ode_growth (real, dimension(:), allocatable x, real, dimension(:), allocatable v, real, dimension(:), allocatable t, real kk, real ti, real tf, real xi, real vi, real acc, integer imeth, type(hm_cosmology) cosm) private
References fd(), and fv().
Referenced by fill_growtab().
omega_m()
real(dl) function nonlinear::omega_m (real(dl) aa, real(dl) om_m0, real(dl) om_v0, real(dl) wval, real(dl) waval) private
Referenced by nonlinear_getnonlinratios().
omega_m_hm()
real function nonlinear::omega_m_hm (real, intent(in) z, type(hm_cosmology), intent(in) cosm) private
References hubble2(), and om_m.
Referenced by delta_c(), delta_v(), fv(), and grow_int().
omega_v()
real(dl) function nonlinear::omega_v (real(dl) aa, real(dl) om_m0, real(dl) om_v0, real(dl) wval, real(dl) waval) private
Referenced by nonlinear_getnonlinratios().
p_1h()
real function nonlinear::p_1h (real, intent(in) k, real, intent(in) z, type(hm_tables), intent(in) lut, type(hm_cosmology), intent(in) cosm) private
References delta_v(), eta(), gnu(), kstar(), and win().
Referenced by halomod().
p_2h()
real function nonlinear::p_2h (real, intent(in) k, real, intent(in) z, real, intent(in) plin, type(hm_tables), intent(in) lut, type(hm_cosmology), intent(in) cosm) private
References fdamp(), and imead.
Referenced by halomod().
p_lin()
real function nonlinear::p_lin (real, intent(in) k, real, intent(in) z, integer, intent(in) itype, type(hm_cosmology), intent(in) cosm) private
References find_pk(), and grow().
Referenced by dispint(), hmcode(), sigint1(), sigint2(), sigma_integrand(), and sigma_v().
r_nl()
real function nonlinear::r_nl (type(hm_tables), intent(in) lut) private
References find().
Referenced by halomod_init().
radius_m()
pure real function nonlinear::radius_m (real, intent(in) m, type(hm_cosmology), intent(in) cosm) private
References cosmic_density().
Referenced by halomod_init().
reverse()
subroutine nonlinear::reverse (real, dimension(n), intent(inout) arry, integer, intent(in) n) private
Referenced by getdist.plots.GetDistPlotter::add_legend(), derivative_table(), and find().
search_int()
integer function nonlinear::search_int (real, intent(in) x, real, dimension(n), intent(in) xtab, integer, intent(in) n) private
Referenced by table_integer().
si()
real function nonlinear::si (real, intent(in) x) private
Referenced by winnfw().
sigint0()
real function nonlinear::sigint0 (real, intent(in) r, real, intent(in) z, integer, intent(in) itype, type(hm_cosmology), intent(in) cosm) private
References f_rapid(), and sigma_integrand().
Referenced by sigma().
sigint1()
real function nonlinear::sigint1 (real, intent(in) r, real, intent(in) z, integer, intent(in) itype, type(hm_cosmology), intent(in) cosm) private
References p_lin(), and wk_tophat().
Referenced by sigma().
sigint2()
real function nonlinear::sigint2 (real, intent(in) r, real, intent(in) z, integer, intent(in) itype, type(hm_cosmology), intent(in) cosm) private
References p_lin(), and wk_tophat().
Referenced by sigma().
sigma()
real function nonlinear::sigma (real, intent(in) r, real, intent(in) z, integer, intent(in) itype, type(hm_cosmology), intent(in) cosm) private
References sigint0(), sigint1(), and sigint2().
Referenced by fill_plintab(), fill_sigtab(), and halomod_init().
sigma_integrand()
real function nonlinear::sigma_integrand (real, intent(in) t, real, intent(in) R, f, real, intent(in) z, integer, intent(in) itype, type(hm_cosmology), intent(in) cosm) private
References p_lin(), and wk_tophat().
Referenced by sigint0().
sigma_v()
real function nonlinear::sigma_v (real, intent(in) R, real, intent(in) z, type(hm_cosmology), intent(in) cosm) private
References alpha(), p_lin(), and wk_tophat().
Referenced by halomod_init().
sigmac()
real function nonlinear::sigmac (real, intent(in) r, real, intent(in) z, type(hm_cosmology), intent(in) cosm) private
References find(), and grow().
Referenced by halomod_init().
table_integer()
integer function nonlinear::table_integer (real, intent(in) x, real, dimension(n), intent(in) xtab, integer, intent(in) n, integer, intent(in) imeth) private
References int_split(), linear_table_integer(), and search_int().
Referenced by derivative_table(), and find().
tcb_tcbnu_ratio()
real function nonlinear::tcb_tcbnu_ratio (real, intent(in) k, real, intent(in) z, type(hm_cosmology) cosm) private
Referenced by fill_plintab().
w_de_hm()
real function nonlinear::w_de_hm (real, intent(in) a, type(hm_cosmology), intent(in) cosm) private
Referenced by ah().
win()
real function nonlinear::win (real, intent(in) k, real, intent(in) rv, real, intent(in) c) private
References winnfw().
Referenced by p_1h().
winnfw()
real function nonlinear::winnfw (real, intent(in) k, real, intent(in) rv, real, intent(in) c) private
References ci(), mass(), and si().
Referenced by win().
wint()
subroutine nonlinear::wint (type(matterpowerdata) CAMB_Pk, integer, intent(in) itf, real(dl) r, real(dl) sig, real(dl) d1, real(dl) d2) private
References transfer::matterpowerdata_k().
Referenced by nonlinear_getnonlinratios().
wk_tophat()
real function nonlinear::wk_tophat (real x) private
Referenced by sigint1(), sigint2(), sigma_integrand(), and sigma_v().
write_parameters()
subroutine nonlinear::write_parameters (real, intent(in) z, type(hm_tables), intent(in) lut, type(hm_cosmology), intent(in) cosm) private
References alpha(), as(), delta_c(), delta_v(), eta(), fdamp(), ihm, and kstar().
Referenced by halomod_init().
x_de()
real function nonlinear::x_de (real, intent(in) a, type(hm_cosmology), intent(in) cosm) private
Referenced by ah(), and hubble2().
zcoll_bull()
subroutine nonlinear::zcoll_bull (real, intent(in) z, type(hm_cosmology) cosm, type(hm_tables) lut) private
References delta_c(), find(), and grow().
Referenced by conc_bull().
Variable Documentation
acur
real(dl) nonlinear::acur private
Referenced by halofit(), and nonlinear_getnonlinratios().
fnu
real(dl) nonlinear::fnu private
Referenced by halofit(), and nonlinear_getnonlinratios().
halofit_bird
integer, parameter, public nonlinear::halofit_bird =2
Referenced by halofit().
halofit_default
integer, parameter, public nonlinear::halofit_default = halofit_takahashi
Referenced by calculator_camb::cambcalc_readparams(), and nonlinear_readparams().
halofit_halomodel
integer, parameter, public nonlinear::halofit_halomodel =6
Referenced by hmcode(), and nonlinear_getnonlinratios().
halofit_mead
integer, parameter, public nonlinear::halofit_mead =5
Referenced by hmcode(), and nonlinear_getnonlinratios().
halofit_original
integer, parameter, public nonlinear::halofit_original = 1
Referenced by halofit().
halofit_peacock
integer, parameter, public nonlinear::halofit_peacock =3
Referenced by halofit().
halofit_takahashi
integer, parameter, public nonlinear::halofit_takahashi =4
Referenced by halofit().
halofit_version
integer, public nonlinear::halofit_version = halofit_default
Referenced by calculator_camb::cambcalc_readparams(), halofit(), hmcode(), nonlinear_getnonlinratios(), and nonlinear_readparams().
ihm
integer nonlinear::ihm private
Referenced by assign_hm_cosmology(), fill_growtab(), fill_plintab(), fill_sigtab(), halomod_init(), hmcode(), and write_parameters().
imead
integer nonlinear::imead private
Referenced by alpha(), as(), delta_c(), delta_v(), eta(), fdamp(), hmcode(), kstar(), and p_2h().
min_kh_nonlinear
real, parameter, public nonlinear::min_kh_nonlinear = 0.005
Referenced by cambmain::makenonlinearsources(), and nonlinear_getnonlinratios().
om_m
real(dl) nonlinear::om_m private
Referenced by halofit(), hubble2(), nonlinear_getnonlinratios(), and omega_m_hm().
om_v
real(dl) nonlinear::om_v private
Referenced by halofit(), hubble2(), and nonlinear_getnonlinratios().
omm0
real(dl) nonlinear::omm0 private
Referenced by nonlinear_getnonlinratios().