cosmomc_bde_v3p1: cambPlots Namespace Reference
cambPlots Namespace Reference
Classes
class ClResult
Functions
def saveCls (f, ls, vecs)
def cl_plot (ax, L, cl, x=None, y=None, grid=False, lmax=None, axargs)
def checkClResult (result, lensedCl=True)
def plot_array (clResults, lmax=None, lmin=2, indices=None, array_tag='cl_array', tags=None, diff=False, label=True, half=False, figsize=(12, 8), tag_separator='', colors=['k', r, b, g, m, axargs)
def plot_compare (clResults, colors=def_colors, ncl=1, x='sqrt', x_lens='log', y=None, y_lens='log', compare=None, diff_fraction=True, args)
Variables
list def_colors = ['b', 'r', 'm', 'c', 'g', 'k', 'y', '0.25', '0.75']
Function Documentation
checkClResult()
def cambPlots.checkClResult (result, lensedCl = True)
References plot_array().
Referenced by plot_compare().
cl_plot()
def cambPlots.cl_plot (ax, L, cl, x = None, y = None, grid = False, lmax = None, axargs)
References CAMB_test_files.int.
Referenced by plot_array(), and plot_compare().
plot_array()
def cambPlots.plot_array (clResults, lmax = None, lmin = 2, indices = None, array_tag = 'cl_array', tags = None, diff = False, label = True, half = False, figsize = (12, 8), tag_separator = '', colors = ['k', r, b, g, m, axargs)
References cl_plot(), CAMB_test_files.int, and mnu.tight_layout.
Referenced by checkClResult().
plot_compare()
def cambPlots.plot_compare (clResults, colors = def_colors, ncl = 1, x = 'sqrt', x_lens = 'log', y = None, y_lens = 'log', compare = None, diff_fraction = True, args)
References checkClResult(), and cl_plot().
saveCls()
def cambPlots.saveCls (f, ls, vecs)
Variable Documentation
def_colors
list cambPlots.def_colors = ['b', 'r', 'm', 'c', 'g', 'k', 'y', '0.25', '0.75']