cosmomc_bde_v3p1: paramgrid.batchjob Namespace Reference
paramgrid.batchjob Namespace Reference
Classes
class batchJob
class dataSet
class importanceSetting
class jobGroup
class jobItem
class propertiesItem
Functions
def resetGrid (directory)
def readobject (directory=None)
def saveobject (obj, filename)
def makePath (s)
def nonEmptyFile (fname)
def getCodeRootPath ()
Function Documentation
getCodeRootPath()
def paramgrid.batchjob.getCodeRootPath ()
makePath()
def paramgrid.batchjob.makePath (s)
Referenced by paramgrid.batchjob.jobItem.makeChainPath(), and paramgrid.batchjob.batchJob.makeDirectories().
nonEmptyFile()
def paramgrid.batchjob.nonEmptyFile (fname)
Referenced by paramgrid.batchjob.jobItem.chainBestfit(), paramgrid.batchjob.jobItem.chainExists(), paramgrid.batchjob.jobItem.chainMinimumExists(), paramgrid.batchjob.jobItem.convergeStat(), and paramgrid.batchjob.jobItem.R().
readobject()
def paramgrid.batchjob.readobject (directory = None)
References paramgrid.batchjob.resetGrid().
resetGrid()
def paramgrid.batchjob.resetGrid (directory)
Referenced by paramgrid.batchjob.readobject().
saveobject()
def paramgrid.batchjob.saveobject (obj, filename)
Referenced by paramgrid.batchjob.batchJob.save().