cosmomc_bde_v3p1: lensing Module Reference
lensing Module Reference
Functions/Subroutines
subroutine, public lens_cls
subroutine corrfuncfullsky
subroutine corrfuncfullskyimpl (lmax)
subroutine corrfuncflatsky
subroutine badharmonic
subroutine getbessels (MaxArg)
real(dl) function, public bessj0 (x)
real(dl) function bessj (n, x)
double precision function bessi0 (X)
double precision function bessi1 (X)
double precision function, public bessi (N, X)
Variables
integer, parameter, public lensing_method_curv_corr =1
integer, parameter, public lensing_method_flat_corr =2
integer, parameter, public lensing_method_harmonic =3
integer, public lensing_method = lensing_method_curv_corr
real(dl), public alens_fiducial = 0._dl
logical, public lensing_includes_tensors = .false.
real(dl), parameter dbessel = 0.05_dl
real(dl), dimension(:), allocatable bess0
real(dl), dimension(:), allocatable ddbess0
real(dl), dimension(:), allocatable bess2
real(dl), dimension(:), allocatable ddbess2
real(dl), dimension(:), allocatable bess4
real(dl), dimension(:), allocatable ddbess4
real(dl), dimension(:), allocatable bess6
real(dl), dimension(:), allocatable ddbess6
integer, parameter lensed_convolution_margin = 100
integer lmax_donelnfa = 0
real(dl), dimension(:), allocatable lnfa
Function/Subroutine Documentation
badharmonic()
subroutine lensing::badharmonic ()
References modelparams::accuracyboost, modeldata::c_cross, modeldata::c_e, modeldata::c_phi, modeldata::c_temp, modeldata::cl_lensed, modeldata::cl_scalar, modeldata::cl_tensor, modeldata::ct_b, modeldata::ct_cross, modeldata::ct_e, modeldata::ct_temp, modelparams::debugmsgs, modelparams::feedbacklevel, modelparams::gettesttime(), lvalues::interpolateclarr(), lensing_includes_tensors, lmax_donelnfa, modeldata::lmax_lensed, lnfa, modelparams::outputdenominator, and modelparams::scale.
Referenced by lens_cls().
bessi()
double precision function, public lensing::bessi (integer, intent(in) N, double precision X)
References bessi0(), and bessi1().
bessi0()
double precision function lensing::bessi0 (double precision X) private
Referenced by bessi().
bessi1()
double precision function lensing::bessi1 (double precision X) private
Referenced by bessi().
bessj()
real(dl) function lensing::bessj (integer n, real(dl) x) private
Referenced by getbessels().
bessj0()
real(dl) function, public lensing::bessj0 (real(dl) x)
Referenced by getbessels().
corrfuncflatsky()
subroutine lensing::corrfuncflatsky ()
References modelparams::accuracyboost, bess0, bess2, bess4, bess6, modeldata::c_cross, modeldata::c_e, modeldata::c_phi, modeldata::c_temp, modeldata::cl_lensed, modeldata::cl_scalar, modeldata::ct_b, modeldata::ct_cross, modeldata::ct_e, modeldata::ct_temp, dbessel, ddbess0, ddbess2, ddbess4, ddbess6, modelparams::debugmsgs, getbessels(), modelparams::gettesttime(), lensing_includes_tensors, modeldata::lmax_lensed, lvalues::lsamp, and modelparams::outputdenominator.
Referenced by lens_cls().
corrfuncfullsky()
subroutine lensing::corrfuncfullsky ()
References corrfuncfullskyimpl(), modelparams::cp, modelparams::highaccuracydefault, lensed_convolution_margin, and modelparams::lmax_extrap_highl.
Referenced by lens_cls().
corrfuncfullskyimpl()
subroutine lensing::corrfuncfullskyimpl (integer, intent(in) lmax) private
References modelparams::accuracyboost, alens_fiducial, modeldata::c_cross, modeldata::c_e, modeldata::c_phi, modeldata::c_temp, modeldata::cl_lensed, modeldata::cl_scalar, modelparams::cp, modeldata::ct_b, modeldata::ct_cross, modeldata::ct_e, modeldata::ct_temp, modelparams::debugmsgs, modelparams::gettesttime(), modelparams::highl_cl_template, lensed_convolution_margin, lensing_includes_tensors, modeldata::lmax_lensed, lvalues::lsamp, modelparams::outputdenominator, and spline().
Referenced by corrfuncfullsky().
getbessels()
subroutine lensing::getbessels (real(dl), intent(in) MaxArg)
References bess0, bess2, bess4, bess6, bessj(), bessj0(), dbessel, ddbess0, ddbess2, ddbess4, ddbess6, modelparams::spl_large, and spline().
Referenced by corrfuncflatsky().
lens_cls()
subroutine, public lensing::lens_cls ()
References badharmonic(), corrfuncflatsky(), corrfuncfullsky(), modelparams::cp, lvalues::initlval(), lensing_method, lensing_method_curv_corr, lensing_method_flat_corr, lensing_method_harmonic, and lvalues::lsamp.
Referenced by camb::camb_getresults(), and camb::camb_transferstopowers().
Variable Documentation
alens_fiducial
real(dl), public lensing::alens_fiducial = 0._dl
Referenced by calculator_camb::cambcalc_cmbtocamb(), and corrfuncfullskyimpl().
bess0
real(dl), dimension(:), allocatable lensing::bess0 private
Referenced by corrfuncflatsky(), and getbessels().
bess2
real(dl), dimension(:), allocatable lensing::bess2 private
Referenced by corrfuncflatsky(), and getbessels().
bess4
real(dl), dimension(:), allocatable lensing::bess4 private
Referenced by corrfuncflatsky(), and getbessels().
bess6
real(dl), dimension(:), allocatable lensing::bess6 private
Referenced by corrfuncflatsky(), and getbessels().
dbessel
real(dl), parameter lensing::dbessel = 0.05_dl private
Referenced by corrfuncflatsky(), and getbessels().
ddbess0
real(dl), dimension(:), allocatable lensing::ddbess0 private
Referenced by corrfuncflatsky(), and getbessels().
ddbess2
real(dl), dimension(:), allocatable lensing::ddbess2 private
Referenced by corrfuncflatsky(), and getbessels().
ddbess4
real(dl), dimension(:), allocatable lensing::ddbess4 private
Referenced by corrfuncflatsky(), and getbessels().
ddbess6
real(dl), dimension(:), allocatable lensing::ddbess6 private
Referenced by corrfuncflatsky(), and getbessels().
lensed_convolution_margin
integer, parameter lensing::lensed_convolution_margin = 100 private
Referenced by corrfuncfullsky(), and corrfuncfullskyimpl().
lensing_includes_tensors
logical, public lensing::lensing_includes_tensors = .false.
Referenced by badharmonic(), calculator_camb::cambcalc_initcambparams(), corrfuncflatsky(), and corrfuncfullskyimpl().
lensing_method
integer, public lensing::lensing_method = lensing_method_curv_corr
Referenced by lens_cls().
lensing_method_curv_corr
integer, parameter, public lensing::lensing_method_curv_corr =1
Referenced by lens_cls().
lensing_method_flat_corr
integer, parameter, public lensing::lensing_method_flat_corr =2
Referenced by lens_cls().
lensing_method_harmonic
integer, parameter, public lensing::lensing_method_harmonic =3
Referenced by lens_cls().
lmax_donelnfa
integer lensing::lmax_donelnfa = 0 private
Referenced by badharmonic().
lnfa
real(dl), dimension(:), allocatable lensing::lnfa private
Referenced by badharmonic().