cosmomc_bde_v3p1: mcsamples Module Reference
mcsamples Module Reference
Functions/Subroutines
subroutine adjustpriors
subroutine mapparameters (invars)
subroutine coolchain (cool)
subroutine deletezeros
subroutine sortcoldata (bycol)
subroutine makesinglesamples (single_thin)
subroutine writethindata (fname, cool)
subroutine thindata (fac, ix1, ix2)
subroutine getcovmatrix
integer function mostcorrelated2d (i1, i2, direc)
subroutine getfractionindices (fraction_indices, n)
real(mcp) function confidval (ix, limfrac, upper, ix1, ix2)
subroutine writes (S)
subroutine pca (pars, n, param_map, normparam_num)
subroutine getusedcols
subroutine doconvergetests (limfrac)
subroutine get1ddensity (j)
subroutine get2dplotdata (j, j2)
logical function plotcontmatlab (aunit, aroot, j, j2, DoShade)
character(len=:) function, allocatable matlablabel (i)
subroutine write2dplotmatlab (aunit, j, j2, DoLabelx, DoLabely, hide_ticklabels)
subroutine writeplotfileinit (unit, sm, subplot_size)
subroutine writeplotfileexport (unit, tag, plot_col, plot_row)
character(len=:) function, allocatable quoted_param_name (j)
character(len=:) function, allocatable quoted_param_name_used (j)
character(len=:) function, allocatable python_param_array (params, num)
subroutine write1dplotmatlab (aunit, j)
subroutine writematlablinelabels (F)
subroutine edgewarning (param)
character(len=:) function, allocatable dat_file_name (rootname, j)
character(len=:) function, allocatable dat_file_2d (rootname, j, j2)
subroutine checkmatlabaxes (afile)
real(mcp) function dinvnorm (p)
subroutine getchainlikesummary (unit)
Variables
type(tparamnames), save namemapping
integer, parameter gp = KIND(1.d0)
character(len= *), parameter float_format = '(*(E16.7))'
real(gp), dimension(:,:), allocatable coldata
integer, dimension(:), allocatable thin_ix
integer thin_rows
integer, parameter max_rows = 500000
integer, parameter max_cols = 500
integer, parameter max_chains = 100
integer, parameter max_split_tests = 4
integer, parameter max_contours = 5
integer corr_length_thin = 0
integer corr_length_steps = 15
type(tdensity1d) density1d
integer, dimension(max_chains) chain_indices
integer num_chains_used
integer bestfit_ix
real(mcp) meanlike
real(mcp) maxlike
integer nrows
integer ncols
integer num_bins
integer num_bins_2d
real(mcp) numsamp
real(mcp) max_mult
real(mcp) mean_mult
integer nd_cont1
integer nd_cont2
real(mcp), dimension(:,:), allocatable nd_limit_top
real(mcp), dimension(:,:), allocatable nd_limit_bot
integer covmat_dimension
integer, dimension(max_cols) colix
integer num_vars
real(mcp), dimension(2, max_cols) prior_ranges
real(mcp), dimension(max_cols) mean
real(mcp), dimension(max_cols) sddev
real(mcp), dimension(:,:), allocatable corrmatrix
character(len=:), allocatable plot_data_dir
character(len=:), allocatable out_dir
character(len=:), allocatable rootdirname
character(len=:), allocatable in_root
character(len=128), dimension(max_cols) labels
character(len=128), dimension(max_cols) pname
logical, dimension(max_cols) has_limits
logical, dimension(max_cols) has_limits_top
logical, dimension(max_cols) has_limits_bot
logical, dimension(max_contours, max_cols) marge_limits_top
logical, dimension(max_contours, max_cols) marge_limits_bot
logical, dimension(max_cols) has_markers
real(mcp), dimension(max_cols) markers
integer num_contours
character(len=3) plot_ext = 'm'
real(mcp) matlab_version
character(len=3) plot_output = 'pdf'
real subplot_size_inch = 3.0
real subplot_size_inch2
real subplot_size_inch3
logical matlab_latex = .false.
real(mcp) font_scale = 1.
real(mcp), dimension(max_contours) contours
real(mcp), dimension(max_contours) max_frac_twotail
integer indep_thin = 0
integer, dimension(max_chains) chain_numbers
logical, dimension(max_cols) isused
logical force_twotail
logical plot_meanlikes
logical mean_loglikes = .false.
logical shade_meanlikes
logical make_single_samples
integer single_thin
integer, dimension(max_cols **2) cust2dplots
integer, dimension(max_cols) ix_min
integer, dimension(max_cols) ix_max
real(mcp), dimension(max_cols) limmin
real(mcp), dimension(max_cols) limmax
real(mcp), dimension(max_cols) center
real(mcp), dimension(max_cols) param_min
real(mcp), dimension(max_cols) param_max
real(mcp), dimension(max_cols) range_min
real(mcp), dimension(max_cols) range_max
logical bw
logical do_shading
type(tstringlist), save compareplots
logical prob_label = .false.
logical plots_only
logical no_plots
real(mcp) smooth_scale_1d =-1.d0
real(mcp) smooth_scale_2d = 1.d0
real(mcp) credible_interval_threshold = 0.05d0
integer boundary_correction_method = 1
Function/Subroutine Documentation
adjustpriors()
subroutine mcsamples::adjustpriors ()
Referenced by getdist().
checkmatlabaxes()
subroutine mcsamples::checkmatlabaxes (integer, intent(in) afile)
Referenced by getdist().
confidval()
real(mcp) function mcsamples::confidval (integer, intent(in) ix, real(mcp), intent(in) limfrac, logical, intent(in) upper, integer, intent(in), optional ix1, integer, intent(in), optional ix2)
References coldata, and nrows.
Referenced by doconvergetests(), get1ddensity(), and getdist().
coolchain()
subroutine mcsamples::coolchain (real(mcp), intent(in) cool)
References coldata, and nrows.
Referenced by getdist().
dat_file_2d()
character(len=:) function, allocatable mcsamples::dat_file_2d (character(len=*) rootname, integer, intent(in) j, integer, intent(in) j2)
References colix, and namemapping.
Referenced by get2dplotdata(), and plotcontmatlab().
dat_file_name()
character(len= :) function, allocatable mcsamples::dat_file_name (character(len=*) rootname, integer, intent(in) j)
References colix, and namemapping.
Referenced by get1ddensity(), and write1dplotmatlab().
deletezeros()
subroutine mcsamples::deletezeros ()
References coldata, and nrows.
Referenced by getdist().
dinvnorm()
real(mcp) function mcsamples::dinvnorm (real(mcp) p)
Referenced by getdist().
doconvergetests()
subroutine mcsamples::doconvergetests (real(mcp), intent(in) limfrac)
References chain_indices, chain_numbers, coldata, confidval(), corr_length_steps, corr_length_thin, covmat_dimension, force_twotail, samples::gelmanrubinevalues(), getfractionindices(), has_limits, indep_thin, isused, labels, mean_mult, ncols, nrows, num_chains_used, numsamp, rootdirname, thin_ix, thin_rows, thindata(), and writes().
Referenced by getdist().
edgewarning()
subroutine mcsamples::edgewarning (integer, intent(in) param)
References namemapping, and writes().
Referenced by get1ddensity().
get1ddensity()
subroutine mcsamples::get1ddensity (integer j)
References boundary_correction_method, center, coldata, colix, confidval(), dat_file_name(), density1d, edgewarning(), float_format, has_limits, has_limits_bot, has_limits_top, ix_max, ix_min, limmax, limmin, settings::logzero, max_mult, mean_loglikes, meanlike, namemapping, nd_limit_bot, nd_limit_top, no_plots, nrows, num_bins, numsamp, param_max, param_min, plot_data_dir, plot_meanlikes, range_max, range_min, settings::rootname, sddev, and smooth_scale_1d.
Referenced by getdist().
get2dplotdata()
subroutine mcsamples::get2dplotdata (integer, intent(in) j, integer, intent(in) j2)
References center, coldata, colix, contours, corrmatrix, dat_file_2d(), float_format, has_limits, has_limits_bot, has_limits_top, meanlike, nrows, num_bins_2d, num_contours, plot_data_dir, range_max, range_min, shade_meanlikes, and smooth_scale_2d.
Referenced by getdist().
getchainlikesummary()
subroutine mcsamples::getchainlikesummary (integer unit)
References bestfit_ix, coldata, maxlike, meanlike, nrows, and numsamp.
Referenced by getdist().
getcovmatrix()
subroutine mcsamples::getcovmatrix ()
References coldata, corrmatrix, covmat_dimension, io::io_writeproposematrix(), isused, matrixutils::matrix_write(), namemapping, ncols, nrows, numsamp, plots_only, and rootdirname.
Referenced by getdist().
getfractionindices()
subroutine mcsamples::getfractionindices (integer, dimension(*) fraction_indices, integer, intent(in) n)
References coldata, nrows, and numsamp.
Referenced by doconvergetests().
getusedcols()
subroutine mcsamples::getusedcols ()
References coldata, isused, ncols, and nrows.
Referenced by getdist().
makesinglesamples()
subroutine mcsamples::makesinglesamples (integer single_thin)
References coldata, colix, settings::feedback, float_format, randutils::initrandom(), nrows, num_vars, plot_data_dir, randutils::ranmar(), and settings::rootname.
Referenced by getdist().
mapparameters()
subroutine mcsamples::mapparameters (real(gp), dimension(1:ncols) invars)
Referenced by getdist().
matlablabel()
character(len=:) function, allocatable mcsamples::matlablabel (integer, intent(in) i)
References labels, and matlab_latex.
Referenced by getdist(), and write2dplotmatlab().
mostcorrelated2d()
integer function mcsamples::mostcorrelated2d (integer, intent(in) i1, integer, intent(in) i2, integer, intent(in) direc)
References colix, corrmatrix, matrixutils::matrix_diagonalize(), and arrayutils::maxindex().
pca()
subroutine mcsamples::pca (integer, dimension(n), intent(in) pars, integer, intent(in) n, character(len=*), intent(in) param_map, integer, intent(in) normparam_num)
References coldata, colix, arrayutils::indexof(), labels, matrixutils::matrix_diagonalize(), mean, nd_cont1, nd_cont2, nrows, num_vars, numsamp, rootdirname, and sddev.
Referenced by getdist().
plotcontmatlab()
logical function mcsamples::plotcontmatlab (integer, intent(in) aunit, character(len=*), intent(in) aroot, integer, intent(in) j, integer, intent(in) j2, logical, intent(in) DoShade)
References dat_file_2d(), num_contours, plot_data_dir, and shade_meanlikes.
Referenced by write2dplotmatlab().
python_param_array()
character(len=:) function, allocatable mcsamples::python_param_array (integer, dimension(:), intent(in) params, integer, intent(in) num)
References quoted_param_name_used().
Referenced by getdist().
quoted_param_name()
character(len=:) function, allocatable mcsamples::quoted_param_name (integer, intent(in) j)
References namemapping.
Referenced by getdist(), and quoted_param_name_used().
quoted_param_name_used()
character(len=:) function, allocatable mcsamples::quoted_param_name_used (integer, intent(in) j)
References colix, and quoted_param_name().
Referenced by getdist(), and python_param_array().
sortcoldata()
subroutine mcsamples::sortcoldata (integer, intent(in) bycol)
References coldata, ncols, and nrows.
Referenced by getdist().
thindata()
subroutine mcsamples::thindata (integer, intent(in) fac, integer, intent(in), optional ix1, integer, intent(in), optional ix2)
References coldata, nrows, numsamp, thin_ix, and thin_rows.
Referenced by doconvergetests(), and getdist().
write1dplotmatlab()
subroutine mcsamples::write1dplotmatlab (integer, intent(in) aunit, integer, intent(in) j)
References colix, compareplots, dat_file_name(), has_markers, markers, plot_data_dir, and plot_meanlikes.
Referenced by getdist().
write2dplotmatlab()
subroutine mcsamples::write2dplotmatlab (integer, intent(in) aunit, integer, intent(in) j, integer, intent(in) j2, logical, intent(in) DoLabelx, logical, intent(in) DoLabely, logical, intent(in), optional hide_ticklabels)
References colix, compareplots, do_shading, matlablabel(), num_contours, and plotcontmatlab().
Referenced by getdist().
writematlablinelabels()
subroutine mcsamples::writematlablinelabels (class(ttextfile) F)
References compareplots.
Referenced by getdist().
writeplotfileexport()
subroutine mcsamples::writeplotfileexport (integer, intent(in) unit, character(len=*), intent(in) tag, integer, intent(in) plot_col, integer, intent(in) plot_row)
References plot_ext, and plot_output.
Referenced by getdist().
writeplotfileinit()
subroutine mcsamples::writeplotfileinit (integer, intent(in) unit, logical, intent(in) sm, real, intent(in) subplot_size)
References bw, compareplots, font_scale, matlab_latex, out_dir, plot_data_dir, plot_ext, and plot_meanlikes.
Referenced by getdist().
writes()
subroutine mcsamples::writes (character(len=*), intent(in) S)
Referenced by doconvergetests(), and edgewarning().
writethindata()
subroutine mcsamples::writethindata (character(len=*), intent(in) fname, real(mcp), intent(in) cool)
References coldata, float_format, ncols, nrows, thin_ix, and thin_rows.
Referenced by getdist().
Variable Documentation
bestfit_ix
integer mcsamples::bestfit_ix
Referenced by getchainlikesummary(), and getdist().
boundary_correction_method
integer mcsamples::boundary_correction_method = 1
Referenced by get1ddensity(), and getdist().
bw
logical mcsamples::bw
Referenced by dopksmoothbspline_(), getdist(), and writeplotfileinit().
center
real(mcp), dimension(max_cols) mcsamples::center
Referenced by get1ddensity(), and get2dplotdata().
chain_indices
integer, dimension(max_chains) mcsamples::chain_indices
Referenced by doconvergetests(), and getdist().
chain_numbers
integer, dimension(max_chains) mcsamples::chain_numbers
Referenced by doconvergetests(), and getdist().
coldata
real(gp), dimension(:,:), allocatable mcsamples::coldata
Referenced by confidval(), coolchain(), deletezeros(), doconvergetests(), get1ddensity(), get2dplotdata(), getchainlikesummary(), getcovmatrix(), getdist(), getfractionindices(), getusedcols(), makesinglesamples(), pca(), sortcoldata(), thindata(), and writethindata().
colix
integer, dimension(max_cols) mcsamples::colix
Referenced by dat_file_2d(), dat_file_name(), get1ddensity(), get2dplotdata(), getdist(), makesinglesamples(), mostcorrelated2d(), pca(), quoted_param_name_used(), write1dplotmatlab(), and write2dplotmatlab().
compareplots
type(tstringlist), save mcsamples::compareplots
Referenced by getdist(), write1dplotmatlab(), write2dplotmatlab(), writematlablinelabels(), and writeplotfileinit().
contours
real(mcp), dimension(max_contours) mcsamples::contours
Referenced by get2dplotdata(), and getdist().
corr_length_steps
integer mcsamples::corr_length_steps = 15
Referenced by doconvergetests(), and getdist().
corr_length_thin
integer mcsamples::corr_length_thin = 0
Referenced by doconvergetests(), and getdist().
corrmatrix
real(mcp), dimension(:,:), allocatable mcsamples::corrmatrix
Referenced by get2dplotdata(), getcovmatrix(), getdist(), and mostcorrelated2d().
covmat_dimension
integer mcsamples::covmat_dimension
Referenced by doconvergetests(), getcovmatrix(), and getdist().
credible_interval_threshold
real(mcp) mcsamples::credible_interval_threshold = 0.05d0
Referenced by getdist().
cust2dplots
integer, dimension(max_cols**2) mcsamples::cust2dplots
Referenced by getdist().
density1d
type(tdensity1d) mcsamples::density1d
Referenced by get1ddensity(), and getdist().
do_shading
logical mcsamples::do_shading
Referenced by getdist(), and write2dplotmatlab().
float_format
character(len=*), parameter mcsamples::float_format = '(*(E16.7))'
Referenced by get1ddensity(), get2dplotdata(), makesinglesamples(), and writethindata().
font_scale
real(mcp) mcsamples::font_scale = 1.
Referenced by getdist(), and writeplotfileinit().
force_twotail
logical mcsamples::force_twotail
Referenced by doconvergetests(), and getdist().
gp
integer, parameter mcsamples::gp = KIND(1.d0)
has_limits
logical, dimension(max_cols) mcsamples::has_limits
Referenced by doconvergetests(), get1ddensity(), and get2dplotdata().
has_limits_bot
logical, dimension(max_cols) mcsamples::has_limits_bot
Referenced by get1ddensity(), get2dplotdata(), and getdist().
has_limits_top
logical, dimension(max_cols) mcsamples::has_limits_top
Referenced by get1ddensity(), get2dplotdata(), and getdist().
has_markers
logical, dimension(max_cols) mcsamples::has_markers
Referenced by getdist(), and write1dplotmatlab().
in_root
character(len=:), allocatable mcsamples::in_root
Referenced by getdist().
indep_thin
integer mcsamples::indep_thin = 0
Referenced by doconvergetests(), and getdist().
isused
logical, dimension(max_cols) mcsamples::isused
Referenced by doconvergetests(), getcovmatrix(), getdist(), and getusedcols().
ix_max
integer, dimension(max_cols) mcsamples::ix_max
Referenced by get1ddensity(), and getdist().
ix_min
integer, dimension(max_cols) mcsamples::ix_min
Referenced by get1ddensity(), and getdist().
labels
character(len=128), dimension(max_cols) mcsamples::labels
Referenced by doconvergetests(), getdist(), matlablabel(), and pca().
limmax
real(mcp), dimension(max_cols) mcsamples::limmax
Referenced by get1ddensity(), and getdist().
limmin
real(mcp), dimension(max_cols) mcsamples::limmin
Referenced by get1ddensity(), and getdist().
make_single_samples
logical mcsamples::make_single_samples
Referenced by getdist().
marge_limits_bot
logical, dimension(max_contours, max_cols) mcsamples::marge_limits_bot
Referenced by getdist().
marge_limits_top
logical, dimension(max_contours, max_cols) mcsamples::marge_limits_top
Referenced by getdist().
markers
real(mcp), dimension(max_cols) mcsamples::markers
Referenced by getdist(), and write1dplotmatlab().
matlab_latex
logical mcsamples::matlab_latex = .false.
Referenced by getdist(), matlablabel(), and writeplotfileinit().
matlab_version
real(mcp) mcsamples::matlab_version
Referenced by getdist().
max_chains
integer, parameter mcsamples::max_chains = 100
Referenced by getdist().
max_cols
integer, parameter mcsamples::max_cols = 500
max_contours
integer, parameter mcsamples::max_contours = 5
max_frac_twotail
real(mcp), dimension(max_contours) mcsamples::max_frac_twotail
Referenced by getdist().
max_mult
real(mcp) mcsamples::max_mult
Referenced by get1ddensity(), and getdist().
max_rows
integer, parameter mcsamples::max_rows = 500000
Referenced by getdist().
max_split_tests
integer, parameter mcsamples::max_split_tests = 4
maxlike
real(mcp) mcsamples::maxlike
Referenced by getchainlikesummary().
mean
real(mcp), dimension(max_cols) mcsamples::mean
Referenced by getdist(), and pca().
mean_loglikes
logical mcsamples::mean_loglikes = .false.
Referenced by get1ddensity().
mean_mult
real(mcp) mcsamples::mean_mult
Referenced by doconvergetests(), and getdist().
meanlike
real(mcp) mcsamples::meanlike
Referenced by get1ddensity(), get2dplotdata(), and getchainlikesummary().
namemapping
type(tparamnames), save mcsamples::namemapping
Referenced by dat_file_2d(), dat_file_name(), edgewarning(), get1ddensity(), getcovmatrix(), getdist(), and quoted_param_name().
ncols
integer mcsamples::ncols
Referenced by doconvergetests(), getcovmatrix(), getdist(), getusedcols(), sortcoldata(), and writethindata().
nd_cont1
integer mcsamples::nd_cont1
Referenced by getdist(), and pca().
nd_cont2
integer mcsamples::nd_cont2
Referenced by getdist(), and pca().
nd_limit_bot
real(mcp), dimension(:,:), allocatable mcsamples::nd_limit_bot
Referenced by get1ddensity(), and getdist().
nd_limit_top
real(mcp), dimension(:,:), allocatable mcsamples::nd_limit_top
Referenced by get1ddensity(), and getdist().
no_plots
logical mcsamples::no_plots
Referenced by get1ddensity(), and getdist().
nrows
integer mcsamples::nrows
Referenced by confidval(), coolchain(), deletezeros(), doconvergetests(), get1ddensity(), get2dplotdata(), getchainlikesummary(), getcovmatrix(), getdist(), getfractionindices(), getusedcols(), makesinglesamples(), pca(), sortcoldata(), thindata(), and writethindata().
num_bins
integer mcsamples::num_bins
Referenced by get1ddensity(), and getdist().
num_bins_2d
integer mcsamples::num_bins_2d
Referenced by get2dplotdata(), and getdist().
num_chains_used
integer mcsamples::num_chains_used
Referenced by doconvergetests(), and getdist().
num_contours
integer mcsamples::num_contours
Referenced by get2dplotdata(), getdist(), plotcontmatlab(), and write2dplotmatlab().
num_vars
integer mcsamples::num_vars
Referenced by getdist(), makesinglesamples(), and pca().
numsamp
real(mcp) mcsamples::numsamp
Referenced by doconvergetests(), get1ddensity(), getchainlikesummary(), getcovmatrix(), getdist(), getfractionindices(), pca(), and thindata().
out_dir
character(len=:), allocatable mcsamples::out_dir
Referenced by getdist(), and writeplotfileinit().
param_max
real(mcp), dimension(max_cols) mcsamples::param_max
Referenced by get1ddensity().
param_min
real(mcp), dimension(max_cols) mcsamples::param_min
Referenced by get1ddensity().
plot_data_dir
character(len=:), allocatable mcsamples::plot_data_dir
Referenced by get1ddensity(), get2dplotdata(), getdist(), makesinglesamples(), plotcontmatlab(), write1dplotmatlab(), and writeplotfileinit().
plot_ext
character(len=3) mcsamples::plot_ext = 'm'
Referenced by getdist(), writeplotfileexport(), and writeplotfileinit().
plot_meanlikes
logical mcsamples::plot_meanlikes
Referenced by get1ddensity(), getdist(), write1dplotmatlab(), and writeplotfileinit().
plot_output
character(len=3) mcsamples::plot_output = 'pdf'
Referenced by getdist(), and writeplotfileexport().
plots_only
logical mcsamples::plots_only
Referenced by getcovmatrix(), and getdist().
pname
character(len=128), dimension(max_cols) mcsamples::pname
Referenced by getdist().
prior_ranges
real(mcp), dimension(2,max_cols) mcsamples::prior_ranges
Referenced by getdist().
prob_label
logical mcsamples::prob_label = .false.
Referenced by getdist().
range_max
real(mcp), dimension(max_cols) mcsamples::range_max
Referenced by get1ddensity(), get2dplotdata(), and getdist().
range_min
real(mcp), dimension(max_cols) mcsamples::range_min
Referenced by get1ddensity(), get2dplotdata(), and getdist().
rootdirname
character(len=:), allocatable mcsamples::rootdirname
Referenced by doconvergetests(), getcovmatrix(), getdist(), and pca().
sddev
real(mcp), dimension(max_cols) mcsamples::sddev
Referenced by get1ddensity(), getdist(), and pca().
shade_meanlikes
logical mcsamples::shade_meanlikes
Referenced by get2dplotdata(), getdist(), and plotcontmatlab().
single_thin
integer mcsamples::single_thin
Referenced by getdist().
smooth_scale_1d
real(mcp) mcsamples::smooth_scale_1d =-1.d0
Referenced by get1ddensity(), and getdist().
smooth_scale_2d
real(mcp) mcsamples::smooth_scale_2d = 1.d0
Referenced by get2dplotdata(), and getdist().
subplot_size_inch
real mcsamples::subplot_size_inch = 3.0
Referenced by getdist().
subplot_size_inch2
real mcsamples::subplot_size_inch2
Referenced by getdist().
subplot_size_inch3
real mcsamples::subplot_size_inch3
Referenced by getdist().
thin_ix
integer, dimension(:), allocatable mcsamples::thin_ix
Referenced by doconvergetests(), thindata(), and writethindata().
thin_rows
integer mcsamples::thin_rows
Referenced by doconvergetests(), thindata(), and writethindata().