cosmomc_bde_v3p1: io Module Reference
io Module Reference
Functions/Subroutines
subroutine io_writeproposematrix (pmat, prop_mat, comment)
subroutine io_readproposematrix (NameMapping, pmat, prop_mat)
subroutine io_outputchainrow (F, mult, like, values)
logical function io_readchainrow (F, mult, like, values, params_used, chainOK, samples_chains)
subroutine io_readlastchainparams (name, mult, like, values, params_used)
subroutine io_outputparamnames (Names, fname, indices, add_derived)
subroutine io_writebounds (Names, fname, limmin, limmax, limbot, limtop, indices)
subroutine io_readparamnames (Names, in_root, prior_ranges)
logical function io_readchainrows (in_root, chain_ix, chain_num, ignorerows, nrows, ncols, max_rows, coldata, samples_are_chains, noerror)
subroutine io_outputmargestats (Names, froot, num_vars, num_contours, contours_str, cont_lines, colix, mean, sddev, has_limits_bot, has_limits_top, labels)
Function/Subroutine Documentation
io_outputchainrow()
subroutine io::io_outputchainrow (class(tfilestream) F, real(mcp) mult, real(mcp) like, real(mcp), dimension(:) values)
References settings::flush_write.
Referenced by generaltypes::tcalculationatparampoint_writeparams().
io_outputmargestats()
subroutine io::io_outputmargestats (class(tparamnames) Names, character(len=*), intent(in) froot, integer, intent(in) num_vars, integer, intent(in) num_contours, character(len=*), intent(in) contours_str, real(mcp), dimension(:,:,:), intent(in) cont_lines, integer, dimension(*), intent(in) colix, real(mcp), dimension(*), intent(in) mean, real(mcp), dimension(*), intent(in) sddev, logical, dimension(:,:), intent(in) has_limits_bot, logical, dimension(:,:), intent(in) has_limits_top, character(len=128), dimension(*) labels)
Referenced by getdist().
io_outputparamnames()
subroutine io::io_outputparamnames (class(tparamnames) Names, character(len=*), intent(in) fname, integer, dimension(:), intent(in), optional indices, logical, intent(in), optional add_derived)
io_readchainrow()
logical function io::io_readchainrow (class(ttextfile) F, real(mcp), intent(out) mult, real(mcp), intent(out) like, real(mcp), dimension(:), intent(out) values, integer, dimension(:), intent(in) params_used, logical, intent(out), optional chainOK, logical, intent(in), optional samples_chains)
References settings::params_used.
Referenced by io_readchainrows(), and importancesampling::timportancesampler_importancesample().
io_readchainrows()
logical function io::io_readchainrows (character(len=*), intent(in) in_root, integer, intent(in) chain_ix, integer, intent(in) chain_num, integer, intent(in) ignorerows, integer, intent(inout) nrows, integer, intent(in) ncols, integer, intent(in) max_rows, real(kind(1.d0)), dimension(:,:), intent(inout), allocatable coldata, logical, intent(in) samples_are_chains, logical, intent(in) noerror)
References io_readchainrow().
Referenced by getdist().
io_readlastchainparams()
subroutine io::io_readlastchainparams (character(len=*), intent(in) name, real(mcp), intent(out) mult, real(mcp), intent(out) like, real(mcp), dimension(:), intent(out) values, integer, dimension(:), intent(in) params_used)
References fileutils::file.
Referenced by generalsetup::tsetup_dosampling().
io_readparamnames()
subroutine io::io_readparamnames (class(tparamnames) Names, character(len=*), intent(in) in_root, real(mcp), dimension(:,:) prior_ranges)
References fileutils::file.
Referenced by getdist().
io_readproposematrix()
subroutine io::io_readproposematrix (class(tparamnames) NameMapping, real(mcp), dimension(:,:) pmat, character(len=*), intent(in) prop_mat)
References fileutils::file, settings::num_params, and settings::num_theory_params.
io_writebounds()
subroutine io::io_writebounds (class(tparamnames) Names, character(len=*), intent(in) fname, real(mcp), dimension(:), intent(in) limmin, real(mcp), dimension(:), intent(in) limmax, logical, dimension(:), intent(in) limbot, logical, dimension(:), intent(in) limtop, integer, dimension(:), intent(in) indices)
Referenced by getdist().
io_writeproposematrix()
subroutine io::io_writeproposematrix (real(mcp), dimension(:,:) pmat, character(len=*), intent(in) prop_mat, character(len=*), intent(in), optional comment)
References matrixutils::matrix_write().
Referenced by mcsamples::getcovmatrix().