cosmomc_bde_v3p1: listtests Module Reference
listtests Module Reference
Data Types
type object_pointer
Functions/Subroutines
integer function runlisttests ()
subroutine test_treallist (fails)
subroutine test_trealarraylist (fails)
subroutine readwrite (T)
subroutine test_tstringlist (fails)
Variables
character(len=0), target empty_string = ''
Function/Subroutine Documentation
readwrite()
subroutine listtests::readwrite (class(tobjectlist) T)
Referenced by test_tstringlist().
runlisttests()
integer function listtests::runlisttests ()
References test_trealarraylist(), test_treallist(), and test_tstringlist().
Referenced by tester().
test_trealarraylist()
subroutine listtests::test_trealarraylist (integer fails)
Referenced by runlisttests().
test_treallist()
subroutine listtests::test_treallist (integer fails)
Referenced by runlisttests().
test_tstringlist()
subroutine listtests::test_tstringlist (integer fails)
References readwrite().
Referenced by runlisttests().
Variable Documentation
empty_string
character(len=0), target listtests::empty_string = ''