cosmomc_bde_v3p1: datalikelihoodlist Module Reference
datalikelihoodlist Module Reference
Functions/Subroutines
subroutine setdatalikelihoods (Ini)
Function/Subroutine Documentation
setdatalikelihoods()
subroutine datalikelihoodlist::setdatalikelihoods (class(tsettingini), intent(in) Ini)
References elementabundances::abundancelikelihood_add(), bao::baolikelihood_add(), cmblikelihoods::cmblikelihood_add(), cosmologytypes::cosmosettings, hst::hstlikelihood_add(), mpk::mpklikelihood_add(), snovae::snlikelihood_add(), szcounts::szlikelihood_add(), mpk::use_mpk, wigglez::wigglezlikelihood_add(), and wl::wllikelihood_add().