cosmomc_bde_v3p1: randutils Module Reference
randutils Module Reference
Data Types
interface randrotation
Functions/Subroutines
subroutine initrandom (i, i2)
subroutine randindices (indices, nmax, n)
subroutine randrotations (R, N)
subroutine randrotationd (R, N)
double precision function gaussian1 ()
double precision function cauchy1 ()
real function randexp1 ()
subroutine rmarin (IJ, KL)
double precision function ranmar ()
Variables
integer rand_inst = 0
integer, parameter krand = KIND(1.d0)
integer rand_feedback = 1
Function/Subroutine Documentation
cauchy1()
double precision function randutils::cauchy1 ()
References gaussian1().
gaussian1()
double precision function randutils::gaussian1 ()
References ranmar().
Referenced by cauchy1(), propose::propose_r(), randrotationd(), and baseparameters::tbaseparameters_setstartpositions().
initrandom()
subroutine randutils::initrandom (integer, intent(in), optional i, integer, intent(in), optional i2)
References mpiutils::mpistop(), rand_feedback, rand_inst, and rmarin().
Referenced by mcsamples::makesinglesamples().
randexp1()
real function randutils::randexp1 ()
References ranmar().
Referenced by propose::propose_r(), and montecarlo::tchainsampler_metropolisaccept().
randindices()
subroutine randutils::randindices (integer, dimension(n) indices, integer, intent(in) nmax, integer, intent(in) n)
References mpiutils::mpistop(), and ranmar().
Referenced by propose::next().
randrotationd()
subroutine randutils::randrotationd (double precision, dimension(n,n) R, integer, intent(in) N)
References gaussian1().
randrotations()
subroutine randutils::randrotations (real, dimension(n,n) R, integer, intent(in) N)
ranmar()
double precision function randutils::ranmar ()
Referenced by gaussian1(), mcsamples::makesinglesamples(), propose::propose_r(), randexp1(), and randindices().
rmarin()
subroutine randutils::rmarin (integer IJ, integer KL)
Referenced by initrandom().
Variable Documentation
krand
integer, parameter randutils::krand = KIND(1.d0)
rand_feedback
integer randutils::rand_feedback = 1
Referenced by initrandom().
rand_inst
integer randutils::rand_inst = 0
Referenced by initrandom().