cosmomc_bde_v3p1: chainDumpPlot Namespace Reference
chainDumpPlot Namespace Reference
Functions
def loadFiles (pat, max_files=400, cl_ix=1, calParam=None, rescale=1)
def CLdensity (samples, param, scalarMap, nbins=300, deltaL=1, Lmax=200, color_pow=0.25)
def truncate_colormap (cmap, minval=0.0, maxval=1.0, n=200)
def getColorMap (parvals, parname)
def setLabels (scalarMap, cNorm, par)
def rainbowLinePlot (ls, pars, cls, parname, lpow=2, delta_to=None, last_colors=None, alpha=1)
def rainbowDensityPlot (ls, pars, cls, parname, lpow=2, delta_to=None, Lmax=200, color_pow=0.25, last_colors=None)
Variables
int colorbar_label_rotation_angle = -90
bool colorbar_tick_label_vertical = False
dictionary label_dict = {}
color_ticks = None
color_ticklabels = None
Function Documentation
CLdensity()
def chainDumpPlot.CLdensity (samples, param, scalarMap, nbins = 300, deltaL = 1, Lmax = 200, color_pow = 0.25)
Referenced by rainbowDensityPlot().
getColorMap()
def chainDumpPlot.getColorMap (parvals, parname)
References truncate_colormap().
Referenced by rainbowDensityPlot(), and rainbowLinePlot().
loadFiles()
def chainDumpPlot.loadFiles (pat, max_files = 400, cl_ix = 1, calParam = None, rescale = 1)
rainbowDensityPlot()
def chainDumpPlot.rainbowDensityPlot (ls, pars, cls, parname, lpow = 2, delta_to = None, Lmax = 200, color_pow = 0.25, last_colors = None)
References CLdensity(), getColorMap(), and setLabels().
rainbowLinePlot()
def chainDumpPlot.rainbowLinePlot (ls, pars, cls, parname, lpow = 2, delta_to = None, last_colors = None, alpha = 1)
References getColorMap(), setLabels(), and copyGridFiles.zip.
setLabels()
def chainDumpPlot.setLabels (scalarMap, cNorm, par)
Referenced by rainbowDensityPlot(), and rainbowLinePlot().
truncate_colormap()
def chainDumpPlot.truncate_colormap (cmap, minval = 0.0, maxval = 1.0, n = 200)
References GetDistGUI.format.
Referenced by getColorMap().
Variable Documentation
color_ticklabels
chainDumpPlot.color_ticklabels = None
color_ticks
chainDumpPlot.color_ticks = None
colorbar_label_rotation_angle
int chainDumpPlot.colorbar_label_rotation_angle = -90
colorbar_tick_label_vertical
bool chainDumpPlot.colorbar_tick_label_vertical = False
label_dict
dictionary chainDumpPlot.label_dict = {}