cosmomc_bde_v3p1: interpolationtests Module Reference
interpolationtests Module Reference
Functions/Subroutines
real(sp) function func (x)
real(sp) function funcderiv (x)
integer function runinterpolationtests ()
Variables
integer, parameter, private sp = KIND(1.d0)
Function/Subroutine Documentation
func()
real(sp) function interpolationtests::func (real(sp) x)
Referenced by runinterpolationtests(), and camb.baseconfig::set_filelocs().
funcderiv()
real(sp) function interpolationtests::funcderiv (real(sp) x)
Referenced by runinterpolationtests().
runinterpolationtests()
integer function interpolationtests::runinterpolationtests ()
References fileutils::file, func(), and funcderiv().
Referenced by tester().
Variable Documentation
sp
integer, parameter, private interpolationtests::sp = KIND(1.d0) private