cosmomc_bde_v3p1: snovae Module Reference
snovae Module Reference
Functions/Subroutines
subroutine snlikelihood_add (LikeList, Ini)
Function/Subroutine Documentation
snlikelihood_add()
subroutine snovae::snlikelihood_add (class(tlikelihoodlist) LikeList, class(tsettingini) Ini)
References jla::jlalikelihood_add(), snls::snlslikelihood_add(), and union2::union2likelihood_add().
Referenced by datalikelihoodlist::setdatalikelihoods().