cosmomc_bde_v3p1: planckStyle Namespace Reference
planckStyle Namespace Reference
Classes
class planckPlotter
class planckStyleTableFormatter
Functions
def setRc ()
def planck_lensing (omm, sigma)
def plotBounds (omm, data, c='gray')
def getPlotter (plot_data=None, chain_dir=None, kwargs)
def getSubplotPlotter (plot_data=None, chain_dir=None, subplot_size=2, kwargs)
def getPlotterWidth (size=1, kwargs)
def getSinglePlotter (ratio=3/4., plot_data=None, chain_dir=None, width_inch=3.464, kwargs)
Variables
dictionary params
string sfmath = os.path.dirname(os.path.abspath(__file__)) + os.sep + 'sfmath'
bool non_final = True
string version = 'CamSpec v910HM'
string defdata_root = 'CamSpecHM'
datalabel = dict()
string defdata_TT = defdata_root + '_TT_lowTEB'
string defdata_TE = defdata_root + '_TE_lowEB'
string defdata_EE = defdata_root + '_EE_lowEB'
string defdata_TE_TEB = defdata_root + '_TE_lowTEB'
string defdata_EE_TEB = defdata_root + '_EE_lowTEB'
string defdata_all = defdata_root + '_TTTEEE_lowTEB'
string defdata_TTTEEE = defdata_all
string defdata_TTonly = defdata_root + '_TT_lowl'
string defdata_allNoLowE = defdata_root + '_TTTEEE_lowl'
string defdata = defdata_TT
deflabel = datalabel[defdata_TT]
string defdata_lensing = defdata_TT + '_lensing'
string defdata_all_lensing = defdata_all + '_lensing'
string planck = r'\textit{Planck}'
planckTT = datalabel[defdata_TTonly]
planckTTlowTEB = datalabel[defdata_TT]
planckall = datalabel[defdata_all]
NoLowLE = datalabel[defdata_allNoLowE]
lensing = datalabel[defdata_lensing]
lensingall = datalabel[defdata_all_lensing]
defplanck = datalabel[defdata]
dictionary shortlabel = {}
string NoLowLhighLtau = r'\textit{Planck}$-$lowL+highL+$\tau$prior'
string NoLowLhighL = r'\textit{Planck}$-$lowL+highL'
string WPhighLlensing = r'\textit{Planck}+lensing+WP+highL'
string WP = r'\textit{Planck}+WP'
string WPhighL = r'\textit{Planck}+WP+highL'
string NoLowL = r'\textit{Planck}$-$lowL'
string lensonly = 'lensing'
string HST = r'$H_0$'
string BAO = 'BAO'
string LCDM = r'$\Lambda$CDM'
s = copy.copy(plots.defaultSettings)
legend_frame
figure_legend_frame
prob_label
norm_prob_label
prob_y_ticks
param_names_for_labels
alpha_filled_add
solid_contour_palefactor
solid_colors
axis_marker_lw
lw_contour
use_plot_data = getdist.use_plot_data
rootdir = getdist.default_grid_root or os.path.join(batchjob.getCodeRootPath(), 'main')
output_base_dir = getdist.output_base_dir or batchjob.getCodeRootPath()
list H0_gpe = [70.6, 3.3]
Function Documentation
getPlotter()
def planckStyle.getPlotter (plot_data = None, chain_dir = None, kwargs)
References setRc().
Referenced by getPlotterWidth(), getSinglePlotter(), and getSubplotPlotter().
getPlotterWidth()
def planckStyle.getPlotterWidth (size = 1, kwargs)
References getPlotter().
getSinglePlotter()
def planckStyle.getSinglePlotter (ratio = 3 / 4., plot_data = None, chain_dir = None, width_inch = 3.464, kwargs)
References getPlotter().
getSubplotPlotter()
def planckStyle.getSubplotPlotter (plot_data = None, chain_dir = None, subplot_size = 2, kwargs)
References getPlotter().
planck_lensing()
def planckStyle.planck_lensing (omm, sigma)
plotBounds()
def planckStyle.plotBounds (omm, data, c = 'gray')
References makePlots.data.
setRc()
def planckStyle.setRc ()
Referenced by getPlotter().
Variable Documentation
alpha_filled_add
planckStyle.alpha_filled_add
axis_marker_lw
planckStyle.axis_marker_lw
BAO
string planckStyle.BAO = 'BAO'
datalabel
planckStyle.datalabel = dict()
defdata
string planckStyle.defdata = defdata_TT
defdata_all
string planckStyle.defdata_all = defdata_root + '_TTTEEE_lowTEB'
defdata_all_lensing
string planckStyle.defdata_all_lensing = defdata_all + '_lensing'
defdata_allNoLowE
string planckStyle.defdata_allNoLowE = defdata_root + '_TTTEEE_lowl'
defdata_EE
string planckStyle.defdata_EE = defdata_root + '_EE_lowEB'
defdata_EE_TEB
string planckStyle.defdata_EE_TEB = defdata_root + '_EE_lowTEB'
defdata_lensing
string planckStyle.defdata_lensing = defdata_TT + '_lensing'
defdata_root
string planckStyle.defdata_root = 'CamSpecHM'
defdata_TE
string planckStyle.defdata_TE = defdata_root + '_TE_lowEB'
defdata_TE_TEB
string planckStyle.defdata_TE_TEB = defdata_root + '_TE_lowTEB'
defdata_TT
string planckStyle.defdata_TT = defdata_root + '_TT_lowTEB'
defdata_TTonly
string planckStyle.defdata_TTonly = defdata_root + '_TT_lowl'
defdata_TTTEEE
string planckStyle.defdata_TTTEEE = defdata_all
deflabel
planckStyle.deflabel = datalabel[defdata_TT]
defplanck
planckStyle.defplanck = datalabel[defdata]
figure_legend_frame
planckStyle.figure_legend_frame
H0_gpe
list planckStyle.H0_gpe = [70.6, 3.3]
HST
string planckStyle.HST = r'$H_0$'
LCDM
string planckStyle.LCDM = r'$\Lambda$CDM'
legend_frame
planckStyle.legend_frame
lensing
planckStyle.lensing = datalabel[defdata_lensing]
lensingall
planckStyle.lensingall = datalabel[defdata_all_lensing]
lensonly
string planckStyle.lensonly = 'lensing'
lw_contour
planckStyle.lw_contour
NoLowL
string planckStyle.NoLowL = r'\textit{Planck}$-$lowL'
NoLowLE
planckStyle.NoLowLE = datalabel[defdata_allNoLowE]
NoLowLhighL
string planckStyle.NoLowLhighL = r'\textit{Planck}$-$lowL+highL'
NoLowLhighLtau
string planckStyle.NoLowLhighLtau = r'\textit{Planck}$-$lowL+highL+$\tau$prior'
non_final
bool planckStyle.non_final = True
norm_prob_label
planckStyle.norm_prob_label
output_base_dir
planckStyle.output_base_dir = getdist.output_base_dir or batchjob.getCodeRootPath()
param_names_for_labels
planckStyle.param_names_for_labels
params
dictionary planckStyle.params
Initial value:
 =  {'backend': 'pdf',
           'axes.labelsize': 9,
           'font.size': 8,
           'legend.fontsize': 8,
           'xtick.labelsize': 8,
           'ytick.labelsize': 8,
           'ytick.major.pad': 4,
           'xtick.major.pad': 4,
           'text.usetex': True,
           'font.family':'sans-serif',
           # free font similar to Helvetica
           'font.sans-serif':'FreeSans'}
planck
string planckStyle.planck = r'\textit{Planck}'
planckall
planckStyle.planckall = datalabel[defdata_all]
planckTT
planckStyle.planckTT = datalabel[defdata_TTonly]
planckTTlowTEB
planckStyle.planckTTlowTEB = datalabel[defdata_TT]
prob_label
planckStyle.prob_label
prob_y_ticks
planckStyle.prob_y_ticks
rootdir
planckStyle.rootdir = getdist.default_grid_root or os.path.join(batchjob.getCodeRootPath(), 'main')
s
planckStyle.s = copy.copy(plots.defaultSettings)
sfmath
string planckStyle.sfmath = os.path.dirname(os.path.abspath(__file__)) + os.sep + 'sfmath'
shortlabel
dictionary planckStyle.shortlabel = {}
solid_colors
planckStyle.solid_colors
solid_contour_palefactor
planckStyle.solid_contour_palefactor
use_plot_data
planckStyle.use_plot_data = getdist.use_plot_data
version
string planckStyle.version = 'CamSpec v910HM'
WP
string planckStyle.WP = r'\textit{Planck}+WP'
WPhighL
string planckStyle.WPhighL = r'\textit{Planck}+WP+highL'
WPhighLlensing
string planckStyle.WPhighLlensing = r'\textit{Planck}+lensing+WP+highL'