cosmomc_bde_v3p1: interpolation Module Reference
interpolation Module Reference
Data Types
type tcubicspline
type tinterpgrid2d
type tinterpolator
type tinterpolator1d
type tlogregularcubicspline
type tregularcubicspline
type tspline1d
Functions/Subroutines
subroutine tinterpolator_firstuse (this)
subroutine tinterpolator_error (this, S, v1, v2)
subroutine tinterpolator1d_firstuse (this)
subroutine tinterpolator1d_initinterp (this, End1, End2)
subroutine tinterpolator1d_initforsize (this, n)
subroutine tinterpolator1d_clear (this)
real(sp_acc) function tinterpolator1d_value (this, x, error)
real(sp_acc) function tinterpolator1d_intvalue (this, x, error)
subroutine tinterpolator1d_loadstate (this, F)
subroutine tinterpolator1d_savestate (this, F)
subroutine tspline1d_findnext (this, x, llo, xlo, xhi)
subroutine tspline1d_findvalue (this, x, llo, xlo, xhi, error)
real(sp_acc) function tspline1d_value (this, x, error)
real(sp_acc) function tspline1d_derivative (this, x, error)
subroutine tspline1d_arrayvalue (this, x, y, error)
subroutine tspline1d_intrangevalue (this, xmin, xmax, y, error)
subroutine tspline1d_clear (this)
subroutine tcubicspline_initforsize (this, n)
subroutine tcubicspline_init (this, Xarr, values, n, End1, End2)
subroutine tcubicspline_initint (this, Xarr, values, n, End1, End2)
subroutine tcubicspline_initinterp (this, End1, End2)
subroutine tcubicspline_initfromfile (this, Filename, xcol, ycol)
subroutine tcubicspline_clear (this)
subroutine tcubicspline_free (this)
subroutine tcubicspline_findnext (this, x, llo, xlo, xhi)
subroutine tcubicspline_loadstate (this, F)
subroutine tcubicspline_savestate (this, F)
subroutine tregularcubicspline_init (this, xmin, xmax, n, values, End1, End2)
subroutine tregularcubicspline_initinterp (this, End1, End2)
subroutine tregularcubicspline_findnext (this, x, llo, xlo, xhi)
subroutine tregularcubicspline_loadstate (this, F)
subroutine tregularcubicspline_savestate (this, F)
subroutine tlogregularcubicspline_init (this, xmin, xmax, n, values, End1, End2)
real(sp_acc) function tlogregularcubicspline_value (this, x, error)
real(sp_acc) function tlogregularcubicspline_derivative (this, x, error)
subroutine spline (x, y, n, d11, d1n, d2)
subroutine regular_spline (delta, y, n, d11, d1n, d2)
subroutine tinterpgrid2d_initinterp (this)
subroutine tinterpgrid2d_init (this, x, y, z)
subroutine tinterpgrid2d_initfrommatrixtextfile (this, Filename, colvals, rowvals)
subroutine tinterpgrid2d_initfrommatrixbinaryfile (this, Filename, colvals, rowvals)
subroutine tinterpgrid2d_initfromfile (this, Filename, xcol, ycol, zcol)
subroutine tinterpgrid2d_clear (this)
subroutine tinterpgrid2d_free (this)
real(gi) function tinterpgrid2d_value (this, x, y, error)
subroutine tinterpgrid2d_values (this, nip, x, y, z, error)
subroutine rgbi3p (Wk, md, nxd, nyd, xd, yd, zd, nip, xi, yi, zi, ier)
subroutine rgsf3p (wk, md, nxd, nyd, xd, yd, zd, nxi, xi, nyi, yi, zi, ier)
real(gi) function z2f (xx1, xx2, zz0, zz1)
real(gi) function z3f (xx1, xx2, xx3, zz0, zz1, zz2)
subroutine rgpd3p (nxd, nyd, xd, yd, zd, pdd)
subroutine rglctn (nxd, nyd, xd, yd, nip, xi, yi, inxi, inyi)
subroutine rgplnl (nxd, nyd, xd, yd, zd, pdd, nip, xi, yi, inxi, inyi, zi)
Variables
integer, parameter sp_acc = KIND(1.0)
real(sp_acc), parameter, public spline_dangle =1.e30_sp_acc
integer, parameter gi = sp_acc
integer, parameter interpolation_version = 1
Function/Subroutine Documentation
regular_spline()
subroutine interpolation::regular_spline (real(sp_acc), intent(in) delta, real(sp_acc), dimension(n), intent(in) y, integer, intent(in) n, real(sp_acc), intent(in) d11, real(sp_acc), intent(in) d1n, real(sp_acc), dimension(n), intent(out) d2)
References spline_dangle.
Referenced by tregularcubicspline_initinterp().
rgbi3p()
subroutine interpolation::rgbi3p (real(gi), dimension(3,nxd,nyd), intent(inout) Wk, integer, intent(in) md, integer, intent(in) nxd, integer, intent(in) nyd, real(gi), dimension(nxd), intent(in) xd, real(gi), dimension(nyd), intent(in) yd, real(gi), dimension(nxd,nyd), intent(in) zd, integer, intent(in) nip, real(gi), dimension(nip), intent(in) xi, real(gi), dimension(nip), intent(in) yi, real(gi), dimension(nip), intent(out) zi, integer, intent(out) ier)
References rglctn(), rgpd3p(), and rgplnl().
Referenced by tinterpgrid2d_values().
rglctn()
subroutine interpolation::rglctn (integer, intent(in) nxd, integer, intent(in) nyd, real(gi), dimension(nxd), intent(in) xd, real(gi), dimension(nyd), intent(in) yd, integer, intent(in) nip, real(gi), dimension(nip), intent(in) xi, real(gi), dimension(nip), intent(in) yi, integer, dimension(nip), intent(out) inxi, integer, dimension(nip), intent(out) inyi)
Referenced by rgbi3p(), and rgsf3p().
rgpd3p()
subroutine interpolation::rgpd3p (integer, intent(in) nxd, integer, intent(in) nyd, real(gi), dimension(nxd), intent(in) xd, real(gi), dimension(nyd), intent(in) yd, real(gi), dimension(nxd,nyd), intent(in) zd, real(gi), dimension(3,nxd,nyd), intent(out) pdd)
References z2f(), and z3f().
Referenced by rgbi3p(), rgsf3p(), and tinterpgrid2d_initinterp().
rgplnl()
subroutine interpolation::rgplnl (integer, intent(in) nxd, integer, intent(in) nyd, real(gi), dimension(nxd), intent(in) xd, real(gi), dimension(nyd), intent(in) yd, real(gi), dimension(nxd,nyd), intent(in) zd, real(gi), dimension(3,nxd,nyd), intent(in) pdd, integer, intent(in) nip, real(gi), dimension(nip), intent(in) xi, real(gi), dimension(nip), intent(in) yi, integer, dimension(nip), intent(in) inxi, integer, dimension(nip), intent(in) inyi, real(gi), dimension(nip), intent(out) zi)
Referenced by rgbi3p(), and rgsf3p().
rgsf3p()
subroutine interpolation::rgsf3p (real(gi), dimension(3,nxd,nyd), intent(inout) wk, integer, intent(in) md, integer, intent(in) nxd, integer, intent(in) nyd, real(gi), dimension(nxd), intent(in) xd, real(gi), dimension(nyd), intent(in) yd, real(gi), dimension(nxd,nyd), intent(inout) zd, integer, intent(in) nxi, real(gi), dimension(nxi), intent(inout) xi, integer, intent(in) nyi, real(gi), dimension(nyi), intent(in) yi, real(gi), dimension(nxi,nyi), intent(inout) zi, integer, intent(out) ier)
References rglctn(), rgpd3p(), and rgplnl().
spline()
subroutine interpolation::spline (real(sp_acc), dimension(n), intent(in) x, real(sp_acc), dimension(n), intent(in) y, integer, intent(in) n, real(sp_acc), intent(in) d11, real(sp_acc), intent(in) d1n, real(sp_acc), dimension(n), intent(out) d2)
References spline_dangle.
tcubicspline_clear()
subroutine interpolation::tcubicspline_clear (class(tcubicspline) this)
tcubicspline_findnext()
subroutine interpolation::tcubicspline_findnext (class(tcubicspline) this, real(sp_acc), intent(in) x, integer, intent(inout) llo, real(sp_acc), intent(out) xlo, real(sp_acc), intent(out) xhi)
tcubicspline_free()
subroutine interpolation::tcubicspline_free (type(tcubicspline) this)
Referenced by interpolation::tcubicspline::tcubicspline_free().
tcubicspline_init()
subroutine interpolation::tcubicspline_init (class(tcubicspline) this, real(sp_acc), dimension(1:), intent(in) Xarr, real(sp_acc), dimension(1:), intent(in) values, integer, intent(in), optional n, real(sp_acc), intent(in), optional End1, real(sp_acc), intent(in), optional End2)
Referenced by interpolation::tcubicspline::init().
tcubicspline_initforsize()
subroutine interpolation::tcubicspline_initforsize (class(tcubicspline) this, integer, intent(in) n)
References tinterpolator1d_initforsize().
tcubicspline_initfromfile()
subroutine interpolation::tcubicspline_initfromfile (class(tcubicspline) this, character(len=*), intent(in) Filename, integer, intent(in), optional xcol, integer, intent(in), optional ycol)
tcubicspline_initint()
subroutine interpolation::tcubicspline_initint (class(tcubicspline) this, integer, dimension(:), intent(in) Xarr, real(sp_acc), dimension(:), intent(in) values, integer, intent(in), optional n, real(sp_acc), intent(in), optional End1, real(sp_acc), intent(in), optional End2)
Referenced by interpolation::tcubicspline::init().
tcubicspline_initinterp()
subroutine interpolation::tcubicspline_initinterp (class(tcubicspline) this, real(sp_acc), intent(in), optional End1, real(sp_acc), intent(in), optional End2)
References spline().
tcubicspline_loadstate()
subroutine interpolation::tcubicspline_loadstate (class(tcubicspline) this, class(tfilestream) F)
References tinterpolator1d_loadstate().
tcubicspline_savestate()
subroutine interpolation::tcubicspline_savestate (class(tcubicspline) this, class(tfilestream) F)
References tinterpolator1d_savestate().
tinterpgrid2d_clear()
subroutine interpolation::tinterpgrid2d_clear (class(tinterpgrid2d) this)
tinterpgrid2d_free()
subroutine interpolation::tinterpgrid2d_free (type(tinterpgrid2d) this)
Referenced by interpolation::tinterpgrid2d::tinterpgrid2d_free().
tinterpgrid2d_init()
subroutine interpolation::tinterpgrid2d_init (class(tinterpgrid2d) this, real(gi), dimension(:), intent(in) x, real(gi), dimension(:), intent(in) y, real(gi), dimension(:,:), intent(in) z)
tinterpgrid2d_initfromfile()
subroutine interpolation::tinterpgrid2d_initfromfile (class(tinterpgrid2d) this, character(len=*), intent(in) Filename, integer, intent(in), optional xcol, integer, intent(in), optional ycol, integer, intent(in), optional zcol)
tinterpgrid2d_initfrommatrixbinaryfile()
subroutine interpolation::tinterpgrid2d_initfrommatrixbinaryfile (class(tinterpgrid2d) this, character(len=*), intent(in) Filename, real(sp_acc), dimension(:), intent(in) colvals, real(sp_acc), dimension(:), intent(in) rowvals)
tinterpgrid2d_initfrommatrixtextfile()
subroutine interpolation::tinterpgrid2d_initfrommatrixtextfile (class(tinterpgrid2d) this, character(len=*), intent(in) Filename, real(sp_acc), dimension(:), intent(in) colvals, real(sp_acc), dimension(:), intent(in) rowvals)
References fileutils::file.
tinterpgrid2d_initinterp()
subroutine interpolation::tinterpgrid2d_initinterp (class(tinterpgrid2d) this)
References rgpd3p().
tinterpgrid2d_value()
real(gi) function interpolation::tinterpgrid2d_value (class(tinterpgrid2d) this, real(gi), intent(in) x, real(gi), intent(in) y, integer, intent(inout), optional error)
References fileutils::error().
tinterpgrid2d_values()
subroutine interpolation::tinterpgrid2d_values (class(tinterpgrid2d) this, integer, intent(in) nip, real(gi), dimension(*), intent(in) x, real(gi), dimension(*), intent(in) y, real(gi), dimension(*), intent(out) z, integer, intent(inout), optional error)
References rgbi3p().
tinterpolator1d_clear()
subroutine interpolation::tinterpolator1d_clear (class(tinterpolator1d) this)
References spline_dangle.
Referenced by tspline1d_clear().
tinterpolator1d_firstuse()
subroutine interpolation::tinterpolator1d_firstuse (class(tinterpolator1d) this)
tinterpolator1d_initforsize()
subroutine interpolation::tinterpolator1d_initforsize (class(tinterpolator1d) this, integer, intent(in) n)
Referenced by tcubicspline_initforsize().
tinterpolator1d_initinterp()
subroutine interpolation::tinterpolator1d_initinterp (class(tinterpolator1d) this, real(sp_acc), intent(in), optional End1, real(sp_acc), intent(in), optional End2)
tinterpolator1d_intvalue()
real(sp_acc) function interpolation::tinterpolator1d_intvalue (class(tinterpolator1d) this, integer, intent(in) x, integer, intent(inout), optional error)
Referenced by interpolation::tinterpolator1d::initinterp().
tinterpolator1d_loadstate()
subroutine interpolation::tinterpolator1d_loadstate (class(tinterpolator1d) this, class(tfilestream) F)
Referenced by tcubicspline_loadstate(), and tregularcubicspline_loadstate().
tinterpolator1d_savestate()
subroutine interpolation::tinterpolator1d_savestate (class(tinterpolator1d) this, class(tfilestream) F)
References interpolation_version.
Referenced by tcubicspline_savestate(), and tregularcubicspline_savestate().
tinterpolator1d_value()
real(sp_acc) function interpolation::tinterpolator1d_value (class(tinterpolator1d) this, real(sp_acc), intent(in) x, integer, intent(inout), optional error)
tinterpolator_error()
subroutine interpolation::tinterpolator_error (class(tinterpolator) this, character(len=*), intent(in) S, class(*), intent(in), optional v1, class(*), intent(in), optional v2)
References stringutils::formatstring(), and mpiutils::mpistop().
tinterpolator_firstuse()
subroutine interpolation::tinterpolator_firstuse (class(tinterpolator) this)
tlogregularcubicspline_derivative()
real(sp_acc) function interpolation::tlogregularcubicspline_derivative (class(tlogregularcubicspline) this, real(sp_acc), intent(in) x, integer, intent(inout), optional error)
References fileutils::error(), and tspline1d_derivative().
tlogregularcubicspline_init()
subroutine interpolation::tlogregularcubicspline_init (class(tlogregularcubicspline) this, real(sp_acc), intent(in) xmin, real(sp_acc), intent(in) xmax, integer, intent(in) n, real(sp_acc), dimension(1:), intent(in), optional values, real(sp_acc), intent(in), optional End1, real(sp_acc), intent(in), optional End2)
References tregularcubicspline_init().
tlogregularcubicspline_value()
real(sp_acc) function interpolation::tlogregularcubicspline_value (class(tlogregularcubicspline) this, real(sp_acc), intent(in) x, integer, intent(inout), optional error)
References fileutils::error(), and tspline1d_value().
tregularcubicspline_findnext()
subroutine interpolation::tregularcubicspline_findnext (class(tregularcubicspline) this, real(sp_acc), intent(in) x, integer, intent(inout) llo, real(sp_acc), intent(out) xlo, real(sp_acc), intent(out) xhi)
tregularcubicspline_init()
subroutine interpolation::tregularcubicspline_init (class(tregularcubicspline) this, real(sp_acc), intent(in) xmin, real(sp_acc), intent(in) xmax, integer, intent(in) n, real(sp_acc), dimension(1:), intent(in), optional values, real(sp_acc), intent(in), optional End1, real(sp_acc), intent(in), optional End2)
Referenced by tlogregularcubicspline_init().
tregularcubicspline_initinterp()
subroutine interpolation::tregularcubicspline_initinterp (class(tregularcubicspline) this, real(sp_acc), intent(in), optional End1, real(sp_acc), intent(in), optional End2)
References regular_spline().
tregularcubicspline_loadstate()
subroutine interpolation::tregularcubicspline_loadstate (class(tregularcubicspline) this, class(tfilestream) F)
References tinterpolator1d_loadstate().
tregularcubicspline_savestate()
subroutine interpolation::tregularcubicspline_savestate (class(tregularcubicspline) this, class(tfilestream) F)
References tinterpolator1d_savestate().
tspline1d_arrayvalue()
subroutine interpolation::tspline1d_arrayvalue (class(tspline1d) this, real(sp_acc), dimension(1:), intent(in) x, real(sp_acc), dimension(1:), intent(out) y, integer, intent(inout), optional error)
Referenced by interpolation::tspline1d::array().
tspline1d_clear()
subroutine interpolation::tspline1d_clear (class(tspline1d) this)
References tinterpolator1d_clear().
tspline1d_derivative()
real(sp_acc) function interpolation::tspline1d_derivative (class(tspline1d) this, real(sp_acc), intent(in) x, integer, intent(inout), optional error)
References fileutils::error().
Referenced by tlogregularcubicspline_derivative().
tspline1d_findnext()
subroutine interpolation::tspline1d_findnext (class(tspline1d) this, real(sp_acc), intent(in) x, integer, intent(inout) llo, real(sp_acc), intent(out) xlo, real(sp_acc), intent(out) xhi)
tspline1d_findvalue()
subroutine interpolation::tspline1d_findvalue (class(tspline1d) this, real(sp_acc), intent(in) x, integer, intent(out) llo, real(sp_acc), intent(out) xlo, real(sp_acc), intent(out) xhi, integer, intent(inout), optional error)
tspline1d_intrangevalue()
subroutine interpolation::tspline1d_intrangevalue (class(tspline1d) this, integer, intent(in) xmin, integer, intent(in) xmax, real(sp_acc), dimension(xmin:), intent(out) y, integer, intent(inout), optional error)
Referenced by interpolation::tspline1d::array().
tspline1d_value()
real(sp_acc) function interpolation::tspline1d_value (class(tspline1d) this, real(sp_acc), intent(in) x, integer, intent(inout), optional error)
References fileutils::error().
Referenced by tlogregularcubicspline_value().
z2f()
real(gi) function interpolation::z2f (real(gi), intent(in) xx1, real(gi), intent(in) xx2, real(gi), intent(in) zz0, real(gi), intent(in) zz1)
Referenced by rgpd3p().
z3f()
real(gi) function interpolation::z3f (real(gi), intent(in) xx1, real(gi), intent(in) xx2, real(gi), intent(in) xx3, real(gi), intent(in) zz0, real(gi), intent(in) zz1, real(gi), intent(in) zz2)
Referenced by rgpd3p().
Variable Documentation
gi
integer, parameter interpolation::gi = sp_acc
interpolation_version
integer, parameter interpolation::interpolation_version = 1
Referenced by tinterpolator1d_savestate().
sp_acc
integer parameter interpolation::sp_acc = KIND(1.0)
spline_dangle
real(sp_acc), parameter, public interpolation::spline_dangle =1.e30_sp_acc
Referenced by samples::density1d_initspline(), regular_spline(), spline(), interpolation::tinterpgrid2d::tinterpgrid2d_free(), and tinterpolator1d_clear().