cosmomc_bde_v3p1: fileutils Module Reference
fileutils Module Reference
Data Types
type tbinaryfile
type tfile
type tfilestream
type tsequentialfile
type ttextfile
Functions/Subroutines
logical function fileexists (aname)
integer(file_size_int) function filesize (name)
integer function txtnumbercolumns (InLine)
integer function txtcolumns (InLine)
subroutine setdefaultmodes (this)
subroutine tsequentialfile_setdefaultmodes (this)
subroutine ttextfile_setdefaultmodes (this)
subroutine checkopen (this, forWrite)
logical function opened (this)
subroutine error (this, msg, errormsg)
subroutine tfilestream_close (this)
subroutine tfilestream_free (this)
subroutine tfilestream_flush (this)
subroutine tfilestream_rewind (this)
integer(file_size_int) function tfilestream_position (this)
integer(file_size_int) function tfilestream_size (this)
subroutine tfilestream_open (this, aname, errormsg, status)
subroutine tfilestream_openfile (this, aname, mode, errormsg, forwrite, append, status)
subroutine createfile (this, aname, errormsg)
subroutine createopenfile (this, aname, append, errormsg)
subroutine readstringsub (this, S, OK)
character(len=:) function, allocatable readstringfunc (this)
subroutine readitemsub (this, R, OK)
logical function readitemfunc (this, R)
subroutine readarray (this, R, n, OK)
logical function readarrayfunc (this, R, n)
logical function readarray2func (this, R)
subroutine readarray2 (this, R, OK)
subroutine readsizedarray_r (this, R)
subroutine readsizedarray_d (this, R)
subroutine readsizedarray_i (this, R)
subroutine readsizedarray2_r (this, R)
subroutine readsizedarray2_d (this, R)
subroutine readsizedarray2_i (this, R)
subroutine writeitemsub (this, R)
subroutine writetrim (this, S)
subroutine writesizedarray1 (this, R, n)
subroutine writesizedarray2 (this, R)
subroutine writeoneandarray (this, I, R)
subroutine writearray (this, R, n)
subroutine writearray2 (this, R)
subroutine writeitems (this, S1, S2, S3, S4, S5, S6)
subroutine readitems (this, S1, S2, S3, S4, S5, S6, OK)
logical function readline (this, InLine, trimmed)
logical function readlineskipemptyandcomments (this, InLine, comment)
logical function readnextcontentline (this, filename, InLine)
logical function skiplines (this, n)
integer function columns (this)
integer function lines (this, nocomments)
character(3) function defaultadvance (this, advance)
subroutine newline (this)
subroutine writeleftaligned (this, Form, str)
subroutine writeinlineitems (this, S1, S2, S3, S4, S5, S6)
subroutine writeitemstxt (this, S1, S2, S3, S4, S5, S6)
subroutine writeinlineitem (this, str, form)
subroutine writeinlinearray (this, str, form, n)
subroutine ttextfile_writeitem (this, R)
subroutine ttextfile_writearray (this, R, n)
subroutine ttextfile_writeoneandarray (this, I, R)
subroutine writeitemtxt (this, str, form, advance)
subroutine writearraytxt (this, str, form, advance, number)
subroutine writearray2txt (this, R)
subroutine writetrimtxt (this, S)
subroutine writeinlinetrim (this, string)
subroutine readarray2txt (this, R, OK)
subroutine readitemtxt (this, R, OK)
subroutine readarraytxt (this, R, n, OK)
subroutine readstringtxt (this, S, OK)
subroutine writeformat (this, formatst, i1, i2, i3, i4, i5, i6, i7, i8)
character(len=:) function, allocatable topcommentline (aname)
character(len=:) function, allocatable lasttopcomment (aname)
integer function txtfilecolumns (aname)
integer function txtfilelines (aname)
character(len=:) function, allocatable lastfileline (aname)
logical function charisslash (C)
logical function isfullpath (aname)
character(len=:) function, allocatable extractfilepath (aname)
character(len=:) function, allocatable extractfileext (aname)
character(len=:) function, allocatable extractfilename (aname, no_ext, all_ext)
character(len=:) function, allocatable changefileext (aname, ext)
character(len=:) function, allocatable checktrailingslash (aname)
character(len=:) function, allocatable file_join (path, aname)
subroutine deletefile (aname)
subroutine readtextvector (aname, vec, n)
subroutine writetextvector (aname, vec, n, fmt)
subroutine writetextmatrix (aname, mat, m, n, fmt)
subroutine readtextmatrix (aname, mat, inm, inn)
subroutine loadtxt_2d (aname, mat, m, n, comment)
subroutine loadtxt_1d (aname, vec, n, comment)
type(ttextfile) function createtextfile (fname)
type(ttextfile) function opentextfile (fname)
Variables
integer, parameter, public file_size_int = KIND(INT64)
type(tfile), save, public file
Function/Subroutine Documentation
changefileext()
character(len=:) function, allocatable fileutils::changefileext (character(len=*), intent(in) aname, character(len=*), intent(in) ext) private
charisslash()
logical function fileutils::charisslash (character, intent(in) C) private
Referenced by checktrailingslash(), extractfileext(), extractfilename(), extractfilepath(), and isfullpath().
checkopen()
subroutine fileutils::checkopen (class(tfilestream) this, logical, intent(in), optional forWrite) private
References miscutils::defaultfalse().
checktrailingslash()
character(len=:) function, allocatable fileutils::checktrailingslash (character(len=*), intent(in) aname) private
References charisslash().
Referenced by file_join().
columns()
integer function fileutils::columns (class(ttextfile) this) private
References file.
createfile()
subroutine fileutils::createfile (class(tfilestream) this, character(len=*), intent(in) aname, character(len=*), intent(in), optional errormsg) private
createopenfile()
subroutine fileutils::createopenfile (class(tfilestream) this, character(len=*), intent(in) aname, logical, intent(in), optional append, character(len=*), intent(in), optional errormsg) private
createtextfile()
type(ttextfile) function fileutils::createtextfile (character(len=*), intent(in) fname) private
defaultadvance()
character(3) function fileutils::defaultadvance (class(ttextfile) this, logical, intent(in), optional advance) private
deletefile()
subroutine fileutils::deletefile (character(len=*), intent(in) aname) private
References file, and fileexists().
error()
subroutine fileutils::error (class(tfilestream) this, character(len=*), intent(in) msg, character(len=*), intent(in), optional errormsg) private
References mpiutils::mpistop().
Referenced by iniobjects::ini_open(), interpolation::tinterpgrid2d_value(), interpolation::tlogregularcubicspline_derivative(), interpolation::tlogregularcubicspline_value(), interpolation::tspline1d_derivative(), and interpolation::tspline1d_value().
extractfileext()
character(len=:) function, allocatable fileutils::extractfileext (character(len=*), intent(in) aname) private
References charisslash().
extractfilename()
character(len=:) function, allocatable fileutils::extractfilename (character(len=*), intent(in) aname, logical, intent(in), optional no_ext, logical, intent(in), optional all_ext) private
References charisslash(), and miscutils::defaultfalse().
extractfilepath()
character(len=:) function, allocatable fileutils::extractfilepath (character(len=*), intent(in) aname) private
References charisslash().
file_join()
character(len=:) function, allocatable fileutils::file_join (character(len=*), intent(in) path, character(len=*), intent(in) aname) private
References checktrailingslash().
fileexists()
logical function fileutils::fileexists (character(len=*), intent(in) aname) private
References file.
Referenced by deletefile(), and tfilestream_openfile().
filesize()
integer(file_size_int) function fileutils::filesize (character(len=*), intent(in) name) private
References file.
isfullpath()
logical function fileutils::isfullpath (character(len=*), intent(in) aname) private
References charisslash().
lastfileline()
character(len=:) function, allocatable fileutils::lastfileline (character(len=*), intent(in) aname) private
lasttopcomment()
character(len=:) function, allocatable fileutils::lasttopcomment (character(len=*), intent(in) aname) private
lines()
integer function fileutils::lines (class(ttextfile) this, logical, intent(in), optional nocomments) private
References miscutils::defaulttrue().
loadtxt_1d()
subroutine fileutils::loadtxt_1d (character(len=*), intent(in) aname, real(kind(1.d0)), dimension(:), allocatable vec, integer, intent(out), optional n, character(len=:), intent(out), optional, allocatable comment) private
Referenced by fileutils::tfile::loadtxt().
loadtxt_2d()
subroutine fileutils::loadtxt_2d (character(len=*), intent(in) aname, real(kind(1.d0)), dimension(:,:), allocatable mat, integer, intent(out), optional m, integer, intent(out), optional n, character(len=:), intent(out), optional, allocatable comment) private
Referenced by fileutils::tfile::loadtxt().
newline()
subroutine fileutils::newline (class(ttextfile) this) private
opened()
logical function fileutils::opened (class(tfilestream) this) private
opentextfile()
type(ttextfile) function fileutils::opentextfile (character(len=*), intent(in) fname) private
readarray()
subroutine fileutils::readarray (class(tfilestream) this, class(*), dimension(1:) R, integer, intent(in), optional n, logical, optional OK) private
Referenced by fileutils::tfilestream::read().
readarray2()
subroutine fileutils::readarray2 (class(tfilestream) this, class(*), dimension(:,:) R, logical, optional OK) private
Referenced by fileutils::tfilestream::read().
readarray2func()
logical function fileutils::readarray2func (class(tfilestream) this, class(*), dimension(:,:) R) private
Referenced by fileutils::tfilestream::readitem().
readarray2txt()
subroutine fileutils::readarray2txt (class(ttextfile) this, class(*), dimension(:,:) R, logical, optional OK) private
readarrayfunc()
logical function fileutils::readarrayfunc (class(tfilestream) this, class(*), dimension(1:) R, integer, intent(in), optional n) private
Referenced by fileutils::tfilestream::readitem().
readarraytxt()
subroutine fileutils::readarraytxt (class(ttextfile) this, class(*), dimension(1:) R, integer, intent(in), optional n, logical, optional OK) private
readitemfunc()
logical function fileutils::readitemfunc (class(tfilestream) this, class(*), intent(out) R) private
Referenced by fileutils::tfilestream::readitem().
readitems()
subroutine fileutils::readitems (class(tfilestream) this, class(*) S1, class(*), optional S2, class(*), optional S3, class(*), optional S4, class(*), optional S5, class(*), optional S6, logical, optional OK) private
References miscutils::defaulttrue().
Referenced by fileutils::tfilestream::read().
readitemsub()
subroutine fileutils::readitemsub (class(tfilestream) this, class(*), intent(out) R, logical, optional OK) private
readitemtxt()
subroutine fileutils::readitemtxt (class(ttextfile) this, class(*), intent(out) R, logical, optional OK) private
readline()
logical function fileutils::readline (class(ttextfile) this, character(len=:), optional, allocatable InLine, logical, intent(in), optional trimmed) private
References set().
readlineskipemptyandcomments()
logical function fileutils::readlineskipemptyandcomments (class(ttextfile) this, character(len=:), allocatable InLine, character(len=:), intent(inout), optional, allocatable comment) private
readnextcontentline()
logical function fileutils::readnextcontentline (class(ttextfile) this, character(len=*), intent(in) filename, character(len=:), intent(out), allocatable InLine) private
readsizedarray2_d()
subroutine fileutils::readsizedarray2_d (class(tfilestream) this, double precision, dimension(:,:), allocatable R) private
Referenced by fileutils::tfilestream::readsizedarray().
readsizedarray2_i()
subroutine fileutils::readsizedarray2_i (class(tfilestream) this, integer, dimension(:,:), allocatable R) private
Referenced by fileutils::tfilestream::readsizedarray().
readsizedarray2_r()
subroutine fileutils::readsizedarray2_r (class(tfilestream) this, real, dimension(:,:), allocatable R) private
Referenced by fileutils::tfilestream::readsizedarray().
readsizedarray_d()
subroutine fileutils::readsizedarray_d (class(tfilestream) this, double precision, dimension(:), allocatable R) private
Referenced by fileutils::tfilestream::readsizedarray().
readsizedarray_i()
subroutine fileutils::readsizedarray_i (class(tfilestream) this, integer, dimension(:), allocatable R) private
Referenced by fileutils::tfilestream::readsizedarray().
readsizedarray_r()
subroutine fileutils::readsizedarray_r (class(tfilestream) this, real, dimension(:), allocatable R) private
Referenced by fileutils::tfilestream::readsizedarray().
readstringfunc()
character(len=:) function, allocatable fileutils::readstringfunc (class(tfilestream) this) private
Referenced by fileutils::tfilestream::readstringitem().
readstringsub()
subroutine fileutils::readstringsub (class(tfilestream) this, character(len=:), allocatable S, logical, optional OK) private
Referenced by fileutils::tfilestream::readstring().
readstringtxt()
subroutine fileutils::readstringtxt (class(ttextfile) this, character(len=:), allocatable S, logical, optional OK) private
readtextmatrix()
subroutine fileutils::readtextmatrix (character(len=*), intent(in) aname, real(kind(1.d0)), dimension(:,:), intent(out) mat, integer, intent(in), optional inm, integer, intent(in), optional inn) private
readtextvector()
subroutine fileutils::readtextvector (character(len=*), intent(in) aname, class(*), dimension(n), intent(out) vec, integer, intent(in) n) private
setdefaultmodes()
subroutine fileutils::setdefaultmodes (class(tfilestream) this) private
skiplines()
logical function fileutils::skiplines (class(ttextfile) this, integer, intent(in) n) private
tfilestream_close()
subroutine fileutils::tfilestream_close (class(tfilestream) this) private
tfilestream_flush()
subroutine fileutils::tfilestream_flush (class(tfilestream) this) private
tfilestream_free()
subroutine fileutils::tfilestream_free (type(tfilestream) this) private
Referenced by fileutils::tfilestream::tfilestream_free().
tfilestream_open()
subroutine fileutils::tfilestream_open (class(tfilestream) this, character(len=*), intent(in) aname, character(len=*), intent(in), optional errormsg, integer, intent(out), optional status) private
tfilestream_openfile()
subroutine fileutils::tfilestream_openfile (class(tfilestream) this, character(len=*), intent(in) aname, character(len=*), intent(in), optional mode, character(len=*), intent(in), optional errormsg, logical, intent(in), optional forwrite, logical, intent(in), optional append, integer, intent(out), optional status) private
References miscutils::defaultfalse(), file, and fileexists().
tfilestream_position()
integer(file_size_int) function fileutils::tfilestream_position (class(tfilestream) this) private
tfilestream_rewind()
subroutine fileutils::tfilestream_rewind (class(tfilestream) this) private
tfilestream_size()
integer(file_size_int) function fileutils::tfilestream_size (class(tfilestream) this) private
References file.
topcommentline()
character(len=:) function, allocatable fileutils::topcommentline (character(len=*), intent(in) aname) private
tsequentialfile_setdefaultmodes()
subroutine fileutils::tsequentialfile_setdefaultmodes (class(tsequentialfile) this) private
ttextfile_setdefaultmodes()
subroutine fileutils::ttextfile_setdefaultmodes (class(ttextfile) this) private
ttextfile_writearray()
subroutine fileutils::ttextfile_writearray (class(ttextfile) this, class(*), dimension(:), intent(in) R, integer, intent(in), optional n) private
ttextfile_writeitem()
subroutine fileutils::ttextfile_writeitem (class(ttextfile) this, class(*), intent(in) R) private
ttextfile_writeoneandarray()
subroutine fileutils::ttextfile_writeoneandarray (class(ttextfile) this, class(*), intent(in) I, class(*), dimension(:), intent(in) R) private
txtcolumns()
integer function fileutils::txtcolumns (character(len=*) InLine) private
txtfilecolumns()
integer function fileutils::txtfilecolumns (character(len=*), intent(in) aname) private
txtfilelines()
integer function fileutils::txtfilelines (character(len=*), intent(in) aname) private
txtnumbercolumns()
integer function fileutils::txtnumbercolumns (character(len=*) InLine) private
writearray()
subroutine fileutils::writearray (class(tfilestream) this, class(*), dimension(1:), intent(in) R, integer, intent(in), optional n) private
Referenced by fileutils::tfilestream::write().
writearray2()
subroutine fileutils::writearray2 (class(tfilestream) this, class(*), dimension(:,:), intent(in) R) private
Referenced by fileutils::tfilestream::write().
writearray2txt()
subroutine fileutils::writearray2txt (class(ttextfile) this, class(*), dimension(:,:), intent(in) R) private
writearraytxt()
subroutine fileutils::writearraytxt (class(ttextfile) this, class(*), dimension(:), intent(in) str, character(len=*), intent(in), optional form, logical, intent(in), optional advance, integer, intent(in), optional number) private
writeformat()
subroutine fileutils::writeformat (class(ttextfile) this, character(len=*), intent(in) formatst, class(*), intent(in) i1, class(*), intent(in), optional i2, class(*), intent(in), optional i3, class(*), intent(in), optional i4, class(*), intent(in), optional i5, class(*), intent(in), optional i6, class(*), intent(in), optional i7, class(*), intent(in), optional i8) private
References stringutils::formatstring().
writeinlinearray()
subroutine fileutils::writeinlinearray (class(ttextfile) this, class(*), dimension(:), intent(in) str, character(len=*), intent(in), optional form, integer, intent(in), optional n) private
Referenced by fileutils::ttextfile::writeinline().
writeinlineitem()
subroutine fileutils::writeinlineitem (class(ttextfile) this, class(*), intent(in) str, character(len=*), intent(in), optional form) private
Referenced by fileutils::ttextfile::writeinline().
writeinlineitems()
subroutine fileutils::writeinlineitems (class(ttextfile) this, class(*), intent(in) S1, class(*), intent(in), optional S2, class(*), intent(in), optional S3, class(*), intent(in), optional S4, class(*), intent(in), optional S5, class(*), intent(in), optional S6) private
writeinlinetrim()
subroutine fileutils::writeinlinetrim (class(ttextfile) this, character(len=*), intent(in) string) private
writeitems()
subroutine fileutils::writeitems (class(tfilestream) this, class(*), intent(in) S1, class(*), intent(in), optional S2, class(*), intent(in), optional S3, class(*), intent(in), optional S4, class(*), intent(in), optional S5, class(*), intent(in), optional S6) private
Referenced by fileutils::tfilestream::write().
writeitemstxt()
subroutine fileutils::writeitemstxt (class(ttextfile) this, class(*), intent(in) S1, class(*), intent(in), optional S2, class(*), intent(in), optional S3, class(*), intent(in), optional S4, class(*), intent(in), optional S5, class(*), intent(in), optional S6) private
writeitemsub()
subroutine fileutils::writeitemsub (class(tfilestream) this, class(*), intent(in) R) private
writeitemtxt()
subroutine fileutils::writeitemtxt (class(ttextfile) this, class(*), intent(in) str, character(len=*), intent(in), optional form, logical, intent(in), optional advance) private
writeleftaligned()
subroutine fileutils::writeleftaligned (class(ttextfile) this, character(len=*) Form, character(len=*) str) private
writeoneandarray()
subroutine fileutils::writeoneandarray (class(tfilestream) this, class(*), intent(in) I, class(*), dimension(:), intent(in) R) private
Referenced by fileutils::tfilestream::write().
writesizedarray1()
subroutine fileutils::writesizedarray1 (class(tfilestream) this, class(*), dimension(1:), intent(in) R, integer, intent(in), optional n) private
Referenced by fileutils::tfilestream::writesizedarray().
writesizedarray2()
subroutine fileutils::writesizedarray2 (class(tfilestream) this, class(*), dimension(:,:), intent(in) R) private
Referenced by fileutils::tfilestream::writesizedarray().
writetextmatrix()
subroutine fileutils::writetextmatrix (character(len=*), intent(in) aname, class(*), dimension(:,:), intent(in) mat, integer, intent(in), optional m, integer, intent(in), optional n, character(len=*), intent(in), optional fmt) private
Referenced by fileutils::tfile::savetxt().
writetextvector()
subroutine fileutils::writetextvector (character(len=*), intent(in) aname, class(*), dimension(:), intent(in) vec, integer, intent(in), optional n, character(len=*), intent(in), optional fmt) private
Referenced by fileutils::tfile::savetxt().
writetrim()
subroutine fileutils::writetrim (class(tfilestream) this, character(len=*), intent(in) S) private
writetrimtxt()
subroutine fileutils::writetrimtxt (class(ttextfile) this, character(len=*), intent(in) S) private
Variable Documentation
file
type(tfile), save, public fileutils::file
Referenced by settings::checkparamchangef(), cmblikes::cmblikes_readclarr(), columns(), deletefile(), fileexists(), filesize(), iniobjects::ini_resolvelinkedfile(), io::io_readlastchainparams(), io::io_readparamnames(), io::io_readproposematrix(), paramnames::paramnames_init(), cmblikes::readbinwindows(), cmblikes::readcovmat(), interpolationtests::runinterpolationtests(), bk_planck::tbk_planck_read_bandpass(), tfilestream_openfile(), tfilestream_size(), interpolation::tinterpgrid2d_initfrommatrixtextfile(), settings::tsettingini_readfilename(), settings::tsettingini_replacedirs(), and objectlists::tstringlist_readcolumnsgetarray().
file_size_int
integer, parameter, public fileutils::file_size_int = KIND(INT64)