cosmomc_bde_v3p1: thermodata Module Reference
thermodata Module Reference
Functions/Subroutines
subroutine, public thermo (tau, cs2b, opacity, dopacity)
real(dl) function, public thermo_opacitytotime (opacity)
subroutine, public inithermo (taumin, taumax)
subroutine settimesteps
subroutine, public thermodata_free
subroutine dothermospline (j2, tau)
real(dl) function ddamping_da (a)
real(dl) function doptdepth_dz (z)
real(dl) function optdepth (z)
real(dl) function ddragoptdepth_dz (z)
real(dl) function dragoptdepth (z)
subroutine find_z (func, zout)
subroutine, public getbackgroundevolution (ntimes, times, outputs)
Variables
integer, parameter nthermo =20000
real(dl), dimension(nthermo) tb
real(dl), dimension(nthermo) cs2
real(dl), dimension(nthermo) xe
real(dl), dimension(nthermo) dcs2
real(dl), dimension(nthermo) dotmu
real(dl), dimension(nthermo) ddotmu
real(dl), dimension(nthermo) sdotmu
real(dl), dimension(nthermo) emmu
real(dl), dimension(nthermo) demmu
real(dl), dimension(nthermo) dddotmu
real(dl), dimension(nthermo) ddddotmu
real(dl), dimension(nthermo) winlens
real(dl), dimension(nthermo) dwinlens
real(dl), dimension(nthermo) scalefactor
real(dl) tauminn
real(dl) dlntau
real(dl) maxtau
real(dl), dimension(:), allocatable, public vis
real(dl), dimension(:), allocatable, public dvis
real(dl), dimension(:), allocatable, public ddvis
real(dl), dimension(:), allocatable, public expmmu
real(dl), dimension(:), allocatable, public dopac
real(dl), dimension(:), allocatable, public opac
real(dl), dimension(:), allocatable, public lenswin
logical, parameter dowinlens = .false.
real(dl), public tight_tau
real(dl) actual_opt_depth
real(dl), public matter_verydom_tau
real(dl) r_drag0
real(dl), public z_star
real(dl), public z_drag
Function/Subroutine Documentation
ddamping_da()
real(dl) function thermodata::ddamping_da (real(dl), intent(in) a) private
References dtauda(), and r_drag0.
Referenced by inithermo().
ddragoptdepth_dz()
real(dl) function thermodata::ddragoptdepth_dz (real(dl), intent(in) z) private
References doptdepth_dz(), dtauda(), and r_drag0.
Referenced by dragoptdepth().
doptdepth_dz()
real(dl) function thermodata::doptdepth_dz (real(dl), intent(in) z) private
References dtauda().
Referenced by ddragoptdepth_dz(), and optdepth().
dothermospline()
subroutine thermodata::dothermospline (integer j2, real(dl) tau) private
References ddddotmu, dddotmu, ddotmu, ddvis, demmu, dlntau, dopac, dotmu, dowinlens, dvis, dwinlens, emmu, expmmu, lenswin, nthermo, opac, tauminn, vis, and winlens.
Referenced by inithermo().
dragoptdepth()
real(dl) function thermodata::dragoptdepth (real(dl), intent(in) z) private
References ddragoptdepth_dz(), and rombint2().
Referenced by inithermo().
find_z()
subroutine thermodata::find_z (real(dl), external func, real(dl), intent(out) zout) private
Referenced by inithermo().
getbackgroundevolution()
subroutine, public thermodata::getbackgroundevolution (integer, intent(in) ntimes, real(dl), dimension(ntimes), intent(in) times, real(dl), dimension(4, ntimes) outputs)
References demmu, dlntau, emmu, nthermo, splder(), splini(), tauminn, thermo(), vis, and xe.
inithermo()
subroutine, public thermodata::inithermo (real(dl) taumin, real(dl) taumax)
References modelparams::accuracyboost, actual_opt_depth, modelparams::adotrad, modelparams::akthom, modelparams::angulardiameterdistance(), modelparams::backgroundoutputs, modelparams::bao_d_v_from_da_h(), constants::barssc0, constants::compton_ct, modelparams::cp, cs2, dcs2, ddamping_da(), ddddotmu, dddotmu, ddotmu, modelparams::debugmsgs, modelparams::deltaphysicaltimegyr(), demmu, modelparams::derived_age, modelparams::derived_dastar, modelparams::derived_kd, modelparams::derived_keq, modelparams::derived_rdrag, modelparams::derived_rstar, modelparams::derived_theta_rs_eq, modelparams::derived_thetad, modelparams::derived_thetaeq, modelparams::derived_thetastar, modelparams::derived_zdrag, modelparams::derived_zeq, modelparams::derived_zstar, dlntau, modelparams::do_bispectrum, dothermospline(), dotmu, dowinlens, dragoptdepth(), modelparams::dsound_da_exact(), dtauda(), modelparams::dtaurec, dwinlens, emmu, modelparams::feedbacklevel, find_z(), modelparams::grhob, modelparams::grhoc, modelparams::grhog, modelparams::grhom, modelparams::grhormass, modelparams::grhornomass, modelparams::hard_bispectrum, modelparams::hofz(), matter_verydom_tau, maxtau, nthermo, optdepth(), r_drag0, rombint(), scalefactor, sdotmu, settimesteps(), splder(), splini(), modelparams::tau_maxvis, tauminn, modelparams::taurend, modelparams::taurst, tb, modelparams::thermoderivedparams, tight_tau, modelparams::timeofz(), modelparams::timesteps, vis, winlens, xe, z_drag, and z_star.
Referenced by cambmain::initvars().
optdepth()
real(dl) function thermodata::optdepth (real(dl), intent(in) z) private
References doptdepth_dz(), and rombint2().
Referenced by inithermo().
settimesteps()
subroutine thermodata::settimesteps ()
References ddvis, dopac, dowinlens, dvis, expmmu, lenswin, maxtau, opac, and vis.
Referenced by inithermo().
thermo()
subroutine, public thermodata::thermo (real(dl) tau, real(dl) cs2b, real(dl) opacity, real(dl), intent(out), optional dopacity)
References cs2, dcs2, dddotmu, ddotmu, dlntau, dotmu, nthermo, and tauminn.
Referenced by gaugeinterface::derivs(), gaugeinterface::derivst(), gaugeinterface::derivsv(), dtauda(), gaugeinterface::gaugeinterface_evolvescal(), gaugeinterface::gaugeinterface_evolvetens(), and getbackgroundevolution().
thermo_opacitytotime()
real(dl) function, public thermodata::thermo_opacitytotime (real(dl), intent(in) opacity)
References dlntau, dotmu, and tauminn.
Referenced by dtauda(), gaugeinterface::initial(), and gaugeinterface::initialt().
thermodata_free()
subroutine, public thermodata::thermodata_free ()
References ddvis, dopac, dowinlens, dvis, expmmu, lenswin, opac, and vis.
Referenced by camb::camb_cleanup().
Variable Documentation
actual_opt_depth
real(dl) thermodata::actual_opt_depth private
Referenced by inithermo().
cs2
real(dl), dimension(nthermo) thermodata::cs2 private
Referenced by dtauda(), gaugeinterface::gaugeinterface_evolvescal(), inithermo(), and thermo().
dcs2
real(dl), dimension(nthermo) thermodata::dcs2 private
Referenced by inithermo(), and thermo().
ddddotmu
real(dl), dimension(nthermo) thermodata::ddddotmu private
Referenced by dothermospline(), and inithermo().
dddotmu
real(dl), dimension(nthermo) thermodata::dddotmu private
Referenced by dothermospline(), inithermo(), and thermo().
ddotmu
real(dl), dimension(nthermo) thermodata::ddotmu private
Referenced by dothermospline(), inithermo(), and thermo().
ddvis
real(dl), dimension(:), allocatable, public thermodata::ddvis
Referenced by dothermospline(), dtauda(), gaugeinterface::output(), gaugeinterface::outputt(), settimesteps(), and thermodata_free().
demmu
real(dl), dimension(nthermo) thermodata::demmu private
Referenced by dothermospline(), getbackgroundevolution(), and inithermo().
dlntau
real(dl) thermodata::dlntau private
Referenced by dothermospline(), getbackgroundevolution(), inithermo(), thermo(), and thermo_opacitytotime().
dopac
real(dl), dimension(:), allocatable, public thermodata::dopac
Referenced by dothermospline(), dtauda(), gaugeinterface::output(), gaugeinterface::outputt(), settimesteps(), and thermodata_free().
dotmu
real(dl), dimension(nthermo) thermodata::dotmu private
Referenced by dothermospline(), inithermo(), thermo(), and thermo_opacitytotime().
dowinlens
logical, parameter thermodata::dowinlens = .false. private
Referenced by dothermospline(), inithermo(), settimesteps(), and thermodata_free().
dvis
real(dl), dimension(:), allocatable, public thermodata::dvis
Referenced by dothermospline(), dtauda(), gaugeinterface::output(), gaugeinterface::outputt(), gaugeinterface::outputv(), settimesteps(), and thermodata_free().
dwinlens
real(dl), dimension(nthermo) thermodata::dwinlens private
Referenced by dothermospline(), and inithermo().
emmu
real(dl), dimension(nthermo) thermodata::emmu private
Referenced by dothermospline(), getbackgroundevolution(), and inithermo().
expmmu
real(dl), dimension(:), allocatable, public thermodata::expmmu
Referenced by dothermospline(), dtauda(), gaugeinterface::output(), gaugeinterface::outputt(), gaugeinterface::outputv(), settimesteps(), and thermodata_free().
lenswin
real(dl), dimension(:), allocatable, public thermodata::lenswin
Referenced by dothermospline(), settimesteps(), and thermodata_free().
matter_verydom_tau
real(dl), public thermodata::matter_verydom_tau
Referenced by dtauda(), gaugeinterface::gaugeinterface_evolvescal(), and inithermo().
maxtau
real(dl) thermodata::maxtau private
Referenced by inithermo(), and settimesteps().
nthermo
integer, parameter thermodata::nthermo =20000 private
Referenced by dothermospline(), getbackgroundevolution(), inithermo(), and thermo().
opac
real(dl), dimension(:), allocatable, public thermodata::opac
Referenced by dothermospline(), dtauda(), gaugeinterface::output(), gaugeinterface::outputt(), settimesteps(), and thermodata_free().
r_drag0
real(dl) thermodata::r_drag0 private
Referenced by ddamping_da(), ddragoptdepth_dz(), and inithermo().
scalefactor
real(dl), dimension(nthermo) thermodata::scalefactor private
Referenced by inithermo().
sdotmu
real(dl), dimension(nthermo) thermodata::sdotmu private
Referenced by inithermo().
tauminn
real(dl) thermodata::tauminn private
Referenced by dothermospline(), getbackgroundevolution(), inithermo(), thermo(), and thermo_opacitytotime().
tb
real(dl), dimension(nthermo) thermodata::tb private
Referenced by inithermo().
tight_tau
real(dl), public thermodata::tight_tau
Referenced by dtauda(), inithermo(), gaugeinterface::initial(), and gaugeinterface::initialt().
vis
real(dl), dimension(:), allocatable, public thermodata::vis
Referenced by dothermospline(), dtauda(), getbackgroundevolution(), inithermo(), gaugeinterface::output(), gaugeinterface::outputt(), gaugeinterface::outputv(), settimesteps(), and thermodata_free().
winlens
real(dl), dimension(nthermo) thermodata::winlens private
Referenced by dothermospline(), and inithermo().
xe
real(dl), dimension(nthermo) thermodata::xe private
Referenced by getbackgroundevolution(), and inithermo().
z_drag
real(dl), public thermodata::z_drag
Referenced by inithermo().
z_star
real(dl), public thermodata::z_star
Referenced by inithermo().