cosmomc_bde_v3p1: bao Module Reference
bao Module Reference
Data Types
type dr1xlikelihood
type mgslikelihood
type tbaolikelihood
Functions/Subroutines
subroutine, public baolikelihood_add (LikeList, Ini)
subroutine bao_readini (this, Ini)
subroutine bao_initprobdist (this, Ini)
real(mcp) function get_rs_drag (this, Theory)
real(mcp) function acoustic (this, CMB, z)
real(mcp) function bao_lnlike (this, CMB, Theory, DataParams)
subroutine bao_dr1x_initprobdist (this, Ini)
real(mcp) function bao_dr1x_loglike (this, CMB, Theory, DataParams)
subroutine bao_mgs_initprobdist (this, Ini)
real(mcp) function bao_mgs_loglike (this, CMB, Theory, DataParams)
Variables
character(len=ini_enumeration_len), dimension(9), parameter measurement_types = [character(Ini_Enumeration_Len)::'Az','DV_over_rs','rs_over_DV','DA_over_rs', 'F_AP', 'f_sigma8','bao_Hz_rs','bao_Hz_rs_103','dilation']
integer, parameter bao_az =1
integer, parameter bao_dv_over_rs = 2
integer, parameter bao_rs_over_dv = 3
integer, parameter bao_da_over_rs = 4
integer, parameter f_ap = 5
integer, parameter f_sigma8 =6
integer, parameter bao_hz_rs = 7
integer, parameter bao_hz_rs_103 = 8
integer, parameter dilation = 9
real(mcp) bao_fixed_rs = -1._mcp
Function/Subroutine Documentation
acoustic()
real(mcp) function bao::acoustic (class(tbaolikelihood) this, class(cmbparams) CMB, real(mcp), intent(in) z) private
References settings::const_c.
bao_dr1x_initprobdist()
subroutine bao::bao_dr1x_initprobdist (class(dr1xlikelihood) this, class(tsettingini) Ini) private
bao_dr1x_loglike()
real (mcp) function bao::bao_dr1x_loglike (class(dr1xlikelihood) this, class(cmbparams) CMB, class(tcosmotheorypredictions), target Theory, real(mcp), dimension(:) DataParams) private
References settings::logzero.
bao_initprobdist()
subroutine bao::bao_initprobdist (class(tbaolikelihood) this, class(tsettingini) Ini) private
bao_lnlike()
real(mcp) function bao::bao_lnlike (class(tbaolikelihood) this, class(cmbparams) CMB, class(tcosmotheorypredictions), target Theory, real(mcp), dimension(:) DataParams) private
References bao_az, bao_da_over_rs, bao_dv_over_rs, bao_hz_rs, bao_hz_rs_103, bao_rs_over_dv, f_ap, f_sigma8, settings::feedback, and matrixutils::matrix_quadform().
bao_mgs_initprobdist()
subroutine bao::bao_mgs_initprobdist (class(mgslikelihood) this, class(tsettingini) Ini) private
bao_mgs_loglike()
real(mcp) function bao::bao_mgs_loglike (class(mgslikelihood) this, class(cmbparams) CMB, class(tcosmotheorypredictions), target Theory, real(mcp), dimension(:) DataParams) private
References settings::logzero.
bao_readini()
subroutine bao::bao_readini (class(tbaolikelihood) this, class(tsettingini) Ini) private
References f_sigma8, settings::feedback, measurement_types, and settings::mpirank.
baolikelihood_add()
subroutine, public bao::baolikelihood_add (class(tlikelihoodlist) LikeList, class(tsettingini) Ini)
References bao_fixed_rs, and settings::feedback.
Referenced by datalikelihoodlist::setdatalikelihoods().
get_rs_drag()
real(mcp) function bao::get_rs_drag (class(tbaolikelihood) this, class(tcosmotheorypredictions), target Theory) private
References bao_fixed_rs, and cosmologytypes::derived_rdrag.
Variable Documentation
bao_az
integer, parameter bao::bao_az =1 private
Referenced by bao_lnlike().
bao_da_over_rs
integer, parameter bao::bao_da_over_rs = 4 private
Referenced by bao_lnlike().
bao_dv_over_rs
integer, parameter bao::bao_dv_over_rs = 2 private
Referenced by bao_lnlike().
bao_fixed_rs
real(mcp) bao::bao_fixed_rs = -1._mcp private
Referenced by baolikelihood_add(), and get_rs_drag().
bao_hz_rs
integer, parameter bao::bao_hz_rs = 7 private
Referenced by bao_lnlike().
bao_hz_rs_103
integer, parameter bao::bao_hz_rs_103 = 8 private
Referenced by bao_lnlike().
bao_rs_over_dv
integer, parameter bao::bao_rs_over_dv = 3 private
Referenced by bao_lnlike().
dilation
integer, parameter bao::dilation = 9 private
f_ap
integer, parameter bao::f_ap = 5 private
Referenced by bao_lnlike().
f_sigma8
integer, parameter bao::f_sigma8 =6 private
Referenced by bao_lnlike(), and bao_readini().
measurement_types
character(len=ini_enumeration_len), dimension(9), parameter bao::measurement_types = [character(Ini_Enumeration_Len)::'Az','DV_over_rs','rs_over_DV','DA_over_rs', 'F_AP', 'f_sigma8','bao_Hz_rs','bao_Hz_rs_103','dilation'] private
Referenced by bao_readini().