cosmomc_bde_v3p1: getdist.types Namespace Reference
getdist.types Namespace Reference
Classes
class BestFit
class ConvergeStats
class LikelihoodChi2
class LikeStats
class MargeStats
class NoLineTableFormatter
class NumberFormatter
class OpenTableFormatter
class ParamLimit
class ParamResults
class ResultTable
class TableFormatter
class TextFile
Functions
def texEscapeText (string)
def float_to_decimal (f)
def numberFigs (number, sigfig)
Function Documentation
float_to_decimal()
def getdist.types.float_to_decimal (f)
Convert a floating point number to a Decimal with no loss of information
Referenced by getdist.types.numberFigs().
numberFigs()
def getdist.types.numberFigs (number, sigfig)
References CAMB_test_files.float, getdist.types.float_to_decimal(), CAMB_test_files.int, and stringutils.join().
Referenced by getdist.types.NumberFormatter.formatNumber().
texEscapeText()
def getdist.types.texEscapeText (string)
Referenced by getdist.types.TableFormatter.formatTitle().