cosmomc_bde_v3p1: snls Module Reference
snls Module Reference
Data Types
type snlslikelihood
type supernova
type supernova_absdist
Functions/Subroutines
subroutine, public snlslikelihood_add (LikeList, Ini)
subroutine, private count_lines (lun, lines, noncommentlines)
subroutine, private read_cov_matrix (filename, mat, n)
subroutine, private read_snls_lc_data (lun, nlines, nnoncommentlines, sndata)
subroutine, private read_snls_absdist_data (lun, nlines, nnoncommentlines, snabsdist)
subroutine, private match_snls_absdist_indices (sndata, snabsdist)
subroutine read_snls_dataset (this, ini)
subroutine invert_covariance_matrix (invcovmat, alpha, beta, status)
subroutine snls_prep
subroutine snls_cleanup
real(mcp) function snls_alpha_beta_like (alpha, beta, lumdists)
real(mcp) function snls_lnlike (this, CMB, Theory, DataParams)
Variables
logical snls_marginalize = .false.
real(mcp), dimension(:), allocatable snls_marge_grid
real(mcp), dimension(:), allocatable alpha_grid
real(mcp), dimension(:), allocatable beta_grid
integer snls_marge_steps = 0
real(mcp) snls_step_width
real(mcp), parameter snls_alpha_center = 1.442
real(mcp), parameter snls_beta_center = 3.262
integer snls_int_points = 1
character(len= *), parameter snls_version = 'April_2012'
logical, parameter allow_inv_cache = .false.
real(mcp), parameter, private inv_twopi = 1.0_mcp / twopi
character, parameter, private uplo = 'U'
integer, parameter, private max_idisp_datasets = 10
integer, parameter, private snnamelen = 12
real(mcp), parameter, private h0cfac = 5*LOG10(100.0/299792.458)
real(mcp), parameter, private alphatol = 1E-10_mcp
real(mcp), parameter, private betatol = 1E-10_mcp
character(len=30), private name
real(mcp), private pecz
real(mcp), dimension(max_idisp_datasets) intrinsicdisp
logical, private twoscriptmfit
logical, private has_thirdvar
real(mcp), private scriptmcut
integer, public nsn
type(supernova), dimension(:), allocatable, private sndata
real(mcp), dimension(:), allocatable, private pre_vars
real(mcp), dimension(:), allocatable, private a1
real(mcp), dimension(:), allocatable, private a2
logical, private diag_errors = .TRUE.
logical, private has_mag_covmat = .FALSE.
logical, private has_stretch_covmat = .FALSE.
logical, private has_colour_covmat = .FALSE.
logical, private has_mag_stretch_covmat = .FALSE.
logical, private has_mag_colour_covmat = .FALSE.
logical, private has_stretch_colour_covmat = .FALSE.
logical, private alphabeta_covmat = .FALSE.
real(mcp), dimension(:,:), allocatable, private mag_covmat
real(mcp), dimension(:,:), allocatable, private stretch_covmat
real(mcp), dimension(:,:), allocatable, private colour_covmat
real(mcp), dimension(:,:), allocatable, private mag_stretch_covmat
real(mcp), dimension(:,:), allocatable, private mag_colour_covmat
real(mcp), dimension(:,:), allocatable, private stretch_colour_covmat
logical, private has_absdist = .FALSE.
integer, private nabsdist = 0
type(supernova_absdist), dimension(:), allocatable, private snabsdist
real(mcp), dimension(:), allocatable, private lumdists
real(mcp), private alpha_prev
real(mcp), private beta_prev
logical first_inversion
logical snls_read = .FALSE.
logical snls_prepped = .FALSE.
Function/Subroutine Documentation
count_lines()
subroutine, private snls::count_lines (integer, intent(in) lun, integer, intent(out) lines, integer, intent(out) noncommentlines) private
Referenced by read_snls_dataset().
invert_covariance_matrix()
subroutine snls::invert_covariance_matrix (real(mcp), dimension(:,:) invcovmat, real(mcp), intent(in) alpha, real(mcp), intent(in) beta, integer, intent(inout) status) private
References allow_inv_cache, alpha_prev, alphabeta_covmat, alphatol, beta_prev, betatol, colour_covmat, diag_errors, first_inversion, has_colour_covmat, has_mag_colour_covmat, has_mag_covmat, has_mag_stretch_covmat, has_stretch_colour_covmat, has_stretch_covmat, mag_colour_covmat, mag_covmat, mag_stretch_covmat, nsn, pre_vars, sndata, stretch_colour_covmat, stretch_covmat, and uplo.
Referenced by snls_alpha_beta_like().
match_snls_absdist_indices()
subroutine, private snls::match_snls_absdist_indices (type(supernova), dimension(:), intent(inout) sndata, type(supernova_absdist), dimension(:), intent(inout) snabsdist) private
References nabsdist, nsn, snabsdist, and sndata.
Referenced by read_snls_dataset().
read_cov_matrix()
subroutine, private snls::read_cov_matrix (character(len=*), intent(in) filename, real(mcp), dimension(n,n), intent(out) mat, integer, intent(in) n) private
References settings::feedback.
Referenced by read_snls_dataset().
read_snls_absdist_data()
subroutine, private snls::read_snls_absdist_data (integer, intent(in) lun, integer, intent(in) nlines, integer, intent(in) nnoncommentlines, type(supernova_absdist), dimension(nnoncommentlines), intent(out) snabsdist) private
References snabsdist.
Referenced by read_snls_dataset().
read_snls_dataset()
subroutine snls::read_snls_dataset (class(snlslikelihood) this, class(tsettingini) ini) private
References alphabeta_covmat, colour_covmat, count_lines(), settings::datadir, diag_errors, settings::feedback, first_inversion, has_absdist, has_colour_covmat, has_mag_colour_covmat, has_mag_covmat, has_mag_stretch_covmat, has_stretch_colour_covmat, has_stretch_covmat, has_thirdvar, intrinsicdisp, mag_colour_covmat, mag_covmat, mag_stretch_covmat, match_snls_absdist_indices(), max_idisp_datasets, nabsdist, name, nsn, pecz, read_cov_matrix(), read_snls_absdist_data(), read_snls_lc_data(), scriptmcut, snabsdist, sndata, snls_prepped, snls_read, stretch_colour_covmat, stretch_covmat, and twoscriptmfit.
read_snls_lc_data()
subroutine, private snls::read_snls_lc_data (integer, intent(in) lun, integer, intent(in) nlines, integer, intent(in) nnoncommentlines, type(supernova), dimension(nnoncommentlines), intent(out) sndata) private
References has_thirdvar, and sndata.
Referenced by read_snls_dataset().
snls_alpha_beta_like()
real(mcp) function snls::snls_alpha_beta_like (real(mcp) alpha, real(mcp) beta, real(mcp), dimension(nsn) lumdists) private
References a1, a2, diag_errors, settings::feedback, inv_twopi, invert_covariance_matrix(), settings::logzero, lumdists, nsn, pre_vars, sndata, snls_marginalize, twoscriptmfit, and uplo.
Referenced by snls_lnlike().
snls_cleanup()
subroutine snls::snls_cleanup () private
References a1, a2, colour_covmat, lumdists, mag_colour_covmat, mag_covmat, mag_stretch_covmat, pre_vars, snabsdist, sndata, snls_prepped, stretch_colour_covmat, and stretch_covmat.
snls_lnlike()
real(mcp) function snls::snls_lnlike (class(snlslikelihood) this, class (cmbparams) CMB, class(tcosmotheorypredictions), target Theory, real(mcp), dimension(:) DataParams) private
References alpha_grid, beta_grid, settings::feedback, has_absdist, settings::logzero, lumdists, nabsdist, nsn, snabsdist, sndata, snls_alpha_beta_like(), snls_int_points, snls_marge_grid, snls_marginalize, snls_prepped, snls_read, and snls_step_width.
snls_prep()
subroutine snls::snls_prep () private
References a1, a2, settings::feedback, first_inversion, intrinsicdisp, lumdists, nsn, pecz, pre_vars, scriptmcut, sndata, snls_prepped, snls_read, and twoscriptmfit.
Referenced by snlslikelihood_add().
snlslikelihood_add()
subroutine, public snls::snlslikelihood_add (class(tlikelihoodlist) LikeList, class(tsettingini) Ini)
References alpha_grid, beta_grid, settings::datadir, snls_alpha_center, snls_beta_center, snls_int_points, snls_marge_grid, snls_marge_steps, snls_marginalize, snls_prep(), snls_step_width, and snls_version.
Referenced by snovae::snlikelihood_add().
Variable Documentation
a1
real(mcp), dimension(:), allocatable, private snls::a1 private
Referenced by snls_alpha_beta_like(), snls_cleanup(), and snls_prep().
a2
real(mcp), dimension(:), allocatable, private snls::a2 private
Referenced by snls_alpha_beta_like(), snls_cleanup(), and snls_prep().
allow_inv_cache
logical, parameter snls::allow_inv_cache = .false. private
Referenced by invert_covariance_matrix().
alpha_grid
real(mcp), dimension(:), allocatable snls::alpha_grid private
Referenced by snls_lnlike(), and snlslikelihood_add().
alpha_prev
real(mcp), private snls::alpha_prev private
Referenced by invert_covariance_matrix().
alphabeta_covmat
logical, private snls::alphabeta_covmat = .FALSE. private
Referenced by invert_covariance_matrix(), and read_snls_dataset().
alphatol
real(mcp), parameter, private snls::alphatol = 1E-10_mcp private
Referenced by invert_covariance_matrix().
beta_grid
real(mcp), dimension(:), allocatable snls::beta_grid private
Referenced by snls_lnlike(), and snlslikelihood_add().
beta_prev
real(mcp), private snls::beta_prev private
Referenced by invert_covariance_matrix().
betatol
real(mcp), parameter, private snls::betatol = 1E-10_mcp private
Referenced by invert_covariance_matrix().
colour_covmat
real(mcp), dimension(:,:), allocatable, private snls::colour_covmat private
Referenced by invert_covariance_matrix(), read_snls_dataset(), and snls_cleanup().
diag_errors
logical, private snls::diag_errors = .TRUE. private
Referenced by invert_covariance_matrix(), read_snls_dataset(), and snls_alpha_beta_like().
first_inversion
logical snls::first_inversion private
Referenced by invert_covariance_matrix(), read_snls_dataset(), and snls_prep().
h0cfac
real(mcp), parameter, private snls::h0cfac = 5*LOG10(100.0/299792.458) private
has_absdist
logical, private snls::has_absdist = .FALSE. private
Referenced by read_snls_dataset(), and snls_lnlike().
has_colour_covmat
logical, private snls::has_colour_covmat = .FALSE. private
Referenced by invert_covariance_matrix(), and read_snls_dataset().
has_mag_colour_covmat
logical, private snls::has_mag_colour_covmat = .FALSE. private
Referenced by invert_covariance_matrix(), and read_snls_dataset().
has_mag_covmat
logical, private snls::has_mag_covmat = .FALSE. private
Referenced by invert_covariance_matrix(), and read_snls_dataset().
has_mag_stretch_covmat
logical, private snls::has_mag_stretch_covmat = .FALSE. private
Referenced by invert_covariance_matrix(), and read_snls_dataset().
has_stretch_colour_covmat
logical, private snls::has_stretch_colour_covmat = .FALSE. private
Referenced by invert_covariance_matrix(), and read_snls_dataset().
has_stretch_covmat
logical, private snls::has_stretch_covmat = .FALSE. private
Referenced by invert_covariance_matrix(), and read_snls_dataset().
has_thirdvar
logical, private snls::has_thirdvar private
Referenced by read_snls_dataset(), and read_snls_lc_data().
intrinsicdisp
real(mcp), dimension(max_idisp_datasets) snls::intrinsicdisp private
Referenced by read_snls_dataset(), and snls_prep().
inv_twopi
real(mcp), parameter, private snls::inv_twopi = 1.0_mcp / twopi private
Referenced by snls_alpha_beta_like().
lumdists
real(mcp), dimension(:), allocatable, private snls::lumdists private
Referenced by snls_alpha_beta_like(), snls_cleanup(), snls_lnlike(), and snls_prep().
mag_colour_covmat
real(mcp), dimension(:,:), allocatable, private snls::mag_colour_covmat private
Referenced by invert_covariance_matrix(), read_snls_dataset(), and snls_cleanup().
mag_covmat
real(mcp), dimension(:,:), allocatable, private snls::mag_covmat private
Referenced by invert_covariance_matrix(), read_snls_dataset(), and snls_cleanup().
mag_stretch_covmat
real(mcp), dimension(:,:), allocatable, private snls::mag_stretch_covmat private
Referenced by invert_covariance_matrix(), read_snls_dataset(), and snls_cleanup().
max_idisp_datasets
integer, parameter, private snls::max_idisp_datasets = 10 private
Referenced by read_snls_dataset().
nabsdist
integer, private snls::nabsdist = 0 private
Referenced by match_snls_absdist_indices(), read_snls_dataset(), and snls_lnlike().
name
character(len=30), private snls::name private
Referenced by read_snls_dataset().
nsn
integer, public snls::nsn
Referenced by invert_covariance_matrix(), match_snls_absdist_indices(), read_snls_dataset(), snls_alpha_beta_like(), snls_lnlike(), and snls_prep().
pecz
real(mcp), private snls::pecz private
Referenced by read_snls_dataset(), and snls_prep().
pre_vars
real(mcp), dimension(:), allocatable, private snls::pre_vars private
Referenced by invert_covariance_matrix(), snls_alpha_beta_like(), snls_cleanup(), and snls_prep().
scriptmcut
real(mcp), private snls::scriptmcut private
Referenced by read_snls_dataset(), and snls_prep().
snabsdist
type(supernova_absdist), dimension(:), allocatable, private snls::snabsdist private
Referenced by match_snls_absdist_indices(), read_snls_absdist_data(), read_snls_dataset(), snls_cleanup(), and snls_lnlike().
sndata
type(supernova), dimension(:), allocatable, private snls::sndata private
Referenced by invert_covariance_matrix(), match_snls_absdist_indices(), read_snls_dataset(), read_snls_lc_data(), snls_alpha_beta_like(), snls_cleanup(), snls_lnlike(), and snls_prep().
snls_alpha_center
real(mcp), parameter snls::snls_alpha_center = 1.442 private
Referenced by snlslikelihood_add().
snls_beta_center
real(mcp), parameter snls::snls_beta_center = 3.262 private
Referenced by snlslikelihood_add().
snls_int_points
integer snls::snls_int_points = 1 private
Referenced by snls_lnlike(), and snlslikelihood_add().
snls_marge_grid
real(mcp), dimension(:), allocatable snls::snls_marge_grid private
Referenced by snls_lnlike(), and snlslikelihood_add().
snls_marge_steps
integer snls::snls_marge_steps = 0 private
Referenced by snlslikelihood_add().
snls_marginalize
logical snls::snls_marginalize = .false. private
Referenced by snls_alpha_beta_like(), snls_lnlike(), and snlslikelihood_add().
snls_prepped
logical snls::snls_prepped = .FALSE. private
Referenced by read_snls_dataset(), snls_cleanup(), snls_lnlike(), and snls_prep().
snls_read
logical snls::snls_read = .FALSE. private
Referenced by read_snls_dataset(), snls_lnlike(), and snls_prep().
snls_step_width
real(mcp) snls::snls_step_width private
Referenced by snls_lnlike(), and snlslikelihood_add().
snls_version
character(len=*), parameter snls::snls_version = 'April_2012' private
Referenced by snlslikelihood_add().
snnamelen
integer, parameter, private snls::snnamelen = 12 private
stretch_colour_covmat
real(mcp), dimension(:,:), allocatable, private snls::stretch_colour_covmat private
Referenced by invert_covariance_matrix(), read_snls_dataset(), and snls_cleanup().
stretch_covmat
real(mcp), dimension(:,:), allocatable, private snls::stretch_covmat private
Referenced by invert_covariance_matrix(), read_snls_dataset(), and snls_cleanup().
twoscriptmfit
logical, private snls::twoscriptmfit private
Referenced by read_snls_dataset(), snls_alpha_beta_like(), and snls_prep().
uplo
character, parameter, private snls::uplo = 'U' private
Referenced by invert_covariance_matrix(), and snls_alpha_beta_like().