cosmomc_bde_v3p1: runbatch Namespace Reference
runbatch Namespace Reference
Functions
def notQueued (name)
def jobName ()
def submitJob (ini)
Variables
Opts
parser
combinedJobs
action
help
nargs
default
None
const
type
float
batch
args
queued = jobqueue.queue_job_names(args.batchPath)
string variant = ''
importance
noimportance
isMinimize = args.importance_minimize or args.minimize
list iniFiles = []
wantSubItems
converge
returnNotExist
sequential
Function Documentation
jobName()
def runbatch.jobName ()
References stringutils.join().
Referenced by submitJob().
notQueued()
def runbatch.notQueued (name)
submitJob()
def runbatch.submitJob (ini)
References jobName().
Variable Documentation
action
runbatch.action
args
runbatch.args
batch
runbatch.batch
combinedJobs
runbatch.combinedJobs
const
runbatch.const
converge
runbatch.converge
default
runbatch.default
float
runbatch.float
help
runbatch.help
importance
runbatch.importance
iniFiles
runbatch.iniFiles = []
isMinimize
runbatch.isMinimize = args.importance_minimize or args.minimize
nargs
runbatch.nargs
noimportance
runbatch.noimportance
None
runbatch.None
Opts
runbatch.Opts
Initial value:
 =  batchjob_args.batchArgs('Submit jobs to run chains or importance sample', notExist=True, notall=True,
                               converge=True)
parser
runbatch.parser
queued
runbatch.queued = jobqueue.queue_job_names(args.batchPath)
returnNotExist
runbatch.returnNotExist
sequential
runbatch.sequential
type
runbatch.type
variant
string runbatch.variant = ''
wantSubItems
runbatch.wantSubItems