cosmomc_bde_v3p1: miscutils Module Reference
miscutils Module Reference
Data Types
interface ifthenelse
interface isfloat
interface presentdefault
Functions/Subroutines
logical function defaultfalse (S)
logical function defaulttrue (S)
character(len=:) function, pointer presentdefault_s (default, S)
logical function presentdefault_l (default, S)
integer function presentdefault_i (default, S)
real function presentdefault_r (default, S)
double precision function presentdefault_d (default, S)
character(len=:) function, pointer ifthenelse_s (flag, either, or)
logical function ifthenelse_l (flag, either, or)
integer function ifthenelse_i (flag, either, or)
real function ifthenelse_r (flag, either, or)
double precision function ifthenelse_d (flag, either, or)
logical function isfloat0 (R)
logical function isfloat1 (R)
logical function isfloat2 (R)
Function/Subroutine Documentation
defaultfalse()
logical function miscutils::defaultfalse (logical, intent(in), optional S)
Referenced by fileutils::checkopen(), fileutils::extractfilename(), stringutils::formatstring(), iniobjects::ini_namevalue_addline(), iniobjects::ini_open(), iniobjects::ini_read_string_default(), paramnames::paramnames_add(), paramnames::paramnames_nameornumber(), stringutils::stringtrimmed(), fileutils::tfilestream_openfile(), iniobjects::tnamevaluelist_init(), iniobjects::tnamevaluelist_override(), settings::tsettingini_readfilename(), settings::tsettingini_settingvaluesfortagname(), and settings::tsettingini_tagvaluesforname().
defaulttrue()
logical function miscutils::defaulttrue (logical, intent(in), optional S)
Referenced by fileutils::lines(), fileutils::readitems(), and iniobjects::tnamevaluelist_add().
ifthenelse_d()
double precision function miscutils::ifthenelse_d (logical, intent(in) flag, double precision either, double precision or)
ifthenelse_i()
integer function miscutils::ifthenelse_i (logical, intent(in) flag, integer either, integer or)
ifthenelse_l()
logical function miscutils::ifthenelse_l (logical, intent(in) flag, logical either, logical or)
ifthenelse_r()
real function miscutils::ifthenelse_r (logical, intent(in) flag, real either, real or)
ifthenelse_s()
character(len=:) function, pointer miscutils::ifthenelse_s (logical, intent(in) flag, character(len=*), target either, character(len=*), target or)
isfloat0()
logical function miscutils::isfloat0 (class(*), intent(in) R)
Referenced by isfloat1(), and isfloat2().
isfloat1()
logical function miscutils::isfloat1 (class(*), dimension(:), intent(in) R)
References isfloat0().
isfloat2()
logical function miscutils::isfloat2 (class(*), dimension(:,:), intent(in) R)
References isfloat0().
presentdefault_d()
double precision function miscutils::presentdefault_d (double precision, intent(in) default, double precision, intent(in), optional S)
presentdefault_i()
integer function miscutils::presentdefault_i (integer, intent(in) default, integer, intent(in), optional S)
presentdefault_l()
logical function miscutils::presentdefault_l (logical, intent(in) default, logical, intent(in), optional S)
presentdefault_r()
real function miscutils::presentdefault_r (real, intent(in) default, real, intent(in), optional S)
presentdefault_s()
character(len=:) function, pointer miscutils::presentdefault_s (character(len=*), intent(in), target default, character(len=*), intent(in), optional, target S)