cosmomc_bde_v3p1: camb Module Reference
camb Module Reference
Modules
baseconfig
bbn
bispectrum
camb
constants
initialpower
lensing
model
nonlinear
recombination
reionization
Data Types
type cambdata
Functions/Subroutines
subroutine camb_gettransfers (Params, OutData, error)
subroutine camb_initcambdata (Dat)
subroutine camb_freecambdata (Dat)
subroutine camb_transferstopowers (CData)
subroutine camb_getresults (Params, error)
subroutine camb_getcls (Cls, lmax, in, GC_conventions)
real(dl) function camb_getage (P)
real(dl) function camb_getzrefromtau (P, tau)
subroutine camb_setdefparams (P)
subroutine camb_setneutrinohierarchy (P, omnuh2, omnuh2_sterile, nnu, neutrino_hierarchy, num_massive_neutrinos)
logical function camb_validateparams (P)
subroutine camb_cleanup
Variables
string __author__ = "Antony Lewis"
string __contact__ = "antony at cosmologist dot info"
string __status__ = "beta"
string __version__ = "0.1.3"
ThreadNum = dll_import(c_int, "modelparams", "threadnum")
DoTensorNeutrinos = dll_import(c_bool, "gaugeinterface", "dotensorneutrinos")
Magnetic = dll_import(c_double, "gaugeinterface", "magnetic")
vec_sig0 = dll_import(c_double, "gaugeinterface", "vec_sig0")
Function/Subroutine Documentation
camb_cleanup()
subroutine camb::camb_cleanup ()
References spherbessels::bessels_free(), modeldata::modeldata_free(), transfer::mt, thermodata::thermodata_free(), and transfer::transfer_free().
camb_freecambdata()
subroutine camb::camb_freecambdata (type (cambdata) Dat)
References modeldata::free_cltransfer(), and transfer::transfer_free().
Referenced by handles::cambdata_free().
camb_getage()
real(dl) function camb::camb_getage (type(cambparams), intent(in) P)
References modelparams::cambparams_set(), modelparams::deltaphysicaltimegyr(), and initialpower::p.
camb_getcls()
subroutine camb::camb_getcls (real, dimension(2:lmax,1:4), intent(out) Cls, integer, intent(in) lmax, integer, intent(in) in, logical, intent(in) GC_conventions)
References modeldata::c_cross, modeldata::c_e, modeldata::c_temp, modeldata::cl_lensed, modeldata::cl_scalar, modeldata::cl_tensor, modelparams::cp, modeldata::ct_cross, modeldata::ct_temp, and modeldata::lmax_lensed.
Referenced by writefitscls().
camb_getresults()
subroutine camb::camb_getresults (type(cambparams) Params, integer, optional error)
References modelparams::call_again, modelparams::cambparams_set(), cambmain::cmbmain(), modelparams::cp, modeldata::ctransscal, modelparams::do_bispectrum, errors::global_error_flag, modelparams::highaccuracydefault, and lensing::lens_cls().
Referenced by camb_gettransfers(), getsigma8(), and tester().
camb_gettransfers()
subroutine camb::camb_gettransfers (type(cambparams) Params, type (cambdata) OutData, integer error)
References camb_getresults(), modeldata::ctransscal, modeldata::ctranstens, modeldata::ctransvec, modeldata::free_cltransfer(), transfer::mt, and transfer::transfer_free().
Referenced by calculator_camb::cambcalc_getnewtransferdata(), calculator_camb::cambcalc_gettheoryforimportance(), and handles::cambdata_gettransfers().
camb_getzrefromtau()
real(dl) function camb::camb_getzrefromtau (type(cambparams) P, real(dl) tau)
References modelparams::cambparams_set(), modelparams::cp, and initialpower::p.
camb_initcambdata()
subroutine camb::camb_initcambdata (type (cambdata) Dat)
Referenced by calculator_camb::cambcalc_getnewtransferdata(), calculator_camb::cambcalc_gettheoryforimportance(), and handles::cambdata_new().
camb_setdefparams()
subroutine camb::camb_setdefparams (type(cambparams), intent(out) P)
References constants::cobe_cmbtemp, constants::default_nnu, gaugeinterface::initial_adiabatic, modelparams::nonlinear_none, modelparams::nu_best, modelparams::outnone, recombination::recombination_setdefparams(), reionization::reionization_setdefparams(), and initialpower::setdefpowerparams().
Referenced by handles::cambdata_new(), getsigma8(), and tester().
camb_setneutrinohierarchy()
subroutine camb::camb_setneutrinohierarchy (type(cambparams), intent(inout) P, real(dl), intent(in) omnuh2, real(dl), intent(in) omnuh2_sterile, real(dl), intent(in) nnu, integer, intent(in) neutrino_hierarchy, integer, intent(in), optional num_massive_neutrinos)
References constants::default_nnu, constants::delta_mnu21, constants::delta_mnu31, and constants::mnu_min_normal.
Referenced by calculator_camb::cambcalc_cmbtocamb().
camb_transferstopowers()
subroutine camb::camb_transferstopowers (type (cambdata) CData)
References cambmain::cltransfertocl(), modelparams::cp, initialpower::initializepowers(), lensing::lens_cls(), and transfer::transfer_get_sigmas().
Referenced by calculator_camb::cambcalc_getnewpowerdata(), and calculator_camb::cambcalc_gettheoryforimportance().
camb_validateparams()
logical function camb::camb_validateparams (type(cambparams), intent(in) P)
References modelparams::max_transfer_redshifts, initialpower::p, recombination::recombination_validate(), and reionization::reionization_validate().
Variable Documentation
__author__
string camb.__author__ = "Antony Lewis" private
__contact__
string camb.__contact__ = "antony at cosmologist dot info" private
__status__
string camb.__status__ = "beta" private
__version__
string camb.__version__ = "0.1.3" private
DoTensorNeutrinos
camb.DoTensorNeutrinos = dll_import(c_bool, "gaugeinterface", "dotensorneutrinos")
Magnetic
camb.Magnetic = dll_import(c_double, "gaugeinterface", "magnetic")
ThreadNum
camb.ThreadNum = dll_import(c_int, "modelparams", "threadnum")
vec_sig0
camb.vec_sig0 = dll_import(c_double, "gaugeinterface", "vec_sig0")