cosmomc_bde_v3p1: jla Module Reference
jla Module Reference
Data Types
type jlalikelihood
type supernova
type supernova_absdist
Functions/Subroutines
subroutine, public jlalikelihood_add (LikeList, Ini)
subroutine, private count_lines (lun, lines, noncommentlines)
subroutine, private read_cov_matrix (filename, mat, n)
subroutine, private read_jla_lc_data (lun, nlines, nnoncommentlines, sndata)
subroutine, private read_jla_absdist_data (lun, nlines, nnoncommentlines, snabsdist)
subroutine, private match_jla_absdist_indices (sndata, snabsdist)
subroutine, public read_jla_dataset (filename)
subroutine invert_covariance_matrix (invcovmat, alpha, beta, status)
subroutine, public jla_prep
subroutine, public jla_cleanup
real(mcp) function jla_alpha_beta_like (alpha, beta, lumdists)
real(mcp) function, public jla_lnlike (this, CMB, Theory, DataParams)
Variables
logical jla_marginalize = .false.
real(mcp), dimension(:), allocatable jla_marge_grid
real(mcp), dimension(:), allocatable alpha_grid
real(mcp), dimension(:), allocatable beta_grid
integer jla_marge_steps = 0
real(mcp) jla_step_width_alpha
real(mcp) jla_step_width_beta
real(mcp), parameter jla_alpha_center = 0.14
real(mcp), parameter jla_beta_center = 3.123
integer jla_int_points = 1
integer, parameter dl = mcp
character(len= *), parameter jla_version = 'December_2013'
logical, parameter allow_inv_cache = .false.
real(dl), parameter, private inv_twopi = 1.0_dl / twopi
character, parameter, private uplo = 'U'
integer, parameter, private max_idisp_datasets = 10
integer, parameter, private snnamelen = 12
real(dl), parameter, private h0cfac = 5*LOG10(100.0/299792.458)
real(dl), parameter, private alphatol = 1E-10_dl
real(dl), parameter, private betatol = 1E-10_dl
character(len=30), private name
real(dl), private pecz
real(dl), dimension(max_idisp_datasets) intrinsicdisp
logical, private twoscriptmfit
logical, private has_thirdvar
real(dl), private scriptmcut
integer, public nsn
type(supernova), dimension(:), allocatable, private sndata
real(dl), dimension(:), allocatable, private pre_vars
real(dl), dimension(:), allocatable, private a1
real(dl), dimension(:), allocatable, private a2
logical, private diag_errors = .TRUE.
logical, private has_mag_covmat = .FALSE.
logical, private has_stretch_covmat = .FALSE.
logical, private has_colour_covmat = .FALSE.
logical, private has_mag_stretch_covmat = .FALSE.
logical, private has_mag_colour_covmat = .FALSE.
logical, private has_stretch_colour_covmat = .FALSE.
logical, private alphabeta_covmat = .FALSE.
real(dl), dimension(:,:), allocatable, private mag_covmat
real(dl), dimension(:,:), allocatable, private stretch_covmat
real(dl), dimension(:,:), allocatable, private colour_covmat
real(dl), dimension(:,:), allocatable, private mag_stretch_covmat
real(dl), dimension(:,:), allocatable, private mag_colour_covmat
real(dl), dimension(:,:), allocatable, private stretch_colour_covmat
logical, private has_absdist = .FALSE.
integer, private nabsdist = 0
type(supernova_absdist), dimension(:), allocatable, private snabsdist
real(dl), dimension(:), allocatable, private lumdists
real(dl), private alpha_prev
real(dl), private beta_prev
logical, private first_inversion
logical, public jla_read = .FALSE.
logical, public jla_prepped = .FALSE.
Function/Subroutine Documentation
count_lines()
subroutine, private jla::count_lines (integer, intent(in) lun, integer, intent(out) lines, integer, intent(out) noncommentlines) private
Referenced by read_jla_dataset().
invert_covariance_matrix()
subroutine jla::invert_covariance_matrix (real(dl), dimension(:,:) invcovmat, real(dl), intent(in) alpha, real(dl), intent(in) beta, integer, intent(inout) status)
References allow_inv_cache, alpha_prev, alphabeta_covmat, alphatol, beta_prev, betatol, colour_covmat, diag_errors, first_inversion, has_colour_covmat, has_mag_colour_covmat, has_mag_covmat, has_mag_stretch_covmat, has_stretch_colour_covmat, has_stretch_covmat, mag_colour_covmat, mag_covmat, mag_stretch_covmat, nsn, pre_vars, sndata, stretch_colour_covmat, stretch_covmat, and uplo.
Referenced by jla_alpha_beta_like().
jla_alpha_beta_like()
real(mcp) function jla::jla_alpha_beta_like (real(dl) alpha, real(dl) beta, real(dl), dimension(nsn) lumdists)
References a1, a2, diag_errors, settings::feedback, inv_twopi, invert_covariance_matrix(), jla_marginalize, settings::logzero, lumdists, nsn, pre_vars, sndata, twoscriptmfit, and uplo.
Referenced by jla_lnlike().
jla_cleanup()
subroutine, public jla::jla_cleanup ()
References a1, a2, colour_covmat, jla_prepped, lumdists, mag_colour_covmat, mag_covmat, mag_stretch_covmat, pre_vars, snabsdist, sndata, stretch_colour_covmat, and stretch_covmat.
jla_lnlike()
real(mcp) function, public jla::jla_lnlike (class(jlalikelihood) this, class(cmbparams) CMB, class(tcosmotheorypredictions), target Theory, real(mcp), dimension(:) DataParams)
References alpha_grid, beta_grid, settings::feedback, has_absdist, jla_alpha_beta_like(), jla_int_points, jla_marge_grid, jla_marginalize, jla_prepped, jla_read, jla_step_width_alpha, jla_step_width_beta, settings::logzero, lumdists, nabsdist, nsn, snabsdist, and sndata.
jla_prep()
subroutine, public jla::jla_prep ()
References a1, a2, settings::feedback, first_inversion, intrinsicdisp, jla_prepped, jla_read, lumdists, max_idisp_datasets, nsn, pecz, pre_vars, scriptmcut, sndata, and twoscriptmfit.
Referenced by jlalikelihood_add().
jlalikelihood_add()
subroutine, public jla::jlalikelihood_add (class(tlikelihoodlist) LikeList, class(tinifile) Ini)
References alpha_grid, beta_grid, settings::datadir, settings::feedback, jla_alpha_center, jla_beta_center, jla_int_points, jla_marge_grid, jla_marge_steps, jla_marginalize, jla_prep(), jla_step_width_alpha, jla_step_width_beta, jla_version, and read_jla_dataset().
Referenced by snovae::snlikelihood_add().
match_jla_absdist_indices()
subroutine, private jla::match_jla_absdist_indices (type(supernova), dimension(:), intent(inout) sndata, type(supernova_absdist), dimension(:), intent(inout) snabsdist) private
References nabsdist, nsn, snabsdist, and sndata.
Referenced by read_jla_dataset().
read_cov_matrix()
subroutine, private jla::read_cov_matrix (character(len=*), intent(in) filename, real(dl), dimension(n,n), intent(out) mat, integer, intent(in) n) private
References settings::feedback.
Referenced by read_jla_dataset().
read_jla_absdist_data()
subroutine, private jla::read_jla_absdist_data (integer, intent(in) lun, integer, intent(in) nlines, integer, intent(in) nnoncommentlines, type(supernova_absdist), dimension(nnoncommentlines), intent(out) snabsdist) private
References snabsdist.
Referenced by read_jla_dataset().
read_jla_dataset()
subroutine, public jla::read_jla_dataset (character(len=*), intent(in) filename)
References alphabeta_covmat, colour_covmat, count_lines(), settings::datadir, diag_errors, settings::feedback, first_inversion, has_absdist, has_colour_covmat, has_mag_colour_covmat, has_mag_covmat, has_mag_stretch_covmat, has_stretch_colour_covmat, has_stretch_covmat, has_thirdvar, intrinsicdisp, jla_prepped, jla_read, mag_colour_covmat, mag_covmat, mag_stretch_covmat, match_jla_absdist_indices(), max_idisp_datasets, nabsdist, name, nsn, pecz, read_cov_matrix(), read_jla_absdist_data(), read_jla_lc_data(), scriptmcut, snabsdist, sndata, stretch_colour_covmat, stretch_covmat, and twoscriptmfit.
Referenced by jlalikelihood_add().
read_jla_lc_data()
subroutine, private jla::read_jla_lc_data (integer, intent(in) lun, integer, intent(in) nlines, integer, intent(in) nnoncommentlines, type(supernova), dimension(nnoncommentlines), intent(out) sndata) private
References has_thirdvar, and sndata.
Referenced by read_jla_dataset().
Variable Documentation
a1
real(dl), dimension(:), allocatable, private jla::a1 private
Referenced by jla_alpha_beta_like(), jla_cleanup(), and jla_prep().
a2
real(dl), dimension(:), allocatable, private jla::a2 private
Referenced by jla_alpha_beta_like(), jla_cleanup(), and jla_prep().
allow_inv_cache
logical, parameter jla::allow_inv_cache = .false.
Referenced by invert_covariance_matrix().
alpha_grid
real(mcp), dimension(:), allocatable jla::alpha_grid
Referenced by jla_lnlike(), and jlalikelihood_add().
alpha_prev
real(dl), private jla::alpha_prev private
Referenced by invert_covariance_matrix().
alphabeta_covmat
logical, private jla::alphabeta_covmat = .FALSE. private
Referenced by invert_covariance_matrix(), and read_jla_dataset().
alphatol
real(dl), parameter, private jla::alphatol = 1E-10_dl private
Referenced by invert_covariance_matrix().
beta_grid
real(mcp), dimension(:), allocatable jla::beta_grid
Referenced by jla_lnlike(), and jlalikelihood_add().
beta_prev
real(dl), private jla::beta_prev private
Referenced by invert_covariance_matrix().
betatol
real(dl), parameter, private jla::betatol = 1E-10_dl private
Referenced by invert_covariance_matrix().
colour_covmat
real(dl), dimension(:,:), allocatable, private jla::colour_covmat private
Referenced by invert_covariance_matrix(), jla_cleanup(), and read_jla_dataset().
diag_errors
logical, private jla::diag_errors = .TRUE. private
Referenced by invert_covariance_matrix(), jla_alpha_beta_like(), and read_jla_dataset().
dl
integer, parameter jla::dl = mcp
first_inversion
logical, private jla::first_inversion private
Referenced by invert_covariance_matrix(), jla_prep(), and read_jla_dataset().
h0cfac
real(dl), parameter, private jla::h0cfac = 5*LOG10(100.0/299792.458) private
has_absdist
logical, private jla::has_absdist = .FALSE. private
Referenced by jla_lnlike(), and read_jla_dataset().
has_colour_covmat
logical, private jla::has_colour_covmat = .FALSE. private
Referenced by invert_covariance_matrix(), and read_jla_dataset().
has_mag_colour_covmat
logical, private jla::has_mag_colour_covmat = .FALSE. private
Referenced by invert_covariance_matrix(), and read_jla_dataset().
has_mag_covmat
logical, private jla::has_mag_covmat = .FALSE. private
Referenced by invert_covariance_matrix(), and read_jla_dataset().
has_mag_stretch_covmat
logical, private jla::has_mag_stretch_covmat = .FALSE. private
Referenced by invert_covariance_matrix(), and read_jla_dataset().
has_stretch_colour_covmat
logical, private jla::has_stretch_colour_covmat = .FALSE. private
Referenced by invert_covariance_matrix(), and read_jla_dataset().
has_stretch_covmat
logical, private jla::has_stretch_covmat = .FALSE. private
Referenced by invert_covariance_matrix(), and read_jla_dataset().
has_thirdvar
logical, private jla::has_thirdvar private
Referenced by read_jla_dataset(), and read_jla_lc_data().
intrinsicdisp
real(dl), dimension(max_idisp_datasets) jla::intrinsicdisp
Referenced by jla_prep(), and read_jla_dataset().
inv_twopi
real(dl), parameter, private jla::inv_twopi = 1.0_dl / twopi private
Referenced by jla_alpha_beta_like().
jla_alpha_center
real(mcp), parameter jla::jla_alpha_center = 0.14
Referenced by jlalikelihood_add().
jla_beta_center
real(mcp), parameter jla::jla_beta_center = 3.123
Referenced by jlalikelihood_add().
jla_int_points
integer jla::jla_int_points = 1
Referenced by jla_lnlike(), and jlalikelihood_add().
jla_marge_grid
real(mcp), dimension(:), allocatable jla::jla_marge_grid
Referenced by jla_lnlike(), and jlalikelihood_add().
jla_marge_steps
integer jla::jla_marge_steps = 0
Referenced by jlalikelihood_add().
jla_marginalize
logical jla::jla_marginalize = .false.
Referenced by jla_alpha_beta_like(), jla_lnlike(), and jlalikelihood_add().
jla_prepped
logical, public jla::jla_prepped = .FALSE.
Referenced by jla_cleanup(), jla_lnlike(), jla_prep(), and read_jla_dataset().
jla_read
logical, public jla::jla_read = .FALSE.
Referenced by jla_lnlike(), jla_prep(), and read_jla_dataset().
jla_step_width_alpha
real(mcp) jla::jla_step_width_alpha
Referenced by jla_lnlike(), and jlalikelihood_add().
jla_step_width_beta
real(mcp) jla::jla_step_width_beta
Referenced by jla_lnlike(), and jlalikelihood_add().
jla_version
character(len=*), parameter jla::jla_version = 'December_2013'
Referenced by jlalikelihood_add().
lumdists
real(dl), dimension(:), allocatable, private jla::lumdists private
Referenced by jla_alpha_beta_like(), jla_cleanup(), jla_lnlike(), and jla_prep().
mag_colour_covmat
real(dl), dimension(:,:), allocatable, private jla::mag_colour_covmat private
Referenced by invert_covariance_matrix(), jla_cleanup(), and read_jla_dataset().
mag_covmat
real(dl), dimension(:,:), allocatable, private jla::mag_covmat private
Referenced by invert_covariance_matrix(), jla_cleanup(), and read_jla_dataset().
mag_stretch_covmat
real(dl), dimension(:,:), allocatable, private jla::mag_stretch_covmat private
Referenced by invert_covariance_matrix(), jla_cleanup(), and read_jla_dataset().
max_idisp_datasets
integer, parameter, private jla::max_idisp_datasets = 10 private
Referenced by jla_prep(), and read_jla_dataset().
nabsdist
integer, private jla::nabsdist = 0 private
Referenced by jla_lnlike(), match_jla_absdist_indices(), and read_jla_dataset().
name
character(len=30), private jla::name private
Referenced by read_jla_dataset().
nsn
integer, public jla::nsn
Referenced by invert_covariance_matrix(), jla_alpha_beta_like(), jla_lnlike(), jla_prep(), match_jla_absdist_indices(), and read_jla_dataset().
pecz
real(dl), private jla::pecz private
Referenced by jla_prep(), and read_jla_dataset().
pre_vars
real(dl), dimension(:), allocatable, private jla::pre_vars private
Referenced by invert_covariance_matrix(), jla_alpha_beta_like(), jla_cleanup(), and jla_prep().
scriptmcut
real(dl), private jla::scriptmcut private
Referenced by jla_prep(), and read_jla_dataset().
snabsdist
type(supernova_absdist), dimension(:), allocatable, private jla::snabsdist private
Referenced by jla_cleanup(), jla_lnlike(), match_jla_absdist_indices(), read_jla_absdist_data(), and read_jla_dataset().
sndata
type(supernova), dimension(:), allocatable, private jla::sndata private
Referenced by invert_covariance_matrix(), jla_alpha_beta_like(), jla_cleanup(), jla_lnlike(), jla_prep(), match_jla_absdist_indices(), read_jla_dataset(), and read_jla_lc_data().
snnamelen
integer, parameter, private jla::snnamelen = 12 private
stretch_colour_covmat
real(dl), dimension(:,:), allocatable, private jla::stretch_colour_covmat private
Referenced by invert_covariance_matrix(), jla_cleanup(), and read_jla_dataset().
stretch_covmat
real(dl), dimension(:,:), allocatable, private jla::stretch_covmat private
Referenced by invert_covariance_matrix(), jla_cleanup(), and read_jla_dataset().
twoscriptmfit
logical, private jla::twoscriptmfit private
Referenced by jla_alpha_beta_like(), jla_prep(), and read_jla_dataset().
uplo
character, parameter, private jla::uplo = 'U' private
Referenced by invert_covariance_matrix(), and jla_alpha_beta_like().