cosmomc_bde_v3p1: massobservable Module Reference
massobservable Module Reference
Functions/Subroutines
real(dl) function theta500 (m, z)
real(dl) function y500 (m, z)
real(dl) function erf_compl (y, sn, q)
Variables
real(dl), parameter thetastar =6.997
real(dl), parameter alpha_theta =1./3.
real(dl), parameter q =6.
Function/Subroutine Documentation
erf_compl()
real(dl) function massobservable::erf_compl (real(dl) y, real(dl) sn, real(dl) q)
References q.
Referenced by numbercounts::grid_c(), and numbercounts::grid_c_2d().
theta500()
real(dl) function massobservable::theta500 (real(dl), intent(in) m, real(dl), intent(in) z)
References alpha_theta, cosmology::cosmopar, cosmology::da(), cosmology::eh(), and thetastar.
Referenced by numbercounts::grid_c(), and numbercounts::grid_c_2d().
y500()
real(dl) function massobservable::y500 (real(dl), intent(in) m, real(dl), intent(in) z)
References cosmology::cosmopar, cosmology::da(), and cosmology::eh().
Referenced by numbercounts::grid_c(), and numbercounts::grid_c_2d().
Variable Documentation
alpha_theta
real(dl), parameter massobservable::alpha_theta =1./3.
Referenced by theta500().
q
real(dl), parameter massobservable::q =6.
Referenced by massfunction::dndlnm(), erf_compl(), numbercounts::grid_c(), numbercounts::grid_c_2d(), and szcounts::sz_init().
thetastar
real(dl), parameter massobservable::thetastar =6.997
Referenced by theta500().