cosmomc_bde_v3p1: massfunction Module Reference
massfunction Module Reference
Data Types
type masspar
Functions/Subroutines
real(dl) function dndlnm (z, M, g)
subroutine splintnr (XA, YA, Y2A, N, X, Y)
Variables
type(masspar) massfnpar
Function/Subroutine Documentation
dndlnm()
real(dl) function massfunction::dndlnm (real(dl), intent(in) z, real(dl), intent(in) M, real(dl), intent(in) g)
References constants_sz::g, massfnpar, constants_sz::pi, massobservable::q, constants_sz::rhocrit0, and splintnr().
Referenced by numbercounts::get_grid().
splintnr()
subroutine massfunction::splintnr (real(dl), dimension(n) XA, real(dl), dimension(n) YA, real(dl), dimension(n) Y2A, integer N, real(dl) X, real(dl) Y)
Referenced by dndlnm().
Variable Documentation
massfnpar
type (masspar) massfunction::massfnpar
Referenced by dndlnm(), szcounts::sz_init(), and szcounts::szlikelihood_add().