cosmomc_bde_v3p1: wl Module Reference
wl Module Reference
Data Types
type wllikelihood
Functions/Subroutines
subroutine, public wllikelihood_add (LikeList, Ini)
subroutine wl_readini (this, Ini)
real(mcp) function wl_lnlike (this, CMB, Theory, DataParams)
subroutine get_convergence (this, CMB, Theory, xi)
Variables
integer, parameter nlmax = 65
real(mcp), parameter dlnl = 0.2d0
real(mcp) dlntheta = 0.25d0
real(mcp), parameter dx = 0.02d0
real(mcp), parameter xstop = 200.0d0
Function/Subroutine Documentation
get_convergence()
subroutine wl::get_convergence (class(wllikelihood) this, class(cmbparams) CMB, class(tcosmotheorypredictions), target Theory, real(mcp), dimension(:), intent(out) xi)
References settings::const_c, dlnl, dlntheta, dx, nlmax, settings::pi, and xstop.
wl_lnlike()
real(mcp) function wl::wl_lnlike (class(wllikelihood) this, class(cmbparams) CMB, class(tcosmotheorypredictions), target Theory, real(mcp), dimension(:) DataParams)
References matrixutils::matrix_quadform().
wl_readini()
subroutine wl::wl_readini (class(wllikelihood) this, class(tsettingini) Ini) private
References settings::feedback, and matrixutils::matrix_inverse().
wllikelihood_add()
subroutine, public wl::wllikelihood_add (class(tlikelihoodlist) LikeList, class(tsettingini) Ini)
References settings::feedback.
Referenced by datalikelihoodlist::setdatalikelihoods().
Variable Documentation
dlnl
real(mcp), parameter wl::dlnl = 0.2d0 private
Referenced by get_convergence().
dlntheta
real(mcp) wl::dlntheta = 0.25d0 private
Referenced by get_convergence().
dx
real(mcp), parameter wl::dx = 0.02d0 private
Referenced by get_convergence().
nlmax
integer, parameter wl::nlmax = 65 private
Referenced by get_convergence().
xstop
real(mcp), parameter wl::xstop = 200.0d0 private
Referenced by get_convergence().