cosmomc_bde_v3p1: spherbessels Module Reference
spherbessels Module Reference
Functions/Subroutines
subroutine, public initspherbessels
subroutine generatebessels
subroutine, public bessels_free
subroutine, public bjl (L, X, JL)
subroutine, public uspherbesselwithderiv (closed, Chi, l, beta, y1, y2)
subroutine phi_small_closed_int (l, beta, chi, y1, y2)
real(dl) function, public phi_recurs (l, K, beta, chi)
real(dl) function, public phi_langer (l, K, beta, chi)
real(dl) function qintegral (sin_K, alpha, K)
real(dl) function airy_ai (x)
real(dl) function polevl (x, coef, N)
real(dl) function p1evl (x, coef, N)
Variables
real(dl), dimension(:,:), allocatable, public ajl
real(dl), dimension(:,:), allocatable, public ajlpr
real(dl), dimension(:,:), allocatable, public ddajlpr
integer num_xx
integer kmaxfile
integer file_numl
integer, dimension(lmax_arr) file_l
real(dl), parameter, public xlimmin =35._dl
real(dl), parameter, public xlimfrac = 0.05_dl
type(regions), public bessranges
Function/Subroutine Documentation
airy_ai()
real(dl) function spherbessels::airy_ai (real(dl) x) private
References p1evl(), and polevl().
Referenced by phi_langer().
bessels_free()
subroutine, public spherbessels::bessels_free ()
References ajl, ajlpr, bessranges, and ddajlpr.
Referenced by camb::camb_cleanup().
bjl()
subroutine, public spherbessels::bjl (integer L, real(dl) X, real(dl) JL)
Referenced by bjl_external(), and generatebessels().
generatebessels()
subroutine spherbessels::generatebessels ()
References modelparams::accuracyboost, ajl, ajlpr, bessranges, bjl(), modelparams::cp, ddajlpr, modelparams::debugmsgs, modelparams::do_bispectrum, modelparams::feedbacklevel, file_l, file_numl, kmaxfile, lvalues::lsamp, modelparams::max_bessels_etak, modelparams::max_bessels_l_index, num_xx, modelparams::spl_large, spline(), xlimfrac, and xlimmin.
Referenced by initspherbessels().
initspherbessels()
subroutine, public spherbessels::initspherbessels ()
References ajl, modelparams::cp, modelparams::debugmsgs, modelparams::feedbacklevel, file_l, file_numl, generatebessels(), kmaxfile, lvalues::lsamp, and modelparams::max_bessels_etak.
Referenced by cambmain::cmbmain().
p1evl()
real(dl) function spherbessels::p1evl (real(dl) x, real(dl), dimension(n) coef, integer N) private
Referenced by airy_ai().
phi_langer()
real(dl) function, public spherbessels::phi_langer (integer l, integer K, real(dl) beta, real(dl) chi)
References airy_ai(), and qintegral().
Referenced by uspherbesselwithderiv().
phi_recurs()
real(dl) function, public spherbessels::phi_recurs (integer, intent(in) l, integer, intent(in) K, real(dl), intent(in) beta, real(dl), intent(in) chi)
Referenced by phi_small_closed_int(), and uspherbesselwithderiv().
phi_small_closed_int()
subroutine spherbessels::phi_small_closed_int (integer, intent(in) l, real(dl), intent(in) beta, real(dl), intent(in) chi, real(dl) y1, real(dl) y2) private
References phi_recurs().
Referenced by uspherbesselwithderiv().
polevl()
real(dl) function spherbessels::polevl (real(dl) x, real(dl), dimension(n+1) coef, integer N) private
Referenced by airy_ai().
qintegral()
real(dl) function spherbessels::qintegral (real(dl) sin_K, real(dl) alpha, integer K) private
Referenced by phi_langer().
uspherbesselwithderiv()
subroutine, public spherbessels::uspherbesselwithderiv (logical, intent(in) closed, real(dl) Chi, integer l, real(dl) beta, real(dl) y1, real(dl) y2)
References modelparams::accuracyboost, phi_langer(), phi_recurs(), and phi_small_closed_int().
Referenced by cambmain::dorangeint(), cambmain::dorangeinttensor(), and cambmain::integratesourcesbessels().
Variable Documentation
ajl
real(dl), dimension(:,:), allocatable, public spherbessels::ajl
Referenced by bessels_free(), cambmain::doflatintegration(), generatebessels(), and initspherbessels().
ajlpr
real(dl), dimension(:,:), allocatable, public spherbessels::ajlpr
Referenced by bessels_free(), cambmain::doflatintegration(), and generatebessels().
bessranges
type(regions), public spherbessels::bessranges
Referenced by bessels_free(), cambmain::doflatintegration(), and generatebessels().
ddajlpr
real(dl), dimension(:,:), allocatable, public spherbessels::ddajlpr
Referenced by bessels_free(), and generatebessels().
file_l
integer, dimension(lmax_arr) spherbessels::file_l private
Referenced by generatebessels(), and initspherbessels().
file_numl
integer spherbessels::file_numl private
Referenced by generatebessels(), and initspherbessels().
kmaxfile
integer spherbessels::kmaxfile private
Referenced by generatebessels(), and initspherbessels().
num_xx
integer spherbessels::num_xx private
Referenced by generatebessels().
xlimfrac
real(dl), parameter, public spherbessels::xlimfrac = 0.05_dl
Referenced by cambmain::doflatintegration(), and generatebessels().
xlimmin
real(dl), parameter, public spherbessels::xlimmin =35._dl
Referenced by cambmain::doflatintegration(), and generatebessels().