cosmomc_bde_v3p1: camb.bbn Namespace Reference
camb.bbn Namespace Reference
Functions
def yhe_to_ypBBN (Yp)
def ypBBN_to_yhe (YBBN)
def yhe_fit (omegab, dneff, taun)
def dh_fit (omegab, dneff, taun)
def runBBN (eta, DeltaN=0, tau=tau_n, prog='./alter_etannutau.x')
def ypBBN_Parthenope (omegab, neff)
def yhe_to_ypBBN (Yp, ombh2)
def runBBNplot ()
Variables
float hbar = 1.05457e-34
int c = 299792458.
float kB = 1.380650e-23
float MeV = 1.6021764e-13
float eV = MeV / 1e6
float G = 6.6738e-11
float TCMB = 2.7255
mP = np.sqrt(hbar * c / G)
float Mpc = 3.0856776e22
float m_proton = 1.672621637e-27
float m_H = 1.673575e-27
float not4 = 3.9715
float m_He = m_H * not4
float zeta3 = 1.202056903
float tau_n = 880.3
tuple n_photon = (kB * TCMB / hbar / c) ** 3 * zeta3 * 2 / np.pi ** 2
tuple omegafac = (1e5 / Mpc) ** 2 / (8 * np.pi * G) * 3
bool alterBBN = False
ombh2s
list DeltaNs = [-3, -2, -1, -0.5, 0, 0.5, 1, 2, 3, 4, 5, 6, 7]
list lines = []
float Yp_fid = 0.2;
tuple rho_b = ombh2 * omegafac;
def YBBN = yhe_fit(ombh2, DeltaN, tau_n)
tuple n_baryon = (4 * Yp_fid / m_He + (1 - Yp_fid) / m_H) * rho_b
tuple eta = n_baryon / n_photon
def outtxt = runBBN(eta, DeltaN)
D = dh_fit(ombh2, DeltaN, tau_n) * 1e-5
He3
Li7
Li6
Be7
sigYBBN = 0.0003
sigdD = 6e-7
sigHe3
sigLi7
sigLi6
sigBe7
tuple actual_ombh2 = eta * n_photon * (YBBN * m_He / 4 + (1 - YBBN) * m_H) / omegafac
tuple Yp = (eta * n_photon / actual_ombh2 / omegafac - 1 / m_H) / (4 / m_He - 1 / m_H)
tuple line
f = open('BBN_full_alterBBN_' + str(tau_n) + '.dat', 'w')
Function Documentation
dh_fit()
def camb.bbn.dh_fit (omegab, dneff, taun)
runBBN()
def camb.bbn.runBBN (eta, DeltaN = 0, tau = tau_n, prog = './alter_etannutau.x')
Referenced by camb.bbn.runBBNplot().
runBBNplot()
def camb.bbn.runBBNplot ()
References CAMB_test_files.float, stringutils.join(), and camb.bbn.runBBN().
yhe_fit()
def camb.bbn.yhe_fit (omegab, dneff, taun)
yhe_to_ypBBN() [1/2]
def camb.bbn.yhe_to_ypBBN (Yp)
Referenced by camb.bbn.yhe_to_ypBBN().
yhe_to_ypBBN() [2/2]
def camb.bbn.yhe_to_ypBBN (Yp, ombh2)
References camb.bbn.yhe_to_ypBBN().
ypBBN_Parthenope()
def camb.bbn.ypBBN_Parthenope (omegab, neff)
ypBBN_to_yhe()
def camb.bbn.ypBBN_to_yhe (YBBN)
Variable Documentation
actual_ombh2
tuple camb.bbn.actual_ombh2 = eta * n_photon * (YBBN * m_He / 4 + (1 - YBBN) * m_H) / omegafac
alterBBN
bool camb.bbn.alterBBN = False
Be7
camb.bbn.Be7
c
int camb.bbn.c = 299792458.
D
def camb.bbn.D = dh_fit(ombh2, DeltaN, tau_n) * 1e-5
DeltaNs
list camb.bbn.DeltaNs = [-3, -2, -1, -0.5, 0, 0.5, 1, 2, 3, 4, 5, 6, 7]
eta
tuple camb.bbn.eta = n_baryon / n_photon
eV
float camb.bbn.eV = MeV / 1e6
f
camb.bbn.f = open('BBN_full_alterBBN_' + str(tau_n) + '.dat', 'w')
Referenced by camb.camb.CAMBdata.redshift_at_comoving_radial_distance(), and camb.model.CAMBparams.set_cosmology().
G
float camb.bbn.G = 6.6738e-11
hbar
float camb.bbn.hbar = 1.05457e-34
He3
camb.bbn.He3
kB
float camb.bbn.kB = 1.380650e-23
Li6
camb.bbn.Li6
Li7
camb.bbn.Li7
line
tuple camb.bbn.line
Initial value:
 =  (('%12.5f ') * 6 + ('%12.3e %12.2e') * 3) % (
                     actual_ombh2, eta * 1e10, DeltaN, Yp, YBBN, sigYBBN, D, sigdD, He3, sigHe3, Li7, sigLi7)
lines
list camb.bbn.lines = []
m_H
float camb.bbn.m_H = 1.673575e-27
m_He
float camb.bbn.m_He = m_H * not4
m_proton
float camb.bbn.m_proton = 1.672621637e-27
MeV
float camb.bbn.MeV = 1.6021764e-13
mP
camb.bbn.mP = np.sqrt(hbar * c / G)
Mpc
float camb.bbn.Mpc = 3.0856776e22
n_baryon
tuple camb.bbn.n_baryon = (4 * Yp_fid / m_He + (1 - Yp_fid) / m_H) * rho_b
n_photon
tuple camb.bbn.n_photon = (kB * TCMB / hbar / c) ** 3 * zeta3 * 2 / np.pi ** 2
not4
float camb.bbn.not4 = 3.9715
ombh2s
camb.bbn.ombh2s
Initial value:
 =  np.hstack((np.linspace(0.005, 0.02, num=int((0.02 - 0.005) / 0.001), endpoint=False),
                         np.linspace(0.020, 0.024, num=16, endpoint=False),
                         np.linspace(0.024, 0.04, num=int((0.04 - 0.024) / 0.001) + 1, endpoint=True)))
omegafac
tuple camb.bbn.omegafac = (1e5 / Mpc) ** 2 / (8 * np.pi * G) * 3
outtxt
def camb.bbn.outtxt = runBBN(eta, DeltaN)
rho_b
tuple camb.bbn.rho_b = ombh2 * omegafac;
sigBe7
camb.bbn.sigBe7
sigdD
int camb.bbn.sigdD = 6e-7
sigHe3
camb.bbn.sigHe3
sigLi6
camb.bbn.sigLi6
sigLi7
camb.bbn.sigLi7
sigYBBN
float camb.bbn.sigYBBN = 0.0003
tau_n
float camb.bbn.tau_n = 880.3
TCMB
float camb.bbn.TCMB = 2.7255
YBBN
camb.bbn.YBBN = yhe_fit(ombh2, DeltaN, tau_n)
Yp
float camb.bbn.Yp = (eta * n_photon / actual_ombh2 / omegafac - 1 / m_H) / (4 / m_He - 1 / m_H)
Yp_fid
tuple camb.bbn.Yp_fid = 0.2;
zeta3
float camb.bbn.zeta3 = 1.202056903