cosmomc_bde_v3p1: samples Module Reference
samples Module Reference
Data Types
type tdensity1d
type tkernel1d
type tsamplelist
Functions/Subroutines
logical function gelmanrubinevalues (cov, meanscov, evals, num)
subroutine tsamplelist_confidval (L, ix, limfrac, ix1, ix2, Lower, Upper)
real(sample_prec) function density1d_prob (D, x)
subroutine density1d_init (D, n, spacing)
subroutine density1d_free (D)
subroutine density1d_initspline (D)
subroutine density1d_limits (D, p, mn, mx, lim_bot, lim_top)
subroutine kernel1d_init (this, winw, h, has_boundary)
Variables
integer, parameter sample_prec = mcp
Function/Subroutine Documentation
density1d_free()
subroutine samples::density1d_free (class(tdensity1d) D)
density1d_init()
subroutine samples::density1d_init (class(tdensity1d) D, integer, intent(in) n, real(sample_prec), intent(in) spacing)
density1d_initspline()
subroutine samples::density1d_initspline (class(tdensity1d) D)
References spline(), and interpolation::spline_dangle.
density1d_limits()
subroutine samples::density1d_limits (class(tdensity1d) D, real(mcp), intent(in) p, real(mcp), intent(out) mn, real(mcp), intent(out) mx, logical, intent(out) lim_bot, logical, intent(out) lim_top)
density1d_prob()
real(sample_prec) function samples::density1d_prob (class(tdensity1d) D, real(sample_prec), intent(in) x)
gelmanrubinevalues()
logical function samples::gelmanrubinevalues (real(sample_prec), dimension(num,num) cov, real(sample_prec), dimension(num,num) meanscov, real(sample_prec), dimension(num) evals, integer, intent(in) num)
References objectlists::error(), matrixutils::matrix_choleskyrootinverse(), and matrixutils::matrix_diagonalize().
Referenced by mcsamples::doconvergetests(), and samplecollector::tmpichaincollector_updatecovandcheckconverge().
kernel1d_init()
subroutine samples::kernel1d_init (class(tkernel1d) this, integer, intent(in) winw, real(mcp), intent(in) h, logical, intent(in) has_boundary)
tsamplelist_confidval()
subroutine samples::tsamplelist_confidval (class(tsamplelist) L, integer, intent(in) ix, real(sample_prec), intent(in) limfrac, integer, intent(in), optional ix1, integer, intent(in), optional ix2, real(sample_prec), intent(out), optional Lower, real(sample_prec), intent(out), optional Upper)
Variable Documentation
sample_prec
integer, parameter samples::sample_prec = mcp