cosmomc_bde_v3p1: constants_sz Module Reference
constants_sz Module Reference
Variables
real(dl), parameter mpc = 3.08568025d22
real(dl), parameter g = 6.67300d-11
real(dl), parameter c = 3.0d8
real(dl), parameter msun = 1.98892d30
real(dl), parameter rhocrit0 =2.7751973751261264d11
real(dl), parameter pi =3.141592653589793238463D0
Variable Documentation
c
real(dl), parameter constants_sz::c = 3.0d8
g
real(dl), parameter constants_sz::g = 6.67300d-11
Referenced by massfunction::dndlnm().
mpc
real(dl), parameter constants_sz::mpc = 3.08568025d22
msun
real(dl), parameter constants_sz::msun = 1.98892d30
pi
real(dl), parameter constants_sz::pi =3.141592653589793238463D0
Referenced by massfunction::dndlnm(), numbercounts::grid_c(), and numbercounts::grid_c_2d().
rhocrit0
real(dl), parameter constants_sz::rhocrit0 =2.7751973751261264d11
Referenced by massfunction::dndlnm().