cosmomc_bde_v3p1: paramgrid.jobqueue Namespace Reference
paramgrid.jobqueue Namespace Reference
Classes
class jobIndex
class jobSettings
Functions
def addArguments (parser, combinedJobs=False)
def replacePlaceholders (txt, vals)
def extractValue (template, name)
def getDefaulted (key_name, default=None, tp=str, template=None, ext_env=None, kwargs)
def checkArguments (kwargs)
def loadJobIndex (batchPath, must_exist=False)
def saveJobIndex (obj, batchPath=None)
def addJobIndex (batchPath, j)
def deleteJobNames (batchPath, jobNames)
def deleteRootNames (batchPath, rootNames)
def deleteJobs (batchPath, jobIds=None, rootNames=None, jobNames=None, jobId_minmax=None, jobId_min=None, confirm=True, running=False, queued=False)
def submitJob (jobName, paramFiles, sequential=False, msg=False, kwargs)
def queue_job_details (batchPath=None, running=True, queued=True, warnNotBatch=True)
def queue_job_names (batchPath=None, running=False, queued=True)
Function Documentation
addArguments()
def paramgrid.jobqueue.addArguments (parser, combinedJobs = False)
References CAMB_test_files.int.
addJobIndex()
def paramgrid.jobqueue.addJobIndex (batchPath, j)
References paramgrid.jobqueue.loadJobIndex(), and paramgrid.jobqueue.saveJobIndex().
Referenced by paramgrid.jobqueue.submitJob().
checkArguments()
def paramgrid.jobqueue.checkArguments (kwargs)
References paramgrid.jobqueue.submitJob().
deleteJobNames()
def paramgrid.jobqueue.deleteJobNames (batchPath, jobNames)
References paramgrid.jobqueue.loadJobIndex(), and paramgrid.jobqueue.saveJobIndex().
deleteJobs()
def paramgrid.jobqueue.deleteJobs (batchPath, jobIds = None, rootNames = None, jobNames = None, jobId_minmax = None, jobId_min = None, confirm = True, running = False, queued = False)
References CAMB_test_files.int, paramgrid.jobqueue.loadJobIndex(), paramgrid.jobqueue.queue_job_details(), and paramgrid.jobqueue.saveJobIndex().
Referenced by paramgrid.jobqueue.deleteRootNames().
deleteRootNames()
def paramgrid.jobqueue.deleteRootNames (batchPath, rootNames)
References paramgrid.jobqueue.deleteJobs().
extractValue()
def paramgrid.jobqueue.extractValue (template, name)
Referenced by paramgrid.jobqueue.getDefaulted().
getDefaulted()
def paramgrid.jobqueue.getDefaulted (key_name, default = None, tp = str, template = None, ext_env = None, kwargs)
References paramgrid.jobqueue.extractValue(), and makePlots.tp.
loadJobIndex()
def paramgrid.jobqueue.loadJobIndex (batchPath, must_exist = False)
Referenced by paramgrid.jobqueue.addJobIndex(), paramgrid.jobqueue.deleteJobNames(), paramgrid.jobqueue.deleteJobs(), and paramgrid.jobqueue.queue_job_details().
queue_job_details()
def paramgrid.jobqueue.queue_job_details (batchPath = None, running = True, queued = True, warnNotBatch = True)
Return: list of jobIds, list of jobNames, list of list names
References paramgrid.jobqueue.loadJobIndex(), and correlated_iso.upper.
Referenced by paramgrid.jobqueue.deleteJobs(), and paramgrid.jobqueue.queue_job_names().
queue_job_names()
def paramgrid.jobqueue.queue_job_names (batchPath = None, running = False, queued = True)
References paramgrid.jobqueue.queue_job_details().
replacePlaceholders()
def paramgrid.jobqueue.replacePlaceholders (txt, vals)
Referenced by paramgrid.jobqueue.submitJob().
saveJobIndex()
def paramgrid.jobqueue.saveJobIndex (obj, batchPath = None)
Referenced by paramgrid.jobqueue.addJobIndex(), paramgrid.jobqueue.deleteJobNames(), and paramgrid.jobqueue.deleteJobs().
submitJob()
def paramgrid.jobqueue.submitJob (jobName, paramFiles, sequential = False, msg = False, kwargs)
References paramgrid.jobqueue.addJobIndex(), stringutils.join(), paramgrid.jobqueue.replacePlaceholders(), and copyGridFiles.zip.
Referenced by paramgrid.jobqueue.checkArguments().