cosmomc_bde_v3p1: generaltypes Module Reference
generaltypes Module Reference
Data Types
type genericparameterization
type int_arr
type tcalculationatparampoint
type tcheckpointable
type tconfigclass
type tdatalikelihood
type tgeneralconfig
type tlikelihoodlist
type tobjectwithparams
type tparameterization
type ttheorycalculator
type ttheoryintermediatecache
type ttheoryparams
type ttheorypredictions
Functions/Subroutines
subroutine paramarraytotheoryparams (this, Params, CMB)
subroutine tparameterization_initialize (this, Ini, Names, DefaultName, Config)
real(mcp) function tparameterization_nonbaseparameterpriors (this, CMB)
subroutine tparameterization_calcderivedparams (this, P, Theory, derived)
subroutine tparameterization_newtheoryparams (this, TheoryParams)
subroutine ttheorypredictions_clear (this)
subroutine tcalculationatparampoint_clear (this, Keep)
subroutine tcalculationatparampoint_acceptreject (this, Trial, accpt)
subroutine tcalculationatparampoint_writeparams (this, Config, mult, like)
subroutine writemodel (this, F, like, mult)
subroutine readmodel (this, F, has_likes, mult, like, error)
subroutine ttheoryintermediatecache_clear (Info)
subroutine ttheorycalculator_initforlikelihoods (this)
subroutine ttheorycalculator_readimportanceparams (this, Ini)
subroutine ttheorycalculator_gettheoryforimportance (this, CMB, Theory, error)
subroutine ttheorycalculator_versiontraceoutput (this, ReadValues)
subroutine ttheorycalculator_errornotimplemented (this, S)
subroutine ttheorycalculator_error (this, S)
subroutine tconfigclass_initconfig (this, Config)
subroutine tconfigclass_initwithparams (this, Ini, Config)
subroutine writetheory (this, F, first)
subroutine readtheory (this, F, first)
subroutine writetextdata (this, fnameroot)
subroutine tgeneralconfig_settheoryparameterization (this, Ini, Names, defaultParam)
logical function tgeneralconfig_setparameterizationname (this, nametag, Ini, Names)
subroutine tgeneralconfig_newtheory (this, Theory)
subroutine tgeneralconfig_initforlikelihoods (this)
subroutine tcheckpointable_readparams (this, Ini)
subroutine tobjectwithparams_readparams (this, Ini)
real(mcp) function tdatalikelihood_getloglike (this, Params, Theory, DataParams)
subroutine tdatalikelihood_writelikelihooddata (this, Theory, DataParams, root)
subroutine tdatalikelihood_initconfig (this, Config)
real(mcp) function, dimension(this%nuisance_params%num_derived) tdatalikelihood_derivedparameters (this, Theory, DataParams)
subroutine tdatalikelihood_loadparamnames (this, fname)
logical function tdatalikelihood_checkconflicts (this, full_list)
character(len=:) function, allocatable tdatalikelihood_gettag (this)
class(tdatalikelihood) function, pointer likelihooditem (L, i)
subroutine writelikelihoodcontribs (L, aunit, likelihoods)
subroutine writedataforlikelihoods (L, P, Theory, fileroot)
integer function comparelikes (this, R1, R2)
subroutine addnuisanceparameters (L, Names)
subroutine addoutputlikelihoodparams (L, Names)
subroutine checkallconflicts (L)
subroutine addlikelihoodderivedparams (L, P, Theory, derived, Likelihoods, logLike)
subroutine outputdescription (L, fname)
Variables
integer, parameter, public likenamelen = 80
integer, parameter liketaglen = 20
type(tlikelihoodlist), target, save, public datalikelihoods
Function/Subroutine Documentation
addlikelihoodderivedparams()
subroutine generaltypes::addlikelihoodderivedparams (class(tlikelihoodlist) L, real(mcp), dimension(:) P, class(ttheorypredictions), allocatable Theory, real(mcp), dimension(:), allocatable derived, real(mcp), dimension(:), intent(in), optional Likelihoods, real(mcp), intent(in), optional logLike) private
addnuisanceparameters()
subroutine generaltypes::addnuisanceparameters (class(tlikelihoodlist) L, type(tparamnames) Names) private
addoutputlikelihoodparams()
subroutine generaltypes::addoutputlikelihoodparams (class(tlikelihoodlist) L, type(tparamnames) Names) private
checkallconflicts()
subroutine generaltypes::checkallconflicts (class(tlikelihoodlist) L) private
comparelikes()
integer function generaltypes::comparelikes (class(tlikelihoodlist) this, class(*) R1, class(*) R2) private
likelihooditem()
class(tdatalikelihood) function, pointer generaltypes::likelihooditem (class(tlikelihoodlist) L, integer, intent(in) i) private
outputdescription()
subroutine generaltypes::outputdescription (class(tlikelihoodlist) L, character(len=*), intent(in) fname) private
paramarraytotheoryparams()
subroutine generaltypes::paramarraytotheoryparams (class(tparameterization) this, real(mcp), dimension(:) Params, class(ttheoryparams), target CMB) private
readmodel()
subroutine generaltypes::readmodel (class(tcalculationatparampoint) this, class(tfilestream) F, logical, dimension(:), intent(out) has_likes, real(mcp), intent(out) mult, real(mcp), intent(out) like, integer, intent(out) error) private
readtheory()
subroutine generaltypes::readtheory (class(ttheorypredictions) this, class(tfilestream) F, logical, intent(in) first) private
tcalculationatparampoint_acceptreject()
subroutine generaltypes::tcalculationatparampoint_acceptreject (class(tcalculationatparampoint) this, class(tcalculationatparampoint) Trial, logical, intent(in) accpt) private
tcalculationatparampoint_clear()
subroutine generaltypes::tcalculationatparampoint_clear (class(tcalculationatparampoint) this, class(tcalculationatparampoint) Keep) private
tcalculationatparampoint_writeparams()
subroutine generaltypes::tcalculationatparampoint_writeparams (class(tcalculationatparampoint) this, class(tgeneralconfig) Config, real(mcp), intent(in) mult, real(mcp), intent(in) like) private
References datalikelihoods, and io::io_outputchainrow().
tcheckpointable_readparams()
subroutine generaltypes::tcheckpointable_readparams (class(tcheckpointable) this, class(tsettingini) Ini) private
tconfigclass_initconfig()
subroutine generaltypes::tconfigclass_initconfig (class(tconfigclass) this, class(tgeneralconfig), target Config) private
tconfigclass_initwithparams()
subroutine generaltypes::tconfigclass_initwithparams (class(tconfigclass) this, class(tsettingini) Ini, class(tgeneralconfig), target Config) private
tdatalikelihood_checkconflicts()
logical function generaltypes::tdatalikelihood_checkconflicts (class(tdatalikelihood) this, class(tlikelihoodlist) full_list) private
tdatalikelihood_derivedparameters()
real(mcp) function, dimension(this%nuisance_params%num_derived) generaltypes::tdatalikelihood_derivedparameters (class(tdatalikelihood) this, class(ttheorypredictions) Theory, real(mcp), dimension(:) DataParams) private
tdatalikelihood_getloglike()
real(mcp) function generaltypes::tdatalikelihood_getloglike (class(tdatalikelihood) this, class(ttheoryparams) Params, class(ttheorypredictions) Theory, real(mcp), dimension(:) DataParams) private
tdatalikelihood_gettag()
character(len=:) function, allocatable generaltypes::tdatalikelihood_gettag (class(tdatalikelihood) this) private
tdatalikelihood_initconfig()
subroutine generaltypes::tdatalikelihood_initconfig (class(tdatalikelihood) this, class(tgeneralconfig), target Config) private
tdatalikelihood_loadparamnames()
subroutine generaltypes::tdatalikelihood_loadparamnames (class(tdatalikelihood) this, character(len=*), intent(in) fname) private
tdatalikelihood_writelikelihooddata()
subroutine generaltypes::tdatalikelihood_writelikelihooddata (class(tdatalikelihood) this, class(ttheorypredictions) Theory, real(mcp), dimension(:), intent(in) DataParams, character(len=*), intent(in) root) private
tgeneralconfig_initforlikelihoods()
subroutine generaltypes::tgeneralconfig_initforlikelihoods (class(tgeneralconfig) this) private
References datalikelihoods.
tgeneralconfig_newtheory()
subroutine generaltypes::tgeneralconfig_newtheory (class(tgeneralconfig) this, class(ttheorypredictions), allocatable Theory) private
tgeneralconfig_setparameterizationname()
logical function generaltypes::tgeneralconfig_setparameterizationname (class(tgeneralconfig) this, character(len=*), intent(in) nametag, class(tsettingini) Ini, class(tparamnames) Names) private
tgeneralconfig_settheoryparameterization()
subroutine generaltypes::tgeneralconfig_settheoryparameterization (class(tgeneralconfig) this, class(tsettingini) Ini, class(tparamnames) Names, character(len=*), intent(in) defaultParam) private
tobjectwithparams_readparams()
subroutine generaltypes::tobjectwithparams_readparams (class(tobjectwithparams) this, class(tsettingini) Ini) private
tparameterization_calcderivedparams()
subroutine generaltypes::tparameterization_calcderivedparams (class(tparameterization) this, real(mcp), dimension(:) P, class(ttheorypredictions), allocatable Theory, real(mcp), dimension(:), allocatable derived) private
tparameterization_initialize()
subroutine generaltypes::tparameterization_initialize (class(tparameterization) this, class(tsettingini) Ini, class(tparamnames) Names, character(len=*), intent(in) DefaultName, class(tgeneralconfig), target Config) private
tparameterization_newtheoryparams()
subroutine generaltypes::tparameterization_newtheoryparams (class(tparameterization) this, class(ttheoryparams), allocatable TheoryParams) private
tparameterization_nonbaseparameterpriors()
real(mcp) function generaltypes::tparameterization_nonbaseparameterpriors (class(tparameterization) this, class(ttheoryparams) CMB) private
ttheorycalculator_error()
subroutine generaltypes::ttheorycalculator_error (class(ttheorycalculator) this, character(len=*), intent(in) S) private
ttheorycalculator_errornotimplemented()
subroutine generaltypes::ttheorycalculator_errornotimplemented (class(ttheorycalculator) this, character(len=*), intent(in) S) private
ttheorycalculator_gettheoryforimportance()
subroutine generaltypes::ttheorycalculator_gettheoryforimportance (class(ttheorycalculator) this, class(ttheoryparams) CMB, class(ttheorypredictions) Theory, integer error) private
ttheorycalculator_initforlikelihoods()
subroutine generaltypes::ttheorycalculator_initforlikelihoods (class(ttheorycalculator) this) private
ttheorycalculator_readimportanceparams()
subroutine generaltypes::ttheorycalculator_readimportanceparams (class(ttheorycalculator) this, class(tsettingini) Ini) private
ttheorycalculator_versiontraceoutput()
subroutine generaltypes::ttheorycalculator_versiontraceoutput (class(ttheorycalculator) this, class(tnamevaluelist) ReadValues) private
ttheoryintermediatecache_clear()
subroutine generaltypes::ttheoryintermediatecache_clear (class(ttheoryintermediatecache) Info) private
ttheorypredictions_clear()
subroutine generaltypes::ttheorypredictions_clear (class(ttheorypredictions) this) private
writedataforlikelihoods()
subroutine generaltypes::writedataforlikelihoods (class(tlikelihoodlist) L, real(mcp), dimension(:), intent(in) P, class(ttheorypredictions), intent(in) Theory, character(len=*), intent(in) fileroot) private
writelikelihoodcontribs()
subroutine generaltypes::writelikelihoodcontribs (class(tlikelihoodlist) L, integer, intent(in) aunit, real(mcp), dimension(*), intent(in) likelihoods) private
writemodel()
subroutine generaltypes::writemodel (class(tcalculationatparampoint) this, class(tfilestream) F, real(mcp), intent(in) like, real(mcp), intent(in) mult) private
writetextdata()
subroutine generaltypes::writetextdata (class(ttheorypredictions) this, character(len=*), intent(in) fnameroot) private
writetheory()
subroutine generaltypes::writetheory (class(ttheorypredictions) this, class(tfilestream) F, logical, intent(in) first) private
Variable Documentation
datalikelihoods
type(tlikelihoodlist), target, save, public generaltypes::datalikelihoods
Referenced by cosmologytypes::initialize_cmbsettings(), cosmologytypes::initialize_pksettings(), parampointset::paramset_readmodel(), parampointset::paramset_writemodel(), tcalculationatparampoint_writeparams(), cosmologytypes::tcosmologyparameterization_setnumbers(), cosmologytypes::tcosmotheorysettings_initforlikelihoods(), tgeneralconfig_initforlikelihoods(), and generalsetup::tsetup_dotests().
likenamelen
integer, parameter, public generaltypes::likenamelen = 80
liketaglen
integer, parameter generaltypes::liketaglen = 20 private