cosmomc_bde_v3p1: propose Module Reference
propose Module Reference
Data Types
type blockedproposer
type blockproposer
type cyclicindexrandomizer
type indexcycler
type randdirectionproposer
type tcovmatproposer
Functions/Subroutines
integer function next (this)
subroutine rotmatrix (M, n)
real(mcp) function, dimension(this%n) proposevec (this, wid)
real(mcp) function propose_r (this)
subroutine updateparams (this, P, vec)
subroutine init (this, parameter_blocks, slow_block_max, oversample_fast, propose_scale)
subroutine blockedproposer_setcovariance (this, propose_matrix)
subroutine getblockproposal (this, P, i)
subroutine getproposal (this, P)
subroutine getproposalslow (this, P)
subroutine getproposalfast (this, P)
subroutine getproposalfastdelta (this, P)
subroutine tcovmatproposer_setcovariance (this, propose_matrix)
subroutine tcovmatproposer_loadstate (this, F)
subroutine tcovmatproposer_savestate (this, F)
Variables
logical propose_rand_directions = .true.
Function/Subroutine Documentation
blockedproposer_setcovariance()
subroutine propose::blockedproposer_setcovariance (class(blockedproposer), target this, real(mcp), dimension(:,:), intent(in) propose_matrix)
References matrixutils::matrix_cholesky().
getblockproposal()
subroutine propose::getblockproposal (class(blockedproposer) this, real(mcp), dimension(:) P, integer, intent(in) i)
getproposal()
subroutine propose::getproposal (class(blockedproposer) this, real(mcp), dimension(:) P)
References getproposalfast(), and getproposalslow().
getproposalfast()
subroutine propose::getproposalfast (class(blockedproposer) this, real(mcp), dimension(:) P)
Referenced by getproposal().
getproposalfastdelta()
subroutine propose::getproposalfastdelta (class(blockedproposer) this, real(mcp), dimension(:) P)
getproposalslow()
subroutine propose::getproposalslow (class(blockedproposer) this, real(mcp), dimension(:) P)
Referenced by getproposal().
init()
subroutine propose::init (class(blockedproposer), target this, type(int_arr), dimension(:) parameter_blocks, integer, intent(in) slow_block_max, integer, intent(in), optional oversample_fast, real(mcp), intent(in), optional propose_scale)
References settings::params_used.
next()
integer function propose::next (class(cyclicindexrandomizer) this)
References randutils::randindices().
propose_r()
real(mcp) function propose::propose_r (class(randdirectionproposer), intent(in) this)
References randutils::gaussian1(), randutils::randexp1(), and randutils::ranmar().
proposevec()
real(mcp) function, dimension(this%n) propose::proposevec (class(randdirectionproposer) this, real(mcp) wid)
References rotmatrix().
rotmatrix()
subroutine propose::rotmatrix (real(mcp), dimension(n,n) M, integer, intent(in) n)
References propose_rand_directions.
Referenced by proposevec().
tcovmatproposer_loadstate()
subroutine propose::tcovmatproposer_loadstate (class(tcovmatproposer) this, class(tfilestream) F)
tcovmatproposer_savestate()
subroutine propose::tcovmatproposer_savestate (class(tcovmatproposer) this, class(tfilestream) F)
tcovmatproposer_setcovariance()
subroutine propose::tcovmatproposer_setcovariance (class(tcovmatproposer), target this, real(mcp), dimension(:,:), intent(in) propose_matrix)
updateparams()
subroutine propose::updateparams (class(blockproposer) this, real(mcp), dimension(:) P, real(mcp), dimension(this%n) vec)
Variable Documentation
propose_rand_directions
logical propose::propose_rand_directions = .true.
Referenced by rotmatrix().