cosmomc_bde_v3p1: cosmologytypes Module Reference
cosmologytypes Module Reference
Data Types
type cmbparams
type tcosmologyparameterization
type tcosmologyrequirementslikelihood
type tcosmotheoryparams
type tcosmotheorysettings
Functions/Subroutines
subroutine tcosmologyparameterization_setnumbers (this, slow_num, semi_slow_num)
subroutine tcosmologyparameterization_newtheoryparams (this, TheoryParams)
subroutine tcosmotheorysettings_readparams (this, Ini)
subroutine tcosmotheorysettings_initforlikelihoods (this)
subroutine initialize_cmbsettings (this)
subroutine initialize_pksettings (this)
subroutine tcosmologyrequirementslikelihood_initforsettings (this, Settings)
Variables
integer, parameter derived_age =1
integer, parameter derived_zstar =2
integer, parameter derived_rstar =3
integer, parameter derived_thetastar =4
integer, parameter derived_dastar = 5
integer, parameter derived_zdrag =6
integer, parameter derived_rdrag =7
integer, parameter derived_kd =8
integer, parameter derived_thetad =9
integer, parameter derived_zeq =10
integer, parameter derived_keq =11
integer, parameter derived_thetaeq =12
integer, parameter derived_theta_rs_eq = 13
integer, parameter as_index =1
integer, parameter ns_index =2
integer, parameter nrun_index =3
integer, parameter nrunrun_index =4
integer, parameter amp_ratio_index = 5
integer, parameter nt_index = 6
integer, parameter ntrun_index = 7
integer, parameter aphiphi_index = 8
integer, parameter last_power_index = Aphiphi_index
integer, parameter max_inipower_params = 10
real(mcp), parameter cl_norm = 1e-10_mcp
integer, parameter max_derived_parameters = 326
integer num_hard
integer num_initpower
integer index_initpower
character(len=4), parameter cmb_cl_fields = 'TEBP'
integer, parameter neutrino_hierarchy_normal = 1
integer, parameter neutrino_hierarchy_inverted = 2
integer, parameter neutrino_hierarchy_degenerate = 3
character(len=ini_enumeration_len), dimension(3), parameter neutrino_types = [character(Ini_Enumeration_Len)::'normal','inverted','degenerate']
integer, parameter cl_t = 1
integer, parameter cl_e =2
integer, parameter cl_b =3
integer, parameter cl_phi =4
type(tcosmotheorysettings), target, save cosmosettings
Function/Subroutine Documentation
initialize_cmbsettings()
subroutine cosmologytypes::initialize_cmbsettings (class(tcosmotheorysettings) this)
References cl_phi, and generaltypes::datalikelihoods.
initialize_pksettings()
subroutine cosmologytypes::initialize_pksettings (class(tcosmotheorysettings) this)
References cosmosettings, and generaltypes::datalikelihoods.
tcosmologyparameterization_newtheoryparams()
subroutine cosmologytypes::tcosmologyparameterization_newtheoryparams (class(tcosmologyparameterization) this, class(ttheoryparams), allocatable TheoryParams)
tcosmologyparameterization_setnumbers()
subroutine cosmologytypes::tcosmologyparameterization_setnumbers (class(tcosmologyparameterization) this, integer, intent(in) slow_num, integer, intent(in) semi_slow_num)
References generaltypes::datalikelihoods, index_initpower, settings::index_semislow, max_inipower_params, num_hard, num_initpower, and settings::num_theory_params.
tcosmologyrequirementslikelihood_initforsettings()
subroutine cosmologytypes::tcosmologyrequirementslikelihood_initforsettings (class(tcosmologyrequirementslikelihood) this, class(tcosmotheorysettings) Settings)
tcosmotheorysettings_initforlikelihoods()
subroutine cosmologytypes::tcosmotheorysettings_initforlikelihoods (class(tcosmotheorysettings) this)
References cmb_cl_fields, generaltypes::datalikelihoods, settings::feedback, and settings::mpirank.
tcosmotheorysettings_readparams()
subroutine cosmologytypes::tcosmotheorysettings_readparams (class(tcosmotheorysettings) this, class(tsettingini) Ini)
References neutrino_hierarchy_degenerate, neutrino_hierarchy_normal, and neutrino_types.
Variable Documentation
amp_ratio_index
integer, parameter cosmologytypes::amp_ratio_index = 5
aphiphi_index
integer, parameter cosmologytypes::aphiphi_index = 8
Referenced by calculator_camb::cambcalc_setpowersfromcamb().
as_index
integer, parameter cosmologytypes::as_index =1
Referenced by cosmologyparameterizations::setfast(), and cosmologyparameterizations::tp_calcderivedparams().
cl_b
integer, parameter cosmologytypes::cl_b =3
Referenced by cmblikes::adapttheoryformaps(), cliklike::clik_likeinit(), and cmblikelihoods::twmaplikelihood_readparams().
cl_e
integer, parameter cosmologytypes::cl_e =2
Referenced by cliklike::clik_likeinit(), cmblikes::cmblikes_readini(), and cmblikelihoods::twmaplikelihood_readparams().
cl_norm
real(mcp), parameter cosmologytypes::cl_norm = 1e-10_mcp
Referenced by cosmologyparameterizations::tp_calcderivedparams().
cl_phi
integer, parameter cosmologytypes::cl_phi =4
Referenced by calculator_camb::cambcalc_setpowersfromcamb(), cmblikes::cmblikes_readini(), and initialize_cmbsettings().
cl_t
integer, parameter cosmologytypes::cl_t = 1
Referenced by cliklike::clik_likeinit(), cmblikes::cmblikes_readini(), cmblikelihoods::readsztemplate(), and cmblikelihoods::twmaplikelihood_readparams().
cmb_cl_fields
character(len=4), parameter cosmologytypes::cmb_cl_fields = 'TEBP'
Referenced by cmblikes::cmblikes_readini(), tcosmotheorysettings_initforlikelihoods(), cmblikes::typeindex(), and cosmotheory::writetextcls().
cosmosettings
type(tcosmotheorysettings), target, save cosmologytypes::cosmosettings
Referenced by calculator_camb::cambcalc_cmbtocamb(), calculator_camb::cambcalc_getnewpowerdata(), calculator_camb::cambcalc_gettheoryforimportance(), calculator_camb::cambcalc_setpowersfromcamb(), calclike_cosmology::cosmo_calculaterequiredtheorychanges(), calclike_cosmology::cosmo_updatetheoryforlikelihoods(), initialize_pksettings(), calculator_pico::pico_cmbtocamb(), calculator_pico::pico_getnewpowerdata(), calculator_pico::pico_getoutputarray(), datalikelihoodlist::setdatalikelihoods(), cosmologyparameterizations::setforh(), cosmologyconfig::tcosmologyconfig_initforlikelihoods(), cosmologyconfig::tcosmologyconfig_newtheory(), cosmologyconfig::tcosmologyconfig_readparams(), cosmotheory::tcosmotheorypredictions_readtheory(), cosmotheory::tcosmotheorypredictions_writetheory(), cosmologyparameterizations::tp_calcderivedparams(), cosmologyparameterizations::tp_init(), and cosmotheory::writetextcls().
derived_age
integer, parameter cosmologytypes::derived_age =1
derived_dastar
integer, parameter cosmologytypes::derived_dastar = 5
derived_kd
integer, parameter cosmologytypes::derived_kd =8
derived_keq
integer, parameter cosmologytypes::derived_keq =11
derived_rdrag
integer, parameter cosmologytypes::derived_rdrag =7
Referenced by bao::get_rs_drag().
derived_rstar
integer, parameter cosmologytypes::derived_rstar =3
derived_theta_rs_eq
integer, parameter cosmologytypes::derived_theta_rs_eq = 13
derived_thetad
integer, parameter cosmologytypes::derived_thetad =9
derived_thetaeq
integer, parameter cosmologytypes::derived_thetaeq =12
derived_thetastar
integer, parameter cosmologytypes::derived_thetastar =4
derived_zdrag
integer, parameter cosmologytypes::derived_zdrag =6
derived_zeq
integer, parameter cosmologytypes::derived_zeq =10
derived_zstar
integer, parameter cosmologytypes::derived_zstar =2
index_initpower
integer cosmologytypes::index_initpower
Referenced by calclike_cosmology::cosmo_calculaterequiredtheorychanges(), cosmologyparameterizations::setfast(), and tcosmologyparameterization_setnumbers().
last_power_index
integer, parameter cosmologytypes::last_power_index = Aphiphi_index
Referenced by cosmologyparameterizations::tp_init().
max_derived_parameters
integer, parameter cosmologytypes::max_derived_parameters = 326
Referenced by calculator_camb::cambcalc_setderived().
max_inipower_params
integer, parameter cosmologytypes::max_inipower_params = 10
Referenced by tcosmologyparameterization_setnumbers().
neutrino_hierarchy_degenerate
integer, parameter cosmologytypes::neutrino_hierarchy_degenerate = 3
Referenced by tcosmotheorysettings_readparams().
neutrino_hierarchy_inverted
integer, parameter cosmologytypes::neutrino_hierarchy_inverted = 2
neutrino_hierarchy_normal
integer, parameter cosmologytypes::neutrino_hierarchy_normal = 1
Referenced by tcosmotheorysettings_readparams().
neutrino_types
character(len=ini_enumeration_len), dimension(3), parameter cosmologytypes::neutrino_types = [character(Ini_Enumeration_Len)::'normal','inverted','degenerate']
Referenced by tcosmotheorysettings_readparams().
nrun_index
integer, parameter cosmologytypes::nrun_index =3
Referenced by cosmologyparameterizations::tp_calcderivedparams().
nrunrun_index
integer, parameter cosmologytypes::nrunrun_index =4
Referenced by cosmologyparameterizations::tp_calcderivedparams().
ns_index
integer, parameter cosmologytypes::ns_index =2
Referenced by szcounts::szcc_cash(), and cosmologyparameterizations::tp_calcderivedparams().
nt_index
integer, parameter cosmologytypes::nt_index = 6
ntrun_index
integer, parameter cosmologytypes::ntrun_index = 7
num_hard
integer cosmologytypes::num_hard
Referenced by calclike_cosmology::cosmo_calculaterequiredtheorychanges(), calclike_cosmology::cosmo_gettheoryforlike(), tcosmologyparameterization_setnumbers(), and cosmologyparameterizations::tp_paramarraytotheoryparams().
num_initpower
integer cosmologytypes::num_initpower
Referenced by calclike_cosmology::cosmo_calculaterequiredtheorychanges(), cosmologyparameterizations::setfast(), and tcosmologyparameterization_setnumbers().