cosmomc_bde_v3p1: arrayutils Module Reference
arrayutils Module Reference
Functions/Subroutines
integer function indexof (aval, arr, n)
integer function maxindex (arr, n)
integer function minindex (arr, n)
Function/Subroutine Documentation
indexof()
integer function arrayutils::indexof (integer, intent(in) aval, integer, dimension(n), intent(in) arr, integer, intent(in) n)
Referenced by baseparameters::orderindices(), and mcsamples::pca().
maxindex()
integer function arrayutils::maxindex (real, dimension(n), intent(in) arr, integer, intent(in) n)
Referenced by mcsamples::mostcorrelated2d().
minindex()
integer function arrayutils::minindex (real, dimension(n), intent(in) arr, integer, intent(in) n)