cosmomc_bde_v3p1: quint Module Reference
quint Module Reference
Functions/Subroutines
subroutine bde_nxyl
subroutine bde_xylata (a, x, y, l)
subroutine bde_wde0 (P, wBDE0)
subroutine bde_h0 (P, H0)
real(dl) function bde_omegade0 (x, y, l)
real(dl) function vofphi (phi, deriv)
subroutine bde_background
subroutine quint_valsata (a, aphi, aphidot)
Variables
integer, parameter numpoints = 10000
integer, parameter numpointsex =NumPoints+2
real(dl), dimension(numpointsex) phi_a
real(dl), dimension(numpointsex) phidot_a
real(dl), dimension(numpointsex) ddphi_a
real(dl), dimension(numpointsex) ddphidot_a
real(dl) initial_phi
real(dl) dn
real(dl), dimension(numpointsex) abde
real(dl), dimension(numpointsex) nbde
real(dl), dimension(numpointsex) xbde
real(dl), dimension(numpointsex) ybde
real(dl), dimension(numpointsex) lbde
real(dl), dimension(numpointsex) ddxbde
real(dl), dimension(numpointsex) ddybde
real(dl), dimension(numpointsex) ddlbde
real(dl) adot
Function/Subroutine Documentation
bde_background()
subroutine quint::bde_background ()
References abde, modelparams::alphabde, ddphi_a, ddphidot_a, lbde, nbde, numpointsex, phi_a, phidot_a, spline(), vofphi(), xbde, and ybde.
Referenced by init_background().
bde_h0()
subroutine quint::bde_h0 (type(cambparams), intent(in) P, real(dl), intent(out) H0)
References bde_xylata(), constants::c, constants::c8pig_evm2, and constants::ev2tompcm2.
bde_nxyl()
subroutine quint::bde_nxyl ()
References abde, ddlbde, ddxbde, ddybde, lbde, nbde, numpoints, numpointsex, spline(), xbde, and ybde.
bde_omegade0()
real(dl) function quint::bde_omegade0 (real(dl), intent(in) x, real(dl), intent(in) y, real(dl), intent(in) l)
References bde_xylata().
bde_wde0()
subroutine quint::bde_wde0 (type(cambparams), intent(in) P, real(dl), intent(out) wBDE0)
References bde_xylata().
bde_xylata()
subroutine quint::bde_xylata (real(dl) a, real(dl) x, real(dl) y, real(dl) l)
References modelparams::ac, ddlbde, ddxbde, ddybde, dn, lbde, numpoints, xbde, and ybde.
Referenced by bde_h0(), bde_omegade0(), bde_wde0(), and cosmologyparameterizations::tp_paramarraytotheoryparams().
quint_valsata()
subroutine quint::quint_valsata (real(dl) a, real(dl) aphi, real(dl) aphidot)
References modelparams::ac, ddphi_a, ddphidot_a, dn, phi_a, and phidot_a.
Referenced by dtauda().
vofphi()
real(dl) function quint::vofphi (real(dl) phi, integer deriv)
References modelparams::alphabde, and modelparams::norm_pot.
Referenced by bde_background(), and dtauda().
Variable Documentation
abde
real(dl), dimension(numpointsex) quint::abde
Referenced by bde_background(), bde_nxyl(), and cosmologyparameterizations::cosmomc_nxyl().
adot
real(dl) quint::adot
ddlbde
real(dl), dimension(numpointsex) quint::ddlbde
Referenced by bde_nxyl(), bde_xylata(), and cosmologyparameterizations::cosmomc_nxyl().
ddphi_a
real(dl), dimension(numpointsex) quint::ddphi_a
Referenced by bde_background(), and quint_valsata().
ddphidot_a
real(dl), dimension(numpointsex) quint::ddphidot_a
Referenced by bde_background(), and quint_valsata().
ddxbde
real(dl), dimension(numpointsex) quint::ddxbde
Referenced by bde_nxyl(), bde_xylata(), and cosmologyparameterizations::cosmomc_nxyl().
ddybde
real(dl), dimension(numpointsex) quint::ddybde
Referenced by bde_nxyl(), bde_xylata(), and cosmologyparameterizations::cosmomc_nxyl().
dn
real(dl) quint::dn
Referenced by bde_xylata(), cosmologyparameterizations::cosmomc_nxyl(), and quint_valsata().
initial_phi
real(dl) quint::initial_phi
lbde
real(dl), dimension(numpointsex) quint::lbde
Referenced by bde_background(), bde_nxyl(), bde_xylata(), and cosmologyparameterizations::cosmomc_nxyl().
nbde
real(dl), dimension(numpointsex) quint::nbde
Referenced by bde_background(), bde_nxyl(), and cosmologyparameterizations::cosmomc_nxyl().
numpoints
integer parameter quint::numpoints = 10000
Referenced by bde_nxyl(), bde_xylata(), and cosmologyparameterizations::cosmomc_nxyl().
numpointsex
integer parameter quint::numpointsex =NumPoints+2
Referenced by bde_background(), bde_nxyl(), and cosmologyparameterizations::cosmomc_nxyl().
phi_a
real(dl), dimension(numpointsex) quint::phi_a
Referenced by bde_background(), and quint_valsata().
phidot_a
real(dl), dimension(numpointsex) quint::phidot_a
Referenced by bde_background(), and quint_valsata().
xbde
real(dl), dimension(numpointsex) quint::xbde
Referenced by bde_background(), bde_nxyl(), bde_xylata(), cosmologyparameterizations::cosmomc_nxyl(), and cosmologyparameterizations::tp_paramarraytotheoryparams().
ybde
real(dl), dimension(numpointsex) quint::ybde
Referenced by bde_background(), bde_nxyl(), bde_xylata(), cosmologyparameterizations::cosmomc_nxyl(), and cosmologyparameterizations::tp_paramarraytotheoryparams().