cosmomc_bde_v3p1: getdist.kde_bandwidth Namespace Reference
getdist.kde_bandwidth Namespace Reference
Classes
class KernelOptimizer2D
Functions
def _bandwidth_fixed_point (h, N, I, logI, a2)
def bin_samples (samples, range_min=None, range_max=None, nbins=2046, edge_fac=0.1)
def gaussian_kde_bandwidth (samples, Neff=None, range_min=None, range_max=None, nbins=2046)
def gaussian_kde_bandwidth_binned (data, Neff, a=None)
Variables
rootpi = np.sqrt(np.pi)
int pisquared = np.pi ** 2
int _kde_lmax_bandwidth = 7
_kde_consts_1d
K
Kodd = np.array([1] + [np.prod(np.arange(1, 2 * j, 2)) / 2. ** (j + 1) / np.sqrt(np.pi) for j in range(1, 9)])
Function Documentation
_bandwidth_fixed_point()
def getdist.kde_bandwidth._bandwidth_fixed_point (h, N, I, logI, a2) private
References copyGridFiles.zip.
bin_samples()
def getdist.kde_bandwidth.bin_samples (samples, range_min = None, range_max = None, nbins = 2046, edge_fac = 0.1)
Referenced by getdist.kde_bandwidth.gaussian_kde_bandwidth().
gaussian_kde_bandwidth()
def getdist.kde_bandwidth.gaussian_kde_bandwidth (samples, Neff = None, range_min = None, range_max = None, nbins = 2046)
References getdist.kde_bandwidth.bin_samples(), and getdist.kde_bandwidth.gaussian_kde_bandwidth_binned().
gaussian_kde_bandwidth_binned()
def getdist.kde_bandwidth.gaussian_kde_bandwidth_binned (data, Neff, a = None)
 Return optimal standard kernel bandwidth assuming data is binned from Neff independent samples
 Return value is the bandwidth in units of the range of data (i.e. multiply by max(data)-min(data))
 Uses Improved Sheather-Jones algorithm from
 Kernel density estimation via diffusion: Z. I. Botev, J. F. Grotowski, and D. P. Kroese (2010)
 Annals of Statistics, Volume 38, Number 5, pages 2916-2957.
 http://arxiv.org/abs/1011.2602
Referenced by getdist.kde_bandwidth.gaussian_kde_bandwidth().
Variable Documentation
_kde_consts_1d
getdist.kde_bandwidth._kde_consts_1d private
Initial value:
 =  np.array([(1 + 0.5 ** (j + 0.5)) / 3 * np.prod(np.arange(1, 2 * j, 2)) / (rootpi / np.sqrt(2.))
                            for j in range(_kde_lmax_bandwidth - 1, 1, -1)])
_kde_lmax_bandwidth
int getdist.kde_bandwidth._kde_lmax_bandwidth = 7 private
K
getdist.kde_bandwidth.K
Initial value:
 =  np.array(
     [1 / np.sqrt(2 * np.pi)] + [(-1) ** j * np.prod(np.arange(1, 2 * j, 2)) / np.sqrt(2 * np.pi) for j in range(1, 5)])
Kodd
getdist.kde_bandwidth.Kodd = np.array([1] + [np.prod(np.arange(1, 2 * j, 2)) / 2. ** (j + 1) / np.sqrt(np.pi) for j in range(1, 9)])
pisquared
int getdist.kde_bandwidth.pisquared = np.pi ** 2
rootpi
getdist.kde_bandwidth.rootpi = np.sqrt(np.pi)