cosmomc_bde_v3p1: cambmain Module Reference
cambmain Module Reference
Data Types
type integrationvars
Functions/Subroutines
subroutine, public cmbmain
subroutine, public cltransfertocl (CTransS, CTransT, CTransV)
subroutine calclimberscalcls (CTrans)
subroutine getlimbertransfers
subroutine sourcetotransfers (q_ix)
subroutine inittransfer
real(dl) function, public gettaustart (q)
subroutine dosourcek (EV, q_ix)
subroutine getsourcemem
subroutine freesourcemem
subroutine, public initvars
subroutine setkvaluesforsources
subroutine setclosedkvaluesfromarr (R, forInt)
subroutine evolved (dum, num, tau, y, yprime)
subroutine calcscalarsources (EV, taustart)
subroutine calctensorsources (EV, taustart)
subroutine calcvectorsources (EV, taustart)
subroutine transferout
subroutine gettransfer (EV, tau)
subroutine makenonlinearsources
subroutine initsourceinterpolation
subroutine setkvaluesforint
subroutine interpolatesources (IV)
subroutine integrationvars_init (IV)
subroutine dosourceintegration (IV)
logical function uselimber (l, k)
subroutine doflatintegration (IV, llmax)
subroutine integratesourcesbessels (IV, j, l, nu)
subroutine dorangeint (IV, chi, chiDisp, nstart, nend, dtau, nu, l, y1, y2, out)
subroutine dorangeinttensor (IV, chi, chiDisp, nstart, nend, dtau, nu, l, y1, y2, out)
subroutine getinitpowerarrayvec (pows, ks, numks, pix)
subroutine getinitpowerarraytens (pows, ks, numks, pix)
subroutine calcscalcls (CTrans)
subroutine calcscalcls2 (CTrans)
subroutine calctenscls (CTrans, GetInitPowers)
subroutine calcveccls (CTrans, GetInitPowers)
subroutine interpolatecls (CTransS, CTransT, CTransV)
Variables
logical wantlatetime = .false.
logical exactclosedsum
integer sourcenum
real(dl), dimension(0:max_transfer_redshifts) tautf
real(dl), dimension(:,:,:), allocatable src
real(dl), dimension(:,:,:), allocatable ddsrc
real(dl), dimension(:,:,:), allocatable icl_scalar
real(dl), dimension(:,:,:), allocatable icl_vector
real(dl), dimension(:,:,:), allocatable icl_tensor
real(dl), dimension(:,:,:,:), allocatable icl_array
type(regions) evolve_q
real(dl), parameter qmin0 =0.1_dl
real(dl) dtaurec_q
real(dl) qmin
real(dl) qmax
real(dl) max_etak_tensor
real(dl) max_etak_vector
real(dl) max_etak_scalar
integer maximum_l
real(dl) maximum_qeta = 3000._dl
integer l_smooth_sample = 3000
real(dl) aid
real(dl) dmid
real(dl), public alens = 1._dl
type(cltransferdata), pointer thisct
Function/Subroutine Documentation
calclimberscalcls()
subroutine cambmain::calclimberscalcls (type(cltransferdata) CTrans) private
References modeldata::c_phi, modelparams::cp, modeldata::has_cl_2d_array, icl_array, icl_scalar, modelparams::limber_phiphi, modelparams::num_redshiftwindows, modelparams::outputdenominator, and initialpower::scalarpower().
Referenced by cltransfertocl().
calcscalarsources()
subroutine cambmain::calcscalarsources (type(evolutionvars) EV, real(dl) taustart)
References modelparams::ac, modelparams::accuracyboost, aid, modelparams::alphabde, modelparams::cp, modelparams::debugevolution, gaugeinterface::derivs(), dmid, dverk(), evolved(), modelparams::fixq, gaugeinterface::gaugeinterface_evolvescal(), errors::global_error_flag, modelparams::grhob, modelparams::grhoc, modelparams::grhodgc, modelparams::grhog, modelparams::grhornomass, gaugeinterface::initial(), modelparams::lambdac, max_etak_scalar, transfer::mt, gaugeinterface::output(), gaugeinterface::outtransf(), src, modelparams::taurend, tautf, modelparams::timeofz(), modelparams::timesteps, modelparams::tol, wantlatetime, and modelparams::wdgc.
Referenced by dosourcek().
calcscalcls()
subroutine cambmain::calcscalcls (type(cltransferdata) CTrans) private
References alens, modeldata::c_cross, modeldata::c_e, modeldata::c_phi, modeldata::c_phie, modeldata::c_phitemp, modeldata::c_temp, modelparams::cp, errors::global_error_flag, modeldata::has_cl_2d_array, icl_array, icl_scalar, modelparams::limber_phiphi, modelparams::num_redshiftwindows, modelparams::outputdenominator, and initialpower::scalarpower().
Referenced by cltransfertocl().
calcscalcls2()
subroutine cambmain::calcscalcls2 (type(cltransferdata) CTrans)
References modeldata::c_cross, modeldata::c_e, modeldata::c_last, modeldata::c_temp, modelparams::cp, errors::global_error_flag, modelparams::outputdenominator, and initialpower::scalarpower().
calctenscls()
subroutine cambmain::calctenscls (type(cltransferdata) CTrans, external GetInitPowers) private
References modelparams::cp, modeldata::ct_b, modeldata::ct_cross, modeldata::ct_e, modeldata::ct_temp, icl_tensor, and modelparams::outputdenominator.
Referenced by cltransfertocl().
calctensorsources()
subroutine cambmain::calctensorsources (type(evolutionvars) EV, real(dl) taustart)
References modelparams::accuracyboost, modeldata::ct_b, modeldata::ct_e, modeldata::ct_temp, gaugeinterface::gaugeinterface_evolvetens(), gaugeinterface::initialt(), max_etak_tensor, gaugeinterface::outputt(), sourcenum, src, modelparams::timesteps, and modelparams::tol.
Referenced by dosourcek().
calcveccls()
subroutine cambmain::calcveccls (type(cltransferdata) CTrans, external GetInitPowers) private
References modelparams::cp, modeldata::ct_b, modeldata::ct_cross, modeldata::ct_e, modeldata::ct_temp, icl_vector, and modelparams::outputdenominator.
Referenced by cltransfertocl().
calcvectorsources()
subroutine cambmain::calcvectorsources (type(evolutionvars) EV, real(dl) taustart) private
References modelparams::accuracyboost, modeldata::ct_b, modeldata::ct_e, modeldata::ct_temp, gaugeinterface::derivsv(), dverk(), gaugeinterface::initialv(), max_etak_vector, gaugeinterface::outputv(), sourcenum, src, modelparams::timesteps, and modelparams::tol.
Referenced by dosourcek().
cltransfertocl()
subroutine, public cambmain::cltransfertocl (type(cltransferdata) CTransS, type(cltransferdata) CTransT, type(cltransferdata) CTransV)
References modeldata::c_last, modeldata::c_temp, calclimberscalcls(), calcscalcls(), calctenscls(), calcveccls(), modelparams::cp, modeldata::ct_cross, modeldata::ct_temp, modelparams::debugmsgs, modelparams::feedbacklevel, getinitpowerarraytens(), getinitpowerarrayvec(), errors::global_error_flag, modeldata::has_cl_2d_array, icl_array, icl_scalar, icl_tensor, icl_vector, modeldata::init_cls(), interpolatecls(), lvalues::lsamp, and modeldata::normalizeclsatl().
Referenced by camb::camb_transferstopowers(), and cmbmain().
cmbmain()
subroutine, public cambmain::cmbmain ()
References cltransfertocl(), modelparams::cp, modeldata::ctransscal, modeldata::ctranstens, modeldata::ctransvec, modelparams::debugmsgs, dosourcek(), evolve_q, exactclosedsum, modelparams::feedbacklevel, freesourcemem(), getlimbertransfers(), getsourcemem(), modelparams::gettesttime(), errors::global_error_flag, initialpower::initializepowers(), lvalues::initlval(), initsourceinterpolation(), spherbessels::initspherbessels(), inittransfer(), initvars(), lvalues::lsamp, makenonlinearsources(), modelparams::max_bessels_etak, modelparams::max_bessels_l_index, maximum_l, maximum_qeta, transfer::mt, modelparams::nonlinear_both, modelparams::nonlinear_lens, modelparams::num_redshiftwindows, modelparams::scale, setkvaluesforint(), setkvaluesforsources(), sourcenum, sourcetotransfers(), thisct, transfer::transfer_get_sigmas(), transferout(), and wantlatetime.
Referenced by camb::camb_getresults().
doflatintegration()
subroutine cambmain::doflatintegration (type(integrationvars) IV, integer llmax) private
References modelparams::accuracyboost, spherbessels::ajl, spherbessels::ajlpr, spherbessels::bessranges, modelparams::cp, modelparams::do_bispectrum, modelparams::full_bessel_integration, modelparams::highaccuracydefault, lvalues::lsamp, modelparams::max_bessels_l_index, thisct, modelparams::timesteps, uselimber(), spherbessels::xlimfrac, and spherbessels::xlimmin.
Referenced by dosourceintegration().
dorangeint()
subroutine cambmain::dorangeint (type(integrationvars) IV, real(dl) chi, real(dl) chiDisp, integer nstart, integer nend, real(dl) dtau, real(dl) nu, integer l, real(dl) y1, real(dl) y2, real(dl), dimension(sourcenum) out)
References modelparams::accuracyboost, modelparams::cp, dtaurec_q, modelparams::highaccuracydefault, modelparams::rofchi(), modelparams::scale, modelparams::timesteps, uselimber(), spherbessels::uspherbesselwithderiv(), and wantlatetime.
Referenced by integratesourcesbessels().
dorangeinttensor()
subroutine cambmain::dorangeinttensor (type(integrationvars), target IV, real(dl) chi, real(dl) chiDisp, integer nstart, integer nend, real(dl) dtau, real(dl) nu, integer l, real(dl) y1, real(dl) y2, real(dl), dimension(sourcenum) out)
References modelparams::accuracyboost, modelparams::cp, modelparams::rofchi(), modelparams::scale, modelparams::timesteps, and spherbessels::uspherbesselwithderiv().
Referenced by integratesourcesbessels().
dosourceintegration()
subroutine cambmain::dosourceintegration (type(integrationvars) IV) private
References modelparams::cp, doflatintegration(), integratesourcesbessels(), lvalues::lsamp, and modelparams::rofchi().
Referenced by sourcetotransfers().
dosourcek()
subroutine cambmain::dosourcek (type(evolutionvars) EV, integer q_ix) private
References calcscalarsources(), calctensorsources(), calcvectorsources(), modelparams::cp, evolve_q, modelparams::fixq, gaugeinterface::getnumeqns(), gettaustart(), and errors::global_error_flag.
Referenced by cmbmain().
evolved()
subroutine cambmain::evolved (real dum, integer num, real(dl) tau, real(dl), dimension(num) y, real(dl), dimension(num) yprime) private
References aid, dmid, modelparams::grhob, and modelparams::grhoc.
Referenced by calcscalarsources().
freesourcemem()
subroutine cambmain::freesourcemem () private
References ddsrc, evolve_q, and src.
Referenced by cmbmain().
getinitpowerarraytens()
subroutine cambmain::getinitpowerarraytens (real(dl), dimension(numks) pows, real(dl), dimension(numks) ks, integer, intent(in) numks, integer, intent(in) pix) private
References errors::global_error_flag, and initialpower::tensorpower().
Referenced by cltransfertocl().
getinitpowerarrayvec()
subroutine cambmain::getinitpowerarrayvec (real(dl), dimension(numks) pows, real(dl), dimension(numks) ks, integer, intent(in) numks, integer, intent(in) pix)
References errors::global_error_flag, and initialpower::scalarpower().
Referenced by cltransfertocl().
getlimbertransfers()
subroutine cambmain::getlimbertransfers () private
References modelparams::accuracyboost, modelparams::cp, ddsrc, evolve_q, modelparams::feedbacklevel, modeldata::init_limber(), modelparams::limber_phiphi, lvalues::lvalues_indexof(), modelparams::max_bessels_etak, modelparams::max_bessels_l_index, modelparams::num_redshiftwindows, qmax, src, modelparams::tau_maxvis, thisct, and modelparams::timesteps.
Referenced by cmbmain().
getsourcemem()
subroutine cambmain::getsourcemem () private
References modeldata::c_cross, modeldata::c_last, modeldata::c_phie, modelparams::cp, ddsrc, evolve_q, modelparams::num_extra_redshiftwindows, modelparams::num_redshiftwindows, sourcenum, src, modelparams::timesteps, and wantlatetime.
Referenced by cmbmain().
gettaustart()
real(dl) function, public cambmain::gettaustart (real(dl), intent(in) q)
References modelparams::adotrad, modelparams::cp, modelparams::fixq, and modelparams::nu_masses.
Referenced by dosourcek(), handles::getoutputevolutionfork(), initvars(), and transferout().
gettransfer()
subroutine cambmain::gettransfer (type(evolutionvars) EV, real(dl) tau) private
References modelparams::accuracyboost, modelparams::cp, gaugeinterface::gaugeinterface_evolvescal(), errors::global_error_flag, gaugeinterface::initial(), transfer::mt, gaugeinterface::outtransf(), tautf, and modelparams::tol.
Referenced by transferout().
initsourceinterpolation()
subroutine cambmain::initsourceinterpolation ()
References ddsrc, evolve_q, sourcenum, modelparams::spl_large, spline(), src, and modelparams::timesteps.
Referenced by cmbmain().
inittransfer()
subroutine cambmain::inittransfer () private
References modelparams::accuracyboost, modelparams::cp, evolve_q, modelparams::highaccuracydefault, transfer::mt, qmin, modelparams::taurst, and transfer::transfer_allocate().
Referenced by cmbmain().
initvars()
subroutine, public cambmain::initvars ()
References modelparams::accuracyboost, modelparams::cp, modelparams::debugmsgs, modelparams::dtaurec, dtaurec_q, modelparams::feedbacklevel, gaugeinterface::gaugeinterface_init(), gettaustart(), errors::global_error_flag, thermodata::inithermo(), max_etak_scalar, max_etak_tensor, max_etak_vector, maximum_qeta, qmax, qmin, qmin0, modelparams::tau_maxvis, tautf, and modelparams::timeofz().
Referenced by calculator_camb::cambcalc_setbackgroundtheorydata(), handles::cambdata_calcbackgroundtheory(), and cmbmain().
integratesourcesbessels()
subroutine cambmain::integratesourcesbessels (type(integrationvars) IV, integer j, integer l, real(dl) nu) private
References modelparams::accuracyboost, modelparams::cp, dorangeint(), dorangeinttensor(), modelparams::highaccuracydefault, modelparams::invsinfunc(), lvalues::lsamp, thisct, modelparams::timesteps, uselimber(), and spherbessels::uspherbesselwithderiv().
Referenced by dosourceintegration().
integrationvars_init()
subroutine cambmain::integrationvars_init (type(integrationvars), intent(inout) IV) private
References sourcenum, and modelparams::timesteps.
Referenced by sourcetotransfers().
interpolatecls()
subroutine cambmain::interpolatecls (type(cltransferdata) CTransS, type(cltransferdata) CTransT, type(cltransferdata) CTransV) private
References modeldata::c_last, modeldata::c_temp, modeldata::cl_scalar, modeldata::cl_scalar_array, modeldata::cl_tensor, modeldata::cl_vector, modelparams::cp, modeldata::ct_cross, modeldata::ct_temp, modeldata::ctransscal, modeldata::has_cl_2d_array, icl_array, icl_scalar, icl_tensor, icl_vector, lvalues::interpolateclarr(), lvalues::interpolateclarrtemplated(), modelparams::lmin, and modelparams::num_redshiftwindows.
Referenced by cltransfertocl().
interpolatesources()
subroutine cambmain::interpolatesources (type(integrationvars) IV) private
References modelparams::cp, ddsrc, modelparams::debugevolution, evolve_q, max_etak_scalar, max_etak_tensor, max_etak_vector, sourcenum, modelparams::spl_large, spline(), src, modelparams::timesteps, and wantlatetime.
Referenced by sourcetotransfers().
makenonlinearsources()
subroutine cambmain::makenonlinearsources () private
References evolve_q, transfer::matterpowerdata_free(), nonlinear::min_kh_nonlinear, transfer::mt, nonlinear::nonlinear_getnonlinratios(), sourcenum, modelparams::spl_large, spline(), src, tautf, modelparams::timesteps, and transfer::transfer_getmatterpowerdata().
Referenced by cmbmain().
setclosedkvaluesfromarr()
subroutine cambmain::setclosedkvaluesfromarr (type(regions) R, logical, intent(in) forInt) private
References modelparams::cp.
Referenced by setkvaluesforint(), and setkvaluesforsources().
setkvaluesforint()
subroutine cambmain::setkvaluesforint () private
References modelparams::accuracyboost, modelparams::cp, modelparams::do_bispectrum, exactclosedsum, modelparams::hard_bispectrum, modelparams::highaccuracydefault, modeldata::init_cltransfer(), modelparams::max_bessels_etak, maximum_l, qmax, qmin, setclosedkvaluesfromarr(), and thisct.
Referenced by cmbmain().
setkvaluesforsources()
subroutine cambmain::setkvaluesforsources ()
References modelparams::accuracyboost, modelparams::cp, evolve_q, modelparams::highaccuracydefault, l_smooth_sample, maximum_l, qmax, qmin, setclosedkvaluesfromarr(), and modelparams::taurst.
Referenced by cmbmain().
sourcetotransfers()
subroutine cambmain::sourcetotransfers (integer q_ix) private
References modelparams::cp, dosourceintegration(), integrationvars_init(), interpolatesources(), sourcenum, thisct, and modelparams::timesteps.
Referenced by cmbmain().
transferout()
subroutine cambmain::transferout () private
References modelparams::debugmsgs, evolve_q, modelparams::feedbacklevel, gaugeinterface::getnumeqns(), gettaustart(), gettransfer(), and transfer::mt.
Referenced by cmbmain().
uselimber()
logical function cambmain::uselimber (integer l, real(dl) k) private
References modelparams::accuracyboost.
Referenced by doflatintegration(), dorangeint(), and integratesourcesbessels().
Variable Documentation
aid
real(dl) cambmain::aid private
Referenced by calcscalarsources(), and evolved().
alens
real(dl), public cambmain::alens = 1._dl
Referenced by calcscalcls(), and calculator_camb::cambcalc_cmbtocamb().
ddsrc
real(dl), dimension(:,:,:), allocatable cambmain::ddsrc private
Referenced by freesourcemem(), getlimbertransfers(), getsourcemem(), initsourceinterpolation(), and interpolatesources().
dmid
real(dl) cambmain::dmid private
Referenced by calcscalarsources(), and evolved().
dtaurec_q
real(dl) cambmain::dtaurec_q private
Referenced by dorangeint(), and initvars().
evolve_q
type(regions) cambmain::evolve_q private
Referenced by cmbmain(), dosourcek(), freesourcemem(), getlimbertransfers(), getsourcemem(), initsourceinterpolation(), inittransfer(), interpolatesources(), makenonlinearsources(), setkvaluesforsources(), and transferout().
exactclosedsum
logical cambmain::exactclosedsum private
Referenced by cmbmain(), and setkvaluesforint().
icl_array
real(dl), dimension(:,:,:,:), allocatable cambmain::icl_array private
Referenced by calclimberscalcls(), calcscalcls(), cltransfertocl(), and interpolatecls().
icl_scalar
real(dl), dimension(:,:,:), allocatable cambmain::icl_scalar private
Referenced by calclimberscalcls(), calcscalcls(), cltransfertocl(), and interpolatecls().
icl_tensor
real(dl), dimension(:,:,:), allocatable cambmain::icl_tensor private
Referenced by calctenscls(), cltransfertocl(), and interpolatecls().
icl_vector
real(dl), dimension(:,:,:), allocatable cambmain::icl_vector private
Referenced by calcveccls(), cltransfertocl(), and interpolatecls().
l_smooth_sample
integer cambmain::l_smooth_sample = 3000 private
Referenced by setkvaluesforsources().
max_etak_scalar
real(dl) cambmain::max_etak_scalar private
Referenced by calcscalarsources(), initvars(), and interpolatesources().
max_etak_tensor
real(dl) cambmain::max_etak_tensor private
Referenced by calctensorsources(), initvars(), and interpolatesources().
max_etak_vector
real(dl) cambmain::max_etak_vector private
Referenced by calcvectorsources(), initvars(), and interpolatesources().
maximum_l
integer cambmain::maximum_l private
Referenced by cmbmain(), setkvaluesforint(), and setkvaluesforsources().
maximum_qeta
real(dl) cambmain::maximum_qeta = 3000._dl private
Referenced by cmbmain(), and initvars().
qmax
real(dl) cambmain::qmax private
Referenced by getlimbertransfers(), initvars(), setkvaluesforint(), and setkvaluesforsources().
qmin
real(dl) cambmain::qmin private
Referenced by inittransfer(), initvars(), setkvaluesforint(), and setkvaluesforsources().
qmin0
real(dl), parameter cambmain::qmin0 =0.1_dl private
Referenced by initvars().
sourcenum
integer cambmain::sourcenum private
Referenced by calctensorsources(), calcvectorsources(), cmbmain(), getsourcemem(), initsourceinterpolation(), integrationvars_init(), interpolatesources(), makenonlinearsources(), and sourcetotransfers().
src
real(dl), dimension(:,:,:), allocatable cambmain::src private
Referenced by calcscalarsources(), calctensorsources(), calcvectorsources(), freesourcemem(), getlimbertransfers(), getsourcemem(), initsourceinterpolation(), interpolatesources(), and makenonlinearsources().
tautf
real(dl), dimension(0:max_transfer_redshifts) cambmain::tautf private
Referenced by calcscalarsources(), gettransfer(), initvars(), and makenonlinearsources().
thisct
type(cltransferdata), pointer cambmain::thisct private
Referenced by cmbmain(), doflatintegration(), getlimbertransfers(), integratesourcesbessels(), setkvaluesforint(), and sourcetotransfers().
wantlatetime
logical cambmain::wantlatetime = .false. private
Referenced by calcscalarsources(), cmbmain(), dorangeint(), getsourcemem(), and interpolatesources().