cosmomc_bde_v3p1: GetDist Namespace Reference
GetDist Namespace Reference
Functions
def runScript (fname)
def doError (msg)
def main (args)
Variables
parser = argparse.ArgumentParser(description='GetDist sample analyser')
nargs
help
action
version
args = parser.parse_args()
content = io.open(getdist.distparam_template).read()
analysis = io.open(getdist.default_getdist_settings).read()
Function Documentation
doError()
def GetDist.doError (msg)
Referenced by main().
main()
def GetDist.main (args)
References doError(), CAMB_test_files.int, and runScript().
runScript()
def GetDist.runScript (fname)
Referenced by main().
Variable Documentation
action
GetDist.action
analysis
GetDist.analysis = io.open(getdist.default_getdist_settings).read()
args
GetDist.args = parser.parse_args()
content
GetDist.content = io.open(getdist.distparam_template).read()
help
GetDist.help
nargs
GetDist.nargs
parser
GetDist.parser = argparse.ArgumentParser(description='GetDist sample analyser')
version
GetDist.version