cosmomc_bde_v3p1: cmblikelihoods Module Reference
cmblikelihoods Module Reference
Data Types
type tcmbszlikelihood
type twmaplikelihood
Functions/Subroutines
subroutine, public cmblikelihood_add (LikeList, Ini)
subroutine tcmbszlikelihood_readparams (this, Ini)
subroutine readsztemplate (this, aname, ascale)
subroutine twmaplikelihood_readparams (this, Ini)
real(mcp) function twmaplikelihood_loglike (this, CMB, Theory, DataParams)
Function/Subroutine Documentation
cmblikelihood_add()
subroutine, public cmblikelihoods::cmblikelihood_add (class(tlikelihoodlist) LikeList, class(tsettingini) Ini)
References cliklike::clik_readparams(), and cliklike::use_clik.
Referenced by cmblikelihoods::twmaplikelihood::loglike(), and datalikelihoodlist::setdatalikelihoods().
readsztemplate()
subroutine cmblikelihoods::readsztemplate (class(tcmbszlikelihood) this, character(len=*), intent(in) aname, real(mcp), intent(in) ascale) private
References cosmologytypes::cl_t.
tcmbszlikelihood_readparams()
subroutine cmblikelihoods::tcmbszlikelihood_readparams (class(tcmbszlikelihood) this, class(tsettingini) Ini)
twmaplikelihood_loglike()
real(mcp) function cmblikelihoods::twmaplikelihood_loglike (class(twmaplikelihood) this, class (cmbparams) CMB, class(tcosmotheorypredictions), target Theory, real(mcp), dimension(:) DataParams)
References likelihood_cosmology::loglike().
twmaplikelihood_readparams()
subroutine cmblikelihoods::twmaplikelihood_readparams (class(twmaplikelihood) this, class(tsettingini) Ini) private
References cosmologytypes::cl_b, cosmologytypes::cl_e, and cosmologytypes::cl_t.