cosmomc_bde_v3p1: mpk Module Reference
mpk Module Reference
Data Types
type mpklikelihood
Functions/Subroutines
subroutine, public mpklikelihood_add (LikeList, Ini)
subroutine mpk_readini (this, Ini)
real(mcp) function mpk_lnlike (this, CMB, Theory, DataParams)
Variables
logical, public use_mpk = .false.
Function/Subroutine Documentation
mpk_lnlike()
real(mcp) function mpk::mpk_lnlike (class(mpklikelihood) this, class(cmbparams) CMB, class(tcosmotheorypredictions), target Theory, real(mcp), dimension(:) DataParams)
References settings::feedback, settings::logzero, and matrixutils::matrix_inverse().
mpk_readini()
subroutine mpk::mpk_readini (class(mpklikelihood) this, class(tsettingini) Ini)
References settings::feedback, and matrixutils::matrix_inverse().
mpklikelihood_add()
subroutine, public mpk::mpklikelihood_add (class(tlikelihoodlist) LikeList, class(tsettingini) Ini)
References settings::feedback, and use_mpk.
Referenced by datalikelihoodlist::setdatalikelihoods().
Variable Documentation
use_mpk
logical, public mpk::use_mpk = .false.
Referenced by mpklikelihood_add(), and datalikelihoodlist::setdatalikelihoods().