cosmomc_bde_v3p1: cmblikes Module Reference
cmblikes Module Reference
Data Types
type tbinwindows
type tcmblikes
type tmapcrosspowerspectrum
type tsqmatrix
Functions/Subroutines
integer function typeindex (C)
subroutine cmblikes_readclarr (this, Ini, basename, Cl, hasKey)
subroutine pairstringtomapindices (this, S, i1, i2)
subroutine pairstringtousedmapindices (this, used_index, S, i1, i2)
subroutine usestring_to_cols (this, S, cols)
subroutine usestring_to_cl_i_j (this, S, used_index, cl_i_j)
subroutine mappair_to_theory_i_j (this, order, i1, i2, i, j)
character(len=:) function, allocatable cl_used_i_j_name (this, i, j)
character(len=:) function, allocatable cl_i_j_name (this, names, i, j)
integer function getcolsfromorder (this, Order, cols)
subroutine readbinwindows (this, Ini, bin_type, binWindows)
subroutine cmblikes_readini (this, Ini)
subroutine readcovmat (this, Ini)
subroutine cmblikes_transform (this, C, Chat, CfHalf, COffset)
subroutine matrixtoelements (this, M, X)
subroutine matrixtoelementsint (this, M, X)
subroutine elementstomatrix (this, X, M)
real(mcp) function exactchisq (this, C, Chat, l)
subroutine getbinnedmapcls (this, MapCls, C, bin)
subroutine initmapcls (this, Cls, nmaps, order)
subroutine gettheorymapcls (this, Theory, Cls, DataParams)
subroutine addforegrounds (this, Cls, DataParams)
subroutine adapttheoryformaps (this, Cls, DataParams)
subroutine cmblikes_writelikelihooddata (this, Theory, DataParams, root)
real(mcp) function cmblikes_loglike (this, CMB, Theory, DataParams)
subroutine tbinwindows_bin (this, TheoryCls, Cls, bin)
Variables
logical, parameter bin_test = .false.
character(len= *), parameter cross_separators = 'x'
integer, parameter tot_theory_fields = len(CMB_CL_Fields)
integer, parameter like_approx_hl =1
integer, parameter like_approx_fid_gaussian =2
integer, parameter like_approx_fullsky_exact =3
character(len=ini_enumeration_len), dimension(3), parameter, public cmblikes_like_names = [character(Ini_Enumeration_Len)::'HL','gaussian','exact']
Function/Subroutine Documentation
adapttheoryformaps()
subroutine cmblikes::adapttheoryformaps (class(tcmblikes) this, class(tmapcrosspowerspectrum), dimension(:,:), intent(inout) Cls, real(mcp), dimension(:), intent(in) DataParams) private
References cosmologytypes::cl_b.
addforegrounds()
subroutine cmblikes::addforegrounds (class(tcmblikes) this, class(tmapcrosspowerspectrum), dimension(:,:), intent(inout), target Cls, real(mcp), dimension(:), intent(in) DataParams) private
cl_i_j_name()
character(len=:) function, allocatable cmblikes::cl_i_j_name (class(tcmblikes) this, class(tstringlist), intent(in) names, integer, intent(in) i, integer, intent(in) j) private
References cross_separators.
cl_used_i_j_name()
character(len=:) function, allocatable cmblikes::cl_used_i_j_name (class(tcmblikes) this, integer, intent(in) i, integer, intent(in) j) private
cmblikes_loglike()
real(mcp) function cmblikes::cmblikes_loglike (class(tcmblikes) this, class(cmbparams) CMB, class(tcosmotheorypredictions), target Theory, real(mcp), dimension(:) DataParams) private
References bin_test, like_approx_fid_gaussian, like_approx_fullsky_exact, like_approx_hl, likelihood_cosmology::loglike(), and matrixutils::matrix_quadform().
cmblikes_readclarr()
subroutine cmblikes::cmblikes_readclarr (class(tcmblikes) this, class(tsettingini), intent(in) Ini, character(len=*), intent(in) basename, real(mcp), dimension(:,:), intent(out), allocatable Cl, logical, intent(inout), optional hasKey) private
References fileutils::file.
cmblikes_readini()
subroutine cmblikes::cmblikes_readini (class(tcmblikes) this, class(tsettingini) Ini) private
References bin_test, cosmologytypes::cl_e, cosmologytypes::cl_phi, cosmologytypes::cl_t, cosmologytypes::cmb_cl_fields, cmblikes_like_names, like_approx_fid_gaussian, like_approx_fullsky_exact, like_approx_hl, and matrixutils::matrix_root().
cmblikes_transform()
subroutine cmblikes::cmblikes_transform (class(tcmblikes) this, real(mcp), dimension(this%nmaps,this%nmaps) C, real(mcp), dimension(this%nmaps,this%nmaps), intent(in) Chat, real(mcp), dimension(this%nmaps,this%nmaps), intent(in) CfHalf, real(mcp), dimension(this%nmaps,this%nmaps), intent(in), optional COffset) private
References matrixutils::matrix_diagonalize(), and matrixutils::matrix_root().
cmblikes_writelikelihooddata()
subroutine cmblikes::cmblikes_writelikelihooddata (class(tcmblikes) this, class(ttheorypredictions) Theory, real(mcp), dimension(:), intent(in) DataParams, character(len=*), intent(in) root) private
elementstomatrix()
subroutine cmblikes::elementstomatrix (class(tcmblikes) this, real(mcp), dimension(this%ncl), intent(in) X, real(mcp), dimension(this%nmaps,this%nmaps), intent(out) M) private
exactchisq()
real(mcp) function cmblikes::exactchisq (class(tcmblikes) this, real(mcp), dimension(this%nmaps,this%nmaps), intent(in) C, real(mcp), dimension(this%nmaps,this%nmaps), intent(in) Chat, integer, intent(in) l) private
References matrixutils::matrix_root(), matrixutils::matrix_trace(), and matrixutils::matrixsym_logdet().
getbinnedmapcls()
subroutine cmblikes::getbinnedmapcls (class(tcmblikes) this, class(tmapcrosspowerspectrum), dimension(:,:) MapCls, real(mcp), dimension(this%nmaps,this%nmaps) C, integer, intent(in) bin) private
getcolsfromorder()
integer function cmblikes::getcolsfromorder (class(tcmblikes) this, character(len=*), intent(in) Order, integer, dimension(:), allocatable cols) private
gettheorymapcls()
subroutine cmblikes::gettheorymapcls (class(tcmblikes), target this, class(tcosmotheorypredictions) Theory, class(tmapcrosspowerspectrum), dimension(:,:), intent(out), pointer Cls, real(mcp), dimension(:), intent(in) DataParams) private
initmapcls()
subroutine cmblikes::initmapcls (class(tcmblikes) this, class(tmapcrosspowerspectrum), dimension(:,:), intent(out), allocatable, target Cls, integer, intent(in) nmaps, integer, dimension(:), intent(in) order) private
mappair_to_theory_i_j()
subroutine cmblikes::mappair_to_theory_i_j (class(tcmblikes) this, integer, dimension(:), intent(in) order, integer, intent(in) i1, integer, intent(in) i2, integer, intent(out) i, integer, intent(out) j) private
matrixtoelements()
subroutine cmblikes::matrixtoelements (class(tcmblikes) this, real(mcp), dimension(this%nmaps,this%nmaps) M, real(mcp), dimension(this%ncl) X) private
matrixtoelementsint()
subroutine cmblikes::matrixtoelementsint (class(tcmblikes) this, integer, dimension(this%nmaps,this%nmaps), intent(in) M, integer, dimension(this%ncl), intent(out) X) private
pairstringtomapindices()
subroutine cmblikes::pairstringtomapindices (class(tcmblikes) this, character(len=*), intent(in) S, integer, intent(out) i1, integer, intent(out) i2) private
References cross_separators.
pairstringtousedmapindices()
subroutine cmblikes::pairstringtousedmapindices (class(tcmblikes) this, integer, dimension(:), intent(in) used_index, character(len=*), intent(in) S, integer, intent(out) i1, integer, intent(out) i2) private
readbinwindows()
subroutine cmblikes::readbinwindows (class(tcmblikes) this, class(tsettingini) Ini, character(len=*), intent(in) bin_type, class(tbinwindows) binWindows) private
References fileutils::file.
readcovmat()
subroutine cmblikes::readcovmat (class(tcmblikes) this, class(tsettingini) Ini) private
References fileutils::file, matrixutils::matrix_inverse(), matrixutils::matrix_read(), matrixutils::matrixsym_read_binary(), and settings::mpi_real_mcp.
tbinwindows_bin()
subroutine cmblikes::tbinwindows_bin (class(tbinwindows) this, class(tskypowerspectrum), dimension(:,:) TheoryCls, real(mcp), dimension(:) Cls, integer bin) private
typeindex()
integer function cmblikes::typeindex (character, intent(in) C) private
References cosmologytypes::cmb_cl_fields.
usestring_to_cl_i_j()
subroutine cmblikes::usestring_to_cl_i_j (class(tcmblikes) this, character(len=*), intent(in) S, integer, dimension(:), intent(in) used_index, integer, dimension(:,:), intent(out), allocatable cl_i_j) private
usestring_to_cols()
subroutine cmblikes::usestring_to_cols (class(tcmblikes) this, character(len=*), intent(in) S, integer, dimension(:), intent(out), allocatable cols) private
Variable Documentation
bin_test
logical, parameter cmblikes::bin_test = .false. private
Referenced by cmblikes_loglike(), and cmblikes_readini().
cmblikes_like_names
character(len=ini_enumeration_len), dimension(3), parameter, public cmblikes::cmblikes_like_names = [character(Ini_Enumeration_Len)::'HL','gaussian','exact']
Referenced by cmblikes_readini().
cross_separators
character(len=*), parameter cmblikes::cross_separators = 'x' private
Referenced by cl_i_j_name(), and pairstringtomapindices().
like_approx_fid_gaussian
integer, parameter cmblikes::like_approx_fid_gaussian =2 private
Referenced by cmblikes_loglike(), and cmblikes_readini().
like_approx_fullsky_exact
integer, parameter cmblikes::like_approx_fullsky_exact =3 private
Referenced by cmblikes_loglike(), and cmblikes_readini().
like_approx_hl
integer, parameter cmblikes::like_approx_hl =1 private
Referenced by cmblikes_loglike(), and cmblikes_readini().
tot_theory_fields
integer, parameter cmblikes::tot_theory_fields = len(CMB_CL_Fields) private