cosmomc_bde_v3p1: matrixutils Module Reference
matrixutils Module Reference
Data Types
type tmatrixtype
Functions/Subroutines
real function getmatrixtime ()
subroutine matrix_start (Name)
subroutine matrix_end (Name)
subroutine matrix_writefilerow (aunit, vec, n)
subroutine matrix_write (aname, mat, forcetable, commentline)
subroutine matrix_write_double (aname, mat, forcetable)
subroutine matrix_write_binary (aname, mat)
subroutine matrixsym_write_binary (aname, mat)
subroutine matrixsym_write_binary_single (aname, mat)
subroutine matrix_writevec (aname, vec)
subroutine matrix_read_binary (aname, mat)
subroutine matrixsym_read_binary (aname, mat)
subroutine matrixsym_read_binary_single (aname, mat)
subroutine matrix_read (aname, mat)
subroutine matrix_readsingle (aname, mat)
real(dm) function, dimension(n) matrix_diag (M, n)
integer function ilaenv_wrap (i, S1, S2, a, b, c, d)
subroutine matrix_diagonalize (M, diag, n)
subroutine matrix_diagonalize_dc (M, diag, n)
subroutine matrix_root (M, n, pow)
subroutine matrix_diagonalize_partial (M, diag, n, emin, emax, nfound)
subroutine matrix_cdiagonalize_partial (M, diag, n, emin, emax, nfound)
subroutine matrix_cdiagonalize (M, diag, n)
complex(dm) function matrix_ctrace (M)
real(dm) function matrix_trace (M)
real(dm) function matrixsym_logdet (mat)
subroutine matrix_crotatesymm (Mat, U, m, Out, triangular)
subroutine matrix_rotatesymm (Mat, U, m, Out, triangular)
subroutine matrix_rotateantisymm (Mat, U, m, Out)
subroutine matrix_cmult_symmright (Mat, U, Out, a, b)
subroutine matrix_cmult_symmleft (Mat, U, Out, a, b)
subroutine matrix_cmult (Mat, U, Out, a, b)
subroutine matrix_multsq_repright (Mat, U, a)
subroutine matrix_multtri (Mat, L, side)
subroutine matrix_mult (Mat, U, Out, a, b)
subroutine matrix_mult_symmleft (Mat, U, Out, a, b)
subroutine matrix_mult_symmright (Mat, U, Out, a, b)
subroutine matrix_cmultgen (Mat, m, k, U, n, Out)
subroutine matrix_multgen (Mat, m, k, U, n, Out)
subroutine matrix_cmult_nt (Mat, U, Out, a, b)
subroutine matrix_mult_nt (Mat, U, Out, a, b)
subroutine matrix_cmult_tn (Mat, U, Out, a, b)
subroutine matrix_mult_tn (Mat, U, Out, a, b)
subroutine matrix_cholesky (M, err, zeroed)
subroutine matrix_ccholesky (M)
subroutine matrix_choleskyrootinverse (M, transpose, error)
subroutine matrix_ccholeskyrootinverse (M, dagger)
subroutine matrix_inverse_chol (M, err)
subroutine matrix_inverse (M)
real(dm) function matrix_gaussianloglike (Cov, d)
double precision function matrix_gaussianloglikedouble (Cov, d)
subroutine matrix_inverseasymm (M)
subroutine matrix_svd (Mat, m, n, D, VT)
subroutine matrix_svd_vt (Mat, m, n, D, U)
subroutine matrix_csvd_vt (Mat, m, n, D, U)
subroutine matrix_csvd_u (Mat, m, n, D, VT)
subroutine matrix_csvd_allvt (Mat, m, n, D, VT)
subroutine matrix_diagpremul (D, M)
subroutine matrix_solvesymm (M, a, soln)
subroutine matrix_solveasymm (M, a, soln)
real(dm) function matrix_vecdot (vec1, vec2)
real(dm) function matrix_quadform (Mat, vec)
subroutine matrix_mulvec (Mat, vec, Out, a, b)
subroutine matrix_mulvecsingle (Mat, vec, Out, a, b)
subroutine matrix_mulvecsymm (Mat, vec, Out, a, b)
subroutine matrix_mulvecsymmsingle (Mat, vec, Out, a, b)
real function matrix_vecdotsingle (vec1, vec2)
subroutine matrix_inversearraympi (Arr, nmat)
Variables
logical, parameter matrix_runmsgs = .false.
integer, parameter dm = KIND(1.0)
integer, parameter mat_f90 =1
integer, parameter mat_norm =2
integer, parameter mat_dc =3
integer, parameter matrix_method = mat_DC
real matrix_starttime
complex(dm), parameter cone = (1._dm, 0._dm)
complex(dm), parameter czero = (0._dm, 0._dm)
real(dm), parameter rone = 1._dm
real(dm), parameter rzero = 0._dm
real, parameter sone = 1.
real, parameter szero = 0.
character(len= *), parameter matrix_io_fmt = '(*(1E17.7))'
Function/Subroutine Documentation
getmatrixtime()
real function matrixutils::getmatrixtime ()
Referenced by matrix_end(), and matrix_start().
ilaenv_wrap()
integer function matrixutils::ilaenv_wrap (integer, intent(in) i, character(len=*), intent(in) S1, character(len=*), intent(in) S2, integer, intent(in) a, integer, intent(in) b, integer, intent(in) c, integer, intent(in) d)
Referenced by matrix_cdiagonalize(), and matrix_diagonalize().
matrix_ccholesky()
subroutine matrixutils::matrix_ccholesky (complex(dm), dimension(:,:), intent(inout) M)
References stringutils::inttostr(), and mpiutils::mpistop().
Referenced by matrix_ccholeskyrootinverse().
matrix_ccholeskyrootinverse()
subroutine matrixutils::matrix_ccholeskyrootinverse (complex(dm), dimension(:,:), intent(inout) M, logical, intent(in), optional dagger)
References stringutils::inttostr(), matrix_ccholesky(), and mpiutils::mpistop().
matrix_cdiagonalize()
subroutine matrixutils::matrix_cdiagonalize (complex(dm), dimension(n,n), intent(inout) M, real(dm), dimension(n), intent(out) diag, integer, intent(in) n)
References ilaenv_wrap(), mat_dc, matrix_end(), matrix_method, matrix_start(), and mpiutils::mpistop().
matrix_cdiagonalize_partial()
subroutine matrixutils::matrix_cdiagonalize_partial (complex(dm), dimension(:,:), intent(inout) M, real(dm), dimension(:), intent(out) diag, integer, intent(in) n, real(dm), intent(in) emin, real(dm), intent(in) emax, integer, intent(inout) nfound)
References matrix_end(), matrix_start(), and mpiutils::mpistop().
matrix_cholesky()
subroutine matrixutils::matrix_cholesky (real(dm), dimension(:,:), intent(inout) M, integer, optional err, logical, intent(in), optional zeroed)
References stringutils::inttostr(), and mpiutils::mpistop().
Referenced by propose::blockedproposer_setcovariance(), matrix_choleskyrootinverse(), matrix_gaussianloglike(), matrix_inverse_chol(), and matrixsym_logdet().
matrix_choleskyrootinverse()
subroutine matrixutils::matrix_choleskyrootinverse (real(dm), dimension(:,:), intent(inout) M, logical, intent(in), optional transpose, integer, intent(out), optional error)
References stringutils::inttostr(), matrix_cholesky(), and mpiutils::mpistop().
Referenced by samples::gelmanrubinevalues().
matrix_cmult()
subroutine matrixutils::matrix_cmult (complex(dm), dimension(:,:), intent(in) Mat, complex(dm), dimension(:,:), intent(in) U, complex(dm), dimension(:,:) Out, complex(dm), intent(in), optional a, complex(dm), intent(in), optional b)
References cone, czero, mat_f90, matrix_end(), matrix_method, matrix_start(), and mpiutils::mpistop().
matrix_cmult_nt()
subroutine matrixutils::matrix_cmult_nt (complex(dm), dimension(:,:), intent(in) Mat, complex(dm), dimension(:,:), intent(in) U, complex(dm), dimension(:,:) Out, complex(dm), intent(in), optional a, complex(dm), intent(in), optional b)
References cone, czero, mat_f90, matrix_end(), matrix_method, matrix_start(), and mpiutils::mpistop().
matrix_cmult_symmleft()
subroutine matrixutils::matrix_cmult_symmleft (complex(dm), dimension(:,:), intent(in) Mat, complex(dm), dimension(:,:), intent(in) U, complex(dm), dimension(:,:) Out, complex(dm), intent(in), optional a, complex(dm), intent(in), optional b)
References cone, czero, mat_f90, matrix_end(), matrix_method, matrix_start(), and mpiutils::mpistop().
matrix_cmult_symmright()
subroutine matrixutils::matrix_cmult_symmright (complex(dm), dimension(:,:), intent(in) Mat, complex(dm), dimension(:,:), intent(in) U, complex(dm), dimension(:,:) Out, complex(dm), intent(in), optional a, complex(dm), intent(in), optional b)
References cone, czero, mat_f90, matrix_end(), matrix_method, matrix_start(), and mpiutils::mpistop().
matrix_cmult_tn()
subroutine matrixutils::matrix_cmult_tn (complex(dm), dimension(:,:), intent(in) Mat, complex(dm), dimension(:,:), intent(in) U, complex(dm), dimension(:,:) Out, complex(dm), intent(in), optional a, complex(dm), intent(in), optional b)
References cone, czero, mat_f90, matrix_end(), matrix_method, matrix_start(), and mpiutils::mpistop().
matrix_cmultgen()
subroutine matrixutils::matrix_cmultgen (complex(dm), dimension(:,:), intent(in) Mat, integer, intent(in) m, integer, intent(in) k, complex(dm), dimension(:,:), intent(in) U, integer, intent(in) n, complex(dm), dimension(:,:) Out)
References cone, czero, mat_f90, matrix_end(), matrix_method, matrix_start(), and mpiutils::mpistop().
matrix_crotatesymm()
subroutine matrixutils::matrix_crotatesymm (complex(dm), dimension(:,:), intent(in) Mat, complex(dm), dimension(:,:), intent(in) U, integer, intent(in) m, complex(dm), dimension(:,:) Out, logical, intent(in), optional triangular)
References cone, czero, mat_f90, matrix_end(), matrix_method, matrix_start(), and mpiutils::mpistop().
matrix_csvd_allvt()
subroutine matrixutils::matrix_csvd_allvt (complex(dm), dimension(m,n), intent(inout) Mat, integer, intent(in) m, integer, intent(in) n, real(dm), dimension(m), intent(out) D, complex(dm), dimension(n,n), intent(out) VT)
References mat_dc, matrix_end(), matrix_method, matrix_start(), and mpiutils::mpistop().
matrix_csvd_u()
subroutine matrixutils::matrix_csvd_u (complex(dm), dimension(m,n), intent(inout) Mat, integer, intent(in) m, integer, intent(in) n, real(dm), dimension(*), intent(out) D, complex(dm), dimension(n,n), intent(out), optional VT)
References mat_dc, matrix_end(), matrix_method, matrix_start(), and mpiutils::mpistop().
matrix_csvd_vt()
subroutine matrixutils::matrix_csvd_vt (complex(dm), dimension(m,n), intent(inout) Mat, integer, intent(in) m, integer, intent(in) n, real(dm), dimension(*), intent(out) D, complex(dm), dimension(m,m), intent(out), optional U)
References mat_dc, matrix_end(), matrix_method, matrix_start(), and mpiutils::mpistop().
matrix_ctrace()
complex(dm) function matrixutils::matrix_ctrace (complex(dm), dimension(:,:), intent(in) M)
References mpiutils::mpistop().
matrix_diag()
real(dm) function, dimension(n) matrixutils::matrix_diag (real(dm), dimension(:,:), intent(in) M, integer, intent(in) n)
matrix_diagonalize()
subroutine matrixutils::matrix_diagonalize (real(dm), dimension(n,n), intent(inout) M, real(dm), dimension(n), intent(out) diag, integer, intent(in) n)
References ilaenv_wrap(), matrix_end(), matrix_start(), and mpiutils::mpistop().
Referenced by cmblikes::cmblikes_transform(), estcovmatmodule::estcovmat(), samples::gelmanrubinevalues(), matrix_diagonalize_dc(), matrix_root(), mcsamples::mostcorrelated2d(), and mcsamples::pca().
matrix_diagonalize_dc()
subroutine matrixutils::matrix_diagonalize_dc (real(dm), dimension(n,n), intent(inout) M, real(dm), dimension(n), intent(out) diag, integer, intent(in) n)
References mat_dc, matrix_diagonalize(), matrix_end(), matrix_method, matrix_start(), and mpiutils::mpistop().
matrix_diagonalize_partial()
subroutine matrixutils::matrix_diagonalize_partial (real(dm), dimension(:,:), intent(inout) M, real(dm), dimension(:), intent(out) diag, integer, intent(in) n, real(dm), intent(in) emin, real(dm), intent(in) emax, integer, intent(inout) nfound)
References matrix_end(), matrix_start(), and mpiutils::mpistop().
matrix_diagpremul()
subroutine matrixutils::matrix_diagpremul (real(dm), dimension(:), intent(in) D, real(dm), dimension(:,:), intent(inout) M)
References mpiutils::mpistop().
matrix_end()
subroutine matrixutils::matrix_end (character(len=*), intent(in) Name)
References getmatrixtime(), matrix_runmsgs, and matrix_starttime.
Referenced by matrix_cdiagonalize(), matrix_cdiagonalize_partial(), matrix_cmult(), matrix_cmult_nt(), matrix_cmult_symmleft(), matrix_cmult_symmright(), matrix_cmult_tn(), matrix_cmultgen(), matrix_crotatesymm(), matrix_csvd_allvt(), matrix_csvd_u(), matrix_csvd_vt(), matrix_diagonalize(), matrix_diagonalize_dc(), matrix_diagonalize_partial(), matrix_gaussianloglike(), matrix_gaussianloglikedouble(), matrix_inverse_chol(), matrix_mult(), matrix_mult_nt(), matrix_mult_symmleft(), matrix_mult_symmright(), matrix_mult_tn(), matrix_multgen(), matrix_multtri(), matrix_mulvec(), matrix_mulvecsingle(), matrix_mulvecsymm(), matrix_mulvecsymmsingle(), matrix_rotateantisymm(), matrix_rotatesymm(), matrix_solveasymm(), matrix_solvesymm(), matrix_svd(), and matrix_svd_vt().
matrix_gaussianloglike()
real(dm) function matrixutils::matrix_gaussianloglike (real(dm), dimension(:,:), intent(inout) Cov, real(dm), dimension(:), intent(in) d)
References matrix_cholesky(), matrix_end(), matrix_start(), and mpiutils::mpistop().
matrix_gaussianloglikedouble()
double precision function matrixutils::matrix_gaussianloglikedouble (double precision, dimension(:,:), intent(inout) Cov, double precision, dimension(:), intent(in) d)
References stringutils::inttostr(), matrix_end(), matrix_start(), and mpiutils::mpistop().
matrix_inverse()
subroutine matrixutils::matrix_inverse (real(dm), dimension(:,:), intent(inout) M)
References matrix_inverse_chol(), and mpiutils::mpistop().
Referenced by estcovmatmodule::estcovmat(), matrix_inversearraympi(), mpk::mpk_lnlike(), mpk::mpk_readini(), cmblikes::readcovmat(), wigglez::wigglez_lnlike(), wigglez::wigglez_readini(), and wl::wl_readini().
matrix_inverse_chol()
subroutine matrixutils::matrix_inverse_chol (real(dm), dimension(:,:), intent(inout) M, integer, optional err)
References stringutils::inttostr(), matrix_cholesky(), matrix_end(), matrix_start(), and mpiutils::mpistop().
Referenced by matrix_inverse().
matrix_inversearraympi()
subroutine matrixutils::matrix_inversearraympi (type(tmatrixtype), dimension(*), target Arr, integer, intent(in) nmat)
References matrix_inverse(), and mpiutils::mpistat().
matrix_inverseasymm()
subroutine matrixutils::matrix_inverseasymm (real(dm), dimension(:,:), intent(inout) M)
References matrix_mult_tn(), matrix_svd(), and mpiutils::mpistop().
matrix_mult()
subroutine matrixutils::matrix_mult (real(dm), dimension(:,:), intent(in) Mat, real(dm), dimension(:,:), intent(in) U, real(dm), dimension(:,:) Out, real(dm), intent(in), optional a, real(dm), intent(in), optional b)
References mat_f90, matrix_end(), matrix_method, matrix_start(), mpiutils::mpistop(), rone, and rzero.
Referenced by matrix_multsq_repright().
matrix_mult_nt()
subroutine matrixutils::matrix_mult_nt (real(dm), dimension(:,:), intent(in) Mat, real(dm), dimension(:,:), intent(in) U, real(dm), dimension(:,:) Out, real(dm), intent(in), optional a, real(dm), intent(in), optional b)
References mat_f90, matrix_end(), matrix_method, matrix_start(), mpiutils::mpistop(), rone, and rzero.
matrix_mult_symmleft()
subroutine matrixutils::matrix_mult_symmleft (real(dm), dimension(:,:), intent(in) Mat, real(dm), dimension(:,:), intent(in) U, real(dm), dimension(:,:) Out, real(dm), intent(in), optional a, real(dm), intent(in), optional b)
References cone, mat_f90, matrix_end(), matrix_method, matrix_start(), mpiutils::mpistop(), rone, and rzero.
matrix_mult_symmright()
subroutine matrixutils::matrix_mult_symmright (real(dm), dimension(:,:), intent(in) Mat, real(dm), dimension(:,:), intent(in) U, real(dm), dimension(:,:) Out, real(dm), intent(in), optional a, real(dm), intent(in), optional b)
References mat_f90, matrix_end(), matrix_method, matrix_start(), mpiutils::mpistop(), rone, and rzero.
matrix_mult_tn()
subroutine matrixutils::matrix_mult_tn (real(dm), dimension(:,:), intent(in) Mat, real(dm), dimension(:,:), intent(in) U, real(dm), dimension(:,:) Out, real(dm), intent(in), optional a, real(dm), intent(in), optional b)
References cone, czero, mat_f90, matrix_end(), matrix_method, matrix_start(), mpiutils::mpistop(), rone, and rzero.
Referenced by matrix_inverseasymm().
matrix_multgen()
subroutine matrixutils::matrix_multgen (real(dm), dimension(:,:), intent(in) Mat, integer, intent(in) m, integer, intent(in) k, real(dm), dimension(:,:), intent(in) U, integer, intent(in) n, real(dm), dimension(:,:) Out)
References mat_f90, matrix_end(), matrix_method, matrix_start(), mpiutils::mpistop(), rone, and rzero.
matrix_multsq_repright()
subroutine matrixutils::matrix_multsq_repright (real(dm), dimension(:,:), intent(in) Mat, real(dm), dimension(:,:), intent(inout) U, real(dm), intent(in), optional a)
References matrix_mult(), mpiutils::mpistop(), and rone.
matrix_multtri()
subroutine matrixutils::matrix_multtri (real(dm), dimension(:,:), intent(inout) Mat, real(dm), dimension(:,:), intent(in) L, character(len=*), intent(in) side)
References matrix_end(), matrix_start(), mpiutils::mpistop(), and rone.
matrix_mulvec()
subroutine matrixutils::matrix_mulvec (real(dm), dimension(:,:), intent(in) Mat, real(dm), dimension(:) vec, real(dm), dimension(:) Out, real(dm), intent(in), optional a, real(dm), intent(in), optional b)
References mat_f90, matrix_end(), matrix_method, matrix_start(), mpiutils::mpistop(), rone, and rzero.
matrix_mulvecsingle()
subroutine matrixutils::matrix_mulvecsingle (real, dimension(:,:), intent(in) Mat, real, dimension(:) vec, real, dimension(:) Out, real, intent(in), optional a, real, intent(in), optional b)
References mat_f90, matrix_end(), matrix_method, matrix_start(), mpiutils::mpistop(), sone, and szero.
matrix_mulvecsymm()
subroutine matrixutils::matrix_mulvecsymm (real(dm), dimension(:,:), intent(in) Mat, real(dm), dimension(:) vec, real(dm), dimension(:) Out, real(dm), intent(in), optional a, real(dm), intent(in), optional b)
References mat_f90, matrix_end(), matrix_method, matrix_start(), mpiutils::mpistop(), rone, and rzero.
Referenced by matrix_quadform().
matrix_mulvecsymmsingle()
subroutine matrixutils::matrix_mulvecsymmsingle (real, dimension(:,:), intent(in) Mat, real, dimension(:) vec, real, dimension(:) Out, real, intent(in), optional a, real, intent(in), optional b)
References mat_f90, matrix_end(), matrix_method, matrix_start(), mpiutils::mpistop(), rone, rzero, sone, and szero.
matrix_quadform()
real(dm) function matrixutils::matrix_quadform (real(dm), dimension(:,:) Mat, real(dm), dimension(:) vec)
References matrix_mulvecsymm(), and matrix_vecdot().
Referenced by bao::bao_lnlike(), cmblikes::cmblikes_loglike(), and wl::wl_lnlike().
matrix_read()
subroutine matrixutils::matrix_read (character(len=*), intent(in) aname, real(dm), dimension(:,:), intent(out) mat)
References mpiutils::mpistop().
Referenced by cmblikes::readcovmat().
matrix_read_binary()
subroutine matrixutils::matrix_read_binary (character(len=*), intent(in) aname, real(dm), dimension(:,:), intent(out) mat)
matrix_readsingle()
subroutine matrixutils::matrix_readsingle (character(len=*), intent(in) aname, real, dimension(:,:), intent(out) mat)
References mpiutils::mpistop().
matrix_root()
subroutine matrixutils::matrix_root (real(dm), dimension(n,n), intent(inout) M, integer, intent(in) n, real(dm), intent(in) pow)
References matrix_diagonalize().
Referenced by cmblikes::cmblikes_readini(), cmblikes::cmblikes_transform(), and cmblikes::exactchisq().
matrix_rotateantisymm()
subroutine matrixutils::matrix_rotateantisymm (real(dm), dimension(:,:), intent(in) Mat, real(dm), dimension(:,:), intent(in) U, integer, intent(in) m, real(dm), dimension(:,:) Out)
References mat_f90, matrix_end(), matrix_method, matrix_start(), mpiutils::mpistop(), rone, and rzero.
matrix_rotatesymm()
subroutine matrixutils::matrix_rotatesymm (real(dm), dimension(:,:), intent(in) Mat, real(dm), dimension(:,:), intent(in) U, integer, intent(in) m, real(dm), dimension(:,:) Out, logical, intent(in), optional triangular)
References mat_f90, matrix_end(), matrix_method, matrix_start(), mpiutils::mpistop(), rone, and rzero.
matrix_solveasymm()
subroutine matrixutils::matrix_solveasymm (real(dm), dimension(:,:), intent(in) M, real(dm), dimension(:), intent(in) a, real(dm), dimension(:), intent(out) soln)
References matrix_end(), matrix_start(), and mpiutils::mpistop().
matrix_solvesymm()
subroutine matrixutils::matrix_solvesymm (real(dm), dimension(:,:), intent(in) M, real(dm), dimension(:), intent(in) a, real(dm), dimension(:), intent(out) soln)
References matrix_end(), matrix_start(), and mpiutils::mpistop().
matrix_start()
subroutine matrixutils::matrix_start (character(len=*), intent(in) Name)
References getmatrixtime(), matrix_runmsgs, and matrix_starttime.
Referenced by matrix_cdiagonalize(), matrix_cdiagonalize_partial(), matrix_cmult(), matrix_cmult_nt(), matrix_cmult_symmleft(), matrix_cmult_symmright(), matrix_cmult_tn(), matrix_cmultgen(), matrix_crotatesymm(), matrix_csvd_allvt(), matrix_csvd_u(), matrix_csvd_vt(), matrix_diagonalize(), matrix_diagonalize_dc(), matrix_diagonalize_partial(), matrix_gaussianloglike(), matrix_gaussianloglikedouble(), matrix_inverse_chol(), matrix_mult(), matrix_mult_nt(), matrix_mult_symmleft(), matrix_mult_symmright(), matrix_mult_tn(), matrix_multgen(), matrix_multtri(), matrix_mulvec(), matrix_mulvecsingle(), matrix_mulvecsymm(), matrix_mulvecsymmsingle(), matrix_rotateantisymm(), matrix_rotatesymm(), matrix_solveasymm(), matrix_solvesymm(), matrix_svd(), and matrix_svd_vt().
matrix_svd()
subroutine matrixutils::matrix_svd (real(dm), dimension(m,n), intent(inout) Mat, integer, intent(in) m, integer, intent(in) n, real(dm), dimension(n), intent(out) D, real(dm), dimension(n,n), intent(out) VT)
References matrix_end(), matrix_start(), and mpiutils::mpistop().
Referenced by matrix_inverseasymm().
matrix_svd_vt()
subroutine matrixutils::matrix_svd_vt (real(dm), dimension(m,n), intent(inout) Mat, integer, intent(in) m, integer, intent(in) n, real(dm), dimension(*), intent(out) D, real(dm), dimension(m,m), intent(out), optional U)
References mat_dc, matrix_end(), matrix_method, matrix_start(), and mpiutils::mpistop().
matrix_trace()
real(dm) function matrixutils::matrix_trace (real(dm), dimension(:,:), intent(in) M)
References mpiutils::mpistop().
Referenced by cmblikes::exactchisq().
matrix_vecdot()
real(dm) function matrixutils::matrix_vecdot (real(dm), dimension(:) vec1, real(dm), dimension(:) vec2)
References mpiutils::mpistop().
Referenced by matrix_quadform().
matrix_vecdotsingle()
real function matrixutils::matrix_vecdotsingle (real, dimension(:) vec1, real, dimension(:) vec2)
References mpiutils::mpistop().
matrix_write()
subroutine matrixutils::matrix_write (character(len=*), intent(in) aname, real(dm), dimension(:,:), intent(in) mat, logical, intent(in), optional forcetable, character(len=*), intent(in), optional commentline)
Referenced by mcsamples::getcovmatrix(), and io::io_writeproposematrix().
matrix_write_binary()
subroutine matrixutils::matrix_write_binary (character(len=*), intent(in) aname, real(dm), dimension(:,:), intent(in) mat)
matrix_write_double()
subroutine matrixutils::matrix_write_double (character(len=*), intent(in) aname, double precision, dimension(:,:), intent(in) mat, logical, intent(in), optional forcetable)
matrix_writefilerow()
subroutine matrixutils::matrix_writefilerow (integer, intent(in) aunit, real(dm), dimension(n) vec, integer, intent(in) n)
References matrix_io_fmt.
matrix_writevec()
subroutine matrixutils::matrix_writevec (character(len=*), intent(in) aname, real(dm), dimension(:), intent(in) vec)
matrixsym_logdet()
real(dm) function matrixutils::matrixsym_logdet (real(dm), dimension(:,:), intent(in) mat)
References matrix_cholesky(), and mpiutils::mpistop().
Referenced by cmblikes::exactchisq().
matrixsym_read_binary()
subroutine matrixutils::matrixsym_read_binary (character(len=*), intent(in) aname, real(dm), dimension(:,:), intent(out) mat)
References mpiutils::mpistop().
Referenced by cmblikes::readcovmat().
matrixsym_read_binary_single()
subroutine matrixutils::matrixsym_read_binary_single (character(len=*), intent(in) aname, real, dimension(:,:), intent(out) mat)
References mpiutils::mpistop().
matrixsym_write_binary()
subroutine matrixutils::matrixsym_write_binary (character(len=*), intent(in) aname, real(dm), dimension(:,:), intent(in) mat)
References mpiutils::mpistop().
matrixsym_write_binary_single()
subroutine matrixutils::matrixsym_write_binary_single (character(len=*), intent(in) aname, real(dm), dimension(:,:), intent(in) mat)
References mpiutils::mpistop().
Variable Documentation
cone
complex(dm), parameter matrixutils::cone = (1._dm, 0._dm)
Referenced by matrix_cmult(), matrix_cmult_nt(), matrix_cmult_symmleft(), matrix_cmult_symmright(), matrix_cmult_tn(), matrix_cmultgen(), matrix_crotatesymm(), matrix_mult_symmleft(), and matrix_mult_tn().
czero
complex(dm), parameter matrixutils::czero = (0._dm, 0._dm)
Referenced by matrix_cmult(), matrix_cmult_nt(), matrix_cmult_symmleft(), matrix_cmult_symmright(), matrix_cmult_tn(), matrix_cmultgen(), matrix_crotatesymm(), and matrix_mult_tn().
dm
integer parameter matrixutils::dm = KIND(1.0)
mat_dc
integer, parameter matrixutils::mat_dc =3
Referenced by matrix_cdiagonalize(), matrix_csvd_allvt(), matrix_csvd_u(), matrix_csvd_vt(), matrix_diagonalize_dc(), and matrix_svd_vt().
mat_f90
integer, parameter matrixutils::mat_f90 =1
Referenced by matrix_cmult(), matrix_cmult_nt(), matrix_cmult_symmleft(), matrix_cmult_symmright(), matrix_cmult_tn(), matrix_cmultgen(), matrix_crotatesymm(), matrix_mult(), matrix_mult_nt(), matrix_mult_symmleft(), matrix_mult_symmright(), matrix_mult_tn(), matrix_multgen(), matrix_mulvec(), matrix_mulvecsingle(), matrix_mulvecsymm(), matrix_mulvecsymmsingle(), matrix_rotateantisymm(), and matrix_rotatesymm().
mat_norm
integer, parameter matrixutils::mat_norm =2
matrix_io_fmt
character(len=*), parameter matrixutils::matrix_io_fmt = '(*(1E17.7))'
Referenced by matrix_writefilerow().
matrix_method
integer, parameter matrixutils::matrix_method = mat_DC
Referenced by matrix_cdiagonalize(), matrix_cmult(), matrix_cmult_nt(), matrix_cmult_symmleft(), matrix_cmult_symmright(), matrix_cmult_tn(), matrix_cmultgen(), matrix_crotatesymm(), matrix_csvd_allvt(), matrix_csvd_u(), matrix_csvd_vt(), matrix_diagonalize_dc(), matrix_mult(), matrix_mult_nt(), matrix_mult_symmleft(), matrix_mult_symmright(), matrix_mult_tn(), matrix_multgen(), matrix_mulvec(), matrix_mulvecsingle(), matrix_mulvecsymm(), matrix_mulvecsymmsingle(), matrix_rotateantisymm(), matrix_rotatesymm(), and matrix_svd_vt().
matrix_runmsgs
logical, parameter matrixutils::matrix_runmsgs = .false.
Referenced by matrix_end(), and matrix_start().
matrix_starttime
real matrixutils::matrix_starttime
Referenced by matrix_end(), and matrix_start().
rone
real(dm), parameter matrixutils::rone = 1._dm
Referenced by matrix_mult(), matrix_mult_nt(), matrix_mult_symmleft(), matrix_mult_symmright(), matrix_mult_tn(), matrix_multgen(), matrix_multsq_repright(), matrix_multtri(), matrix_mulvec(), matrix_mulvecsymm(), matrix_mulvecsymmsingle(), matrix_rotateantisymm(), and matrix_rotatesymm().
rzero
real(dm), parameter matrixutils::rzero = 0._dm
Referenced by matrix_mult(), matrix_mult_nt(), matrix_mult_symmleft(), matrix_mult_symmright(), matrix_mult_tn(), matrix_multgen(), matrix_mulvec(), matrix_mulvecsymm(), matrix_mulvecsymmsingle(), matrix_rotateantisymm(), and matrix_rotatesymm().
sone
real, parameter matrixutils::sone = 1.
Referenced by matrix_mulvecsingle(), and matrix_mulvecsymmsingle().
szero
real, parameter matrixutils::szero = 0.
Referenced by matrix_mulvecsingle(), and matrix_mulvecsymmsingle().