cosmomc_bde_v3p1: getdist.mcsamples Namespace Reference
getdist.mcsamples Namespace Reference
Classes
class Kernel1D
class MCSamples
class MCSamplesError
class ParamError
class SettingError
Functions
def loadMCSamples (file_root, ini=None, jobItem=None, no_cache=False, settings={}, dist_settings={})
def GetChainRootFiles (rootdir)
def GetRootFileName (rootdir)
Variables
int pickle_version = 21
Function Documentation
GetChainRootFiles()
def getdist.mcsamples.GetChainRootFiles (rootdir)
Gets the root names of all chain files in a directory.
:param rootdir: The root directory to check
:return:  The root names
Referenced by getdist.gui.mainwindow.MainWindow.openDirectory().
GetRootFileName()
def getdist.mcsamples.GetRootFileName (rootdir)
Gets the root name of chains in given directory (assuming only one set of chain files).
:param rootdir: The directory to check
:return: The root file name.
loadMCSamples()
def getdist.mcsamples.loadMCSamples (file_root, ini = None, jobItem = None, no_cache = False, settings = {}, dist_settings = {})
Loads a set of samples from a file or files.
Sample files are plain text (*file_root.txt*) or a set of files (*file_root_1.txt*, *file_root_2.txt*, etc.).
Auxiliary files **file_root.paramnames** gives the parameter names
and (optionally) **file_root.ranges** gives hard prior parameter ranges.
For a description of the various analysis settings and default values see
`analysis_defaults.ini <http://getdist.readthedocs.org/en/latest/analysis_settings.html>`_.
:param file_root: The root name of the files to read (no extension)
:param ini: The name of a .ini file with analysis settings to use
:param jobItem: an optional grid jobItem instance for a CosmoMC grid output
:param no_cache: Indicates whether or not we should cached loaded samples in a pickle
:param settings: dictionary of analysis settings to override defaults
:param dist_settings: (old) alias for settings
:return: The :class:`MCSamples` instance
Referenced by getdist.plots.MCSampleAnalysis.samplesForRoot(), and getdist_tests.getdist_test.GetDistFileTest.testFileLoadPlot().
Variable Documentation
pickle_version
int getdist.mcsamples.pickle_version = 21