cosmomc_bde_v3p1: power_sz Module Reference
power_sz Module Reference
Functions/Subroutines
subroutine inigrowth
real(dl) function delta (z)
subroutine ddelta (dummyr, n, a, y, yprime)
real(dl) function growint (a)
Variables
real(dl) normsig8
real(dl) normgrowth
Function/Subroutine Documentation
ddelta()
subroutine power_sz::ddelta (real, intent(in) dummyr, integer, intent(in) n, real(dl), intent(in) a, real(dl), dimension(n) y, real(dl), dimension(n) yprime)
References cosmology::cosmopar, cosmology::omegade(), cosmology::omegak(), and cosmology::omegam().
Referenced by delta().
delta()
real(dl) function power_sz::delta (real(dl), intent(in) z)
References cosmology::cosmopar, ddelta(), dverk(), growint(), normgrowth, and rombint().
Referenced by numbercounts::get_grid(), and inigrowth().
growint()
real(dl) function power_sz::growint (real(dl), intent(in) a)
References cosmology::cosmopar, and cosmology::omegam().
Referenced by delta().
inigrowth()
subroutine power_sz::inigrowth ()
References delta(), and normgrowth.
Variable Documentation
normgrowth
real(dl) power_sz::normgrowth
Referenced by delta(), and inigrowth().
normsig8
real(dl) power_sz::normsig8