cosmomc_bde_v3p1: stringutils Module Reference
stringutils Module Reference
Data Types
interface realtostr
Functions/Subroutines
logical function iswhitespace (C)
integer function getparamcount ()
character(len=:) function, allocatable getparam (i)
character(len=:) function, allocatable getenvironmentvariable (name, is_present)
logical function stringstarts (S, substring, index)
character(len=:) function, allocatable stringtrimmed (S, trimmed)
subroutine stringreplace (FindS, RepS, S)
character(len=:) function, allocatable stringescape (S, C, escape)
character(len=:) function, allocatable join (separator, S, S1, S2, S3, S4, S5, S6, trimmed)
character(len=:) function, allocatable numcat (S, num)
character(len=:) function, allocatable inttostr (I, minlen)
integer function strtoint (S)
subroutine stringappend (S, X)
character(len=:) function, allocatable concat (S1, S2, S3, S4, S5, S6, S7, S8)
character(len=:) function, allocatable doubletostr (R, figs)
character(len=:) function, allocatable singletostr (R, figs)
logical function subnextformat (S, X)
character(len=:) function, allocatable formatstring (formatst, i1, i2, i3, i4, i5, i6, i7, i8, allow_unused)
Function/Subroutine Documentation
concat()
character(len=:) function, allocatable stringutils::concat (character(len=*), intent(in) S1, class(*), intent(in) S2, class(*), intent(in), optional S3, class(*), intent(in), optional S4, class(*), intent(in), optional S5, class(*), intent(in), optional S6, class(*), intent(in), optional S7, class(*), intent(in), optional S8)
References stringappend().
Referenced by inttostr(), numcat(), and paramnames::paramnames_init().
doubletostr()
character(len=:) function, allocatable stringutils::doubletostr (double precision, intent(in) R, integer, intent(in), optional figs)
References singletostr().
formatstring()
character(len=:) function, allocatable stringutils::formatstring (character(len=*), intent(in) formatst, class(*), intent(in), optional i1, class(*), intent(in), optional i2, class(*), intent(in), optional i3, class(*), intent(in), optional i4, class(*), intent(in), optional i5, class(*), intent(in), optional i6, class(*), intent(in), optional i7, class(*), intent(in), optional i8, logical, intent(in), optional allow_unused)
References miscutils::defaultfalse(), stringreplace(), and subnextformat().
Referenced by interpolation::tinterpolator_error(), and fileutils::writeformat().
getenvironmentvariable()
character(len=:) function, allocatable stringutils::getenvironmentvariable (character(len=*), intent(in) name, logical, intent(out), optional is_present)
Referenced by iniobjects::ini_expandenvironment(), iniobjects::ini_read_string_default(), and initests::test_read().
getparam()
character(len=:) function, allocatable stringutils::getparam (integer, intent(in) i)
References getparamcount().
getparamcount()
integer function stringutils::getparamcount ()
Referenced by getparam().
inttostr()
character(len=:) function, allocatable stringutils::inttostr (integer, intent(in) I, integer, intent(in), optional minlen)
References concat().
Referenced by matrixutils::matrix_ccholesky(), matrixutils::matrix_ccholeskyrootinverse(), matrixutils::matrix_cholesky(), matrixutils::matrix_choleskyrootinverse(), matrixutils::matrix_gaussianloglikedouble(), matrixutils::matrix_inverse_chol(), paramnames::paramnames_hasreadiniforparam(), paramnames::paramnames_nameornumber(), paramnames::paramnames_readiniforparam(), paramnames::paramnames_setunnamed(), stringappend(), and subnextformat().
iswhitespace()
logical function stringutils::iswhitespace (character, intent(in) C)
Referenced by iniobjects::ini_read_enumeration_list(), paramnames::paramnames_parseline(), and paramnames::paramnames_readindices().
join()
character(len=:) function, allocatable stringutils::join (character(len=*), intent(in) separator, character(len=*), intent(in) S, character(len=*), intent(in) S1, character(len=*), optional S2, character(len=*), optional S3, character(len=*), optional S4, character(len=*), optional S5, character(len=*), optional S6, logical, intent(in), optional trimmed)
References stringtrimmed().
Referenced by getdist.inifile.IniFile::__str__(), getdist.types.MargeStats::__str__(), paramgrid.batchjob.dataSet::add(), copyGridFiles::doCopy(), getdist.gui.mainwindow.MainWindow::errorReport(), paramgrid.batchjob.dataSet::extendForImportance(), CAMB_test_files::getTestParams(), runbatch::jobName(), getdist.paramnames.ParamList::listString(), planck.plik_postprocess::main_fg2000(), paramgrid.batchjob.jobItem::makeImportance(), CAMB_test_files::makeIniFiles(), paramgrid.batchjob.dataSet::makeNormedDatatag(), paramgrid.batchjob.jobItem::makeNormedName(), paramgrid.batchjob.batchJob::normalizeDataTag(), CAMB_test_files::num_unequal(), getdist.types::numberFigs(), getdist.covmat.CovMat::paramNameString(), makeTables::paramResultTable(), getdist.mcsamples.MCSamples::PCA(), getdist.gui.mainwindow.MainWindow::plotData(), paramgrid.batchjob.batchJob::resolveName(), plot_directive::run(), bbn::runBBNplot(), camb.bbn::runBBNplot(), iniFile.iniFile::saveFile(), plot_directive::split_code_at_show(), paramgrid.jobqueue::submitJob(), getdist.types.ResultTable::tableTex(), paramgrid.batchjob.dataSet::tagReplacing(), getdist.types.TextFile::write(), copyGridFiles::writeIni(), paramgrid.batchjob.jobItem::writeIniLines(), and getdist.mcsamples.MCSamples::writeScriptPlots1D().
numcat()
character(len=:) function, allocatable stringutils::numcat (character(len=*) S, integer num)
References concat().
Referenced by singletostr().
singletostr()
character(len=:) function, allocatable stringutils::singletostr (real, intent(in) R, integer, intent(in), optional figs)
References numcat().
Referenced by doubletostr().
stringappend()
subroutine stringutils::stringappend (character(len=:), allocatable S, class(*) X)
References inttostr().
Referenced by concat().
stringescape()
character(len=:) function, allocatable stringutils::stringescape (character(len=*), intent(in) S, character, intent(in) C, character, intent(in), optional escape)
stringreplace()
subroutine stringutils::stringreplace (character(len=*), intent(in) FindS, character(len=*), intent(in) RepS, character(len=:), intent(inout), allocatable S)
Referenced by formatstring(), paramnames::paramnames_init(), subnextformat(), settings::tsettingini_readfilename(), and settings::tsettingini_replacedirs().
stringstarts()
logical function stringutils::stringstarts (character(len=*), intent(in) S, character(len=*), intent(in) substring, integer, intent(in), optional index)
Referenced by iniobjects::ini_namevalue_addline(), iniobjects::ini_open(), settings::tsettingini_settingvaluesfortagname(), and settings::tsettingini_tagvaluesforname().
stringtrimmed()
character(len=:) function, allocatable stringutils::stringtrimmed (character(len=*), intent(in) S, logical, intent(in), optional trimmed)
References miscutils::defaultfalse().
Referenced by join().
strtoint()
integer function stringutils::strtoint (character(len=*), intent(in) S)
Referenced by subnextformat().
subnextformat()
logical function stringutils::subnextformat (character(len=:), allocatable S, class(*) X)
References inttostr(), stringreplace(), and strtoint().
Referenced by formatstring().