cosmomc_bde_v3p1: mpiutils Module Reference
mpiutils Module Reference
Data Types
type ttimer
Functions/Subroutines
integer function getmpirank ()
logical function ismainmpi ()
subroutine mpistop (Msg)
subroutine mpistat (MpiID, MpiSize)
subroutine mpiquietwait
subroutine mpiwakequietwait
subroutine mpisharestring (S, from)
real(ttimer_dp) function timertime ()
subroutine ttimer_start (this)
real(ttimer_dp) function ttimer_time (this)
subroutine ttimer_writetime (this, Msg, start)
Variables
integer, parameter ttimer_dp = Kind(1.d0)
Function/Subroutine Documentation
getmpirank()
integer function mpiutils::getmpirank ()
References mpistop().
Referenced by ismainmpi(), and mpisharestring().
ismainmpi()
logical function mpiutils::ismainmpi ()
References getmpirank().
mpiquietwait()
subroutine mpiutils::mpiquietwait ()
References mpistat().
mpisharestring()
subroutine mpiutils::mpisharestring (character(len=:), allocatable S, integer from)
References getmpirank(), and mpistop().
mpistat()
subroutine mpiutils::mpistat (integer MpiID, integer MpiSize)
References mpistop().
Referenced by matrixutils::matrix_inversearraympi(), mpiquietwait(), and mpiwakequietwait().
mpistop()
subroutine mpiutils::mpistop (character(len=*), intent(in), optional Msg)
Referenced by settings::checkparamchangef(), fileutils::error(), getmpirank(), randutils::initrandom(), matrixutils::matrix_ccholesky(), matrixutils::matrix_ccholeskyrootinverse(), matrixutils::matrix_cdiagonalize(), matrixutils::matrix_cdiagonalize_partial(), matrixutils::matrix_cholesky(), matrixutils::matrix_choleskyrootinverse(), matrixutils::matrix_cmult(), matrixutils::matrix_cmult_nt(), matrixutils::matrix_cmult_symmleft(), matrixutils::matrix_cmult_symmright(), matrixutils::matrix_cmult_tn(), matrixutils::matrix_cmultgen(), matrixutils::matrix_crotatesymm(), matrixutils::matrix_csvd_allvt(), matrixutils::matrix_csvd_u(), matrixutils::matrix_csvd_vt(), matrixutils::matrix_ctrace(), matrixutils::matrix_diagonalize(), matrixutils::matrix_diagonalize_dc(), matrixutils::matrix_diagonalize_partial(), matrixutils::matrix_diagpremul(), matrixutils::matrix_gaussianloglike(), matrixutils::matrix_gaussianloglikedouble(), matrixutils::matrix_inverse(), matrixutils::matrix_inverse_chol(), matrixutils::matrix_inverseasymm(), matrixutils::matrix_mult(), matrixutils::matrix_mult_nt(), matrixutils::matrix_mult_symmleft(), matrixutils::matrix_mult_symmright(), matrixutils::matrix_mult_tn(), matrixutils::matrix_multgen(), matrixutils::matrix_multsq_repright(), matrixutils::matrix_multtri(), matrixutils::matrix_mulvec(), matrixutils::matrix_mulvecsingle(), matrixutils::matrix_mulvecsymm(), matrixutils::matrix_mulvecsymmsingle(), matrixutils::matrix_read(), matrixutils::matrix_readsingle(), matrixutils::matrix_rotateantisymm(), matrixutils::matrix_rotatesymm(), matrixutils::matrix_solveasymm(), matrixutils::matrix_solvesymm(), matrixutils::matrix_svd(), matrixutils::matrix_svd_vt(), matrixutils::matrix_trace(), matrixutils::matrix_vecdot(), matrixutils::matrix_vecdotsingle(), matrixutils::matrixsym_logdet(), matrixutils::matrixsym_read_binary(), matrixutils::matrixsym_read_binary_single(), matrixutils::matrixsym_write_binary(), matrixutils::matrixsym_write_binary_single(), mpisharestring(), mpistat(), paramnames::paramnames_add(), paramnames::paramnames_asstring(), paramnames::paramnames_init(), paramnames::paramnames_readindices(), randutils::randindices(), interpolation::tinterpolator_error(), and settings::tsettingini_failstop().
mpiwakequietwait()
subroutine mpiutils::mpiwakequietwait ()
References mpistat().
timertime()
real(ttimer_dp) function mpiutils::timertime ()
Referenced by settings::timer(), ttimer_start(), ttimer_time(), and ttimer_writetime().
ttimer_start()
subroutine mpiutils::ttimer_start (class(ttimer) this)
References timertime().
ttimer_time()
real(ttimer_dp) function mpiutils::ttimer_time (class(ttimer) this)
References timertime().
ttimer_writetime()
subroutine mpiutils::ttimer_writetime (class(ttimer) this, character(len=*), intent(in), optional Msg, real(ttimer_dp), optional start)
References timertime().
Variable Documentation
ttimer_dp
integer, parameter mpiutils::ttimer_dp = Kind(1.d0)