cosmomc_bde_v3p1: iniobjects Module Reference
iniobjects Module Reference
Data Types
type tinifile
type tnamevalue
type tnamevalue_pointer
type tnamevaluelist
Functions/Subroutines
subroutine tnamevaluelist_init (this, ignoreDuplicates)
subroutine tnamevaluelist_clear (this)
subroutine tnamevaluelist_free (this)
character(len=:) function, pointer tnamevaluelist_valueof (this, AName)
character(len=:) function, pointer tnamevaluelist_name (this, i)
character(len=:) function, pointer tnamevaluelist_value (this, i)
integer function tnamevaluelist_indexof (this, AName)
logical function tnamevaluelist_haskey (this, AName)
subroutine tnamevaluelist_override (this, Settings, only_if_exists)
subroutine tnamevaluelist_add (this, AName, AValue, only_if_undefined)
subroutine tnamevaluelist_addreal (this, AName, AValue)
subroutine tnamevaluelist_adddouble (this, AName, AValue)
subroutine tnamevaluelist_addint (this, AName, AValue)
subroutine tnamevaluelist_addlogical (this, AName, AValue)
subroutine tnamevaluelist_setcapacity (this, C)
subroutine tnamevaluelist_delete (this, i)
subroutine tnamevaluelist_failstop (this)
subroutine tnamevaluelist_error (this, Msg, Key)
subroutine ini_emptycheckdefault (this, Key, Default)
character(len=:) function, allocatable ini_expandenvironment (this, InValue)
subroutine ini_namevalue_addline (this, AInLine, only_if_undefined)
character(len=:) function, allocatable ini_resolvelinkedfile (this, name, thisfilename)
recursive subroutine ini_open (this, filename, error, slash_comments, append, only_if_undefined)
subroutine ini_open_fromlines (this, Lines, NumLines, slash_comments)
subroutine ini_close (this)
character(len=:) function, pointer ini_read_string (this, Key, NotFoundFail)
character(len=:) function, allocatable ini_read_string_default (this, Key, Default, AllowBlank, EnvDefault)
logical function ini_testequal (this, Key, value, EmptyOK)
character(len=:) function, allocatable ini_key_to_arraykey (this, Key, index)
character(len=:) function, pointer ini_read_string_array (this, Key, index, NotFoundFail)
integer function ini_read_int_array (this, Key, index, Default)
integer function ini_read_int (this, Key, Default, min, max, OK)
integer function ini_enumerationvalue (this, S, Names)
integer function ini_read_enumeration (this, Key, Names, Default)
subroutine ini_read_enumeration_list (this, Key, Names, Enums, nvalues, max_enums, Default)
double precision function ini_read_double (this, Key, Default, min, max)
double precision function ini_read_double_array (this, Key, index, Default, min, max)
real function ini_read_real (this, Key, Default, min, max)
real function ini_read_real_array (this, Key, index, Default, min, max)
logical function ini_read_logical (this, Key, Default)
subroutine ini_savereadvalues (this, afile)
subroutine ini_read_int_change (this, Key, Current, min, max)
subroutine ini_read_double_change (this, Key, Current, min, max)
subroutine ini_read_real_change (this, Key, Current, min, max)
subroutine ini_read_logical_change (this, Key, Current)
subroutine ini_read_string_change (this, Key, Current)
Variables
character(len=0), target empty_string = ''
integer, parameter, public ini_enumeration_len = 64
Function/Subroutine Documentation
ini_close()
subroutine iniobjects::ini_close (class(tinifile) this) private
ini_emptycheckdefault()
subroutine iniobjects::ini_emptycheckdefault (class(tinifile) this, character(len=*), intent(in) Key, class(*), intent(in), optional Default) private
ini_enumerationvalue()
integer function iniobjects::ini_enumerationvalue (class(tinifile) this, character(len=*) S, character(len=ini_enumeration_len), dimension(:), intent(in) Names) private
ini_expandenvironment()
character(len=:) function, allocatable iniobjects::ini_expandenvironment (class(tinifile) this, character(len=:), intent(in), allocatable InValue) private
References stringutils::getenvironmentvariable().
ini_key_to_arraykey()
character(len=:) function, allocatable iniobjects::ini_key_to_arraykey (class(tinifile), intent(in) this, character (len=*), intent(in) Key, integer, intent(in) index) private
ini_namevalue_addline()
subroutine iniobjects::ini_namevalue_addline (class(tinifile) this, character (len=*), intent(in) AInLine, logical, intent(in), optional only_if_undefined) private
References miscutils::defaultfalse(), and stringutils::stringstarts().
ini_open()
recursive subroutine iniobjects::ini_open (class(tinifile) this, character (len=*), intent(in) filename, logical, intent(out), optional error, logical, intent(in), optional slash_comments, logical, intent(in), optional append, logical, intent(in), optional only_if_undefined) private
References miscutils::defaultfalse(), fileutils::error(), and stringutils::stringstarts().
ini_open_fromlines()
subroutine iniobjects::ini_open_fromlines (class(tinifile) this, character (len=*), dimension(numlines), intent(in) Lines, integer, intent(in) NumLines, logical, intent(in), optional slash_comments) private
ini_read_double()
double precision function iniobjects::ini_read_double (class(tinifile) this, character (len=*), intent(in) Key, double precision, intent(in), optional Default, double precision, intent(in), optional min, double precision, intent(in), optional max) private
ini_read_double_array()
double precision function iniobjects::ini_read_double_array (class(tinifile) this, character(len=*), intent(in) Key, integer, intent(in) index, double precision, intent(in), optional Default, double precision, intent(in), optional min, double precision, intent(in), optional max) private
ini_read_double_change()
subroutine iniobjects::ini_read_double_change (class(tinifile) this, character(len=*), intent(in) Key, double precision, intent(inout) Current, double precision, intent(in), optional min, double precision, intent(in), optional max) private
Referenced by iniobjects::tinifile::read().
ini_read_enumeration()
integer function iniobjects::ini_read_enumeration (class(tinifile) this, character(len=*), intent(in) Key, character(len=ini_enumeration_len), dimension(:), intent(in) Names, integer, intent(in), optional Default) private
ini_read_enumeration_list()
subroutine iniobjects::ini_read_enumeration_list (class(tinifile) this, character(len=*), intent(in) Key, character(len=ini_enumeration_len), dimension(:), intent(in) Names, integer, dimension(:), intent(out), allocatable Enums, integer, intent(in), optional nvalues, integer, intent(in), optional max_enums, character(len=*), intent(in), optional Default) private
References stringutils::iswhitespace().
ini_read_int()
integer function iniobjects::ini_read_int (class(tinifile) this, character(len=*), intent(in) Key, integer, intent(in), optional Default, integer, intent(in), optional min, integer, intent(in), optional max, logical, intent(out), optional OK) private
ini_read_int_array()
integer function iniobjects::ini_read_int_array (class(tinifile) this, character(len=*), intent(in) Key, integer, intent(in) index, integer, intent(in), optional Default) private
ini_read_int_change()
subroutine iniobjects::ini_read_int_change (class(tinifile) this, character(len=*), intent(in) Key, integer, intent(inout) Current, integer, intent(in), optional min, integer, intent(in), optional max) private
Referenced by iniobjects::tinifile::read().
ini_read_logical()
logical function iniobjects::ini_read_logical (class(tinifile) this, character(len=*), intent(in) Key, logical, intent(in), optional Default) private
ini_read_logical_change()
subroutine iniobjects::ini_read_logical_change (class(tinifile) this, character(len=*), intent(in) Key, logical, intent(inout) Current) private
Referenced by iniobjects::tinifile::read().
ini_read_real()
real function iniobjects::ini_read_real (class(tinifile) this, character(len=*), intent(in) Key, real, intent(in), optional Default, real, intent(in), optional min, real, intent(in), optional max) private
ini_read_real_array()
real function iniobjects::ini_read_real_array (class(tinifile) this, character(len=*), intent(in) Key, integer, intent(in) index, real, intent(in), optional Default, real, intent(in), optional min, real, intent(in), optional max) private
ini_read_real_change()
subroutine iniobjects::ini_read_real_change (class(tinifile) this, character(len=*), intent(in) Key, real, intent(inout) Current, real, intent(in), optional min, real, intent(in), optional max) private
Referenced by iniobjects::tinifile::read().
ini_read_string()
character(len=:) function, pointer iniobjects::ini_read_string (class(tinifile) this, character (len=*), intent(in) Key, logical, intent(in), optional NotFoundFail) private
ini_read_string_array()
character(len=:) function, pointer iniobjects::ini_read_string_array (class(tinifile) this, character (len=*), intent(in) Key, integer, intent(in) index, logical, intent(in), optional NotFoundFail) private
ini_read_string_change()
subroutine iniobjects::ini_read_string_change (class(tinifile) this, character(len=*), intent(in) Key, character(len=:), intent(inout), allocatable Current) private
Referenced by iniobjects::tinifile::read().
ini_read_string_default()
character(len=:) function, allocatable iniobjects::ini_read_string_default (class(tinifile) this, character (len=*), intent(in) Key, character (len=*), intent(in), optional Default, logical, intent(in), optional AllowBlank, logical, intent(in), optional EnvDefault) private
References miscutils::defaultfalse(), and stringutils::getenvironmentvariable().
ini_resolvelinkedfile()
character(len=:) function, allocatable iniobjects::ini_resolvelinkedfile (class(tinifile) this, character(len=*), intent(in) name, character(len=*), intent(in) thisfilename) private
References fileutils::file.
ini_savereadvalues()
subroutine iniobjects::ini_savereadvalues (class(tinifile) this, character(len=*), intent(in) afile) private
ini_testequal()
logical function iniobjects::ini_testequal (class(tinifile) this, character (len=*), intent(in) Key, character (len=*), intent(in) value, logical, intent(in), optional EmptyOK) private
tnamevaluelist_add()
subroutine iniobjects::tnamevaluelist_add (class(tnamevaluelist) this, character(len=*), intent(in) AName, character(len=*), intent(in) AValue, logical, intent(in), optional only_if_undefined) private
References miscutils::defaulttrue().
tnamevaluelist_adddouble()
subroutine iniobjects::tnamevaluelist_adddouble (class(tnamevaluelist) this, character(len=*), intent(in) AName, double precision, intent(in) AValue) private
Referenced by iniobjects::tnamevaluelist::add().
tnamevaluelist_addint()
subroutine iniobjects::tnamevaluelist_addint (class(tnamevaluelist) this, character(len=*), intent(in) AName, integer, intent(in) AValue) private
Referenced by iniobjects::tnamevaluelist::add().
tnamevaluelist_addlogical()
subroutine iniobjects::tnamevaluelist_addlogical (class(tnamevaluelist) this, character(len=*), intent(in) AName, logical, intent(in) AValue) private
Referenced by iniobjects::tnamevaluelist::add().
tnamevaluelist_addreal()
subroutine iniobjects::tnamevaluelist_addreal (class(tnamevaluelist) this, character(len=*), intent(in) AName, real, intent(in) AValue) private
Referenced by iniobjects::tnamevaluelist::add().
tnamevaluelist_clear()
subroutine iniobjects::tnamevaluelist_clear (class(tnamevaluelist) this) private
tnamevaluelist_delete()
subroutine iniobjects::tnamevaluelist_delete (class(tnamevaluelist) this, integer, intent(in) i) private
tnamevaluelist_error()
subroutine iniobjects::tnamevaluelist_error (class(tnamevaluelist) this, character(len=*) Msg, character(len=*), optional Key) private
tnamevaluelist_failstop()
subroutine iniobjects::tnamevaluelist_failstop (class(tnamevaluelist) this) private
tnamevaluelist_free()
subroutine iniobjects::tnamevaluelist_free (type(tnamevaluelist) this) private
Referenced by iniobjects::tnamevaluelist::tnamevaluelist_free().
tnamevaluelist_haskey()
logical function iniobjects::tnamevaluelist_haskey (class(tnamevaluelist), intent(in) this, character(len=*), intent(in) AName) private
tnamevaluelist_indexof()
integer function iniobjects::tnamevaluelist_indexof (class(tnamevaluelist), intent(in) this, character(len=*), intent(in) AName) private
tnamevaluelist_init()
subroutine iniobjects::tnamevaluelist_init (class(tnamevaluelist) this, logical, intent(in), optional ignoreDuplicates) private
References miscutils::defaultfalse().
tnamevaluelist_name()
character(len=:) function, pointer iniobjects::tnamevaluelist_name (class(tnamevaluelist), intent(in) this, integer i) private
tnamevaluelist_override()
subroutine iniobjects::tnamevaluelist_override (class(tnamevaluelist) this, class(tnamevaluelist), intent(in) Settings, logical, intent(in), optional only_if_exists) private
References miscutils::defaultfalse().
tnamevaluelist_setcapacity()
subroutine iniobjects::tnamevaluelist_setcapacity (class(tnamevaluelist) this, integer C) private
tnamevaluelist_value()
character(len=:) function, pointer iniobjects::tnamevaluelist_value (class(tnamevaluelist), intent(in) this, integer i) private
tnamevaluelist_valueof()
character(len=:) function, pointer iniobjects::tnamevaluelist_valueof (class(tnamevaluelist), intent(in) this, character(len=*), intent(in) AName) private
References empty_string.
Variable Documentation
empty_string
character(len=0), target iniobjects::empty_string = '' private
Referenced by tnamevaluelist_valueof().
ini_enumeration_len
integer, parameter, public iniobjects::ini_enumeration_len = 64
Referenced by iniobjects::tinifile::read().