cosmomc_bde_v3p1: planck.plik_postprocess Namespace Reference
planck.plik_postprocess Namespace Reference
Functions
def parse_minimumfile (minfile)
def parse_paraname (parfile)
def getLk (plikfile)
def main_fgfile (argv)
def main_fg2000 (argv, tag='')
def main (argv)
Variables
cache = dict()
Function Documentation
getLk()
def planck.plik_postprocess.getLk (plikfile)
Referenced by planck.plik_postprocess.main_fg2000(), and planck.plik_postprocess.main_fgfile().
main()
def planck.plik_postprocess.main (argv)
References planck.plik_postprocess.main_fg2000(), and planck.plik_postprocess.main_fgfile().
main_fg2000()
def planck.plik_postprocess.main_fg2000 (argv, tag = '')
References CAMB_test_files.float, planck.plik_postprocess.getLk(), CAMB_test_files.int, stringutils.join(), correlated_iso.p, planck.plik_postprocess.parse_minimumfile(), and planck.plik_postprocess.parse_paraname().
Referenced by planck.plik_postprocess.main().
main_fgfile()
def planck.plik_postprocess.main_fgfile (argv)
References planck.plik_postprocess.getLk(), correlated_iso.p, planck.plik_postprocess.parse_minimumfile(), and planck.plik_postprocess.parse_paraname().
Referenced by planck.plik_postprocess.main().
parse_minimumfile()
def planck.plik_postprocess.parse_minimumfile (minfile)
References CAMB_test_files.float.
Referenced by planck.plik_postprocess.main_fg2000(), and planck.plik_postprocess.main_fgfile().
parse_paraname()
def planck.plik_postprocess.parse_paraname (parfile)
Referenced by planck.plik_postprocess.main_fg2000(), and planck.plik_postprocess.main_fgfile().
Variable Documentation
cache
planck.plik_postprocess.cache = dict()