cosmomc_bde_v3p1: recdata Module Reference
recdata Module Reference
Variables
real(dl) lambda
real(dl) deltab
real(dl) deltab_he
real(dl) lalpha
real(dl) mu_h
real(dl) mu_t
real(dl) h_frac
real(dl) lambda_he
real(dl) lalpha_he
real(dl) bfact
real(dl) ck_he
real(dl) cl_he
real(dl) l_h_ion
real(dl) l_h_alpha
real(dl) l_he1_ion
real(dl) l_he2_ion
real(dl) l_he_2s
real(dl) l_he_2p
real(dl) cb1
real(dl) cdb
real(dl) cr
real(dl) ck
real(dl) cl
real(dl) ct
real(dl) cb1_he1
real(dl) cb1_he2
real(dl) cdb_he
real(dl) fu
real(dl) a2p_s
real(dl) a2p_t
real(dl) sigma_he_2ps
real(dl) sigma_he_2pt
real(dl) l_he_2pt
real(dl) l_he_2st
real(dl) l_he2st_ion
real(dl), parameter bigh =100.0D3/Mpc
real(dl), parameter sigma = sigma_thomson
real(dl), parameter not4 = mass_ratio_He_H
real(dl) tnow
real(dl) ho
integer n_eq = 3
real(dl) omegak
real(dl) omegat
real(dl) z_eq
Variable Documentation
a2p_s
real(dl) recdata::a2p_s
Referenced by recombination::ion().
a2p_t
real(dl) recdata::a2p_t
Referenced by recombination::ion().
bfact
real(dl) recdata::bfact
Referenced by recombination::ion(), and recombination::recombination_init().
bigh
real(dl), parameter recdata::bigh =100.0D3/Mpc
Referenced by recombination::recombination_init().
cb1
real(dl) recdata::cb1
Referenced by recombination::ddeltaxe_dtau(), recombination::get_init(), and recombination::recombination_init().
cb1_he1
real(dl) recdata::cb1_he1
Referenced by recombination::get_init(), and recombination::recombination_init().
cb1_he2
real(dl) recdata::cb1_he2
Referenced by recombination::get_init(), and recombination::recombination_init().
cdb
real(dl) recdata::cdb
Referenced by recombination::ddeltaxe_dtau(), recombination::ion(), and recombination::recombination_init().
cdb_he
real(dl) recdata::cdb_he
Referenced by recombination::ion(), and recombination::recombination_init().
ck
real(dl) recdata::ck
Referenced by recombination::ddeltaxe_dtau(), recombination::ion(), and recombination::recombination_init().
ck_he
real(dl) recdata::ck_he
Referenced by recombination::ion(), and recombination::recombination_init().
cl
real(dl) recdata::cl
Referenced by recombination::ddeltaxe_dtau(), recombination::ion(), and recombination::recombination_init().
cl_he
real(dl) recdata::cl_he
Referenced by recombination::ion(), and recombination::recombination_init().
cr
real(dl) recdata::cr
Referenced by recombination::ddeltaxe_dtau(), recombination::get_init(), recombination::ion(), and recombination::recombination_init().
ct
real(dl) recdata::ct
Referenced by recombination::ion(), and recombination::recombination_init().
deltab
real(dl) recdata::deltab
Referenced by recombination::recombination_init().
deltab_he
real(dl) recdata::deltab_he
Referenced by recombination::recombination_init().
fu
real(dl) recdata::fu
Referenced by recombination::ddeltaxe_dtau(), recombination::ion(), and recombination::recombination_init().
h_frac
real(dl) recdata::h_frac
Referenced by recombination::ion(), and recombination::recombination_init().
ho
real(dl) recdata::ho
Referenced by recombination::ion(), and recombination::recombination_init().
l_h_alpha
real(dl) recdata::l_h_alpha
Referenced by recombination::recombination_init().
l_h_ion
real(dl) recdata::l_h_ion
Referenced by recombination::recombination_init().
l_he1_ion
real(dl) recdata::l_he1_ion
Referenced by recombination::recombination_init().
l_he2_ion
real(dl) recdata::l_he2_ion
Referenced by recombination::recombination_init().
l_he2st_ion
real(dl) recdata::l_he2st_ion
Referenced by recombination::ion().
l_he_2p
real(dl) recdata::l_he_2p
Referenced by recombination::ion(), and recombination::recombination_init().
l_he_2pt
real(dl) recdata::l_he_2pt
Referenced by recombination::ion().
l_he_2s
real(dl) recdata::l_he_2s
Referenced by recombination::recombination_init().
l_he_2st
real(dl) recdata::l_he_2st
Referenced by recombination::ion().
lalpha
real(dl) recdata::lalpha
Referenced by recombination::recombination_init().
lalpha_he
real(dl) recdata::lalpha_he
Referenced by recombination::recombination_init().
lambda
real(dl) recdata::lambda
Referenced by recombination::ddeltaxe_dtau(), and recombination::ion().
lambda_he
real(dl) recdata::lambda_he
Referenced by recombination::ion().
mu_h
real(dl) recdata::mu_h
Referenced by recombination::recombination_init().
mu_t
real(dl) recdata::mu_t
Referenced by recombination::recombination_init().
n_eq
integer recdata::n_eq = 3
Referenced by recombination::recombination_init().
not4
real(dl), parameter recdata::not4 = mass_ratio_He_H
Referenced by recombination::ion(), and recombination::recombination_init().
omegak
real(dl) recdata::omegak
Referenced by recombination::ion(), and recombination::recombination_init().
omegat
real(dl) recdata::omegat
Referenced by recombination::ion(), and recombination::recombination_init().
sigma
real(dl), parameter recdata::sigma = sigma_thomson
sigma_he_2ps
real(dl) recdata::sigma_he_2ps
Referenced by recombination::ion().
sigma_he_2pt
real(dl) recdata::sigma_he_2pt
Referenced by recombination::ion().
tnow
real(dl) recdata::tnow
Referenced by recombination::ddeltaxe_dtau(), recombination::get_init(), recombination::ion(), recombination::recombination_init(), and recombination::recombination_tm().
z_eq
real(dl) recdata::z_eq
Referenced by recombination::ion(), and recombination::recombination_init().