cosmomc_bde_v3p1: lrggettheory Module Reference
lrggettheory Module Reference
Functions/Subroutines
subroutine transfer_getmatterpowerandnw (MTrans, outpower, itf, in, minkh, dlnkh, npoints, kmindata, getabstransferscale, outpowernw, outpowerrationwhalofit)
Variables
real(dl), parameter anear = 0.809717d0
real(dl), parameter amid = 0.745156d0
real(dl), parameter afar = 0.70373d0
real(dl), parameter z0 = 0.0d0
real(dl), parameter znear = 0.235d0
real(dl), parameter zmid = 0.342d0
real(dl), parameter zfar = 0.421d0
real(dl), parameter sigma2baonear = 86.9988
real(dl), parameter sigma2baomid = 85.1374
real(dl), parameter sigma2baofar = 84.5958
real(dl), parameter zeffdr7 = 0.312782
real(dl), dimension(4) transferscalefid
real(dl), dimension(4) powerscaletoz0
real(dl), parameter kmindata = 0.02
integer iz0lrg
integer iznearlrg
integer izmidlrg
integer izfarlrg
logical use_dr7lrg = .false.
Function/Subroutine Documentation
transfer_getmatterpowerandnw()
subroutine lrggettheory::transfer_getmatterpowerandnw (type(mattertransferdata), intent(in) MTrans, real, dimension(npoints), intent(out) outpower, integer, intent(in) itf, integer, intent(in) in, real, intent(in) minkh, real, intent(in) dlnkh, integer, intent(in) npoints, real(dl), intent(in) kmindata, real(dl), intent(out) getabstransferscale, real, dimension(npoints), intent(out) outpowernw, real, dimension(npoints), intent(out) outpowerrationwhalofit)
References transfer::matterpowerdata_free(), nonlinear_getratios(), spline(), transfer::transfer_getmatterpowerdata(), transfer::transfer_kh, transfer::transfer_max, transfer::transfer_power_var, and transfer::transfer_tot.
Variable Documentation
afar
real(dl), parameter lrggettheory::afar = 0.70373d0
amid
real(dl), parameter lrggettheory::amid = 0.745156d0
anear
real(dl), parameter lrggettheory::anear = 0.809717d0
iz0lrg
integer lrggettheory::iz0lrg
izfarlrg
integer lrggettheory::izfarlrg
izmidlrg
integer lrggettheory::izmidlrg
iznearlrg
integer lrggettheory::iznearlrg
kmindata
real(dl), parameter lrggettheory::kmindata = 0.02
powerscaletoz0
real(dl), dimension(4) lrggettheory::powerscaletoz0
sigma2baofar
real(dl), parameter lrggettheory::sigma2baofar = 84.5958
sigma2baomid
real(dl), parameter lrggettheory::sigma2baomid = 85.1374
sigma2baonear
real(dl), parameter lrggettheory::sigma2baonear = 86.9988
transferscalefid
real(dl), dimension(4) lrggettheory::transferscalefid
use_dr7lrg
logical lrggettheory::use_dr7lrg = .false.
z0
real(dl), parameter lrggettheory::z0 = 0.0d0
zeffdr7
real(dl), parameter lrggettheory::zeffdr7 = 0.312782
zfar
real(dl), parameter lrggettheory::zfar = 0.421d0
zmid
real(dl), parameter lrggettheory::zmid = 0.342d0
znear
real(dl), parameter lrggettheory::znear = 0.235d0