cosmomc_bde_v3p1: massivenu Module Reference
massivenu Module Reference
Functions/Subroutines
subroutine, public sum_mnu_for_m1 (summnu, dsummnu, m1, targ, sgn)
subroutine, public nu_init
subroutine nurhopres (am, rhonu, pnu)
subroutine, public nu_background (am, rhonu, pnu)
subroutine, public nu_rho (am, rhonu)
real(dl) function, public nu_drho (am, adotoa, rhonu)
Variables
real(dl), parameter, public const = 7._dl/120*pi**4
real(dl), parameter const2 = 5._dl/7/pi**2
real(dl), parameter zeta3 = 1.2020569031595942853997_dl
real(dl), parameter zeta5 = 1.0369277551433699263313_dl
real(dl), parameter zeta7 = 1.0083492773819228268397_dl
real(dl), parameter, public neutrino_mass_fac = 94.07_dl
integer, parameter nrhopn =2000
real(dl), parameter am_min = 0.01_dl
real(dl), parameter am_max = 600._dl
real(dl), parameter am_minp =am_min*1.1
real(dl), parameter am_maxp =am_max*0.9
real(dl) dlnam
real(dl), dimension(:), allocatable r1
real(dl), dimension(:), allocatable p1
real(dl), dimension(:), allocatable dr1
real(dl), dimension(:), allocatable dp1
real(dl), dimension(:), allocatable ddr1
integer, parameter, public nqmax0 =80
real(dl), dimension(nqmax0), public nu_q
real(dl), dimension(nqmax0), public nu_int_kernel
integer, public nqmax
Function/Subroutine Documentation
nu_background()
subroutine, public massivenu::nu_background (real(dl), intent(in) am, real(dl), intent(out) rhonu, real(dl), intent(out) pnu)
References am_maxp, am_min, am_minp, const, const2, dlnam, dp1, dr1, p1, r1, zeta3, zeta5, and zeta7.
Referenced by dtauda(), gaugeinterface::massivenuvars(), gaugeinterface::massivenuvarsout(), and gaugeinterface::switchtomassivenuapprox().
nu_drho()
real(dl) function, public massivenu::nu_drho (real(dl), intent(in) am, real(dl) adotoa, real(dl) rhonu)
References am_maxp, am_min, am_minp, const, const2, ddr1, dlnam, dr1, zeta3, and zeta5.
Referenced by dtauda(), and gaugeinterface::massivenuvarsout().
nu_init()
subroutine, public massivenu::nu_init ()
References modelparams::accuracyboost, am_max, am_min, const, modelparams::cp, ddr1, dlnam, dp1, dr1, modelparams::grhom, modelparams::grhor, nqmax, nqmax0, nrhopn, nu_int_kernel, modelparams::nu_masses, nu_q, nurhopres(), p1, r1, splder(), splini(), and zeta3.
Referenced by init_massive_nu().
nu_rho()
subroutine, public massivenu::nu_rho (real(dl), intent(in) am, real(dl), intent(out) rhonu)
References am_maxp, am_min, am_minp, const, const2, dlnam, dr1, r1, zeta3, and zeta5.
Referenced by gaugeinterface::derivst(), and dtauda().
nurhopres()
subroutine massivenu::nurhopres (real(dl), intent(in) am, real(dl), intent(out) rhonu, real(dl), intent(out) pnu) private
References const, and splint().
Referenced by nu_init().
sum_mnu_for_m1()
subroutine, public massivenu::sum_mnu_for_m1 (real(dl), intent(out) summnu, real(dl), intent(out) dsummnu, real(dl), intent(in) m1, real(dl), intent(in) targ, real(dl), intent(in) sgn)
References constants::delta_mnu21, and constants::delta_mnu31.
Referenced by calculator_camb::cambcalc_cmbtocamb().
Variable Documentation
am_max
real(dl), parameter massivenu::am_max = 600._dl private
Referenced by nu_init().
am_maxp
real(dl), parameter massivenu::am_maxp =am_max*0.9 private
Referenced by nu_background(), nu_drho(), and nu_rho().
am_min
real(dl), parameter massivenu::am_min = 0.01_dl private
Referenced by nu_background(), nu_drho(), nu_init(), and nu_rho().
am_minp
real(dl), parameter massivenu::am_minp =am_min*1.1 private
Referenced by nu_background(), nu_drho(), and nu_rho().
const
real(dl), parameter, public massivenu::const = 7._dl/120*pi**4
Referenced by nu_background(), nu_drho(), nu_init(), nu_rho(), and nurhopres().
const2
real(dl), parameter massivenu::const2 = 5._dl/7/pi**2 private
Referenced by nu_background(), nu_drho(), and nu_rho().
ddr1
real(dl), dimension(:), allocatable massivenu::ddr1 private
Referenced by nu_drho(), and nu_init().
dlnam
real(dl) massivenu::dlnam private
Referenced by nu_background(), nu_drho(), nu_init(), and nu_rho().
dp1
real(dl), dimension(:), allocatable massivenu::dp1 private
Referenced by nu_background(), and nu_init().
dr1
real(dl), dimension(:), allocatable massivenu::dr1 private
Referenced by nu_background(), nu_drho(), nu_init(), and nu_rho().
neutrino_mass_fac
real(dl), parameter, public massivenu::neutrino_mass_fac = 94.07_dl
nqmax
integer, public massivenu::nqmax
Referenced by gaugeinterface::copytensorvariablearray(), gaugeinterface::derivst(), dtauda(), gaugeinterface::gaugeinterface_evolvescal(), gaugeinterface::gaugeinterface_init(), gaugeinterface::getnumeqns(), gaugeinterface::next_nu_nq(), nu_init(), gaugeinterface::nu_integrate_l012(), gaugeinterface::nu_intvsq(), gaugeinterface::nu_pi(), gaugeinterface::nu_pinudot(), gaugeinterface::setupscalararrayindices(), and gaugeinterface::setuptensorarrayindices().
nqmax0
integer, parameter, public massivenu::nqmax0 =80
Referenced by nu_init().
nrhopn
integer, parameter massivenu::nrhopn =2000 private
Referenced by nu_init().
nu_int_kernel
real(dl), dimension(nqmax0), public massivenu::nu_int_kernel
Referenced by dtauda(), nu_init(), gaugeinterface::nu_integrate_l012(), gaugeinterface::nu_intvsq(), gaugeinterface::nu_pi(), and gaugeinterface::nu_pinudot().
nu_q
real(dl), dimension(nqmax0), public massivenu::nu_q
Referenced by gaugeinterface::copyscalarvariablearray(), gaugeinterface::derivs(), gaugeinterface::derivst(), dtauda(), gaugeinterface::gaugeinterface_init(), gaugeinterface::getnumeqns(), gaugeinterface::next_nu_nq(), nu_init(), gaugeinterface::nu_integrate_l012(), gaugeinterface::nu_intvsq(), gaugeinterface::nu_pi(), and gaugeinterface::nu_pinudot().
p1
real(dl), dimension(:), allocatable massivenu::p1 private
Referenced by nu_background(), and nu_init().
r1
real(dl), dimension(:), allocatable massivenu::r1 private
Referenced by nu_background(), nu_init(), and nu_rho().
zeta3
real(dl), parameter massivenu::zeta3 = 1.2020569031595942853997_dl private
Referenced by nu_background(), nu_drho(), nu_init(), and nu_rho().
zeta5
real(dl), parameter massivenu::zeta5 = 1.0369277551433699263313_dl private
Referenced by nu_background(), nu_drho(), and nu_rho().
zeta7
real(dl), parameter massivenu::zeta7 = 1.0083492773819228268397_dl private
Referenced by nu_background().