cosmomc_bde_v3p1: initialpower Module Reference
initialpower Module Reference
Data Types
type initialpowerparams
Functions/Subroutines
subroutine, public setdefpowerparams (AP)
subroutine, public initializepowers (AParamSet, acurv)
real(dl) function, public scalarpower (k, ix)
real(dl) function, public tensorpower (k, ix)
integer function, public power_descript (in, Scal, Tens, Keys, Vals)
subroutine, public initialpower_readparams (InitPower, Ini, WantTensors)
Variables
character(len= *), parameter, public power_name = 'power_tilt'
integer, parameter, public nnmax = 5
integer, parameter, public tensor_param_indeptilt =1
integer, parameter, public tensor_param_rpivot = 2
integer, parameter, public tensor_param_at = 3
real(dl) curv
type(initialpowerparams), save p
Function/Subroutine Documentation
initializepowers()
subroutine, public initialpower::initializepowers (type (initialpowerparams) AParamSet, real(dl) acurv)
References curv, nnmax, and p.
Referenced by camb::camb_transferstopowers(), and cambmain::cmbmain().
initialpower_readparams()
subroutine, public initialpower::initialpower_readparams (type(initialpowerparams) InitPower, type(tinifile) Ini, logical, intent(in) WantTensors)
References inifile::ini_read_double_array_file(), inifile::ini_read_double_file(), inifile::ini_read_int_file(), nnmax, tensor_param_at, and tensor_param_indeptilt.
power_descript()
integer function, public initialpower::power_descript (integer, intent(in) in, logical, intent(in) Scal, logical, intent(in) Tens, character(len=8), dimension(*), intent(out) Keys, real(dl), dimension(*), intent(out) Vals)
References p.
scalarpower()
real(dl) function, public initialpower::scalarpower (real(dl) k, integer ix)
References p.
Referenced by cambmain::calclimberscalcls(), cambmain::calcscalcls(), cambmain::calcscalcls2(), cambmain::getinitpowerarrayvec(), and tensorpower().
setdefpowerparams()
subroutine, public initialpower::setdefpowerparams (type (initialpowerparams) AP)
References tensor_param_indeptilt.
Referenced by camb::camb_setdefparams().
tensorpower()
real(dl) function, public initialpower::tensorpower (real(dl) k, integer ix)
References curv, p, scalarpower(), tensor_param_at, tensor_param_indeptilt, and tensor_param_rpivot.
Referenced by cambmain::getinitpowerarraytens().
Variable Documentation
curv
real(dl) initialpower::curv private
Referenced by initializepowers(), and tensorpower().
nnmax
integer, parameter, public initialpower::nnmax = 5
Referenced by initializepowers(), and initialpower_readparams().
p
type(initialpowerparams), save initialpower::p private
Referenced by camb::camb_getage(), camb::camb_getzrefromtau(), camb::camb_validateparams(), initializepowers(), power_descript(), scalarpower(), and tensorpower().
power_name
character(len=*), parameter, public initialpower::power_name = 'power_tilt'
tensor_param_at
integer, parameter, public initialpower::tensor_param_at = 3
Referenced by initialpower_readparams(), and tensorpower().
tensor_param_indeptilt
integer, parameter, public initialpower::tensor_param_indeptilt =1
Referenced by initialpower_readparams(), setdefpowerparams(), and tensorpower().
tensor_param_rpivot
integer, parameter, public initialpower::tensor_param_rpivot = 2
Referenced by tensorpower().