cosmomc_bde_v3p1: /home/ealmaraz/software/cosmomc/bde/v3.1/camb/plotcls.m File Reference
plotcls.m File Reference
Functions
function plotcls (varargin) global l_label clf
colnum (i)
if (noB) TE
end if (lmax >=3000) ticks
end end subplot (ploty, plotx, 1)
seth (h)
loglog (ls, TT, col)
setaxes (minTT *0.9, maxTT *1.1, lmin, lmax)
subplot (ploty, plotx, 3)
plot (sqrt(ls), TT, col)
setaxes (0, maxTT *1.1, sqrt(lmin), sqrt(lmax))
set (gca, 'XTick', sqrt(ticks))
set (gca, 'XTickLabel', ticks)
subplot (ploty, plotx, 2)
loglog (ls, EE, ['-' col])
setaxes (e, t, lmin, lmax)
loglog (ls, TE, ['-' col])
loglog (ls,-TE, [':' col])
if ~noB loglog (ls, BB, ['--' col])
end subplot (ploty, plotx, 4)
plot (sqrt(ls), TE, ['-' col])
plot (sqrt(ls), EE, ['-' col])
setaxes (minTE *1.1, maxTE *1.1, sqrt(lmin), sqrt(lmax))
if i subplot (ploty, plotx, 5)
plot (sqrt(ls(1:dm)), cmp, col)
set (gca, 'XLim', [sqrt(lmin) sqrt(lmax)])
ylabel ('{\Delta C_l/C_l}(TT)')
xlabel (l_label)
subplot (ploty, plotx, 6)
end plot (sqrt(ls(1:dm)), cmp, [':' col])
ylabel ('{{\Delta C_l/C_l}}(EE/TE)')
seth (hin)
id ps ()
function d global l_label set (gca, 'YLim', [a, b], 'XLim', [c, d])
ylabel ('l(l+1) C_l/2\pi')
Variables
hin =ishold
h =false
colours = 'krbcmgy'
l_label = 'l'
ticks = [2 40 200 600 1200]
for i
x =size(dats{i})
end lmin =2
lmax =1
minTE =1e30
minEE =1e30
minTT =1e30
maxTE =-1e30
maxEE =-1e30
maxTT =-1e30
plotx =2
ploty =2
col =colours(i)
ls =x(:,1)
TT =x(:,2)
EE =x(:,3)
noB = colnum(i)==4 || colnum(i)==6
BB =0
TE =x(:,5)
compEE =EE
compTE =TE
e =minEE*0.5
t =max(maxEE,maxTE)*2
hold on
cmp = (TT(1:dm) - compTT(1:dm)) ./ compTT(1:dm)
maxcmp = max(cmp)
for j
end
function b
function c
Function Documentation
colnum()
colnum (i)
if() [1/2]
if (noB)
if() [2/2]
end if (lmax >= 3000)
loglog() [1/5]
loglog (ls , TT , col)
loglog() [2/5]
loglog (ls , EE)
loglog() [3/5]
loglog (ls , TE)
loglog() [4/5]
loglog (ls , - TE)
loglog() [5/5]
if ~noB loglog (ls , BB)
plot() [1/5]
plot (sqrt(ls) , TT , col)
Referenced by cambPlots.ClResult::compare_array_acc(), and cambPlots.ClResult::compare_type_tol().
plot() [2/5]
plot (sqrt(ls) , TE)
plot() [3/5]
plot (sqrt(ls) , EE)
plot() [4/5]
plot (sqrt(ls(1:dm)) , cmp , col)
plot() [5/5]
end plot (sqrt(ls(1:dm)) , cmp)
plotcls()
function plotcls (varargin)
ps()
id ps () virtual
set() [1/4]
set (gca , 'XTick' , sqrt(ticks))
Referenced by camb.camb.CAMBdata::get_background_time_evolution(), camb.camb.CAMBdata::get_time_evolution(), paramgrid.batchjob.jobItem::makeImportance(), fileutils::readline(), and camb.camb::set_params().
set() [2/4]
set (gca , 'XTickLabel' , ticks)
set() [3/4]
set (gca , 'XLim')
set() [4/4]
function d global l_label set (gca , 'YLim' , 'XLim')
setaxes() [1/4]
setaxes (minTT *0. 9, maxTT *1. 1, lmin , lmax)
setaxes() [2/4]
setaxes (0 , maxTT *1. 1, sqrt(lmin) , sqrt(lmax))
setaxes() [3/4]
setaxes (e , t , lmin , lmax)
setaxes() [4/4]
setaxes (minTE *1. 1, maxTE *1. 1, sqrt(lmin) , sqrt(lmax))
seth() [1/2]
seth (h)
seth() [2/2]
seth (hin)
subplot() [1/6]
end end subplot (ploty , plotx , 1)
subplot() [2/6]
subplot (ploty , plotx , 3)
subplot() [3/6]
subplot (ploty , plotx , 2)
subplot() [4/6]
end subplot (ploty , plotx , 4)
subplot() [5/6]
if i subplot (ploty , plotx , 5)
subplot() [6/6]
subplot (ploty , plotx , 6)
xlabel()
xlabel (l_label)
ylabel() [1/3]
ylabel ('{\Delta C_l/C_l}(TT)')
ylabel() [2/3]
ylabel ('{{\Delta C_l/C_l}}(EE/TE)')
ylabel() [3/3]
ylabel ('l(l+1) C_l/2\pi')
Variable Documentation
b
function b
BB
else BB =0
c
function c
cmp
else seth(h) end cmp = (TT(1:dm) - compTT(1:dm)) ./ compTT(1:dm)
col
col =colours(i)
colours
colours = 'krbcmgy'
compEE
compEE =EE
compTE
compTE =TE
e
e =minEE*0.5
EE
EE =x(:,3)
end
end
h
end h =false
hin
hin =ishold
i
if i
Initial value:
=1:nargin
dats{i}=load(varargin{i})
Referenced by dopksmoothbspline_().
j
for j
Initial value:
=1:dm
    cmp= (TE(1:dm) - compTE(1:dm)) ./ sqrt(compEE(1:dm).*compTT(1:dm))
Referenced by dopksmoothbspline_().
l_label
l_label = 'l'
lmax
end if i lmax =1
lmin
end end lmin =2
ls
ls =x(:,1)
maxcmp
maxcmp = max(cmp)
maxEE
maxEE =-1e30
maxTE
maxTE =-1e30
maxTT
maxTT =-1e30
minEE
minEE =1e30
minTE
minTE =1e30
minTT
end minTT =1e30
noB
noB = colnum(i)==4 || colnum(i)==6
on
hold on
plotx
plotx =2
ploty
if nargin ploty =2
t
t =max(maxEE,maxTE)*2
TE
TE =x(:,5)
ticks
ticks = [2 40 200 600 1200]
TT
TT =x(:,2)
x
x =size(dats{i})