cosmomc_bde_v3p1: fileutils::tfilestream Type Reference
fileutils::tfilestream Type Reference
Private Member Functions
procedure setdefaultmodes
procedure open => TFileStream_Open
procedure openfile => TFileStream_OpenFile
procedure flush => TFileStream_Flush
procedure createfile
procedure createopenfile
procedure position => TFileStream_Position
procedure size => TFileStream_Size
procedure close => TFileStream_Close
procedure rewind => TFileStream_Rewind
procedure error
procedure opened
procedure writetrim
procedure checkopen
procedure, private readstringfunc
procedure, private readstringsub
procedure, private readitemsub
procedure, private readitemfunc
procedure, private readitems
procedure, private readarray
procedure, private readarray2
procedure, private readarray2func
procedure, private readarrayfunc
procedure, private writeitemsub
procedure, private writearray
procedure, private writeoneandarray
procedure, private writearray2
procedure, private writeitems
procedure, private writesizedarray1
procedure, private writesizedarray2
procedure, private readsizedarray_r
procedure, private readsizedarray_d
procedure, private readsizedarray_i
procedure, private readsizedarray2_i
procedure, private readsizedarray2_d
procedure, private readsizedarray2_r
generic write => WriteItems, WriteArray, WriteArray2, WriteOneAndArray
generic read => ReadItems, ReadArray, ReadArray2
generic readitem => ReadItemFunc, ReadArrayFunc, ReadArray2Func
generic readstring => ReadStringSub
generic readstringitem => ReadStringFunc
generic writesizedarray => WriteSizedArray1, WriteSizedArray2
generic readsizedarray => ReadSizedArray_R, ReadSizedArray_D, ReadSizedArray_I, ReadSizedArray2_I, ReadSizedArray2_R, ReadSizedArray2_D
final tfilestream_free
Private Attributes
integer unit = 0
logical readonly = .true.
character(len=:), allocatable mode
character(len=:), allocatable access
character(len=:), allocatable filename
Member Function/Subroutine Documentation
checkopen()
procedure fileutils::tfilestream::checkopen () private
close()
procedure fileutils::tfilestream::close () private
createfile()
procedure fileutils::tfilestream::createfile () private
createopenfile()
procedure fileutils::tfilestream::createopenfile () private
error()
procedure fileutils::tfilestream::error () private
flush()
procedure fileutils::tfilestream::flush () private
open()
procedure fileutils::tfilestream::open () private
opened()
procedure fileutils::tfilestream::opened () private
openfile()
procedure fileutils::tfilestream::openfile () private
position()
procedure fileutils::tfilestream::position () private
read()
generic fileutils::tfilestream::read () private
References fileutils::readarray(), fileutils::readarray2(), and fileutils::readitems().
readarray()
procedure, private fileutils::tfilestream::readarray () private
readarray2()
procedure, private fileutils::tfilestream::readarray2 () private
readarray2func()
procedure, private fileutils::tfilestream::readarray2func () private
readarrayfunc()
procedure, private fileutils::tfilestream::readarrayfunc () private
readitem()
generic fileutils::tfilestream::readitem () private
References fileutils::readarray2func(), fileutils::readarrayfunc(), and fileutils::readitemfunc().
readitemfunc()
procedure, private fileutils::tfilestream::readitemfunc () private
readitems()
procedure, private fileutils::tfilestream::readitems () private
readitemsub()
procedure, private fileutils::tfilestream::readitemsub () private
readsizedarray()
generic fileutils::tfilestream::readsizedarray () private
References fileutils::readsizedarray2_d(), fileutils::readsizedarray2_i(), fileutils::readsizedarray2_r(), fileutils::readsizedarray_d(), fileutils::readsizedarray_i(), and fileutils::readsizedarray_r().
readsizedarray2_d()
procedure, private fileutils::tfilestream::readsizedarray2_d () private
readsizedarray2_i()
procedure, private fileutils::tfilestream::readsizedarray2_i () private
readsizedarray2_r()
procedure, private fileutils::tfilestream::readsizedarray2_r () private
readsizedarray_d()
procedure, private fileutils::tfilestream::readsizedarray_d () private
readsizedarray_i()
procedure, private fileutils::tfilestream::readsizedarray_i () private
readsizedarray_r()
procedure, private fileutils::tfilestream::readsizedarray_r () private
readstring()
generic fileutils::tfilestream::readstring () private
References fileutils::readstringsub().
readstringfunc()
procedure, private fileutils::tfilestream::readstringfunc () private
readstringitem()
generic fileutils::tfilestream::readstringitem () private
References fileutils::readstringfunc().
readstringsub()
procedure, private fileutils::tfilestream::readstringsub () private
rewind()
procedure fileutils::tfilestream::rewind () private
setdefaultmodes()
procedure fileutils::tfilestream::setdefaultmodes () private
size()
procedure fileutils::tfilestream::size () private
Referenced by getdist.gui.mainwindow.MainWindow::writeSettings().
tfilestream_free()
final fileutils::tfilestream::tfilestream_free () final private
References fileutils::tfilestream_free().
write()
generic fileutils::tfilestream::write () private
References fileutils::writearray(), fileutils::writearray2(), fileutils::writeitems(), and fileutils::writeoneandarray().
writearray()
procedure, private fileutils::tfilestream::writearray () private
writearray2()
procedure, private fileutils::tfilestream::writearray2 () private
writeitems()
procedure, private fileutils::tfilestream::writeitems () private
writeitemsub()
procedure, private fileutils::tfilestream::writeitemsub () private
writeoneandarray()
procedure, private fileutils::tfilestream::writeoneandarray () private
writesizedarray()
generic fileutils::tfilestream::writesizedarray () private
References fileutils::writesizedarray1(), and fileutils::writesizedarray2().
writesizedarray1()
procedure, private fileutils::tfilestream::writesizedarray1 () private
writesizedarray2()
procedure, private fileutils::tfilestream::writesizedarray2 () private
writetrim()
procedure fileutils::tfilestream::writetrim () private
Member Data Documentation
access
character(len=:), allocatable fileutils::tfilestream::access private
filename
character(len=:), allocatable fileutils::tfilestream::filename private
Referenced by plot_directive.ImageFile::filenames().
mode
character(len=:), allocatable fileutils::tfilestream::mode private
readonly
logical fileutils::tfilestream::readonly = .true. private
unit
integer fileutils::tfilestream::unit = 0 private
The documentation for this type was generated from the following file:
/home/ealmaraz/software/cosmomc/bde/v3.1/source/FileUtils.f90