cosmomc_bde_v3p1: modelparams::cambparams Type Reference
modelparams::cambparams Type Reference
Public Attributes
logical wantcls
logical wanttransfer
logical wantscalars
logical wanttensors
logical wantvectors
logical dolensing
logical want_zstar
logical want_zdrag
logical pk_wanttransfer
integer nonlinear
logical want_cmb
integer max_l
integer max_l_tensor
real(dl) max_eta_k
real(dl) max_eta_k_tensor
real(dl) omegab
real(dl) omegac
real(dl) omegav
real(dl) omegan
real(dl) h0
real(dl) tcmb
real(dl) yhe
real(dl) num_nu_massless
integer num_nu_massive
integer nu_mass_eigenstates
logical share_delta_neff
real(dl), dimension(max_nu) nu_mass_degeneracies
real(dl), dimension(max_nu) nu_mass_fractions
integer, dimension(max_nu) nu_mass_numbers
integer scalar_initial_condition
integer outputnormalization
logical accuratepolarization
logical accuratebb
logical accuratereionization
integer massivenumethod
type(initialpowerparams) initpower
type(reionizationparams) reion
type(recombinationparams) recomb
type(transferparams) transfer
real(dl), dimension(1:10) initialconditionvector
logical onlytransfers
logical derivedparameters
type(reionizationhistory) reionhist
logical flat
logical closed
logical open
real(dl) omegak
real(dl) curv
real(dl) r
real(dl) ksign
real(dl) tau0
real(dl) chi0
real(dl) lambdac
real(dl) alphabde
real(dl) wdgc
real(dl) omegadgc
real(dl) ac
real(dl) rsdrag
real(dl) rhor0
real(dl) wde0
Member Data Documentation
ac
real(dl) modelparams::cambparams::ac
accuratebb
logical modelparams::cambparams::accuratebb
accuratepolarization
logical modelparams::cambparams::accuratepolarization
accuratereionization
logical modelparams::cambparams::accuratereionization
alphabde
real(dl) modelparams::cambparams::alphabde
chi0
real(dl) modelparams::cambparams::chi0
closed
logical modelparams::cambparams::closed
curv
real(dl) modelparams::cambparams::curv
derivedparameters
logical modelparams::cambparams::derivedparameters
dolensing
logical modelparams::cambparams::dolensing
flat
logical modelparams::cambparams::flat
h0
real(dl) modelparams::cambparams::h0
initialconditionvector
real(dl), dimension(1:10) modelparams::cambparams::initialconditionvector
initpower
type(initialpowerparams) modelparams::cambparams::initpower
ksign
real(dl) modelparams::cambparams::ksign
lambdac
real(dl) modelparams::cambparams::lambdac
massivenumethod
integer modelparams::cambparams::massivenumethod
max_eta_k
real(dl) modelparams::cambparams::max_eta_k
max_eta_k_tensor
real(dl) modelparams::cambparams::max_eta_k_tensor
max_l
integer modelparams::cambparams::max_l
max_l_tensor
integer modelparams::cambparams::max_l_tensor
nonlinear
integer modelparams::cambparams::nonlinear
nu_mass_degeneracies
real(dl), dimension(max_nu) modelparams::cambparams::nu_mass_degeneracies
nu_mass_eigenstates
integer modelparams::cambparams::nu_mass_eigenstates
nu_mass_fractions
real(dl), dimension(max_nu) modelparams::cambparams::nu_mass_fractions
nu_mass_numbers
integer, dimension(max_nu) modelparams::cambparams::nu_mass_numbers
num_nu_massive
integer modelparams::cambparams::num_nu_massive
num_nu_massless
real(dl) modelparams::cambparams::num_nu_massless
omegab
real(dl) modelparams::cambparams::omegab
Referenced by camb.model.CAMBparams::get_omega_k().
omegac
real(dl) modelparams::cambparams::omegac
Referenced by camb.model.CAMBparams::get_omega_k().
omegadgc
real(dl) modelparams::cambparams::omegadgc
omegak
real(dl) modelparams::cambparams::omegak
omegan
real(dl) modelparams::cambparams::omegan
Referenced by camb.model.CAMBparams::get_omega_k().
omegav
real(dl) modelparams::cambparams::omegav
Referenced by camb.model.CAMBparams::get_omega_k().
onlytransfers
logical modelparams::cambparams::onlytransfers
open
logical modelparams::cambparams::open
outputnormalization
integer modelparams::cambparams::outputnormalization
pk_wanttransfer
logical modelparams::cambparams::pk_wanttransfer
r
real(dl) modelparams::cambparams::r
recomb
type(recombinationparams) modelparams::cambparams::recomb
reion
type(reionizationparams) modelparams::cambparams::reion
reionhist
type(reionizationhistory) modelparams::cambparams::reionhist
rhor0
real(dl) modelparams::cambparams::rhor0
rsdrag
real(dl) modelparams::cambparams::rsdrag
scalar_initial_condition
integer modelparams::cambparams::scalar_initial_condition
share_delta_neff
logical modelparams::cambparams::share_delta_neff
tau0
real(dl) modelparams::cambparams::tau0
tcmb
real(dl) modelparams::cambparams::tcmb
transfer
type(transferparams) modelparams::cambparams::transfer
want_cmb
logical modelparams::cambparams::want_cmb
want_zdrag
logical modelparams::cambparams::want_zdrag
want_zstar
logical modelparams::cambparams::want_zstar
wantcls
logical modelparams::cambparams::wantcls
wantscalars
logical modelparams::cambparams::wantscalars
wanttensors
logical modelparams::cambparams::wanttensors
wanttransfer
logical modelparams::cambparams::wanttransfer
wantvectors
logical modelparams::cambparams::wantvectors
wde0
real(dl) modelparams::cambparams::wde0
wdgc
real(dl) modelparams::cambparams::wdgc
yhe
real(dl) modelparams::cambparams::yhe
The documentation for this type was generated from the following file:
/home/ealmaraz/software/cosmomc/bde/v3.1/camb/modules.f90