cosmomc_bde_v3p1: inifile::tnamevaluelist Type Reference
inifile::tnamevaluelist Type Reference
Public Attributes
integer count
integer delta
integer capacity
logical ignoreduplicates
type(tnamevalue_pointer), dimension(:), pointer items
Member Data Documentation
capacity
integer inifile::tnamevaluelist::capacity
count
integer inifile::tnamevaluelist::count
delta
integer inifile::tnamevaluelist::delta
ignoreduplicates
logical inifile::tnamevaluelist::ignoreduplicates
items
type(tnamevalue_pointer), dimension(:), pointer inifile::tnamevaluelist::items
Referenced by paramgrid.batchjob.batchJob::hasName(), paramgrid.batchjob.batchJob::makeItems(), paramgrid.batchjob.batchJob::normed_name_item(), and paramgrid.batchjob.batchJob::resolveRoot().
The documentation for this type was generated from the following file:
/home/ealmaraz/software/cosmomc/bde/v3.1/camb/inifile.f90