cosmomc_bde_v3p1: elementabundances::abundancelikelihood Type Reference
elementabundances::abundancelikelihood Type Reference
Private Member Functions
procedure readini => Abundance_ReadIni
procedure logliketheory => Abundance_LnLike
Private Attributes
character(len=:), allocatable measurement
class(tinterpgrid2d), pointer bbn_value
class(tinterpgrid2d), pointer bbn_error
real(mcp) mean
real(mcp) error
Member Function/Subroutine Documentation
logliketheory()
procedure elementabundances::abundancelikelihood::logliketheory () private
References elementabundances::abundancelikelihood_add().
readini()
procedure elementabundances::abundancelikelihood::readini () private
Member Data Documentation
bbn_error
class(tinterpgrid2d), pointer elementabundances::abundancelikelihood::bbn_error private
bbn_value
class(tinterpgrid2d), pointer elementabundances::abundancelikelihood::bbn_value private
error
real(mcp) elementabundances::abundancelikelihood::error private
mean
real(mcp) elementabundances::abundancelikelihood::mean private
Referenced by getdist.mcsamples.MCSamples::_setLikeStats(), getdist.chains.WeightedSamples::mean_diff(), and getdist.mcsamples.MCSamples::PCA().
measurement
character(len=:), allocatable elementabundances::abundancelikelihood::measurement private
The documentation for this type was generated from the following file:
/home/ealmaraz/software/cosmomc/bde/v3.1/source/ElementAbundances.f90