cosmomc_bde_v3p1: iniobjects::tnamevaluelist Type Reference
iniobjects::tnamevaluelist Type Reference
Private Member Functions
procedure init => TNameValueList_Init
procedure clear => TNameValueList_Clear
procedure valueof => TNameValueList_ValueOf
procedure indexof => TNameValueList_IndexOf
procedure haskey => TNameValueList_HasKey
procedure setcapacity => TNameValueList_SetCapacity
procedure delete => TNameValueList_Delete
procedure error => TNameValueList_Error
procedure failstop => TNameValueList_FailStop
procedure addstring => TNameValueList_Add
procedure name => TNameValueList_Value
procedure override => TNameValueList_Override
procedure tnamevaluelist_adddouble
procedure tnamevaluelist_addreal
procedure tnamevaluelist_addint
procedure tnamevaluelist_addlogical
generic add => AddString, TNameValueList_AddDouble, TNameValueList_AddReal, TNameValueList_AddInt, TNameValueList_AddLogical
final tnamevaluelist_free
Private Attributes
integer count = 0
integer delta = 128
integer capacity = 0
logical ignoreduplicates = .false.
logical allowduplicatekeys = .false.
type(tnamevalue_pointer), dimension(:), allocatable items
Member Function/Subroutine Documentation
add()
generic iniobjects::tnamevaluelist::add () private
References iniobjects::tnamevaluelist_adddouble(), iniobjects::tnamevaluelist_addint(), iniobjects::tnamevaluelist_addlogical(), and iniobjects::tnamevaluelist_addreal().
addstring()
procedure iniobjects::tnamevaluelist::addstring () private
clear()
procedure iniobjects::tnamevaluelist::clear () private
delete()
procedure iniobjects::tnamevaluelist::delete () private
error()
procedure iniobjects::tnamevaluelist::error () private
failstop()
procedure iniobjects::tnamevaluelist::failstop () private
haskey()
procedure iniobjects::tnamevaluelist::haskey () private
indexof()
procedure iniobjects::tnamevaluelist::indexof () private
init()
procedure iniobjects::tnamevaluelist::init () private
name()
procedure iniobjects::tnamevaluelist::name () private
override()
procedure iniobjects::tnamevaluelist::override () private
setcapacity()
procedure iniobjects::tnamevaluelist::setcapacity () private
tnamevaluelist_adddouble()
procedure iniobjects::tnamevaluelist::tnamevaluelist_adddouble () private
tnamevaluelist_addint()
procedure iniobjects::tnamevaluelist::tnamevaluelist_addint () private
tnamevaluelist_addlogical()
procedure iniobjects::tnamevaluelist::tnamevaluelist_addlogical () private
tnamevaluelist_addreal()
procedure iniobjects::tnamevaluelist::tnamevaluelist_addreal () private
tnamevaluelist_free()
final iniobjects::tnamevaluelist::tnamevaluelist_free () final private
References iniobjects::tnamevaluelist_free().
valueof()
procedure iniobjects::tnamevaluelist::valueof () private
Member Data Documentation
allowduplicatekeys
logical iniobjects::tnamevaluelist::allowduplicatekeys = .false. private
capacity
integer iniobjects::tnamevaluelist::capacity = 0 private
count
integer iniobjects::tnamevaluelist::count = 0 private
delta
integer iniobjects::tnamevaluelist::delta = 128 private
ignoreduplicates
logical iniobjects::tnamevaluelist::ignoreduplicates = .false. private
items
type(tnamevalue_pointer), dimension(:), allocatable iniobjects::tnamevaluelist::items private
Referenced by paramgrid.batchjob.batchJob::hasName(), paramgrid.batchjob.batchJob::makeItems(), paramgrid.batchjob.batchJob::normed_name_item(), and paramgrid.batchjob.batchJob::resolveRoot().
The documentation for this type was generated from the following file:
/home/ealmaraz/software/cosmomc/bde/v3.1/source/IniObjects.f90