cosmomc_bde_v3p1: interpolation::tcubicspline Type Reference
interpolation::tcubicspline Type Reference
Public Member Functions
procedure initfromfile => TCubicSpline_InitFromFile
procedure initforsize => TCubicSpline_InitForSize
procedure initinterp => TCubicSpline_InitInterp
procedure clear => TCubicSpline_Clear
procedure findnext => TCubicSpline_FindNext
procedure loadstate => TCubicSpline_LoadState
procedure savestate => TCubicSpline_SaveState
generic init => TCubicSpline_Init, TCubicSpline_InitInt
FINAL tcubicspline_free
Public Attributes
real(sp_acc), dimension(:), allocatable x
Private Member Functions
procedure, nopass, private spline
procedure, private tcubicspline_init
procedure, private tcubicspline_initint
Member Function/Subroutine Documentation
clear()
procedure interpolation::tcubicspline::clear ()
findnext()
procedure interpolation::tcubicspline::findnext ()
init()
generic interpolation::tcubicspline::init ()
References interpolation::tcubicspline_init(), and interpolation::tcubicspline_initint().
initforsize()
procedure interpolation::tcubicspline::initforsize ()
initfromfile()
procedure interpolation::tcubicspline::initfromfile ()
initinterp()
procedure interpolation::tcubicspline::initinterp ()
loadstate()
procedure interpolation::tcubicspline::loadstate ()
savestate()
procedure interpolation::tcubicspline::savestate ()
spline()
procedure, nopass, private interpolation::tcubicspline::spline () private
tcubicspline_free()
FINAL interpolation::tcubicspline::tcubicspline_free () final
References interpolation::tcubicspline_free().
tcubicspline_init()
procedure, private interpolation::tcubicspline::tcubicspline_init () private
tcubicspline_initint()
procedure, private interpolation::tcubicspline::tcubicspline_initint () private
Member Data Documentation
x
real(sp_acc), dimension(:), allocatable interpolation::tcubicspline::x
The documentation for this type was generated from the following file:
/home/ealmaraz/software/cosmomc/bde/v3.1/source/Interpolation.f90