cosmomc_bde_v3p1: fileutils::tfile Type Reference
fileutils::tfile Type Reference
Private Member Functions
procedure, nopass txtnumbercolumns
procedure, nopass txtcolumns
procedure, nopass txtfilecolumns
procedure, nopass txtfilelines
procedure, nopass lasttopcomment
procedure, nopass topcommentline
procedure, nopass lastline => LastFileLine
procedure, nopass size => FileSize
procedure, nopass exists => FileExists
procedure, nopass extractname => ExtractFileName
procedure, nopass extractpath => ExtractFilePath
procedure, nopass join => File_Join
procedure, nopass changeext => ChangeFileExt
procedure, nopass checktrailingslash
procedure, nopass isfullpath
procedure, nopass extractext => ExtractFileExt
procedure, nopass delete => DeleteFile
procedure, nopass readtextmatrix
procedure, nopass readtextvector
procedure, nopass writetextmatrix
procedure, nopass writetextvector
procedure, nopass loadtxt_1d
procedure, nopass loadtxt_2d
procedure, nopass opentextfile
procedure, nopass createtextfile
procedure, nopass charisslash
generic loadtxt => LoadTxt_2D, LoadTxt_1D
generic savetxt => WriteTextMatrix, WriteTextVector
Member Function/Subroutine Documentation
changeext()
procedure, nopass fileutils::tfile::changeext () private
charisslash()
procedure, nopass fileutils::tfile::charisslash () private
checktrailingslash()
procedure, nopass fileutils::tfile::checktrailingslash () private
createtextfile()
procedure, nopass fileutils::tfile::createtextfile () private
delete()
procedure, nopass fileutils::tfile::delete () private
exists()
procedure, nopass fileutils::tfile::exists () private
extractext()
procedure, nopass fileutils::tfile::extractext () private
extractname()
procedure, nopass fileutils::tfile::extractname () private
extractpath()
procedure, nopass fileutils::tfile::extractpath () private
isfullpath()
procedure, nopass fileutils::tfile::isfullpath () private
join()
procedure, nopass fileutils::tfile::join () private
lastline()
procedure, nopass fileutils::tfile::lastline () private
lasttopcomment()
procedure, nopass fileutils::tfile::lasttopcomment () private
loadtxt()
generic fileutils::tfile::loadtxt () private
References fileutils::loadtxt_1d(), and fileutils::loadtxt_2d().
loadtxt_1d()
procedure, nopass fileutils::tfile::loadtxt_1d () private
loadtxt_2d()
procedure, nopass fileutils::tfile::loadtxt_2d () private
opentextfile()
procedure, nopass fileutils::tfile::opentextfile () private
readtextmatrix()
procedure, nopass fileutils::tfile::readtextmatrix () private
readtextvector()
procedure, nopass fileutils::tfile::readtextvector () private
savetxt()
generic fileutils::tfile::savetxt () private
References fileutils::writetextmatrix(), and fileutils::writetextvector().
size()
procedure, nopass fileutils::tfile::size () private
Referenced by getdist.gui.mainwindow.MainWindow::writeSettings().
topcommentline()
procedure, nopass fileutils::tfile::topcommentline () private
txtcolumns()
procedure, nopass fileutils::tfile::txtcolumns () private
txtfilecolumns()
procedure, nopass fileutils::tfile::txtfilecolumns () private
txtfilelines()
procedure, nopass fileutils::tfile::txtfilelines () private
txtnumbercolumns()
procedure, nopass fileutils::tfile::txtnumbercolumns () private
writetextmatrix()
procedure, nopass fileutils::tfile::writetextmatrix () private
writetextvector()
procedure, nopass fileutils::tfile::writetextvector () private
The documentation for this type was generated from the following file:
/home/ealmaraz/software/cosmomc/bde/v3.1/source/FileUtils.f90