cosmomc_bde_v3p1: camb::cambdata Type Reference
camb::cambdata Type Reference
Public Attributes
type(cltransferdata) cltransscal
type(cltransferdata) cltranstens
type(cltransferdata) cltransvec
type(mattertransferdata) mtrans
type(cambparams) params
Member Data Documentation
cltransscal
type (cltransferdata) camb::cambdata::cltransscal
cltranstens
type (cltransferdata) camb::cambdata::cltranstens
cltransvec
type (cltransferdata) camb::cambdata::cltransvec
mtrans
type (mattertransferdata) camb::cambdata::mtrans
params
type (cambparams) camb::cambdata::params
Referenced by paramgrid.batchjob.dataSet::add(), getdist.inifile.IniFile::asType(), iniFile.iniFile::bool(), getdist.inifile.IniFile::bool(), iniFile.iniFile::delete_keys(), getdist.inifile.IniFile::delete_keys(), iniFile.iniFile::fileLines(), getdist.inifile.IniFile::fileLines(), iniFile.iniFile::float(), getdist.inifile.IniFile::getAttr(), getdist.inifile.IniFile::hasKey(), iniFile.iniFile::int(), getdist.inifile.IniFile::isSet(), iniFile.iniFile::readFile(), getdist.inifile.IniFile::readFile(), iniFile.iniFile::replaceTags(), getdist.inifile.IniFile::replaceTags(), getdist.inifile.IniFile::split(), and iniFile.iniFile::string().
The documentation for this type was generated from the following file:
/home/ealmaraz/software/cosmomc/bde/v3.1/camb/camb.f90