cosmomc_bde_v3p1: iniobjects::tinifile Type Reference
iniobjects::tinifile Type Reference
Private Member Functions
procedure open => Ini_Open
procedure open_fromlines => Ini_Open_Fromlines
procedure close => Ini_Close
procedure read_string => Ini_Read_String
procedure read_string_default => Ini_Read_String_Default
procedure read_string_array => Ini_Read_String_Array
procedure read_int_array => Ini_Read_Int_Array
procedure read_int => Ini_Read_Int
procedure read_double => Ini_Read_Double
procedure read_double_array => Ini_Read_Double_Array
procedure read_real => Ini_Read_Real
procedure read_real_array => Ini_Read_Real_Array
procedure read_logical => Ini_Read_Logical
procedure read_enumeration => Ini_Read_Enumeration
procedure read_enumeration_list => Ini_Read_Enumeration_List
procedure testequal => Ini_TestEqual
procedure savereadvalues => Ini_SaveReadValues
procedure key_to_arraykey => Ini_Key_To_Arraykey
procedure enumerationvalue => Ini_EnumerationValue
procedure resolvelinkedfile => Ini_ResolveLinkedFile
procedure expandenvironment => Ini_ExpandEnvironment
procedure, private namevalue_addline => Ini_NameValue_AddLine
procedure, private emptycheckdefault => Ini_EmptyCheckDefault
procedure, private ini_read_real_change
procedure, private ini_read_double_change
procedure, private ini_read_int_change
procedure, private ini_read_logical_change
procedure, private ini_read_string_change
generic read => Ini_Read_Real_Change, Ini_Read_Double_Change, Ini_Read_Int_Change, Ini_Read_Logical_Change, Ini_Read_String_Change
Private Attributes
logical slashcomments = .false.
logical echo_read = .false.
logical fail_on_not_found = .false.
logical expandenvironmentvariables = .true.
character(len=:), allocatable original_filename
type(tnamevaluelist) readvalues
Member Function/Subroutine Documentation
close()
procedure iniobjects::tinifile::close () private
emptycheckdefault()
procedure, private iniobjects::tinifile::emptycheckdefault () private
enumerationvalue()
procedure iniobjects::tinifile::enumerationvalue () private
expandenvironment()
procedure iniobjects::tinifile::expandenvironment () private
ini_read_double_change()
procedure, private iniobjects::tinifile::ini_read_double_change () private
ini_read_int_change()
procedure, private iniobjects::tinifile::ini_read_int_change () private
ini_read_logical_change()
procedure, private iniobjects::tinifile::ini_read_logical_change () private
ini_read_real_change()
procedure, private iniobjects::tinifile::ini_read_real_change () private
ini_read_string_change()
procedure, private iniobjects::tinifile::ini_read_string_change () private
key_to_arraykey()
procedure iniobjects::tinifile::key_to_arraykey () private
namevalue_addline()
procedure, private iniobjects::tinifile::namevalue_addline () private
open()
procedure iniobjects::tinifile::open () private
open_fromlines()
procedure iniobjects::tinifile::open_fromlines () private
read()
generic iniobjects::tinifile::read () private
References iniobjects::ini_enumeration_len, iniobjects::ini_read_double_change(), iniobjects::ini_read_int_change(), iniobjects::ini_read_logical_change(), iniobjects::ini_read_real_change(), and iniobjects::ini_read_string_change().
read_double()
procedure iniobjects::tinifile::read_double () private
read_double_array()
procedure iniobjects::tinifile::read_double_array () private
read_enumeration()
procedure iniobjects::tinifile::read_enumeration () private
read_enumeration_list()
procedure iniobjects::tinifile::read_enumeration_list () private
read_int()
procedure iniobjects::tinifile::read_int () private
read_int_array()
procedure iniobjects::tinifile::read_int_array () private
read_logical()
procedure iniobjects::tinifile::read_logical () private
read_real()
procedure iniobjects::tinifile::read_real () private
read_real_array()
procedure iniobjects::tinifile::read_real_array () private
read_string()
procedure iniobjects::tinifile::read_string () private
read_string_array()
procedure iniobjects::tinifile::read_string_array () private
read_string_default()
procedure iniobjects::tinifile::read_string_default () private
resolvelinkedfile()
procedure iniobjects::tinifile::resolvelinkedfile () private
savereadvalues()
procedure iniobjects::tinifile::savereadvalues () private
testequal()
procedure iniobjects::tinifile::testequal () private
Member Data Documentation
echo_read
logical iniobjects::tinifile::echo_read = .false. private
expandenvironmentvariables
logical iniobjects::tinifile::expandenvironmentvariables = .true. private
fail_on_not_found
logical iniobjects::tinifile::fail_on_not_found = .false. private
original_filename
character(len=:), allocatable iniobjects::tinifile::original_filename private
readvalues
type(tnamevaluelist) iniobjects::tinifile::readvalues private
slashcomments
logical iniobjects::tinifile::slashcomments = .false. private
The documentation for this type was generated from the following file:
/home/ealmaraz/software/cosmomc/bde/v3.1/source/IniObjects.f90