cosmomc_bde_v3p1: objectlists::tobjectlist Type Reference
objectlists::tobjectlist Type Reference
Private Member Functions
procedure addarray
procedure additem
procedure additempointer
procedure addcopy
procedure assignpointers
procedure deleteitem
procedure deleterange
procedure freeitem
procedure setcapacity
procedure arrayitem
procedure arrayitemindex
procedure savebinary
procedure readbinary
procedure thin
procedure sort
procedure sortarr
procedure swap
procedure compare
procedure clear
procedure deltasize
procedure quicksort
procedure quicksortarr
procedure removeduplicates
procedure checkindex
procedure error
procedure savestate => TObjectList_SaveState
procedure loadstate => TObjectList_LoadState
procedure object => TObjectList_Object
FINAL finalize
generic add => AddItem, AddArray
Private Attributes
integer count =0
integer delta = 32
integer deltascale = 10
integer capacity = 0
logical ownsobjects = .true.
type(object_pointer), dimension(:), allocatable items
Member Function/Subroutine Documentation
add()
generic objectlists::tobjectlist::add () private
References objectlists::addarray(), and objectlists::additem().
addarray()
procedure objectlists::tobjectlist::addarray () private
addcopy()
procedure objectlists::tobjectlist::addcopy () private
additem()
procedure objectlists::tobjectlist::additem () private
additempointer()
procedure objectlists::tobjectlist::additempointer () private
arrayitem()
procedure objectlists::tobjectlist::arrayitem () private
arrayitemindex()
procedure objectlists::tobjectlist::arrayitemindex () private
assignpointers()
procedure objectlists::tobjectlist::assignpointers () private
checkindex()
procedure objectlists::tobjectlist::checkindex () private
clear()
procedure objectlists::tobjectlist::clear () private
compare()
procedure objectlists::tobjectlist::compare () private
deleteitem()
procedure objectlists::tobjectlist::deleteitem () private
deleterange()
procedure objectlists::tobjectlist::deleterange () private
deltasize()
procedure objectlists::tobjectlist::deltasize () private
error()
procedure objectlists::tobjectlist::error () private
finalize()
FINAL objectlists::tobjectlist::finalize () final private
References objectlists::finalize().
freeitem()
procedure objectlists::tobjectlist::freeitem () private
loadstate()
procedure objectlists::tobjectlist::loadstate () private
object()
procedure objectlists::tobjectlist::object () private
quicksort()
procedure objectlists::tobjectlist::quicksort () private
quicksortarr()
procedure objectlists::tobjectlist::quicksortarr () private
readbinary()
procedure objectlists::tobjectlist::readbinary () private
removeduplicates()
procedure objectlists::tobjectlist::removeduplicates () private
savebinary()
procedure objectlists::tobjectlist::savebinary () private
savestate()
procedure objectlists::tobjectlist::savestate () private
setcapacity()
procedure objectlists::tobjectlist::setcapacity () private
sort()
procedure objectlists::tobjectlist::sort () private
sortarr()
procedure objectlists::tobjectlist::sortarr () private
swap()
procedure objectlists::tobjectlist::swap () private
thin()
procedure objectlists::tobjectlist::thin () private
Member Data Documentation
capacity
integer objectlists::tobjectlist::capacity = 0 private
count
integer objectlists::tobjectlist::count =0 private
delta
integer objectlists::tobjectlist::delta = 32 private
deltascale
integer objectlists::tobjectlist::deltascale = 10 private
items
type(object_pointer), dimension(:), allocatable objectlists::tobjectlist::items private
Referenced by paramgrid.batchjob.batchJob::hasName(), paramgrid.batchjob.batchJob::makeItems(), paramgrid.batchjob.batchJob::normed_name_item(), and paramgrid.batchjob.batchJob::resolveRoot().
ownsobjects
logical objectlists::tobjectlist::ownsobjects = .true. private
The documentation for this type was generated from the following file:
/home/ealmaraz/software/cosmomc/bde/v3.1/source/ObjectLists.f90