cosmomc_bde_v3p1: inifile::tinifile Type Reference
inifile::tinifile Type Reference
Public Attributes
logical slashcomments
type(tnamevaluelist) l
type(tnamevaluelist) readvalues
Member Data Documentation
l
type (tnamevaluelist) inifile::tinifile::l
Referenced by cambPlots.ClResult::compare_array_acc(), cambPlots.ClResult::compare_type_tol(), and cambPlots.ClResult::set_lensedcl().
readvalues
type (tnamevaluelist) inifile::tinifile::readvalues
slashcomments
logical inifile::tinifile::slashcomments
The documentation for this type was generated from the following file:
/home/ealmaraz/software/cosmomc/bde/v3.1/camb/inifile.f90