cosmomc_bde_v3p1: inifile::tnamevalue Type Reference
inifile::tnamevalue Type Reference
Public Attributes
character(ini_max_name_len) name
character(ini_max_string_len) value
Member Data Documentation
name
character(ini_max_name_len) inifile::tnamevalue::name
Referenced by getdist.types.MargeStats::__str__(), getdist.types.LikeStats::__str__(), getdist.paramnames.ParamInfo::getLabel(), paramgrid.batchjob.jobItem::hasConvergeBetterThan(), paramgrid.batchjob.jobItem::iniFile(), getdist.paramnames.ParamInfo::latexLabel(), paramgrid.batchjob.jobItem::makeImportance(), and getdist.paramnames.ParamInfo::string().
value
character(ini_max_string_len) inifile::tnamevalue::value
The documentation for this type was generated from the following file:
/home/ealmaraz/software/cosmomc/bde/v3.1/camb/inifile.f90