cosmomc_bde_v3p1: /home/ealmaraz/software/cosmomc/bde/v3.1/camb/subroutines.f90 File Reference
subroutines.f90 File Reference
Functions/Subroutines
subroutine splder (y, dy, n, g)
subroutine splini (g, n)
real(dl) function rombint2 (f, a, b, tol, maxit, minsteps)
real(dl) function rombint (f, a, b, tol)
real(dl) function rombint_obj (obj, f, a, b, tol, maxit)
subroutine spline (x, y, n, d11, d1n, d2)
subroutine spline_deriv (x, y, y2, y1, n)
subroutine spline_integrate (x, y, y2, yint, n)
subroutine splint (y, z, n)
subroutine dverk (EV, n, fcn, x, y, xend, tol, ind, c, nw, w)
real(dl) function newton_raphson (xxl, xxh, funcs, param, param2)
Function/Subroutine Documentation
dverk()
subroutine dverk (real EV, integer n, external fcn, real(dl) x, real(dl), dimension(n) y, real(dl) xend, real(dl) tol, integer ind, real(dl), dimension(*) c, integer nw, real(dl), dimension(nw,9) w)
Referenced by cambmain::calcscalarsources(), cambmain::calcvectorsources(), power_sz::delta(), dtauda(), gaugeinterface::gaugeinterface_evolvetens(), gaugeinterface::gaugeinterface_scalev(), and recombination::recombination_init().
newton_raphson()
real(dl) function newton_raphson (real(dl), intent(in) xxl, real(dl), intent(in) xxh, external funcs, real(dl), intent(in) param, real(dl), intent(in) param2)
rombint()
real(dl) function rombint (external f, real(dl), intent(in) a, real(dl), intent(in) b, real(dl), intent(in) tol)
Referenced by power_sz::delta(), thermodata::inithermo(), and cosmology::r().
rombint2()
real(dl) function rombint2 (external f, real(dl), intent(in) a, real(dl), intent(in) b, real(dl), intent(in) tol, integer, intent(in) maxit, integer, intent(in) minsteps)
Referenced by thermodata::dragoptdepth(), and thermodata::optdepth().
rombint_obj()
real(dl) function rombint_obj (real obj, external f, real(dl), intent(in) a, real(dl), intent(in) b, real(dl), intent(in) tol, integer, intent(in), optional maxit)
splder()
subroutine splder (real(dl), dimension(n), intent(in) y, real(dl), dimension(n), intent(out) dy, integer, intent(in) n, real(dl), dimension(n), intent(in) g)
Referenced by thermodata::getbackgroundevolution(), thermodata::inithermo(), and massivenu::nu_init().
spline()
subroutine spline (real(dl), dimension(n), intent(in) x, real(dl), dimension(n), intent(in) y, integer, intent(in) n, real(dl), intent(in) d11, real(dl), intent(in) d1n, real(dl), dimension(n), intent(out) d2)
Referenced by quint::bde_background(), quint::bde_nxyl(), lensing::corrfuncfullskyimpl(), cosmologyparameterizations::cosmomc_nxyl(), samples::density1d_initspline(), spherbessels::generatebessels(), lensing::getbessels(), cambmain::initsourceinterpolation(), lvalues::interpolateclarr(), cambmain::interpolatesources(), lambdageneral::interpolrde(), recombination::kappa_hh_21cm(), recombination::kappa_ph_21cm(), cambmain::makenonlinearsources(), transfer::matterpowerdata_getsplines(), recombination::recombination_init(), lambdageneral::setddwa(), interpolation::tcubicspline_initinterp(), lrggettheory::transfer_getmatterpowerandnw(), and transfer::transfer_getmatterpowerd().
spline_deriv()
subroutine spline_deriv (real(dl), dimension(n), intent(in) x, real(dl), dimension(n), intent(in) y, real(dl), dimension(n), intent(in) y2, real(dl), dimension(n), intent(out) y1, integer, intent(in) n)
spline_integrate()
subroutine spline_integrate (real(dl), dimension(n), intent(in) x, real(dl), dimension(n), intent(in) y, real(dl), dimension(n), intent(in) y2, real(dl), dimension(n), intent(out) yint, integer, intent(in) n)
splini()
subroutine splini (real(dl), dimension(n), intent(out) g, integer, intent(in) n)
Referenced by thermodata::getbackgroundevolution(), thermodata::inithermo(), and massivenu::nu_init().
splint()
subroutine splint (real(dl), dimension(n), intent(in) y, real(dl), intent(out) z, integer, intent(in) n)
Referenced by massivenu::nurhopres().